### ISSUE TITLE
Haxe 4.2.0 dev: Macro functions must be called immediately

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#10025]
Today I tested a couple development builds (from today, Nov, and July) against our large project, and they all exhibit a new error (since 4.1.4, which works):

```
.hx:40: characters 5-55 : Macro functions must be called immediately
.hx:40: characters 5-55 : Invalid macro access
.hx:41: characters 5-61 : Macro functions must be called immediately
.hx:41: characters 5-61 : Invalid macro access
...
```

Which is weird, because the functions in question are not macro functions... :raised_eyebrow: Actually, one of the offending lines is of the form:

```
  instance.macro_function(foo, bar, callback_function);
```

The `macro_function` is a `public macro function` member of a class, being passed a (non-macro) `callback_function` expression, which of course, isn't invoked immediately. So it's being incorrectly flagged as a macro function that's not being called immediately.

**Comment by RealyUniqueName** [comment]
Any chance for a small reproducible sample?

**Comment by jcward** [comment]
Yeah, I'm trying to make one...

**Comment by jcward** [comment]
Hmm, the small testcase doesn't reproduce. Well, perhaps I'll slog through this (and a number of other little changes) the next time we try to update our Haxe build.

**Comment by Simn** [comment]
I'm quite curious about this because I did change some related internals. A non-macro function being considered a macro function does not seem possible, but then again who knows what's possible and what's not...

I wonder if we somehow end up creating a temporary variable for `instance.macro_function` and then try to call that. I don't really know which part of the compiler could do this, but it's the only potential cause I can think of right now.

**Comment by RealyUniqueName** [comment]
Removed from "Release 4.2" milestone because we don't know how to reproduce.

**Comment by Simn** [comment]
Oh well, if anyone ever finds a reproducible example of this we can reopen the issue.
