### ISSUE TITLE
4.2 – hxcpp Native.star generates incorrect syntax

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#10057]
In haxe 4.1, `cpp.Native.star(ident)` generates `(*(ident))`, in latest development it generates `(*((*(ident))))` causes hxcpp compile to fail with "indirection requires pointer operand". Internally this operation is `CppDereference` in gencpp.ml

(this affects a number of other calls that rely on cpp.Native.star)

Example code
[haxe-10057.zip](https://github.com/HaxeFoundation/haxe/files/5789632/haxe-10057.zip)

Bisected to b0c8b5b2113cc2e53c09ce415f3334e6a76462de (if I take development and revert this commit the issue is resolved)

Specific line that introduces this: https://github.com/HaxeFoundation/haxe/commit/b0c8b5b2113cc2e53c09ce415f3334e6a76462de#r45782386

**Comment by vonagam** [comment]
Looked into it.

`Native.star` [has](https://github.com/HaxeFoundation/haxe/blob/18fdc8c39249b8eda8c29291157679a6a0ac1c6a/std/cpp/Native.hx#L42-L43) `@:native("::hx::Dereference")` meta.

This is used [here](https://github.com/HaxeFoundation/haxe/blob/18fdc8c39249b8eda8c29291157679a6a0ac1c6a/src/generators/gencpp.ml#L2717-L2719), which adds `Dereference` but (if i see correctly) does not change a resulted expression's type. So the generator still thinks that it is a pointer, that's why it adds another dereference later for implicit cast to reference (which happens in assignment in your demo).

So the revealed problem here is wrong typing of `Native.star`.

**Comment by haxiomic** [comment]
Aye, one a fix might be to change `Native.star` to
```haxe
static inline function star<T>(ptr:cpp.Star<T>):cpp.Reference<T> return ptr;
```
And let the new auto cast do the deref

**Comment by vonagam** [comment]
Yeah, that might be better idea, but to minimise changes just fixed the typing of `::hx::Dereference`.
