### ISSUE TITLE
[eval] error: { field : String, expr : haxe.macro.Expr } has no field quotes

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#10092]
code from [here](https://code.haxe.org/category/macros/combine-objects.html)

haxe version :4.1.5 and nightly build

![image](https://user-images.githubusercontent.com/748320/106098093-69420600-6173-11eb-81bb-38f6ff787730.png)

**Comment by kLabz** [comment]
`EObjectDecl` doesn't work well with type inference since haxe 4 and the addition of the optional `quotes` field. Your code should work if you use `ObjectField` instead of an anonymous structure (use `Map<String, ObjectField>`).

If you need haxe 3.4.x compatibility, you can add this:
```hx
#if !haxe4
typedef ObjectField = { field:String, expr:Expr }
#end
```
_(with haxe 4, `ObjectField` will be imported with `haxe.macro.Expr`)_

**Comment by sonygod** [comment]
https://github.com/hkssprangers/hkssprangers/blob/c39c5a8a58730c00095367fff9a5b3e9543c200a/src/hkssprangers/ObjectTools.hx
