### ISSUE TITLE
Operator overload for calling an abstract

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#10119]
As discussed, let's allow overloading the "call" operator in abstracts, similar to overload resolution:

```haxe
abstract Foo(Bar) {
  @:op(a()) function callNoArgs():Void {}
  @:op(a()) function callOneArg(x:Int):Void {}
}
```

**Comment by Simn** [comment]
I have delayed generic expansion until after we have resolved overloads. This never came up before because our overloads are always extern or inline, both of which don't work with `@:generic`. With the change the following works:

```haxe
abstract Foo(String) {
	@:op(a()) function callNoArgs():Void {}

	@:op(a()) @:generic function callOneArg<T>(x:T):Void {}

	@:op(a()) function callTwoArgs(i:Int, s:String) {}
}

function main() {
	var foo:Foo = null;
	foo();
	foo(12);
	foo("foo");
	foo(12, "foo");
}
```

Generated JS:

```js
Foo.callOneArg_String = function(this1,x) {
};
Foo.callOneArg_Int = function(this1,x) {
};
Foo.callNoArgs = function(this1) {
};
Foo.callTwoArgs = function(this1,i,s) {
};
function Main_main() {
	var foo = null;
	Foo.callNoArgs(foo);
	Foo.callOneArg_Int(foo,12);
	Foo.callOneArg_String(foo,"foo");
	Foo.callTwoArgs(foo,12,"foo");
}
```

I can think of two more problems to solve:

1. Macros. I think we can allow macros here, but that requires a few limitations:
    1. We definitely cannot allow the combination of macros and non-macros because we don't type arguments, so we cannot resolve overloads.
    2. For the same reason, we cannot support proper macro overloads. However, we _could_ overload by-arity because that's independent of the actual types. The only concern then is the combination with `Rest`. I'm not quite sure if this is worth the effort. Alternatively, we could allow only a single macro `@:op(a())` per abstract, but that seems a bit cheap...
2. IDE support: With the conflation of the abstract and one of its fields in syntax, it's not clear what hovering and goto-definition should do exactly. Technically, the abstract is just the abstract, but that doesn't seem very useful in practice. It would be nice if the IDE told us which overload is being used at a given call-site, but I don't know how that would be queried and shown.

**Comment by player-03** [comment]
Isn't this done?

**Comment by Simn** [comment]
My last comment suggests that there were some open questions, but I guess those weren't very important!
