### ISSUE TITLE
Haxe 4.2 Threads and loops

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10114]
There is to be several issues with Haxe 4.2 Threads and event loops, see 
https://github.com/HeapsIO/heaps/pull/927

There's some things I'm not I understand, such as why MainLoop.tick() no longer process timers ?
ATM Heaps is broken by Haxe 4.2 so it's not a very good situation...

**Comment by ncannasse** [comment]
One of the problem seems to be the inability to have classes that register their own loops without having to be explicitely initialized.

The following used to work on Hashlink/JS targets (and we designed to):

```
static function __init__() {
   haxe.MainLoop.add(customLoop);
}
```

I guess it's a bit target specific, but the following should definitely work but it seems to crash:

```
static var init = haxe.MainLoop.add(customLoop);
```

**Comment by Yanrishatum** [comment]
This still seems to be not fixed:
https://github.com/HeapsIO/heaps/pull/933
https://github.com/HaxeFoundation/hashlink/issues/447

**Comment by RealyUniqueName** [comment]
The only potential issue I see is if this 
https://github.com/HeapsIO/heaps/blob/master/hxd/System.hl.hx#L423-L425
is executed before this:
https://github.com/HaxeFoundation/haxe/blob/bf9ff69c0801082174f0b2b0a66faeb5356de580/std/hl/_std/sys/thread/Thread.hx#L74-L80
which could happen because the order of `__init__` functions execution is not specified.

Other than that HeapsIO/heaps#933 looks like it should do the trick, because Haxe sorts static fields initialization by dependencies of their expressions. That means `haxe.MainLoop.mutex` should be initialized prior to `hxd.System._`.

**Comment by Yanrishatum** [comment]
Well, I would expect `__init__` ordering to be treated the same way. :) But I suppose it's harder to implement?
