### ISSUE TITLE
abstract class vs final

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#10139]
Can/should the following be allowed?

```haxe
abstract class A { // This class has uninitialized final vars, which requires a constructor
	final x:Int; // Example of an uninitialized final var
}

class B extends A {
	public function new() {
		x = 10; // Cannot access field or identifier x for writing
	}
}
```

**Comment by Simn** [comment]
So the part where we allow this is easy, but one thing we also have to do is check that the assignment actually takes place. That's a bit more involved because we don't really keep this kind of information around after type-building. I think we can mark such fields with a flag, but we do have to browse the hierarchy and consider potential intermediate classes that initialize things.

I'll just make the commit that allows this now and deal with the additional check some other time.

**Comment by Simn** [comment]
It's a bit concerning that this broke only a single test, but oh well...
