### ISSUE TITLE
reflect call method issue with rest function arguments

### ISSUE THREAD

**Issue by PXshadow** [HaxeFoundation/haxe#10196]
```haxe
function main() {
  test("hello","world"); //this works
  Reflect.callMethod(null,test,["hello","world"]); //this errors on hl/eval/neko and works on js
}

function test(...args:String) {
  trace(args[0]);
}
```
On hashlink:  ```Can't cast String to hl.types.ArrayDyn```
Seems to be caused by a diffrence in haxe.Rest at compile time.

**Comment by Simn** [comment]
I don't think that could work in the general because you're passing an array, which is not the same as rest arguments.

**Comment by Simn** [comment]
Uhm, disregard that, I somehow thought that the signature of `callMethod` was also using rest arguments.

**Comment by RealyUniqueName** [comment]
I don't think we can fix this. On some targets rest arguments are implemented on the compiler level. Compiler generates an array declaration for such arguments.
So, at compile time your sample actually becomes this:
```haxe
function main() {
  test(["hello","world"]); 
  Reflect.callMethod(null,test,["hello","world"]);
}

function test(args:Array<String>) {
  trace(args[0]);
}
```
As you can see to make it work you need to wrap `["hello","world"]` in an additional array declaration.

Unfortunately reflection can't do that automatically for you because it can't detect if the method has rest arguments.

**Comment by PXshadow** [comment]
That makes sense @RealyUniqueName in that case I'll close this and work on another way to achieve this. I appreciate you looking into it 🙂
