### ISSUE TITLE
Build and offer binaries for Apple Silicon

### ISSUE THREAD

**Issue by tyrondis** [HaxeFoundation/haxe#10190]
According to the authors of [asdf-haxe](https://github.com/asdf-community/asdf-haxe), https://github.com/asdf-community/asdf-haxe/issues/14 is currently blocked due to Haxe not offering Apple Silicon / M1 binaries for download. I wasn't able to find an issue for it yet, is this something the team is planning to do?

**Comment by smorimoto** [comment]
The problem here is that GitHub doesn't offer a Apple Silicon runner. Also, the runner client is currently written in C#, which (.NET) only supports Apple Silicon in beta release. So there are two problems here:

1. GitHub doesn't offer a Apple Silicon runner
2. The runner doesn't work with Apple Silicon in the first place

We can build it manually and add it to the release asset. In that case, I have experience with both OCaml and Haxe, so I think I can help you all. Or the official team can use services like Cirrus CI (They are one of the few services that has a runner client with Apple Silicon support.) with Scaleway (As far as I know, they are one of the cheapest and most stable providers of Apple Silicon machines.) to build it. In any case, it's not that easy, at least for the very moment.

**Comment by meadowsys** [comment]
I believe you can still build for an Apple Silicon target regardless of if the host machine is x86, so Github not offering an Apple Silicon runner isn't an issue I think

**Comment by barisyild** [comment]
I think Github offering an Apple Silicon runner finally.

https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by smorimoto** [comment]
Given that some of Haxe is written in OCaml, it's not easy to target Apple Silicon.

**Comment by smorimoto** [comment]
You can use the Apple Silicon macOS on the paid runner, but I don't think it's possible with the free runner.

**Comment by barisyild** [comment]
> You can use the Apple Silicon macOS on the paid runner, but I don't think it's possible with the free runner.

macOS larger runners will be priced at $0.16/minute for XL and $0.12/minute for large

Github runner is free within certain limits.

Each platform uses a different amount of quota.

**Comment by smorimoto** [comment]
No, you can't: https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners

> Larger runners are only available for organizations and enterprises using the GitHub Team or GitHub Enterprise Cloud plans.

**Comment by RblSb** [comment]
I only found one free alternative, but it needs installation in repo and has 500min/month free quota:
https://www.flyci.net/
Even if macos workflow will be optimized to cache homebrew deps, it's not enough for every nightly build on commit.

**Comment by smorimoto** [comment]
Finally: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by RblSb** [comment]
That's nice. It is ok to start new folder mac-arm64 here, or there is some simple way to merge binaries to universal?
https://build.haxe.org/builds/haxe/

**Comment by barisyild** [comment]
Can compile Haxe as universal binary?
This way there is only one executable and the runner is not a problem.

https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary
