### ISSUE TITLE
allow sys for target-specific files

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10214]
Currently haxe only allows js,cpp,java,...
In a few situations it would be really useful if sys was also allowed.
The targets themselves should always have the higher priority. So (compile to cpp):

```
Example.hx
Example.cpp.hx
Example.sys.hx
```

Loads Example.cpp.hx
but

```
Example.hx
Example.js.hx
Example.sys.hx
```

Loads Example.sys.hx

**Comment by back2dos** [comment]
It would also be nice to go the other way, i.e. be *more* specific than just per-target. For example, if you have a node server and a browser client, you can still have different versions of a module. Or even if you wish to build something that runs on say both openfl and heaps, it'd be neat to be able to have per-framework-modules instead of an `#if`-fest. Then again this raises quite a few question of how these "target flags" are defined and prioritized in module resolution.

**Comment by RealyUniqueName** [comment]
This question was raised a few times already. We can't support `.whateverDefine.hx` as there could be dozens or even hundreds of defines per compilation and checking each define for each `.hx`  module seems too expensive.

**Comment by RealyUniqueName** [comment]
But maybe we could have an additional compiler argument like `--module-selector whatever`?

**Comment by Simn** [comment]
This is going to require a haxe-evolution proposal. I'm against just hardcoding `sys` here because then we end up scanning the filesystem for three different files every time we try to resolve one. If users want this in some circumstances that's another story, but it definitely shouldn't become the default behavior.
