### ISSUE TITLE
Will it support wasm?

### ISSUE THREAD

**Issue by jingyuexing** [HaxeFoundation/haxe#10211]

**Comment by nanjizal** [comment]
Have you looked at JSPrime used by NME toolkit?

Quote from NME Gitter channel:
"Hugh Sanderson
@hughsando
Aug 08 2020 14:13
JSPrime is the web backend. It has 2 bits - 1 is just the haxe code compiled to js, the other is the nme c++ code compiled to WASM. Doing the build.n generates the wasm code (and a few other files) that acts like a dll for javascript...."

I have tried JSPrime the start up is slow compared to native WebGL or say similar OpenFL code but otherwise works well, so may well be ideal for large game.

You can see Hugh chess in JSPrime.
https://haxenme.github.io/nme-chess/

You can find a bit more on old blog post on Hugh blog.
http://hughsando.com/2017/09/11/10-year-anniversary/

It's fairly easy to setup and use NME with JSPrime just install latest NME and then you can build it with hxml and application.xml file this should show roughly how it differs from other toolkits.

https://github.com/nanjizal/PolyominoTriangles/blob/master/compile/polyominoTrianglesNME.hxml

https://github.com/nanjizal/PolyominoTriangles/blob/master/compile/application.xml

So haxe does WASM just Hugh has a tendancy not to advertise NME enough, I am not sure how easy it is to do WASM without NME likely you would need to look through source files there is likely no documentation, maybe there are examples somewhere?

**Comment by nanjizal** [comment]
WASM seems not ideal as in practical situations there is some setup time, and you may find better to use haxe js direct to WebGL, although NME works well. Perhaps with newer browser WASM will become more relevant.

**Comment by Simn** [comment]
asked and answered
