### ISSUE TITLE
Nested map does not work with `[]` initialiser

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#10227]
```haxe
var x = new Map<Int, {a:Map<Int, Int>}>();
// x[0] = {a: []}; // error, no @:arrayAccess etc etc
x[0] = {a: new Map()}; // works
```

**Comment by Simn** [comment]
The problem here is the array access because the example can be reduced to just this:

```haxe
function main() {
	var x = new Map<Int, Map<Int, Int>>();
	x[0] = [];
}
```

The question is if the expected type for the `[]` should really be `Map<Int, Int>`. It's a bit weird because we generally type all three components of the array write access (base, index, value) independently and only then try to resolve an appropriate array access function on the abstract.

I can however see the argument that we should use the expected type if there's exactly one array access function defined on the abstract. This would be similar to what we do with from-casts in some places.

**Comment by nadako** [comment]
is this the same as #8038 and #6743 then?

**Comment by Simn** [comment]
Yes, I knew this seemed familiar!
