### ISSUE TITLE
Operator overloading issue since Haxe 4.2

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#10248]
Executing the following code in Haxe 4.2 shows that the variable `val` contains 1 after adding the int value of CustomInt, where as in Haxe 4.1 and earlier `val` contains 3. It looks like the expression `val += customInt` is not evaluated correctly.

https://try.haxe.org/#EEd3d1c4

```haxe
@:forward
abstract CustomInt(CustomIntImpl) from CustomIntImpl to CustomIntImpl {

  public function new(val:Int) this = new CustomIntImpl(val);
  
  @:op(A+=B) static inline function op_add_assign3(a:Int, b:CustomInt):Int return a + b.value;
}

private class CustomIntImpl {
  var _value:Int;
  function get_value():Int return _value;
  public var value(get, never):Int;

  public function new(initialValue:Int) _value = initialValue;
}


class Test {
  static function main() {
    var customInt = new CustomInt(2);
    var val = 1;
    val += customInt;
    trace(val);  // prints 1 on Haxe 4.2 and 3 on Haxe 4.1 or earlier
  }
}
```

**Comment by RealyUniqueName** [comment]
Actually I think new behavior is more correct.
You're overriding an operator. Which means it's up to you to replicate an assignment semantics if you want. Whereas old behavior gave no such option.
You need to rewrite `@:op(A += B)` like this:
```haxe
@:op(A+=B) static inline function op_add_assign3(a:Int, b:CustomInt):Int 
    return this = a + b.value;
```

**Comment by Aurel300** [comment]
@RealyUniqueName The version you give is not what Haxe used to do. It's the `a` parameter that should be assign-modified, not `b`, the abstract. There is no way to modify `a` within the function. Taking the returned value as the new assigned value makes some sense…

**Comment by Aurel300** [comment]
@sebthom Can you resolve your issue by defining `@:op(a + b)` instead?

**Comment by nanjizal** [comment]
initially sent reply direct, by mistake, perhaps it's useful to have the try in the conversation.

Sabastian

It seems to work fine the other way round, the problem seems to be that haxe does not want to allow
'+=' on the custom type to effect a value on Int type.
https://try.haxe.org/#B55FDaEA

I don't know if this is correct behaviour, but seems fairly logical that you would add the operator on a new defined Int abstract type instead, I guess perhaps it's problematic for operator to effect anothers base type? But just thought, felt it useful to clarify the reverse still works. Maybe there are complex implications that makes the previous behaviour problematic for reliability ?

**Comment by nanjizal** [comment]
I presume one approach is to require just working with abstracts that are designed to work with CustomInt, although that gets dirty, I have assumed to/from Int for simplicity. Something perhaps like...
```Haxe
@:forward
abstract MyInt( Int ) to Int from Int {
@:op(A+=B) static inline function op_add_assign3(a:MyInt, b:CustomInt):MyInt return ( a + b.value: MyInt );
}
```

**Comment by nanjizal** [comment]
You can create a typedef to hide some implementation detail from the user, and perhaps put in the global imports, it gets messy I guess.
```Haxe
typedef Int = MyInt;
```

**Comment by sebthom** [comment]
> @sebthom Can you resolve your issue by defining `@:op(a + b)` instead?

@:op(A+B) seems to work

@Aurel300  Does that mean `@:op(A+=B)` has been removed in Haxe 4.2?

**Comment by sebthom** [comment]
I did some more experiments. With the following code overloading `+=` does not work for `int += CustomInt` but works for `CustomInt += int`

```haxe
@:forward
abstract CustomInt(CustomIntImpl) from CustomIntImpl to CustomIntImpl {

  public function new(val:Int) this = new CustomIntImpl(val);

  @:op(A+=B) inline function op_add_assign(a:Int):CustomInt { this.addAndGet(a); return this; }
  @:op(A+=B) static inline function op_add_assign2(a:Int, b:CustomInt):Int return a + b.value;
}

private class CustomIntImpl {
  var _value:Int;
  function get_value():Int return _value;
  public var value(get, never):Int;

  public function new(initialValue:Int) _value = initialValue;
  
  public function addAndGet(amount:Int):Int return _value += amount;
}


class Test {
  static function main() {

    // increment and assign int with CustomInt
    var customInt = new CustomInt(3);
    var val = 1;
    val += customInt;
    trace(val);  // prints 1 on Haxe 4.2 and 2 on Haxe 4.1 or earlier
    
    // increment and assign CustomInt with int
    customInt += 1;
    var customInt = new CustomInt(3);
    var val = 1;
    customInt += val;
    trace(customInt.value);  // prints 4 on all Haxe versions
  }
}
```

**Comment by sebthom** [comment]
So in my actual project I had these operator overloads:
```haxe
   @:op(A+=B) static inline function op_add_assign4(a:Int, b:CustomInt):Int return a + b.value;
   @:op(A+B)  static inline function op_add3(a:Int, b:CustomInt):Int return a + b.value;
```

Removing the first one made the code work again also on Haxe 4.2. I just don't understand why.

**Comment by RealyUniqueName** [comment]
> @RealyUniqueName The version you give is not what Haxe used to do.

Ah, sorry. I was not carefully reading through the issue because It looked to me as the similar issue I was trying to figure out recently.

Still I think it should be up to user to decide about assignment. We just don't have means to declare it in this case.

**Comment by Aurel300** [comment]
> So in my actual project I had these operator overloads:
> 
> ```hx
>    @:op(A+=B) static inline function op_add_assign4(a:Int, b:CustomInt):Int return a + b.value;
>    @:op(A+B)  static inline function op_add3(a:Int, b:CustomInt):Int return a + b.value;
> ```
> 
> Removing the first one made the code work again also on Haxe 4.2. I just don't understand why.

There are multiple things happening here.

First of all, `@:op(a += b)` was not removed. It still works, but it has slightly different meaning now. In particular, the "assignment" part no longer happens by default, which is ok if the LHS is an abstract (because then you can simply do `this = ...` to make the re-assignment), but causes the issue you've noticed when it happens to be a value type like `Int` or `Bool`. Just like in normal Haxe functions if you take an `Int` argument and re-assign it inside your function, this does not affect any variable at the place the function was called.

```haxe
function foo(a:Int) a = 5;
function bar() {
  var x = 10;
  foo(x);
  trace(x); // still 10
}
```

Next, when you only define `@:op(a + b)`, Haxe will interpret `a += b` as `a = a + b` by default.

And finally, there is the case when you have both `@:op(a += b)` and `@:op(a + b)`. IIRC, *if* you define `+=` first (i.e. syntactically first in the code), it will be used for `+=` operations. If the `+` version is defined first, then even `+=` uses it. I think there was a recent issue about that, unsure if we want to change this behaviour in the end.

**Comment by sebthom** [comment]
@Aurel300 thanks for the explanation. 

Since I could fix my project by removing the `@:op(A+=B)` overload I am closing this issue. 

Thanks to everyone for helping me out!
