### ISSUE TITLE
[js] undefined $global in AudioWorklet environment 

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#10258]
I recenly touched `AudioWorklet`, which runs in the `AudioWorkletGlobalScope`,

Since ~~`AudioWorklet` doesn't have any similar `$global` variable~~,  so the code compiled by haxe will not run in it, 
unless your code doesn't have any reference to `$global`, 

I just wonder is `$global` really necessary?

For example, when calling `$global.console.log` from haxe, the compile should be able to directly generate `console.log` instead of `window.console.log/global.console.log.....`

**Comment by RealyUniqueName** [comment]
`$global` is supplied to a haxe-generated IIFE, which wraps haxe-generated code.
It could be a `window` object in browser, `exports` object in nodejs etc.
As a fallback it uses `self` variable if defined or `this` otherwise.
Try defining `self` variable prior to loading haxe-generated js file.

**Comment by R32** [comment]
I suddenly found that ES6 [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) is available in AudioWorklet

**Comment by haxiomic** [comment]
Why does javascript have 4 global conventions? O_o
![standards](https://user-images.githubusercontent.com/3742992/120206205-ce416180-c222-11eb-986c-d173061585a5.png)
https://xkcd.com/927/


The solution would be to add `globalThis` to the list of global variables for ES5. Initialization currently looks something like this
```js
$global = typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this
```

And for ES6 output we can just use `globalThis` for `$global` because `globalThis` is available everywhere for ES6

**Comment by R32** [comment]
The `globalThis` looks bit too new, I guess some js environments may not support it.

and other js environments may uses different `$global` name,

for example: the wechat mini-games chooses `gameGlobal` as global object.

> In China, almost everyone uses wechat(weixin) even if they don’t like it.

Maybe we can add a definition something like `-D js-env=xxx`, when `js-env` exists then uses it instead of `$global`

**Comment by haxiomic** [comment]
@R32 maybe we're safe when `-D js-es=6` is used because `globalThis` is in ES6 spec: https://262.ecma-international.org/6.0/#sec-code-realms

But maybe leave it a few years because some environments will still be non-es6 compliant. In the meantime, just adding to this list of possible globals is the way to go

Some discussion about this mess: https://mathiasbynens.be/notes/globalthis
