### ISSUE TITLE
Inconsistent message error

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10267]
Hej,

It's not a bug but maybe it would be cool to have a same message error if an `inline` fails beeing in front of a function declaration or in front of a call of this function :
`Function foo cannot be inlined because of a not final return` in front of a call function
`Cannot inline a not final return` in front of a function declaration

**Comment by Simn** [comment]
Please post some code that demonstrates what you mean because I don't understand it.

**Comment by filt3rek** [comment]
Hi Simon,
Thanks for your answer !
https://try.haxe.org/#7Cf3c7fB
Here is an example with `Cannot inline a not final return`:
```haxe
class Test {
  static function main() {
  	foo( true );
  }
  
  inline static function foo( b ){
    if( b == null )
      return !b
    else if( b )
      return b;
        
    return false;
  }
}
``` 
And here with `Function foo cannot be inlined because of a not final return`
```haxe
class Test {
  static function main() {
  	inline foo( true );
  }
  
  static function foo( b ){
    if( b == null )
      return !b
    else if( b )
      return b;
        
    return false;
  }
}
```

**Comment by Simn** [comment]
Well, this is supposed to be "inconsistent" by design. If the function itself is inline, a non-final `return` is incompatible at definition-level and is thus reported. However, if you attempt to call-site inline such a function, then the problem is your `inline` attempt, not the nature of the function. This is working as expected.
