### ISSUE TITLE
JSON parsing slow and memory intense on eval - due to Reflect.setField.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#10284]
Here's an example: https://try.haxe.org/#e820468b

The full data was taken from https://github.com/benmerckx/mime/blob/master/src/mime-db.json (170KB), but on try.haxe that makes the compiler run out of memory (takes about 2s to parse and allocates ~300MB).

For comparison, `Context.parse` of the same string is about 100x faster.

The reason seems to be that `Reflect.setField` (called from `haxe.format.JsonParser::parseRec`) is sloooooow. This can be quickly verified by nooping it out: https://try.haxe.org/#2F9517aC

**Comment by Simn** [comment]
The problem is that the object prototype is updated on each `setField`, and that's not a very fast operation.

I guess for cases like this we really need a proper dictionary mode for objects. This is going to require some engineering, but should be worth the effort.

**Comment by Simn** [comment]
I've made a change to put objects in dictionary mode when there's a write-access to an unknown field. This should greatly help dynamic code while not hurt properly typed code much either (it's just one additional branch which I doubt can be measured).

Will keep this issue open so I remember to check the benchmarks because there could be some negative side-effect I'm overlooking.

**Comment by Simn** [comment]
Benchmarks look good:

![brave_GAE7Jbtguc](https://user-images.githubusercontent.com/634365/126107871-0f71a561-25d4-4171-811a-35a3427846ae.png)

The date is off but I think that's because that's due to CI/building problems.
