### ISSUE TITLE
haxelib isn't working

### ISSUE THREAD

**Issue by MisterPigeon** [HaxeFoundation/haxe#10292]
I installed the binary version of Haxe, and it said neko.dll was missing. I downloaded the Neko binaries and dropped neko.dll into the Haxe folder. It then asked for gcmt.dll.dll (first .dll comes from the file name). I found the file in the Neko binaries folder and dropped it into the Haxe folder. Now, when I open haxelib, the command window briefly flashes on the screen before closing. Can anyone help me?

**Comment by Aurel300** [comment]
`haxelib` is a command line program, I assume you are trying to just run the .exe? You need to open `cmd` or PowerShell and type e.g. `haxelib help`.

**Comment by MisterPigeon** [comment]
Please elaborate what cmd or PowerShell is, as I am not familiar with the names.

**Comment by haxiomic** [comment]
`cmd` and `PowerShell` are both examples of command lines. You're familiar with running programs with a graphical user interface, with buttons and things but there's another way to interact with a program: via a text interface. This is what a command line is

Here's a youtube video explaining a bit about the command line on windows: https://www.youtube.com/watch?v=MBBWVgE0ewk

haxelib.exe does not have a graphical user interface, only a command line / text interface. When you open a program like that, it will open the command line window and because it didn't get any input, it closes again immediately. This is normal for a command line program – you need to run haxelib from an already opened command line window to use it

You may be better off using the haxe installer rather than binaries because you'll need to setup other things like your %PATH% variable for everything to work

I'm closing this as it's not an issue – for these sorts of questions you'll get better responses on https://community.haxe.org or the hae discord group: https://discord.gg/7R69ytu
