### ISSUE TITLE
optimizer reorders inlined code wrong

### ISSUE THREAD

**Issue by AdrianV** [HaxeFoundation/haxe#10304]
the following code is reordered wrong by the inliner. As soon as I remove `inline` from `next()` the expected result is returned.

All Haxe versions from 3 to 4.2.3 behave the same.

https://try.haxe.org/#e650210b

```haxe
class PairIter<T> {
	var data: Array<T>;
  var x = 0;
  var prev: T;
  var cur: T;
  
  public inline function new(data: Array<T>) {
		this.data = data;
  }
  
  public inline function hasNext() {return x < data.length;}
		
  public inline function next() {
		prev = cur;
		cur = data[x++];
		return {prev: prev, cur: cur};
  }
}

class Test {
  static function main() {
    for (p in new PairIter([1,2,3])) {
      trace('${p.prev}  ${p.cur}');
    }
  }
}
```
output is 
```
1 1
2 2
3 3
```
expected is
```
null 1
1 2
2 3
```

**Comment by back2dos** [comment]
The problem is introduced by the analyzer. If you [disable it](https://try.haxe.org/#fFA91d8E), the output is as expected.

**Comment by AdrianV** [comment]
Should have checked that. My issue title is misleading then.

**Comment by Simn** [comment]
Works with `-D analyzer-no-copy-propagation`. I'll check what's going wrong there.

**Comment by Simn** [comment]
This is related to variable initialization status prior to the analyzer transformation. If we disable `check_local_vars_init`, the problem reproduces with this code:

```haxe
function main() {
	var prev;
	var cur;
	while (true) {
		prev = cur;
		cur = 1;
		trace(prev, cur);
		break;
	}
}
```

Note how the  `prev = cur` line usually gives an error because `cur` is uninitialized. If we change its definition to `var cur = null`, we get the expected result.

This tells me two things:

1. The analyzer relies on variables being initialized before usage because that's a language constraint.
2. Somewhere in the arcane depths of (constructor?) inlining, that constraint is violated.

**Comment by Simn** [comment]
This took me longer than I care to admit considering it's a one-line fix. One could argue that this kind of situation should raise an error because there's something wrong internally, but on the other hand the analyzer should not rely on language-level assumptions anyway.

**Comment by Simn** [comment]
Actually I would still like to ping @basro because if we ever move `check_local_vars_init` behind the inline constructor processing, the `used without being initialized` error message will appear. 

This is a bit of a silly situation because we have stronger constraints for local variables than we do for member fields, so when transforming the latter to the former we end up with problems. I'm not sure what the best solution is here though.

**Comment by AdrianV** [comment]
I see the problem is/was the missing initialization of `cur` in the constructor. I was up to now living with the false assumption that a not explicit initialized member var is initialized to null/default. For several reasons I would prefer either a `used without being initialized` error message in such a case, or better a implicit initialization of such vars, because this is likely what the author intended.

**Comment by basro** [comment]
If I remember correctly the constructor inliner depends on `check_locals_vars_init` since it assumes that variables will be not be used before initialization.

I agree however that it shouldn't output things that violate that condition, I will have a more in depth look soon.

**Comment by Simn** [comment]
The original example now gives a warning: `Warning : Constructor inlining cancelled because of use of uninitialized member field cur`

Usually I don't like warnings very much, but in this instance it's a good solution because while the code works correctly as far as the logic is concerned, it's _probably_ still not quite what the user wanted.
