### ISSUE TITLE
[Java/Jvm] `-java-lib-extern` imports default interfaces improperly 

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [HaxeFoundation/haxe#10328]
Java has interfaces that can have function bodies.
```java
interface Example {
    default void doSomething() {
         // do something
    }
   String someNonDefaultVar;
}
```

When importing this from a jar and implementing this interface, haxe complains about there being no definition for the function
```hx
class ExampleThing implements Example {
    var someNonDefaultVar:String;
}
```
 throws `Field doSomething needed by Example is missing`

This should probably be fixed as it breaks compatibility.

**Comment by Simn** [comment]
We rejected this as a language feature here: https://github.com/HaxeFoundation/haxe-evolution/pull/70

The fact that it comes from an extern doesn't change that.

**Comment by Gama11** [comment]
It seems like there should be _some_ way to deal with this when working with externs though. If those interface methods were marked with a special meta (`java.default` or something?) for instance, you could at least write a macro that handles this automatically.

**Comment by RealyUniqueName** [comment]
I agree Haxe compiler should not complain about missing implementations for such methods.

**Comment by Simn** [comment]
It should complain because this is not a Haxe language feature.

Marking these in some ways seems fair enough though.

**Comment by nanjizal** [comment]
This seems valid code, is this suitable approach direction for supporting Java, could -java-lib-extern create something like this, I guess it would be really complex with multiple interfaces, and I am not sure it is suitable.
https://try.haxe.org/#d804341E
```Haxe
interface Example_ {
  public var someNonDefaultVar: String;
}
abstract class Example implements Example_ {
    public function doSomething(): Void {
         // do something
    }
}
class ExampleTest extends Example {
  public function new(){
		someNonDefaultVar = 'hi';
  }
  override public function doSomething(): Void {
		trace( someNonDefaultVar );
  }
}
class Test {
  static function main() {
    var e = new ExampleTest();
    e.doSomething();
    trace("Haxe is great!");
  }
}
```

**Comment by nanjizal** [comment]
I am a bit worried if it should work since I only declare the public var in the interface, so feels bit magic!

**Comment by Simn** [comment]
Guys, this is _not_ valid Haxe code and should _not_ work. The haxe-evolution team made that decision and we aren't going to subvert this in some random issue.

**Comment by nanjizal** [comment]
There seems two options for Bulby.
1) unzip the jar modify it to be compatible and rezip?
2) eliminate the need for the extern by wrapping the offending code in a java wrapper that uses composition and does not expose any part that haxe compiler can't understand, so you are only exposing the wrapper extern. So in effect you would create a jar wrapper, this may change the way the library would be used but it would eliminate the need to maintain a separate branch of the original jar. If too slow then 1) seems the best option.

**Comment by nanjizal** [comment]
[ deleted my code snipit above as it was not useful ]

**Comment by RealyUniqueName** [comment]
This issue is strictly about consuming extern interfaces with default implementations from extern libraries.

**Comment by TheDrawingCoder-Gamer** [comment]
Yes, I think it's reasonable that all java features be compatible with haxe someway (even if it isn't the exact way it should be)
For example, inteface statics are handled by adding a class in the same module and moving all the statics in the interface there.
Right now interface defaults are incompatible with haxe. I have to make abstract classes for it (and i don't even know where to start for versions <4.2.0).
It would be nice if implemented exactly but as long as it's compatible in some way i'm okay with it.

**Comment by Simn** [comment]
> This issue is strictly about consuming extern interfaces with default implementations from extern libraries.

Yes but the implementing class is not extern itself, so it would require us to implement this feature in the compiler even though we formally rejected it.

**Comment by kevinresol** [comment]
How about making the declaration mandatory, so to fulfill Haxe interface's requirement. But using a meta to instruct the compiler to copy the default implementation? In case of multiple default implementation exists, just reject it and force user to define the function body manually, which aligns with java's behaviour. Example:

```haxe
class ExampleThing implements Example {
    var someNonDefaultVar:String;

	@:jvm.copyDefault
	public function doSomething():Void;
}
```

**Comment by back2dos** [comment]
> Yes but the implementing class is not extern itself, so it would require us to implement this feature in the compiler even though we formally rejected it.

There are two statements here.

### We formally rejected it

This is true and I don't think anyone is actually trying to subvert the decision here. **It's purely a matter of having better interop with the Java eco system.**

Default implementations exist in Java, [so that it's possible to add methods to an interface in a backward compatible fashion](https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html#existing_libraries). Because Java (in contrast to Haxe) has "real" method overloading, this is realistically possible, as methods with incompatible signatures cannot clash (although there's always the slim chance that the semantics silently choose an implementation that was not intended by the user).

This is not some purely academic feature. It was added in Java 1.8, where the corresponding JDK added [`Iterable::forEach`](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html#forEach-java.util.function.Consumer-), to an interface that probably has a bazillion implementations out there, some in commercially licensed obfuscated jars, where the company that created them is long gone, along with the source.

How likely this is to affect haxe/jvm users in daily life is another matter. It is however true that Java libraries are designed with Java and not Haxe in mind. Their APIs are nothing we have influence over - only how easy to use we make them. Little is gained by forcing Haxe users to fully implement interfaces that were never designed with that intent in mind, or by making Haxe users deal with breaking changes if they update their dependencies to a version that is backward compatible from a Java perspective. These are sources of friction that could be removed specifically at the integration barrier between Haxe and the Java ecosystem, all the while respecting [the conceptual reasons given for rejecting this is part of the core language](https://github.com/HaxeFoundation/haxe-evolution/pull/70#issuecomment-646520025).

### It would require us to implement this feature in the compiler

Indeed. It would have to be implemented. Only then would it become possible to restrict availability to extern interfaces in java. That's arguably quite silly, but the question is whether or not it's worth the hassle.

I wouldn't categorically reject it, as this is quite comparable to the early support for overloads that was added solely for haxe/java and haxe/cs (which aren't even restricted to implementing/overriding extern interfaces/classes). Whether or not this feature is as useful, I cannot say, because honestly I have very little real world experience with haxe/java.

So I would like to suggest that we're not deciding for or against the subversion of formal decisions taken in the language design process. Rather, we're weighing the complexity of generally supporting this feature only to disable it in almost all cases, against the added compatibility with one of our target eco system. I cannot gauge the former nor the latter, but I'm convinced that that's what should be done ;)

**Comment by Simn** [comment]
> I don't think anyone is actually trying to subvert the decision

> It would have to be implemented

> restrict availability to extern interfaces in java ... quite silly

This is exactly how this would go. I'm protecting the process here because this would lead to a backdoor introduction of a feature that was rejected. You're somewhat supporting my point by bringing up overloads because these are now also creeping into more parts of the language, even though they were originally introduced for a narrow reason. The difference is that overloads were never formally rejected.

If people want this feature (with whatever restrictions might apply), it has to go through the same process again. I'd expect a vote to be successful, but it needs a vote nonetheless. Otherwise the entire process is useless.

Note that I'm not even arguing on the merits or usefulness of this feature because I honestly can't judge that. Regarding complexity, I'd expect a bit of a nasty surprise regarding how to actually get the code from A to B. Whether or not that would be a showstopper, I cannot judge either.

**Comment by TheDrawingCoder-Gamer** [comment]
how does one reopen a vote if it was already rejected? wasn't the decision final?

**Comment by TheDrawingCoder-Gamer** [comment]
also, to talk about concerns in the old pr for haxe-evo, why not just lock default implementations behind metadata (i.e. @:partial), and to also solve this issue, force all imported java externs to have that metadata (if i am correct on how i think libs are imported)

**Comment by RealyUniqueName** [comment]
> how does one reopen a vote if it was already rejected?

One does not reopen a rejected evolution proposal. I'd suggest to start an issue for discussion in haxe-evolution repo. And then, if there's an interest, submit a new proposal with all the show-stoppers worked out.

**Comment by kevinresol** [comment]
I don't think this even requires an evolution proposal. Because it only affects java externs but not the Haxe language as a whole.
If I understand correctly this "default method" is purely a runtime feature in the point of view of the interface consumers. Because the actual body of the default implementation is stored in the interface itself, which is then used as fallback when the corresponding method is missing in an implementing class.

In this case, the Haxe compiler merely needs to take note of the default methods in interfaces when parsing external jars and then allow their implementation to be optional in the implementing classes.

**Comment by Simn** [comment]
Yes I have since learned that this is actually a JVM feature, not a Java compiler feature. My assumption was that the compiler would have to handle all this, but if this is merely a matter of tagging some methods in some way then I don't have any objection. In that case there's not even the risk of us randomly opening the feature to other targets.
