### ISSUE TITLE
Closure var eliminated unexpectedly

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#10335]
```haxe
class Main {
	final prop = {
		var value = 1;
		{
			get: () -> value,
			set: v -> value = v,
		}
	}
	
	function new() {}
	
	static function main() {
		final inst = new Main();
		trace(inst.prop.get() == 1); // true
		inst.prop.set(2);
		trace(inst.prop.get() == 2); // false, but should be true
	}
}
```

generates (note that the variable `value` is not present):

```js
	this.prop = { get : function() {
		return 1;
	}, set : function(v) {
		return v;
	}};
```

**Comment by Simn** [comment]
The problem was that we ran the analyzer on these expressions early, before the `VCaptured` flag on variables had been determined. I don't see a reason why we specifically run it on these expressions at all because all relevant optimizations should occur during post-processing anyway. Removing the early optimization fixed this, and quite possibly a few more other related problems.
