### ISSUE TITLE
[JS] switch with pattern matching produces weird result

### ISSUE THREAD

**Issue by botsman** [HaxeFoundation/haxe#10346]
Hi,

It looks like on JS platform Haxe produces weird output when switch/case expression used along with pattern matching.

Haxe:
```haxe
public static function main() {
    var a: Dynamic = "someString";
    switch a {
      case "b":
        trace(1);
      case StringTools.contains(a, "b") => true:
        trace(2);
      case StringTools.contains(a, "c") => true:
        trace(3);
      case "c":
        trace(4);
      case "d":
        trace(5);
      default:
        trace(6);
    }
  }
```

JS:
```js
function() {
	var a = "someString";
	var _hx_tmp;
	var _hx_tmp1;
	switch(a) {
	case "b":
		console.log("project/Main.hx:14:",1);
		break;
	case "c":
		_hx_tmp1 = a.indexOf("b") != -1;
		if(_hx_tmp1 == true) {
			console.log("project/Main.hx:16:",2);
		} else {
			_hx_tmp = a.indexOf("c") != -1;
			if(_hx_tmp == true) {
				console.log("project/Main.hx:18:",3);
			} else {
				console.log("project/Main.hx:20:",4);
			}
		}
		break;
	case "d":
		_hx_tmp1 = a.indexOf("b") != -1;
		if(_hx_tmp1 == true) {
			console.log("project/Main.hx:16:",2);
		} else {
			_hx_tmp = a.indexOf("c") != -1;
			if(_hx_tmp == true) {
				console.log("project/Main.hx:18:",3);
			} else {
				console.log("project/Main.hx:22:",5);
			}
		}
		break;
	default:
		_hx_tmp1 = a.indexOf("b") != -1;
		if(_hx_tmp1 == true) {
			console.log("project/Main.hx:16:",2);
		} else {
			_hx_tmp = a.indexOf("c") != -1;
			if(_hx_tmp == true) {
				console.log("project/Main.hx:18:",3);
			} else {
				console.log("project/Main.hx:24:",6);
			}
		}
	}
}
```

For some reason part of the pattern matchers is duplicated under multiple case expressions.  
Maybe I don't understand something, but to me it looks like some part of generated code is unnecessary.

Thanks!

**Comment by Simn** [comment]
Which parts do you think are unnecessary? The problem with extractors is that even if your subject matches `case "c"`, the logic still has to check if one of the extractor cases should take priority because they appear before that case. In fact, your `case "c"` in this example is useless because the `StringTools.contains(a, "c")` check will always hold if `a == "c"`. The compiler can't really know that though because it doesn't understand what `contains` means.

I'm open to suggestions regarding code generation with extractors and I'd be curious to see what other compiler generate here. We _could_ generate an `if else` chain which would look nicer, but then we end up with potentially a lot of sequential checks especially in large switches.

**Comment by botsman** [comment]
Thank you for the detailed explanation!

At first I was quite confused with the generated code and thought that something gone wrong. Now I see that the execution logic will be that same as in the Haxe code.

The second case in `case StringTools.contains(a, "c")` and `case "c"` is useless indeed. I just wanted to make an example of the compiled code. There could be any other expression.
