### ISSUE TITLE
Why is this error? It looks like the variable is defined

### ISSUE THREAD

**Issue by WREQI** [HaxeFoundation/haxe#10358]
![image](https://user-images.githubusercontent.com/35467304/130322064-a6c12331-64c4-4b6f-b3b9-61091b159dad.png)
Why is this error? It looks like the variable is defined

**Comment by back2dos** [comment]
Because `final` is a keyword. And the compiler is complaining about a missing *identifier* (although the wording is slightly awkward) because `var` is expected to be followed by an identifier (and you cannot use a keyword as an identifier). You would get the same error with just `var;`.

**Comment by kLabz** [comment]
We need a better error message here (indicating that using `final` as a variable name is the real issue)

**Comment by WREQI** [comment]
OK thanks to the community @kLabz @back2dos

**Comment by Simn** [comment]
The error isn't exactly wrong because the variable identifier is in fact missing. Any suggestions?

**Comment by back2dos** [comment]
Well, I think the message should read something like `Keyword <keyword> cannot be used as variable name`.

As to how that is accomplished, I can think of two ways:

1. [if the variable list comes out empty](https://github.com/HaxeFoundation/haxe/blob/6eb36b2aa38591203005ea30f8334e41de292111/src/syntax/grammar.mly#L1208), peek the next token
2. because the above won't work for bulk var declarations, another option is to replace `dollar_ident` with something like `parse_var_name` when [parsing var names](https://github.com/HaxeFoundation/haxe/blob/6eb36b2aa38591203005ea30f8334e41de292111/src/syntax/grammar.mly#L1186) that'll also allow identifiers (with dollar), but will treat keywords by raising an explicit error.

Plus some diagnostics/display support (although it's probably safe to say the latter won't be used while naming vars).

**Comment by Simn** [comment]
Thanks for mentioning bulk var declarations, I probably would have forgotten about those.

I've added a `no_keyword` function which we can use in other places as well when we come across similar problems.
