### ISSUE TITLE
Incompatibilities between haxe.Rest in cs and java (could not merge definition)

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#10351]
Haxe dev (3cb7fe4) is currently throwing an exception during API doc generation (dox CI against nightlies is broken):

> std/haxe/rtti/XmlParser.hx:289: characters 5-10 : Uncaught exception Incompatibilities between haxe.Rest in cs and java (could not merge definition)

**Comment by RealyUniqueName** [comment]
This happens because of various java-specific `@:from` methods on `haxe.Rest`:
https://github.com/HaxeFoundation/haxe/blob/3fac24b5e2465af7ae26fb533f5ef6d93cf29825/std/java/_std/haxe/Rest.hx#L40-L45
Other targets don't have those. And dox fails if amount of `@:from` methods does not match on various targets.
Fencing them with `#if !doc_gen` doesn't work because java's stdlib depends on them.

**Comment by RblSb** [comment]
Is this will be required to fix to get documentation for 4.3 release?

**Comment by ncannasse** [comment]
Could something like @:nodoc or other work here ?
