### ISSUE TITLE
Cannot add cpp.Int64 with anything since haxe 4.2.1

### ISSUE THREAD

**Issue by Aidan63** [HaxeFoundation/haxe#10378]
Since 4.2.1 trying to add `cpp.Int64` with something results in a "Cannot add cpp.Int64 and x" error.

```haxe
function main() {
    final i1 : cpp.Int64 = 32453456;
    final i2 : cpp.Int64 = 5096756;
    final i3 = i1 + i2;
}
```

All other operations appear to work and this only seems to effect cpp.Int64, not any of the other cpp specific numeric types.

**Comment by RealyUniqueName** [comment]
Actually, no.
`cpp.Int64` does not have any operations defined so it should not work (as it is now).
Prior to 4.2.1 it has `to Int` and compiler implicitly converted it to `Int` to make an addition, which is obviously wrong due to loss of data. You can still do that by `i1.toInt() + i2.toInt()` if data loss does not bother you. Or use `haxe.Int64` instead.

I consider current behavior as a fix of a previously existed flaw.

**Comment by Aidan63** [comment]
Ah, yes, that makes sense. I brought it up because I came across it while updating my haxe.Int64 PR to use cpp.Int64 instead of its current struct.
Thanks!
