### ISSUE TITLE
Fancy completion bug (sorry Simon)

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10412]
Default Haxe project with this `Main.hx`:
```haxe
class Main {
	static function main() {
		new Game();
	}
}

class Scene {
	public var scale:Float;
}

class Game extends Scene {

	public function new():Void {}

	function itWorks():Void {
		// There is completion:
		// Res.|.bar;
		Res.foo.bar;
	}

	function itDoesNot():Void {
		// There is not:
		// Res.|.bar;
		Res.foo.bar;

		// because of `final scale`
		// changing `final scale` to other name fixes it
		var strangeBust = 5 / 10;
		final scale = 5 / 10;
		// if you comment out `strangeBust` it will also work,
		// but not if you change `final scale` to `var scale`
	}
}

class Res {
	public static var foo = {bar: "hello"};
}
```

**Comment by Simn** [comment]
wtf...

**Comment by Simn** [comment]
Explanation: The parsing goes into resuming mode at the completion point, which means that it tries to find the next thing that is a class field, or a type definition. This happens at the `strangeBust` variable, and subsequently the `scale` field is also parsed as a class field, leading to a "redefinition of final" situation. That was erroring so hard that the compiler just gave up.

Actually, while writing this explanation I wondered why the `var strangeBust` is necessary to reproduce this. The resuming parser should pick up the `final scale` as a class field regardless, so that might be something else to investigate.
