### ISSUE TITLE
abstract @:to not considered for static extensions

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#10435]
Hi folks,

is the last expression in this example supposed to compile?

```haxe
using Test.Usings;

class Usings {

    public static function withInt (m:Int):Int {
        return m;
    }

    public static function withString(m:String):String {
        return m;
    }
}

abstract Zapp(Int) to Int {

    @:to public function toString ():String return "";

}

function main () {
    var z:Zapp = cast null;
    z.withInt(); // works
    var y:String = z; // works
    z.withString(); // using fails to compile
}
```

**Comment by back2dos** [comment]
Well, that's kinda by design: https://github.com/HaxeFoundation/haxe/issues/5924

I guess a "smarter" way to deal with the problems I raised would be to first resolve extensions on the type itself and only then on types compatible via `@:from`/`@:to` casts. Although that still means that down the line the addition of more casts can affect the second selection pass in existent modules, either breaking things or silently selecting another extension.

**Comment by frabbit** [comment]
Ah yes, thx for clarification.
