### ISSUE TITLE
[QUESTION] Git issue with Haxe v4.2.0?

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#10443]
This has been a question which has been plaguing the Friday Night Funking modding community for a while, and I wanted to see if I could get a conclusive answer in regards to it.

On [the README for the official Friday Night Funkin' repo](https://github.com/ninjamuffin99/Funkin/blob/1212c520ce728495c32bf348c2ef2664d1fdd7ae/README.md) (the game is written in HaxeFlixel), it states that users should:

> Install Haxe 4.1.5 (Download 4.1.5 instead of 4.2.0 because 4.2.0 is broken and is not working with gits properly...)

The community has been following this advice and using an outdated version of Haxe ever since. However, I have been running Haxe 4.2.3 myself, and I have not been able to replicate any issues with version control that ninjamuffin99 describes, no have I found any bug reports related to this issue, nor have any of the changelogs since the release of 4.2.0 included any references to a fix.

Does anyone know what the exact symptoms of the issue were, and whether they have been resolved? If the issue still exists, it should be resolved, and if the issue has already been fixed (or can be proven to have never existed in the first place) the relevant communities should be informed about it.

**Comment by Simn** [comment]
I have no idea what that means, so you should probably ask them about it. Alternatively, just keep using the more recent version and be happy about it!

**Comment by nanjizal** [comment]
Eric, 
When a new version of Haxe comes out it sometimes takes awhile for large libraries to adjust, regular Haxe users often use the latest Haxe even nightly without problems, and if we want to use a large toolkit we have to manually build it and fix any problems which can often be minor, but sometimes the build proceedure is not straight forward.  

But with FNF you are relying on OpenFL which is a large complex library, I know for instance recent builds had some font regressions - as they tried to improve which may well be sorted, and then in turn Fixel is built on top of OpenFL and sometimes does not use the latest version of OpenFL. 

I am unsure what version of OpenFL fixel currently uses. So the question is not really related to the Haxe compiler. 

I think you need to work out what version of OpenFL fixel currently uses and what features FNF uses. It may well be that you can use the latest of everything but not run on a specific mobile like android or IOS without work.

You need to create a matrix of platforms both OS used and targets/os targetted, and test against them or create some form of automated testing so that you know when its always working and when users would be best off using an older version.

**Comment by EliteMasterEric** [comment]
I am using the current version of both OpenFL and Flixel, and AFAIK so are the other devs.

I updated to Haxe latest in hopes of being able to determine exactly what problem was being experienced, and nothing of note has happened. Aside from a couple dependencies using deprecated methods, e everything build, runs, and appears fine.

The README explicitly stated that the issue is with Haxe 4.2.0, that the issue is with how Haxe interacts with version control (which I find very odd since a project is only text files) and that the issue does not exist in 4.1.5.

I was hoping one of the developers here knew more about it, but unless @ninjamuffin99 decides to respond, I'll assume the issue was resolved at some point.

**Comment by ninjamuffin99** [comment]
FNF is currently developed using the latest version of haxe.
That line in the FNF readme is probably from last December or whatev, when 4.2.0 was hot off the presses and there was some compatibility issues with flixel, openfl, and/or lime.

**Comment by EliteMasterEric** [comment]
Omg it's him

Thanks for letting us know! Greatly appreciate the work you've done for the community!

**Comment by nanjizal** [comment]
I still think it's good to have a matrix of platforms, versions and targets.  For instance does FNF work on android and ios, and PI, does it work on all linux ? Then you can always refer to people to that, and then when a new Haxe comes out, new OpenFL, new Lime or new Fixel, it can be used as a reference for people to check.

Actually it's probably something that the community needs for all toolkits and Haxe, but would need group of users so it's probably not likely to happen.  Not all haxe toolkits have unit tests or they are not easy to run.

**Comment by lublak** [comment]
@nanjizal this is a good idea. I currenlty worked on a matrix for haxe itself (hashlink and neko) https://gist.github.com/lublak/c6f9310e735cfb8c9776d8b0240a934d
But a complete matrix is a good idea. But alot of work.
