### ISSUE TITLE
[php] PHP 8.1 compatibility

### ISSUE THREAD

**Issue by cedx** [HaxeFoundation/haxe#10502]
😭  PHP 8.1 has introduced some additional incompatibilities...

```
PHP Fatal error:  During inheritance of JsonSerializable: Uncaught ErrorException:
Return type of Array_hx::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed,
or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

This error is due to: https://wiki.php.net/rfc/internal_method_return_types
For now, it can be avoided by early adjusting the `error_reporting` level (in the PHP front file, for example):

```php
\php\Boot::__hx__init();
if (version_compare(PHP_VERSION, "8.1.0", ">=")) error_reporting(error_reporting() & ~E_DEPRECATED);
// OR: if (PHP_VERSION_ID >= 80100) ...
```

**Comment by RealyUniqueName** [comment]
Related #9964

**Comment by RealyUniqueName** [comment]
I excluded `E_DEPRECATED` notices from error reporting.
Also I added support for php attribues (see bb59dda) as another solution to this issue is to annotate reported methods with `#[\ReturnTypeWillChange]` in php code.

Closing this issue because overall compatibility with PHP 8 is tracked in #9964

**Comment by cedx** [comment]
@RealyUniqueName Great news! I hope to see a new release of Haxe soon.
