### ISSUE TITLE
[Java/JVM] `@:strict` doesn't produce arguments

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [HaxeFoundation/haxe#10517]
`@:strict` metadata doesn't generate args. (my build 4.3.0-rc.1) 
Haxe metadata: 
`@:strict(org.spongepowered.asm.mixin.Mixin(target = net.minecraft.client.gui.screen.TitleScreen))`
JVM Output (viewed using a bytecode decompiler)
`@Mixin`

Note `@:meta` does work:
`@:meta(org.spongepowered.asm.mixin.Mixin(target = net.minecraft.client.gui.screen.TitleScreen))`
JVM:
```
@Mixin(
   target = screen.TitleScreen
)
```

**Comment by Simn** [comment]
Huh, there's a decent chance that I've never noticed the `@:strict` metadata before... but from looking at the implementation it is just transformed into some `@:meta` equivalent.

**Comment by TheDrawingCoder-Gamer** [comment]
that doesn't explain this behavior then 🤔

**Comment by Simn** [comment]
I looked at the implementation again and it turns out you're actually supposed to use object declaration syntax: `{target: net.minecraft.client.gui.screen.TitleScreen}`.

I'm not very happy with the overall situation here. The fact that your example just silently does nothing is really silly considering this is supposed to be "strict" in some way. There's also a difference between Java and C# here: Java simply ignores any argument except the first one if it is an object declaration, whereas C# uses them for the constructor call.

So, for Java/JVM it makes sense to error with "Object declaration expected". I think that should be extent of the "fix" for this particular issue.

Correction: The *last* argument has to be the object declaration. Although I have no idea why more than one argument would even be allowed if they are simply ignored.
