### ISSUE TITLE
Proposal: make `Math.NaN` an `Int`

### ISSUE THREAD

**Issue by jrc03c** [HaxeFoundation/haxe#10525]
As it stands, `Math.NaN` can't be stored in `Int` variables and can't be returned from functions whose return type is `Int`. Also, `Std.int(Math.NaN)` produces `0`, which definitely _is_ a number. Furthermore, all integers can be floats, but not all floats can be integers; so it seems like turning `Math.NaN` into an integer would allow it to be used in both integer and float contexts.

I'm sure there are good mathematical or technical reasons why it's currently a float value, but I just thought I'd pass along this suggestion in case it wasn't something you'd considered before. Thanks!

**Comment by Simn** [comment]
The fact that `Std.int(Math.NaN)` produces `0` should already tell you that NaN cannot be represented as an integer. This is just not how digital numbers work, so yes, there are technical reasons for this.

**Comment by jrc03c** [comment]
There's no need to be unkind about it. I was merely making a suggestion. How was I to know that `Std.int(Math.NaN)` producing `0` was intentional and not a bug? If it had been obvious to me, I wouldn't have asked. If it's clear to you that I don't know some fundamental computer science thing, why not explain it to me, or at least point me in the direction of an explanation? You should spent time pondering how you can better welcome new developers to the Haxe community rather than running them off with condescending non-explanations.

**Comment by Simn** [comment]
You hypothesized yourself that there are technical reasons, I merely confirmed that. There's nothing condescending about this.

> How was I to know that Std.int(Math.NaN) producing 0 was intentional and not a bug?

Its documentation states that the result is unspecified if the argument is `NaN`, which suggests that this is not some oversight.

**Comment by nanjizal** [comment]
Simn approach is very factual and does not always come over for all languages users as friendly - try not to take his approach as intentionally negative, there are a lot of issued raised and some are really important and others perhaps more of a distraction, there are only two full time developers on haxe language from my understanding so thier time can be quite limited, so they may not always be in a position to explain why certain aspects are not as you might expect, but need to close issues that are not going to be worked on.

There is a haxe discord, it is often worth discussing aspects of Haxe language with other Haxe users prior to submitting an issue, sometimes you will get very direct corrections - but there are lots of users that are very happy to help with more complex understanding, and it's the correct place to discuss opinions in regard to language choices prior to any issue or evolution proposal.  I highly suggest you start using the Haxe discord as your primary place to suggest feedback there are often core developers and contributors that frequent the discord, so your ideas and thoughts will be considered, often European time is most busy.

Hopefully we will see more of you there.

**Comment by Apprentice-Alchemist** [comment]
A bit more explanation on why `Math.NaN` should be a float.
Most fixed point integer formats do not have a representation for invalid data, and the concept of "Not a Number" does not exist for integer arithmetic in most processors.
NaN is only defined for floating point numbers.
(Which is why `Std.parseInt` returns `null` on invalid input whereas `Std.parseFloat` returns `NaN`)

See: https://en.wikipedia.org/wiki/NaN

**Comment by kaikoga** [comment]
To fulfill my standing position, **I would just be mean**:tm: and advise you to study about the concepts of "static targets" – like C++, Java, and C# , and "dynamic targets" – like JavaScript, PHP, and Python. ( I've failed to find the exact definition but it was here -> https://haxe.org/manual/types-nullability.html ) And yes, it breaks badly if you try to treat `Math.NaN` as `Int` in static targets, because the representation of `Int` type in each static target just can't hold the `NaN` value. It's like trying to squeeze an apple into a banana case. That's how the static targets work.
