### ISSUE TITLE
`@:generic` doesn't work with `@:structInit`

### ISSUE THREAD

**Issue by ALANVF** [HaxeFoundation/haxe#10550]
Example on try.haxe: https://try.haxe.org/#759D133E

**Comment by Simn** [comment]
Turns out we don't copy metadata to the generated classes at all, with the exception of `@:keep`. This probably causes all sorts of weird problems.

If anyone wants to help out: We should go through https://github.com/HaxeFoundation/haxe/blob/development/src-json/meta.json and check if there's any metadata that should not be on the generated class. The only one I can immediately think of is `@:generic` itself.

**Comment by Simn** [comment]
I've committed what I meant, using your list of metadata.

**Comment by ALANVF** [comment]
Fair enough
