### ISSUE TITLE
Offer broken completion.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#10560]
Simn brought up the subject of how the parser recovers in display mode in https://github.com/HaxeFoundation/haxe/pull/10555#issuecomment-1014436088 

I wanted to continue the conversation we started there in a separate issue. Here are the relevant bits:

> [back2dos] 
> I wonder whether it wouldn't be better for "Hail Mary mode" to assume that any keyword that can begin a field is the start of a field. Worst case you get completion for things that are intended to be not-yet-declared local functions / vars. Seems a better tradeoff then loosing all the following fields that have no access modifier.
> 
> [Simn] 
> I'm not sure about the tradeoff you mention though. I would prefer no completion over any sort of completion that causes broken code if "accepted", because that is way more irritating.

Being intimately familiar with the feeling of getting no completion, I'm puzzled how one would not find that extremely irritating.

If, as a user, I accept a completion option, it's my responsibility whether or not it leads to correct code. Accepting the first option here causes broken code all the same:

![image](https://user-images.githubusercontent.com/509501/150477526-c6f700af-63d3-4bff-932e-2a029f9f0fa0.png)

I much prefer irrelevant identifiers popping up than to have to type relevant, but unavailable identifiers by hand, which not only costs more time, but also increases the risk of introducing typos.

For our entertainment, let me end with this short tale in 3 acts:

![image](https://user-images.githubusercontent.com/509501/150478268-cfcf4343-0fdb-467d-93b9-ff3b0aba5f8d.png)
![image](https://user-images.githubusercontent.com/509501/150478393-dfefb098-96a8-4e5d-8be8-58a8515174b5.png)
![image](https://user-images.githubusercontent.com/509501/150478522-41193017-2b11-4a5f-9f7f-87a9b59c22d5.png)

**Comment by Simn** [comment]
I'm not very good at interpreting screenshot stories, but there's a false dichotomy here: I'm not saying that any accepted completion must be valid code because that's clearly often not the case, as you rightfully pointed out. In your example, it is reasonable to assume that you might indeed want to complete to `wip`, and then, for instance, dot-access it in a way that makes it valid code. In other words, there's at least the _potential_ of it being right.

This is different when the compiler suggests you completion for things that don't even exist. In such cases, the compiler is essentially lying to you, and that's where I draw the line.

Another way to look at it is to consider context: Completion itself can be sound, but the result can fail in a given context. This is a different quality than completion that is unsound in and of itself, and which will fail in any context. I'd like to avoid that as much as possible.

**Comment by Simn** [comment]
I'll go ahead and close this because I don't think there's anything actionable here. I'm happy to discuss our completion philosophy further though!
