### ISSUE TITLE
Macro using method not found

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10587]
Hej,

Strange error here : https://try.haxe.org/#fFB78764  `Method foo not found on class Macro`
Same if `using`commented and `Macro.foo( 1 );` uncommented.
Without using, it throw correct error `Type not found : Expr`
_Test.hx_ : 
```haxe
using Macro;
class Test {
  static function main() {
    1.foo();
    //Macro.foo( 1 );
  }
}
```
_Macro.hx_ : 
```haxe
class Macro {
  public static macro function foo( e : Expr ){

  }
}
```

**Comment by Simn** [comment]
The original example could mean that the error is somehow swallowed while trying to resolve the static extension, but what's strange is that this also fails:

```haxe
using Macro;

class Main {
	static function main() {
		Macro.foo( 1 );
	}
}
```

I don't think the `using Macro` here should even do anything, because the field can be resolved before we even have to look at static extensions. I think that's a separate issue, but also one we should look into.

**Comment by filt3rek** [comment]
Hej Simn ! 
Thanks for your reply.
And yes you're right this, with a simple `import` also fails so probably nothing to do with static extension.
```haxe
import Macro;
class Test {
  static function main() {
    Macro.foo( 1 );
  }
}
```
