### ISSUE TITLE
Switch and final var

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10624]
```haxe
class Test {
  static final RANDOM : Int = 33;
  static function main() {
    var x = 33;
    switch( x ) {
    case 1:
    case RANDOM:
        trace("a");
    default:
        trace("b");
    }
  }
}
```

Without the "final RANDOM", the compilation fails with 
```
Test.hx:8: characters 10-16 : Pattern variables must be lower-case
Test.hx:10: lines 10-11 : Warning : This case is unused
```

With the final RANDOM declaration, the compilation is successful but the case RANDOM is not handled (we get trace("b"))

**Comment by Simn** [comment]
This works on development, but I can see it failing on 4.2.5. It does sound a bit like hotfix material, but I don't even know where we fixed this. It might not even be about the pattern matcher itself because the output seems to be the same.

**Comment by Simn** [comment]
Disregard that, this appears to be a problem with `-D analyzer-optimize`.

**Comment by Simn** [comment]
Disregard that as well, the analyzer only made this surface because it const-propagated the `x = 33` into the `switch`. The real problem was that the general switch optimization made the assumption that if we switch on a constant, and no pattern matches that constant directly, we must use the default case.

I've changed this in https://github.com/HaxeFoundation/haxe/commit/efaeae7b392a4aff66df7c483877ef67ccda0d1a to actually check if we can extract a constant value to compare against. This is also going to be required for any kind of `extern static final` stuff.
