### ISSUE TITLE
Compilation server feature: treat same class name at multiple paths, as separate versions in cache

### ISSUE THREAD

**Issue by TC218** [HaxeFoundation/haxe#10686]
Currently compilation server has to be started as separate instance for each hxml project. 

Can it be modified such that it's sufficient to have only single instance, for all projects ? 

It can work out as additional memory optimization, in situation where same library version is checked out as git submodule, in multiple filesystem locations.

**Comment by kLabz** [comment]
While I'm kinda annoyed at how much RAM I end up giving haxe compilation server, I don't see this reducing it that easily.

> in situation where same library version is checked out as git submodule, in multiple filesystem locations.

Even if using dev version and multiple projects are using it, you can't really reuse its cached version accross projects. Different targets, different compilation defines and possibly also different used fields wouldn't work in some cases. Also, dependencies of that module could be different from another project (different dependency version, or even shadowed class, etc.).

**Comment by Simn** [comment]
Yeah this isn't going to just work like that. We have enough problems with the cache already, and trying to optimize memory like that is only going to make this harder. Part of the problem is that we cache everything directly, which means that any references to other classes and such must point to the same context.
