### ISSUE TITLE
[JVM] Regular expression causes runtime error when targeting the JVM

### ISSUE THREAD

**Issue by gr4vityWall** [HaxeFoundation/haxe#10680]
```
class Main {
	static function main() {
		var reg = ~/(\\)?<(\/)?([^><{}\s]*|{[^}<>]*})>/g;
		trace(reg.match('<b>Hello</b>, World!'));
	}
}
```

The above code runs fine on every other target, but throws an exception with the JVM target:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.util.regex.PatternSyntaxException: Illegal repetition near index 23
(\\)?<(/)?([^><{}\s]*|{[^}<>]*})>
```

**Comment by Simn** [comment]
This fails on the Java target as well. I don't think I want to fix this either. Our regular expressions will never be 100% cross-target because the underlying implementations differ. Here the problem is that `{` has a special meaning for Java regexes and thus has to be escaped. We _could_ try to handle such escaping in the regex string, but IMO this is messy and ultimately futile. The documentation on `EReg` even tells you this:

> While basic usage and patterns consistently work across platforms, some more
>	complex operations may yield different results. This is a necessary trade-
>	off to retain a certain level of performance.

**Comment by gr4vityWall** [comment]
No problem, thanks for the explanation @Simn

**Comment by tobil4sk** [comment]
> We could try to handle such escaping in the regex string, but IMO this is messy and ultimately futile.

@Simn Would it not be possible to handle this when converting the `~/regex/` syntax into a `new EReg("regex")` call? This conversion already involves escaping characters.

**Comment by Simn** [comment]
I'm not sure what you mean, the typer just rewrites this directly to the `new EReg` call.

**Comment by tobil4sk** [comment]
There is definitely a difference, for example, check this on eval: https://try.haxe.org/#3521439a
```haxe
final regex = new EReg("abc\x00def", "");
trace(regex.match("abc")); // true

final regex = ~/abc\x00def/;
trace(regex.match("abc")); // false
```
Even though the contents are indentical, some sort of escaping is done when the regex literal syntax is converted which changes the outcome of this code.

**Comment by Simn** [comment]
I think that's from the literal lexing itself, not the conversion. And the lexer should behave the same for all targets.

**Comment by tobil4sk** [comment]
I see. But if escaping { on the other targets wouldn't change the behaviour could it be done?

**Comment by Simn** [comment]
I mean, you can try. I doubt we test this properly though...

**Comment by 9Morello** [comment]
@tobil4sk @Simn Any chance we could take another look at this?

**Comment by tobil4sk** [comment]
I think I gave up on the lexing change I suggested, because that wouldn't fix regexes constructed directly with the EReg class: `new EReg("{")`. I think that would end up causing more confusion.

Maybe the regex constructor could just replace `"{"` with `"\{"` for the jvm target. This adds an overhead, but imo that would be ok because it is only paid once at regex initialisation time. There would be no further cost when matching the regex against strings.

However, I think it would first make sense to have a look at the bigger picture, to see if this is the only difference between jvm and remaining targets, or whether there are other compatibilities. If this is the only thing missing, then maybe it would make sense to fix. If it is one incompatibility among many, then maybe there is not much point, and it might be better to have some non-std solution for completely cross-platform regex behaviour.
