### ISSUE TITLE
Bad completion for local function name

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10691]
```haxe
class Main {
	static public function main() {
		function hello() {}
		function |
	}
}
```
```hxml
--js bin/main.js
or
--jvm bin/Main.jar
```
Currently suggests `hello` and `main` functions for name here. So when you trying to write `add()` at this place, you will get `addhello()` as result after pressing `(`.

**Comment by Simn** [comment]
How do you get `addhello` here? That must be some IDE configuration problem.

What happens here is that the compiler recovers from the parsing and provides block-level completion. I'm not sure if this is worth addressing because then we potentially don't recover in some cases where we should. Why does completion even trigger for you here?

**Comment by RblSb** [comment]
Completion triggers after you start writing function name. Vshaxe thinks that this is call to some field, and tries to fix your "typo" with replace to some other field from completion list, after you complete your name with `(` or tab.
Haxe should detect this as "name scope" and do not suggest any fields. Or we can disable completion by detecting function token on vshaxe side, maybe.
