### ISSUE TITLE
EitherType + ReadOnlyArray regression

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10730]
Vshaxe compilation is broken for haxe nightly after this commit: https://github.com/HaxeFoundation/haxe/commit/5345c4d0496edf418d12c58a832bf03ac4eb5fba
```haxe
import haxe.ds.ReadOnlyArray;
import haxe.extern.EitherType;

typedef LanguageClientOptions = {
	documentSelector:EitherType<DocumentFilter, ReadOnlyArray<DocumentFilter>>,
}

typedef DocumentFilter = {
	final ?language:String;
	final ?scheme:String;
}

class Main {
	static function main() {
		final clientOptions:LanguageClientOptions = {
			documentSelector: {language: "haxe"},
		}
	}
}
```
`{ language : String } should be haxe.extern.EitherType<DocumentFilter, haxe.ds.ReadOnlyArray<DocumentFilter>>`

**Comment by Simn** [comment]
I thought this might be because `ReadOnlyArray` has a `from Array<T>`, but this also fails:

```haxe
import haxe.extern.EitherType;

abstract A(String) {}
typedef ET = EitherType<DocumentFilter, A>;

typedef DocumentFilter = {
	final ?language:String;
	final ?scheme:String;
}

class Main {
	static function main() {
		final et:ET = {language: "haxe"};
	}
}
```

The related logic was broken before, but now it's apparently broken in a different way.

**Comment by Simn** [comment]
I have fixed my example because that one was definitely broken. The problem with yours is that we have two candidates for top-down inference:

1. Direct typing against `DocumentFilter`
2. Typing against `Array<DocumentFilter>` via `from Array<T>` on `ReadOnlyArray`

In such cases, the compiler rejects top-down inference completely and types the object as-is, which essentially leaves us with this situation:

```haxe
typedef DocumentFilter = {
	var ?language:String;
	var ?scheme:String;
}

class Main {
	static function main() {
		var o:{language:String} = {language: "haxe"};
		var d:DocumentFilter = o; // { language : String } should be DocumentFilter
	}
}
```

While I acknowledge that this particular example looks quite silly, I'm not sure if there's actually anything to fix here.

**Comment by Simn** [comment]
I'll go ahead and close this because I don't think there's anything to fix here.
