### ISSUE TITLE
Triggering typing in build macro breaks interfaces (4.2+)

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#10847]
Since 4.2 (https://github.com/HaxeFoundation/haxe/commit/12a78f8b8ca2995c3721a011ffb0a2f016a47e06), and still reproducible on current development, when a build macro for a type having interface(s) triggers typing for example with `Context.typeof`, an error is thrown about built type missing fields for its interfaces.

> Main.hx
```haxe
interface Foo {
	function foo():Void;
}

@:build(Macro.build())
class Main implements Foo {
	public function foo():Void {}
	static function main() {}
}
```

> Macro.hx
```haxe
import haxe.macro.Expr.Field;
import haxe.macro.Context;

class Macro {
	public static macro function build():Array<Field> {
		Context.typeof(macro (null:String));
		return null;
	}
}
```

```
Main.hx:6: characters 7-11 : Field foo needed by Foo is missing
```

**Comment by Simn** [comment]
The interface field check is delayed to `PConnectField` stage because in the general case it is necessary to perform these checks before typing expressions. `Context.typeof` then sets the pass to `PTypeField` (via `typing_timer`), which is also necessary in the general case.

Next, we end up on `load_module` (via typing the `ECheckType` `(null : String)`), which does `flush_pass PConnectField` and then the missing field failure triggers. This was changed in https://github.com/HaxeFoundation/haxe/commit/12a78f8b8ca2995c3721a011ffb0a2f016a47e06, which explains the regression.

This particular change keeps coming up as the root cause for random problems. IIRC it fixed some problem @nadako had in one of their codebases, but it's quite difficult to reason about this. I can confirm that reverting it breaks the test for #9811, but that isn't exactly a very obvious test case either...

**Comment by kLabz** [comment]
Thanks!

@back2dos can you check arma with this?
You might need to cherry-pick https://github.com/HaxeFoundation/haxe/commit/66c86baf82ca70aee8953522c98165e68066dbbc in `4.2_bugfix` branch, I'm not sure this codebase is ready for 4.3 .

**Comment by kLabz** [comment]
> Thanks!
> 
> @back2dos can you check arma with this? You might need to cherry-pick [66c86ba](https://github.com/HaxeFoundation/haxe/commit/66c86baf82ca70aee8953522c98165e68066dbbc) in `4.2_bugfix` branch, I'm not sure this codebase is ready for 4.3 .

@gene-pavlovsky maybe?
