### ISSUE TITLE
Reification outside of "macro" expr

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10883]
The following expression compiles but will call lib.Macros.initEntitySetter at $b evaluation time:

```haxe
var setters = [{ value : macro null, field : "s" }];
var expr = macro { $b{[for( s in setters ) lib.Macros.initEntitySetter(${s.value},$v{s.field})]}; };
```

Whereas it should not as it's missing the `macro` before lib.Macros.initEntitySetter:

```haxe
var setters = [{ value : macro null, field : "s" }];
var expr = macro { $b{[for( s in setters ) macro lib.Macros.initEntitySetter(${s.value},$v{s.field})]}; };
```

Compiler should be able to tell something is wrong because we're using reification `${s.value}` in a normal Haxe expression which is not a macro expression.

**Comment by Simn** [comment]
I'm not particularly good at reading reification code, but I think that's a more complex example of `macro $e{lib.Macros.initEntitySetter()}`, in which case it would behave as expected.

**Comment by ncannasse** [comment]
The problem can be actually simplified using the following example:

```haxe
class Main {

	static function main() {
		trace($i{"wtf"});
	}

}
```

This compiles while it should error

**Comment by ncannasse** [comment]
Please not that it should not error with "Unknown identifier wtf", instead it should error with "reification $i is not allowed outside macro expression" (or something similar)

**Comment by Simn** [comment]
Oh now I get it. The parser processes this as `@$i "wtf"` and the typer then just skips over the metadata. In that case I agree this should fail at typing-level.

**Comment by Simn** [comment]
Looks like my fix was too aggressive and broke haxelib, I have reverted it for now.

**Comment by kLabz** [comment]
Seems like it was due to something wrong in `$p{}` handling, unless I'm missing something as to why `e` was used instead of `e1` there: https://github.com/HaxeFoundation/haxe/pull/10887/files#diff-d9f1787cbe562bca8676ee9e3f009c2fb1b9b5d931a40c2f98421f889aad9a62R371

https://github.com/HaxeFoundation/haxe/pull/10887 should fix this issue

**Comment by kLabz** [comment]
Hmm.
I just noticed [4.3.2 changelog](https://haxe.org/download/version/4.3.2/) includes "all : do not raise error on no-op reification outside macro", implying https://github.com/HaxeFoundation/haxe/commit/a443fd3b9b467a9d58d18f5f2e5cfffb4b6ff370 was included... but [it's not there](https://github.com/HaxeFoundation/haxe/blob/4.3_bugfix/src/typing/typer.ml#L1708-L1715).

Should I add it on next 4.3.x release? (if any)
Or is it not worth it anymore given most people likely have removed their reification outside macro since then?
