### ISSUE TITLE
[jvm/java] Rest from Array doesn't work properly

### ISSUE THREAD

**Issue by ilevd** [HaxeFoundation/haxe#10906]
(Create an issue in https://github.com/HaxeFoundation/hxjava/issues/40 but not sure that is will be read there, so duplicate here)
When creating an Array and populating it with push(), the Rest from it doesn't work correct - it adds null value at the end. The bug in --java and --jvm:

```Haxe
import haxe.Rest;


class Main {
	static public function main() {
		var a:Array<Any> = new Array<Any>();
		a.push(1);
		a.push(2);
		a.push(3);
		trace(a, a.length);  // [1,2,3], 3
		var r = Rest.of(a);
		trace(r, r.length);  // [1,2,3,null], 4
	}
}
```

```
-cp src
-main Main
--each

--java bin/java
--next

--jvm bin/jvm/main.jar
--next

--interp
```

**Comment by Simn** [comment]
Nice find. The JVM implementation is clearly wrong because it just uses the underlying native array, which might have a larger size than the `Array` wrapper. In similar fashion, the Java implementation iterates to `src.length`, which might be too far.

**Comment by Simn** [comment]
I have fixed this for Java. Still fighting with JVM because I keep running into casting issues when trying to use a similar approach.

**Comment by Simn** [comment]
This works in the linked commit, but I've created a new problem there:

```haxe
import haxe.Rest;

function main() {
	function rest<T>(...values:T):Array<T> {
		return values.toArray();
	}
	rest(5, 6.2, 7);
}
```

```
Exception in thread "main" java.lang.ClassCastException: class [D cannot be cast to class [Ljava.lang.Object; ([D and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
        at _Main.Main_Fields_$Closure_main_rest_0.invoke(source/Main.hx)
```

The issue is that the generator thinks it's calling a `Rest<float>` function because that's the type of the expression itself. In reality however, the function is a `Rest<Object>` due to the generic type parameter, and these two are not compatible.

I'm not sure how to fix this right now and it might be a quite artificial corner case, so I might be willing to leave this broken for 4.3.

**Comment by Simn** [comment]
Never mind I fixed it.
