### ISSUE TITLE
[hl] unify stack traces with other targets

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#10926]
Since https://github.com/HaxeFoundation/haxe/commit/a40ab79ce44c9511f9be102f7a4874411161d91b, hl has derived from other targets for stack trace handling, which led to CI failing.

I'm adding a patch to make CI green again, but we need a proper solution.

**Comment by Apprentice-Alchemist** [comment]
For context, the root cause of the issue is the exception stack handling rework in <https://github.com/HaxeFoundation/haxe/commit/98df21758045580f7370469c9ffa464e794e80f3>

<https://github.com/HaxeFoundation/haxe/commit/a40ab79ce44c9511f9be102f7a4874411161d91b> just reverted the fix I implemented in <https://github.com/HaxeFoundation/haxe/pull/10610>.
(Before that PR hl-ver was 1.11 for the test-suite and the old behaviour was used, so the issue didn't arise)

**Comment by kLabz** [comment]
@ncannasse any thoughts on that? I don't know what to do about it, it seems wrong to me that hl derived from the common behavior but I suppose simply reverting that commit would break things for you
