### ISSUE TITLE
hxcpp internal encoding

### ISSUE THREAD

**Issue by furretpaws** [HaxeFoundation/haxe#10934]
I suppose this isn't an issue at all because this is how it was done i guess.

Ok so, I am trying to get the image bytes from a png file, however, I want to upload that image with a HTTP request.
The issue here is that the API requires those bytes to be sent as binary. Now, from what I have read on https://haxe.org/manual/std-String-encoding.html. C++ uses UTF-16 as their internal encoding. So I don't know if there's a way to send the image as a binary string. Not as UTF-16.

The thing here is that I tried to do the same thing with Neko, and it worked, the image uploaded successfully (third image). I tried to print the image bytes so I can see how they were.
I'm going to attach 2 files. The first one is how it looks on Neko, the second one is how it looks on C++.
Now, the thing is that, on hxcpp what's being sent to the server is just some random characters (É?NG→). Not the image.

I don't know if there's a way to send it as binary or not.
![image](https://user-images.githubusercontent.com/99131021/213881119-eb4db077-e83d-447e-80ce-591466269528.png)
![image](https://user-images.githubusercontent.com/99131021/213881144-b5d9adcf-f9cf-42a1-978e-80a783bdafb0.png)
![image](https://user-images.githubusercontent.com/99131021/213881223-8b329c9a-8230-409b-bcc1-4108c2bbb161.png)

**Comment by furretpaws** [comment]
Forgot to add the code that gets the image bytes
`var input = sys.io.File.getBytes(json.attachments[i].filename);
var hex = input.toHex().toString();
var stringBytes:String = haxe.io.Bytes.ofHex(hex).toString();`
then, the image bytes are added into the http request

**Comment by Aurel300** [comment]
@FurretDev As I already commented on your [last issue](https://github.com/HaxeFoundation/haxe/issues/10922), you should not use `String` for binary data. `String`s are for text, i.e. a sequence of Unicode codepoints, which a PNG image is not. This works in Neko by accident, not by design.

Although you don't post your full source code, the snippet you did post shows that although you encode and decode to/from hexadecimal for some reason, you are still trying to store the bytes in a `String` variable. If you are using this with Haxe's HTTP APIs, use the [`setPostBytes`](https://api.haxe.org/sys/Http.html#setPostBytes) method instead of `setPostData` as it allows you to pass a `Bytes` value.

**Comment by furretpaws** [comment]
> 

Source code is at https://github.com/FurretDev/hxdiscord/blob/main/hxdiscord/endpoints/Endpoints.hx - Line 257
Also I'm going to try to use setPostBytes as you told me, I will edit this comment if it worked or not

EDIT: It didn't work, it keeps sending a corrupted image.
