### ISSUE TITLE
Too big error range for Duplicate field in object declaration

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10961]
```haxe
class Main {
	static function main() {
		final foo:Foo = {
			a: 0,
			b: 0,
			c: 0,
			d: 0,
			a: 0
                        ~ // <- error only on field duplicate will be better
		}
		final foo = {
			a: 0,
			b: 0,
			c: 0,
			d: 0,
			a: 0
                        ~
		}
	}
}
typedef Foo = {
	a:Int,
	b:Int,
	c:Int,
	d:Int,
}
```

**Comment by kLabz** [comment]
There are several problems here: 
 * can't really have a position that spans the 2+ duplicate fields (unless consecutive but that should be rare) other than current solution
 * and can't position the error to the first duplicate field (with a sub error pointing to first one) because **object field position is not a thing** (only expr has, which would be even an even worse choice than current situation imo). 

I guess this looks like a wontfix? :/ What do you think @Simn ?

**Comment by Simn** [comment]
Arguably, object field position should be a thing...

**Comment by kLabz** [comment]
Yeah, function arguments and I guess some other ones too, but uh that would likely be a huge breaking change for macros :/

**Comment by kLabz** [comment]
(eh, can't edit on phone)
unless added separately from name on ObjectField?

**Comment by back2dos** [comment]
I'm not sure I understand. Fields in object literals definitely have positions: https://github.com/HaxeFoundation/haxe/blob/58e0b880edb7eb2b368d5b3db6daa6aba7cffd88/src/core/ast.ml#L211

Barring some off-by-one error, they can be used even from macros via the undocumented [`name_pos`](https://github.com/HaxeFoundation/haxe/blob/58e0b880edb7eb2b368d5b3db6daa6aba7cffd88/src/macro/macroApi.ml#L527) as seen here: https://try.haxe.org/#A39d1681 (on a side note, it seems like the macro doesn't even get called if there are duplicate fields).
