### ISSUE TITLE
[analyzer] code eliminates question

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#10972]
The book says that assuming `a` and `b` are active variables, but `c`  and `e` are not,
then finally both `e` and `c` can be eliminated. But after I running haxe I found that the last statement `c` still remains

```haxe
class Main {
	static function main() {
		var a = Std.random(100);
		var b = Std.random(100);
		var c = Std.random(100);
		var d = Std.random(100);
		var e = Std.random(100);
		a = b + c;
		b = b - d;
		c = c + d;
		e = b + c;
		trace(a + b);
	}
}
```
js output:
```js
	var a = Std.random(100);
	var b = Std.random(100);
	var c = Std.random(100);
	var d = Std.random(100);
	a = b + c;
	b -= d;
	c += d;  // Not eliminated
	console.log("src/Main.hx:16:",a + b);
```

**Comment by Simn** [comment]
The analyzer updates the reaching definition of all origin variables during SSA transformation, which essentially means that at the end, the reaching definition of the origin variable is the last definition seen. This is useful for the SSA algorithm itself, but following it during the mark phase of LocalDCE makes no sense because it would effectively consider all final definitions used.

I've changed it so that we make sure to mark the origin variable used (which is necessary in the general case because we transform everything back to the same variable), but don't explore explore its reaching definition. There's a chance that this breaks something I didn't consider, but we'll see!
