### ISSUE TITLE
Nested EitherType type inference

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10980]
```haxe
import haxe.extern.EitherType as Or;

typedef Callback = Or<
		Or<
			() -> Void,
			(a:Int) -> Void
		>,
		(a:Int, b:Int) -> Void
	>;

class Main {
	static function main() {
		final foo:Callback = a -> {
			$type(a); // Unknown<0> instead of Int
			return;
		}
	}
}
```

**Comment by Simn** [comment]
Note that this fix is specific to the local function situation, because that's the only place where we currently use my crazy unification matrix thing. It should be possible to construct cases where top-down inference like this fails for structures and other things, but I'd like to focus on the function situation as a kind of field test for the time being.
