### ISSUE TITLE
Compiler can't find something that exists?

### ISSUE THREAD

**Issue by swordcube** [HaxeFoundation/haxe#11011]
I'm having a very strange compiler error with a Haxe project i'm working on.

Error:
`Module engine.utilities.Signal does not define type Signal`

It thinks none of my Signal stuff exists, even though it does.
I don't really have much else to say because this started happening randomly.

If it helps here is the specific project shown in the screenshot:
https://github.com/swordcube/Funkin-Raylib

Here is the Signal.hx file itself:
[Signal.zip](https://github.com/HaxeFoundation/haxe/files/10957290/Signal.zip)

**Comment by Aurel300** [comment]
You closed the issue so I figure you resolved it but just in case: given your `Signal.hx` file I think what may have happened is that you entered macro context (e.g. by calling into a `macro` function) and then tried to resolve the `Signal` type from a macro context (e.g. by having a `Signal` local variable within the `macro` function, or even from an `import.hx` file), but the `Signal` type does not exist in the macro context, since it is only enabled `#if !macro`.

**Comment by swordcube** [comment]
yeah i fixed it by making the signal class always exist regardless of macro
