### ISSUE TITLE
[java] Source files are always placed in a "src/" directory

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11051]
https://github.com/HaxeFoundation/haxe/blob/b24ae6839db69a6d0b5df144ef1344010b074822/src/generators/genjava.ml#L2689

I'm trying to have Haxe generate the Java files into a workspace, so they can be picked up by another Java project, but the generated files are being placed in the wrong folder because the Java source generator is adding `src/` to the path at a low level.

**Comment by EliteMasterEric** [comment]
For the record, I ended up being able to modify the `build.gradle` in the project to point to the new location.

**Comment by Simn** [comment]
I think this is fair because from the generator perspective, the output directory is the one where the .jar ends up. Generators are free to use additional sub-directories, and the src/obj structure is quite common in this regard. IMO this should be addressed by some post-build action, or by configuring subsequent builds like you did.
