### ISSUE TITLE
[java] Haxe Enums incompatible with java.lang.Enum

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11080]
I have a extern function which takes, as an argument, a `Supplier<java.NativeArray<java.lang.Enum>>`.

```haxe
public static function fromEnum<E:java.lang.Enum<E>>(elementsSupplier:java.util.function.Supplier<java.NativeArray<E>>):net.minecraft.util.StringRepresentable_EnumCodec<E>;
```

This would presumably work fine with other extern enums, but I want to instantiate and use my own enum.

The problem is that I cannot get the Haxe->Java step to accept using Haxe enum values here. I get an error along the lines of `Expected java.lang.Enum, got MyEnum`.

This issue appears to be resolved on the JVM target ([see here](https://github.com/HaxeFoundation/haxe/blob/68280ac20dcf87fb6ff6f4ab4aaf284f485d9936/std/haxe/EnumTools.hx#L116), but due to #11016, and my use case requiring class files of a specific JDK version (a Minecraft mod), I am forced to use the Java source target.

**Comment by Simn** [comment]
I don't see us fixing this for the Java target. The base class for all enums is `HxEnum`, which is indeed not related to `java.lang.Enum`. It works on the JVM target because I considered it when designing enums, so the Haxe base class `jvm.Enum` extends `java.lang.Enum` explicitly.

Unless this is contributed by someone, it is unlikely that this will be addressed. I'll close the issue accordingly as not planned.
