### ISSUE TITLE
Please add some indicator at macro time for a `--run` situation.

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe#11085]
Currently `tink_syntaxhub` and `tink_runloop` depend on being able to parse out a `main` function to know what method to wrap with the top level functionality. 
This can't be achieved where `--run` is invoked. Would it be possible to add a define with the main class at macro time?

**Comment by tobil4sk** [comment]
Looks like the issue is that with `--run`, `Sys.args()` at macro time already returns the args passed to the script instead of the compiler arguments? https://github.com/haxetink/tink_syntaxhub/blob/master/src/tink/SyntaxHub.hx#L24-L30

Would the new `haxe.macro.Compiler.getConfiguration().mainClass` work?

**Comment by back2dos** [comment]
> Would the new `haxe.macro.Compiler.getConfiguration().mainClass` work?

Yup, that's great. I will look into using that.

> with `--run`, `Sys.args()` at macro time already returns the args passed to the script instead of the compiler arguments

I'd argue that's an issue, but a separate one: https://github.com/HaxeFoundation/haxe/issues/11087

**Comment by back2dos** [comment]
@0b1kn00b Lastest tink_macro uses `haxe.macro.Compiler.getConfiguration().mainClass` and latest tink_syntaxhub makes use of that ;)

**Comment by kLabz** [comment]
Sounds nice! Is there anything left to do here?

**Comment by back2dos** [comment]
Can be closed, I just don't have the permissions ;)
