### ISSUE TITLE
luv 0.5.12 broke compiler build

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#11116]
I tried to package haxe 4.3.0 for fedora, got the build error as follows:
```
File "src/macro/eval/evalLuv.ml", line 2392, characters 15-20:
2392 | 				"uid",vint p.uid;
       				           ^^^^^
Error: This expression has type Unsigned.ulong = Unsigned.ULong.t
       but an expression was expected of type int
```

full build log: https://kojipkgs.fedoraproject.org//work/tasks/258/99770258/build.log

I believe it's because of Luv 0.5.12, which was released just 3 days ago and it's not yet on OPAM: https://github.com/ocaml/opam-repository/pull/23652

**Comment by aantron** [comment]
Indeed, this is probably because of https://github.com/aantron/luv/pull/147/commits/8c39349b5cec89894ea7c3583ec45e57cb51deba, which is in turn because of https://github.com/libuv/libuv/commit/f3e0bffcb147fcda65c27007d276cc95ca084a18 upstream in libuv. You can convert an `Unsigned.ULong.t` to `int` using [`Unsigned.ULong.to_int`](https://github.com/yallop/ocaml-integers/blob/6aaa3e3d6e9bd52e9afa433de38d8c69debc97eb/src/unsigned.mli#L87). This is the only [breaking change](https://github.com/aantron/luv/releases/tag/0.5.12) in 0.5.12.

**Comment by andyli** [comment]
note: update `opam` in the source root to use `"luv" {>= "0.5.12"}` after fixing this

**Comment by Simn** [comment]
I just wanted to look into this, but my opam still only has `0.5.11`.

**Comment by aantron** [comment]
The release was merged into opam only five hours ago (https://github.com/ocaml/opam-repository/pull/23652), so maybe `opam update` hasn't picked it up yet.

**Comment by Simn** [comment]
Ah I see, I'm not very familiar with that process. Thanks!

**Comment by kLabz** [comment]
> The release was merged into opam only five hours ago ([ocaml/opam-repository#23652](https://github.com/ocaml/opam-repository/pull/23652)), so maybe `opam update` hasn't picked it up yet.

Any idea why it's still not available on windows? Not sure how to deal with this if we need different versions (and code) on windows and unix

**Comment by aantron** [comment]
Do you mean that the package Luv 0.5.12 does not appear in opam on Windows yet? Perhaps a stupid question from me, but has `opam update` been done? Is this in CI? Is there perhaps some kind of caching going on?

**Comment by kLabz** [comment]
Yes it's from CI with cache dropped and with `opam update`
https://github.com/kLabz/haxe/actions/runs/4729100602/jobs/8391262415 (don't mind the job not failing despite errors :sweat_smile:)

```
The following dependencies couldn't be met:
  - haxe -> luv >= 0.5.12
      no matching version
```

Could it be related to mingw?

**Comment by aantron** [comment]
It's possible. I'm not familiar with how packages are distributed on Windows at the moment -- haven't caught up on it yet, since the deprecation of opam-repository-mingw. I understand that https://github.com/ocaml-opam/opam-repository-mingw is the repo to look to now, but I don't know its status and whether it would pick up Luv 0.5.12. Luv 0.5.12 itself does support Windows to the best of my knowledge, so as long as you can get the actual tarball either from the main opam repo or perhaps even manually (if the opam repos have become too much of a mess), you should be able to install it and have it working.

**Comment by aantron** [comment]
@MisterDA, would you be able to comment on how distributing opam packages for Windows (MinGW) works now?

**Comment by MisterDA** [comment]
In any case, opam won't find the new package until its description has been merged into the opam-repository. Now that that luv has been submitted and merged to the opam-repository, it's just a matter of using the proper repository. There is <https://opam.ocaml.org> which gets synced to <https://github.com/ocaml/opam-repository.git> every couple of hours. If you always want the latest opam-repository, you can use the latter.

On Windows, we used to have <https://github.com/fdopen/opam-repository-mingw.git>. It contained the same packages as upstream opam-repository, with some patches for Windows compatibility. It was deprecated last August. As the two repositories started to drift, problems started to occur. For Windows, we now have an new [_sunset_](https://github.com/ocaml-opam/opam-repository-mingw) repository with updated package descriptions, and advice to fallback to the default opam-repository for newer packages. 

```yaml
uses: ocaml/setup-ocaml@v2
with:
  opam-repositories: |
    opam-repository-mingw: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
    default: https://github.com/ocaml/opam-repository.git
```

See [Sunsetting opam-repository-mingw](https://discuss.ocaml.org/t/sunsetting-opam-repository-mingw/11632) for more explanations and guidelines.

I suspect that your problem with constraints comes from using the deprecated opam-repository-mingw. Try switching to the sunset repo and add the default opam-repository.
