### ISSUE TITLE
Std.parseInt & Std.parseFloat do not account for number seperators

### ISSUE THREAD

**Issue by kinoko87** [HaxeFoundation/haxe#11110]
Inputting a number that has a number seperator (_) into the `parseFloat`/`parseInt` functions will strip anything after the underscore and then parse the number.

How to replicate: Pass a number with a number seperator into the `parseFloat`/`parseInt` functions.
Example:
```hx
var number = "100_000"
trace(Std.parseInt(number));

// Output: 100
```

Tested on:
* Haxe Interpreter, Linux Mint 21.1
* [try.haxe.org](https://try.haxe.org/#6c9FdB3D)

**Comment by tobil4sk** [comment]
Std.parseInt is for general integer parsing, so it's not 1-to-1 with how integer literals happen to work in the Haxe language. If you want to accept any valid Haxe integer literal, that's a separate use case outside the scope of parseInt.

Changing parseInt to accept `_` would also be a breaking change, since currently it ignores trailing text. This was discussed when the number separator was being implemented: https://github.com/HaxeFoundation/haxe/issues/10480

**Comment by kinoko87** [comment]
Ahh alright!

**Comment by Simn** [comment]
What he said

**Comment by Simn** [comment]
Uhm... timing!

**Comment by kinoko87** [comment]
LOL

**Comment by Aurel300** [comment]
@Simn We talked about this in #10480 already, but: if `Std.parseInt` and `Std.parseFloat` are not meant to parse the strings in `EConst(CInt(...) / CFloat(...))`, then there really needs to be some API for macros to do so. In that issue you just close with "this is fine" but I don't really see that…

**Comment by Simn** [comment]
Well this issue isn't about that, but I agree it would be good to have such functions.

**Comment by Aurel300** [comment]
Let's use this issue to track the missing feature then...
