### ISSUE TITLE
"static extern inline" should be allowed on extern interface methods

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11149]
```haxe
extern interface IMathOperation {
	public static extern inline function test():Void {
		trace("test");
	}
}
```

I would expect that this would compile successfully, but I instead receive the error `Invalid modifier: inline on method of interface`.

If I remove the `inline` keyword, I get the warning `Extern non-inline function may not have an expression`.

The `inline` keyword should be valid on interface functions, but ONLY if the method is `static` and the interface is `extern` (which is the only case where function bodies are allowed on interfaces).

EDIT: **Context**:

The reason I want to include an inline function on the interface is because I want to provide compatibility between version of the native library. In the newer version, the interface function of the extern library is used, but I want to use conditional compilation to point to the correct function on the older version.

**Comment by Simn** [comment]
Let us please keep interfaces code-free. We have rejected [default implementation in interfaces](https://github.com/HaxeFoundation/haxe-evolution/pull/70), and introducing an edge case for static inline does not seem worthwhile to me.

**Comment by back2dos** [comment]
> Let us please keep interfaces code-free. We have rejected https://github.com/HaxeFoundation/haxe-evolution/pull/70

That reasoning is flawed.

1. There's a fundamental difference between class objects and instances. There is no type relationship between class objects of related classes. That's for example why abstract classes may not have abstract static methods, because a subclass has no way of implementing them. In other words, even an abstract class has a concrete class object. Static members do not affect instances, so whether or not this is added has no effect on whether or not interfaces are code-free.
2. Default implementation is just as unrelated, because that too is about instances.

----

As for the merits of this feature, I have no strong opinions. I'm generally not a huge fan of global state or implementations, but then again I see no reason why interfaces should be excluded from this fabulous footgun. 

FWIW this was added in Java 8, C# 8 and PHP 7.4. 

Let's examine this not totally whacky example:

```haxe
interface Serializer {
  function serialize(value:Dynamic):String;
  static public var DEFAULT:Serializer = new NoneProvided();
  static public function run(value:Dynamic) return DEFAULT.serialize(value);
}

private class NoneProvided implements Serializer {
  public function new() {}
  public function serialize(value:Dynamic):String
    return throw 'Please provide a serializer implementation by setting Serializer.DEFAULT';
}
```

It's evidently not a total killer feature, in particular because it's easy enough to work around the limitations: 

1. making `Serializer` an abstract class (not always possible) 
2. having a separate class to hold `DEFAULT` (requires coming up with more names)
3. having a separate abstract over the interface, which can have static fields and other shenanigans (also requires coming up with names, but it's used in tink quite a bit, where typically `FooObject` is the interface and `Foo` is the abstract).
4. promoting the statics to module statics, where by `Serializer.run` and `Serializer.DEFAULT` will be global, e.g.: https://try.haxe.org/#C102e38D

Given the last possibility, I do wonder if it's really such a good idea to forbid the statics to be defined on the interface, if they can be defined on the module holding the interface as its primary type.

**Comment by Simn** [comment]
Yeah I shouldn't have mentioned that proposal... but now you're talking about an even more general feature, while this particular issue is just about `static inline`.

We can discuss this, but it likely requires its own haxe-evolution.
