### ISSUE TITLE
Q: Why can't EnumValue parameters be changed?

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#11227]
Sorry, this is just a question, but I figured here is a reasonable place to explain it:

I realized while working with `DISC(center:{ x:Float, y:Float }, radius:Float)` - the `center` is an object and so the `x` and `y` can be changed if you keep a reference to it. But `radius` cannot be updated, and I'd have to create a new `DISC` with the new radius value, which is unfortunate if I've already passed my `DISC` into some engine. Or I could change my codebase to something like `DISC(center:{ x:Float, y:Float }, { radius:Float })`, but that useless object is not very pretty, and these changes are syntactically tedious in every place it's used.

I'm guessing that in every implementation, `DISC` is some object, so radius _could_ be updated by the runtime. But is there something that relies on these values being unchangeable?

Is there a reason Haxe doesn't have either:

```
class Type {
  public static function setEnumParameter(e:EnumValue, parameter:String, value:Dynamic):Dynamic;
}
```

Or:

```
abstract EnumValue {
  public function setParameter(parameter:String, value:Dynamic):Dynamic;
}
```

If the `EnumValue` is assigned a constructor without the specified parameter, e.g. `RECTANGLE` has no `radius`, it could either throw or be undefined (therefor, wrapping it in a `Type.enumConstructor` check is required for safe usage.)

**Comment by back2dos** [comment]
I guess one reason is that Haxe's enums are modelled after OCaml, where they're immutable (although they can hold mutable refs for example). This comes with its own benefits.

As for adding reflection API to allow setting enum parameters, I think that's not such a good idea. On some platforms, parameters are stored by name (e.g. JS unless you use `-D js-enums-as-arrays`), on others by index (e.g. PHP). Whether you expect to set the param by name or value, it will be slow (even relative to normal reflection) on the platform that does it the opposite way.

If we therefore discard reflection and decide that enum params should still be mutable (not that I'm a fan, but let's explore the idea), the question is what would be a practical notation that allows for that. And it's not so easy to even come up with something. Say I have `haxe.ds.Option.Some(123)` and want to set that value to `321`. How do you express that? You can reference the enum value itself, and you can switch over that reference, but even when in a `case`, the compiler has the captured params on the one hand and the original reference itself, but nothing that points to the particular constructor, where you could say `myEnumValueThatIsSome.v = 321`.

As you've pointed out yourself, an alternative is to put mutable objects into the enum params. That sidesteps all limitations, including the above. I guess in OCaml this is syntactically a bit more convenient, as you would simply use a ref, which doesn't produce as much noise. I think you could model something of the sort with Haxe:

```haxe
@:transitive
abstract Ref<T>(haxe.ds.Vector<T>) {
  public var value(get, set):T;
    @:to inline function get_value() return this[0];
    inline function set_value(param) return this[0] = param; 
  
  @:from public inline function new(v)
    this = new haxe.ds.Vector(1, v);
}
// and now given this
enum Trololo {
  DISC(center:{ x:Float, y:Float }, radius:Ref<Float>);
}
// we can still write
DISC({ x: 1, y: 2 }, 3);
```

Of course you will have an extra allocation here. I wonder whether `DISC(params:{ x:Float, y:Float, radius:Float })` isn't "better" anyway ;)

**Comment by jcward** [comment]
Thanks for the thoughtful response, Juraj. :+1: 

Hmm, the inline-abstract doesn't want to be used in the same way Floats are used. https://try.haxe.org/#0a9E0727 :thinking:
- Cannot compare Float and Ref<Float>
- Assignment seems to be producing a new Ref<Float> instead of calling set_value :thinking: 

I tried some non-generic `@:to toFloat():Float` and sprinkling `@:generic` / `@:forward` but to no avail.

I had considered `DISC(params:{ x:Float, y:Float, radius:Float })` - but to me it feels somehow like side-stepping part of the essence of an enum - just dump all my data into one object. Essence aside, it affects all the syntax around matching and constructing.

I could write a function for the platforms I care about. Even with array or object, JS is easy. Not sure about hl / hxcpp, would have to research.

**Comment by back2dos** [comment]
> Hmm, the inline-abstract doesn't want to be used in the same way Floats are used.

Yeah. You should be operating on `ref.value` really. For operations on Ref, you could of course define all possible operators, if you're so inclined, but for setting the value, there's really no way around it ;) (short of convincing Simn that overloading`=` should be allowed).

> Even with array or object, JS is easy.

Sorta.

For starters, when enums are arrays, it's typically hard to actually even get a parameter name. You'll have to use native reflection capabilities to retrieve it on the function (and in JS it's not actually guaranteed to work - in fact, it's *guaranteed **not** to work* if you're minifying the code). I'm hesitant to believe that this is even possible on hl or hxcpp.

You could instead go by param index, which is more in line with how reflection with enums is typically done. That's rather expensive where enums are objects, e.g. JS, where it would be something like this:

```haxe
function setParam(v:EnumValue, index:Int, to:Dynamic) {
  var e = Type.getEnum(v);
	
  var name = (cast e).__constructs__[v.getIndex()].__params__[index];
  
  Reflect.setField(v, name, to);
}
```

There are quite a few lookups there, simply to get to a field name and then set the field by reflection again. This is is gonna be slow.

----

The thing is that at compile time (whether via macro or first class support), on most targets it would be quite straight forward to generate optimal code to update the param directly and remain type safe in the process. But that still boils down to even having a decent notation for this.

> to me it feels somehow like side-stepping part of the essence of an enum

I think you have that part backward. Enums are immutable by design. You're looking for a way to work around that essential property.

**Comment by jcward** [comment]
> This is is gonna be slow.

Yeah... probably better to just  pack my parameters into one object. At least then, DISC and RECTANGLE still imply the type of their respective params object.

Alright, thanks again. I owe you a drink next Haxe conference. :smile:  :beers:
