### ISSUE TITLE
Abstract @:op(a == b) not working on Haxe 4.3

### ISSUE THREAD

**Issue by AxGord** [HaxeFoundation/haxe#11240]
Working on Haxe 4.2, but not working on Haxe 4.3
```
trace(('': Attribute) == null); // Haxe 4.2 => true, Haxe 4.3 => false

abstract Attribute(String) from String to String {
	@:op(a == b) public function equal(b: Any):Bool {
		return this == b || (this == '' && b == null);
	}
}
```
With this comparison works: `@:op(a > b)`
And works if you specify that the type can be null: `b: Null<Any> - work`

**Comment by Simn** [comment]
Looking  at https://github.com/HaxeFoundation/haxe/commit/2467fce5d5dd6a7c8d333a2aa91e10408523e830, this appears to have been a bugfix related to `Any`. The new behavior is more consistent and now matches what you'd get when using `Dynamic` instead of `Any`.

I would like to check which commit caused this change though.

**Comment by Simn** [comment]
Rudy bisected it to https://github.com/HaxeFoundation/haxe/commit/eda6551f2b4fa3f0b80088eb39869d1b83f811d7. So yeah, I consider this better behavior now.
