### ISSUE TITLE
OCaml 5 compat

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#11271]
Fedora decided to upgrade OCaml to 5.x in their distro, thus we need to sort out OCaml 5 compat. A partial patch was provided in https://bugzilla.redhat.com/show_bug.cgi?id=2218692

Many other distros, and older versions of them, has only OCaml 4, so we need to support both OCaml 4 and 5 in some way.

If using a single code base is not possible to support both OCaml 4 and 5, we can maintain a seperate branch, such that I can generate patches from that branch for packaging purpose.

**Comment by kLabz** [comment]
What's the status for ocaml 5 on windows though?

(I have a branch somewhere where I started migrating to ocaml 5)

**Comment by andyli** [comment]
> What's the status for ocaml 5 on windows though?

No idea and that shouldn't be a problem if we maintain both OCaml 4 and 5 compat.

**Comment by kLabz** [comment]
That would be an issue if we can't have a single codebase compatible with both.

I'd like to migrate to ocaml 5 asap personally, as editor support is very minimal with < 5. There are also nice features :)

**Comment by kLabz** [comment]
I think we'll have to migrate away from `objsize` lib for this, but I'm not sure how to proceed to get the expected results in `memory.ml` using "new" std utils like `Obj.reachable_words`

**Comment by Octachron** [comment]
On the subject of the OCaml 5 Windows port, the mingw64 port is availble with OCaml 5.0.0, and the cygwin one will be available in the upcoming 5.1.0, however the MSVC port will take longer to reappear.

Concerning the `objsize` module, I would encourage you to document the haxe needs on the related PR https://github.com/ocaml/ocaml/pull/10031 since this is typically the kind of function that might work better in term of  backward-compatibility risk when hosted in the OCaml standard library.
