### ISSUE TITLE
Double `Null<T>` wrapping when inferring nullable type

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#11286]
```haxe
function main() {
	var a = null;
	if (a == null) a = 10;
	$type(a); // Null<Null<Int>>
}
```

**Comment by Simn** [comment]
With type inference the general case for this seems difficult to handle. Given that we allow `Null<?>`, the `?` can easily be bound to another `Null<T>` and then we have the double-wrapping.

Logically, the monomorph would have to know that it is already nullable in order to react to a `Null<T>` type being bound.

**Comment by nadako** [comment]
Probably a naive question, but can't this "just" be handled in the `unify` function?

**Comment by Simn** [comment]
I misjudged how silly the compiler is behaving here:

```haxe
function main() {
	var a = null;
	$type(a); // Null<Unknown<0>>
	a = null;
	$type(a); // Null<Null<Unknown<0>>>
	a = null;
	$type(a); // Null<Null<Null<Unknown<0>>>>
	a = 10;
	$type(a); // Null<Null<Null<Int>>>
}
```

Will have to look into what exactly happens. This might be about `null` literals in particular.

**Comment by Simn** [comment]
This is something for the bugfix release!
