### ISSUE TITLE
[Hashlink] Wrong JSON array parsing

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#11284]
When trying to parse array and print the results, hashlink failed with ```Build failure```
Example code ( https://try.haxe.org/#AdC9CB10 ) 
```haxe
var text:String = '[{"age":12 },{"name":"Bob", "age":42},{"name":"John", "age":24}]';
var data =  haxe.Json.parse(text);
trace("Data: "+data[0].age);
```

**Comment by Simn** [comment]
This isn't really about JSON, except for the fact that `Json.parse` returns `Dynamic`. Because we don't bind that to monomorphs, `data` remains one and the `data[0].age` access then infers it to be `[Var data<3492>:Array<{ age : String }>]`.

I don't know what to fix here. This keeps coming up in the context of `Json.parse`, but the typer's behavior isn't exactly wrong here...

**Comment by aemorax** [comment]
@Simn 
This is not the case of json being parsed wrong.
If you trace the variable itself trace will output it correctly.

The problem is probably because of "Data: " (String) + Dynamic concatenation.

Take this for example:
```haxe
var data =  haxe.Json.parse(text);
trace("Data: " + Std.string(data[0].age));
```
Will run.

**Comment by snsvrno** [comment]
When using `Std.string()` you are telling haxe that it should get a string and then it know what to do.

The problem is that since it's an anonymous type (`data`), you're accessing members that the compiler has no idea if they exist and doesn't know how to type it.

If you did

```haxe
var age = data[0].age;
trace("Data: " + age);
```

It would still not work, but if you did

```haxe
var age : Dynamic = data[0].age;
```

It will build.

I think haxe wants to be a statically typed language. There are some allowances to allow otherwise (`Dynamic`), but I don't think a way that fixes this aligns with haxes goals.

I agree with I don't know what the solution to this would be.

**Comment by aemorax** [comment]
I think a fix would be available for Haxe stdlib since `@to` and `@from` metadata for abstracts has been introduced.

Here in `StdTypes`:
https://github.com/HaxeFoundation/haxe/blob/7d5430119155b680e8f378fbdcbc221765d18bb3/std/StdTypes.hx#L105C1-L105C49

Maybe this would be a solution:
``` haxe
@:coreType @:runtimeValue abstract Dynamic<T> {
  @:to
  inline function toString() : String {
    return Std.string(this);
  }
  ...
}
```
Although in lots of cases these kind of implicit casts do not work.
