### ISSUE TITLE
No hover/definition for overload call

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#11285]
```haxe
using Main.MathTools;

function main() {
	var float = 0.0;
	var int = 0;
	float.wrapAround(0, 1);
	int.wrapAround(0, 1); // no hover
}

class MathTools {
	extern overload public static inline function wrapAround(v:Int, min:Int, max:Int):Int {
		var range = max - min;
		return min + (((v - min) % range) + range) % range;
	}
	extern overload public static inline function wrapAround(v:Float, min:Float, max:Float):Float {
		var range = max - min;
		return min + (((v - min) % range) + range) % range;
	}
}
```
```
Request textDocument/hover failed.
  Message: Could not find a suitable overload, reasons follow
```
Also, if you swap functions in `MathTools`, then both calls will fail for hover.

**Comment by Simn** [comment]
From an initial investigation, the problem appears to be related to `MCall`. It holds the two actual call arguments, but the full call needs the initial self-argument as well in order to succeed, which means that all overload attempts fail with "not enough arguments".

I don't know yet why it works for Float version, I'd expect it to have the same behavior here. So there's likely another problem in play.
