### ISSUE TITLE
No completion because of wrong type errors

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#11422]
```haxe
class Main {
	static function main() {
		var string = "";
		foo(0.0, s|);
	}

	static function foo(a:Int, name:String):Void {}
}
```

**Comment by Simn** [comment]
When I see this I'm always tempted to just ignore all other arguments in calls and only deal with the one that we want to have completion for, but in the general case we shouldn't do that:

```haxe
class Main {
	static function main() {
		var i1 = 1;
		var s = "foo";
		var i2 = 2;

		eq("foo", |)
	}

	static function eq<T>(e1:T, e2:T) {}
}
```

Here we want toplevel completion to prioritze `s` over both `i1` and `i2` because we know that we expect a string. This only works if we unify the first argument in order to bind `eq.T` properly.

So the real solution is to recover from the typing error somehow. I'm not sure why this one is so special that it kills all completion.
