### ISSUE TITLE
[cpp] Enums: wrong `catch` branch and `Std.isOfType` is always `true`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#11442]
```haxe
class Main {
	static public function main() {
		trace(Std.isOfType(DummyCtor, haxe.ds.Option)); //prints true for cpp target
	}
}

enum Dummy {
	DummyCtor;
}
```

**Comment by Aidan63** [comment]
I wonder if I accidentally broke this with https://github.com/HaxeFoundation/haxe/pull/10476, I made some changes to what casts are generated with that, but it was quite a while ago.

**Comment by RealyUniqueName** [comment]
Nope. The issue exists even in Haxe 4.1.5, which was released long before your PR.

**Comment by RealyUniqueName** [comment]
`try...catch` also falls into wrong branch:
```haxe
try {
	throw DummyCtor;
} catch(e:haxe.ds.Option<Dynamic>) {
	trace('wrong catch'); //this one gets executed
} catch(e:Dummy) {
	trace('correct catch');
}
```
prints `wrong catch`

**Comment by Aidan63** [comment]
I've just had a look at this and from what I can tell generated enums are never given a unique `_hx_ClassId` like generated classes are. This means any type checking involving enums is really just checking if its an enum in the first place since it falls back to checking `hx::EnumBase_obj::_hx_ClassId` which is always `hx::clsIdEnum`.

I'm having a play around now to see if its as simple as copying the class id generation for enums.
