### ISSUE TITLE
Enum comparison

### ISSUE THREAD

**Issue by acarioni** [HaxeFoundation/haxe#11536]
When enums with argument are compared, the compiler rightly complains. 
But why is the compiler behaviour different when the comparison is between two enum variables?

For example (in Haxe 4.3.3)

```
enum E { A(x: Int); B(y: Int); }

function f(a: E, b: E) {
  // return A(1) == B(2); Error: You cannot directly compare enums with arguments. Use either `switch`, `match` or `Type.enumEq`
  return a == b; // No error
}
```

**Comment by kLabz** [comment]
It's comparing references in this case

**Comment by acarioni** [comment]
Ok, I understand. However I think it’s a little misleading. 
Since enums are value objects, I would expect the compiler to compare the values as it does with strings.

**Comment by Simn** [comment]
The concept of value objects doesn't really exist in Haxe. String is the only case of a class that is compared by value, and that aligns with many of our run-times.

Haxe emits an error in your original example because any such comparison will always be `false`, but it can only know that if you explicitly use the constructor expressions.

So there's nothing to fix here. Comparing enums by-value would require substantial work on the target run-times which I don't think can be justified,
