### ISSUE TITLE
Issues with haxe in 4.3.4-2

### ISSUE THREAD

**Issue by kralle333** [HaxeFoundation/haxe#11652]
After upgrading haxe from 4.3.3-1 to 4.3.4-2, haxelib would no longer work for me, showing some weird behaviour:
![image](https://github.com/HaxeFoundation/haxe/assets/5738476/cb95b366-4316-46cc-b0e9-4a0476d773b6)

I see the same error `Uncaught exception - load.c(181) : Module not found : list` when I try to build with haxe.

Im on EndeavourOs, x86-64 if that is any help.

**Comment by tobil4sk** [comment]
Hi, I've come across this issue as well and I'm working on the upstream patch here: #11653. I have a patch for the Arch package as well, but I cannot submit it because account creation is restricted for the Arch gitlab (I'm in the process of contacting support for an account).

In the meanwhile, you can either revert to the previous version, or I've attached a [patched version of the package files](https://github.com/HaxeFoundation/haxe/files/15200093/haxe-arch-package-src.zip) if you're comfortable building it yourself.

**Comment by tobil4sk** [comment]
I've opened a bug report here on the Arch gitlab: https://gitlab.archlinux.org/archlinux/packaging/packages/haxe/-/issues/2

Along with a merge request: https://gitlab.archlinux.org/archlinux/packaging/packages/haxe/-/merge_requests/2

**Comment by RMSPORTS1902** [comment]
diff --git a/Makefile b/Makefile
index a369415b0..632744313 100644
--- a/Makefile
+++ b/Makefile
@@ -106,8 +106,10 @@ endif
 
 # haxelib should depends on haxe, but we don't want to do that...
 haxelib:
-	(cd $(CURDIR)/extra/haxelib_src && $(CURDIR)/$(HAXE_OUTPUT) client.hxml && nekotools boot run.n)
-	mv extra/haxelib_src/run$(EXTENSION) $(HAXELIB_OUTPUT)
+	cd $(CURDIR)/extra/haxelib_src && \
+	HAXE_STD_PATH=$(CURDIR)/std $(CURDIR)/$(HAXE_OUTPUT) client.hxml && \
+	nekotools boot -c run.n
+	${CC} $(CURDIR)/extra/haxelib_src/run.c -o $(HAXELIB_OUTPUT) -lneko
 
 tools: haxelib

**Comment by tobil4sk** [comment]
The patch for the Arch package has been merged and a new version has been released, please update your packages.

**Comment by kralle333** [comment]
thanks!
