### ISSUE TITLE
Confusing deprecation warning when using `--jvm out.jar`

### ISSUE THREAD

**Issue by FeldrinH** [HaxeFoundation/haxe#11737]
Following the example in https://haxe.org/manual/target-jvm-getting-started.html I created a Main.hx file and ran the following command:
```bash
haxe --jvm bin/Main.jar --main Main
```
This produced the following output:
```
Warning : (WDeprecated) --java out.jar -D jvm is deprecated; use --jvm out.jar directly
```
As far as I can tell I am not using `--java out.jar -D jvm`, so why am I getting this warning?

Tested with Haxe 4.3.5 on Windows 10.

**Comment by Simn** [comment]
> so why am I getting this warning?

Evidently because we're idiots: https://github.com/HaxeFoundation/haxe/commit/100fcbbea15678509154c0f071705b9f6a4170ae

The argument parser sets the platform to `Java` and adds the `Jvm` define, and then the `generate` function warns about that exact situation.

Looks like it's time for 4.3.6 soon @kLabz!

**Comment by kLabz** [comment]
:facepalm:
