### ISSUE TITLE
Unsupported recursive type only errors on hashlink

### ISSUE THREAD

**Issue by PXshadow** [HaxeFoundation/haxe#11839]
```haxe
function main() {
	var i:F = null;
}

typedef F = String->F;
```

https://try.haxe.org/#92773A15

Analyzer optimize: no
Latest nightly Haxe

**Comment by Simn** [comment]
On JVM this defaults to `String -> Object` which is arguably worse than simply erroring... I'm inclined to match HL's behavior here because it's unclear to me what this should even generate. (Edit: actually this just ends up as `haxe.jvm.Function`, so there's no reason to error.)

On C++ this also becomes `Dynamic i`.
