### ISSUE TITLE
Unclosed monomorph

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#11881]
Below code compiles fine:

```haxe
var logs = [];
for (l in logs) {
    logs.push(l.msg);
}
```

But when going through hxb writer (so compiling through compilation server), writer attempts to close the monomorph, which results in an (uncaught) unification error:

```
Recursive type
Unknown<0> appears in { msg: Unknown<0> : { msg : Unknown<0> } }
```

Ideally, we should not reach hxb writer with unclosed monomorph.

**Comment by Simn** [comment]
This made me doubt my sanity for a while. The compiler would report that there are two monomorphs:

1. The `logs` one, which was `Array<Unknown<0>>`
2. The array parameter one, which was `Unknown<0>`

The parameter one was printed as `{ msg: Unknown<0> : { msg : Unknown<0> } }`, which is the recursive constraint. However, when closing it the compiler would tell me that it was already bound to a type, so nothing happened.

Turns out there's a _third_ monomorph involved here, which is the one from the `l.msg` field access. The new and improved `@:debug.mono` now shows all 3:

```
   0: Unknown<0> : { msg : Unknown<0> } (5:13)
   1: Unknown<1> := Unknown<0> (unknown)
   2: Unknown<2> := Array<Unknown<0>> (3:2)
```

It's not clear to me why that third monomorph exists at all, given that we already have one. For now I've made sure that the function context knows about it, so that it closes it and errors.

Edit: Right, the third monomorph isn't about the expression we're accessing on, but about the field we're accessing. We have no information about that here so spawning a monomorph is correct.
