### ISSUE TITLE
Lambda should support Iterator<T> as well as Iterable<T>

### ISSUE THREAD

**Issue by bji** [HaxeFoundation/haxe#1914]
It's not possible to do this with Lambda although it would be nice:

var sm = new StringMap<String>();
sm.set("One", "Two");
sm.set(Three", "Four");

var arr = Lambda.array(sm.keys());

The reason that this is not possible is that Lamda.array takes an Iterable instead of an Iterator.  But you can't get an Iterable from an Iterator, and StringMap.keys() can only give an Iterator, not an Iterable.

Unfortunately Haxe does not support polymorphism on function names so you can't just also declare a version of Lambda.array that takes a Interator<T>; a name other than array has to be used.  What is a good candidate for a name?  Not sure ...

**Comment by ncannasse** [comment]
This thread is quite old already, and after reading again through it I'm not satisfied with any of the solutions that came up, so I prefer to keep the status quo here.

**Comment by scriptorum** [comment]
I prefer @bji's solution, since I think an iterator is logically also Iterable. Lamba.iterable() would be a welcome step; I've used a wrapper class to make an Iterator iterable:
```haxe
class Iter<T> {
	private var iter:Iterator<T>;
	public function new(iter:Iterator<T>) { this.iter = iter; }
	public function iterator():Iterator<T> { return iter; }
	public static function make<T>(iter:Iterator<T>): Iter<T> { return new Iter<T>(iter); }
}
```
```haxe
Lambda.array(Iter.make(map.keys()));
```
Also, it's slower because it has to loop through the values, but Lambda.list will arrive at the same result.

**Comment by ncannasse** [comment]
An iterator is not iterable because it would require to be able to clone it, and the semantics of cloning after several values have been already iterated can be misleading : do we clone the "full" iterator, or the current one ? What if the data structure was modified during the process ?

**Comment by scriptorum** [comment]
I think I understand your concern: if an Iterator supports Iterable, does myIterator.iterator() return myIterator itself, or call the original data source to create a fresh iterator? And more importantly, *does a method so named create the expectation that it will do the latter*? Personally, I wouldn't think so, but I get your point. I'd also be happy with your Lambda.iterable().

**Comment by vrescobar** [comment]
That's still broken, I am a new user and I spent some time with this issue because I can't use lambda with map.keys() out of the box; also fails by using static extensions. I even [posted a dummy question](http://stackoverflow.com/questions/32844086/usage-of-lambda-filter-in-haxe-typed-iterables-or-equivalent-functional-constr) in stack overflow about it.

The static extension of lambda is still not better; mostly because the "solution" is to transform the data structure in an array or whatever that fits the signature, but then still everything needs to be iterated as much times as transformations are required in the data structured.

Several functional languages work with lazy iterators and return lazy iterators as output by default instead of consume them by default; it makes possible to chain series of transformations without spend unnecessary cycles of CPU.

*My proposal:* I would suggest to create a whole new Lambda API and keep the old one for backward compatibility until haxe4 is there and then make disruptive changes. The new API should be updated to match the latest functional constructs and technics, including laziness by default and *fully compatibility with the default iterables and iterators present in the haxe standard library*.

For sure that's some work and a lot of fun,... but I don't find acceptable in 2015 (especially in comparison with all new programming languages which exploit those functionalities much better) that a construct looking like that would need to loop 3 times (actually haxe could optimize via macro inlining the functions as single loop). 

    var keys:Map<Int,Int>;
    // productive code
    a = [for (i in keys.keys()) i].filter(function(k:Int) { return keys.exists(k); }).filter(function(k){ return k>=65;});


P.D. However Haxe is still a nice language and that is a feature typical of functional programming languages (and in my opinion Haxe should be functional enough to be named multiparadigm as it is from time to time described).

**Comment by waneck** [comment]
You can already do that in a single loop:
```haxe
var keys:Map<Int,Int>;
// productive code
a = [for (i in keys.keys()) if (keys.exists(k) && k >= 65) i];
```

**Comment by yar3333** [comment]
Stop frustration and use [stdlib](http://lib.haxe.org/p/stdlib/) library after all! :)
```haxe
using stdlib.Lambda;
...
var arr = map.keys().array();
var arr = map.keys().sorted();
...
```

**Comment by markknol** [comment]
While we are still slightly offtopic, You can also use array comprehension along with functions and type inference for small output but readable code. This does not use the "real" lambda.filter or array.filter functions, so there is only one loop, and thanks to the inlining, no actual function calls in runtime.

```haxe
var values = [1,2,3,4,5,6,7,8,9,10];
// productive code
inline function filter(v) return v > 5;
inline function map(v) return v*v;
var a = [for (v in values) if(filter(v)) map(v)];
```

**Comment by vrescobar** [comment]
thank you for the answers on list comprehensions, they are so handy... however I find there is a gap which can only be filled with lambda and lazy map/reduce; especially while using lists of transformations that can be partly applied to collections (especially while doing compositions).

Perhaps you are right @yar3333 and I should take a deeper look to the stdlib before reimplement the wheel.
