### ISSUE TITLE
Macro cache does not work with -swf-lib

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxe#1946]
Step 1. Create file `L.hx`
```
class Library {}
```

Step 2. Create Library.swf
```
haxe L.hx -swf Library.swf
```

Step 3. Create file `Macro.hx`

```
import haxe.macro.Expr;
import haxe.macro.Context;
class Macro
{
	#if haxe3 macro #else @:macro #end public static function checkCache():Expr
	{
		Context.warning("Not cached!", Context.currentPos());
		return macro null;
	}
}
```

Step 4. Create file `Main.hx`

```
import Library
class Main
{
	public static function main()
	{
		Macro.checkCache();
	}
}
```

Step 5. Start a haxe server

```
haxe --wait 6000
```

Step 6. Compile Main.hx

```
$ haxe -swf Main.swf -swf-lib Library.swf --connect 6000 -main Main
Main.hx:6: characters 2-20 : Warning : Not cached!
```

Step 7. Compile Main.hx again

```
$ haxe -swf Main.swf -swf-lib Library.swf --connect 6000 -main Main
Main.hx:6: characters 2-20 : Warning : Not cached!
```

I expect the `Not cached!` warning disappears at step 7, but the macro is evaluated again, and the waring appears again.

I tested this issue on Haxe 3 and Haxe 2.11 r5884, the the macro cache does not work on both versions.

**Comment by ncannasse** [comment]
Ok, that was something that was not implemented in the original compiler cache. Now it should work nicely. The only drawback is that because we need to make sure that the type comes from the same library as previous compilation, we are still required to read the SWF (or JAR / DLL for Java/C#) and build the module.

Also, as a consequence, if the extern module structure has been changed but the referenced library file has not, we will not be able to detect a change and will keep the cached version.

I don't think that's something that will happen unless @cwaneck build different modules depending of flags that are not integrated into the compiler cache key that already includes defines.

**Comment by ncannasse** [comment]
Sorry, I was meant to call @waneck :)
