### ISSUE TITLE
Haxe doesn't show completion for Haxe macro functions

### ISSUE THREAD

**Issue by as3boyan** [HaxeFoundation/haxe#2072]
I am using FlashDevelop and Haxe doesn't show completion for macro static public functions

**Comment by sebpatu** [comment]
I don't think theres a way to ask the compiler to specifically give completion in macro context. It always give completion in non macro context, and theres no compiler option that asks the compiler to only handle macro context, so that we could get the associated completion infos.

thats an issue for IDE and completion in macro context.

we need:
wether, compiler gives all completion infos, macro and non macro context
wether, we have a compiler option to display macro context completion, and by default it gives (a today) non macro context completion

**Comment by ncannasse** [comment]
There shouldn't be any difference between compilation server and compiler mode. Please report a small reproducible example not involving any third party library if you find some.

@sebpatu compiler should be able to give completion in macro context too

**Comment by sebpatu** [comment]
For me its same behavior between compilation server and compiler mode.
But i was able to reproduce my issue with simpe code and it shows the 
inconsistency:

If i get this code in one single source file:
class TestMacro {
     public static function test0():Void {}
     macro public static function test1():Void {}
     #if macro
         public static function test2():Void {}
     #end
}

class Test {
     #if macro
     static function main() {
         trace("Haxe is great!");
         TestMacro.|
     }
     #end
}

Completion will correctly show me test0, test1 and test2.
But if i separate the TestMacro  class definition in another file, same 
package, completion will only gives test0, test1 and forget test2.

i do the test in flashdevelop, with not mixed completion settings.  i 
get same result with compiler, and completion server settings.
