### ISSUE TITLE
Compiler Message Quality : Unknown Identifier

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#2087]
Some messages of the haxe compiler can prove obscure and or misleading.

class Main{
	public static function main(){
		
		
		trace( haxe.GetResource.getString("some_tiles") );
               //should be trace( haxe.Resource.getString("some_tiles") );
                //there is a type in haxe.GetResource
		//message is ./Main.hx:6: characters 9-35 : Unknown identifier : haxe
		
	}
}

Here the haxe identifier is valid but error suggest it is not, this use case should be enhanced as it is a common error for beginner.
We can enhance it with something like : 
Cannot find identifier *haxe.GetResource* either *GetResource* is not member of *haxe* Package either haxe.GetResource is not defined.
Thanks.

**Comment by jcward** [comment]
Sorry for commenting on an old old issue, but I just got `Unknown identifier : haxe` for accidentally mistyping `haxe.Callstack` instead of `haxe.CallStack` -- it was very confusing, because I know `haxe` is defined, and I didn't notice the subtle `S` capitalization error. The compiler usually has very helpful suggestions, but definitely not the case here.

It's a user error, but perhaps a common one, and the kind that could be frustrating.

**Comment by Simn** [comment]
I made the change that I mentioned [here](https://github.com/HaxeFoundation/haxe/issues/2087#issuecomment-24879606). The logic seems designed for `Unknown_ident` to be raised, but by turning it into a display error that part was never properly executed. I'm not 100% sure if this has any undesired side-effects for other errors.

**Comment by delahee** [comment]
thx ! ( I laughed at the MORDOR comment so hard... )
