### ISSUE TITLE
In some cases super constructor does not called

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#2117]
Tested in js. Minimal source code files:
```
// Base.hx
@:autoBuild(Macro.build()) class Base
{
	public function new() : Void
	{
		trace("base");
	}
}
```
```
// BaseChild.hx
class BaseChild extends Base {}
```
```
// BaseChildChild.hx
class BaseChildChild extends BaseChild {}
```
```
// Empty.hx
```
```
// Macro.hx
class Macro
{
	public static function build() : Array<haxe.macro.Expr.Field>
	{
		haxe.macro.Context.getModule("Empty");
		return null;
	}
}
```
```
// Main.hx
import BaseChildChild;
import BaseChild;

class Main 
{
	static function main() {}
}
```

Compile:
```
haxe -cp src -js bin/index.js -main Main
```

Generated js:
```
(function () { "use strict";
function $extend(from, fields) {
	function inherit() {}; inherit.prototype = from; var proto = new inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var Base = function() {
	console.log("base");
};
var BaseChild = function() {
	Base.call(this);
};
BaseChild.__super__ = Base;
BaseChild.prototype = $extend(Base.prototype,{
});
var BaseChildChild = function() { }
BaseChildChild.__super__ = BaseChild;
BaseChildChild.prototype = $extend(BaseChild.prototype,{
});
var Main = function() { }
Main.main = function() {
}
Main.main();
})();
```

Error in line
```
var BaseChildChild = function() { }
```
As you can see, super constructor does not called.

**Comment by ncannasse** [comment]
I had a look at this one in depth.
The problem comes from this line in `typing_timer` (which wraps `Interp.get_module`):

```
	if ctx.pass < PTypeField then ctx.pass <- PTypeField;
```

Here, we will put our context in "typing" mode, which will have the effect of flushing all pending unbuilt classes (including BaseChildChild) WHILE we are still building our BaseChild.

That's quite a general problem in our pass system which for simplicity reason does not track all the required dependencies between modules so will flush all the types at a given stage. Usually typing is quite ordered (parsing, building modules, building classes structures, typing fields), but build macros that use Context.* methods might do some field typing while we haven't yet built all the classes structures.

In this example this will trigger the building of class BaseChildChild while BaseChild constructor has not yet been defined (we're still in autobuild macro !). As a consequence, we do not generate an inherited constructor since BaseChild has not at this point

A partial solution would be to prevent child classes from being built while parent class is still ongoing built. That seems a fair restriction wrt macros.

**Comment by yar3333** [comment]
Thank you, Nicolas, It was important for me!
