### ISSUE TITLE
Allow "conflicting" typedefs if they are the same

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#2324]
The concrete use case:

- [tink.CoreApi.Outcome](https://github.com/haxetink/tink_core/blob/master/src/tink/CoreApi.hx#L7)
- [tink.MacroApi.Outcome](https://github.com/haxetink/tink_macro/blob/5f17f870a11a786473922c4ac41b60054f4a8b70/src/tink/MacroApi.hx#L13)

Jason renamed some stuff to avoid the conflict, but it's not really the optimal solution.

Any chance of allowing this (really just for typedefs that point to the same type)?

**Comment by ncannasse** [comment]
I agree with @Simn, that's not worth the change.

**Comment by back2dos** [comment]
I agree with the conclusion, but I question the premise. I don't really understand why [at the place where the error is produced[(https://github.com/HaxeFoundation/haxe/blob/e01fbc4ec0870e626810ea6f83d912b80e12aebc/typeload.ml#L2471), you cannot check if the two equally named types resolve to the same type.

It would also allow avoiding useless types like this: http://api.haxe.org/haxe/macro/TExprTools.html

In the end, such modules as `haxe.macro.Tools` are a nice way to allow pre-bundling import and using statements. And I think it's just stupid to have to dance around this kind of limitation, when it shouldn't be hard to lift.

**Comment by ncannasse** [comment]
In order to compare if they are the same type, you need to follow it, and you're not allowed to do so while you're building the module (which we are doing in decl_type).

We could ignore the error here and add a delay that check the structure and raise an error, but that might cause confusing errors for the user in case the types are not the same actually

**Comment by kevinresol** [comment]
What if we only allow typedef that follows to the other type? Such that the compiler doesn't need to mess with type unification.

e.g. The following is disallowed:
```haxe
// mypack/File1.hx
typedef Foo = String;

// mypack/File2.hx
typedef Foo = String;
```
Because ultimately the compiler need to try unifying String and String.

While the following is allowed:

```haxe
// mypack/File1.hx
class Foo;

// mypack/File2.hx
typedef Foo = mypack.Foo;
```

Because following the typedef will brings you to the name-clashed type, and no unification is needed.

**Comment by back2dos** [comment]
Yeah, this still comes up ^^

I suppose another alternative would be if a module could `export` another type, that gets imported if you import the module (same for `using`). Would have more of a chance to be added?
