### ISSUE TITLE
Flash interface default params

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#2431]
From decompiling, it looks like the default value of params are not being compiled into interface definitions. This seems to trigger an issue when AOT compiling using AIR, where calling f() on an Iface produces the wrong default value (aduros/flambe#203).

``` haxe
// haxe -main TestMain -swf out.swf

interface Iface {
    // param is compiled as optional, but no default value included 
    function f (param :Float = 666) :Void;
}

class Impl implements Iface {
    // param is compiled as optional WITH correct default value
    public function f (param :Float = 666) {
    }
}

class TestMain
{
    private static function main ()
    {
    }
}
```

**Comment by ncannasse** [comment]
@Simn what's your take on this ? I still think we should forbid default value in interfaces, since they most likely can't be enforced anyway. But at the same time, using a default value is the only way to make a not Null type for a basic type with an optional param.

**Comment by Simn** [comment]
Given that by design default values are only relevant in the function that is actually called (at run-time) I don't think interface default values make much sense. They could even give the wrong impression that they might be applied at call-site or something.

The self-documentation argument is a bit misleading as well for the same reasons: You can never be sure what default value is actually going to be used unless you look at the actual implementation function.

**Comment by ncannasse** [comment]
Looking at this again (not flash specific).

It is currently necessary on static system to be able to declare the following:
```
interface F {
	function foo(x:Int=0) : Void;
}

class A implements F {
	public function foo(x=0) {
	}
}
```

Because there a difference between `?x:Int` and `x:Int=0` , the first one being `Null<Int>` and not the other. 

ATM This correctly compiles and seems to work ok. The only thing wrong I can see is that in the dump output the F.foo x is not written as optional, although calling F.foo() seems to work as expected.

**Comment by Simn** [comment]
We should disallow default values on interfaces because they are misleading.

Can the problem you describe be reproduced with overrides as well?

**Comment by Simn** [comment]
I've looked at this again and now understand your previous comment better. It is indeed not possible to say "optional, non-nullable argument" without specifying a default value.

However, the real problem here still seems to be that `?x:Int` automatically becomes `?x:Null<Int>`. I find it very strange that we overrule an explicit type-hint like that...

**Comment by Simn** [comment]
I would like to change it so that `?x:Int` does not change the type to `?x:Null<Int>`. Any objections?

**Comment by ncannasse** [comment]
That's a pretty big change, can we open a specific issue to discuss it ?

**Comment by Simn** [comment]
#6972
