### ISSUE TITLE
Support ECMAScript 5-style JS properties

### ISSUE THREAD

**Issue by lptr** [HaxeFoundation/haxe#2469]
When I have some Haxe code like this:

```haxe
class SomeClass {
	var length (get, never):Int;
	
	function get_length():Int {
		return 5;
	}
}
```

I'd like to get it compiled into this:

```JavaScript
// ...
    Object.defineProperty(SomeClass.prototype, "length", {
        get: function () {
            return 5;
        },
        enumerable: true,
        configurable: true
    });
// ...
```

IMO it should also support `default` getters and setters.

TypeScript is a great example of how this could work:
http://blogs.microsoft.co.il/gilf/2013/01/22/creating-properties-in-typescript/

**Comment by yar3333** [comment]
I think a good solution is made support of @:property for js and add compiler option (define?) to switch compiler into new/old mode (always generate native properties/generate legacy properties).

**Comment by ncannasse** [comment]
Looking again at this : from a pure Haxe point of view, it does not make much sense to add support for this because it's not bringing anything new. So it's only useful when for instance you want to keep the way to access the property directly in JS. But then again, that will cause some issues with our specification which allows to read the variable in the getter and write it in the setter (this would cause infinite loops with native properties, and require some renaming).

A macro could extract the properties and the Object.defineProperty call can be done at runtime, according to the end-user custom wishes to handle native properties.

I think we should then close.

**Comment by yar3333** [comment]
For those, who want to have native js properties now, I write a simple macro library http://lib.haxe.org/p/jsprop (https://bitbucket.org/yar3333/haxe-jsprop).
