### ISSUE TITLE
Iterator not a function in wrappped content.

### ISSUE THREAD

**Issue by pshtif** [HaxeFoundation/haxe#2603]
Hi guys I run into a curious Haxe problem, when I have this code inside a swc which is than used in AS3:

var a:Array<Int> = [];
a.iterator();

It will run ok in a standalone swf but in a wrapped content such as FGL sandbox it will throw an error that the iterator is not a function. If I trace it its obviously null but if I trace the Array.prototype.iterator its there.

Not sure if it is Haxe issue though, can anyone point me out what to do about it or if there is any workaround? This makes usage of Haxe swcs impossible as many game programmers publish their games inside various wrapped content like game portals.

Thank you

**Comment by bmfs** [comment]
@pshtif  Do you remember if calling the haxe.initSwc solved the issue?

**Comment by timdp** [comment]
I don't think `-D no-flash-override` (without the s at the end) will do much. Looking at [genswf9.ml](https://github.com/HaxeFoundation/haxe/blob/6e69281ba0b3b4f8ed4906be44df5b4a5a238dfb/genswf9.ml#L317), it only affects `Array.prototype.map`, `String.prototype.charCodeAt`, and `Date.prototype.toString`, and relates to overloading prototype functions rather than adding ones. Regardless, the issue is more broad: Flash just won't let you make any changes to the builtin prototypes in certain contexts.
