### ISSUE TITLE
VerifyError: Error #1053: Illegal override of x in x

### ISSUE THREAD

**Issue by polygonal** [HaxeFoundation/haxe#2712]
minimalistic example: (taken from https://github.com/polygonal/ds/blob/master/src/de/polygonal/ds/Heap.hx)

```haxe
class Item implements Heapable {}

interface Collection<T>
{
	function contains(x:T):Bool;
}

interface Heapable {}

class Heap<T:(Heapable)> implements Collection<T>
{
	public function new() {}
	
	public function contains(x:T):Bool
	{
		return false;
	}
}

class Main
{
	static function main()
	{
		new Heap<Item>(); //VerifyError: Error #1053: Illegal override of Heap in Heap.
	}
}
```

compile with ```haxe -swf main.swf -main Main``` using official 3.1.0 release

**Comment by hughsando** [comment]
The code can't be optimised as written with the interface because if you were to use a single generic class with 2 unrelated type parameters, the single implementation code would not know where to find the interface functions within the vtable - hence the name lookup.
An actual class could work as a base though - is this what you have done in flash?
This code in hxcpp is pretty ugly, and I would prefer to implement it with filters, which could be a bit risky.
