### ISSUE TITLE
JS Std inline functions do not appear inlined

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#2732]
Notably, Std.int () is flagged to be inlined, but appears in the JS output. As a result, Google Closure fails to minify the resulting JS, because it trips on finding "int" as a function name.

**Comment by nadako** [comment]
> Google Closure fails to minify the resulting JS, because it trips on finding "int" as a function name.

Any idea why is that? `int` is not a JS keyword, so what's the actual issue? Is it still relevant?

I'm asking, because our keyword list in genjs needs a cleanup, since now it basically consists of Java keywords, not JavaScript, which results in ugly code generation like `object["use"](...)`. Nicolas simply reverted the proper list back then in 4db89a8a1c55e905e31474e9549bffa34e3e4396, but I think we should handle this properly...

**Comment by nadako** [comment]
Oh I just found this document: https://mathiasbynens.be/notes/reserved-keywords, so these were indeed keywords in ES <=3. Nowadays tho the default ES version we output is 5, so I think we should remove es3 keywords from the list when `js-es` is >= 5.
