### ISSUE TITLE
Some UInt calculations aren't unsigned

### ISSUE THREAD

**Issue by shohei909** [HaxeFoundation/haxe#2736]
```hx
class MainTest {
	static public function main() {
		var a:UInt = 50000 * 50000;
		var b:UInt = 50000;

		trace(a); //2500000000
		trace(a / b); //50000 in flash and js, but -35899.34592 in neko
		trace(a > b); //true in flash and js, but false in neko
		trace(a == -1794967296); //compile error in flash, false in js, and true in neko
		trace(a % b); //0 in flash and js, but 4294950000 in neko, 
		trace(a >> 1); //-897483648 in flash, but 3397483648 in neko and js
	}
}
```

**Comment by ncannasse** [comment]
Seems to be a lot better now, but we still have this issue with shift behavior.
I think that we should have `UInt >> 1` use unsigned bit shift (and we need to document that since it's a change wrt 3.2).

@Simn could you fix it and write unit tests for this so we make sure we have same behavior everywhere ?

**Comment by Simn** [comment]
But `>>` leads to a negative result on Flash in the original example. If we use `>>>` and stick to UInt we will not have the same behavior on other targets. So I don't quite understand what you want me to fix here.

**Comment by ncannasse** [comment]
@Simn I was proposing to use `>>>` on all targets of course, so it's always signed.
In C there is only `>>`, the operation depends if the type is signed or not.

**Comment by Herschel** [comment]
Since Haxe has both >> and >>> operators, I think that the signedness of the shift should depend on the operator used, not on the operand type. This puts it in line with other languages with both >> and >>>.

**Comment by ncannasse** [comment]
@Herschel yes I actually started thinking about it just after posting my comment. Maybe we should stick to `>>` returning an Int and `>>>` keeping the type intact. @Simn would that work for you ?

**Comment by Herschel** [comment]
Looks like cs target is different here as well, UInt >> n results in an unsigned shift (above example returns 1250000000).

**Comment by ncannasse** [comment]
@Herschel ah now that's annoying, because that means we have on some platforms a different behavior on what people are used to...

**Comment by ncannasse** [comment]
Maybe taking the C side is better then. @waneck what about Java, and what's your take on this ?

**Comment by Simn** [comment]
The question is always if that's a problem with C# or with gencs.

**Comment by waneck** [comment]
On C# there is no unsigned shift operator; rather, >>> casts the left side
to UInt to be able to make it be unsigned.
So yeah, it's how C# deals with shifts. I'm not sure if it even makes sense
to have a signed operator to work on an unsigned type. It would make sense
for me that we simply forbid >> on UInt

**Comment by ncannasse** [comment]
@waneck given how it's hard to decice on a given behavior, forbidding is maybe the best solution indeed.

**Comment by ousado** [comment]
Following the principle of least surprise I'd (also?) vote for making >> an unsigned shift. Forbidding it would only force people to change >> into >>> in some places to make things compile, for no good reason. If there was a good use-case for >> being signed, that'd be different, but I highly doubt that anyone using UInt in the first place would want to perform signed shifts on it, and that an operators behavior depends on the types it's used with makes sense, IMO.

**Comment by ncannasse** [comment]
It was not supposed to be closed, and each new message on this thread makes me change my opinion. I'll sleep on it and look at it again this week with fresh mind

**Comment by Simn** [comment]
I'm leaning towards making >> "return" Int. That way it's completely user's choice.

**Comment by Simn** [comment]
... but I change my opinion about this on a regular basis as well.

**Comment by ncannasse** [comment]
As long as we don't agree then everything is normal :-)

**Comment by Herschel** [comment]
We had a discussion on IRC, here's the consensus:

The semantics of the shift operators are based on the operand type. >> maintains the sign of the value, >>> zero-shifts. Since UInt values have no sign, >> and >>> are the same for UInt, both zero-shift.

>>:
Int -> Int -> Int
UInt -> Int -> UInt

>>>:
Int -> Int -> Int
UInt -> Int -> UInt

We briefly discussed disallowing >>> for UInt, but decided to have >> and >>> mean the same to avoid people having to change >>> to >> everywhere for not much of a reason.

What do you think of this, @ncannasse ?

**Comment by ncannasse** [comment]
I seriously thought about it as well, but came to a different conclusion :)
First, regarding the types: I agree that the type should be conserved with bitshifting operations, so as you said both `>>` and `>>>` should return UInt when applied to an UInt.

But I think that we should also get the same result. For instance

`(0xFFFFFFFF >>> 1 = 0x7FFFFFFF) = 2147483647` for both Int and UInt
and
`(0xFFFFFFFF >> 1 = 0xBFFFFFFF) = 3221225471 (UInt) or -1073741825 (Int)`. The value is the same, only the way it's displayed changes.

That allows to switch between Int and UInt without changing the actual calculus being done, which is normal for bit operators. This way we specify that `>>` is an signed bitshift operator and that `>>>` is an unsigned one.

I think it actually makes more sense this way if you represent the value as bits, which is what the operator does (operates on bits).

**Comment by Simn** [comment]
We have updated our consensus in the sense that nobody cares enough to disagree with your opinion. So let's go ahead with that!

**Comment by waneck** [comment]
Nicolas, I think that this is the worst behaviour we can have. On many languages - that don't have the >>> operator -, what determines if it's a signed or unsigned shift is their type (e.g. C, C++, C#...). Porting code from these languages into Haxe would be very cumbersome if we make the behaviour you're suggesting.

My own personal view - in light of porting code and the confusion it brings - is that whatever we decide, we should `@:deprecate` the `>>` operator on UInt. I know it's inconvenient, but it can save a lot of hours of debugging.

**Comment by ousado** [comment]
We have to be careful:
- On an unsigned integer, there simply is no sign bit we can carry. 
- On an unsigned integer, to perform an arithmetic right-shift, you *do* a logical one.

- What are "signed" / arithmetic right-shifts useful for? For quickly dividing by powers of 2, for instance:

signed arithmetic right-shift:
10000000000000000000000000000000 >> 1 = 11000000000000000000000000000000 
(-2147483648) / 2 = (-1073741824)   // USEFUL!!!

unsigned **both** logical and arithmetic right-shift:
10000000000000000000000000000000 >> 1 = 01000000000000000000000000000000 
2147483648 / 2 = 1073741824  // ALSO USEFUL!!!

proposed haxe so called "signed"/arithmetic right-shift on an unsigned integer:
10000000000000000000000000000000 >> 1 = 11000000000000000000000000000000
2147483648 / 2 = 3221225472   // ???????????? !!!  

Seriously, frankly, please, let's not try to be "clever but different"  here. 
C, C#, C++, D, Rust, SML, Go, Perl, Scala - not a single one of these languages which 
1. do have unsigned types and 
2. have both arithmetic and logical right-shift 
use "signed"/arithmetic shift on unsigned integers. Not one. And that's because it would be wrong, plain and simple.

See especially D which, syntax-wise, also uses >>> for a 0-filling right-shift on signed integers, does allow >> on unsigned types and it does exactly the same - a plain logical, 0-filling right-shift, not a 1-filling pseudo-arithmetic one.

Haxe is an awesome language for systems programming. An outstanding one, even. And it will become much better at it. Let's get integers, of all things, right. Please.

**Comment by waneck** [comment]
Well, I have to say, after what @ousado said, I'm convinced.

**Comment by Simn** [comment]
Indeed, can't disagree with that.

**Comment by ncannasse** [comment]
Another day, another opinion... Ok, let's go with `UInt >>`  being unsigned shift, and burn people that complains about it afterwards :)

**Comment by waneck** [comment]
Hahahah that comment made my day. :)
