### ISSUE TITLE
[Python] add native Json.stringify

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#2945]
we have to override a function which is a keyword in haxe (default) to implement this. Without a dirty hack we would need @:native for functions (blocking issue: #1492) to implement this properly.

**Comment by Antoine-Lassauzay** [comment]
In order to implement ``JSON.stringify`` correctly with the native json module, we need to subclass [JsonEncoder](https://docs.python.org/3.3/library/json.html#json.JSONEncoder) so the ``replacer`` function can be called to each key/value pair.

This subclass has to declare a ``default()`` method, which is what @frabbit was referring to, I believe.

Maybe ``json.dumps`` can be used by default with a fallback on ``haxe.format.JsonPrinter`` if ``replacer`` is specified?

**Comment by Simn** [comment]
I'll close this as nobody seems to care much.
