### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3072]
We want to add to the standard library, fully tested versions of the following classes:
- haxe.Ucs2
- haxe.Utf8
- haxe.Utf16

They will be implemented as abstracts and will follow the String API + conversions between them and fromBytes/toBytes.

**Comment by Simn** [comment]
Can someone comment on the approach(es) taken by https://github.com/mandel59/unifilll and if we could make use of it?

**Comment by deltaluca** [comment]
For reference: http://site.icu-project.org/

**Comment by ncannasse** [comment]
@Simn broken link

**Comment by Simn** [comment]
edited (no idea how that happened)

**Comment by ncannasse** [comment]
I don't think that the Unifill using is a good idea : since all calls go through the Utf interface, no inlining is possible so while it makes the code more generic (for instance you can implement split for all encodings) in the end it's very slow.

I would instead have an Utf interface that mimics entirely the String API so it can be a drop down replacement (no using), then an implementation for each encoding. For fixed codepoint encoding (UCS2, UTF32), this would benefit from having not to take codepoint width into acconut

**Comment by Simn** [comment]
You're complaining about the Utf interface, then suggest to use an Utf interface instead. ?_?

**Comment by cref** [comment]
Hearing all the lacking-unicode-support-talk going on at WWX2015, I thought maybe [this project](https://github.com/walling/unorm) might be of help. It implements unicode normalization and can be used as a polyfill for the ES6-proposed [String.prototype.normalize()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize).

**Comment by elliott5** [comment]
Just to reinforce what I said at my WWX2015 talk last Saturday, the existing body of Unicode-related Go packages could easily be auto-translated to Haxe using [TARDISgo](https://github.com/tardisgo/tardisgo), including:
- [Package unicode provides data and functions to test some properties of Unicode code points.](https://golang.org/pkg/unicode/)
- [Package utf8 implements functions and constants to support text encoded in UTF-8. It includes functions to translate between runes (32-bit unicode code-points) and UTF-8 byte sequences.](https://golang.org/pkg/unicode/utf8/)
- [Package utf16 implements encoding and decoding of UTF-16 sequences.](https://golang.org/pkg/unicode/utf16/)
- [Package norm contains types and functions for normalizing Unicode strings.](https://godoc.org/golang.org/x/text/unicode/norm)
- and many more related packages, see the [repository of text-related packages, such as character encodings, text transformations, and locale-specific text handling.](https://godoc.org/golang.org/x/text)

The main issue would be creating a more user-friendly and haxe-friendly API wrapper for the generated code, as the current autogenerated API is rather ugly, see the [normalization example from my talk.](https://speakerdeck.com/elliott5/prospects-for-using-go-libraries-in-haxe?slide=8) However this is nothing like as much work as writing the libraries from scratch.

By auto-generating the libraries in this way, the Haxe ecosystem could very quickly have a complete working solution, one which leverages the many man-years of work that the Google Go team have put into making these libraries correct. Of course the generated code is larger and slower than hand-written Haxe would be,  so there would be opportunities to re-write key elements of the libraries to improve speed/size in future.

**Comment by mandel59** [comment]
I've rewritten Unifill to avoid using Utf interface. Now UtfXs are abstract.

**Comment by mandel59** [comment]
Unifill doesn't support Ucs2, because what we call UCS-2 is actually potentially ill-formed UTF-16 in most cases. (cf. https://simonsapin.github.io/wtf-8/#ill-formed-utf-16)
We, however, should consider how to deal potentially ill-formed UTF-16 (or UTF-8) strings. Ideally, dirty strings should be separated into different types, but the domain of Haxe is not an ideal world but the real. While Unifill provides `validate` method to assert string encoding validity, it may not be enough.

**Comment by Simn** [comment]
unifill seems to have all the required tools already, so is this just a matter of changing how to interact with it?

**Comment by waneck** [comment]
When we add support for unicode, let us please also include an `encoding` option for `readString` or any other way we provide to read from Bytes to the String (we may need to include it into the CFFI as well, by the way). This way we can still be sure that the string is always in a valid encoding internally, and there is no awkward `encode` function with a type like `String->String`

**Comment by Simn** [comment]
@ncannasse: Please follow up.

**Comment by indolering** [comment]
> I haven't seen any discussion on handling unicode normalization before.

I think virtually all languages that support Unicode will have a `normalize` function that supports the basic normal forms, that doesn't take care of everything but (AFAIK) it wouldn't require too much work.

@elliott5 Sounds like the more advanced stuff should be left as an external library.

**Comment by mandel59** [comment]
[I18N/CanonicalNormalizationIssues](http://www.w3.org/wiki/I18N/CanonicalNormalizationIssues) shows that normalization is not magic that resolves all of enigmatic multilingual problems. We always have to consider whether normalization is suitable for our usage, or it yields unexpected results.

Supporting Unicode is just one of task of internationalization. Also normalization is. There are some referential works of internationalization API/libraries.

- [ECMAScript Internationalization API](http://www.ecma-international.org/ecma-402/1.0/). I think it would become popular owing to native support of web browsers.
- [International Components for Unicode](http://site.icu-project.org/). Most of internationalization API based on it. Supporting C/C++ and Java.

**Comment by frabbit** [comment]
@nicolas what should i use as the underlying type for bytes based ucs2, utf8, utf16? at the moment i use BytesAccess (an abstract around BytesData) hl makes it somehow more difficult, because BytesData relies on Bytes instead of the other way around.

**Comment by frabbit** [comment]
hm, i think i confused hl.Bytes with io.Bytes, sorry for the noise.

**Comment by longde123** [comment]
hxcpp   Stirng ...please    support haxe.Ucs2  haxe.Utf16

**Comment by frabbit** [comment]
i just want to update everyone, the current status of unicode can be found here:
https://github.com/frabbit/haxe-1/tree/unicode_vector

i'm planning to get it done in the next weeks, feedback appreciated.

**Comment by m22spencer** [comment]
Great job so far!

Couple of notes: 
* ucs2/utf16.fromCharCode(0xD800)
  Why is 0xD800 not accepted?  The break tests file require it.
  http://www.unicode.org/Public/9.0.0/ucd/auxiliary/GraphemeBreakTest.txt

* Mandatory conversion
  Consider C#/Utf16 impl.
  C# String type is Utf16. (Confirm?)

  i18n.Utf16 converts C# String -> Bytes on construction
                  and Bytes -> C# String on toNativeString.
  Doesn't this make interop with existing functions very expensive?
  Can each native platform use `String` directly for that particular i18n repr?
  eg:
    - C#: String == i18n.Utf16
    - js: String == i18n.Ucs2
    - hl: String == i18n.Utf16
    - ...
  
* Grapheme clusters
  Even with the unicode aware representation, another layer of abstraction is needed in order to get expected results.

  See below:
     (These results are the same for Ucs2/Utf8/Utf16/Utf32.):
```haxe
var s = new haxe.i18n.Utf8("☔︎한🌍");    // 3 characters.

trace(s.charAt(0).toNativeString());   //☔ Hmm.. this umbrella looks different
trace(s.charAt(1).toNativeString());   //  Nothing?
trace(s.charAt(2).toNativeString());   //ᄒ ???

trace(s.substr(2,1).toNativeString()); //ᄒ
trace(s.substr(2,2).toNativeString()); //하
trace(s.substr(2,3).toNativeString()); //한

var a = new haxe.i18n.Utf8("한");      // 1 character.
var b = new haxe.i18n.Utf8("한");      // 1 character.
trace(a.charAt(0).toNativeString());  //ᄒ
trace(b.charAt(0).toNativeString());  //한
```

**Comment by darmie** [comment]
When are we likely to have this shipped into the official Haxe source?

**Comment by frabbit** [comment]
I plan to work on this and it should be included in 4.0.

**Comment by andyli** [comment]
@ncannasse I think you want to review frabbit's work. Assigning to you.

**Comment by frabbit** [comment]
@andyli would be nice if i get more reviews, so that i have a clear roadmap on how to improve the current state. Hopefully i find some time next week, but i'm quite busy atm, and on vacation afterwards. Will come back to this in the first november week.

**Comment by frabbit** [comment]
Things on my roadmap: 

- Fast Iterators for all encodings
- Faster UTF16 Impl for native Ucs2 Platforms (java, js, c#, etc)

**Comment by frabbit** [comment]
I have pushed the implementation for these 2 features:
[x] Fast Iterators for all encodings
[x] Faster UTF16 Impl for native Ucs2 Platforms (java, js, c#, etc)

Would be nice to know what's still missing, any bugs left? @m22spencer 

What about unicode normalization, it's not part of the implementation atm.
@ncannasse @andyli

**Comment by frabbit** [comment]
I wonder what i should do with toLowercase and toUpperCase, at the moment it's only applied for the ascii range 41...5A and 61...7A

**Comment by frabbit** [comment]
Some things that i would like to add to std, please let me know if that's fine @ncannasse @Simn 

- **Vector + operator** or append/concat method to concat two vectors into a new one.
- Move some BytesData related stuff out of Bytes and into a helper class **BytesDataTools** or Something, so that Bytes and a new **ByteAccess** type can share common functions. ByteAccess is an abstract on top of BytesData with length access, it's used for ucs2, utf16 and utf8.
- **BytesBuffer.reset** to reset and reuse a buffer
- **BytesBuffer.addBytesData** or **BytesBuffer.addData** to push a full BytesData object into the buffer, without creating a bytes object first.
- StringBuffer.addString or something (https://github.com/HaxeFoundation/haxe/issues/5440)

**Comment by Simn** [comment]
I don't see any reason not to add/change these, but can we please do that after we're done with the first step?

**Comment by frabbit** [comment]
Of course, the question is what exactly is the first step (i guess a merge) and what's missing to do that.

**Comment by R32** [comment]
I feel like we don't need utf16, actually the ucs2 is quite enough.  If a guy uses a 4-byte utf16 character such as "𤭢", then just convince him not to use the character, because no one knows this weird character . In fact, there are only 2,000 Chinese characters commonly used in China.

**Comment by back2dos** [comment]
Emojis are outside the BMP. Maybe we can live with that. Just pointing out that not everything that doesn't fit ucs2 is largely unused.

**Comment by frabbit** [comment]
#6748

**Comment by back2dos** [comment]
I mostly agree, however if you represent it as `Array<Int>` (or probably rather `Vector<Int>`) you're going to use 8 bytes per code point on many platforms. This is especially wasteful if you're operating in the ASCII range (which textual formats like JSON and XML tend to do). You might get away with it on the client, but on a server this will severely throttle your maximum throughput.

**Comment by farteryhr** [comment]
Yes, it depends on how carefully you want to process the data. Regarding existing utilities, they're OK and I don't mean to deprecate/delete any of them.

For parsing, just use code point iterator, returning where we are, what the code is and how big this char is, and cut out what we need according to them, all with the native `String`.

For daily usages like finding, splitting and replacing, since the key string and the big string are both encoded the same way on the same runtime, there will be no problem with the native APIs (assuming they're coded with valid utf-8, utf-16 underlying, of course).

Issues like #6897 is essentially what I intend to deal with, when the underlying format makes unavoidable difference. String.split("") is something special (how much memory does the `Array<String>` take?).

What about a specialized `Array<Int24>`? ![funny](https://raw.githubusercontent.com/YunTM/huaji/master/huaji_64.png)

**Comment by Simn** [comment]
With #7009 merged, we can close here. #6748 is still open to track further Unicode support in the standard library.
