### ISSUE TITLE
Array prototype doesn't get modified in loaded SWF

### ISSUE THREAD

**Issue by timdp** [HaxeFoundation/haxe#3087]
When using `Loader::load` to dynamically load an SWF loaded with Haxe, sometimes(?), the Array prototype extensions (copy, insert, remove, and iterator), don't seem to stick. Consequently, all code along these lines fails in the loaded SWF:

```haxe
var a:Array<Dynamic> = [];  // or new Array<Dynamic>()
var b:Array<Dynamic> = a.copy();
```

The extensions are defined in [`flash::Boot::__init__`](https://github.com/HaxeFoundation/haxe/blob/development/std/flash/Boot.hx#L213), but this function only seems to be included in AS3 output, not in an SWF. (I checked using the JPEXS decompiler, which did turn up some odd code now and then.)

I tried to reproduce the behavior by cooking up two SWFs in pure AS3, with cross-domain requests, combining HTTP and HTTPS, several content loader domains, and several SWF versions, none of which prevented me from modifying the array prototype. This leads me to believe that the Haxe compiler does something peculiar, but since I don't know OCaml, I can't decipher the compilation logic.

[This email](https://groups.google.com/forum/#!topic/haxelang/CfpPIwvPFTs) suggests a workaround using `Type::createInstance`, but I'd rather figure out what's going wrong and possibly come up with a fix.

**Comment by ncannasse** [comment]
We have discussed recently about not breaking the current behavior of Array extensions in flash, in order to keep backward compatibility when using Dynamic for instance.

I will then close this one, we can maybe look at it again if there is some way to actually reproduce the issue.

**Comment by bmfs** [comment]
This issue seems related to #2603 

I also faced this problem. On my case we have a swc library created with haxe being loaded on a as3 project.
When the project swf was run separately everything works fine. When the swf is loaded by a game portal wrapper it complains about the 'iterator is not a function'.

The portal wrapper loads the game into a separate application domain by default.
I managed to get the wrapper to load the game into the same application domain and it started working
