### ISSUE TITLE
Quoted fields should be preserved quoted in JS

### ISSUE THREAD

**Issue by exFalso** [HaxeFoundation/haxe#3101]
```
class Tmp
{
    static function fun(d:Dynamic)
	{
	}

	public static function main()
	{
		var object = {
			"hello" : "there",
		};
		fun(object);
	}
}
```

compiles into

```
(function () { "use strict";
var Tmp = function() { };
Tmp.fun = function(d) {
};
Tmp.main = function() {
	var object = { hello : "there"};
	Tmp.fun(object);
};
Tmp.main();
})();

```

Notice how "hello" lost the quotes. This means that minification will not preserve the symbol.

**Comment by Simn** [comment]
I came across an implementation problem where the semantics are not clear to me. Consider this:

```haxe
typedef MyStructure = {
    field: String
}

class Main {
    static function main() {
        var obj:MyStructure = {
            "field": "value"
        };
        obj; // don't inline
        obj.field;

        var obj2:MyStructure = {
            field: "value"
        }
        obj2;
        obj2.field;
    }
}
```

There's no way to distinguish `obj.field` and `obj2.field` because the access is made on the same type as far as the compiler is concerned. The quoted status of the field is a property of the structure declaration type, which in this case is different from the type the field access is made on.

If we infer quoted status on `MyStructure` all field access on that type will be generated as `obj["field"]`, which would not be correct either.

I don't have a solution for this right now, short of adding `-D quote-fields` and just quoting everything.

**Comment by ncannasse** [comment]
The problem is that is quite specific to JS, while Haxe behavior is crossplatform.

One solution for instance would be to declare this:

```haxe
@:build(some-macro) abstract MyStructure {
    @quoted var field : String;
     var unquotedOne : Bool;
}
```

So you could field-by-field define which field is quoted, and then things will be automatically handled when you would read or write the field.

Would that work for you (we can provide the macro code for it)

**Comment by ncannasse** [comment]
Reminds me I should never have accepted quoted fields in the first place...

**Comment by Simn** [comment]
Well they are quite useful for working with externs. Only thing is that I don't share your enthusiasm for encoding state in strings. ;)
