### ISSUE TITLE
Important type hole

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3128]
The following code is incorrectly constraint:
```
class Test {
	static function main() {
		var objs = new Map<Int,{h:Int}>();
		function get(o) {
			var k = objs.get(o.id);
			return o.v;
		};
		$type(get);
	}
}
```

The type of get.o is missing the `v` field. Might be related to the abstract access ?

**Comment by Simn** [comment]
The problem has to do with the `TAnon` case of `apply_params` and open structures. In the case of inline with type parameters we expression- and type-map the entire expression, which maps types using `apply_params` and among other things sets the `v.v_type` to that.

This means that upon calling an inline function with a local argument that is typed as an open structure, that structure effectively gets locked into the variable because all further operations only modify a copy of it.

I think when mapping open structures we should mutate `a.a_fields` instead of creating a new `TAnon` here: https://github.com/HaxeFoundation/haxe/blob/development/type.ml#L545

@ncannasse: Any thoughts?
