### ISSUE TITLE
Option to apply a build macro to all types

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3129]
A request from TiVo: They want to apply a build macro to their entire code base and look for an option to do that. I suggested using Compiler.addMetadata, but the problem with that is that it does not handle module sub-types.

The next idea was to introduce Compiler.addGlobalMetadata, but that would be quite brutal. Still looking for a better way of approaching this.

**Comment by bjitivo** [comment]
Am I misunderstanding something?  Compiler.addGlobalMetadata adds metadata to all types based on a string path filter; but @:genericBuild doesn't work for anything other than classes or enums.

This means that any wildcard used in the addGlobalMetadata path filter which includes interfaces, cannot be used to apply a @:genericBuild macro.

This is really inconvenient.  I want to just use an "apply to everything" wildcard for Compiler.addGlobalMetadata (turns out the empty string does this, "*" does not, this is beyond my comprehension but whatever), and then have the @:genericBuild macro return null for types that it doesn't want to deal with.

I think the underlying problem is that @:genericBuild gives an error when applied to interfaces.

I guess I'll submit an issue about this last problem?

**Comment by back2dos** [comment]
You're mixing up a whole number of things. First of all, @:genericBuild is
a misleading name. It doesn't have to involve type building or generics.

A build macro is a macro invoked by @:build on a type (or @:autoBuild on
subtypes) that is expected to return an Array<Field>.

You can use Compiler.addGlobalMetadata to add @:build metadata everywhere.
I am not entirely sure it works on typedefs, but other than that, it will
run on all named types (i.e. interfaces, classes, enums and abstracts).
