### ISSUE TITLE
Inconsistent structual typing of inferred anon-types.

### ISSUE THREAD

**Issue by deltaluca** [HaxeFoundation/haxe#3192]
``` haxe
class Test {
    static function main() {
        var x1 = {x:1, y:2};
        var x2 = ({x:1, y:2}:{x:Int,y:Int});
        var x3:{x:Int,y:Int} = {x:1, y:2};
        var y1:{} = x1;
        var y2:{} = x2;
        var y3:{} = x3;
        var z1:{x:Int} = x1; // <-- error only on this line
        var z2:{x:Int} = x2;
        var z3:{x:Int} = x3;
    }
}
```

{y:Int,x:Int} should be {x:Int}
{y:Int,x:Int} has extra field y

**Comment by ncannasse** [comment]
The idea is that constant structures are not allowed to be reduced. This allows for instance to check for the following:

```haxe
function foo(o:{?x:Int,?y:Int}) {
}
var pt = { x: 0, yy : 1 }; // typo
foo(pt); // goes unnoticed
```

Also, it will gives error if you modify the signature of foo, for instance by removing a field.

**Comment by ncannasse** [comment]
@Simn if you can get the same warnings as we currently get errors (no less, no more) then it's good for me

**Comment by Simn** [comment]
#3856 has made me change my perspective here. If we allow structural sub-typing between structures it's really silly to not allow this for structure declarations in the general case.

So I propose this: Let's give an error only if the expected type has optional fields. This is the only case where the typo problem can occur.

**Comment by ncannasse** [comment]
There's another issue with it.
Let's say you design your API with
``
function foo( o : { x : Int, y : Int, z : Int } ) {
}
`` 

And then you change it at a later stage to:
``
function foo( o : { x : Int, y : Int } ) {
}
`` 

Currently, this will give you errors at all the places you pass a constant struct with a "z" value, allowing you to cleanup the code as well. It's very useful for refactoring.

**Comment by Simn** [comment]
-D disallow-const-struct-reduction-or-something?

**Comment by ncannasse** [comment]
We don't want to have this be a compiler flag, because then some libraries might either compile or don't depending if they support that flag : compilation result should not be affected by flags (unless they're #if ... user code of course)

**Comment by Simn** [comment]
Sure but if the refactoring-and-removing-a-field case is your concern (and I'm sure that happens thousands of times a day (unlike the intended const-assignment-to-smaller-structure (not like there's an issue about these every other week (or a question)))) this would be a nice temporary flag to set in order to detect these cases.

**Comment by ncannasse** [comment]
That's why a warning (with no flag) would be nice :)

**Comment by Simn** [comment]
Cool so we can make it work by default and have a flag which gives warnings in this case?

**Comment by ncannasse** [comment]
Let's go step by step here : first a warning , then if people complains with valid cases that it is annoying we can hide it unless some flag is turned on. I'm still convinced atm that the report is useful. The only issue with current error is that it might make people misunderstand that structures are not structurally subtyped when they're testing with literal values.

**Comment by Simn** [comment]
It's not entirely trivial to turn this into a warning because it can also happen while unifying, which means there is no context to warn in.

As far as "the only issue" goes: Even I was lead to believe that there is no structural subtyping between structures due to this behavior. 

I can rally some people to complain about this if that's what's required here. :P

**Comment by Simn** [comment]
I just re-read everything and still don't think that turning this into a warning is the right thing to do. Warnings only make sense when there's an obvious fix for them and I have trouble spotting obvious fixes here. Let's look at a really basic example:

```haxe
class Main {
	static function main() {
		var x1 = {x:1, y:2};
		var z1:{x:Int} = x1;
		trace(x1.y);
	}
}
```

Let's assume I get a warning from that because of the extra `y` field. Then what? I don't want to remove the field because it's actually used. I also cannot adjust the type of `z1` in the general case because it could be some API function somewhere.

The only thing I can do is type-hint `x1` to `{x:Int, y:Int}`. But that raises some other questions, like why that makes a difference in the first place. Usually type-inference takes care of that, so why is that not the case here?

I keep coming back to the idea that extra fields should only be reported when we're directly declaring a structure against a type that has less fields.

**Comment by ncannasse** [comment]
I'm fine with your last sentence, it should clear up misunderstandings about structural subtyping while still eliminating most of typo errors (when optional fields are involved in particular). I'm just a bit concerned that this will go unnoticed:

```haxe
function foo( o : { x : Int, ?foo : Int } ) {
}
var o = { x : 0, fooo : 10 }; // typo
foo(o); // pass! 
```

**Comment by Simn** [comment]
Yes I know, which is why I think detecting unused fields is ultimately the way to go.

**Comment by Simn** [comment]
Doesn't this mean we can get rid of the `Const` flag entirely? I know it does something special in `unify_min` which I don't understand. There's also a hack for `using_field` which I believe becomes irrelevant once unification is allowed properly.

**Comment by Simn** [comment]
@ncannasse: I'm working on this part of the compiler right now, can you confirm that we can get rid of the Const flag?

**Comment by ncannasse** [comment]
We can get rid of it as long as we have a check at a later compilation phase which warn for extra fields when unifying a TObjectDecl with a TAnon

**Comment by ncannasse** [comment]
... or if we use with_type to warn about it when typing EObjectDecl, that should be enough

**Comment by Simn** [comment]
> ... or if we use with_type to warn about it when typing EObjectDecl, that should be enough

That's the plan!

**Comment by nadako** [comment]
Looks like this should be reopened

**Comment by jasononeil** [comment]
Here's a try-haxe with the same code producing the same error: https://try.haxe.org/#62857

The same problem occurs on 3.4.4, 4.0.0-preview.2 and the current nightly (`git build development @ 8951632`)

**Comment by haxiomic** [comment]
I would be nice to be able to suppress the warning in the context of externs (or by using metadata) 

In js externs sometimes you have a structure that has some explicit fields but allows extra fields (that will be used at runtime)

**Comment by Gama11** [comment]
Should that then be `Dynamic<{explitiFields}>` or something like that?

**Comment by haxiomic** [comment]
That would compile but you’d lose type check and autocomplete on your other fields I think
