### ISSUE TITLE
Consider adding "finally"

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3335]
Up to know I was not a big fan of "finally". I find it complexify a bit too much try/catch while not bringing something that can't be done in a more standard way.

However I found that finally allows to have some cleanup code while preserving the full stack trace for the exception (tested in Chrome/JS), which is something right know we only support in Neko with neko.Lib.rethrow.

I wonder if we should either add finally as-it or use it to implement some kind of "rethrow" function on all platforms.

**Comment by Simn** [comment]
I don't know what should happen here.

**Comment by jacekszymanski** [comment]
```finally``` and scope exits serve a very important purpose: to ensure that a thunk of code is executed (entered, in fact) *exactly once* regardless of how the protected (i.e. ```try```) scope exits. Without this feature I believe it is impossible correctly to write or use anything that relies on reference counters and/or leases (e.g. object pools).

It need not be mixed with ```try```/```catch```, e.g. Common Lisp has a special operator ```unwind-protect``` which only ensures that cleanup code is executed when protected code exits by whatever means, but is not used for error handling.

I don’t think it’s ambiguous, it’s just like @Simn has written above: "if control flow leaves the try block (by whatever means), execute the finally block. If control flow reaches the end of the finally block, continue with what would have originally happened”; and otherwise what would have happened is lost and the non-local exit from finally block is continued.

I agree that ```finally``` as it is in Java is a very ugly pattern, but I nevertheless believe that the ability to have a thunk executed exactly once as a cleanup is indispensable. In languages that do not have this ability, but have exceptions, it can be simulated as a code pattern, but this disallows ```return```, ```continue``` or ```break``` in the protected code with no possibility to enforce this restriction and is thus very error prone.

In its basic form ```finally``` does not require code duplication at all, it’s done with a pretty simple rewrite, so what would be
```
try {
  protected;
}
finally {
  cleanup;
}
```
becomes
```
try {
  protected;
  throw PassedOK;
}
catch (e: Dynamic) {
  cleanup;
  if (e != PassedOK) rethrow(e);
}
```
but, as easily seen, this simple rewrite requires that ```protected``` contain no ```return``` et al. or the catch block, and thus ```cleanup``` is bypassed.

In Haxe, macros can be used to remove this restriction by means of rewriting ```return```, ```break``` and ```continue``` to throwing other control exceptions, though to achieve this the ability to expand inside macros is required. I have implemented this in my library [scopes](http://lib.haxe.org/p/scopes), and the only restriction I am now aware of is that the users never throw or catch control exceptions. Once ```finally``` (syntax aside) is implemented, scope exit expressions are even easier to add with macros, though still the ability to expand is required.

Adding ```finally``` or an equivalent feature would have the advantage that in targets that have ```finally``` natively it can be used as is, without throwing unnecessary exceptions, thus making generated code simpler, and in targets that do not have this ability, it can be simulated with exceptions as I described above. It would also make debugging code relying on cleanup expressions way easier, as the macro-generated code is necessarily far from readable.

**Comment by ncannasse** [comment]
@jacekszymanski one problem with "emulating" finally on platforms that don't support it is that unless they have some way to "rethrow" exceptions this will eat up the callstack, making it very hard to debug such exceptions...

That's one of the main reasons holding me from adding finally as-it in Haxe syntax.

**Comment by Danielku15** [comment]
For a start you could add support for finally to the languages that support it natively and also translate it as such: 

* Flash/AS3 (http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00000724.html)
* JavaScript (https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/try...catch#The_finally_clause)
* PHP (http://php.net/manual/en/language.exceptions.php) 
* C# (https://msdn.microsoft.com/en-us/library/zwc8s4fz.aspx) 
* Java (https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html) 
* Python (https://docs.python.org/2.7/tutorial/errors.html#defining-clean-up-actions) 

I understand that Haxe wants to have 100% the same behavior on all platforms and that finally might be implemented differently on some languages. But considering the usage of finally, which is mostly resource-cleanup, it should not be a big deal. If issues are supported from the public, they can be investigated on demand. 

The other targets are a bit more tricky: 

* Lua seems to have some solutions that can be adapted (https://github.com/siffiejoe/lua-finally https://github.com/dmccuskey/lua-error).
* Neko and HashLink might need some bytecode/VM extensions to work as expected
* C++ does not directly support finally as a keyword, but it supports stack allocated variables which are 
destroyed on scope exit. 
```
try {
    <try-body>
}
finally {
    <finally-body>
}

```
Can become...

```
{
    ScopeHelper scope([&] () {
        <finally-body>
    });

    <try-body>
}
```
...where the ScopeHelper destructor calls simply the lambda. This only works for simple cases where finally does not have return statements:

```
public function test() : Int {
    try {
        return 1;
    }
    finally {
        return 2;
    }
}
var x = test();  // x = 2
```
In a first version it could be unsupported to have return statements in the finally block to overcome this problem. 

Another solution to this topic might be to not support support finally, but only support something like the C# using-block or the Java try-block: 
```
using(<variable-declaration|expression>) <block>
try(variable-declaration|expression>) <block>
```
Focusing only on some dedicated resource-cleanup control-flows there might be simpler solutions than support any kind of finally-block.

**Comment by Sunjammer** [comment]
I know this potentially makes me a filthy hobo, but I really do like returning from a function in the `try/catch` block set while still having a `finally` to let me clean up post return but before the stack frame is closed (a trick that felt like discovering time-travel the first time I encountered it). It may be filthy, but it's a very strong productivity feature that makes writing cleaner stateful code much simpler in the scenarios where state can't be avoided.

**Comment by ncannasse** [comment]
Another thing that should be discussed as part of Haxe Evolution process.

**Comment by barisyild** [comment]
I believe the "try-finally" structure is particularly useful when working with mutexes. For this reason, I think it's worth bringing this topic back into discussion. Adding support for "finally" would greatly improve resource management and help ensure that mutexes are properly released, even in the presence of exceptions.

## Sample 1

```haxe
import sys.thread.Mutex;

class Test {
  private static var mutex:Mutex = new Mutex();
  
  static function main() {
    mutex.acquire();
    
    try {
         throw "Exception";
    } finally {
	          mutex.release();
    }
  }
}
```

### ~~Generated Code~~

```haxe
import sys.thread.Mutex;

class Test {
  private static var mutex:Mutex = new Mutex();
  
  static function main() {
    mutex.acquire();
    
    try {
      throw "Exception";
      try { mutex.release(); } catch(e) {}
    } catch(e) {
      try { mutex.release(); } catch(e) {}
      throw e;
    }
  }
}
```

## Sample 2

```haxe
static function queryAndClose(query:String) {
  try {
	return query(query);
  } finally {
	closeConnection();
  }
}

static function query(raw:String) {
	// ...
}
```

### ~~Generated Code~~

```haxe
static function queryAndClose(query:String) {
	try {
		var tempVal = query(query);
                try { closeConnection(); } catch(e) {}
	       return tempVal;
	} catch(e) {
		closeConnection();
		try { closeConnection(); } catch(e) {}
		throw e;
	}
}

static function query(raw:String) {
	// ...
}
```

**Comment by binki** [comment]
@barisyild I disagree with trapping exceptions in a `finally` block. In all other languages I’ve used, an exception thrown in a `finally` will be thrown instead of the originally caught exception. So instead I would do:

```ts
import sys.thread.Mutex;

class Test {
  private static var mutex:Mutex = new Mutex();
  
  static function main() {
    mutex.acquire();
    
    try {
      throw "Exception";
      mutex.release();
    } catch(e) {
      mutex.release();
      throw e;
    }
  }
}
```

and (removing the already-duplicated line)

```ts
static function queryAndClose(query:String) {
  try {
    var tempVal = query(query);
    closeConnection();
    return tempVal;
  } catch(e) {
    closeConnection();
    throw e;
  }
}

static function query(raw:String) {
  // ...
}
```

**Comment by barisyild** [comment]
> [@barisyild](https://github.com/barisyild) I disagree with trapping exceptions in a `finally` block. In all other languages I’ve used, an exception thrown in a `finally` will be thrown instead of the originally caught exception. So instead I would do:
> 
> import sys.thread.Mutex;
> 
> class Test {
>   private static var mutex:Mutex = new Mutex();
>   
>   static function main() {
>     mutex.acquire();
>     
>     try {
>       throw "Exception";
>       mutex.release();
>     } catch(e) {
>       mutex.release();
>       throw e;
>     }
>   }
> }
> and (removing the already-duplicated line)
> 
> static function queryAndClose(query:String) {
>   try {
>     var tempVal = query(query);
>     closeConnection();
>     return tempVal;
>   } catch(e) {
>     closeConnection();
>     throw e;
>   }
> }
> 
> static function query(raw:String) {
>   // ...
> }

Yeah you are right, sorry.

Updated version is looks like;

## Sample 1

```haxe
import sys.thread.Mutex;

class Test {
  private static var mutex:Mutex = new Mutex();
  
  static function main() {
    mutex.acquire();
    
    try {
         throw "Exception";
    } finally {
	          mutex.release();
    }
  }
}
```

### Generated Code

```haxe
import sys.thread.Mutex;

class Test {
  private static var mutex:Mutex = new Mutex();
  
  static function main() {
    mutex.acquire();
    
    try {
      throw "Exception";
      mutex.release();
    } catch(e) {
      mutex.release();
      throw e;
    }
  }
}
```

## Sample 2

```haxe
static function queryAndClose(query:String) {
  try {
	return query(query);
  } finally {
	closeConnection();
  }
}

static function query(raw:String) {
	// ...
}
```

### Generated Code

```haxe
static function queryAndClose(query:String) {
	try {
		var tempVal = query(query);
                closeConnection();
	       return tempVal;
	} catch(e) {
		closeConnection();
		throw e;
	}
}

static function query(raw:String) {
	// ...
}
```

Thanks

**Comment by barisyild** [comment]
It seems that many targets already have `finally` support.

In languages ​​that natively support it, it might be possible to use these structures directly; those that don't can use the code generation I described above.

| Language | `finally` Support |
| :--- | :---: |
| **Java (JVM)** | ✅
| **JavaScript** | ✅
| **C# (.NET)** | ✅
| **Python** | ✅ 
| **ActionScript 3** | ✅ 
| **PHP** | ✅
| **C#** | ✅
| **C++** | ❌
| **Lua** | ❌
| ***Neko** | ❌ 
| ***HashLink** | ❌ 

*I see no reason why HashLink and Neko shouldn't have native `finally` support.
