### ISSUE TITLE
[cs] @:property doesn't really respect get/set/never

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3375]
Consider the following example:
```haxe
@:nativeGen
class A {
    @:property
    var a(get,set):Int;
    function get_a() return 1;
    function set_a(v) return v;
}
```
It generates the following C# code as it should:
```cs
	public virtual   int a{
		get { return _get_a(); }
		set { _set_a(value); }
	}
	private   int _get_a(){
		unchecked {
			return 1;
		}
	}
	private   int _set_a(int v){
		unchecked {
			return v;
		}
	}
```
However, if we change `get` or `set` to `never` without removing corresponding method, C# getter/setter will still be generated and method will still be prefixed (not sure if the latter is a bug or implementation detail though).

**Comment by waneck** [comment]
Unfortunately, this doesn't seem to be easy to deal with - since even if you don't include a getter/setter, C# will reserve the `get_` / `set_` name. I've proposed a fix at https://github.com/waneck/haxe/commit/7e849d578262c12fe9ab0755da74abb095cc4890 , but I don't think this will be merged (see error if compiling the unit tests)
