### ISSUE TITLE
[php] issue with Date.fromTime(0);

### ISSUE THREAD

**Issue by jdonaldson** [HaxeFoundation/haxe#3415]
It doesn't look like php considers the time zone when calculating a base timestamp:

``` haxe3
trace(Date.fromTime(0));
```

```
|| PHP:
Main.hx|4 info| 1970-01-01 00:00:00
|| 
|| 
|| NEKO:
Main.hx|4 info| 1969-12-31 16:00:00
|| 
|| 
|| NODE:
|| Wed Dec 31 1969 16:00:00 GMT-0800 (PST)
|| 
|| 
|| CPP:
Main.hx|4 info| 1969-12-31 16:00:00
```

**Comment by RealyUniqueName** [comment]
This happens because of [this line](https://github.com/HaxeFoundation/haxe/blob/2fc83d6b0aa234d10fc04266c0d8376f727ab581/std/php/Boot.hx#L976)
So if your php.ini does not have timezone setting, haxe-generated php fallbacks to UTC timezone instead of following system settings.
You shoud either define `date.timezone` in your php.ini or use [date_default_timezone_set()](http://php.net/manual/en/function.date-default-timezone-set.php) somewhere in the entry point of your app.

Or you can move to new php generator with `-D php7`, which does not force timezone to UTC :)
