### ISSUE TITLE
[python target] :     AttributeError: '_io.FileIO' object has no attribute 'readAll'

### ISSUE THREAD

**Issue by zaxebo1** [HaxeFoundation/haxe#3445]
haxe program with following line:
        var sOutputStdout: String = process1.stdout.readAll().toString();

------------

**Now, when compiled for haxe/python Gives following ERROR at runtime:** ==>

        sOutputStdout = process1.stdout.readAll().toString()
        File "a1.py", line 1518, in readAll
        return self.impl.readAll(bufsize)
    AttributeError: '_io.FileIO' object has no attribute 'readAll'

NOTE: the same code successfully compiles and runs good for NEKO target, but fails at runtime for PYTHON target

=========================

(for compiling for haxe/python , i used the haxe build dated 2014-09-16 from http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux32/haxe_2014-09-16_development_5391c45.tar.gz AND on ubuntu 12.04 LTS)

**Comment by zaxebo1** [comment]
please label this bug as "platform-python". I am not able to create label on this bug.

**Comment by Simn** [comment]
@frabbit: We should check this one for 3.2.

**Comment by zaxebo1** [comment]
this may be made a "unit test", so that all current and future targets do this check

**Comment by frabbit** [comment]
i pushed a partial/temporary fix to adress this issue here: https://github.com/HaxeFoundation/haxe/commit/0cff3436e16cc97d977aa8f615bff849c464531f

The problem is that the returned io streams for stdout and stderr are not seekable. With this fix readAll reads from the current position in the stream until the end. If you just use readAll, this should work fine, but using readBytes from a specific position would read from the beginning, maybe we should throw an error if the stream is not seekable and a position different than 0 is used.

**Comment by Justinfront** [comment]
https://docs.python.org/3/library/io.html

seekable()
    Return True if the stream supports random access. If False, seek(), tell() and truncate() will raise OSError.

Should haxe have seekable property rather than relying just on an error.  I may not understand the problem just was curious and googled, appoligize if it's just noise but just incase.

**Comment by frabbit** [comment]
@Justinfront thx, yes i already check this flag, the problem was that my previous implementation used `seek` even when it wasn't necessary. Thus `readAll` on `process.stdout` didn't worked because  it's not seekable in python.
