### ISSUE TITLE
overload, callbacks, pattern matching, double-typing

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3452]
E.hx
```haxe
enum E {
    A;
    B;
}
```

Main.hx
```haxe
class Main {
    static function main() {
        f(function(e) {
            $type(e);
            switch (e) {
                case A:
                case B:
            }
        });
    }

    @:overload(function(c:E->Void):Void {})
    static function f(a:String, c:E->Void):Void {}
}
```

This will fail to compile, outputting:
```
Main.hx:4: characters 18-19 : Warning : Unknown<0>
Main.hx:6: characters 21-22 : Capture variables must be lower-case
Main.hx:4: characters 18-19 : Warning : E
```

**Comment by Simn** [comment]
Seeing how this is not a regression I'll prefer to not address it for 3.2. It's not an easy fix and might have unintended side-effects.

**Comment by Simn** [comment]
We can easily reproduce this without any function types too:

```haxe
class Main {
	static function main() {
		var e = null;
		f(e, e); // String should be Int
	}

	@:overload(function(a:Int, b:Int):Void {})
	static function f(a:String, b:Int):Void {}
}
```

My preferred solution would be "Cannot call overloaded function with unknown types". The way I see it our type-inference architecture cannot support this without pulling some really weird tricks.

**Comment by Simn** [comment]
@ncannasse: This is in a similar category as #3033 so I'm interested in your opinion here too. To summarize: Calling an overloaded field with a monomorph can bind that monomorph during the "first try" which then causes an otherwise valid call unification to fail afterwards.

**Comment by ncannasse** [comment]
@Simn I think we can have similar issue with constraints that will be registered for later check. One possibility would be when we have overloads, to clone the type and unify (for each overload), until we find a match, in which case we unify again with the "real type". That's the only way IMHO to have proper resuming of unification. And yes, monomorphs are good, they are at the very center of type inference :)

**Comment by Simn** [comment]
I still don't see how that would work. Here's what we call for each call argument:

```
let type_against t e =
		let e = type_expr ctx e (WithTypeResume t) in
		(try Codegen.AbstractCast.cast_or_unify_raise ctx t e e.epos with Error (Unify l,p) -> raise (WithTypeError (l,p)));
	in
```

Notice how we type `e` against `WithTypeResume t`. This means that _every single unification_ made against the expected type during normal typing might bind a monomorph.

There is no single place where we could replace all monomorphs in the expression and even if we tried to do that, we would still have to retain their identity relationship (that is, every monomorph m1 should be replaced by monomorph m2 throughout the entire typing).

**Comment by Simn** [comment]
By the way, the problem doesn't come from monomorphs on the expression itself (because we type each expression per argument per call anyway), but from those in mutable parts of the AST like `tvar.v_type`.

**Comment by Simn** [comment]
I think our resume-approach is fundamentally flawed. The original intent was to only resume when there are unification failures directly related to an expected type. However, that information is not always available as seen in my [initial example](https://github.com/HaxeFoundation/haxe/issues/3452#issuecomment-58269750).

The problem there is that the variable unification does not raise a resume error because the unification against `String` is not a `WithTypeResume`.

I think it would be much better to put the entire context in "overload-mode" while typing a function argument to an overloaded method. While in overload-mode, any unification failure is changed into a `Resumable_Error` exception which is caught by `unify_field_call` to continue trying with the next overload. If all overloads failed, `unify_field_call` raises the first error normally.

This still doesn't deal with the [mutability problem](https://github.com/HaxeFoundation/haxe/issues/3452#issuecomment-110123331), but should be a good first step.

**Comment by Simn** [comment]
The original example works now. The mutability problems are currently considered an unfortunate but necessary limitation.
