### ISSUE TITLE
No way to @:allow access from all classes in a module

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxe#3590]
``` haxe
// MyModule.hx

class MyClass
{

  // Expect allowing access from all classes in MyModule, but it does not
  @:allow(MyModule)
  var internalInt1:Int;

  // Works
  @:allow(MyHelper1)
  var internalInt2:Int;
}

class MyHelper1
{
  function plus(myClass:MyClass):Int
  {
    return myClass.internalInt1 + myClass.internalInt2;
  }
}
```

```
$ haxe MyModule
MyModule.hx:19: characters 11-32 : Cannot access private field internalInt1
```

**Comment by Atry** [comment]
The `@:allow` behavior is inconsistent from `import`:

```haxe
// Imports a class
import myPackage.MyModule.MyClass;
```

```haxe
// Allows a class
@:allow(myPackage.MyClass)
```

```haxe
// Imports all classes in a module
import myPackage.MyModule;
```

```haxe
// Only allows myPackage.MyModule.MyModule
@:allow(myPackage.MyModule)
```

**Comment by Simn** [comment]
This is actually tricky because unlike addGlobalMetadata we have to consider context here. If you have `@:allow(MyHelper)` you would want both `current.package.CurrentModule.MyHelper` and the top-level type `MyHelper` to work. But even that would come with surprises because ACL does not respect imports.

I'm not sure this is worth spending much time on because it's possible to work around this issue by using different paths.

**Comment by Simn** [comment]
This would require a review of the access control implementation which I don't think is worth it.
