### ISSUE TITLE
[python] class/module naming for python std lib

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3684]
I wonder if there's was a final decision of naming scheme for haxe extern classes repesenting python std lib.

What I have concerns about is classes like `ShUtil`, `DateTime`, 'FuncTools', etc. that represent `shutil`, `datetime` and `functools` python modules respectively. For `hxnodejs` project we chose to only capitalize first letter (so e.g. `datetime` becomes `Datetime` and not `DateTime`) which seems consistent, especially considering that we have e.g. `Tempfile` extern for the `tempfile` python module.

I think we should decide on that and clean up our python std lib externs before 3.2 because after that it'll be breaking change (even tho python target is experimental).

cc @Simn @frabbit

**Comment by Simn** [comment]
@nadako: Are you gonna take this one?

**Comment by nadako** [comment]
Well I guess someone has to :-)

**Comment by frabbit** [comment]
Hey guys i can do it too, i'm back in business now and want to work in The Python target in the next days and weeks. Sorry for beeing unresponsive in the last time, will come back to IRC soon ;)

**Comment by frabbit** [comment]
and yes i agree it should be consistent

**Comment by nadako** [comment]
Nice! Feel free to work on it then :wink:. I'll join when I have time.

**Comment by frabbit** [comment]
let's summarize our options:

1)
ShUtil => Shutil
FuncTools => Functools
ByteArray => Bytearray
datetime.DateTime => datetime.Datetime
datetime.TimeDelta => datetime.Timedelta
datetime.TzInfo => datetime.Tzinfo

should we really go this way? Or should we fix the ones that don't follow this convention like:

2)
Tempfile => TempFile
Subprocess => SubProcess
etc.

actually i would rather go the second way, because it's more haxe conform. I know it's a difficult question because native function names doesn't follow haxe conventions too. 

On the other hand, most types in python follow pascal-case-convention. Modules does not, but static members of modules become a class Haxe, so one could argue that it would be consistent to have all python classes follow this convention.

**Comment by frabbit** [comment]
ping @simn @nadako

**Comment by Simn** [comment]
I think 1) is better because it doesn't involve any decisions about what to capitalize. That's good for both us and the users. I leave it to you guys though.

**Comment by nadako** [comment]
I agree with Simon and that is also how hxnodejs is done.

**Comment by frabbit** [comment]
OK thats fine, but i leave classes that are already PascalCase as they are, right?

**Comment by nadako** [comment]
You mean like `codecs.StreamWriter`? Sure. I think the rule should simply be like: `captialize class/module names that start with lowercase`, so `datetime` becomes `Datetime`, but `codecs.StreamWriter` stays as is.
