### ISSUE TITLE
[inlining] wrong unification with abstracts + inlining

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3713]
```haxe
class A<T> {
    public function new() {}
}

abstract B<T>(A<T>) {
    public function new() this = new A();
    public inline function f():C<T> return new C(this);
}

class C<T> {
    public inline function new(d:A<T>) {}
}

class Main {
    static function main() {
        var b = new B<Int>();
        var c = b.f();
    }
}
```

```
Main.hx:17: characters 16-21 : d : A<Int> -> Void should be B<Int> -> Void
Main.hx:17: characters 16-21 : Cannot unify argument 1
Main.hx:17: characters 16-21 : B<Int> should be A<Int>
```

if we remove `inline` from either `f` or `C` constructor, it compiles fine.

**Comment by Simn** [comment]
My fix for this wasn't perfect. We don't actually want to override the expression type in some cases as that changes the TField expressions, which in turn cause trouble with `@:multiType` abstracts.

**Comment by Simn** [comment]
Okay, I don't think we can avoid the temp var creation for the abstract `this` variable. The reason being that it has a different type between the "inside" and "outside". In the original example the `this` within `B.f` is typed as `A<T>` (the underlying type), while the outside `b` local is typed as `B<T>`. This leads to the unification error.

We also cannot cast it because in that case we would end up with something like `(cast this) = value` for assignments which doesn't make any sense.

Lastly we also cannot rewrite the expression type because that leads to issues with `@:multiType` abstracts which require the "outside" type to determine what to resolve to.
