### ISSUE TITLE
Is there any way to use keywords in externs fields?

### ISSUE THREAD

**Issue by PeyTy** [HaxeFoundation/haxe#3745]
There is a field named `luanet.enum`. Of course Haxe disallows own keywords as fields names.
Such syntax of `@:native("enum")` does nothing:
```haxe
@:native("luanet") extern class Luanet
{
    @:native("enum") public static function enums(type:Dynamic, value:String):Dynamic;
}
```
But `@:native("luanet")` works as expected.
Tested on JS

**Comment by sonygod** [comment]
+1

**Comment by YellowAfterlife** [comment]
This would be pretty handy for JSGenerator-based targets, since, if needed, language-specific registered keywords can be blocked or auto-renamed separately.

**Comment by fzzr-** [comment]
:+1:

**Comment by Simn** [comment]
This generates `luanet["enum"](null,null);` which is exactly what I expect it to generate. I don't understand what the issue is here?

**Comment by PeyTy** [comment]
@Simn http://try.haxe.org/#74A59 Dont work for me. Is it fixed in Haxe 3.2 ?

**Comment by Simn** [comment]
`@:native` on class fields is itself a 3.2 feature. Why are you talking about keywords here?

**Comment by PeyTy** [comment]
```haxe
@:native("luanet") extern class Luanet
{
    /* field named enum */
    public static function enum(type:Dynamic, value:String):Dynamic;
}
```
@Simn okay, so this works in 3.2. Issue closed

**Comment by Simn** [comment]
Eh, it doesn't work in 3.2. like that either. enum is still a keyword.

**Comment by PeyTy** [comment]
Then, we are all waiting for fix. I think this is more like a bug, because it looks like very natural for externs to have such feature

**Comment by Simn** [comment]
???

Your original example already compiles to what I posted. What else do you want? We will not change the parser to allow keywords in these places.

**Comment by PeyTy** [comment]
Sorry for the misunderstanding. if @:native works, then everything is fine.

**Comment by nadako** [comment]
I wonder if we can make try.haxe.org provide two versions to choose from - haxe release and auto-updated haxe git, so people could easily check if the issue is still there. ping @clemos, @markknol

**Comment by Simn** [comment]
That's funny, I was bugging @markknol about the same thing just yesterday. :)

**Comment by clemos** [comment]
It would be great.
I've been looking into Docker for my job, lately.
I think it might be a solution for multiple / custom haxe install, but also to enable macros (filesystem access, ...) and eventually sys/server targets ;)
Please open an issue on try haxe so we keep track of this.

**Comment by markknol** [comment]
@Simn pointed me a related interesting thing that could have some more thoughts. You ask for a dev build option somyou can compare manually. But basically we only need the try-haxe snippets that actually compile/run. If we can log that with the current haxe version, we could compile/run the same snippets agains the latest dev build and compare both. This would give us thousands of free tests. 
In my opinion this shouldnt be a public part of try-haxe since this is only interesting for the haxe team. I also think retesting case by case with latest devbuild is not that practical(?) but at the other hand it would be nasty to make everything complete public (who knows what people put in the snippets). So as a separate tool/service on top of try-haxe it could be very useful.
What do you guys think?
