### ISSUE TITLE
Code output stability and features

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3787]
I'm still getting different code output for CastleDB depending if I'm using compilation server or not.
This is related to the JS output of `$estr` (enum to string). I guess something related to "features" activation is not properly cached, which could result in runtime errors.

**Comment by Simn** [comment]
I forgot again how all this is supposed to work. Features are stored in `com.features`, but how does that work with the compilation server?

**Comment by ncannasse** [comment]
They should also be stored in module.m_extra.m_features, so we can copy them, but it seems to be only done in Dce.run (so never done when -dce no ?)

**Comment by Simn** [comment]
`m_features` is something else: When we type a field which has `@:ifFeature("f")` we put that field into `m_features`. DCE then picks these fields up and puts them in a hash table in order to check them as soon as a feature is "activated".

The problem with `$estr` seems different because it's a plain `has_feature "may_print_enum"` check. That feature is set during post-processing (before the class state is saved) by checking which enums are assigned to `Dynamic` because in that case we have to assume that it might be printed.

The thing is that once a feature is set, I don't see how it would be unset from the common context at all as long as the compilation server is running...

**Comment by ncannasse** [comment]
We have a new common context for each compilation, but we will reuse the modules (maybe some of them, maybe all of them). That's why we need to store per-module feature activation. Maybe we should store may_print_enum on a per module basis then activate it in the common context if one of the modules have it

**Comment by Simn** [comment]
So what you're saying is this: instead of adding features to the common context we add them to the module, then just before generation we "commit" all these features to the common context. Right?

In this scenario, what if a module loses a feature while the compilation server is running? Is that reset somewhere?

**Comment by Simn** [comment]
@ncannasse: please test now.

**Comment by ncannasse** [comment]
@Simn what do you mean by "losing a feature" exactly ? :)

**Comment by ncannasse** [comment]
I confirm that the feature is no longer disabled when using compilation server, thanks !

**Comment by ncannasse** [comment]
@Simn if the module is modified, then it's discarded and rebuilt. Does that answer your question about losing features ?
