### ISSUE TITLE
Missing parameter error does not report missing type ( Java ).

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/haxe#3802]
Missing parameter error does not report missing type ( Java ).

var ge = GraphicsEnvironment.getLocalGraphicsEnvironment();// import java.awt.GraphicsEnvironment;
var gd : GraphicsDevice = ge.getDefaultScreenDevice(); // import java.awt.GraphicsDevice;
gd.isWindowTranslucencySupported();

Not enough arguments
Function 'isWindowTranslucencySupported' requires arguments : param1

Error message could read:

Not enough arguments
Function 'isWindowTranslucencySupported' requires arguments ( param1:java.awt.GraphicsDevice.GraphicsDevice_WindowTransulencency )

**Comment by Simn** [comment]
You picked the worst target for this feature request because there could be overloads on Java which makes it hard to give an accurate error message.

What we could do is make the compiler output the position of the field it tried to call so that you get another error line reading "File.hx:12:See definition of isWindosTranslucencySupported". That requires some internal changes though so I can't add it for 3.2.

**Comment by Justinfront** [comment]
Simn could Haxe cope more easily with functions that aren't overloaded and leave overloaded ones till later revision, that way the feature will definitely happen, it's so much easier to have error messages that hint you on the type especially useful on Java, and I think the user would understand if the compiler indicated multiple options but did not specify.

**Comment by Justinfront** [comment]
But it's not something that needs to get into next release, just meaning to say that incremental might be better.
