### ISSUE TITLE
[cs] generation of haxe anon functions that are unified with delegates

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3809]
as we talked on #haxe-dev, currently for those functions we generate a `Delegate` method with function body and make `__hx_invoke*` call it which introduces a function call cost which could be pretty significant for simple functions. what we could do is implement it vice-versa - keep function body in the `__hx_invoke*` method and make `Delegate` call it.

**Comment by waneck** [comment]
Oh wait did you mean only for the functions that are unified with
delegates? I thought you meant adding another function with the correct
types only for the sake of making it easier for C# code to interop with
haxe generated code.

Right now, for functions that are unified with delegates, Haxe already
generates that extra function. And since there's no way to transform it
back into an Haxe function, I think that in this case we should optimize
for the actual delegate case.

**Comment by nadako** [comment]
> Oh wait did you mean only for the functions that are unified with
delegates? I thought you meant adding another function with the correct
types only for the sake of making it easier for C# code to interop with
haxe generated code.

That as well :-)

> Right now, for functions that are unified with delegates, Haxe already
generates that extra function.

Yeah but it places function body inside "correct-types" method (`Delegate`) and makes a call to it from `__hx_invoke` and you said that adds significant overhead for simple functions. Or did I misunderstand you?

**Comment by waneck** [comment]
I'm confused about this. I think haxe currently does what should be done: It makes the non _hx_invoke function the main one - since it doesn't have to mangle the types so it will be the fastest anonymous function. Otherwise we'd have to pay the price of the types mangling even if it's being called by the C# delegate.
For now, I'm closing this, but feel free to reopen if you think I'm wrong :)
