### ISSUE TITLE
Null<T> vs. default values

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3826]
On my quest to write some more `Null<T>` tests to make sure nobody ever gets the idea of writing a fast static target for Haxe `</rant>` I came across this old case again:

```
class Main {
    static function main() {
        var n:Null<Int> = null;
        printA(n);
    }

    static function printA(a = 1) {
        trace(a);
    }
}
```

There are two possible interpretations of what should happen here:
1. Upon assigning `n` to `a` we detect a `Null<Int>` being assigned to `Int` case, generating an unbox-or-use-default-value-if-null. Alternatively we let the target run-time deal with it to the same effect. In this case it would print `0`.
2. We detect that we are assigning a possibly-null value to a non-null optional argument and go with the use-default-value-if-argument-is-null idea. In this case it would print `1`.

Currently this is one of these things where all targets expect Flash/As3 agree on 2. Is this a necessary limitation, an oversight, working as designed, clearly broken or what?

**Comment by ncannasse** [comment]
My original idea is to make a difference between `foo(a=1)` and `foo(?a=1)`. In the first case, you're having an optional argument with a default value, but the argument is not nullable, which enable some additional optimizations on static targets.

So yes the actual Haxe specification is ( 1 ). I think it's a good thing to enable fast optional arguments on static targets. It also enable to express the way things actually works when the underlying VM does support such constructs (for instance when overidding an native method)

**Comment by Simn** [comment]
We have to be careful with null padding if you want to go for that. Extending the example:

```
class Main {
	static function main() {
		var n:Null<Int> = null;
		printA(n);
	}

	static function printA(a = 1, b = 2) {
		trace(a);
		trace(b);
	}
}
```

The AST of the call on cpp is this:

```
[Call:Void]
	[Field:?a : Int -> ?b : Int -> Void]
		[TypeExpr Main:Class<Main>]
		[FStatic:?a : Int -> ?b : Int -> Void]
			Main
			printA
	[Local tmp(149):Null<Int>]
	[Const null:Null<Int>]
```

Type-wise the two cases are indistinguishable: we assign `Null<Int>` to `Int`.

**Comment by ncannasse** [comment]
That should not make any difference here. trace(a) should never print null since a is not `Null<Int>` but Int

**Comment by ncannasse** [comment]
But yes I see your point : in case the argument is null, should it be cast to 0 or should we use the default value argument ?

**Comment by ncannasse** [comment]
And yes in that case you're right we should have  a=0, b = 2

**Comment by Simn** [comment]
For genc I'm addressing this by checking if we're assigning `TConst TNull` to a basic type which is not `Null<T>`. The assumption is that null padding is the only way this could occur, but it feels a bit weak.

**Comment by ncannasse** [comment]
We could add a TMeta for such cases

**Comment by Simn** [comment]
I'll have to check that, but I'm concerned that we might need something more elaborate if someone takes a closure of a function like that:

```haxe
class Main {
    static function main() {
        var n:Null<Int> = null;
        var closure:?Int->?Int->Void = printA;
        closure();
    }

    static function printA(a = 1, b = 2) {
        trace(a);
        trace(b);
    }
}
```

This gets really weird because we either get nullable optional arguments or non-nullable optional arguments _without default value_ because we cannot determine default values from types. I'm assuming it's the former because a) the `?` implies nullability for function arguments and b) the latter doesn't have a syntactic representation.

But that leads to the original issue again if we imagine the closure being a forwarding function (e.g. to deal with required casts that our type system just waves through):

```
var closure = function(?a, ?b) return printA(a, b);
```

That would again cause the null-to-0 coercion which then means calling `closure()` would give a different result than calling `printA()` directly.

**Comment by ncannasse** [comment]
Maybe that closure should not unify since we have a type difference here?
That would restrict to using  Int -> Int -> Void in that case, until we find an actual representation for this.

For instance, do we allow already:

```haxe
function foo( i : Int ) {
}
var f : Null<Int> -> Void = foo;
```

That's a similar problem.

**Comment by Simn** [comment]
Unfortunately that would likely require a larger review of `Null<T>` which is not really viable for Haxe 3. I'm all for it though because that implicit type difference is a pain to deal with.

**Comment by Simn** [comment]
@ncannasse: This affects HL too:

```haxe
class Main {
    static function main() {
        var n:Null<Int> = null;
        printA(n);
    }

    static function printA(a = 1) {
        trace(a); // 1
    }
}
```

**Comment by Simn** [comment]
We might want to consider a spec-change for Haxe 4 here. Supporting the `null -> 0` behavior is gonna be a major pain from what I can tell.

I don't think we have to take any action for Haxe 3 though.

**Comment by Simn** [comment]
bump

We should make up our minds about this one. Still not really sure what to do with it...

**Comment by RealyUniqueName** [comment]
If we are considering changing a spec, then maybe instead consider a compiler error if user passes `Null<Int>` to the `Int` argument with default value?

**Comment by Simn** [comment]
Requires decision

**Comment by ncannasse** [comment]
I agree we need to specify, but at the same time it seems quite hard to enforce a given specification on all platforms...  

static platforms clearly specify that `Null<Int>` cast to `Int` should be `0`, so I would say that HL interpretation is correct, I don't think `printA()` and `printA(null)` are the same thing (which is coherent with also having the value being `Dynamic`). And I think that `printA(v)` should be same as `printA((v:Int))` since the argument is an Int.

But for Dynamic platforms since null is a valid value for Int, `printA(null)` might express _I want `a` to be null_ which we don't allow and instead substitute to 1. But for implementation reasons (not all dynamic platforms have a concept of `undefined`) I think we should keep current behavior.

So my tentative answer would be:
- `0` on static platforms 
- `1` on dynamic platforms

Although I don't like to introduce a discrepancy here, I think that's the best here.

**Comment by RealyUniqueName** [comment]
> * 0 on static platforms
> * 1 on dynamic platforms

Horrible debug sessions are coming.

**Comment by RealyUniqueName** [comment]
What about these cases:
```haxe
function test(a = 1, b = true, c = 2) {
  trace(a, b, c);
}

test(false); //generated as test(null, false, null)
```
Also, we have 8 targets with null padding for optional arguments.

**Comment by ncannasse** [comment]
Uhm, there's a problem here... it seems we indeed have a lot of static targets with null padding...

**Comment by ncannasse** [comment]
@RealyUniqueName you cannot skip not nullable arguments on static platforms anyway

[EDIT] : actually I was thinking that was the case but only HL and Flash did not allow such skip. Since HL supports it quite well actually so I've enabled it in PR. Might need to look at the bind() failing case.

**Comment by ncannasse** [comment]
More thoughts on this : 

somehow it comes to down to what is the meaning of `foo( x = 1 )` . For me, it should be the same as `foo(x : Int)` except that we can pass 1 as default value. So the signature of the `foo` function on static platforms should be `Int -> Void` as it's correctly set by haxe compiler.

But that's not for instance what Java does, as it generates a `java.lang.Object` for each optional parameter whereas they are nullable or not.

At the same time we need some way to specify "no value" (for reflection support for instance), and we are back to the question - is "no value" the same as "null" value ?

In HL runtime I have two different types. I pass nullable optional args as `null<i32>` (which are actually "dynamic" GC allocated values - which performs boxing). And I pass not nullable optional args as `ref<i32>` which is the same as `int*` in C, so no boxing involved.

@hughsando @waneck what's your take on this ?

**Comment by hughsando** [comment]
I think it comes down to: please do call-site substitution of default params.

Hxcpp uses `Null<Int>` which is a struct of int plus a bool to say whether it is specified.  But, the ast puts a `TConst(null)` in the calling arg and this is how the bool flag is set.  So in fact, it logically indistinguishable from a boxed-int, using null as a "specified" flag - it is just a performance optmization.
Since the ast puts null in the call site AST, there is no way to tell whether the programmer put an actual null value in there, or whether the compiler generated one.
I think the only way he can hope to tell them apart is to insert the default values at the call site. 

If haxe did this, then I could change the signature to be an actual "int" - and i would have to do some funny business with the dynamic wrappers to add the default values in this case.  This would separate the null from unspecified in the compile-time case (ie, passing null would transform to 0, as "desired").
But is it actually broken?  If all the targets are doing the same thing, then just make it the specification.

**Comment by hughsando** [comment]
Also, it it probably more of an issue with default enum values.  You can not tell the difference between an actual null and an compiler-generated missing arg, and this is the same across all targets not matter what they do.

**Comment by ncannasse** [comment]
I have updated the proposed specification by unifying static/dynamic platforms.
That leaves flash out of the spec, and I need to work on HL to support this, but I guess other platforms will be ok.

**Comment by Simn** [comment]
I think that's the right choice here.

**Comment by vonagam** [comment]
What about externs though? Resulted design choice does not take them into account and they do not expect some nulls coming in.

Padding with specified default values instead of nulls as Hugh proposed would have worked with both external and haxe generated functions. Why wasn't that route chosen instead?

**Comment by RealyUniqueName** [comment]
A parent and overridden methods may have different default values.
```haxe
extern class Parent {
  function test(i:Int = 1):Void;
}
class Child extends Parent {
  override  function test(i:Int = 2) 
    super.test(i);
}

(v:Parent).test(); // should this call get 1 or 2?
```

**Comment by Simn** [comment]
I remember thinking that this should be a compilation error, but IIRC people disagreed.

**Comment by RealyUniqueName** [comment]
Imagine both `Child` and `Parent` are extern classes. A compilation error would mean it's impossible to use them from Haxe.

**Comment by hughsando** [comment]
Externs can be handled with overloading the function with different number of args.  The default value would then be inserted in the haxe code as a comment, since it is the native value that actually fills in the blank.

**Comment by vonagam** [comment]
> A parent and overridden methods may have different default values.

Interesting case. That means that padding will not work either way for native optional values and should be forbidden for such.

> override function test(i:Int = 2)

This will not produce valid output on any static target, since extern says that it has argument of type `Int` but in override it will be some kind of `Null<Int>`.

> (v:Parent).test(); // should this call get 1 or 2?

And currently instead null is passed to an argument that says that it does not accept nulls...

> A compilation error would mean it's impossible to use them from Haxe.

Thus nothing will change because it is already impossible to use them. (I am not for making it an error, just pointing out.)

> Externs can be handled with overloading the function with different number of args.

Overloads are for overloads and optional arguments for optional arguments. If overloads were a proper solution and not a hack then haxe would have generated those overloads for native optional arguments, but it does not because, for example, it screws up overriding.

Why padding is needed in the first place? 
Why static targets generate non-optional arguments for optional arguments?

**Comment by hughsando** [comment]
The first thing to think about is, are you trying to replicate the default value in the header?  If so, you should use overloading to get haxe the generate fewer params in the function call.  This way you will never be out-of-sync with that the header/library thinks the best default value is. From the developer point of view in c++ you simply do not put the extra parameter in there, and you can't tell the difference between overloaded function call with fewer parameters and one where the default is filled in for you. In fact, the library may change the implementation here and the code will still work.  So in this sense, overloading with fewer parameters is not a hack, but it accurately reflects the API of the library.
If you want to provide a haxe default that is independent of what the header thinks the default should be - or indeed independent of whether the header thinks there should be a default at all, then you can make an inline translation function.
Call-site defaults would be nicer for providing different defaults, but you could run into the problem in keeping the haxe default in sync with the header default for externs.
I think having some type of call-site defaults for all targets should be relatively well-defined, maybe 'inline' ?
```haxe
function someFunc(inline a=1, inline b=2)
```
Here the function would not be required to change any dynamic null to a "1", just like a function without defaults.

**Comment by vonagam** [comment]
I try to understand why static targets output non-optional arguments for optional arguments.
```haxe
class Check {
  static function nativish(x: Int = 0) {}
  static function nullish(?x: Int = 0) {}
}
```
Why cpp and cs generate non-optional nullable arguments for `x`?

**Comment by vonagam** [comment]
@RealyUniqueName replying to [this](https://github.com/HaxeFoundation/haxe/issues/3826#issuecomment-672755360)

> (v:Parent).test(); // should this call get 1 or 2?

Turns out that convention between static targets which support optional arguments (cpp and cs) is to use default values of class on which call being dispatched ([1](https://stackoverflow.com/questions/3533589/can-virtual-functions-have-default-parameters), [2](https://rules.sonarsource.com/csharp/tag/pitfall/RSPEC-1006)). So the answer seems to be 1 (parent default). But as said in those links - it is not good to change defaults and ideally such changing should produce a warning.
