### ISSUE TITLE
Anon typing rules

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#3856]
Please see the following code, live example at: http://try.haxe.org/#30234
There seems to be a difference in the unification of anons, in some cases { x : Int, y : Int } unifies with { x : Int } and in others it doesn't. The difference in the following code seems to be the presence of _any_ explicit type annotation for the entity typed as { x : Int, y : Int };
If such an annotation exists, something typed as  { x : Int, y : Int } unifies with something typed as { x : Int }. 

There is one exception, though,  f4(v_no) even compiles for v_no, which isn't explicitly typed, so there seems to be yet another special case if the explicit type is introduced by the type parameter constraint of the function. 

The question is what the intended behavior in these cases should be, and I think @ncannasse knows the answer :) 

.. but if there isn't a definitive answer so far, I'd vote for "no unification" in all cases presented here.

```haxe

typedef K  = { x : Int };
typedef KX = { x : Int, y : Int };

class Test {
    
    static function f1(v) return v.x;
    
    static function f2(v:K) return v.x;
    
    static function f3(v:{x:Int}) return v.x;
    
    static function f4<T:K>(v:T) return v.x;
    
    static function main() {
        
        var v_yes:KX = {x:1,y:2};
        
        f1(v_yes);
        f2(v_yes);
        f3(v_yes);
        f4(v_yes);
        
        var v_no = {x:1,y:2};
        
        // the following don't compile
        
        // f1(v_no);
        // f2(v_no);
        // f3(v_no);
        
        // but !!!!!!!!!!!!!!!!!!!!!!!!
        
        f4(v_no);
        
        // does.
        
        
        // as well as the following: 
        var v2_yes = ({x:1,y:2}:{x:Int,y:Int});
        
        f1(v2_yes);
        f2(v2_yes);
        f3(v2_yes);
        f4(v2_yes);
        
        // same types, of course:
        
        $type(v_no);
        $type(v2_yes);
        
        // not specific to calls
        
        var x:K;
        x = v_yes;
        x = v2_yes;
        // x = v_no; // gives:
        // {y:Int,x:Int} has extra field y
        
        var y:{x:Int};
        var y_no                = {x:1,y:2};
        var y_yes:{x:Int,y:Int} = {x:1,y:2};
        y = y_yes;
        //y = y_no; //same here.
        
    }
}
```

**Comment by ousado** [comment]
OK, relevant issues ( thanks @deltaluca )
https://github.com/HaxeFoundation/haxe/issues/3192
https://github.com/HaxeFoundation/haxe/issues/3198

The answers seem to suggest that haxe allows structural subtyping among anons, while the manual http://haxe.org/manual/type-system-structural-subtyping.html states that it's supposed to be available to classes being unified with anon types only.

**Comment by ousado** [comment]
Any chance to get an answer to this one? It's certainly a crucial point when writing a target.

**Comment by Simn** [comment]
I always thought Haxe didn't allow structural subtyping between structures (only class vs. structure) but it looks like that's simply wrong.

**Comment by ousado** [comment]
Thanks, time to rethink anons for genc then, I'm afraid.

**Comment by Simn** [comment]
Yes this basically forces us into a dynamic route for the general case. We can detect cases where this is not necessary, but the default implementation is likely gonna be the same as if it was Dynamic.

**Comment by ncannasse** [comment]
Another way of doing is to pass around two values:
a) the first contains the anon data, as well as its structure
b) the second is an index that maps the current type to the anon fields.

For instance if you have
runtime value = { x : 0, y : 0. };   compile time type : { x : Int, y : Float }; then you have an index [0,1]
if you have 
runtime value = { x : 0, v : 1, y : 0 }, then your index wil be [0,2]

Of course, when "upcasting" an anon, this requires to query at runtime the corresponding index map. These can be either prebuild (but that would takes a lot of space and a lot of potential combinations are not likely to happen) or built on demand, then cached into the shared runtime data.

For efficiency it would be required to have all runtime values having the same fields+types combinations to share the same "type" with the indexes maps. Using Reflect on an anon struct might change its "type" or even create a new one since we can't predict the outcome.

It would also work for classes instances BTW.

The only drawback I can see is subtyping for Int/Float : if we pass { x : (0:Int) } to { var x(default,null) : Float } then we need to be able to detect this as well.

**Comment by ncannasse** [comment]
And yes I confirm that structure subtyping works:
 * between a classe and a structure
 * between structures
So for instance any class/structure can be unified with `{}`

**Comment by Simn** [comment]
Keeping this open as a reminder to fix the manual.

It's quite strange because I distinctly remember committing to my memory that there's no structural subtyping between structures. I guess this must have come up in the context of constant structures and I just interpreted it wrongly.

The index idea still requires an additional indirection, but I suppose it's better than a fully dynamic lookup.

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/HaxeManual/issues/119

**Comment by jcward** [comment]
Reading the above linked issues, I have a possibly-related question... Can someone explain [this case](https://try.haxe.org/#962cF), please?

**Given:** A named struct, TypeA, has an optional field.

Specifically the error on line 26 is weird to me:

- While I can assign an anonymous structure (missing the optional) to a named structure,
- I cannot assign a named structure (seemingly of the same type as the anonymous) to the named structure.

I think the root issue is, on a static target, "absence of a field is not the same as a nullable field" (though on a Dynamic target, they are effectively the same.) So I think I understand why... but it still feels odd.

Is there anything that could be done to make this (and perhaps other issues) feel more consistent? e.g.
- This could be allowed when targeting dynamic targets (but probably not good to make compiler errors only on static targets?)
- This could be handled under the hood to satisfy static targets... if I were describing it as an abstract, it would assign each field to a compatible instance, leaving the optional null.

Sorry to bump an old thread, and thanks for any input.
