### ISSUE TITLE
Implement `let` value binding

### ISSUE THREAD

**Issue by roobie** [HaxeFoundation/haxe#3886]
It should act like a `var` but only bindable once, and required to do so at declaration. Similarly to OCaml `let`

**Comment by ncannasse** [comment]
You don't say why ?

**Comment by Simn** [comment]
Let bindings are questionable in an otherwise mutable world. Also it only makes sense if the code generators utilize it to generate optimized code (e.g. reuse the same allocated memory for bindings to the same name).

I think with SSA transformation we're well equipped to optimize mutable variables. From a usability point of view you might as well declare your variable once, then reassign to it. This only fails if there are type differences in which case it's doubtful that they should have the same binding name as well.
