### ISSUE TITLE
Possible issue with absolute -swf-lib value

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#3912]
Hey guys,

Someone reported that switching to an absolute -swf-lib path caused problems on their system:

https://github.com/openfl/lime/issues/345

Motion-Twin reported that having multiple -swf-lib tags was causing conflicts when they used relative paths, perhaps with similar file names, I'm not sure.

I can't reproduce, but thought someone might have an idea, if they know of something in the code that might cause this to fail under certain circumstances that I'm not aware

**Comment by Simn** [comment]
This might be OS-specific because file lookup depends on class paths which depending on the OS have different settings. For me (Windows) the class paths contain `""` which implicitly deals with absolute paths when they are appended to it. Thus when compiling with `-swf-lib "c:\\github\swf.swf` the compiler performs these lookups:

```
class path: "src/", full path: src/c:\\github\swf.swf
class path: "C:\GitHub\haxe\extraLibs/", full path: C:\GitHub\haxe\extraLibs/c:\\github\swf.swf
class path: "", full path: c:\\github\swf.swf
```

I'll find a Unix person to double-check this for 3.2.

**Comment by Simn** [comment]
There was indeed a problem which only surfaced when `HAXE_STD_PATH` was set (which it is by default on Linux).

**Comment by Simn** [comment]
P.S.: This might have affected other code that used `Common.find_file` as well such as Context.resolve.

**Comment by jgranick** [comment]
Great, I'll report this back and see if removing the environment variable can fix it, glad to help get this in before the next release, thanks so much! :smile:
