### ISSUE TITLE
syntax error that shouldn't compile

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#3915]
``` haxe
class Test {
    static function main() {
        function expand (p:Array<String>) {
            return [(for (x in p) x]; // this should not compile
        }
        trace(expand(["1"]));

    }
}
```

**Comment by frabbit** [comment]
thx, i get an error now ;)

**Comment by ncannasse** [comment]
If everybody could be as happy as you when they get a compiler error, the world would be a better place :)

**Comment by Simn** [comment]
You actually get not one but THREE `Unexpected ]` from this. I really think we should check our exception catching.

**Comment by frabbit** [comment]
@ncannasse definitely better than an empty array at runtime ;)

@simn `Unexpected ]` was quite clear to me ;)

**Comment by Simn** [comment]
Following parser control flow stories is a lot of fun... What I think happens is that we come across the first error as a Stream.Error because the POpen doesn't have its PClose. This is caught in `block` which recurses upon itself and then exits via Stream.Failure.

Act 2 takes us back to `parse_class_fields` which wants its beloved BrClose to find happiness in life. However, there's still the evil `]` in the stream, leading to the second error.

The plot twist is that I don't know where the third one comes from, but this is material enough for me to believe that catching Stream.Error is a bad idea.
