### ISSUE TITLE
[analyzer] Prune assignments in dead branches

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3938]
The following code is not completely optimized at the moment:

```
class Main {
	static function main() {
		var a = 1;
		if (a == 1) {
			a = 2;
		} else {
			a = 3;
		}
		trace(a);
	}
}
```

JS output:

```
	var a = 1;
	a = 2;
	console.log(a);
```

Clearly this could be optimized to `console.log(2)` here. The problem is that while we cut off dead branches during const-propagation, we do not prune the assignments that occur there. Thus the value of `a` after the branch is still `__ssa__phi(2, 3)` and const propagation doesn't happen.

This isn't hard to fix but is going to require some internal changes, so I'll leave it for 3.3.

**Comment by delahee** [comment]
As a professionnal optimizer, I have to ask for some feature to prevent a 'var' being optimized

for ex:

```
var z = 0;
for( v in vectors)
 v.x = z;
 v.y = z;
 v.z = z;
```

will get translated to :
```
for( v in vectors)
 v.x = 0;
 v.y = 0;
 v.z = 0;
```

where it should really be : 
```
(volatile) var z = 0;
for( v in vectors)
 v.x = z;
 v.y = z;
 v.z = z;
```
 z must never get optimised and splat along so that cpu pipeline optimisation and register preemption can operate properly...

You must think I am crazy but that is an actual use case...

**Comment by deltaluca** [comment]
I would be very suprised if this made any real difference when writing Haxe code (vs assembly.)

**Comment by delahee** [comment]
I have several case where it made big difference ( software morphing code on ARM based archs, binary decoding, png alpha premultiplication etc... ) and that is a well known fact for cpu optimizers that constants are sometime worth eliminating because they are wayyyy  longer to load than registers. 

Because all architecture are not made equal. :)

If you want I can certainly exhibit a benchmark but I have no such time to spend  atm so it will have to wait :)

**Comment by delahee** [comment]
I think some kind of unescaping for analyzer would suffice:
ex

```
@:no_analyzer
function foo(){
 ...
}
```

@Simn do you think its we can consider something like that ?

**Comment by Simn** [comment]
Try `@:analyzer(no_const_propagation)`

**Comment by delahee** [comment]
Ok thank you !

2015-06-04 12:56 GMT+02:00 Simon Krajewski <notifications@github.com>:

> Try @:analyzer(no_const_propagation)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/haxe/issues/3938#issuecomment-108839754>
> .
>



-- 
David Elahee
