### ISSUE TITLE
Int64 unistd support

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3940]
Seems like comparing Int64 with

```
haxe.Int64.make(0,0) == haxe.Int64.make(0,0)
```

in unistd is not supported. I guess it goes through Dynamic. We can either change that by doing .compare() == 0 but it might be better to support it directly (if possible) since it makes writing unit tests on 64 bit values easier

**Comment by ncannasse** [comment]
Also, that most likely mean we don't have yet unit tests for Int64 :)

**Comment by Simn** [comment]
The Int64 tests are in Test64 because they predate the unitstd implementation.

I'll check what's going on with the equality test.

**Comment by Simn** [comment]
Actually that's (not) working as expected because `a == b` is translated to `eq(a, b)` which means no operator is resolved. I don't want to make a special case for Int64 here because then we would just have the same problem with the next abstract.

I have changed the test to `t(b.getInt64(17) == haxe.Int64.make(0xABCDEF00,0xCAFFEED1))`.
