### ISSUE TITLE
JS API regressions

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4005]
Got the following errors while compiling with new JS API:

```
js.html.CanvasRenderingContext2D has no field imageSmoothingEnabled
js.html.Element has no field onmousewheel (Suggestion: onmouseenter)
js.html.Element has no field scrollIntoViewIfNeeded
```

Given that it's on a small project that mostly use JQuery, that makes me worry we will hit a big number of such incompatibilites when releasing 3.2. Any insight @aduros ?

**Comment by aduros** [comment]
scrollIntoViewIfNeeded is webkit-only and not in any standard AFAIK.

onmousewheel is also non-standard, and never actually worked in Firefox. The new name in the DOM3 spec is "onwheel", which is included in these externs.

This raises a good discussion about maintaining these externs. What happens when specs change? Do we provide backwards compatibility (which may not work at runtime) or allow the compiler help fix broken code?

imageSmoothingEnabled is a good one, I'll add that in there. It is prefixed in most browsers, which is why it didn't show up.

**Comment by ncannasse** [comment]
@aduros In general I'm in favor of adding even the non standard spec if they are already supported by some dominant browser(s). It's then up to the user to do the work of looking at browser support for such capabilities.

If/when the spec change we can use `@:deprecated` for that and suggest the new way of doing, but maybe not sure because even in that case people might want to fallback on old method if != null to support older browser version

**Comment by ncannasse** [comment]
PS: In my case it's for CastleDB, which uses NWJS so only webkit is needed
I also got an error about DOMWindow being renamed to Window. Maybe we should keep a DOMWindow with @:deprecated so at least the code compiles

**Comment by ncannasse** [comment]
that would be:  @:deprecated("use js.html.Window") typedef DOMWindow = Window;

**Comment by aduros** [comment]
One example case is Gamepad.buttons, which was an [Array&lt;Float>](https://github.com/HaxeFoundation/haxe/blob/a06f9d35ae138be1e163444146354933301697f4/std/js/html/Gamepad.hx#L31) in an old version of the spec, but then the Gamepad spec and browsers changed to [Array&lt;GamepadButton>](https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/Gamepad.hx#L34).

We could handle simple renames with @:deprecated, but unless the externs never change, we're going to have to introduce incompatibilities sometimes. I think that's a good thing! By compiling against the latest Haxe, you can be reasonably sure your app is standards compliant and works in modern browsers. If I'm compiling a web project that uses webkit-only or deprecated APIs, I'd want the luxury of finding those issues at compile time rather than hitting bugs at runtime.

As for NWJS, even though webkit-only there will be API changes (like that gamepad one).

DOMWindow and other typedefs sound good to me.

**Comment by fponticelli** [comment]
I totally agree with Bruno here. Is not like Haxe is breaking
compatibility, it is the native API that is changing.

Il giorno mer 11 mar 2015 alle ore 14:42 Bruno Garcia <
notifications@github.com> ha scritto:

**Comment by nadako** [comment]
+1

**Comment by ncannasse** [comment]
Yes, when there's such change it's perfectly fine to adapt to newest. But it seems the API upgrade have also removed a lot of webkit specific things that people might be relying on, for instance to provide better user experience on Chrome.

For instance what's your proposal for onmousewheel ? should not it be listed ? it seems only Firefox does not supports it, others (IE, Webkit, Opera) does https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel

**Comment by sledorze** [comment]
Also getPropertyCSSValue is now deprecated for chromium..
cf https://code.google.com/p/chromium/issues/detail?id=331608

**Comment by Justinfront** [comment]
I was wondering if we could do this with a haxelib then users could install older or newer versions or branches using local or dev.

**Comment by aduros** [comment]
I added those typedefs for convenience (eg: DOMWindow to Window) with a @:deprecated.

For onmousewheel, wouldn't it be easy to switch to wheel? Browser support is better than mousewheel: https://developer.mozilla.org/en-US/docs/Web/Events/wheel

**Comment by ncannasse** [comment]
Ok let's way for RC feedback to see if additional changes are required.
