### ISSUE TITLE
Compile error with self types

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#4012]
is this supposed to work?

```haxe
class Foo<TSelf:Foo<TSelf>> {
    public function doIt ():TSelf {
        return this;
    }
}
```

it fails to compile with `Foo<Foo.TSelf> should be Foo.TSelf`

**Comment by frabbit** [comment]
@ncannasse @Simn

**Comment by back2dos** [comment]
It is not, as the compiler says: the type of `this` is `Foo<Foo.TSelf>`, which is not `Foo.TSelf`.

Does this make it clearer?

```
class Foo<TSelf:Foo<TSelf>> {
    public function doItToThat(that:TSelf):TSelf {
        return that;//works of course
    }
    public function doItToThatToo(that:Foo<TSelf>):TSelf {
        return that;//doesn't work, but type wise it's what you want to do, given that `this` has the same type as `that`
    }
}
```

So sadly, you'll need a cast.

**Comment by back2dos** [comment]
Generally speaking, it is just not a self type. Let's assume it compiled for a moment. Then consider this:

```
class FooA extends Foo<FooA> {}
class FooB extends Foo<FooA> {}
```

This is valid, because `FooA` meets the constraint. But calling `FooB.doIt` will result in `FooA`, even though it returns `this` which is `FooB`.

A self type has a very specific meaning and type parameters fail to capture it. They make it easier to emulate, as long as *you* manually respect the self constraint. Unfortunately the compiler has no way of understanding that.

**Comment by Simn** [comment]
I find @back2dos argument quite convincing, so I'll go ahead and close this.
