### ISSUE TITLE
"Module js.html.HtmlElement is loaded with a different case than js.html.HTMLElement"

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#4024]
3.2rc1
with my js app for mush.
Hmmm I may be mistaken but haven seen issues about that...

```Module js.html.HtmlElement is loaded with a different case than js.html.HTMLElement```

I don't have a clue from where does come the offending HtmlElement casing...

@Simn did i miss something?

thanks !

**Comment by Simn** [comment]
It used to be HtmlElement but is now HTMLElement (as it should be). We should typedef this or at least document it.

@aduros

**Comment by delahee** [comment]
a good search replace all over the projects did the trick. since windows will not allow us to have two files names htmlElement.hx, i understand the nuisance so i am ok to close if its too much of a pita.

**Comment by Simn** [comment]
If this is a special case we can just hack a deprecated typedef into the new file.

**Comment by ncannasse** [comment]
I think documenting the change is good enough, HtmlElement should be quite rarely used given it represents the `<html>` root document, not sure why you're using it @delahee

**Comment by ncannasse** [comment]
(reopened, wrong button)

**Comment by delahee** [comment]
Dunno the details but the twinoid code base made use of it (offsetHeight,scrollHeight)

**Comment by aduros** [comment]
@delahee Would a `typedef HtmlElement = HTMLElement` at the bottom of HTMLElement.hx fix that on Windows?

**Comment by delahee** [comment]
I don t know, mentionning the renaming to the migration guide should
suffice imvho.

**Comment by ncannasse** [comment]
@aduros I would not do that, since it's Windows specific

**Comment by Justinfront** [comment]
Seems a shame that this change breaks Lime and openfl for the js target on my mac, I would expect hxcpp openfl to be broken but not js target.
Could we consider moving to treating Openfl/NME, SnowKit, Flambe as haxe targets rather than independant libraries this will increase the users and machines where new versions of haxe will be tried and not leave earlier adoptors with as many broken projects.

**Comment by ncannasse** [comment]
That seems indeed to affect a lot of code. Shall we revert this change and adopt a different strategy with renaming as Juraj suggested ?

```
An alternative I have proposed was to call said supertype BaseElement and leave the old names as they were, but haven't gotten any feedback on that. I guess it's too later for that to happen now, but you never know.```

What do you think @aduros ?

**Comment by Simn** [comment]
Can we please stick to the extern names and not invent new type names? I acknowledge that this is a bit annoying, but I don't consider it to be a major deal breaker. The fix comes down to replacing all occurences of HtmlElement with HTMLElement which is really not too much to ask. All we have to do is document it properly.

**Comment by nadako** [comment]
+1

**Comment by Simn** [comment]
I have added a specialized error for this which now says "HtmlElement is now HTMLElement, please replace all occurrences accordingly". Yes the error position might be wrong, but this is all the work I'm willing to put into this particular issue.

I'm sure there will be some complaining, but I can take the hit and it will die down very soon.

**Comment by aduros** [comment]
Thanks Simn, that should help a lot. The error message is incorrect though. `Element` was renamed `HTMLElement`, and `HtmlElement` is now `HTMLHtmlElement`.

Yes, these names are dumb, but we should stick to the official names.

**Comment by aduros** [comment]
Some more context here:

In Haxe 3.1, `js.html.Element` was a unified version of [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) and [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement).
Our Element contained functionality from both Element and HTMLElement.

In Haxe 3.2, we match the DOM spec more closely. There's a `js.html.HTMLElement` now, and you probably want to use it instead of Element (unless you're working with SVG or something). That required renaming `js.html.HtmlElement` to [HTMLHtmlElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHtmlElement).

Haxe 3.1:
* Element
* HtmlElement

Haxe 3.2:
* Element
* HTMLElement
* HTMLHtmlElement

To ease this transition, maybe we should move all fields from the new HTMLElement up into the Element parent class. This isn't 100% correct from a spec standpoint... but it'll fix a lot of these errors and make the API easier to work with (there are DOM methods that return Element that are effectively HTMLElements unless you're working with SVG).

**Comment by Simn** [comment]
I see, so I've been misunderstanding the problem too.

So the real solution for users is to rename HtmlElement to HTMLHtmlElement? Though this makes me wonder if users actually mean the `<html>` thing or if they just used it because they thought it was HTMLElement.

**Comment by delahee** [comment]
In our case the right transition was it was Element->HtmlElement.

The migration guide will help :)

**Comment by ncannasse** [comment]
My problem is that if 99.9% of the time you're using HtmlElement, why not naming it Element (which is shorter AND backward compatible). I'm pretty sure we have a LOT of code out there that uses Element, and I don't see really what it brings to break up such thing.

My bad for reacting that late, I didn't understand that Element was concerned, I thought it was only about the `<HTML>` element.

**Comment by back2dos** [comment]
First of all, we use namespaces where the spec uses prefixes. `HTMLAnchorElement` is called `AnchorElement` in the standard lib. Therefore `HTMLHtmlElement` should remain `HtmlElement` and `HTMLElement` should remain `Element`. This has nothing to do with "inventing names". It's about a consistent, straight forward, bijective mapping that we had, that is now being thrown out of the window without any good reason. It is in fact the *new* naming that is inconsistent with the official names.

Second of all, we failed to be bijective by putting some other stuff that doesn't have an `HTML` prefix into the same package. That's something we can't change right now, so we'll have to live with that.

Because of the above failure, we're left with a singularity, namely with the native `Element` type, that would conflict with or name for `HTMLElement` if we mapped it like everything else. We need it, because we want `SVGSVGElement` (yeas that's what it's actually called) to be declared properly and that's fair enough. 
We can "invent" *one* name for it and move along, or we can mess up a whole lot of code. Given those two options, I very much prefer the first one.

So to be clear: `HTMLHtmlElement` and `HTMLElement` should get back their old names, because we should be consistent and because we should be stable. Find a solution for the native `Element`. I suggest `js.html.DomElement`/ `js.dom.Element` / `js.html.dom.Element`, because that *actually communicates* that we're having a mere DOM element.

This is not a non-issue. The old `Element` was very common place. A search-and-replace in files is not a viable option for users of 3rd party libraries, nor is it for their maintainers.

**Comment by Simn** [comment]
I lost the plot. I thought the native name was HTMLElement so it made sense to me to stick to it. If it's HtmlElement then why did we rename this to HTMLElement in the first place?

**Comment by frabbit** [comment]
i have to agree with juraj, we should stick to our html package instead of adding the prefix to all classes. It's a good idea to add HTMLElement as js.dom.Element or something like that.

**Comment by frabbit** [comment]
we could add js.svg.* and deprecate SVG classes inside of js.html

**Comment by Simn** [comment]
I'm taking down the release files. You guys can give me a call once we're actually ready to make a release.

**Comment by back2dos** [comment]
@frabbit I think the svg change is impractical. Right now we need a workable solution. For me, the easiest way to do that would be to go back to the old naming and an find a decent name for the native `Element` interface. As for the rest, that's something to do for Haxe 4 or whatever.

@Simn You are right in assuming that `HTMLElement` is the native name for what we have called `js.html.Element` in the past. Similarly `HTMLHtmlElement ` is the native name for what we have called `js.html.HtmlElement` in the past. Now, if I tell you that `HTMLAnchorElement` is the name for what we have been and still are calling `js.html.AnchorElement`, which also goes for `HTMLTableElement` becoming `js.html.TableElement` and in fact almost anything that ends with "Element" in that package, what would you say the name of `HTMLElement` and `HTMLHtmlElement` should be in the future? Why should we introduce an exception to the rule, particularly if it introduces quite severe incompatibility?

**Comment by frabbit** [comment]
@back2dos yes, true it's not a good idea to change this now. When everything we need is a new name for a DomElement, i would suggest js.html.DomElement or js.html.DOMElement (i don't like it, but it's more conform to current naming), that's doesn't require a new package with only one class. For 4.0 we can talk about a better api.

**Comment by frabbit** [comment]
@aduros @ncannasse @back2dos @simn can we agree on js.html.DOMElement for now and leave the other types as they were before?

**Comment by back2dos** [comment]
I agree ;)

**Comment by Justinfront** [comment]
Sorry for not following the conversation, will the new proposed changes still break typical openfl html5 project eg:

$ haxe build.hxml
/usr/lib/haxeLibrary/lime/2,1,3/lime/app/Config.hx:11: characters 12-44 : Module js.html.HtmlElement does not define type HtmlElement
Error: Command failed with error 1

It looks like Joshua has already created an html fix for 3.2 but it would be ideal if it did not need one then more code would be compatible over the switch.

https://github.com/openfl/lime/commit/c846cb397c69b828016c0bde544d63c663a26da2

**Comment by ncannasse** [comment]
I'm fine with both js.html.DOMElement and js.dom.Element

**Comment by ncannasse** [comment]
as long as we keep js.html.Element being the default "element in the html page". HtmlElement should be the `<html>` element

**Comment by back2dos** [comment]
That's what it was before:
https://github.com/HaxeFoundation/haxe/blob/7be30670b2f1f9b6082499c8fb9e23c0a6df6c28/std/js/html/HtmlElement.hx#L31

**Comment by aduros** [comment]
Ok, Element is now DOMElement, HTMLElement is now back to Element, and HTMLHtmlElement is now back to HtmlElement. I also moved more members from Element up into DOMElement, to prevent breakage where places that previously returned an Element now return a DOMElement.

The 3.2 transition should be completely seamless now, sorry for the inconvenience. Haxepocalypse averted!

**Comment by underscorediscovery** [comment]
Do we know when a new RC is coming yet?

Currently this breaks 3.1.3 > rc.1 > git compatibility. 

Many users (thanks to them being so enthusiastic to help test, as we hoped/asked) are on rc.1. 
User facing code accounts for 3.1.3 and rc.1 with `#if haxe_ver`, but git is matching `haxe_ver 3.2` - So it gets the wrong condition, and gets the reverted changes (rc.1 code).

**Comment by Simn** [comment]
That's the reason I took down the RC. I'll work on releasing it again today.

**Comment by nadako** [comment]
@aduros is this doc up to date - https://github.com/HaxeFoundation/html-externs#haxe-32-api-migration? because our `Breaking changes` wiki page mentioned in release notes links to it, so it's important not to confuse people.

**Comment by aduros** [comment]
It should be up to date now.

**Comment by underscorediscovery** [comment]
Thanks for the new RC @Simn, no new issues as yet
