### ISSUE TITLE
Context.resolvePath return the wrong path

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4031]
The file in `-lib` always shadows the file in `-cp`.
Minimal example:

src/Test.hx

``` haxe
import haxe.macro.*;

class Test {
    macro static public function test():Expr {
        var curFile = Context.getPosInfos(Context.currentPos()).file;
        trace(curFile); //"src/Test.hx"
        var resFile = Context.resolvePath(curFile);
        trace(resFile); //"/Users/andy/Documents/workspace/TestHaxe/test/src/Test.hx"
        trace(sys.io.File.getContent(resFile)); //"wrong"
        return macro {};
    }
    static function main():Void {
        test();
    }
}
```

test/src/Test.hx

```
wrong
```

Run:

```
haxelib dev test test
haxe -main Test -lib test -cp src --interp
```

**Comment by Simn** [comment]
Is this a regression?

**Comment by andyli** [comment]
Nop. Both 3.1.3 and 3.2.0-rc1 give the same (wrong) result.

**Comment by Simn** [comment]
I remember Nicolas going out of his way to support correct order between -lib and -cp, so I'm surprised to see this isn't working. I'm not sure I want to touch this for Haxe 3 as it might cause really strange errors.

**Comment by Simn** [comment]
Interestingly, this still reproduces. The class path order is correct: `Classpath: src/;C:\Users\simn\Desktop\Issue4031\test\;;C:\GitHub\haxe\extraLibs/;C:\GitHub\haxe\std/eval/_std/;C:\GitHub\haxe\std/`.

**Comment by Simn** [comment]
Oh you know what, this actually isn't a valid issue. You're looking up `src/Test.hx`, which is not part of the `src` class path as it would be `src/src/Test.hx`. That's why it is picked up when attempting the `test/src/Test.hx` lookup. If you change the lookup to `Test.hx` (and move `test/src/Test.hx` to `test/Test.hx`) it picks up `src/Test.hx` as expected.

Sorry it took me 4 years to realize that!
