### ISSUE TITLE
Breaking change when switching on Xml.nodeType (3.2.0-rc2)

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxe#4084]
Previously this code worked (Haxe 3.1.3):

        switch x.nodeType {
            case Xml.ProcessingInstruction:
            case Xml.DocType:
            case Xml.Document:
            case Xml.CData:
            case Xml.PCData:
            case Xml.Element:
            case Xml.Comment:
        }

Now you must use this code (Haxe 3.2.0-rc2):

        switch x.nodeType {
            case ProcessingInstruction:
            case DocType:
            case Document:
            case CData:
            case PCData:
            case Element:
            case Comment:
        }

I'm not stressed if this is a breaking change as part of the otherwise great Xml fixes.  It would be good to include it in this list though: https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-3.2.0

See http://try.haxe.org/#9a95b

**Comment by jasononeil** [comment]
I forgot to include the error message:

> Unmatched patterns: Document | ProcessingInstruction | DocType | Comment | CData | PCData | Element

**Comment by Simn** [comment]
Finally a real issue. \o/ Let's hope I break something with the fix.

**Comment by jasononeil** [comment]
I've got a few more, once I can reproduce ;)

**Comment by Simn** [comment]
It turns out this was actually failing for a good reason, if with the wrong error message. All these static fields on `Xml` are not inline/read-only, so inlining their expression is not sound. In fact, this is also broken for the plain identifier case (`case Element:`) which inlines the expression value.

**Comment by Simn** [comment]
Actually `case Element:` is sound: Here top-down inference identifies it as a constructor of `XmlType`, which is _not_ the same as `Xml.Element`. When I fixed this issue I assumed that the two were equivalent when in fact they are not.

Long story short I think `case Xml.Element:` should indeed fail because it doesn't/shouldn't resolve to a constant value.

**Comment by Simn** [comment]
Stupid revert commits closing issues. Anyway, this is not an issue an working as expected, so it can remain closed.

**Comment by jasononeil** [comment]
> Let's hope I break something with the fix.

You got what you hoped for!

Thanks for the explanation, it makes sense.  On a different note, I'm really surprised that those Xml static fields are not inlined / constant.  Changing them would cause all kinds of Xml chaos.
