### ISSUE TITLE
Proposal: Haxelib shim

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4093]
# Haxelib Shim

## Current Problems

Many users experience problems running `haxelib selfupdate`

On a Mac or Linux system, "/usr/lib/haxe/haxelib" may require elevated system privileges, and may be locked.

On Windows, running "haxe update.hxml" afterward feels messy.

Experienced developers I know do not run `haxelib selfupdate` at all -- they have never heard of it.

If we make vital improvements to the Haxe package manager, we need a mechanism that allows users to receive the update.

## Improvements to Development Process

There is no simple way to test changes to the Haxelib client, currently. If you could `haxelib dev haxelib_client path/to/dev/client` it could improve the workflow for improving haxelib.

If more developers can contribute to haxelib, it may help prevent critical issues we have had.

## Proposal

I propose that we create a shim that is able to detect updated versions of the haxelib client, and prefer those if they are available. However, I propose that it also includes a full compiled version of the haxelib, itself, which allows it run as normal if an update is not found.

Haxe always comes with a haxelib binary. Alone, the shim functions identically.

If a user would run `haxelib upgrade` and find a new `haxelib_client` library, the shim would prefer this version. The user could also `haxelib set haxelib_client` to choose a version, they could `haxelib dev haxelib_client` to work with a development version, or do none of these to use the original.

## Prototype

I have built a prototype here:

https://github.com/jgranick/haxelib-shim/blob/master/Main.hx
https://github.com/jgranick/haxelib-shim/blob/master/build.hxml

It is currently working perfectly on my system. I can `set`, `dev`, or `remove` each version and it responds properly.

I would be happy to discuss this further.

The risk is very low, and something like this would forever improve the use of haxelib.

**Comment by jgranick** [comment]
The shim prefers a `haxelib.n` over `haxe --run` because it performs much faster on my system. However it supports both methods, so a haxelib client release without a Neko binary can still be used.

**Comment by larsiusprime** [comment]
This sounds like exactly what we need. Haxelib problems have been the major sore spot in haxe development for me. What do we need to move forward with this?

**Comment by Simn** [comment]
- dictionary to look up what "shim" means - check
- issue report in the correct repository - TBD

**Comment by jgranick** [comment]
Whether to include this as the "haxelib" binary in the Haxe releases, or not, is a Haxe decision I believe.

**Comment by jgranick** [comment]
This seems a bit hostile, but I've opened a duplicate here: https://github.com/HaxeFoundation/haxelib/issues/193

**Comment by hughsando** [comment]
I would certainly like to see haxelib distributed as a binary.  The concept of just changing the haxelib_client code and everything working is nice, but problematic due bootstrapping and possibly efficiency reasons.
If haxeib was a binary on its own release-cycle, you could update it many times a year.  This alone would solve many issues.
I think you could also rename it to "haxe", and move haxe.exe/std to the haxelib area.  So you could do:
haxe set haxe 3.2.0.rc2
and you would be testing the RC with no risk
haxe [anything but set/info/path etc] 
would locate the haxe folder and pass on the args

For linux, installing would be a matter of downloading haxe (ie, haxelib) and by running it, i would download + install the latest haxe - maybe neko too.

This would give you about 10x more testing on the release candidates since you can easily swich back for production.
