### ISSUE TITLE
createInstance works in a different way than instantiating a class normally

### ISSUE THREAD

**Issue by mlopes** [HaxeFoundation/haxe#4135]
While creating class instances from a string using Type.createInstance, I noticed that it behaves differently from creating a class in the "normal" way.
I'm instantiating a class from the same package as the current one, when creating it normally, I don't need to import the module, but with create instance I do. It also doesn't work with create instance if I import using a wildcard.
Additionally, if the class is missing the constructor, createInstance is still able to create a new instance, but creating it the normal way fails with a "does not have a constructor" error message.

Cheers,
Marco Lopes

**Comment by Simn** [comment]
I'm not very good at reading code stories, but what you describe sounds like the expected behavior. The import is probably related to the class not being compiled at all if it's not referenced in traceable code. The behavior when these functions are used with classes that do not have a constructor is unspecified.

**Comment by mlopes** [comment]
That makes sense. About the constructor thing I guess I just expected it to behave the same way as a normal instantiation, but truth is, it didn't affected my code in any way, and I just found it out while trying to figure why I needed the explicit import.

Thanks for the reply.
