### ISSUE TITLE
Issue with var keyword allows declaring multiple variables, separated by comma

### ISSUE THREAD

**Issue by as3boyan** [HaxeFoundation/haxe#4175]
```haxe
class Test {
    //var a,b:Int;
    //var d,e = 2;
    //var f:Int,g:Int;
    static function main() {
        trace("Haxe is great!");
    }
}
```

None of commented lines work in try.haxe.org(Haxe version: 3.2.0 RC2)
http://try.haxe.org/#187A4

**Comment by ncannasse** [comment]
Only single variable declaration are allowed in type definition (class, typedef, etc).

**Comment by as3boyan** [comment]
So only local variables can have multiple var declarations?

**Comment by ncannasse** [comment]
yes

**Comment by Justinfront** [comment]
http://try.haxe.org/#A354c 
Does documentation explain the logic behind this behaviour - only for local variables?

**Comment by nadako** [comment]
Why does it have to? Field definition is a different syntax. Fields require explicit type, have restrictions on init expression, can be private/public/inline, etc. This has nothing to do with local var syntax.

**Comment by Justinfront** [comment]
If you argue that Field is so different from local variables, then surely they should not share the same "var" keyword, but they are purposely treated similar, and for good reasons so your argument seems more about not knowing the best implementation.

Commonly a haxer highlights a local variable and drags them to the class properties, but when I try this I get an error.

http://try.haxe.org/#20245

The error message does not explain this only works for local varibles so as3boyan is correct in highlighting this issue as the error message should include something along the lines of...

"you can only use comma separation for local variables not for class fields"

I am still not really sure why this sugar was added since it seems a bit unneeded and inconsistant?  
But anyway this all pretty minor so I will shut up now :)

**Comment by as3boyan** [comment]
@Justinfront That's fun. I didn't thought that we can use it this way)
