### ISSUE TITLE
[cpp] #include <hx/HxcppMain.h

### ISSUE THREAD

**Issue by adamretter** [HaxeFoundation/haxe#4199]
I am trying to create a cross-platform API and library, and therefore I do not require my library to be executable, i.e. no `main`. Compilation of this library to Java works, I use the command line:

```bash
$ haxe -cp src -java java_out example.expath.file.FileModule
```

I also want to produce a compilation to C++, using the equivalent command line for the cpp backend:

```bash
$ haxe -cp src -cpp cpp_out example.expath.file.FileModule
```

I get the following compilation error:

```make
g++ -Iinclude -DHX_DECLARE_MAIN -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/usr/lib/haxelib/hxcpp/3,2,81/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -x c++ -frtti -Wno-invalid-offsetof ./src/__main__.cpp -oobj/darwin64/501f6158___main__.o
Error: ./src/__main__.cpp:10:25: error: expected "FILENAME" or <FILENAME>
#include <hx/HxcppMain.h
                        ^
1 error generated.
Error: Build failed
```

Is it possible to generate a dynamically linked library using the CPP backend? I rather expected this to be the default if I did not pass `-main` to the haxe compiler command.

**Comment by hughsando** [comment]
The issue with the include has been fixed.
Usually, I would think the best way to make a dll would be to make a .lib file first, and then link this against a small, well-defined API, since a full export of all the haxe symbols would at least require the user of this dll to include a synchnonised version of hxcpp.  The android target creates a dll with just one symbol exported - something like this may be possible, but maybe not useful.
You can generate a .lib file with the "-D static_link" define, whether or not you have "-main" specified.
As to whether no main should imply "-D static_link" or some kind of dll_link, is something I will think about.

**Comment by adamretter** [comment]
@hughsando How do I get access to the fix?

I am not a C++ developer in any sense, but I am trying to create a small module that can be used from either Java or C++. I do not really also want to maintain anything additional outside of Haxe, i.e. another well-defined-API. Is it not possible to create a dynamic library + include files that I can distribute to C++ developers in Haxe?

**Comment by Simn** [comment]
Check out builds.haxe.org for nightly builds.

**Comment by adamretter** [comment]
@Simn Thanks. And how about my goal of generating a dynamic library and include files for C++ developers?
