### ISSUE TITLE
[java] Imposssible to create private member fields

### ISSUE THREAD

**Issue by adamretter** [HaxeFoundation/haxe#4208]
No matter what modifiers you place on the vars in a class in Haxe, in the generated Java class they will always be declared public.

```haxe
class MyClass {
  private var thing: String;
  public new(thing) {
    this.thing = thing;
  }
}
```

This will generate a Java Class like (simplified):

```java
class MyClass {
  public String thing;
  public MyClass(String thing) {
    this.thing = thing;
  }
}
```

**Comment by nadako** [comment]
This is intentional and is required for inlining, reflection and other stuff. However, you can add `@:protected` metadata for a field to make it `protected` in the generated Java code. However be prepared for access violation errors from the Java compiler.

**Comment by adamretter** [comment]
@nadako Can you give me some further information? What inlining? I am not interested in any intermediate form, just the finally produced java code, even if I add `@:nativeGen` to the Haxe class to remove reflection, I still end up with public members. This still doesn't sound right to me... probably because I don't understand!

**Comment by nadako** [comment]
Consider this example:

```haxe
package packA;

class Some {
    var value:Int; // private field

    public function new() {}

    public inline function setValue(v:Int) { // note the inline
        value = v;
    }
}
```

and the following usage cases:

```haxe
class Main {
    static var some = new packA.Some();

    static function main() {
        some.setValue(10);
    }

    @:access(packA.Some.value)
    static function other() {
        Sys.println(some.value);
    }

    static function more() {
        Sys.println(@:privateAccess some.value);
    }
}
```

it will generate java as follows (stripped):

```java
public class Main {
	public static packA.Some some;
	
	public static void main() {
		Main.some.value = 10; // inlined setValue
	}
	
	public static void other() {
		java.lang.System.out.println(Main.some.value);
	}
	
	public static void more() {
		java.lang.System.out.println(Main.some.value);
	}
}
```

This would not be possible if `Some.value` field was generated as private, because Java compiler would then complain. You can try adding `@:protected` to the `Some.value` field and see it failing for yourself.

Why are you so interested in the generated java code? Are you trying to provide API for use from native java code? Then consider using `@:protected`, but be aware of cases like in examples above.

**Comment by adamretter** [comment]
Okay two things, first the `@access` annotations seem rather unpleasant, it appears they exist to work around an existing access model. Secondly, `protected` is not the same as `private`.

If keeping the variables all public in Java is just for the purpose of `inline` and relaxed access controls, then it would seem to me that this is the exception rather than standard case. As such I would think that the default should be to generate the Java code in a semantically correct way, however if the use of `inlining` or `@:access` is detected, then you could relax the visibility of member variables to public to accommodate this. No?

**Comment by nadako** [comment]
`@:access` and `@:allow` exist to provide much more fine-grained access control than classic public/private/friend does (see http://haxe.org/manual/lf-access-control.html).

Yeah, I know that `protected` is not the same as `private`, but from the API point of view it should do the job, since you hide a field/method from public API.

Properly detecting fields to be made `public` instead of `protected` (haxe's `private` is actually more like  `protected`) involves complex analyzing code and extra state in the compiler, it also raises more questions and unexpected behaviour (e.g. `why some of my fields are generated private and some are public?`). And the benefits are not really worth the trouble.

The generated java code is quite efficient and readable, and it implements all haxe features, so why do you care so much about it being "sematically correct java code"? As I already said before, one case where one would REALLY need to generate non-public fields and prevent generation of reflection helpers is providing an API for use from Java. But `@:protected` and `@:nativeGen` should be sufficient for that. If not, please provide concrete examples and we'll think about how to improve the interop.

**Comment by nadako** [comment]
Summon @waneck for more comments.

**Comment by adamretter** [comment]
@nadako So yeah my goal is to generate an API for use from both Java and C++. My fear is that with protected, anyone can access that through either subclassing or placing a class in the same package.

**Comment by nadako** [comment]
One pragmatic option is to make a @:nativeGen interface for outer world and make your haxe class implement it.

As for generating `private` from haxe, I'll leave these kinds of decisions to @waneck.

**Comment by waneck** [comment]
Haxe doesn't have the concept of private like Java or C#. I can't see how
we could make a private variable without the compiler support.

>
