### ISSUE TITLE
problems with clean mac install and HAXE/OPENFL

### ISSUE THREAD

**Issue by lewislepton** [HaxeFoundation/haxe#4214]
this is a problem i have ran into after a clean install of my computer.

i have followed exactly everything and have what i need installed. i had a flixel install before i wipe the computer, but am choosing to just use openfl instead.
it had worked before i had done the clean install.

but on running, both in terminal and in sublime [using the HAXE build system], am running into trouble and dont know what they are or how to fix. ive followed everything on the sites given. but the same thing
here are some screenshot to show
im also using HAXE 3.2.0 and have tried 3.2.0r2 but both do not work

thanks

![screen shot 2015-05-13 at 16 36 06](https://cloud.githubusercontent.com/assets/11299322/7614570/8e1fe9b2-f98f-11e4-9253-7658ed8487ef.png)

![screen shot 2015-05-13 at 16 46 01](https://cloud.githubusercontent.com/assets/11299322/7614575/9882da7c-f98f-11e4-8773-e0e470d1a35f.png)

**Comment by Simn** [comment]
You may want to report this to openfl/lime. I don't think we can help you here unless you can suggest that the issue at hand is caused by Haxe itself.

"Invalid field access" usually means that it's doing `null.field`. Check the referenced code to see if you can spot why whatever is to the left of `.length` could be a null value.

**Comment by lewislepton** [comment]
cool thanks
