### ISSUE TITLE
Type building requests VarAccess

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxe#4226]
I'm trying to follow the manual verbatim here: http://haxe.org/manual/macro-type-building.html

When I do, I get a compilation error:

    project/macro/TypeBuilder.hx:82: characters 41-95 : { pos : haxe.macro.Position, expr : haxe.macro.ExprDef } should be haxe.macro.VarAccess
    project/macro/TypeBuilder.hx:82: characters 41-95 : For function argument 'write'

Originally, I thought this was a documentation bug.  But then I traced an existing class field and copy-pasted it into the type building code (modifying it to be formatted correctly etc.) and I still get the same error.

The relevant "new" code (that produces the same error) looks like:

                    var field = {
                        kind: FVar(null, {expr: EConst(CInt('13')), pos:  Context.currentPos()}),
                        meta: [],
                        name: 'someNumber',
                        doc: null,
                        pos: Context.currentPos(),
                        access: [AInline,AStatic]
                    };
                    newFields.push(field);

**Comment by Simn** [comment]
The problem is that `FVar` is overloaded: It is a constructor for both Expr.FieldType and Type.FieldKind. You probably have `import haxe.macro.Type` after `import haxe.macro.Expr` which causes it to have priority (see http://haxe.org/manual/type-system-resolution-order.html)

You can fix this by qualifying it as `FieldType.FVar`. Another option is to type-hint `var field:Field` in which case top-down inference (http://haxe.org/manual/type-system-top-down-inference.html) can tell what you want.

While this is a bit unfortunate, it is not exactly a bug. We may want to rename this in the future but we can't do that without breaking code.

**Comment by explorigin** [comment]
Aside from renaming, it seems like it wouldn't be much effort to say...if I have an error on an overloaded type, display a message that this type is overloaded and the error may be caused by the overload.

**Comment by Simn** [comment]
The compiler doesn't even know that there are other possible candidates because it just picks the first one it finds. Thus "it wouldn't be much effort" really does not hold and even if it did this would potentially lead to annoying messages.
