### ISSUE TITLE
Regression: constraint check failure with @:multiType abstract

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#4237]
```haxe
package;

class Main
{
	static function main()
	{
		var signal = new AbstractSignal();
		signal = DestroyUtil.destroy(signal);
	}
}

@:multiType
abstract AbstractSignal(Signal)
{
	public function new();
	
	@:to 
	private static inline function toSignal(signal:Signal):Signal 
	{
		return new Signal();
	}
}

class Signal
{
	public function new() {}
	public function destroy():Void {}
}

class DestroyUtil
{
	public static function destroy<T:Signal>(destroyable:T):T
	{
		if (destroyable != null)
			destroyable.destroy();
		return null;
	}
}
```

Produces the following error (tested with 3.2.0 and latest dev):

```
Main.hx:8: characters 11-30 : Constraint check failure for destroy.T
Main.hx:8: characters 11-30 : AbstractSignal should be Signal
```

It compiles fine in 3.1.3. Explicitly typing `signal` as `Signal` also makes it compile, but I don't think that should be necessary?

This happens with HaxeFlixel's `FixSignal`.

**Comment by Simn** [comment]
I think this should fail. Type parameter constraints are not checked against expressions but are delayed and then checked against types. This means that implicit field-casts cannot be applied because there's nowhere to put the cast expression.

3.1.3 had some issues and inconsistencies with abstract unification and I suspect this was one of them. I'll leave the issue open for a bit though and think about it again.

**Comment by gamedevsam** [comment]
Do you have a suggestion on how to fix this issue on our end?

**Comment by Simn** [comment]
Can you type `destroyable` as `Signal`?
