### ISSUE TITLE
"@:extern inline" causes run-time error if method can't be inlined, instead of compile time error

### ISSUE THREAD

**Issue by grisevg** [HaxeFoundation/haxe#4277]
Haxe: v3.2.0
Target: JS, Analyzer ON, DCE - FULL
Also reproduced on nightly: `haxe_2015-06-02_development_ff9462c` for windows
http://try.haxe.org/#bF98A
```haxe
class Test {
    static function main() {
        var lo = fancyInlineMethod;
        lo();
    }
    
    @:extern private inline static function fancyInlineMethod(y:Int = 3):Int
    {
        var x = 5;
        return x + (x += x) - y;
	}
}
```
Current behaviour: run-time error is thrown when code tries to take reference to extern-inlined method.
Expected behaviour: compiler should throw compile-time error if code takes reference to extern-inlined method.

**Comment by Simn** [comment]
This is a bit weird. Usually we create an extra class which hosts the implementation of static extern inline methods. This works nicely for `extern class` but with `@:extern` fields we currently do not take the metadata off the field which makes it entirely pointless. The weird part is that if we support this, we would basically ignore the `@:extern` and just move the implementation to a new class.

I agree that in this case we should give an error because clearly the author does not want the function to be part of the output in any way.

**Comment by grisevg** [comment]
Thank you
