### ISSUE TITLE
Rewrite PHP target

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4290]
The current PHP target is difficult to maintain and targets an old version of PHP. We want to write a new generator which takes advantage of some newer PHP features

----------

The current generator is still going to be available via some -D flag.

**Comment by back2dos** [comment]
![I don't always use haxe/php, but when I do, it's to run code on some lousy web space](http://cdn.meme.am/instances2/500x/115936.jpg)

For me the whole point of having a PHP backend is to be able to run "anywhere". I can think of only two reasons to use haxe/php:

1. To integrate with an existing legacy code base (in which case just upgrading the PHP version is probably not an option)
2. To run in an environment where you don't have the privileges to set up mod_neko, in which case you also have no control over the PHP version

So having a haxe/php backend that only runs on modern PHP environments seems to me to defeat the whole purpose of having this in the first place.

I assume what you want is to not have to maintain the current php backend and I'm hesitant to believe that just adding another less portable backend will give you that.

Let's not forget how much Haxe has evolved since PHP was first released. I'd like to think that with the help of abstracts (implicit casts and operator overloading (for example we can define `+` right on `Dynamic` to get consistent behavior)), inlining and all the other goodies the analyzer gives us, we can solve a lot of the issues in the Haxe code itself. We might be able to cook up something with `String` being an abstract, that has an implicit cast to `StringObject` when it needs to be unified with `{}` or `Dynamic`, thus having the type system do the boxing for us etc. etc.

I think the worst part that needs to be done by the generator itself is the convoluted function handling, but since this has to be done in any backend where the target semantics don't support it out of the box, I think it's fair enough. I'm hereby volunteering to lend assistance with this, to the best of my abilities (I don't see myself writing the generator itself, but I'd like to think that I have solid PHP and Haxe knowledge that might be of value).

**Comment by ncannasse** [comment]
@Simn could you precise which PHP version is required now and which would be required by the new backend as you imagine it ?

**Comment by Simn** [comment]
We want to use closures and namespaces which I think is 5.3? I'll let @mockey confirm that though.

Also I don't really want to discuss whether or not to do it because I don't see any other option if we want to have a maintainable target.

**Comment by mockey** [comment]
Closures and namespaces are PHP 5.3, yes. `$this` can be used in closures only from 5.4 on. Not sure if that's really needed, though.
Also note that 5.3 was released 2009 and is not maintained anymore. Oldest maintained version is currently 5.4. Running a webserver with PHP 5.2 nowadays (even a lous one) might not be such a good idea...

**Comment by RealyUniqueName** [comment]
Just want to add  to the statement that php target is not only useful on "lousy web server"  :)

E.g. in my company almost all backends (even for new projects) are being written in php due to tremendous existing internal codebase which simplifies solving most tasks in development of our games. And right now i'm creating a common part of battle logic of a game which will be compiled into C++, Flash and PHP.

So i hope PHP target will not be treated just as a fallback when Neko is not available :)

I'm not familiar with Ocaml, but i'm not bad with PHP. I can offer my help in this field if you need.

**Comment by Simn** [comment]
I'm giving up on this. I severely underestimated the peculiarities of PHP's "parser" and with my limited PHP knowledge I can't manage to get this right.
