### ISSUE TITLE
Regression with return in switch

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4329]
I have some quite long code which does something of this kind:

```
switch( e ) {
case Mode1:
    tiles = switch( kind ) {
    case A: ...
    ...(more cases)
    default:
         return somethingElse();
    }
...(more modes)
}
```

It used to work well but it now complains in the default case about "Void should be hxd.res.Image". I guess it comes from a change in either pattern matching or EReturn type ? (which should be Dynamic).   Sadly I tried reproducing with a small example but was not able to do so. It seems to be quite a recent issue.

**Comment by Simn** [comment]
Looks like that comes from https://github.com/HaxeFoundation/haxe/commit/afb3b28314a51d0d651e49bc71ac2d43c3fc249d. I'm not sure why though because that change didn't actually add any unification. What's the $type of `somethingElse()`?

**Comment by ncannasse** [comment]
Uhm... let me look, it's a 2300 lines function :) ... ok, the return is Void, which I understand more why there was an error, but it's somehow wrongly reported

**Comment by Simn** [comment]
The question is where the hxd.res.Image return type comes from, and another question is if maybe this should indeed fail. In that case a third question would be why it didn't fail before that change.

I tried finding a case where this happens but couldn't find anything. That function of yours must be doing something quite special. I don't want to revert the change though because it fixed an invalid AST case that is easy to reproduce. We'll have to figure out if this is a real regression or rather a bugfix.

**Comment by ncannasse** [comment]
Ok, looking more into it I found the following reproducible example:
```haxe
class Test  {

	static function foo(x:Int) {
		var r = switch( x ) {
		case 5: 3;
		default:
			return bar();
		}			
	}
	
	static function bar() {
	}

 	static function main() {
	}

}
```

The problem is more about the error message, which reports at line 7 (default) "Void should be Int".

**Comment by Simn** [comment]
Ah, now I see what the problem is!
