### ISSUE TITLE
[hxcpp] Problem with Array<Int> vs. Array<Null<Int>> equality

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4340]
```haxe
class Main {
	static function main() {
		var a:Array<Int> = [1, 2, 3];
		var b:Array<Null<Int>> = a;
		trace(a == b); // false
	}
}
```

**Comment by waneck** [comment]
This should also happen on C# and is very annoying to fix

**Comment by Simn** [comment]
Well on C# it at least fails at native compile-time with `error CS0019: Operator '==' cannot be applied to operands of type 'Array<int>' and 'Array<object>'`.

**Comment by waneck** [comment]
IMHO, this problem should really be tackled at typing level

**Comment by Simn** [comment]
I would like to clarify that this is not about the equality check itself. The following example demonstrates how bad this can be:

```haxe
class Main {
	static function main() {
		var a:Array<Null<Int>> = [];
		add12(a);
		trace(a.length); // 0
	}

	static function add12(a:Array<Int>) {
		a.push(12);
	}
}
```

And yes this occurs on C# as well.

**Comment by ncannasse** [comment]
I think the first step would be maybe to have runtime error for this, in case the user goes through Dynamic it shouldn't make a copy anyway:

```haxe
   var a:Array<Int> = [1, 2, 3];
   var b : Dynamic = a;
   var c:Array<Null<Int>> = a; // runtime error
```

We have started to discuss with @Simn what to do wrt to compile time errors, but we cannot fix the Dynamic case within the compiler

**Comment by Simn** [comment]
I didn't realize the Dynamic route was also problematic, though now that I think about it it makes sense that it would be.

**Comment by Simn** [comment]
@hughsando: What is your opinion on having run-time errors for something like this?

**Comment by hughsando** [comment]
I think this is an easy one - it should be a haxe compiler error, since an Int is not a ```Null<Int>```.
```
class A { }
class B extends A {  }

class Test {
   public static function main() {
      // This does not work ...
      //var b = new Array<B>();
      //var a:Array<A> = b;
      // So why does this ...
      var ints = new Array<Int>();
      var nulls:Array< Null<Int> > = ints;

      // Dynamic case works as expected most of the time
      var ints:Array<Int> = haxe.Json.parse("[1,2,3]");
      trace(ints);
      var floats:Array<Float> = haxe.Json.parse("[1,2,3]");
      trace(floats);
      var nulls:Array< Null<Float> > = haxe.Json.parse("[1,2,3]");
      trace(nulls);
   }
}
```

The Dynamic case we have spoken of earlier.  The copy gives the correct result most of the time - throwing a runtime error may cause code that used to work to stop working (eg, unserialize, JSON.parse("[1,2,3]") ).  I have some ideas about the representation of an ```Array<Dynamic>``` that should fix this in the dynamic case for something like unserialize.  But this is not that case, since the ```Array<Int>``` and ```Array< Null<Int> >``` are completely different beasts (even if you go via Dynamic).  I would be more comfortable about throwing an error instead of copying if Array<Dynamic> case was already fixed.

There are lots of bugs like this with strongly typed Arrays - if you want an efficient implementation of ```Array<Int>``` you must not allow ```Array< something the might look a bit like and int >``` to be passed in its place, or you must add a extra level of indirection on all array accesses.  There is absolutely no other way of going using the current syntax.

We could possibly add something like ```ArrayView<Float>``` which uses an extra indirection to allow arrays of "somethings that look like Floats" (eg, and Array of Ints, or an Array Null<Float> ) to be passed.

**Comment by Simn** [comment]
I completely agree that it should be a compile-time error (if we can detect it). That's part of the reason I suggested #4316.

**Comment by hughsando** [comment]
Cool - did not see that.  I use this pattern a lot (not because I want to, but because I don't know of a better way) : ``` var x:Float = nullFloat==null ? 1.0 : nullFloat;```  Obviously I would prefer something like ```var x = nullFloat.withDefault(1.0);``` but the issues of breaking changes etc are obviously tricky ones.
The most fundamental thing for me is that ```A "isA" B``` _Does Not Imply_ ```Array<A> "isA" Array<B>```.
Whether you want to consider ```Int``` "isA" ```Null<Int>``` or the other way around I think is a separate and more controversial issue.

**Comment by Simn** [comment]
I agree, but that already matches our semantics: `Int` isA `Null<Int>` is represented by unification (`unify`) whereas for the parameters we require type equality (`type_eq`). Both cases are much easier approached through TAbstract than TType (which has implied type equality) either way.

**Comment by hughsando** [comment]
Ok, I think I get it.  Int and Null<Int> Unify to Null<int> - but they
should not be equal, so the Arrays should not unify.  They are currently
equal to allow the "operator=" to work in both directions, but abstracts
would be better for this now (if you even want to allow it).  So the other
discussion is really the crux of the matter.

**Comment by ncannasse** [comment]
Reminder : we need a compiler error for the Dynamic case anyway :)
