### ISSUE TITLE
More permissive license

### ISSUE THREAD

**Issue by hughsando** [HaxeFoundation/haxe#4362]
Can we move to a non-gpl license?
I believe that the current license prevents people using haxe in cool ways (eg, embedding) and I feel kind of dirty enforcing obligations on people who want to use my freely contributed code.

**Comment by ncannasse** [comment]
The GPL does allow to the haxe compiler to be used in a bigger application as soon as it's not a derivative work, and changes in the compiler are published. I think that it's also a good way to keep haxe open source in the long term. Do you have any specific example that the current license restricts ?

**Comment by hughsando** [comment]
GPL does not allow linking to the code - only spawning exes, which is not possible on some platforms (mobile, web - not sure if sandbox-windows allows this either).  LGPL allows dlls, which might cover android and maybe web, but not iOS.
So under no circumstances could  someone  make a commercial, locally running  version of "try haxe" for iOS.  Or embed a haxe (not hscript) interpreter in iOS, or ass some super-specific macro handler.
You could maybe use LGPL with static linking exception to achieve the use cases I'm thinking of, and still oblige publishing of changes made to the haxe compiler code.
But this seems more confusing than simply using a more liberal license in the first place.
And this comes back to why choose the GPL?  It will not stop language fragmentation, since if this comes it will almost certainly come from an open-source fork of haxe (there is no more room in this world for another closed-source language, no one would commit to such a language). So all you really achieve is restricting the usefulness of the language to the point where if someone is looking to embed a compiler, it will be another language like lua, which actively encourages this use.  ie, it is defective-by-design.

**Comment by ncannasse** [comment]
The static nature of Haxe makes it a lot less likely to be embedded than Lua for instance. Also, this would require some OCaml hackery to be able to link it to some host program. We could imagine such usages could exist in theory but it seems nobody actually tried it yet. OTOH the GPL allows us to ensure that nobody will take haxe, repackage it and sell it in some other form, or make a non open source fork of it. GPL gives better chances to keep one single open source code base. 

I don't want to enter into a license war here, GPL has it's pro and cons as every license, I recognize both the side of it and I'm still satisfied with the balance it brings.

**Comment by hughsando** [comment]
I do not think that being a better language than lua should preclude it from being embedded.
I also do not think repackaging and selling haxe is a bad thing - a good way to get wider acceptance without needing to do anything ourselves.
And I will say it again about forks - any fragmentation is going to come from an opensource fork, not a close source fork.  GPL does not protect you here.

The very reason I have not tried any ocaml hackery is the GPL, hence this request.  Any way of using the code other than a desktop exe is simply not worth pursuing in the shadow of the GPL.

**Comment by delahee** [comment]
There has always been some closed source Haxe fork. I know at least one of them which lead to non compiler related commercial product. 

So GPL is not really the question since it is very hard to enforce and in the end, it remains a Haxe thing.

@hughsando I like the model of some OSS projects which sub licences their code with different licences for commercial needs, could this fit you or do you have a use case needing the whole haxe stack changing licence ? 

I mean... this is a big move so telling the team where we go with this seems fair, amirite ? (sorry to intrude)

**Comment by hughsando** [comment]
Yes, it is a reasonably big move - but not that new a concept, since a lot
of the code has already transitioned away from GPL.  Haxe is for
developers, and GPL transfers "freedom" from developers (to close-source
their code) to the end-user (to change the application).  Which is nice and
all for end-users, but haxe needs to win the hearts and minds of developers.
I don't think sub-licensing is going to help here - just create impediments
preventing maximum use of code.  I know that I will not be trying the use
haxe in new and unusual ways unless I can do so completely openly.

Perl has (used to have?) it's "Artistic license" which said something like
you can use the code how you like, but must open changes to the "standard
version" - so you can link it to your app, but if you add language features
you must open them.  This sounds like what Nicolas is mainly concerned with
(but not wanting to speak for him...).  This usually is dual-licensed with
GPL to keep it simple for linux die-hards.  This would be acceptable for
the uses I have in mind, and might be a nice compromise.  But it would be
simpler just to go MIT.

(Apache while we are at it ?  Forcing contributors to match the existing
license)

**Comment by back2dos** [comment]
I imagine this might really be quite cool for game engines + editors that would tightly integrate Haxe (and cppia) for scripting. Having to open source your whole product will most likely be unacceptable for most companies.

I think it's backward to say that people won't embed Haxe because it requires some doing. It's a matter of resources. Sure, someone might do it in their free time, but most realistically, it will happen when someone actually pays for it.

As it is, everybody can already fork Haxe, rebrand it and sell it. Sure, the compiler will have to stay open source. The standard lib won't and what not. Also, I don't see your problem Nicolas. The first thing they will probably do is to add short lambdas, after which you won't care much for the project anyway :P

**Comment by Simn** [comment]
This issue is too high-level for me.
