### ISSUE TITLE
Php Reflect.setField with null value field doesn't display stack error.

### ISSUE THREAD

**Issue by alamboley** [HaxeFoundation/haxe#4385]
Small reproducible example:
```haxe
package;
class Main {
	public function new() {

		var struct = {};

		var result = {};

		Reflect.setField(result, null, struct);
	}
	
	public static function main() {
		new Main();
	}
}
```
Output: *Fatal error: Cannot access empty property in /Users/Aymeric/Documents/Workspace/bin/lib/php/Boot.class.php on line 707*.
If I specify `-debug` and `-dce no` same problem.
Works as expected with CPP.

**Comment by nadako** [comment]
Documentation says `If `o` or `field` are null, the result is unspecified.`, so it's quite fair.

**Comment by alamboley** [comment]
Well what does `unspecified`really mean? It depends of the target? This is complicated to debug something which doesn't have any debug stack on a big project. Here I had some chances because thanks to CPP (which doesn't provide an error) I was able to trace and see this null things.
If it was pure PHP project, I'd put trace everywhere to determine the issue line. Really not very convenient.

**Comment by nadako** [comment]
> It depends of the target?
Exactly.

I'm not too familiar with PHP target, however I think that the case with `null` field should be quite rare, so it's not worth adding additional check for every `Reflect.setField` call (performance-wise, because it's most likely inlined to some native `o->{field} = value` expression).

For debugging, you can do that locally though: https://github.com/HaxeFoundation/haxe/blob/development/std/php/_std/Reflect.hx#L32

**Comment by alamboley** [comment]
Yes absolutely, that make sense! Thanks again for your quick answer :+1:

**Comment by jgranick** [comment]
It might be worth the overhead to add a null check to `-debug` builds? Or behind a define?

In C++, a null pointer is a pretty hard crash, though there is -D HXCPP_CHECK_POINTER which (optionally) adds a check to help provide a better error condition for debugging it
