### ISSUE TITLE
Utf8.charCodeAt() causes a lot of GC via array allocation

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFoundation/haxe#4440]
Here:
https://github.com/HaxeFoundation/haxe/blob/development/std/cpp/_std/haxe/Utf8.hx#L61

```Haxe
	public static function charCodeAt( s : String, index : Int ) : Int {
      var array:Array<Int> = untyped __global__.__hxcpp_utf8_string_to_char_array(s);
		return array[index];
	}
```

An array is generated and then seemingly allowed to be GC'ed. Of course I just learned one should use Utf8.iter() in a loop rather than charCodeAt, but this will still generate some GC burden as that array becomes garbage and is only used to return a single value.

Posted at Nicolas' request:
https://groups.google.com/forum/#!topic/haxelang/dAfHfAgfLe8

**Comment by back2dos** [comment]
I've published a pure Haxe version here: https://github.com/back2dos/utf8

It adds full utf8 support (outside BMP).

The only thing it allocates are iterators and [current benchmarks](https://github.com/back2dos/utf8/blob/master/src/Main.hx#L119) show operations to be 2 to 6 times faster (20 times for comparison) on my machine:

```
Main.hx:123: old iter
Main.hx:124: 0.0169912752199747s
Main.hx:125: new iter
Main.hx:126: 0.00369193627906665s
Main.hx:128: old bad loop
Main.hx:129: 0.954053097093622s
Main.hx:130: new bad loop
Main.hx:131: 0.167085675579339s
Main.hx:134: old compare
Main.hx:135: 0.0219088569760544s
Main.hx:136: new compare
Main.hx:137: 0.00150393213121383s
Main.hx:123: old iter
Main.hx:124: 0.0427381196269458s
Main.hx:125: new iter
Main.hx:126: 0.0108010747785844s
Main.hx:128: old bad loop
Main.hx:129: 3.95341560355244s
Main.hx:130: new bad loop
Main.hx:131: 0.977833382477573s
Main.hx:134: old compare
Main.hx:135: 0.0434312704989696s
Main.hx:136: new compare
Main.hx:137: 0.00294983853453029s
```

String comparison is so fast, because [as explained](https://github.com/back2dos/utf8/blob/master/src/haxe/Utf8.hx#L74) utf8 strings can just be compared directly. The [tests taken from the haxe repo](https://github.com/back2dos/utf8/blob/master/src/Main.hx#L65) confirm that. Which begs the question why `haxe.Utf8.compare` was added in the first place.

While it also runs on neko, it is of course A LOT slower there (factor 200 for `iter` last I checked).

The haxe.Utf8 module can just be applied to the standard lib, if you wish.

**Comment by larsiusprime** [comment]
Nicely done :)
