### ISSUE TITLE
Switch the PHP target to PHP 5.4+ instead of 5.1+

### ISSUE THREAD

**Issue by bablukid** [HaxeFoundation/haxe#4465]
As discussed here https://github.com/HaxeFoundation/haxe/issues/4464
there is an inconsistency between the php version check and the generated code.

Currently the generated PHP code always start with this , it should be updated since version 5.1 is veeeeery old
```
if(version_compare(PHP_VERSION, '5.1.0', '<')) {
    exit('Your current PHP version is: ' . PHP_VERSION . '. Haxe/PHP generates code for version 5.1.0 or later');
}
```

**Comment by rivetweb** [comment]
http://serverfault.com/questions/626200/when-is-php-5-4-end-of-life
http://php.net/supported-versions.php

so switch to php 5.6 as minumal version is better

**Comment by Simn** [comment]
@andyli: As a first step, can you change travis Linux to use PHP 5.4?

**Comment by andyli** [comment]
I happened to look at that yesterday and found out that the default version of php available to ubuntu precise (12.04) is [php 5.3.10](http://packages.ubuntu.com/precise/php/php5). Ubuntu precise's [EOL date](https://wiki.ubuntu.com/Releases) is April 2017.

Given our php target is meant to be used with old servers, we probably want to support php 5.3 until ubuntu precise reaches it EOL...

**Comment by Simn** [comment]
The thing is that there are already multiple problems with Haxe/PHP 5.3, so it's fair to say that we're not completely supporting it anyway. I don't want to introduce any changes that would break additional stuff for 5.3 at the moment, but I also don't want to make 5.3-specific fixes in our generator.

**Comment by back2dos** [comment]
The fact is that 5.3 is no longer supported by the PHP group since a year and a half: http://php.net/supported-versions.php

And I think the foremost strength of haxe/php is that you can deploy Haxe web apps to virtually any webspace. However the provider of such webspace has practically no alternative to having a PHP version that still gets security fixes (i.e. >=5.5).

Yes, there are those who are keeping some weirdly stitched together PHP spaghetti apps alive and can't upgrade PHP without everything breaking. But only few among those have haxe/php code to start with, and even those who do could just go and use an older Haxe version to build. I don't think the haxe/php backend should carry everyone's technical debt.

**Comment by andyli** [comment]
Our TravisCI builds now use php 5.4 ;)

**Comment by Simn** [comment]
Thanks, I'll make the other changes for 3.3.
