### ISSUE TITLE
[js] further optimize @:jsRequire generation

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4486]
We could make our `require` generator a bit smarter and analyze importing of the same module, effectively re-using imported objects to only generate the `require` call once. This could probably speed-up small scripts a bit.

E.g.:

``` haxe
package js.node;

@:jsRequire("dns")
extern class Dns { ... }

@:jsRequire("dns")
@:fakeEnum(String)
extern enum DnsErrorCode { ... }
```

currently it will generate:

``` js
var js_node_Dns = require("dns");
var js_node_DnsErrorCode = require("dns");
```

However I think we can make it cache and re-use `require`d objects like:

``` js
var js_node_Dns = require("dns");
var js_node_DnsErrorCode = js_node_Dns;
```

**Comment by back2dos** [comment]
If there is a straight forward way to do this, then sure. Otherwise it might be wise to simply rely on the fact that `require` has its own cache. 

Given that we require once per class per application, while node apps require once per module per dependency, with a little luck we're actually doing better ;)

**Comment by nadako** [comment]
Yeah that's right, this is just about beautiful generation, so it's low priority :-)

**Comment by Simn** [comment]
This strikes me as "not worth it".
