### ISSUE TITLE
JQuery embed feature is weird

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#4538]
Looking at this code: https://github.com/HaxeFoundation/haxe/blob/development/std/js/JQuery.hx#L403
I have the strange feeling that there are 2 issues:

  1. `untyped` inside the the brackets are redundant (or remove the one outside)
  2. the `if` condition is a runtime condition and `Compiler.includeFile` works regardless of the condition so it is always included if `-D embed_js` and never otherwise.

Should that piece of code just be the following?

```haxe
	private static function __init__() : Void untyped {
		#if embed_js
		haxe.macro.Compiler.includeFile("js/jquery-latest.min.js");
		#end
		var q : Dynamic = js.Browser.window.jQuery;
		var js = __js__("js || {}");
		js.JQuery = q;
		__feature__('js.JQuery.iterator',
			q.fn.iterator = function() return { pos : 0, j : __this__, hasNext : function() return __this__.pos < __this__.j.length, next : function() return $(__this__.j[__this__.pos++]) }
		);
	}
```

**Comment by fponticelli** [comment]
I can make a PR if approved ;)

**Comment by andyli** [comment]
That's done by @ncannasse in caa013e813b3ed4021cc9498ed46f7fb01af15d2. So I will let him comment.

I haven't noticed it and haven't done that for the new extern. If it is required, I have to think about how to do that. It is tricky now since `Compiler.includeFile` inject the file not at the call site, but out of the top most closure by default. It means the content of jQuery will escape from `typeof($) == 'undefined'`. And, newer version of jQuery is not strict mode compatible, thus cannot be injected at the call site, which is inside the top most strict mode enabled closure...

**Comment by ncannasse** [comment]
The idea is that even if you use -D embedJS, you might still prefer to use the previously imported JQuery instead of overwriting it. Also, I don't think we will change anything here since it's deprecated in favor of @andyli `js.jquery.JQuery` (we actually discussing feedback about it there, you're welcome to contribute https://github.com/HaxeFoundation/haxe/issues/4528)

**Comment by fponticelli** [comment]
I am glad we are switching to @andyli implementation.
@ncannasse just for your information, the code generates `if(typeof($) == 'undefined') {}` so it literally does nothing.

**Comment by ncannasse** [comment]
ah, did something changed in includeFile implementation in JS ?

**Comment by andyli** [comment]
Yes, in #4419.
To maintain the old behavior, we can specify the position argument as follows:
```haxe
haxe.macro.Compiler.includeFile("js/jquery-latest.min.js", Inline);
```
