### ISSUE TITLE
[js] add ES6 types

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4552]
It seems that the ES6 spec is finalized wrt built-in types like `Set`, `Map`, `WeakMap` etc. and they are already available in e.g. node.js, so we should start adding externs for that.

After that we could think of adding `-D js-es6` or `-D es=6` or something to make our own types (like `haxe.ds.*Map`) use native ones.

Also, @aduros, we currently have `js.html.Uint8Array` and friends, but those are not really HTML-related, they are just general ES types, I think we should move those to the `js` package. What do you think?

**Comment by nadako** [comment]
@explorigin you've done something regarding ES6 types, haven't you?

**Comment by explorigin** [comment]
https://github.com/explorigin/es6-externs Should be a good start.

**Comment by nadako** [comment]
Nice! @ncannasse what do you think about integrating those into std lib?

**Comment by explorigin** [comment]
Hold off a second, there was one change I wanted to make to the Symbol API.  I'm looking for it.

**Comment by explorigin** [comment]
I can't seem to find it.  Maybe you guys can help.  In ES6 `Symbol()` is a static function which I've attached to `Symbol.get()` with `@:selfCall`.  I remember reading somewhere that I could use `@:selfCall` on the class instead of a member static method.  That would be preferable since it's closer to the JS, but I can't find how to do that now.

**Comment by nadako** [comment]
@explorigin you can add `@:selfCall` to the constructor so `new Symbol()` will be generated simply as `Symbol`.

**Comment by explorigin** [comment]
OK cool, I'll change that.  I'd also like to add WeakSet.

Something that's worth knowing before you throw this in the stdlib...WeakMap and WeakSet do not support iteration (because it would be non-deterministic) like the Haxe WeakMap object seems to.  This is not a problem until you want the ES6 WeakMap to be the implementation of the Haxe WeakMap for the JS target.

Speaking of, if you want an `-D js-es6` flag (which I am all for) take a look at https://github.com/explorigin/es6-coretypes

**Comment by explorigin** [comment]
Finished with my changes.

**Comment by ncannasse** [comment]
What's browser support status wrt to these ? I'll let @aduros decide to integrate these when he sync the API. And yes, we could use them in implementing our own Map etc. but maybe we should check if it improves performances first, just in case :)

**Comment by explorigin** [comment]
These enjoy good support is most evergreen browsers (IE11 has less features but basic support). http://kangax.github.io/compat-table/es6/

I would like for something like https://github.com/explorigin/es6-coretypes to be used under the `-D js-es6` flag regardless performance, because I prefer smaller code to faster code.  I think in most cases the ES6 types are slower than the ES5 equivalent implementations because they are not yet optimized in most browsers. (https://jsperf.com/object-vs-map/4)  However, I  expect that to change in the future for new engines like Servo or just later versions of v8.

**Comment by back2dos** [comment]
@explorigin It probably won't surprise you that I find that a bit too speculative for my taste ;) But I wonder, given that your libraries are ready to use, is there any reason to add this to the core *right now*?

This seems straight forward enough, but fiddling with the implementations of core data structures is always risky. Also adding a new flag increases the complexity of the test matrix for the std lib.

I think down the line we should write the std lib against the ES6 spec and use properly tested vanilla JS polyfills (or at least mention them in the documentation). That way, we have only one API to worry about and only one implementation to test. Just as an example: for collections [this thing](https://github.com/WebReflection/es6-collections) appears quite [well tested](https://github.com/WebReflection/es6-collections/blob/master/test/index.js) and [reasonably small at 2kb](https://github.com/WebReflection/es6-collections/blob/master/es6-collections.js).

Still, given that we already have a library that deals with ES6, I wonder if the best time to act is right now. With ES6, things are only getting better, so time is basically on our side.

**Comment by nadako** [comment]
I like the idea of writing against a modern spec and providing optional polyfills. I, for example, only use JavaScript target for node.js which nowadays is pretty compilant to at least ES5 and ES6 containers.

This also brings to mind an idea of adding ES6 target for Haxe that generates all those fancy class syntax, `let`s and function binding. It could already be supported by node.js without any additional tools, and can easily be translated to ES5 with e.g. babel.

**Comment by explorigin** [comment]
> @explorigin It probably won't surprise you that I find that a bit too speculative for my taste ;)

That's fine.  My point is that if a developer provides the `-D js-es6` flag, I don't feel like it is the compiler's job to hold their hand if they've made a bad technical decision.  The default (without the flag) should, of course, work on as many platforms as possible.

> But I wonder, given that your libraries are ready to use, is there any reason to add this to the core right now?

It's not really important to me.  I have what I want in these libraries.  But if you guys want to add them into the standard library, I'll be glad to help.

> I think down the line we should write the std lib against the ES6 spec and use properly tested vanilla JS polyfills (or at least mention them in the documentation). That way, we have only one API to worry about and only one implementation to test.

I'm fully in favor of this.  (Personally) My next challenge for implementing and ES6 target was rewriting Haxe iterators to be translated to ES6 iterators/generators.  It would not be a simple task from a JSGenerator perspective.  But implementing it in OCAML would be much easier.

**Comment by explorigin** [comment]
From a speed perspective, I can say with confidence that most Map operations are slower than Haxe's Map operations.  However, Map.keys() and Map.iterator() might be slower because it builds an array in N-time (http://try.haxe.org/#c6f57).  There are several solutions to this problem.  Most notably http://blog.zame-dev.org/fastiteratingstringmap-part-2/  but supporting ES6 iterators is one solution and supporting ES6 map is another.

**Comment by indolering** [comment]
FWIW, as a JS developer I would prefer to have the generated code reflect the Haxe code as much as possible.  Client-side JS isn't generally computationally intensive; I'm writing a web client in Polymer using a virtual dom (which entails a huge amount of performance overhead) that deals with thousands of records and I've never had trouble keeping the UI responsive.  Custom data structures also decrease compatibility with external code, although I understand this use-case isn't as applicable in other targets.

I would think that an optimization flag would allow for more flexibility when it comes to accepting hand-tuned data structures, Emscripten-esque type annotations, and other enhancements above the baseline output.  It would also make it easier to rollback a change to the native data structure if later JS engine optimizations or native JS transpilers like Closure Compiler end up doing a better job.

WRT polyfills vs transpiling, I suspect targeting a transpiler would be much easier than dealing with polyfills.  The biggest changes (`yield`, classes, arrow functions, etc) can't be polyfilled and the JS community is trying to increase the pace of development.

**Comment by indolering** [comment]
> Client-side JS isn't generally computationally intensive

Of course, I'm not writing game code so WTF do I know :smile:.  That being said, *most* Javascript is never run and most javascript that is run is never hot enough to require optimization.  But maybe this just speaks to two different use cases and (as an end user) I would prefer to have both options.

**Comment by AllNamesRTaken** [comment]
Maybe I am late to the game and totally new to Haxe but I am writing my own 2d game engine. Began in JS, translated it all to Typescript and now moving to HAXE. The big thing with ES6 Maps is that it is not using objects. Since most optimizing compilers (read V8 atleast) is going to translate objects into memory offsets for speed when optimizing. Using an object as a hash will result in the compiler evicting the code into the state machine and running a horribly slow Hash list version there just to try a few seconds later to optimize it and the evict it again. This causes horrible horrible lag and jank when you try to keep 60FPS in Javascript. My experience from running my engine as well as looking at the deoptimization debug info that V8 outputs, is that the ES6 Map object doesn't cause this to happen. Anyone else have noticed this or can tell me that I am way off?

**Comment by fullofcaffeine** [comment]
Any news about ES6 output support? Do we have a roadmap for the js generator?

**Comment by dmouton** [comment]
+1

> * ES5-style classes don't work with native Custom Elements because the
>  * HTMLElement constructor uses the value of `new.target` to look up the custom
>  * element definition for the currently called constructor. `new.target` is only
>  * set when `new` is called and is only propagated via super() calls. super()
>  * is not emulatable in ES5. The pattern of `SuperClass.call(this)`` only works
>  * when extending other ES5-style classes, and does not propagate `new.target`.

ES6 output support is a must have to stay up to date with Javascript standards

**Comment by nadako** [comment]
> super() is not emulatable in ES5

So you're saying Babel doesn't work either? IIRC what it generates for `super()` is `Object.getPrototypeOf(ThisClass)).call(this)`, which should be exactly the same as `SuperClass.call(this)`...

Could you provide concrete code examples where current haxe js output is not sufficient? I'm not very familiar with html stuff, so it's not easy for me to understand the problem by your description, sorry  :)

**Comment by dmouton** [comment]
Yep Babel doesn't work either.

```haxe
package ;

import js.html.HtmlElement;

class Main {
    public static function main():Void{
        CustomElementRegistry.define("test-damo",Toto);
    }
}


class Toto extends HtmlElement{

}

@:native('customElements')
extern class CustomElementRegistry{
    public static function define(name:String,type:Dynamic):Void;
}

```
```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test CustomElement</title>
    <script src="release/main.js"></script>
</head>
<body>
<script>
    class XProduct extends HTMLElement {
        constructor() {
            // Always call super first in constructor
            super();

            // Create a shadow root
            var shadow = this.attachShadow({mode: 'open'});

            // Create a standard img element and set it's attributes.
            var img = document.createElement('img');
            img.alt = this.getAttribute('data-name');
            img.src = this.getAttribute('data-img');
            img.width = '150';
            img.height = '150';
            img.className = 'product-img';

            // Add the image to the shadow root.
            shadow.appendChild(img);

        }
    }

    // Define the new element
    customElements.define('x-product', XProduct);
</script>
<x-product data-name="Ruby" data-img="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4621/ruby.png" data-url="http://example.com/1"></x-product>
<test-damo data-name="DAMO"></test-damo>
<x-product data-name="Ruby" data-img="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4621/ruby.png" data-url="http://example.com/1"></x-product>
</body>
</html>
```

**Comment by nadako** [comment]
Interesting, thanks! I see Babel has a [plugin](https://github.com/github/babel-plugin-transform-custom-element-classes/blob/master/lib/index.js) to work that around with `Reflect.construct`. We could look into that in the short term. But yeah, eventually we'll need a proper ES6 target.

**Comment by nykevinwong** [comment]
will this feature be compatible with BabelJS? any plan of when this feature to be released?

**Comment by Simn** [comment]
I think we can close this.
