### ISSUE TITLE
Q: Why does Array Access set require a return value?

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#4554]
From this example from the docs:
http://haxe.org/manual/types-abstract-array-access.html

```
@:arrayAccess
public inline function arrayWrite(k:K, v:V):V {
    this.set(k, v);
    return v;
}
```

I'm curious about the reason for the explicit return, this usage pattern seems unusual:

`var ret = x[index] = val;` 
or 
`func(x[index] = val)` 

I am wondering because the majority of cases I've tried just generate a loose expression in the output.
When combined with inlining and such there leads to a lot of redundant code, for example with C++ :

```
{
    ::__hxcpp_memory_set_float(this1->buffer->b,this1->byteOffset,((Float)1.0));
    ((Float)1.0);
}
```

Where the usage was `x[0] = 1.0`.
If the set has no return value, or allows `Void`, 
it can be properly inlined without the scope and without the loose expression.

This is a trivial example, for more complex examples the little extra expression balloons, sometimes making 100 lines of out 1 expression.

So I'm curious, what is the return used for?

**Comment by mrcdk** [comment]
I would guess that it's because this http://haxe.org/manual/class-field-property-rules.html (the trivia part)

**Comment by underscorediscovery** [comment]
I believe setters existed long before the array access, though, and I consider them quite different.

(The setter ones make sense to me).

**Comment by fponticelli** [comment]
Just to add some color, Swift prevents both cases ... the assign operator
returns Void. I think it is quite a smart strategy.

Il giorno ven 18 set 2015 alle ore 18:01 Sven Bergström <
notifications@github.com> ha scritto:

**Comment by back2dos** [comment]
> Just to add some color, Swift prevents both cases ... the assign operator
returns Void. I think it is quite a smart strategy.

Arguably, there's some elegance to its simplicity. But such a change would require a new Haxe version ;)

What's more important: a setter or an `@:arrayAccess` write can modify the value and the most efficient way to set and know the new state is to return it. In the case of an object that either does its own synchronization or stores its state on the file system or whatever, you do not want to have the overhead twice.

As for the actual problem: it seems more an issue with inlining/code generation than with the language semantics themselves. This has to be addressed for *all* functions, not just setters. It would be pretty silly to make users return `Void` instead of a value to have smaller code. That would pretty much defeat the purpose of having a compiler for a higher level language.

**Comment by underscorediscovery** [comment]
The inlining works as it is documented, and expected. 
The loose expression is a result of a return value that is not needed/used.

While typing to clarify (since all function? really?) I realized I hadn't tried what I am suggesting in code. I tried it and it does allow Void with no return statement. That's exactly what I was after.
