### ISSUE TITLE
Type parameter failed to unificate

### ISSUE THREAD

**Issue by mandel59** [HaxeFoundation/haxe#4578]
The following code (http://try.haxe.org/#1c799) doesn't pass type checking.

```haxe
class Test {
    static function main() {
        var i = new IUnOp(function(x) return x * 2);
        var v = i.denote(Cons(10, Nil));
        trace('$v');
    }
}

class TList {}
class TCons<U,V:TList> extends TList {}
class TNil extends TList {}

enum Stack<L:TList> {
    Nil: Stack<TNil>;
    Cons<X,L:TList>(x: X, xs: Stack<L>): Stack<TCons<X,L>>;
}

interface Instr<L1:TList,L2:TList> {
    function denote(s: Stack<L1>): Stack<L2>;
}

class IUnOp<X,Y,S:TList> implements Instr<TCons<X,S>,TCons<Y,S>> {
    var f: X->Y;

    public function new(f) {
        this.f = f;
    }

    public function denote(s: Stack<TCons<X,S>>): Stack<TCons<Y,S>> {
        return switch(s) {
            case Cons(x, s):
                Cons(f(x), s);
            	// Cons(f((x:Dynamic)), s); // this passes
        }
    }
}
```

```
Test.hx:32: characters 23-24 : Cons.X should be IUnOp.X
Test.hx:32: characters 23-24 : For function argument ''
Test.hx:31: characters 12-16 : Void should be Stack<TCons<IUnOp.Y, Cons.L>>
```

**Comment by Simn** [comment]
That was fun to figure out, I'll log something here in case I come across this again in a few years: When typing GADT enum constructors we turn all enum field type parameters into monomorphs, type the "constructor call" and then turn back all still-monomorphs to type parameters. This is done in order to avoid invalid monomorph binding later on which would cause really strange errors.

The problem here is that the monomorph we come across is not the original one (from turning `Cons.X` into a monomorph), but instead has been bound to `IUnOp.X`. The pattern matcher still turned this back into the original type parameter which caused the observed problem. I fixed this by checking if the monomorph we come across is physically equal to the followed monomorph.
