### ISSUE TITLE
Math.log10e() ? Any chance we can add?

### ISSUE THREAD

**Issue by andytwoods** [HaxeFoundation/haxe#4621]
Hi there,

would just please us scientists :)  

JS has it. AS3 too.

Using below here.

inline public static function log10e():Float {
   return 0.4342944819032518;
 }

**Comment by Chlorodatafile** [comment]
Why not implement it like that instead : 
```haxe
public static inline var LOG10e:Float = 0.4342944819032518;
```

The like `String`, `UInt`, `Int`, `Float` and `Bool` have absolutely no problem with this kind of definition. :)

And because it's a constant value, it have to be typed in upper case, but because e is generally in lower case, I think this way of writing could be ok. :)

**Comment by Simn** [comment]
There's not enough incentive to add this.
