### ISSUE TITLE
JSON parse inconsistent for cpp target

### ISSUE THREAD

**Issue by er453r** [HaxeFoundation/haxe#4627]
Test case here: https://gist.github.com/er453r/2e460b4945aad29f73ff

On all platforms except `cpp` both parses are successful, on `cpp` the class cast returns `null`.

Tried with ` -D haxeJSON` and without. I know that documentation does not say anything about casting parsed JSON to Class (only typedefs are mentioned) but I've been using this successfully on multiple platforms until I tried `cpp`.

**Comment by Simn** [comment]
You cannot parse something and expect it to magically turn into a class on static targets. This is going to fail on other such targets as well and is undefined behavior.

**Comment by er453r** [comment]
Ok, I understand :) Java manages this quite easily, and I'm certain I can this manually in haxe - the only requirement is an empty constructor. Create a new empty instance, call setters/public fields and viola.

**Comment by Simn** [comment]
If you have a finite set of potential classes it's better to just create them properly (without reflection), but it's usually not a big deal. Performance-wise it's more important to actually use a proper class instead of a typedef structure and targets such as C++, even if that means a slightly more complicated creation process.
