### ISSUE TITLE
ES5 Array reduce in Haxe

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/haxe#4637]
Haxe `Array` doesn't have the `reduce` method, which is available otherwise as `Lamda.fold` as a Haxe implementation.

ES5 capable browsers (IE9+) have a native `Array.prototype.reduce` method which may be more efficient than `Lambda`'s.

Could `Lamda.fold(a, ...)` be inlined as `a.reduce(...)` when `-D js-es5` is set?

Bonus: add `reduce` to `Array` (possibly implemented using Lamda).

**Comment by ncannasse** [comment]
Please submit a PR and check that unit tests are properly done

**Comment by mrcdk** [comment]
Are we sure that `reduce` is more efficient than `Lambda.fold`? This little tests gives me better results when using `Lambda.fold` but the test my be flawed. http://try.haxe.org/#d48A1

**Comment by nadako** [comment]
Weird, it seems that `reduce` takes more time to warm-up, but then it's actually works faster, at least in this artificial example. I believe the main concern about `Lambda` is that it works with plain `Iterable`s and `Iterator`s, so it doesn't know about Array iteration optimization and always allocates an iterator object, which is a real bummer.

**Comment by back2dos** [comment]
It looks like when the JIT is hot native reduce does get faster:
http://try.haxe.org/#7EfC1

**Comment by elsassph** [comment]
Let's say that the performance difference in practice is likely to be limited, but that's a bit less generated code, less allocations, less `using`, and it'd complete the other usual functions like map/filter are available.

**Comment by back2dos** [comment]
Also, if we just inlined Lambda.fold, then it would be faster already (when
the reduction function is known): http://try.haxe.org/#602bB

It's too bad that even after inlining, it still doesn't eliminate the
iterator (using fold2 in the example generates the same code), although I
think that might be attainable.

However I have to point out that we are examining a purely academical
example, namely calculating sums. In Haxe, these are our options:

   { var ret = 0; for (x in target) ret += x; x; }
   target.fold(function (x,y) return x + y, 0);
   target.reduce(function (x, y) return x + y);

The above is the fastest, by quite a factor. The second can be made to be
as fast as the first one (by inlining lambda and by avoiding the iterator
after inlining). The third will be slower. In fact as long as the function
that does the calculation is inlineable (because it's a known anonymous
function or an inline method), the native version will never be faster.

But if the reducing function actually does something slightly more complex,
it just won't matter anyway.

**Comment by elsassph** [comment]
Again I think having very lean JS code is good to have for readability, but I guess it can matter to be inlined on some platforms.

**Comment by nadako** [comment]
Just so you know, I'm almost prepared a PR for this, using this API: https://github.com/HaxeFoundation/haxe/blob/array_reduce/std/Array.hx#L276-L288

**Comment by nadako** [comment]
Okay, PRs are there.

**Comment by hughsando** [comment]
What is the status of this - do you want me to merge the hxcpp changes?

**Comment by nadako** [comment]
No idea, I'll ping in haxe issue

**Comment by nadako** [comment]
Oh nvm, I thought I'm commenting hxcpp PR. So, ping?

**Comment by Simn** [comment]
Can you add a test for when this is accessed through Dynamic, if that works?

**Comment by nadako** [comment]
I think it won't work on JS since it's an inline extern method.

**Comment by nadako** [comment]
oh nvm, sorry, I am a bit sick :)

**Comment by Simn** [comment]
I was gonna say, JS is pretty much the only target I'm not worried about.

**Comment by nadako** [comment]
Yeah, but it's actually a native ES5 method, I confused this issue with some other...

**Comment by back2dos** [comment]
I still don't get why this is actually being added. Natively, exactly one
target supports this, and the speedup is not convincing (also if speed is
what we care about then inlining Lambda will give us that ... on all
platforms mind you). What's next? `forEach`?

I see exactly one good argument for having added `map` and `filter` to
`Array` and that's the fact that `Lambda` constructs lists, not arrays.
This argument does not apply to `forEach` or `reduce`, for obvious reasons.
So what am I missing?

**Comment by hughsando** [comment]
Yes, an inline Lambda mapArray/filterArray would be nicer. Only one "using
Lambda" away from optimal solution.

**Comment by nadako** [comment]
Let's close this then, to reduce issue clutter.
