### ISSUE TITLE
genericBuild macro when applied to an interface doesn't work

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/haxe#4652]
I expect that the semantics of genericBuild cannot actually work for interfaces (type building on interfaces probably just isn't well supported in the compiler).  However, it is still sometimes useful to run a genericBuild macro against an interface; for example, if Compiler.addGlobalMetadata is used to add a @:genericBuild meta to a wildcarded set of types, and one of those types happens to be an interface, then the compiler will emit an error like this if 'null' is returned from the generic build macro:

TestElideLonelyInterfaces.hx:107: lines 107-118 : Should implement by using an interface

The generic build macro that I am using looks like this:

    macro static function apply() : ComplexType
    {
        return null;
    }

I would expect this to simply have 'no effect' when run against an interface; but instead, it produces the error I described.

**Comment by Simn** [comment]
For the most part we treat interfaces just like classes, so I don't think we should make an exception here. The problem here is likely that returning `null` causes the compiler to try and infer the type (it creates a monomorph in this case). The error you're seeing then comes from your class trying to implement a monomorph which confuses the compiler.

I'm not sure how to address this. If you simply use the original type (which lead to the invocation of the macro) you will likely end up with a compiler crash due to infinite recursion. The problem is really that `@:genericBuild` isn't a good candidate for being applied to multiple types like that.

**Comment by bjitivo** [comment]
So when returning null when building a class type, does it also generate a monomorph?  If so, why does that work?  Do contexts that expect a class also work with a monomorph, just fetching the class type out of it (if that makes any sense)?

If so, can't contexts that require an interface (such as implements arrays within class types) also handle a monomorph by similarly fetching the actual interface out of it?

**Comment by bjitivo** [comment]
Also, why does it infinite recurse?  How does the build macro know not to re-evaluate against the result of the build macro sometimes, but not other times?

**Comment by bjitivo** [comment]
For what it's worth, the macro I am trying to implement wants to do this:

- Run an initial macro in a --no-output context that:
  - In Context.onGenerate(), iterates over all types and identifies interfaces that are only implemented by one class
  - Run the compiler in a second step with all of the original arguments, except the initial macro invocation and the --no-output removed, and with another macro or set of macros specified on the command line argument that will:
    - Rewrite 'implements' clauses using the "lonely interfaces" using a dummy empty interface instead
    - Rewrite all references to those interfaces everywhere else in the AST as references to the singly implementing class

This is a way to try to implement feature request https://github.com/HaxeFoundation/haxe/issues/4603 using macros.

I could generate a separate build macro for each lonely interface (which causes it return the dummy interface instead of itself), and a separate build macro to be appled to all classes and enums that rewrites all type references to all lonely interfaces to the singly-implementing class (note entirely sure exactly how to do this though, but that's a separate problem).

**Comment by Simn** [comment]
The problem is not the type definition but its usage. If you have `class C implements I` and `I` becomes a monomorph you get the error you're seeing. The whole point of `@:genericBuild` is that it is applied for each (syntactical) occurrence of a type and in some of these places having an unknown type doesn't make any sense.

It basically works like this:

1. The compiler comes across a type-hint, i.e. a `ComplexType`.
2. That type-hint is a dot path which resolves to a class/interface which has `@:genericBuild`.
3. The macro is executed and the returned `ComplexType` goes back to 1.

Thus when your macro returns a dot path which keeps resolving to the same `@:genericBuild` type you'll get in trouble.

**Comment by bjitivo** [comment]
So basically it's not possible for a @:genericBuild() macro to return the same type as is in Context.getLocalType() because that will infinitely recurse?  Am I misunderstanding?  Is there a way for the generic build macro to remove the @:genericBuild meta so that it doesn't get re-applied if the macro returns the original type?

Or what if the compiler didn't re-apply build macros to a type returned by a build macro if the type returned is the same type as was passed in?

**Comment by Simn** [comment]
You could try removing the metadata via [MetaAccess.remove](http://api.haxe.org/haxe/macro/MetaAccess.html#remove). You can get a `MetaAccess` structure on the `meta` field of [ClassType](http://api.haxe.org/haxe/macro/ClassType.html). I can't guarantee if that works as expected though.

**Comment by bjitivo** [comment]
Too bad the pathFilter used by addGlobalMetadata isn't a regexp.  It would be much more convient if it were.

**Comment by bjitivo** [comment]
I think I have worked around this.
