### ISSUE TITLE
Recurrent Interfaces takes the compiler into infinite loop

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#4671]
```haxe
interface IFoo extends IBar{}
interface IBar extends IFoo{}
```
=> infinite cycle.

Haxe version: 3.2.1 (release)

**Comment by Simn** [comment]
Same with classes actually:

```haxe
class A extends B { }
class B extends A { }
```

I guess `is_parent` needs a stack.

**Comment by Simn** [comment]
Actually it's `set_heritance` that is being called recursively.

**Comment by Simn** [comment]
My investigations suggest that this has been caused by @ncannasse's change here: https://github.com/HaxeFoundation/haxe/commit/e01fbc4ec0870e626810ea6f83d912b80e12aebc

I think due to the mutual recursion both types are considered "not ready", so the compiler keeps retrying. The recursion is not detected because the relation (`cl_implements`/`cl_super`) is never set due to the build cancellation.

**Comment by Simn** [comment]
Same as #4504. Also mentioned in #3933.

**Comment by ncannasse** [comment]
Can you add a check for recursion at the top of cancel_build ? that should do it

**Comment by Simn** [comment]
That doesn't help because there is no recursion to detect: `cl_super` and `cl_implements` are never set, so `is_parent` is never true.

I don't understand why we should cancel out of `set_heritance` in the first place. Even if the class isn't built yet, it's still going to be the same class so setting the heritance relation shouldn't do any harm. We should only cancel out of anything involving its *structure*.

Unfortunately I don't know how to do that.

**Comment by ncannasse** [comment]
If it's not built yet the metadata is not propagated from its parent some we might miss some @:build. I'm doing some debugging related to this atm.

**Comment by Simn** [comment]
Fair enough, but setting `cl_super/cl_implements` is not strictly tied to that. I think we should two-pass this:

1. Set the relation (`cl_super` and `cl_implements`).
2. Do whatever else we're doing there, including metadata processing.

This way we can cancel out of building while still checking recursion.

**Comment by ncannasse** [comment]
Sure, this _might_ work. Another solution is to check for recursion before checking cl_build

**Comment by Simn** [comment]
Again, there's no recursion to detect because the relation is never set.
