### ISSUE TITLE
Compile-time concatenation of inlined string

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4706]
Refer to comments in sample code below:

```haxe
class Test {
    static inline var int = 1;
    static inline var sum = int + 2;
    
    static inline var str = "a";
    static inline var concat = str + "b";
    
    static function main() {
        trace(sum); // output code: console.log(3);
        trace(concat); // output code: console.log("a" + "b"); // but desired: console.log("ab");

    }
}
```

**Comment by Simn** [comment]
We discussed this before and back then @ncannasse turned it down because of potential effects on the size of the constant pool on some targets.

**Comment by kevinresol** [comment]
Alright, this is no big deal (I hope)

**Comment by back2dos** [comment]
Isn't the exact opposite true for other targets, like JS?

This is one is really tough to do with macros, because you have to have the
whole thing typed, then revert it back to expressions, then perform the
compile time concatenation and then do all kinds of crazy stuff to the
expression to make it pass the typer a second time.

So given the original objection, would it be possible to enable this only
in a given scope that is decorated with something like `@:mergeStrings`
metadata?

**Comment by Simn** [comment]
If anything this should be a compiler flag.

**Comment by back2dos** [comment]
The reason I am asking is that I wanted to bring tink_markup back to life.
Without this optimization, the generated code is significantly slower,
particularly on neko. Both because optimization is best performed only
where it matters, and because of the original objection, I would think that
a local solution may be preferable to a compiler flag, where you have to
make a choice for your whole code base. If somebody really wants this
globally (for whatever reasons) then addGlobalMetaData would do the trick.

**Comment by ncannasse** [comment]
Not specific to this, but a more general view on the topic:

I'm not a big fan of introducing new metadata to tweak the compiler behavior, especially for such kind of optimization. I find that we have way too many already, so much that I no longer myself understand what some of them are supposed to do :) 

Adding metadata was a good idea to enable us to experiment new ideas but I would not like Haxe to turn into something that adds specific case over specific case and loose its simplicity. I think we will need a full examination of these for Haxe 4, to decide which should be turned into proper language feature, which is not useful, which should be done through macros, etc.
