### ISSUE TITLE
Improvements in Haxe Language

### ISSUE THREAD

**Issue by jobs-git** [HaxeFoundation/haxe#4730]
@ncannasse @Simn @andyli @waneck @nadako  @hughsando 

Hello to all developers, I just wish that Haxe to become the best programming language! So I am gonna contribute a link that a developer blogged regarding further improvements in Haxe, hope you check it out and maybe add some of it to the 'to dos list'.

http://blog.zame-dev.org/8-things-i-dont-like-in-haxe/

Short Summary
1. Inconsistent behavior while using uninitialized class variables
2. Float is “stronger” than Int
3. Absence of abstract class methods (like abstracts in java / php or virtual methods = 0 in c++)
4. Inconsistent ObjectMap behaviour
....

**Comment by ncannasse** [comment]
1. Inconsistent behavior of uninitialized variables : I don't think we will change that, or maybe only enforce 0. for Float defaults in Flash instead of NaN so we reduce to two behaviors (0. or null if the platform uses static typing). tracing a Null<Float> on CPP shouldn't segfault anymore

2. Std.int(a/b) should be optimized correctly now on plaforms that have such native operation, open an issue if it's not the case.

3. Macros

4. I think that functions are no longer accepted for ObjectMap, can you confirm @Simn ?

5. We could something open it, open a separate issue

6. We did some work on it, it's not easy. I don't think JS allows to iterate over object keys in an iterator-way

7. Fixed in 3.2

8. You can use  e.match(EFoo(_))
 
I'm closing this for now, please open separate issues when you want to report things, it's much more easy to handle afterwards.

**Comment by nadako** [comment]
1. Actually, I think we could do some work on default values. I also heard (needs benchmarking tho) that on JS it's actually better performance-wise to always initialize all class fields (even to `null`).

2. `Std.int(a/b)` is optimized at least on Java/C#, as nicolas said, please open an issue if it's not the case.

3. I agree it could be a nice addition to the language, but not cruicial.

6. We *could* add some hacks into the compiler to optimize map iterators, similar to length+arrayaccess, but it's much better to try designing some universal way to implement optimized iterators using just haxe.

**Comment by nadako** [comment]
Let's discuss it for a bit and then close (potentially opening separate issues?)

**Comment by delahee** [comment]
There is consensus or enginnering in the works for most points but : 

1- agreed, approved and needed. It is a proven nightmare on cpp and neko
3- after years and thoughts, i really **not** want them for safety reasons, my code is much readable and better without those. And there are many better alternatives already...

**Comment by YellowAfterlife** [comment]
The post is from 10 months ago, a handful of things had been fixed since then (the post author themselves states that in the beginning of it), Creating an issue and tagging lots of people without prior research is immature at best.

On 1, V8 uses object "patterns" (sets of fields stored) to access the fields quicker. Appropriately initializing all fields by yourself will yield the same result and the runtime will not spend additional time to initialize something to null\0 only for the field to be overwritten later.

On 6, iterating over map keys is rarely fast anywhere. If you direly need constant iteration over keys, you can make a combined structure containing an array of keys and the map of key-value pairs. Multiple examples exist already.

Additionally on 8, familiarizing yourself with [the manual](http://haxe.org/manual/lf-pattern-matching.html) is generally a good idea.

**Comment by Simn** [comment]
I don't see the value in a catch-all issue like this. If you want to discuss something specific use the haxelang/haxedev google groups or open a specific issue.

**Comment by hughsando** [comment]
He he - I really like auto-cast Float to Int and also to Bool (with
exception of operator=), eg "if (flags & SomeBit) ... ".

Also, can't we please just have Math.idiv(a,b) ?   4.idiv(3) = 1.  I
thought the "optimized" version gave different results somehow - maybe with
overflow or divide-by-zero.

But I agree these should be separate issues.
