### ISSUE TITLE
Error Setting Up Lime And OpenFL

### ISSUE THREAD

**Issue by samncrowley** [HaxeFoundation/haxe#4737]
So I've just been trying out HaxeFlixel for the first time today and have not been able to resolve this...

I'm running Mac OS X El Capitan and when following the setup instructions, `haxelib install lime` works perfectly fine and it all installs fine, but when I run `haxelib run lime setup` I get this error:
```
Called from ? line 1
Called from CommandLineTools.hx line 1385
Called from CommandLineTools.hx line 25
Called from a C function
Called from CommandLineTools.hx line 64
Called from CommandLineTools.hx line 1082
Called from /usr/lib/haxe/std/neko/_std/sys/io/File.hx line 30
Uncaught exception - [file_contents,/haxelib.json]
```

Also when running some of the commands I get:
`This is the first time you are runing haxelib. Please run haxelib setup first`

Upon running `haxelib setup` I try to set the default directory by pressing enter, which just gives this error:
`Failed to create directory '/usr/lib/haxelib' (std@sys_create_dir), maybe you need appropriate user rights
Check also that the parent directory exists`

I am completely new to Haxe and really don't have a clue as to what's going on. Any ideas?

**Comment by nadako** [comment]
You may want to report this to the OpenFL/Lime repository, because that looks like a bug in their command-line tools.

But anyway, this is probably related to the fact haxelib repository location isn't set up indeed, so you really need to do `haxelib setup` first. The error you get when doing `haxelib setup` most likely means that you're trying to use that directory without root rights (hence the "maybe you need appropriate user rights" message). Try specifying some path in your home directory, or run `haxelib setup` as root (I wouldn't do that though).

**Comment by nadako** [comment]
Oh, right, there's an issue on OSX El Capitan with `/usr/lib` paths, you could also try `/usr/local/lib/haxe/lib` or something (see https://github.com/HaxeFoundation/haxelib/issues/250)
