### ISSUE TITLE
Compiler's error about missing ' ; ' not throws

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#4767]
In the next code see all lines ending with `}` but not with semicolon `;`.

You can reproduce it with latest Haxe dev nightly build. 
```haxe
class Main
{
	static function main()
	{
		function returnAnonC()
			return {}

		returnAnonA();
		returnAnonB();
		returnAnonC();

		// enother tests:
		{a:"", b:42}
		var foo = {a:"", b:42}
		var bar:{a:String, b:Int}
	}

	static function returnAnonA()
	{
		return {}
	}

	static function returnAnonB()
		return {}

	// Main.hx:22: characters 9-11 : Missing ; - it's OK
	//static function returnConst()
	//	return ""
}
```
Build: `$ haxe -main Main -x out/tests.n`.

**Comment by Simn** [comment]
That's working as intended, `} implies `;` in these cases.

**Comment by fzzr-** [comment]
@Simn, I know what `}` implies `;` when end of block. But why after `var foo = {a:"", b:42}` and `var bar:{a:String, b:Int} too?`

**Comment by Simn** [comment]
Yes, that's how it is and I see no reason to change it. It doesn't cause any parsing problems I'm aware of.

**Comment by nadako** [comment]
TBH was also finding it quite weird not to require `;` after `}` in non-blocks, but changing it now will break a lot of code so it's not worth it.

**Comment by tobil4sk** [comment]
> It doesn't cause any parsing problems I'm aware of.

It does kind of cause issues... I've been trying to do some work on tree-sitter-haxe: https://github.com/vantreeseba/tree-sitter-haxe.

tree-sitter doesn't seem to have a way of "looking back" the way the haxe parser does to check whether the last token was a semicolon...

Not only this, there are language issues that result from having these blocks in nested expressions. Take this example:

```haxe
final a = 10 + {30;} - 20; // no error
trace(a); // 40
```

No error is thrown, and 40 is traced, because -20 gets treated as a separate statement where the - is a unary operator instead of a binary one. i.e. it's like the semicolon is automatically inserted for you.
```haxe
final a = 10 + {30;}; - 20;
```

But what if I was unaware that you can't put operators after blocks, and assumed that the output would be 20?
