### ISSUE TITLE
Unreachable code warnings

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4782]
We need to fix a few things wrt unreachable code.

- we need a metadata to suppress the warning, and tell about it in the warning
- i would like a few cases to be whitelisted. for instance I often get warnings in such code:

```
function foo(x:Int) {
    while( true ) {
       ....
    }
    return false;
}
```

It is right that the `return false` is not reachable, but that doesn't make it bad coding practices either. if we could whitelist`TReturn TLocal` and `TReturn TConst` that would solve it.

**Comment by Simn** [comment]
I just documented that yesterday: http://haxe.org/manual/cr-static-analyzer.html#modules

The metadata in this case is `@:analyzer(no_unreachable_code)`.

I'm not sure about the whitelisting, isn't that rather arbitrary? It might very well detect a faulty algorithm which is supposed to have a loop exit but does in fact not.

**Comment by ncannasse** [comment]
Yes but that can be detected by simply running the program. I don't think that the analyzer role should be to inform the user of a missing break. I'm fine if we make the whitelist for final return, but it's a case I often find : I have several in hscripts, and others in my code, I don't think that it's good practice to remove these returns.

**Comment by Simn** [comment]
> Yes but that can be detected by simply running the program.

That's true for virtually any compile-time error.

> I don't think that it's good practice to remove these returns.

Let's look at the disadvantages of unreachable code:

* Larger source files
* Not always easy to detect by just looking at it
* Additional work for the compiler at every stage (parsing, typing, post-processing)
* Has to be removed on at least the Java target anyway because it's a native compiler error

You're gonna say that all that is negligible, and I agree, but given that there are no *advantages* of unreachable code it's still an easy decision to make.

I'll deal with the HF repositories and even send you a PR for heaps if that what it takes. Let's not add arbitrary exceptions because "it affects my code", I don't think that's a good basis for compiler design.

**Comment by Simn** [comment]
Argh, looks like hscript is on your side. What I didn't consider is that we made inlining improvements that might affect this. The code is considered unreachable on 3.3.0 (because a `throw` was inlined) but not unreachable on 3.2.1.

Fine then, I'll disable unreachable code checks by default.
