### ISSUE TITLE
Haxe Serializer throws Segmentaion Fault with Xml in PHP.

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe#4801]
```
haxe.Serializer.run(xml);//Segmentation Fault
```

PHP 5.5.9-1ubuntu4.14 
HAXE v 3.2.1.

Same issue if it is wrapped with a class.

**Comment by Simn** [comment]
Can you please post a complete minimal example?

**Comment by waneck** [comment]
Have you compiled neko yourself?

**Comment by back2dos** [comment]
@waneck could you enlighten me on how that is relevant for a PHP issue?

**Comment by waneck** [comment]
Oops. I misread the issue. Sorry :)

2016-01-19 11:25 GMT-02:00 Juraj Kirchheim <notifications@github.com>:

**Comment by 0b1kn00b** [comment]
I'm reasonably sure you can use an empty xml instance, I'll test as soon as
I can.

**Comment by ncannasse** [comment]
Have you seen Star Wars already?
This MIGHT be relevant to the current issue, because PHP is quite picky

**Comment by RealyUniqueName** [comment]
Actually that's a documented behavior.
Parsed xml structure has circular references, so `Serializer` falls into infinite recursion.
You should use [`Serializer.USE_CACHE`](http://api.haxe.org/haxe/Serializer.html#USE_CACHE) field for objects with circular references.

And that Star Wars movie has no connection with PHP, because Yoda died much earler.
