### ISSUE TITLE
Static macro methods on @:generic classes

### ISSUE THREAD

**Issue by fussybeaver** [HaxeFoundation/haxe#4804]
This is a regression from a previous fix: https://github.com/HaxeFoundation/haxe/issues/3766

Example:

```
@:generic
class Main<T> {
    static function main() {
        new Main<String>();
    }

    function new() { }

    macro static function test() {
        return macro null;
    }
}
```

This fails to compile with the error "A generic class can't have static fields"

Macro static methods are an exception, and are allowed in a generic class https://github.com/HaxeFoundation/haxe/blob/3.2.1/codegen.ml#L418

**Comment by Simn** [comment]
This one confused me, but there's no regression here:

1. Your example is invalid because you do in fact have the static function main on your `@:generic` class.
2. You have to `#if !macro` your macro function, the error you're getting actually occurs in macro context because there the macro is not really considered a macro (don't ask).
