### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4816]
```
class Main {
    static function main() {
		var f = { f : { name : "hello" } };
		trace( macro $i{f.name} );
    }
}
```

Instead of failing with  `f has no field name` is does print:

```
Main.hx:7: characters 18-24 : Identifier 'CIdent' is not part of enum haxe.macro
.Constant (Suggestion: CIdent)
Main.hx:7: characters 18-24 : For function argument 'c'
```

**Comment by back2dos** [comment]
FWIW I can confirm that. I had practically the same error message during reification with EField this week. I thought it was due to total compiler abusal and chose to work around it.

**Comment by back2dos** [comment]
Sorry for the noise. Just wanted to add that I had the error on 3.2.1.

**Comment by Simn** [comment]
It's similar to #2148 and caused by this:

```ocaml
ctx.on_error <- (fun ctx msg ep ->
	(* raise Not_found only if the error is actually about the outside identifier (issue #2148) *)
	if ep = pc then
		raise Not_found
	else begin
		restore();
		ctx.on_error ctx msg ep;
	end
);
```

`ctx.on_error` receives "{ f : { name : String } } has no field name" and raises `Not_found` because the positions match due to reification. The problem is that it cannot tell if the error is actually about the identifier not being found.

The only obvious way I can see that would fix this is to check if the error message starts with "Unknown identifier". I'm reluctant to put something like this into our typer though.
