### ISSUE TITLE
statics with side effects and DCE

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4839]
Someone reported me the following issue today:

```
class Main {
     static var id = 0;
     public static var A = id++;
     public static var B = id++;
     static function main() {
          trace(B);
     }
}
```

With DCE full, this will trace 0 instead of 1, because of the removal of A.
We should force a keep on the static if it has some side effect. The problem is that new() can be considered a side effect, and we don't want to keep new Array() or new Map() for instance.

Any idea @Simn?

**Comment by back2dos** [comment]
All parts involved are variables. Is it then really reasonable to have expectations about the value of B here in the first place? And if yes, could this not actually be a desired result (e.g. if you want to generate as few ids as possible to consume space in some later representation that uses the id)?

The "proper" solution for this requires a macro, that will increment the counter at compile time:

```haxe
class Main {
  public static var A = Id.local();
  public static var B = Id.local();
}
```

The macro can use the `Context.getLocalType` to count from 0 for each new type. Added bonus: the variables can then be declared inline.

**Comment by Simn** [comment]
This is pretty much the same as #3916, just with statics.

**Comment by ncannasse** [comment]
@back2dos yes it is reasonable, statics are always initialized in-order
I confirms this breaks the "least surprise" behavior and want it fixed, I just don't know to which extend when there's a `new` involved.

It's actually quite a complex problem of dependencies if we look at it, because it would somehow mean to decide that B depends on A (dce wise).

What if we told that since we keep B, we will keep id, so any side effect on id has to be kept as well ?
That would still eliminate the three variables altogether if none is used.

**Comment by Simn** [comment]
I think that makes sense. I'll have to check how to implement that, maybe it's the right time to add a proper field-dependency-graph which the analyzer would appreciate as well.

Regarding `new`, we can use the same concept of purity that the analyzer uses in some places.

**Comment by back2dos** [comment]
@ncannasse If a whole class gets DCEd, you wouldn't want its static initialization side effects applied, would you? How is this any different?

The premise that "statics are always initialized in-order" is wrong because its generalization "statics are always initialized" does not hold under DCE. That is the point of DCE, is it not?

The only thing you can say is "statics are never initialized out of order" and this is true with DCE and without it.

Practically speaking, the change you propose will stop DCE from occurring in many places. Consider [this simplified example](http://try.haxe.org/#122A6)

```haxe
class Test {
    static function main() {
        trace(Pools.oranges.alloc().toString());
    }
}

class Apple {
    public function new() {}
}
class Orange {
    public function new() {}
    public function toString()
    	return 'Tasty Orange';
}
class Pools {
    static public var apples(default, null) = Pool.of(Apple);
    static public var oranges(default, null) = Pool.of(Orange);
}

class Pool<T> {
    var ctor:Void->T;
    function new(ctor) {
        this.ctor = ctor;
    }
    public function alloc():T {
        return ctor();//this is a bit of a lousy pool, yes
    }
    static var cache = new haxe.ds.ObjectMap<Dynamic, Dynamic>();
    @:generic static public function of<T:{ function new():Void;}>(c:Class<T>):Pool<T> {
        if (!cache.exists(c)) 
           cache.set(c, new Pool<T>(function () return new T()));
        return cache.get(c);
    }
}
```

As for your interpretation of the principle of the least surprise, it is quite a stretch. It should not come as a surprise that shooting your foot will cause damage to your foot. I maintain that code that uses variable initialization to cause side-effects relevant to code that *never* accesses said variable, misuses variable initialization. The example you posted is a clear-cut case of someone using the wrong tool for the job. When simply not asking for trouble as in this example, the current behavior is both more useful and more intuitive than what you propose.
