### ISSUE TITLE
Use top-down inference for function arity

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4852]
```haxe
class Main {
	static function main() {
		onClick = function() { }
	}

	static var onClick:String -> Void;
}
```

This currently fails with `Void -> Void should be String -> Void` which is generally correct. However, if we type a `function` against a function type of higher arity we could pad the missing arguments automatically so the user doesn't have to declare useless arguments by hand.

Any problem with that?

**Comment by ncannasse** [comment]
I'm not sure I understand. Are you proposing that this code should compile ?

**Comment by Simn** [comment]
Yes by transforming it to `onClick = function(_) { }`. This way users don't have to do that manually, which means they don't have to count the number of arguments and can't accidentally shadow a name by introducing function arguments.

**Comment by nadako** [comment]
This seems quite useful for node.js callbacks (it's about anon functions only, right?)

**Comment by Simn** [comment]
Yes only for EFunction, else we cannot pad the arguments easily.

**Comment by ncannasse** [comment]
TBH I don't like it very much. While I agree it would help for JS event binding, it only makes sense for this specific case and doesn't make much sense in terms of typing in general.

If for instance you refactorize some code by adding an extra parameter, you want to know where the function is bounded in order to process the new argument correctly, which requires a typing error.

I also think this cause some weird issues with type inference, for instance:

```
var f = function(_) {};
f = function() {}; // OK;

var g = function() {};
g = function(_) {}; // ERROR
```

Nothing new here, we have the same for Int/Float etc. But it becomes quite less natural with functions, maybe because I'm used to other cases.

**Comment by Simn** [comment]
I don't really see much of a problem with either of these cases, but then again this is not important enough for me to have lengthy discussions.
