### ISSUE TITLE
haxe.rtti.Classdef's meta field populated with quoted string values

### ISSUE THREAD

**Issue by JeriXNet** [HaxeFoundation/haxe#4858]
test case provided in [this SO-question](http://stackoverflow.com/questions/35440615/strange-quotes-in-meta-values-in-haxe)

**Comment by Simn** [comment]
This indeed looks weird, though it should be "just" a printing problem. That is, the quotes are not actually part of the string value.

**Comment by Gama11** [comment]
According to `charAt()`, they seem to be part of it though:

```haxe
package;

@:rtti
class TestClass
{
    @testMeta("test_val_0", "test_val_1")
    var testVar = 0;
}

class Main
{
    static function main()
    {
        trace(haxe.rtti.Meta.getFields(TestClass).testVar.testMeta[0].charAt(0));
        for( field in haxe.rtti.Rtti.getRtti(TestClass).fields )
            if( field.name == "testVar" )
                for( meta in field.meta )
                    if( meta.name == "testMeta" )
                        trace(meta.params[0].charAt(0));
    }
}
```

```
Main.hx:14: t
Main.hx:19: "
```

**Comment by Simn** [comment]
Come to think of it, it might make sense to have the quotes there because otherwise you couldn't distinguish `"test_val_0"` and `test_val_0`. Either way, it should be consistent.

So the quotes are part of the XML in the `__rtti` field?

**Comment by ncannasse** [comment]
I think you were only allowed constant data into runtime metadata

**Comment by Simn** [comment]
I totally ignored the fact that we are comparing two different concepts here: Metadata values and RTTI output. The RTTI output is supposed to have the quotes because it is used to generate documentation. We don't have the value itself but rather a string representation of the value. The metadata value on the other hand is an actual run-time value, which is why there are no quotes printed for it.

This means that there's no issue here.
