### ISSUE TITLE
Sourcemap generation is wrong sometimes

### ISSUE THREAD

**Issue by Neverbirth** [HaxeFoundation/haxe#4916]
Haxe mappings are not always right, for example if you download [these files](https://www.dropbox.com/s/fy89kl67b8xx7ih/sm.zip?dl=0), you'll see that for original line 26 (starting at 1), the generated line points to line 13 instead of 14.

**Comment by ncannasse** [comment]
@Simn could you look into it? improving the haxe mappings is quite important to get correct IDE debugger integration, which I hope is what @Neverbirth is working on :)

**Comment by Simn** [comment]
I could, but I know virtually nothing about JS source maps so there may be more suitable candidates for this.

**Comment by nadako** [comment]
@aduros knows about this, right?

**Comment by ncannasse** [comment]
Dan maybe you want to have a look? We need a new source map expert, I think Bruno is quite busy :)

**Comment by nadako** [comment]
>  I know virtually nothing about JS source maps 

This is true for me as well, but I'll try taking a look at it once I have a minute.

**Comment by nadako** [comment]
Sorry, I'm not sure where to look, the debugger seem to output correct lines:

![](http://i.imgur.com/BDBqjl6.png)

**Comment by Simn** [comment]
I think @RobDangerous had a case where it's not accurate.

**Comment by Neverbirth** [comment]
Mmmm, if you check out with

https://sokra.github.io/source-map-visualization/#custom
http://murzwin.com/base64vlq.html

And some others like Firefox, they all display problems. I can get a lot of other errors inside Chrome, but on some way bigger project.

**Comment by nadako** [comment]
Wow, judging by the vizualization, our source maps are really bad, I think I'll research this topic.:)

**Comment by Neverbirth** [comment]
I'll try to gather some more info too. I may be missing or overlooking something, but my tests are consistent with what I see in other places.

**Comment by ncannasse** [comment]
@nadako any news on this topic ? Would be nice to have some improvements already in for 3.3 :)

**Comment by nadako** [comment]
Not really, I read about sourcemap structure and tried those visualizers (to find out that TS and Coffee apparently do much better job with mapping), but I haven't got much time to dive deeply into it. Not sure I'll be able to improve on this for 3.3.

**Comment by nadako** [comment]
Here's something we could use for testing source maps: https://github.com/mozilla/source-map

**Comment by aduros** [comment]
There's definitely room for improvement with source maps. I probably won't be able to revisit it in time for 3.3.

That visualizer should help things immensely!

**Comment by nadako** [comment]
Yeah. I tried looking into it again and it seems that there's something wrong with expr positions to begin with, investigating further...

**Comment by Simn** [comment]
That wouldn't surprise me, I've been pretty sloppy when it comes to positions so the whole optimization stage probably messes them up somewhere.

**Comment by nadako** [comment]
I fixed a couple of issues and the source map [looks a bit better now](http://sokra.github.io/source-map-visualization/#base64,Ly8gR2VuZXJhdGVkIGJ5IEhheGUgMy4zLjAKKGZ1bmN0aW9uICgpIHsgInVzZSBzdHJpY3QiOwp2YXIgTWFpbiA9IGZ1bmN0aW9uKCkgeyB9OwpNYWluLm1haW4gPSBmdW5jdGlvbigpIHsKCXZhciBidXR0b24gPSB3aW5kb3cuZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgiYnV0dG9uIik7CglidXR0b24udGV4dENvbnRlbnQgPSAiQ2xpY2sgbWUhIjsKCWJ1dHRvbi5vbmNsaWNrID0gZnVuY3Rpb24oZXZlbnQpIHsKCQlNYWluLmxldmVsMSgpOwoJfTsKCXdpbmRvdy5kb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGJ1dHRvbik7Cn07Ck1haW4ubGV2ZWwxID0gZnVuY3Rpb24oKSB7CglNYWluLmxldmVsMigpOwp9OwpNYWluLmxldmVsMiA9IGZ1bmN0aW9uKCkgewoJdGhyb3cgbmV3IEVycm9yKCk7Cn07Cn0pKCk7CgovLyMgc291cmNlTWFwcGluZ1VSTD1iLmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYi5qcyIsInNvdXJjZVJvb3QiOiJmaWxlOi8vLyIsInNvdXJjZXMiOlsiRjovQ29kZS9zbS9NYWluLmh4Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7OztZQWFRLFdBQ1A7Q0FDb0I7Q0FDYixxQkFBcUI7Q0FDckIsaUJBQWlCLGdCQUN0Qjs7O0NBRUssaUNBQWtDOztjQUdsQyxXQUVOOzs7Y0FHTSxXQUVOO09BQU07Ozs7In0=,cGFja2FnZTsKCmltcG9ydCBqcy5Ccm93c2VyOwppbXBvcnQganMuRXJyb3I7CmltcG9ydCBqcy5MaWI7CgovKioKICogLi4uCiAqIEBhdXRob3IKICovCmNsYXNzIE1haW4KewoKCXN0YXRpYyBmdW5jdGlvbiBtYWluKCkKCXsKICAgICAgICB2YXIgYnV0dG9uID0gQnJvd3Nlci5kb2N1bWVudC5jcmVhdGVCdXR0b25FbGVtZW50KCk7CiAgICAgICAgYnV0dG9uLnRleHRDb250ZW50ID0gIkNsaWNrIG1lISI7CiAgICAgICAgYnV0dG9uLm9uY2xpY2sgPSBmdW5jdGlvbihldmVudCkgewoJCQlsZXZlbDEoKTsKICAgICAgICB9CiAgICAgICAgQnJvd3Nlci5kb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGJ1dHRvbik7CiAgICB9CgoJc3RhdGljIGZ1bmN0aW9uIGxldmVsMSgpOlZvaWQKCXsKCQlsZXZlbDIoKTsKCX0KCglzdGF0aWMgZnVuY3Rpb24gbGV2ZWwyKCk6Vm9pZAoJewoJCXRocm93IG5ldyBFcnJvcigpOwogICAgICAgICAgICB0cmFjZSgiSGF4ZSBpcyBncmVhdCIpOwoJfQoKfQ==), however there are still issues remaining with block expressions, it seems. Investigating if it's a `expr.epos` issue or source-map generation related.

**Comment by nadako** [comment]
Ok, positions do seem to be right, it's the source map generator not supporting multi-line expressions properly.

**Comment by nadako** [comment]
Okay, I added some awkward newline handling when printing a single expr and the source map now looks like [this](https://sokra.github.io/source-map-visualization/#base64,Ly8gR2VuZXJhdGVkIGJ5IEhheGUgMy4zLjAKKGZ1bmN0aW9uICgpIHsgInVzZSBzdHJpY3QiOwp2YXIgTWFpbiA9IGZ1bmN0aW9uKCkgeyB9OwpNYWluLm1haW4gPSBmdW5jdGlvbigpIHsKCXZhciBidXR0b24gPSB3aW5kb3cuZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgiYnV0dG9uIik7CglidXR0b24udGV4dENvbnRlbnQgPSAiQ2xpY2sgbWUhIjsKCWJ1dHRvbi5vbmNsaWNrID0gZnVuY3Rpb24oZXZlbnQpIHsKCQlNYWluLmxldmVsMSgpOwoJfTsKCXdpbmRvdy5kb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGJ1dHRvbik7Cn07Ck1haW4ubGV2ZWwxID0gZnVuY3Rpb24oKSB7CglNYWluLmxldmVsMigpOwp9OwpNYWluLmxldmVsMiA9IGZ1bmN0aW9uKCkgewoJdGhyb3cgbmV3IEVycm9yKCk7Cn07Cn0pKCk7CgovLyMgc291cmNlTWFwcGluZ1VSTD1iLmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYi5qcyIsInNvdXJjZVJvb3QiOiJmaWxlOi8vLyIsInNvdXJjZXMiOlsiRjovQ29kZS9zbS9NYWluLmh4Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7OztZQWFXLFdBQ1A7QUFBQSxDQUNpQjtDQUNiLHFCQUFxQjtDQUNyQixpQkFBaUIsZ0JBQ2I7QUFBQTs7Q0FFSixpQ0FBa0M7O2NBRy9CLFdBRUg7QUFBQTs7Y0FHRyxXQUVIO0FBQUEsT0FBTTs7OzsifQ==,cGFja2FnZTsKCmltcG9ydCBqcy5Ccm93c2VyOwppbXBvcnQganMuRXJyb3I7CmltcG9ydCBqcy5MaWI7CgovKioKICogLi4uCiAqIEBhdXRob3IKICovCmNsYXNzIE1haW4KewoKICAgIHN0YXRpYyBmdW5jdGlvbiBtYWluKCkKICAgIHsKICAgICAgICB2YXIgYnV0dG9uID0gQnJvd3Nlci5kb2N1bWVudC5jcmVhdGVCdXR0b25FbGVtZW50KCk7CiAgICAgICAgYnV0dG9uLnRleHRDb250ZW50ID0gIkNsaWNrIG1lISI7CiAgICAgICAgYnV0dG9uLm9uY2xpY2sgPSBmdW5jdGlvbihldmVudCkgewogICAgICAgICAgICBsZXZlbDEoKTsKICAgICAgICB9CiAgICAgICAgQnJvd3Nlci5kb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGJ1dHRvbik7CiAgICB9CgogICAgc3RhdGljIGZ1bmN0aW9uIGxldmVsMSgpOlZvaWQKICAgIHsKICAgICAgICBsZXZlbDIoKTsKICAgIH0KCiAgICBzdGF0aWMgZnVuY3Rpb24gbGV2ZWwyKCk6Vm9pZAogICAgewogICAgICAgIHRocm93IG5ldyBFcnJvcigpOwogICAgICAgICAgICB0cmFjZSgiSGF4ZSBpcyBncmVhdCIpOwogICAgfQoKfQ==).

Still not very pretty and I think it'll require much more work to get it it completely right, but it should be better than before.

Could interested parties please check out the latest development version and see if there any more issues with it?

PS @Simn also check out that source map, there's something wrong with `var button = ...` and I think that one is because expr position is wrong.

**Comment by Simn** [comment]
You're right, try now.

**Comment by nadako** [comment]
Looks better now, thanks!

**Comment by Neverbirth** [comment]
Nice, thanks for the improvements, I've been playing a bit with a night build. Sadly it's still not as useful as it should, maybe you didn't notice (sorry if you did), if you check the first line inside each function, the mapped generated information maps to the start of the function block, ie: the opening bracket that may be in the previous line, so it's still a problem for the end developer.

**Comment by nadako** [comment]
Hmm, I thought it's not a problem because the actual generated expression on the next line is also mapped to the corresponding hx position...

**Comment by Neverbirth** [comment]
I will try to make some more checks, but I would say it's a problem. Maybe taking into account the end position on my side could improve things, but I think it shouldn't be needed, last I read in the topic a lot of libraries and programs don't even bother to calculate it.

**Comment by Neverbirth** [comment]
Sorry for not replying before. After making some more tests it turns out to not be a big deal, at least during my small tests.

**Comment by nadako** [comment]
Nice! Unless I'll have some more free time, I'd say let's keep it like this for 3.3 and then work on make sourcemaps perfect for 3.4.

**Comment by Simn** [comment]
What's the status here?

**Comment by Simn** [comment]
I'll go ahead and close this as there hasn't been any activity. If there's still an issue, feel free to reopen.
