### ISSUE TITLE
[cpp] "undeclared identifier" accessing field of member with type from type param

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5026]
```haxe
class Main<T:Foo> {
	public static function main() {}

	public var foo:T;

	public function new() {
		foo.test();
	}
}

class Foo {
	public function test() {}
}
```

```
./src/Main.cpp(11): error C2039: 'Foo': is not a member of '`global namespace''
./src/Main.cpp(11): error C2065: 'Foo': undeclared identifier
./src/Main.cpp(11): error C2227: left of '->test' must point to class/struct/union/generic type
./src/Main.cpp(11): note: type is 'unknown-type'
```

Regression.

**Comment by nadako** [comment]
seems to be a missing include

**Comment by Simn** [comment]
I've seen this issue before but I can't find it right now. It should indeed be a matter of a missed dependency because a recursion into the type parameter constraints is missing.

**Comment by hughsando** [comment]
The old code made foo a dynamic, so it did not need the header.
I fixed a similar version of this  interfaces, and think I will do the same for these variables.
I could try the keep the types stronger, but I'm not really sure what the difference is between "some T that is a type of Foo restriction" rather than just "Foo" - but if the developer wants some difference, they can have dynamic.
