### ISSUE TITLE
[cpp] instance function comparison is broken in release builds

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5068]
```haxe
class Main {
	public static function main() {
		new Main();
	}	
	
	public function new() {
		var a = [foo1, foo2];
		trace(a.indexOf(foo1));
		trace(a.indexOf(foo2));
	}
	
	function foo1() {}
	function foo2() {}
}
```

This traces:
- `0, 1` on Haxe 3.2.1 as expected (regardless of `-debug`)
- `0, 1` on dev as expected (with `-debug`)
- `0, 0` on dev without `-debug` **(!)**

**Comment by Simn** [comment]
I'm not sure if that's defined.

**Comment by Gama11** [comment]
I think we had to do some hackery with `Reflect.compareMethods()` for `FlxSignal` (where this was isolated from) for Neko only.

Either way, shouldn't it at least be consistent with and without `-debug`?

**Comment by Gama11** [comment]
Also, `Reflect.compareMethods()` doesn't work here either:

```haxe
class Main {
	public static function main() {
		new Main();
	}	
	
	public function new() {
		trace(foo1 == foo2);
		trace(Reflect.compareMethods(foo1, foo2));
	}
	
	function foo1() {}
	function foo2() {}
}
```

Traces `true, true` in release and `false, false` in debug.

**Comment by ncannasse** [comment]
That's a hxcpp error right ? @hughsando the result of method comparison should not change between debug/release.

**Comment by ncannasse** [comment]
But yes, the result of == (used by indexOf) is unspecified (but should not be random :) ) using Reflect.compareMethods should work (return true if same function, false either)

**Comment by hughsando** [comment]
This one is actually quite funny.
I added an optimization to remove "virtual" on functions that are not actually event overridden, which seems pretty sensible.
But now the compiler, in release mode, actually uses *exactly* the same function for foo1 and foo2, since they are exactly the same.   It seems a shame to disable these optimizations, or add extra data to all closures, just to get "==" to work.
The issue is only "*identical* instance function comparison is broken in release builds", I will have to think how to fix this with minimal overhead.

**Comment by Simn** [comment]
Isn't it fair to leave `==` unspecified? I'd be fine with it as long as compareMethods works.

**Comment by hughsando** [comment]
same problem.

**Comment by Simn** [comment]
Ah, well, we'll have to address that unfortunately.

**Comment by ncannasse** [comment]
Yes, I think that optimization creates more issues than it fix things.

**Comment by hughsando** [comment]
Well, there is my optimization, and the compilers.  Mine could be a pretty
big win in some cases (I wonder if this existed in static functions in
3.2.1?).  I could try to prevent the compiler for doing theirs - I'm pretty
sure there are some flags for it, but it could be a pain since we support
quite  a few compilers.
But I think I will add the function name to the closure class - this will
have the benefit of making  trace look nicer, but it will make the exe
slightly bigger.

**Comment by hughsando** [comment]
It added about 1% to the size of the unit tests, and you get the function name when you trace it out, so I think this is quite a nice fix.
