### ISSUE TITLE
Fix haxe.Utf8.validate for neko, cpp, macro

### ISSUE THREAD

**Issue by mandel59** [HaxeFoundation/haxe#5096]
This test should pass:

``` haxe
haxe.Utf8.validate("\xf0\xa9\xb8\xbd\xe3\x81\xc3\xab\x61") == false;
haxe.Utf8.validate("\xc0\xaf") == false; // redundant sequence
haxe.Utf8.validate("\xed\xa0\x80") == false; // surrogate byte sequence
haxe.Utf8.validate("\xed\xbf\xbf") == false; // surrogate byte sequence
haxe.Utf8.validate("\xf4\x90\x80\x80") == false; // U+110000
```

**Comment by Simn** [comment]
Thanks, I was about to open this issue too!

**Comment by nadako** [comment]
Who is responsible for this? Are doing this for 3.3?

**Comment by nadako** [comment]
Assigning to @ncannasse as he was talking about unicode support at last WWX :-P

**Comment by ncannasse** [comment]
PR please ?

**Comment by ncannasse** [comment]
I made a PR for neko here:
https://github.com/HaxeFoundation/neko/pull/146
It uses pretty good code as described here:
http://bjoern.hoehrmann.de/utf-8/decoder/dfa/
However I'm a bit reluctant to merge such copyrighted code in there.

Also, it would require to be ported to OCaml instead of using Utf8.validate in macro code.

**Comment by frabbit** [comment]
@ncannasse  this is a milestone 3.3 issue, is this still relevant for a release?

**Comment by ncannasse** [comment]
I think it can wait for full unicode support ;)

**Comment by Simn** [comment]
haxe.Utf8 has been deprecated, so this issue is obsolete.
