### ISSUE TITLE
Multireturn

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#5114]
As @jdonaldson mentioned [here](https://github.com/HaxeFoundation/haxe/issues/4300#issuecomment-210232975), multireturn functions would be a great plus for externs:

> It would allow for more natural extern support on the languages that use them in core libraries. It's currently impossible to get Haxe to deal with multivalue return functions in a first class way. You either have to wrap the result somehow (which adds overhead), only type/provide the first argument (which ends up losing info on the other values returned), or use magic methods (and give up communicating anything about the type).

There were various ideas using types to do the trick. That opens a can of worms though, e.g. how to deal with `Array<MultiReturn<Int, Float, String>>` and what not.

An alternative would be to allow for a `@:multireturn` metadata. That is, if this is really just for externs.
For starters callers could use switch statements for destructuring, e.g.:

``` haxe
switch methodThatReturnsIntAndString() {
  case [4, "foo"]:
  case [i, s]:
}
```

It would also be possible to allow users to perform multireturns by treating array literals as tuples (like in switch statements) in `@:multireturn` functions. Example:

``` haxe
class Foo implements NativeFoo {
   @:multireturn((_:String))
   function methodThatReturnsIntAndString():Int {
      return [5, "bar"];
   }
}
```

Whether or not that should be a general language feature (emulated on platforms that don't have it) is a question worth considering, too. For now, I guess getting it right for specific targets (lua in particular) is a good place to start.

**Comment by Simn** [comment]
Is multireturn actually different from "returning a tuple"?

**Comment by back2dos** [comment]
Conceptually, for me a tuple is a value and it has a type. So I can do `someArray.push(functionThatReturnsTuple())`. The particular solution I am proposing is to have multiple individual values and force the user to deal with them.

But if by "tuple" you don't actually mean a first-class value and more something like the thing that we switch over, then sure, they are practically the same.

Otherwise, the the difference even shows at runtime, that is if the environment supports it. In one case you get multiple values back on the stack, in the other case you get one compound value (that needs to be allocated etc.).

**Comment by jdonaldson** [comment]
Good call on making this a separate issue.  

The pattern matching techniques here are nice, and I hadn't properly thought them out.  I think we'll need to support them to have reasonable "switch" semantics, but I'm still not clear on how useful they'll be.  Most of my multiple return value situations are "flat" and comprised of 1-3 values, vs the more complex ADTs that can be nested, etc.

The next question is whether to make tuples/multiple-returns a general Haxe feature, or something only available as an extern feature.  Part of my hesitation there is that I'm not sure that both concepts are 100% equivalent.... or... if after we support tuples we'll still need to support multiple return values a separate way.  FWIW, I typically see tuples and destructured assignments used in *dynamic* languages, where passing and returning basic value types are encouraged (instead of object or container wrappers).  I'm not sure how useful tuples and destructured assignment will be in the world of Haxe.

Finally, if we're going to communicate the fields of a tuple using some haxe-friendly proxy structure, I think strong arguments can be made for a typedef'd anonymous object (rather than put the additional fields in metadata labels).  The typedef'd anonymous object fields can take on the names of the tuple variable names, and everything will play well with IDEs and basic type hinting done by the compiler.

So, I'm personally leaning towards making multiple returns distinct from tuples, and provide them as extern-only features for the languages that support them.  That's just my 2 cents so far though, keep the discussion going.

**Comment by kobi2187** [comment]
```
var (pos, len) = getNextMatch();
function getNextMatch() : (Int, Int) {}
```
this is very similar to anonymous structures.
in fact, it is just a subset of them. no names.
a step in the way can be: `return ({ _:3, _:2 });
which sugared, will look like: return (3,2);
there is another way with arrays, but it involves dynamic and misses on the type safety.

this actually opens interesting possibilities in macros and code generation.
the called function can convert arrays to tuples, and return to variables. for example easy initialization of many variables.

**Comment by jdonaldson** [comment]
Yeah, multiple variable initialization is easier in some sense, but you'd still be making the user look up the return values of the multi-return method, and name them appropriately.    Taken to an extreme, I find this:

```haxe
var pos, len, arg1, arg2, someAttribute, etc = getMultiReturn()
trace(someAttribute);
```
Much harder to deal with than:
```haxe
var ret = getMutliReturn();
trace(ret.someAttribute);
```

@back2dos brings up a good point though, passing around these multi-return type objects would only be appropriate for methods that can accept haxe.extern.Rest<T>.  You wouldn't want to pass them directly to an array.push for instance, the behavior would be undefined (some platforms let you do the equivalent of array.push(1,2,3,4), some require pushing one value at a time).  Maybe that's an indication that they should implement some kind of haxe.extern.MultiReturn<T> that extends Rest<T>?

**Comment by kobi2187** [comment]
@jdonaldson my personal opinion is that getting vars easiliy helps you keep your train of thoughts, instead of destructuring and long typing.  usually you would use 2 or 3 vars. it can also serve a role similar to the result enum.
i don't find it harder, and the compiler will help you when types don't match.
maybe the function signature should include names for the returning vars, just to aid the programmer understanding at a glance what is returned.
wrt array+multivars, it depends on the definition: 
for example, more vars than array length, extra vars are null. 
less vars than array length, the last one gets what remains of that array.
when users know what to expect it will not be a problem.

**Comment by back2dos** [comment]
@jdonaldson Sorry, the multiple cases in my code were probably distracting. I just meant to point out that the noise of the switch statements comes with at least some rewards. Particularly in cases where you get something like error and data (as in nodejs callbacks) this might actually look rather nice.

My reason for suggesting switch here is that for them we seem to have some concept of "transient" n-ary tuples in the compiler and to me that seems like an exact fit for expressing the notion of native multireturn semantics. It doesn't allow them to escape anywhere, much like this code [will not compile](http://try.haxe.org/#23677):

```haxe
switch [1, 2] {
  case a: // Error: Pattern should be tuple [Int,Int]
}
```

I think not allowing to pass multireturn "tuples" around is a good starting point, as it sidesteps the question of how they should be represented. Only the backend will know that. I was looking for a solution that works without introducing a new kind of type or giving some particular `MultiReturn` special treatment by the compiler, as @Simn voiced some concern over those kinds of hacks recently.

I'm all for having a well-designed solution for tuples that composes and decomposes them without hassle and what not, but I think that might be better to look at in the context of Haxe 4.

**Comment by jdonaldson** [comment]
Supporting the typical [error,data] callback result of node I think is a great first class use-case for this.

I suppose one other way of representing this would be : 

```haxe
switch mr {
   case {error : null, data = d} : // proceed with data in d
   case _ : // throw error, or handle error.
}
```

This goes back to the notion of representing multiple returns as anonymous objects somehow.  I like the ability to put names on each value.  It's a bit of a hack onto anonymous objects and structure types (since they don't typically give guarantees on ordering of fields), but it's a hack we can easily turn into a first class feature if it works out.  I find that to be a little clearer, and friendlier to refactoring.  Granted, it is more verbose.

We can also prevent multireturns from getting passed around.  That's probably safest for now.

Also, I agree that further discussion on advanced decomposition techniques are really out of scope for this feature.  Those advanced techniques are going to require broad support across all the targets, and involve a lot of compiler work.  I really don't want to pin multi-return support on that unless we're certain it's a proper subset.

**Comment by underscorediscovery** [comment]
The idea of transforming multiple return values into an anonymous object automatically isn't as ideal on GC targets (like in lua this would be an explicit action, table.pack/table.unpack). Especially if it can be represented as separate values, though without closures and wrapping it's unclear how that may work in implementation detail. I'd be curious on the approach in mind? 

Anyway language wise, I much prefer the open variables vs structure.

`var a, b = fn();`
This also allows for ignoring while structures/singular objects don't:
`var _, b = fn();`

**Comment by back2dos** [comment]
The main problem with that is that `var a, b = fn();` already has a meaning.

As for wrapping it in an anonymous object, if it occurs at the call site, it needn't cause a GC overhead, since the compiler should then be able to inline the temporary anonymous object.

**Comment by ncannasse** [comment]
As @underscorediscovery said, I'm against any solution that would involve having hidden allocations being made.

This is not easy to solve, because not all platforms have by-reference parameters. In that case, you need a anonymous object but you cannot allocate it at call site or you also doing an hidden allocation. 

You could have a static singleton preallocated for it, but this break both reentrancy and mulithreading. I'm not sure there is an actual cross platform no-allocation solution for it.

**Comment by jdonaldson** [comment]
One way of avoiding hidden allocation while allowing reentrancy and multithreading is preallocating the anonymous containers per-thread rather than globally as a singleton.

That's a pretty deep rabbit hole though, and my 2 cents is that I still don't see multi-return or destructuring assignment as a big enough win that we need every platform to support it as a first class feature.

**Comment by ncannasse** [comment]
If it becomes a language feature then it is necessary to have it
implemented efficiently on all platforms, that's the promise we make with
Haxe users.
Le 21 avr. 2016 20:17, "Justin Donaldson" <notifications@github.com> a
écrit :

**Comment by jdonaldson** [comment]
I don't have anything new to add, but I'm hoping we can continue the conversation.

I agree 100% that this is about efficiency, and if we provide something general purpose it needs to serve all targets equally well.  

However, I have to admit I'm at a bit of a loss on how to go about introducing new AST changes to the Haxe language that permits multiple returns (and how to implement low cost runtime wrapper logic for targets that don't natively support multiple returns).

**Comment by kobi2187** [comment]
isn't it the premature optimization pitfall? even if you guys decide to implement with arrays or custom data structures like Pair, bag, ..
it will still be very much progress. using portable convenient high level haxe code, and targetting multiple languages is a good thing.

**Comment by mikesmullin** [comment]
i guess this is working fine right now

```
@:multiReturn extern class OsExecute {
	var success : Bool;
	var output  : String;
	var status  : Int;
}
```

**Comment by ncannasse** [comment]
Closing for now, my arguments still stand.

**Comment by back2dos** [comment]
Is it correct that your argument is: it may cause hidden allocations on some targets, therefore it must not be added to the language? Should we then remove variable capturing from the language? I don't think so.

Also, you have it the wrong way around:

1. If someone wants to return multiple values, they will wrap it in an object anyway. So the allocation becomes necessary. They will also probably use an anonymous object for succinctness, which makes matters worse on static platforms. So one way or the other, the allocation will take place.
2. On platforms where multireturn is possible (either by actually returning multiple values directly or returning something like a stack-allocated struct), code can be generated that skips all allocation.

With this feature added, there will not be more allocations on any target (because when someone needs to return multiple values, they will do the allocation anyway). On some targets code can be transparently generated that skips the allocation, without laying the problem at the feet of the programmer.

**Comment by danielo515** [comment]
So why was not this implemented just for targets that support it natively? Lua already allows multi return for externs, and in order to properly communicate with the external Lua we need to be able to return multiple values. Can this be reconsidered with a more constrained approach ?
