### ISSUE TITLE
Field ... has no expression (possible typing order issue)

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#5134]
One thing @nadako previously mentioned, I have narrowed down something that causes the same type of error message.

The source of the error has to do with `@:generic` and `inline`, it seems that when the two are combined it can trip completion. I frequently see this error around but haven't managed to reproduce it reliably until now, so hopefully it will be easier to track the cause.

```haxe
@:generic
class A<T> {
    var items:Array<T>;
    public function new() {
        items = [];
    }
    inline public function get(_index:Int) : T {
        return items[_index];
    }
}

class Test {

	var a: A<Int>;
    
    function new() {
		
    }
    static function main() {
        trace("Haxe is great!");
		//a //add . after a 
        //since try.haxe runs completion from inside comments
        //even typing a dot here will trigger the same error
    }
}
```

```
Test.hx:8: lines 8-10 : Field get has no expression (possible typing order issue)
Test.hx:13: characters 0-5 : Defined in this class
Test.hx:15: characters 1-15 : While building A_Int
Test.hx:13: characters 0-5 : Defined in this class
Test.hx:5: lines 5-7 : Field new has no expression (possible typing order issue)
Test.hx:13: characters 0-5 : Defined in this class
Test.hx:15: characters 1-15 : While building A_Int
Test.hx:13: characters 0-5 : Defined in this class
```

Here is the try.haxe version http://try.haxe.org/#9Da5C

**Comment by Simn** [comment]
I was looking at a case like that for quite a bit yesterday. The problem with display mode is that the compiler tries to avoid a lot of typing in order to speed things up, but in some cases that might lead to fields or expressions missing.

I'm thinking that we should simply not expand `@:generic` at all in display mode. This would not only avoid these problems but also avoid some unnecessary typing. We tried that yesterday but @nadako had some errors which may or may not have been related.

**Comment by nadako** [comment]
We should look into those errors, disabling `@:generic` for display makes much sense to me.
