### ISSUE TITLE
[display] can't position/type queries don't work for `super`

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5149]
See title. If we hover `super` right now, we get the `Cannot use super as value` error.
```haxe
class Base {
    function new() {}
}

class Main extends Base {
    function new() {
        super();
    }

    static function main() {
    }
}
```

**Comment by Simn** [comment]
I'm not sure if this should show the base class or the base class constructor.

**Comment by nadako** [comment]
Not sure too, considering that `super` can appear not only in constructor, maybe it makes sense to point to the class.

**Comment by Gama11** [comment]
Showing the base class constructor seems more intuitive to me in this example.. Maybe the `super` in `super()` and `super.method()` need to be treated differently?

**Comment by Simn** [comment]
Even `super.method()` can be a bit confusing: You already get to the overridden method on the `method` part of it, but the `super` part might actually lead you to a different class because the method could be defined in an ancestor of the direct parent class. It's not clear if this is correct or if it should take you to the class that actually defines the field.

**Comment by Simn** [comment]
I left it at direct super class for now. Going to the defining class is basically implicitly achieved by going to the overridden method anyway.
