### ISSUE TITLE
support @:deprecated for function arguments

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5151]
Now when we have argument metadata, we can support this. i tried looking into this, but with all argument-skipping and `TFun` vs `TFunction` business it's not that easy to do, so I'm creating this issue as a reminder.

**Comment by Simn** [comment]
I find this feature too obscure and too tricky to implement. It would also not be very robust because it would only work if you make a direct call, not if you create a closure or call the field through some other abstraction. It's similar to call-site default-value handling which we don't do in Haxe for similar reasons (and because it gets really stupid with dynamic dispatch involved).

**Comment by kLabz** [comment]
Has the situation changed, or is it still that complicated to implement?

With new overloads, there's a workaround that seems to handle most cases:
https://try.haxe.org/#BEd82746

```haxe
class Test {
  static function main() {
    foo();
    foo(1); // Warning : bar argument is deprecated
  }
  
  @:deprecated('bar argument is deprecated')
  overload static extern inline function foo(bar:Int):Void _realFoo(bar);
  overload static extern inline function foo():Void _realFoo();
  
  @:native('foo') @:noCompletion
  static function _realFoo(?bar:Int = 42):Void trace(bar);
}
```
