### ISSUE TITLE
Reflect.hasField fails on flash for type names

### ISSUE THREAD

**Issue by ciscoheat** [HaxeFoundation/haxe#5215]
```haxe
class Test 
{
    static function main() {
        var input = { int: 1001, test: "test" };

        trace(Reflect.hasField(input, "int")); // false
        Reflect.setField(input, "int", 1001); // now hasField will return true
    }
}
```

It seems to work on every other target.

**Comment by Simn** [comment]
Yes that can happen if you use identifiers which are keywords or reserved for other reasons on the target. We could try working around this somehow, but I don't think that'd be worth it because you would hit this restriction in other places too.

**Comment by ciscoheat** [comment]
Ok, if it's a known issue then I can change that field name, no problem. Thanks! (Leaving this open, but close if you like)

**Comment by kevinresol** [comment]
On python, keywords are [specially handled](https://github.com/HaxeFoundation/haxe/blob/4c6484ef32e44c29c300350d588f7d0cd2aca12e/std/python/_std/Reflect.hx#L38)

Maybe flash need to do so too?

**Comment by nadako** [comment]
Let's look at this for 3.4

**Comment by ncannasse** [comment]
Some special platform keywords are escaped in structures or classes. In that case reflection is affected in unspecified ways.

**Comment by kevinresol** [comment]
That means the user has to know about the specifics of the target platform, which IMHO violates Haxe's motto of "One Language, Everywhere". Platform keywords should be escaped by `__hx_` (or anything, as long as it is consistent across platform). So as a Haxe user, I don't need to care about the platform-specifics, but only need to be aware not to declare anything starts with `__hx_`, because it is reserved by haxe.

**Comment by ncannasse** [comment]
In Haxe specification, both in terms of language and std library, we need to leave some things unspecified in order to still keep native performances. This is one of them.
