### ISSUE TITLE
Inline function type parameters escape their context

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#5229]
The following code fails:

```haxe
class Main {

  static function main() {
    var arr = ["hello","world"];

    var __iterator = null;
    {
      inline function setIterator<T>(?iterable:Iterable<T>, ?iterator:Iterator<T>) {
        __iterator = iterable != null ? iterable.iterator() : iterator;
      }
      setIterator(arr);
    }

    while (__iterator.hasNext()) {
      var elt = __iterator.next();
      trace(elt.length);
    }
  }

}
```

With:
```
Main.hx:16: characters 12-22 : inline_setIterator.T has no field length
```

This is a regression.

**Comment by Simn** [comment]
This might be the expected behavior if we strictly follow typing order top-to-bottom. I'm not sure why it worked differently in 3.2.1.

It's a strange case: You unify a general type with the `__iterator` monomorph when assigning to it inside the `setIterator` function, and then you expect it to have a concrete type at the bottom. It's quite similar to #3033.

**Comment by waneck** [comment]
I'm not sure I understand. As far as I'd expect, the inline function type parameters should never escape its context. Also, even in top-bottom order, by line 16 it should already be typed correctly, shouldn't it?

**Comment by Simn** [comment]
I think leaking the type parameters is actually less of a problem than leaving random monomorphs around. This is probably caused by https://github.com/HaxeFoundation/haxe/commit/fb39918ae55b7c6ae2b4da163631d6a45000cc71 which fixed some insane type inference bugs.

Your assignment to `__iterator` within the inline function is pretty much asking for the type parameter to be leaked. The only way to avoid that is to bring back the type mapping of outside variables when inlining, but that would bring back the problems mentioned in https://github.com/HaxeFoundation/haxe/pull/3888#issuecomment-159412099.

**Comment by Simn** [comment]
On a side note, your example fails on 3.2.1 if you make it a non-inline function. I think it's good to be consistent here.

**Comment by waneck** [comment]
I reckon the problem. However, even if I can get it to compile (by taking of any usage of that var), the type parameters escape their context, generating some invalid code:
```
					[Local __iterator(2776):Iterator<inline_setIterator.T>]
```

So this would generate invalid code on platforms like java/c# which care about type parameters. I'm fine with that snippet not working, but I don't think we should ever leak the type parameters. What do you think?

**Comment by Simn** [comment]
That's a known issue, see #3033.

**Comment by waneck** [comment]
Alright then!
