### ISSUE TITLE
Error: Invalid SWF version X

### ISSUE THREAD

**Issue by peteshand** [HaxeFoundation/haxe#5262]
Following on from this issue: https://github.com/HaxeFoundation/haxe/issues/3628
How I can run a project with <app swf-version="X"/> set to anything higher than 17?
AIR is currently at 21, so I was expecting if I used the GIT version of Haxe 21 would supported... is this possible? or is there another way to manually set the AIR/Flex sdk? It would really handy if this could be set externally.

**Comment by nadako** [comment]
It looks like version support has to be added to haxe itself: https://github.com/HaxeFoundation/haxe/blob/development/src/typing/common.ml#L892

I'm not sure if this can be avoided or not, but I think latest haxe should support current flash runtime versions, so I'm assigning this to @ncannasse and setting 3.3 tag.

**Comment by Justinfront** [comment]
Note that if can modify a header using format library if you want a quick work round, and use dynamic to hack round access of new features.
https://github.com/HaxeFoundation/format/blob/master/tests/swf/Test.hx#L27
https://github.com/HaxeFoundation/format/blob/master/format/swf/Data.hx#L69
But perhaps you will need to do this in Ocaml because of 
https://github.com/HaxeFoundation/haxe/blob/development/extra/extract.hxml

**Comment by peteshand** [comment]
Could we change it to something like

pseudo code:
if (swf-version >= 12.0) return cast(swf-version, Int) + 11;

This way it wouldn't need to be used every AIR update
