### ISSUE TITLE
[neko] Utf8.compare is still broken

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#5308]
#4396 doesn't seem to have completely fixed the issue. Tested with Haxe 3.3.0rc1 and Neko 2.1.

````haxe
class Test extends haxe.unit.TestCase {

    static function main() {
        var runner = new haxe.unit.TestRunner();
        runner.add(new Test());
        runner.run();
    }

    function testUtf8Compare() {
        assertEquals(-1, haxe.Utf8.compare("a", "b")); // returns 1 on Neko
        assertEquals( 0, haxe.Utf8.compare("a", "a")); // works
        assertEquals( 1, haxe.Utf8.compare("b", "a")); // returns -1 on Neko
    }
}
````

**Comment by ncannasse** [comment]
Bad news, it seems it's been inverted. We can either fix that in the neko natives, but that would require a new Neko release, or simply insert a minus into the haxe implementation. @andyli what's your take on it?

**Comment by back2dos** [comment]
The current implementation only compares the strings by characters rather than bytes, which leads to exactly the same result.

If two characters are equal, then their byte representation is equal.
If a > b and they need equal amounts of space, then from left to right all their bytes are equal until one byte in a is greater.
If a > b and a needs more space, then it's leading byte will have more leading bits set, making it greater than b's leading byte.

The whole point of having comparison operators for unicode is to deal with at least with [equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence) if not collation also. We're doing no such thing, only doing some fancy branching that leads to the same conclusions as bytewise comparison (which is not surprising, because if you look at the current implementation, all it actually does is bytewise comparison of bytes that would have been compared anyway). Another explanation is here: http://stackoverflow.com/questions/18329781/will-strcmp-compare-utf-8-strings-in-code-point-order

So what I am saying: Unless you actually inspect the semantics of the characters (which is a Pandora's box), string comparison will be a simpler, faster and correct implementation. The only thing to do would be to leave it explicitly unspecified how the function behaves on invalid utf8-strings.

**Comment by andyli** [comment]
I haven't looked into the unicode details, but if a fix in Neko is needed, we can release a new Neko version, which I want to do so anyway since we need https://github.com/HaxeFoundation/neko/commit/a8c71ad97faaccff6c6e9e09eba2d5efd022f8dc to correctly package Haxe 3.3.

**Comment by ncannasse** [comment]
@back2dos that makes sense, the idea was first to put in place a char-by-char comparison, and later extend it with more information.

**Comment by ncannasse** [comment]
Fixed https://github.com/HaxeFoundation/neko/commit/8b56f432d59969eed53722528e8e693f92ce6697
