### ISSUE TITLE
[js] Reflect.setProperty(): Local variable tmp used without being initialized

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5320]
This is related to the compilation server.

```haxe
class Main
{
    static function main()
    {
        var o = {};
        Reflect.setProperty(o, 'test', 1);  
    }
}
```
```
-cp src
--connect 6115
-main Main
-js bin/test.js
```

How to reproduce:

0. start haxe server at port 6115
0. compile
0. edit something in the source code (add a space for example)
0. compile

Error:
`Local variable tmp used without being initialized`

**Comment by Simn** [comment]
This is much harder to address than it should be...

**Comment by kevinresol** [comment]
From these issues I learned: @Simn doesn't like the compilation server. :stuck_out_tongue: 

Just joking. But so far I haven't been able to actually use the compilation server due to these bugs. Is the compilation server a stable feature yet?

**Comment by nadako** [comment]
> @Simn doesn't like the compilation server. :stuck_out_tongue:

hehe, what else is new?

**Comment by ncannasse** [comment]
I and whole team are using the completion server on a daily basis, works very well for us (flash plaform for now), and I have it activated for JS projects as well (CastleDB for instance). Didn't try much on other plaforms, it's not easy to unit test it.

**Comment by kevinresol** [comment]
Isn't the test just a few steps? I.e. Start the server, compile twice, then shutdown the server?

**Comment by Simn** [comment]
At the very least you have to touch a file so it recompiles, else the second step does nothing. If you want to set up a small test system for it, go right ahead!

This issue itself is still a bit of a problem for me. Unfortunately the local-var-inits check is not as smart as the analyzer in this situation. Ultimately I want to integrate it there, but for 3.3 we'll need some sort of temporary solution.

**Comment by kevinresol** [comment]
Here is a working test for this particular issue.
https://github.com/kevinresol/test-compilation-server

It is currently a standalone test. I haven't got the time yet to look into the structure of Haxe's test suite. It would be nice if @andyli can give me some guidances or even give me a hand to integrate it into the current test suite.

**Comment by Simn** [comment]
I still don't have a solution for this, so I'll take a bit about the problem itself instead. Basically this is what happens:

1. First compilation
  * inline Reflect.setProperty
  * check local vars initialization
  * optimize
2. Second compilation
  * inline previously optimized version of Reflect.setProperty
  * check local vars initialization
  * fail

The reason it fails is that the analyzer transformed the expression of Reflect.setProperty to this:

```
var tmp;
var tmp1;
if ((o.__properties__)){
	tmp = o.__properties__["set_" + "test"];
	tmp1 = tmp;
} else tmp1 = false;
if ((tmp1))o[tmp](1) else o["test"] = __define_feature__("Reflect.setProperty",1);
```

It doesn't reconstruct the original `&&` expression because there's a block involved which should not be put in value places (technically this block is unnecessary here, but that's not the actual issue). We can tell that `tmp` is only being used if `tmp1` is true and that if `tmp1` is true `tmp` has a value. However, the var initialization checker does not see that.

Ideally, the local var initialization check should be done as part of the static analysis, but that's not something I could just change without a lot of thought.

I'm starting to think that we should not optimize the expressions of inline functions at all, under the assumption that their inlined expressions is going to be optimized anyway.

Any thoughts?

**Comment by ncannasse** [comment]
disable analyzer on inline functions?

**Comment by Simn** [comment]
Well, that's what I suggested as well.

**Comment by Simn** [comment]
However, this would only work if we make sure not to actually generate these inline functions. If we ignore the analyzer completely they might retain evil constructs like blocks in value places which targets like hxcpp are going to choke on. This would make compilation success depend on the DCE setting, which is not really an option either.

You're gonna hate this, but I think we should add a reverse dependency from the call-site module to the inline function module.

**Comment by ncannasse** [comment]
There's still a problem in case inlining is canceled which can happen for various reasons (such as recursion)

**Comment by Simn** [comment]
Well, if it's canceled the original problem doesn't occur anyway. But yes we should only set the dependency if the inlining is actually completed.

**Comment by ncannasse** [comment]
Another option : apply the analyzer but keep the unanalyzed texpr somewhere so it gets reused when inlining instead of the analyzed one

**Comment by Simn** [comment]
I thought about that too but got stuck on the "somewhere" part.

**Comment by ncannasse** [comment]
could be a new meta, but since we cannot have Ast depend on Type it requires some additional trick:
```haxe

type strict_meta =
...
| TExpr of (unit -> unit)


in Type:

let expr_ref = ref None
let make_expr_meta e = TExpr (fun() -> expr_ref := Some e)
let get_meta_expr = match m with
   | TExpr f -> f(); let v = !expr_ref; expr_ref := None; v
   | _ -> None
```
