### ISSUE TITLE
[analyzer?] abstract over abstract and static field initialization

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5332]
```haxe
abstract A(String) from String {}

abstract B(A) {
    public inline function new(s:String) this = s;
}

class Main {
    static var some = new B("hello");

    static function main() {
    }
}
```

this still generates:

```js
Main.some = (function($this) {
	var $r;
	var this1 = "hello";
	$r = this1;
	return $r;
}(this));
```

**Comment by nadako** [comment]
Interestingly, it generates nice code on 3.2: http://try.haxe.org/#45Bb2, so a regression \o/ :D

**Comment by Simn** [comment]
This happens because `type_change_ok` doesn't accept the assignment of `String` to `A` here:

```
[Var this1(3331):A] [Const:String] "hello"
[Cast:B] [Local this1(3331):A]
```

We were talking about it before, it's not really clear in which cases and on which targets we can skip an abstract like that. The correct fix would be to insert another case node, but I'm fairly certain that this would cause problems on Java/C# again.

If you're feeling brave you can change `type_change_ok` to accept the assignment of an abstract to its underlying type. Otherwise I prefer not to address this for 3.3 because it's a rare case with little consequence other than code output beauty.

**Comment by Simn** [comment]
Then again the unit tests compile fine with the cast change, so I guess we can give it a try after all.
