### ISSUE TITLE
No way to return non-zero exit code without using Sys.exit

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5335]
Calling Sys.exit can be problematic, at least on C#, as it force closes the app. On C# Environment.Exit terminates the app immediately even if other threads are running. Also, doc does not clearly states that this will force close the app.

https://msdn.microsoft.com/en-us/library/system.environment.exit(v=vs.110).aspx

**Comment by ousado** [comment]
Yes, it doesn't just set the exit code (if that's what you think it should do) - it terminates the process you're running - so it behaves as it should. If you want to store an exit code that should be used later, you have to implement that yourself.

**Comment by vroad** [comment]
I think I can't do that because Haxe does not allow me to return exit code from `main()` function. main function always returns 0 unless you force close the app with `Sys.exit`.

**Comment by ousado** [comment]
You can call Sys.exit with a value of your choice, at the end of the main function or anywhere else.

**Comment by vroad** [comment]
That's not same as exiting normally without using sys.exit. It's still force close. It'd be better to exit normally whenever it's possible.

**Comment by back2dos** [comment]
Unless you're in some kind of runloop environment, then if the main function is done, the program is done. Regardless of other threads and what not (all threads being daemon/background threads or however you want to call them). If you want to wait for completion of any threads you start, then you must do that yourself. Once you've ensured their completion, calling `Sys.exit` is safe.

**Comment by vroad** [comment]
That doesn't sound like an ideal solution. I don't think you can stop all threads if one of libraries is using threads.
That MSDN page also says that `Environment.Exit` has a problem with Constrained Execution Regions (CER). I've never used this future, but might be a issue for people want to use this future.

**Comment by vroad** [comment]
I googled about it, the only difference between exit and return is whether it runs destructor of local variables. So you think it's safe as long as you use `exit` carefully? I don't know if it's possible to call `exit` without any local variable on all targets. And it still looks error-prone.
http://stackoverflow.com/questions/461449/return-statement-vs-exit-in-main

C# has `Environment.ExitCode`, a function which allows you to set exit code even when you declare main function as `void`. Why doesn't Haxe have something like this?

https://msdn.microsoft.com/en-us/library/system.environment.exitcode(v=vs.110).aspx

**Comment by ousado** [comment]
> That's not same as exiting normally without using sys.exit. It's still force close. It'd be better to exit normally whenever it's possible.

Actually it is the same, it's linked in that SO thread:
http://www.iso-9899.info/n1570.html#5.1.2.2.3p1

> If the return type of the main function is a type compatible with int, a return from the
    initial call to the main function is equivalent to calling the exit function with the value
    returned by the main function as its argument

You can easily check that, e.g. strace on linux shows you which system calls are being executed for a given program.

Calling destructors is a language specific thing, so yes, if you're in C++ or some other language with locally scoped instances with destructors AND you rely on the destructors to be run AND you instantiate those in main(), don't just call exit before they go out of scope. 

Haxe isn't one of those languages, though, and hence you're fine.

**Comment by vroad** [comment]
Is there any good reason not to support "Sys.exitCode" property? Is there target cannot implement this? I think it's easy to implement.

I don't know why you force developers to program in a error-prone way. It's not completely same in Haxe since some targets depend on destructos or stack unwinding.

On C# you cannot simply use this call from less trusted apps.

**Comment by ncannasse** [comment]
Most of the plaforms don't have any other way of returning an exit code than to actually exit, so I guess we don't have much a choice here. You can always access the C# specific API to do what you want for this particular platform.

**Comment by ousado** [comment]
@vroad if you use any of the haxe targets in a way that depends on stack unwinding for calling destructors, you're not actually using pure haxe. Just because haxe targets e.g. C++ it doesn't mean it uses stack allocated instances that rely on destructors to be invoked in a way you don't have control over. As always, if you rely on target specific features in native extensions or the like, you're responsible for making sure to play nicely with the environment yourself.

If you are concerned about safety, you're highly unlikely to rely on the very rare and system- and platform-specific differences between calling exit at the end of the main function vs. returning an int from main. 

That .NET has a platform-specific concept of foreground and background threads that are handled in different ways by other platform specific ways to exit a program is a very good example for something that a cross-platform language like Haxe should 
a) abstract away in normal usage and 
b) expose if you need access to that functionality. 

And voila - that's exactly what it does:
Set the exit code: http://api.haxe.org/cs/system/Environment.html 
Set thread to fore-/background: http://api.haxe.org/cs/system/threading/Thread.html

I'm not aware of any other target language that does that sort of hand-holding in the first place, and the idea that calling exit in a Haxe program is more error-prone certainly needs /some/ sort of backup, not just repeated assertions that all refer to very specific target language properties.
