### ISSUE TITLE
Upredictable behaviour of Date class

### ISSUE THREAD

**Issue by mepsoid** [HaxeFoundation/haxe#5369]
When I instantiate Date from unix timestamp it uses GMT zone, but when I instantiate Date from the constructor it uses local time zone [(example)](http://try.haxe.org/#3c486):

```
class Test {
    static function main() {
        var date1 = Date.fromTime(1455555555 * 1000); // 15 Feb 2016 16:59:15 GMT
        var date2 = new Date(2016, 1, 15, 16, 59, 15);
        trace(date1.toString(), date1.getTime()); // it's GMT time
        trace(date2.toString(), date2.getTime()); // it's local time, for me GMT+4
    }
}
```

I'd like to receive same values of getTime() in unix timestamp at GMT zone in both cases. I.e. when I instantiate from unix timestamp I receive the same value; when I construct from my LOCAL time I receive GMT unix timestamp in getTime() AND the same LOCAL components of time (getDate(), getMonth(), getMinutes() etc...) that I have used in constructor.

**Comment by mepsoid** [comment]
Moreover getTime() have Float type but just overflows like this at Flash target:
`
trace(new Date(6, 6, 2016, 0, 0, 0).getTime()); // -1829966400000
`

**Comment by thomasjwebb** [comment]
Date is unreliable for me in the C++ target:

```haxe
var date = new Date(1904, 12, 12, 1, 4, 1);
trace(date.getFullYear()); // prints 1900
trace(date.getHours()); // prints 0
```

**Comment by Aurel300** [comment]
@mepsoid 's original issue is primarily caused by integer overflow (`1455555555 * 1000`). The multiplication of two `Int`s must result in an `Int`. Can be alleviated with `1455555555 * 1000.` (so the latter operand is a `Float`). The issue still reproduces then if you are not in a UTC timezone, but that is already tracked in #6353.

@thomasjwebb I think you mentioned the same issue in #7303, problems with `< 0` timestamps on hxcpp. Additionally the second argument (month) should be between 0 and 11.

Closing this in favour of the other two issues.
