### ISSUE TITLE
Error: Error accessing Haxelib repository: $e

### ISSUE THREAD

**Issue by jhertel** [HaxeFoundation/haxe#5448]
I just installed the latest Haxe for the first time ever, and on a new computer that never had Haxe installed before and is running Windows 10 (10.0.10586).

The setup program is haxe-3.3.0-rc.1-win.exe (which oddly says it is version 3.3.02.0, and during the installation the setup program referred to itself as "rc2", not "rc1"). Its size is 4,963,081 bytes.

I installed Haxe to the folder "C:\Programmer\HaxeToolkit". "C:\Programmer" is a builtin Windows hard link (or similar) to "C:\Program Files" on Danish versions of Windows. I got no complaints about this choice of folder from the installation program.

I then pressed Windows+R, typed cmd and pressed Enter to get a command prompt.

I typed the command

`haxelib install lime`

and got this error:

`Error: Error accessing Haxelib repository: $e`

which seems odd. $e had not been expanded to anything. 

And I was never asked to run `haxelib setup`, even though I have never had Haxe on the computer before.

**Comment by nadako** [comment]
Hey, thanks for the report. The `$e` is indeed a bug in haxelib (i'll create an issue about it on the haxelib repo), it should be expanded to the actual error happened, but it never did, because there's wrong string syntax used.

Most probably, the actual error has something to do with directory creation permissions (since haxelib on Windows will try to use `<haxe install dir>/lib` as the default repository), so I suggest you try running `haxelib setup` and choosing a directory where you can create a subdir without admin access.

**Comment by nadako** [comment]
Moved to HaxeFoundation/haxelib#335

**Comment by ncannasse** [comment]
@waneck should not the Haxe installer give writing rights to (haxe)/lib ?

**Comment by Simn** [comment]
This has been addressed in haxelib.
