### ISSUE TITLE
Odd Behaviour Of Optional Typedef Fields

### ISSUE THREAD

**Issue by hereticByte** [HaxeFoundation/haxe#5476]
Hello Haxe Foundation,

I probably have found odd behaviour of optional fields of typedefs.

Have a look of my example [here](http://try.haxe.org/#630d2).

In this example a condition asks if the optional field 'array' exists.

If it doesn't, the if-scope should be indicated with a trace() fn call. Also an array is handed over to this field.
If it does exist, the else-scope should be indicated with a trace() fn call. Also the first item of this array is supposed to be traced as well.

Oddly, the mashine indicates the else-scope and traces the array initialized in the if-scope...

Speaking out the obvious: If the array is initialized in the if-scope, the else-scope is supposed not be executed...

Is that an issue or am I overseeing something?

I would like to use optional typedef fields but only if it throws a nice error on faulty programming or showing a solid behaviour if this is not the case.

Kind regards
Arnim

**Comment by jcward** [comment]
Interesting. The great Object is being factored away and only great_array remains.

I think the main issue is, line 17 is being treated as a constant intializer:

`17:        	great.array = [ "Fantastic", "Great" ];`

And is being promoted to the declaration, line 12.

But the problem is, it's being promoted out of a conditional statement. That's illegal, as the conditional means that the assignment on line 17 is not actually constant. (Actually, the condition `great.array==null` itself could be considered constant and false, but the compiler doesn't seem to be making that optimization.)

**Comment by mockey** [comment]
Doesn't happen in current version.

**Comment by Simn** [comment]
Yes this was some problem with 3.2's ghetto analyzer. The 3.3 output looks fine:

```javascript
	var great_string;
	var great_array;
	if(great_array == null) {
		console.log("If");
		great_array = ["Fantastic","Great"];
	} else {
		console.log("Else:");
		console.log(great_array[0]);
	}
	console.log(great_array.toString());
	if(great_string == null) {
		console.log("If");
		great_string = "Yuhu!";
	} else {
		console.log("Else:");
		console.log(great_string);
	}
```

**Comment by hereticByte** [comment]
So, the _try.haxe.org_ code-server is not running on the latest version?

Could it be **updated** to the **latest version** then? This would be nice, as I am using it for testing small code snippets and having a playground for small, "stupid" experiments. This is much handier than always having a test-project running in the background.

Thanks to all.

**Comment by Simn** [comment]
try.haxe currently uses the latest stable version, it will be updated to 3.3 once that has been released properly.

**Comment by hereticByte** [comment]
Thanks for the info.
