### ISSUE TITLE
Mac - Broken IDE Plugin Paths - haxe-3.3.0-rc.1

### ISSUE THREAD

**Issue by Gautamji** [HaxeFoundation/haxe#5489]
**Version** : haxe-3.3.0-rc.1
**OS** : Mac OS 10.10.1
**Issue 1** : [Errno 2] No such file or directory: 'haxelib' in Sublime Text
**Issue 2** : Information:sh: neko: command not found in Intellij Idea
**Details** : 
I upgraded and installed haxe-3.3.0-rc.1 and the above issues cropped up, after a lot of searching, reinstalling, and debugging attempts later, the solution or rather the problem I found was that this new version puts symlinks and the haxe binary in /usr/local/bin rather than in the previous /usr/bin and also removes the previous binaries and symlinks. This is what broke the paths in the sublime and intellij pugins.

**Solution** : Copy the haxe, haxelib, neko and neko related symlinks from /usr/local/bin to /usr/bin

**Comment by andyli** [comment]
`/usr/local` is the right default installation prefix. Writing to `/usr/bin` and `/usr/lib` is even forbidden since OSX 10.11. If there is any IDE plugin only look for Haxe/Neko in `/usr/bin`, it should be fixed in the IDE plugin itself.

For the intellij plugin, please report this to https://github.com/TiVo/intellij-haxe

For the sublime plugin, I'm not sure since I'm using `/usr/local` and I cannot remember I've had issue with the sublime plugin. But you may try to explicitly set the paths according to https://github.com/clemos/haxe-sublime-bundle/wiki/Usage#settings

Related: https://github.com/HaxeFoundation/haxe/issues/5409
