### ISSUE TITLE
"from Dynamic" doesn't work with abstracts

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5506]
``` haxe
abstract A(Dynamic) from Dynamic {}
abstract B(Dynamic) {}

class Main {
    static function main() {
        var a:A = (null : Main); // works fine as expected
        var b:A = (null : B); // ERROR: B should be A
    }
}
```

Is there a reason for this? This e.g. prevents passing abstracts where `Any` is expected.

**Comment by nadako** [comment]
If we specify the `@:from` function with `Dynamic` argument, it'll work. Also this is not a regression.

**Comment by Simn** [comment]
I can tell you that the reason for this is that `unify_abstracts` calls `unify_from` with `~allow_transitive_cast:false`, which causes `unify_from` to use `type_eq` instead of `unify`.

The related change was here: https://github.com/HaxeFoundation/haxe/commit/262ba9a3541f909dfd5f428f4d520f0d433be5e5

Without it, the types Vec3 and Quat are assignable to each other because they can detour over `Array<Float>`, which is their common underlying type.

I think the problem here is that the test is too strict: In the abstract vs. abstract case, we could allow a `from`, xor we could allow a `to`, but we cannot allow both.

**Comment by Simn** [comment]
This works now.

**Comment by nadako** [comment]
OMG there already was an issue about this from 2016, by me, haha
