### ISSUE TITLE
Specification for FileSystem.deleteDirectory()

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5585]
Does it force-delete non-empty directory?

Since it is not clearly documented anywhere, I doubt the consistency among targets.

**Comment by Simn** [comment]
When in doubt, try. I'd expect it to delete non-empty directories but I don't think it's tested very well. There are some calls to it in our sys tests: https://github.com/HaxeFoundation/haxe/blob/development/tests/sys/src/TestFileSystem.hx

**Comment by kevinresol** [comment]
Yeah surely I know I can try it. But what I really mean here is to clarify the intended specification and write proper documentation, which will help both target implementors and haxe users.

**Comment by nadako** [comment]
Let's specify and test that, this is really important. I personally think recursive deletion would be the most useful, but I don't know, maybe there should be a separate function for it, or an optional arg. What are you thinking people? @ncannasse @Simn @andyli @hughsando @waneck

**Comment by ncannasse** [comment]
I'm fine with recursive deletion as default behaviour

**Comment by Simn** [comment]
At this point we'll focus on the new asys API and won't make any substantial changes to the old sys classes.

**Comment by Simn** [comment]
I was reminded of this via https://github.com/HaxeFoundation/hxnodejs/pull/197, and asys or not, this remains one of the controversial inconsistencies that we have to sort out in the sys API.

I'm still of the opinion that directory deletion should always be recursive by default because that's what I mean when I tell the computer to delete a directory.

**Comment by ncannasse** [comment]
@Simn we all agree to this :)

**Comment by tobil4sk** [comment]
Just to summarise what I said in the hxnodejs PR:
- Since the original discussion, for 6 years the deleteDirectory spec states that the directory must be empty: 8616359ff7f1916e5275cf9d620e79837bc66025 `"Only empty directories can be deleted"`. All haxe targets throw if it is non empty.
- All haxe targets' native apis have non-recursive delete as the default, so we would be deviating from that
- It is a silent breaking change which will break programs that rely on the spec (could result in data loss)

I agree that recursive delete is more useful, but since this would be a silent breaking change I think it should default to `recursive=false` or we should deprecate the current method and add a new one which is recursive by default.

**Comment by back2dos** [comment]
Recursive deletion is practical, but doesn't really map to what's happening on a file system level, where you have unlink for files and rmdir for *empty* directories, both of which are atomic and to me that's what the two `sys.FileSystem` calls have mentally always corresponded to.

To make recursive deletion *look* atomic one would have to:

1. move the directory to some temp location
2. empty it recursively
3. delete it in the temp location
4. pray a lot that nothing goes wrong in steps 2 and 3 (like your process being killed)

And an optimal implementation would probably start breadth first and start pushing work to threads if the tree is discovered to be big.

FWIW nodejs does have `fs.rmSync(path, { recusrive: true })` which deletes whatever is at the given `path`, with retry logic and what not. And even `fs.rmSync(path, { recursive: true, force: true })` that just noops out if `path` does not exist (I don't understand why it's called `force`, but that's another matter).

I'm not sure this really needs to be the stdlib's problem and if it were, then I think `createDirectory` should equally just recursively take care of creating all the necessary parent directories if they don't exist. Which I'm not against, but I agree with @tobil4sk that changing the default behavior now doesn't sound like a great idea. And even if it were, I think it would be good to expose just the atomic file system operations to the user, if they prefer control over convenience.

**Comment by Simn** [comment]
> I'm not sure this really needs to be the stdlib's problem and if it were, then I think createDirectory should equally just recursively take care of creating all the necessary parent directories if they don't exist.

It is, its specification says "This method is recursive: The parent directories don't have to exist.". I also never want to call another create directory function which doesn't do that ever again...

The atomicity argument gives me some pause though. Let me think about that in particular some more.

**Comment by kLabz** [comment]
> I don't understand why it's called force, but that's another matter

Could be to reproduce the behavior of rm -rf

**Comment by Simn** [comment]
What we have here is a bit of a clash between pragmatism and correctness, and Haxe has some history leaning towards the former. However, I really can't find a good argument for making recursive deletion the _default_, especially given that it wasn't until now. The best compromise is then to support it if specified by an optional flag, and default to the current behavior. This breaks no existing code (well, except for some hxnodejs cases I guess) but still allows recursive deletion if that's what we're after (which I still think we are 99% of the time, but that's not very relevant).
