### ISSUE TITLE
[python] AttributeError: type object 'python_Boot' has no attribute 'keywords'

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe#5592]
I was playing around with Python and Sqlite
(https://github.com/MatthijsKamstra/haxepython/blob/master/10sqlite/code/src/Main.hx)

And ran into this error.

```
  File "example.py", line 4696, in <module>
    User.manager = sys_db_Manager(User)
  File "example.py", line 1220, in __init__
    m = Reflect.field(haxe_rtti_Meta.getType(classval),"rtti")
  File "example.py", line 1948, in getType
    meta = haxe_rtti_Meta.getMeta(t)
  File "example.py", line 1958, in getMeta
    return Reflect.field(t,"__meta__")
  File "example.py", line 529, in field
    return python_Boot.field(o,field)
  File "example.py", line 3974, in field
    field1 = (("_hx_" + field) if ((field in python_Boot.keywords)) else (("_hx_" + field) if (((((len(field) > 2) and ((ord(field[0]) == 95))) and ((ord(field[1]) == 95))) and ((ord(field[(len(field) - 1)]) != 95)))) else field))
AttributeError: type object 'python_Boot' has no attribute 'keywords'
Error: Command failed with error 1
```

I guess its looking for: https://github.com/HaxeFoundation/haxe/blob/development/std/python/Boot.hx#L39

**Comment by frabbit** [comment]
@MatthijsKamstra can you provide a reproducible example. I tried to use your example, but sqlite isn't even implemented for python, so i don't know how you ran into this issue.

**Comment by MatthijsKamstra** [comment]
Hi @frabbit 

it was working on the basic documentation for different language targets from Haxe.

And I was curious if it would be as easy as advertised... It wasn't.
So I must have written down the error that I ran into.. a year ago. 

Its been a while and I never finished that part to the documentation....
And it might be that's related to the fact that python doesn't support sqlite.

I just don't know anymore. You can close this issue.

**Comment by frabbit** [comment]
ok, thx, yes the python target needs polishing, new or newer targets are feature-wise always behind the more established ones. Especially DB stuff is a lot of work and contributions are very helpful ;).

**Comment by gr4vityWall** [comment]
I've ran into this issue. Seems like it's caused by the static member `keywords` having its declaration at the end of the file, while it's being used much earlier.

Editing the compiled python code to move the `keywords` declaration inside the `python_Boot` class makes the problem go away. Editing the `python.Boot` Haxe class to inline a new `Set` every time you use the `keywords` static member also works, but it's an ugly hack and probably very inefficient.

You can reproduce it with this haxelib: https://gitea.com/gravityWall/python-sqlite

If there's any other info I can provide to help, please let me know. I'm not familiar with Python so my workarounds probably have much better alternatives.

**Comment by gr4vityWall** [comment]
I've managed to make a minimal example to reproduce this:
```
import haxe.rtti.Meta;

class Main {

	@metadata("metadata_value") var fieldWithMetadata:Int;

	static var ohNo = Meta.getFields(Main).fieldWithMetadata.metadata;

	static public function main() {

		trace(ohNo);

	}

}
```

The code above causes the reported error on the Python target, and it works fine on Neko/HL/JS/CPP/JVM (and I assume all other targets).
