### ISSUE TITLE
[display] @type Typecore.Fatal_error("Map does not have a constructor", _)

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5617]
```haxe
class Main {
	static var m = new Map<String, Int>();

	public static function main() {}
}
```

Hover over `m` to get `Typecore.Fatal_error("Map does not have a constructor", _)`.

**Comment by Simn** [comment]
This one was tough. The problem was that we checked the field display too early which lead to the field type being followed (and thus its expression being built) before other types had time to brush their teeth and initialize their fields.

I have delayed this to only display when we actually set the field expression, which should be safe.
