### ISSUE TITLE
[display] weird handling of comments in @type

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5625]
`@type` appears to think comments have a type (`Void` here, but I've seen `Dynamic` as well). It also highlights the entire function, which is a bit strange.

![](http://i.imgur.com/ZQNMDbL.png)

``` haxe
class Main {
    public static function main() {
        trace("hello");
        // comment
        trace("world");
    }
}
```

**Comment by nadako** [comment]
I think this is normal actually. Here, it returns a type for the hovered block and highlights it, e.g. the same as:

![](http://i.imgur.com/5NJuOoc.png)

The returned position range seems buggy regarding end line though, but when I last touched this I decided not to do anything right now, because to report positions properly we need a proper json output for hover info.

**Comment by Simn** [comment]
This is in the same ballpark as conditional compilation handling because it requires dealing with the tokens when skipping them. Can't do anything about that for 3.3, but we should look into the bad position offset.

Can you confirm that the Haxe output itself is off, not something in the vshaxe processing?

**Comment by Simn** [comment]
#7050
