### ISSUE TITLE
remove structurally extending class?

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5633]
I was wondering what `KExtension` is and saw that it's some deprecated feature that is still allowed.
However, this code generates some rubbish that fails at native compilation
```haxe
class Main {
    static function main() {
        var b = new B();
        b.b = 5;
    }
}

class A {
    public var a:Int;
    public function new() {}
}

typedef B = {
    >A,
    var b:Int;
}
```
E.g. on C#: `new global::+A().b = 5;`

So if this thing doesn't seem to work at all, let's just remove it already?

**Comment by nadako** [comment]
Just checked C++, JS and SWF - doesn't work there too.

**Comment by Simn** [comment]
We deprecated this for 3,2 so I think we can throw it out now.

**Comment by sbimikesmullin** [comment]
@Simn, @nadako: this is unfortunate. 

in cases like OpenFL `openfl.display.MovieClip` it would be very useful to extend classes with structures. right now we are using unsafe casts all over the place. afaik unsafe cast has no runtime performance penalty, but its annoying to have to write everywhere.

i'm surprised also to learn that typedefs come with a performance penalty on static targets.
https://haxe.org/manual/types-structure-performance.html

i'd like to propose an alternative implementation of this `structurally extending class` idea, based on unsafe casts. i mean, if it was harder to implement the original way.

why not have the following:

```
typedef IPet = { >openfl.display.MovieClip, hunger:Int };
// ...
function feedPet(pet:IPet, foodValue:Int) {
  pet.hunger += foodValue;
}
```

...be identical to the following?

```
function feedPet(pet:MovieClip, foodValue:Int) {
  pet.hunger = cast ((cast pet.hunger:Int) + foodValue);
}
```

reasoning:
- cascading typedef will ensure we can eliminate all calls to `Reflect`, `untyped`, and `cast` 
- we'd have 100% type coverage
- and therefore 100% compile time checking and auto-complete
- we won't have to make typedefs structures to mirror classes and keep them in sync

**Comment by nadako** [comment]
This is quite particular use-case, which I think only makes sense when the extended class supports dynamic properties (i.e. `implements Dynamic`).

I don't think it's worth adding support for this in the anonymous type, because it's possible to achieve the desired API with an `abstract` like this:

```haxe
extern class MovieClip implements Dynamic {
	var width:Int;
	function new() {}
}

@:forward // forward field access to the underlying type by default
abstract Pet(MovieClip) from MovieClip {
	// add proper typing for a dynamic property of an underlying value
	public var hunger(get,set):Int;
	inline function get_hunger() return this.hunger;
	inline function set_hunger(value) return this.hunger = value;
}

class Main {
	static function main(){
		var pet = new MovieClip();
		feedPet(pet, 100);
	}

	static function feedPet(pet:Pet, food:Int) {
		pet.hunger -= food;
	}
}
```

The `get`/`set` boilerplate might be something we could reduce, for example like this:
```haxe
abstract Pet(MovieClip) from MovieClip {
	@:forward public var hunger:Int;
}
```

@Simn what do you think?

**Comment by sbimikesmullin** [comment]
the above does not work as written
- `this.hunger` is not defined by parent so cannot be `@:forward`ed
- `Pet` assumes `this.hunger` is a type of `:Dynamic` because under type is `implements Dynamic`

**Comment by sbimikesmullin** [comment]
our use case is dealing with large amounts of art data. we have several thousand art assets. while these are composed from a basic set of <10 class types, it is the hierarchical tree structure they can be combined in represents the challenge.

`(a:MovieClip).b.(...).y.(z.TextField).maxChars` is difficult to type because there are any number of combinations inbetween `a` and `z`.

this is solved by other tree structures like the HTML DOM by providing rules of which classes are valid children for each type, and a set of functions to access them (albiet using reflection):

- `getElementById()`
- `getElementsByClassName()`
- `getElementsByName()`
- `getElementsByTagName()`
- `getElementsByTagNameNS()`

unfortunately, perhaps one of the many fallacies of Flash, this wasn't modeled by the Flash AS3 API. the nearest approximations we have are `.getChildAt(index:Int):MovieClip` and `.getChildByName(name:String):MovieClip` but we still must use reflection to learn the type of the child, and without iteration+reflection we cannot locate a child by its type.

another approach we could take here is to define a set of static functions which take a `MovieClip` type as their first parameter, in a helper/utility class, and with the haxe `using` keyword apply a set of methods more like those in the DOM.

...and I like that haxe provides so many ways of doing the same thing.

but it would be really convenient if there were a way to do it like i described above. the abstract is also cool, but its a ton of boilerplate. the goal in mind is making it less to type than the alternatives, and without performance impacts.

**Comment by nadako** [comment]
> the above does not work as written

not sure what do you mean by that?

> this.hunger is not defined by parent so cannot be @:forwarded

`@:forward` forwards any field access, including Dynamic

> Pet assumes this.hunger is a type of :Dynamic because under type is implements Dynamic

yes, that's why I created a property that explicitly types it as `Int` for the outside world

> MovieClip that implements Dynamic<DisplayObjectContainer>

not sure why it does work then, because `Int` value is certainly not a `DisplayObjectContainer` :)

**Comment by sbimikesmullin** [comment]
ya my fear is that it only works in js because its a dynamic target. 
but i mean can provide a tryhaxe demonstrating the abstract example? i couldn't.

**Comment by nadako** [comment]
https://try.haxe.org/#b3c9d

**Comment by sbimikesmullin** [comment]
ah ok i was missing your `MovieClip implements Dynamic` point. with minor tweaks, that does build. nice.
https://try.haxe.org/#335Da

**Comment by sbimikesmullin** [comment]
our use case is dealing with large amounts of art data. we have several thousand art assets. while these are composed from a basic set of <10 class types, the hierarchical tree structure they can be combined in represents the challenge.

`(a:MovieClip).b.(...).y.(z.TextField).maxChars` is difficult to type because there are any number of combinations inbetween `a` and `z`.

this is solved in other tree structures like the HTML DOM by providing rules of which classes are valid children for each type, and a set of functions to access them (albiet using something like reflection):

- `getElementById()`
- `getElementsByClassName()`
- `getElementsByName()`
- `getElementsByTagName()`
- `getElementsByTagNameNS()`

unfortunately, perhaps one of the many fallacies of Flash, this wasn't modeled by the Flash AS3 API. the nearest approximations we have are `.getChildAt(index:Int):MovieClip` and `.getChildByName(name:String):MovieClip` but we still must use reflection to learn the type of the child, and without iteration+reflection we cannot locate a child by its type.

another approach we could take here is to define a set of static functions which take a `MovieClip` type as their first parameter, in a helper/utility class, and with the haxe `using` keyword apply a set of methods more like those in the DOM.

...and I like that haxe provides so many ways of doing the same thing.

but it would be both the most type script and convenient if there were a way to do it like i described above. the abstract is also cool, but its a ton of boilerplate. the goal in mind is making it less to type than the alternatives, and without performance impacts.

perhaps the most critical observation is that an individual art asset can have a tree that is composed of millions of nodes. in those cases, its futile to think we can or would try to maintain compile-time-checked types for the the entire tree structure.

that's why this duck-typing approach of typedef extending class idea feels so appealing. we can focus in on only the patterns and parts of the tree we care to integrate with code. (e.g., the interactive elements of the art; the buttons, etc.) and we only have to define these types once and we can reuse them everywhere, rather than re-defining them with every reference via unsafe cast.
