### ISSUE TITLE
[display] type completion for function return types

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5649]
Trying to add an explicit return type to `f` doesn't return a completion result:

``` haxe
class Main {
    public static function main() {}

    function f() {
        return false;
    }
}
```

![](http://i.imgur.com/hYWMBCW.gif)

Instead it errors with `source/Main.hx:4: lines 4-6 : Function body required`.

**Comment by Simn** [comment]
The problem is that the parser sees the `{` and assumes you mean to declare a structure type. It's only when it comes across the `return` that it's clear what's going on, and at that point it's pretty much too late. If you had a normal identifier there it would _still_ assume that it's a structure type and it just came across the first key.

In fact, if you do the same thing on your `main` function it's a valid type-hint, namely `{}`. That particular case is outright unfixable, and the one on `f` is pretty bad as well. I can take a look after 3.3 but I doubt we'll be able to recover from this.

**Comment by Gama11** [comment]
The original test case seems to work now, although it must've been for a while (also works when going back to 3.4.7).  However, it doesn't work on `main`:

```haxe
class Main {
    public static function main(): {}

    function f() {
        return false;
    }
}
```

Ctrl+space after the `:` gives "completion point not found".

**Comment by Simn** [comment]
Would it be fair to only support this _on_ the colon?

**Comment by Gama11** [comment]
That kind of clashes with some code styles... [including your own](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/rtti/JsonModuleTypes.hx#L37), recently? :P

Why is that easier? Can't you check if there's just whitespace between?
