### ISSUE TITLE
[display] @type on function with type param returns monomorph

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5664]
```haxe
class Main {
	public static function main() {
		typeParam([1]);
	}
	
	static function typeParam<T>(a:Array<T>) {}
}
```

![](http://i.imgur.com/8SKjaqo.png)

I guess ideally, this should show `a:Array<typeParam.T>` like it does when you hover over the function itself?

**Comment by Simn** [comment]
I'm not sure if this can be fixed because that's how the typer types things. I'm also not sure if this should be fixed because that would essentially leak the type parameter to the outside. From the call-site point of view the signature indeed does have a monomorph there, so I think we shouldn't touch this.
