### ISSUE TITLE
[display] @statistics should find implicit toString() calls

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5681]
It would be nice if implicit `toString()` calls could be detected. In the following example, `toString()` is called 5 times, but only the one explicit call is actually reported:

![](http://i.imgur.com/Siv0UOM.png)

``` haxe
class Main {
    public static function main() {
        trace("" + new ToStringable());
        trace('${new ToStringable()}');
        trace(new ToStringable());
        trace(Std.string(new ToStringable()));
        trace(new ToStringable().toString());
    }
}

class ToStringable {
    public function new() {}

    public function toString() {
        return "toStringable";
    }
}
```

**Comment by kevinresol** [comment]
Should that cover implicit casts (@:from / @:to) as well?

**Comment by Simn** [comment]
I think these already work because they actually show up in the internal structure.

The problem with `toString` is that the compiler doesn't care for them at all on classes. All it does is use `Std.string(object)`, which is then (at run-time) free to check for `toString`. This has already given me a lot of trouble in DCE where several special cases were required to handle it.

I'm not sure I actually want to address this for statistics. I think it would be more prudent to change our internal handling so that it actually inserts the calls, but that's not a change I want to randomly make over lunch.

**Comment by Gama11** [comment]
Implicit casts indeed seem to work already (at least the simple case I tested). Impressive!

**Comment by Simn** [comment]
Let's ignore this. I've been playing with toString a bit, but it's not easy because we have to consider `null` values in the generated code, which in turn might require binding complex expressions to temporary variables.
