### ISSUE TITLE
Introduce `EnumTools.getParameter(e:EnumValue, i:Int):Dynamic`

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#5690]
There's currently `EnumTools.getParameters(e:EnumValue)`, which returns the ADT's parameters as an array.
It's a bit of a purpose-specific function - on all targets that I've checked, it (somewhat expectedly) returns a shallow copy of the enum's parameters. While this is good for a few things (like cloning an EnumValue by combining this with several other Type API functions), in a general case it's not much use due to allocation of an array.

Would I would like to propose, is to introduce a separate `EnumTools.getParameter(e:EnumValue, index:Int):Dynamic` function, which would return the given enum' parameter by index. Essentially same as `Reflect.field`, but for enum parameters.

Since most (all?) targets store enum parameters in one or other kind of an array, implementation would be trivial, inline-able, and fast. For the rest a polyfill could be made based on getParameters.

Can assemble a pull request for a handful of targets if needed.

**Update:** As an example, for AST and parsers, it may be desirable to store position in constructors themselves,

``` haxe
enum Token {
    Number(pos:TokenPos, value:Float);
    String(pos:TokenPos, value:String);
    Ident(pos:TokenPos, name:String);
    // ...
}
enum Node {
    Number(data:NodeData, value:Float);
    String(data:NodeData, String);
    Return(data:NodeData, expr:Node);
    Block(data:NodeData, nodes:Array<Node>);
    // ...
}
```

instead of nesting them in anonymous structures, as the program needs to check constructor index much more often than the additional data, thus serving no other purpose than adding complexity and tiny overheads.

But then, to pull out that `pos`/`data` value, you'll need either a giant goofy switch,

``` haxe
return switch(node) {
case Number(d, _), String(d, _), Return(d, _), Block(d, _)/* ... */: d;
}
```

(hopefully made with a macro but still non-inlining)
or a function with one or more platform-specific `untyped` returns.
Having a `getParameter` function would address this, and permit to have a cleanly inline-able helper function.

**Comment by nadako** [comment]
note that i have a (yet to be merged) branch for c# that implements enum parameters as class fields, but anyway, it shouldn't be hard to add getParameter for that too

**Comment by Simn** [comment]
I'm inclined to suggest simply supporting array indexing on enum values. It currently doesn't have a meaning and the requires int-keys would work as well. This would also allow us to translate directly to TEnumParameter, which we've had internally for a while.

**Comment by back2dos** [comment]
The basic issue brought up here is that the reflection API does not support
getting single enum parameters out and it might make sense to add that (so
that The Children of Memory Conservation may once again rejoice \o/). For
the sake of completeness you should then also be able to get the number of
parameters, otherwise you're shooting in the dark.

As for having some uber clever shortcuts, we'd get that for free if we
could use features of abstracts (i.e. operator overloading including array
access) through static extension (here I go again ...). So then `using
CodeGolf` one can write `myEnumValue[0]`. But if in a given context one can
define `[]` as something different, why not let the user do that?

**Comment by Simn** [comment]
This would have to go through a haxe-evolution.
