### ISSUE TITLE
Generic Class Inline Functions are extremely slow (~x5)

### ISSUE THREAD

**Issue by PDeveloper** [HaxeFoundation/haxe#5698]
Using this gist as a sample:
https://gist.github.com/PDeveloper/50bdaf7e8e2d4c38de330a1599e06e21

Inline functions in generic classes are SLOW.
The generated code shows why. The inline function causes a c-style cast to happen, while the non-inlined version uses a static_cast first, and then access fields normally. At least at first glance, that's what I could see to be the only difference!

**Comment by Simn** [comment]
@hughsando: I'm not sure but I think this one is for you too. I can't spot anything suspicious in the AST dump.

What's interesting is that changing the length of that 'asdfasdf' string changes the benchmark result for me, with a shorter string leading to a better result. I suppose creating objects within that loop is more of a GC test than anything else, but the inline/non-inline difference is still obvious.

This might be a performance regression so I'll label it as such.

**Comment by hughsando** [comment]
As written, you need to set the string to empty between runs - and maybe add an empty string instead to measure only the array performance, rather than adding a bunch of noise to do with GC.
This show the difference more dramatically.
Inlining the generic constructor tips the balance back in favour of the Inline case (3x faster with empty string!).
But you are right in that the inline case should be performing at least as well here.

**Comment by Simn** [comment]
Thanks for the fix!

However, I wonder why the nature of the string makes such a difference, given that Haxe strings are immutable and could share instances.

**Comment by hughsando** [comment]
They are accumulated (result = result + o.field;) that is why the second run is slower that the first.
If you use the empty string, the resultant empty string will map to a single instance of the empty string.

**Comment by Simn** [comment]
Right you are!
