### ISSUE TITLE
[Neko] Sys.programPath() with neko booted executables

### ISSUE THREAD

**Issue by Yanrishatum** [HaxeFoundation/haxe#5708]
`Sys.programPath()` returns incorrect path to neko modules that are booted with `nekotools boot` command. It is expected that function return path to booted executable, but instead it returns path executable folder + `.n`. `Sys.executablePath` provided as comparsion.  
Tested on `haxe_2016-09-21_development_3df5463.tar.gz`.  
Test results:

``` haxe
// neko programpath.n
Sys.programPath()    = C:\_temp\programpath\programpath.n
Sys.executablePath() = E:\HaxeToolkit\neko\neko.exe
// nekotools boot programpath.n
// programpath.exe
Sys.programPath()    = C:\_temp\programpath\.n
Sys.executablePath() = C:\_temp\programpath\programpath.exe
// cpp version for comparsion:
Sys.programPath()    = C:\_temp\programpath\ProgramPath_cpp.exe
Sys.executablePath() = C:\_temp\programpath\ProgramPath_cpp.exe
```

Reproduction code:

``` haxe
class ProgramPath
{
  public static function main():Void
  {
    Sys.println("Sys.programPath()    = " + Sys.programPath());
    Sys.println("Sys.executablePath() = " + Sys.executablePath());
  }
}
```

Build.hxml:  

``` hxml
ProgramPath.hx
-main ProgramPath
-neko programpath.n
-cmd nekotools boot programpath.n
```

**Comment by ncannasse** [comment]
I think @andyli made changes here.

**Comment by derRaab** [comment]
Are these paths in any way related to the loading of dynamic linked libraries? Might this break the lookup within the same directory for dynamic linked libraries?

I'm just curios if that might affect my approach of using a neko booted executable called from an Adobe AIR application in a positive way (since it doesn't find the libraries next to it when called from AIR - but wen called from a terminal it's just fine).

**Comment by puggsoy** [comment]
Just want to say that this issue is still present in Haxe 3.4.0-rc.2. Sys.executablePath() works fine but it's annoying to keep being told to use programPath in a warning.

**Comment by ncannasse** [comment]
Up @andyli
