### ISSUE TITLE
haxelib cleared on make of haxe

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/haxe#5711]
I guess it might be expected behaviour (?), but nevertheless annoying when you work with extensions - after compiling the latest haxe version the `haxe/lib` directory is getting completely cleared out

https://github.com/HaxeFoundation/haxe/blob/development/Makefile#L111

This is especially annoying when you've been working with a lot of different extensions and need to re-install them, or have even lost non-commited changes to some of them. Additionally of course having to re-download all extensions is a time consuming process

2 possible solutions ...

a) warn on `make install` that `haxe/lib` is not empty and that it will be cleared
b) move `haxe/lib` out of `haxe` directory

**Comment by Simn** [comment]
@andyli: Could you check that, that sounds pretty bad.

**Comment by tong** [comment]
The default behavior of `make install` should be to copy over existing files.
For a 'clean' install someone can run `make uninstall install`.

**Comment by frabbit** [comment]
@andyli this is a milestone 3.3 issue, is this still relevant for a release?

**Comment by ibilon** [comment]
This is about using the dev version, doesn't need to be in a release.

**Comment by Justinfront** [comment]
@mastef
Normally it's best to create 'haxeLibrary' somewhere outside the haxe folder ( like for instance alongside ), then when you setup haxelib you just point to that folder and your haxe library is unharmed on reinstall.
perhaps it would be enough to change the default location that haxelib uses to be next to the haxe folder rather than in it, I use the name 'haxeLibrary' to be more explicit than lib.  
It can be useful to have it outside because you could have different library sets, for instance if you wanted to update all your libraries just take a copy first incase of problems you can just point back to that oldHaxeLibrary, you could also have haxe3_3Library and haxe3_2Library.  
The default behaviour of lib being inside the installed Haxe folder is not ideal.

**Comment by Justinfront** [comment]
The change would need to be haxelib not haxe and would still overwrite with the next install, but afterwards behave better.

**Comment by mastef** [comment]
Thanks @andyli
