### ISSUE TITLE
[display] @position support for structure fields

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5712]
```haxe
class Main {
	public static function main() {
		var s:Struct = { field: 0 };
	}
}

typedef Struct = {
	field:Int
}
```

Invoking `@position` on `field` in line 3 results in an empty list. It should report the field's declaration in line 8.

**Comment by Simn** [comment]
This one is a bit strange because the structure declaration is technically not strictly tied to the type you're declaring. Imagine that `Struct` was declared to have `field:Float`, would type-display on your line 3 `field` give `Int` (from the declaration) or `Float` (from the type)?

I guess position display is more obvious because it makes no sense to take you to the declaration position, given that you're already there anyway.

**Comment by Gama11** [comment]
You mean because `0` is an `Int` literal? As opposed to `0.0` which would be a `Float` literal?

**Comment by Simn** [comment]
I just used that example to highlight the difference. Internally there are actually two class fields involved here and if you give them different types you get different results. This would also affect `s.field` display, which could go to the structure declaration or the type declaration.

**Comment by Gama11** [comment]
Nice! Even supports doc display on hover now, which didn't work before IIRC. :)
