### ISSUE TITLE
Constant folding array values

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#5717]
Would it be possible to fold these type of constants too?

``` haxe
    var v = [0,1,2,3,4,5][3];
    trace(v);
```

Expected output:

``` js
console.log(3);
```

Haxe 3.2.1 outputs (js target)

``` js
var v = [0,1,2,3,4,5][3];
console.log(v);
```

Haxe 3.3.0-rc.1 outputs (js target)

``` js
console.log([0,1,2,3,4,5][3]);
```

**Comment by Simn** [comment]
Note that in the general case we cannot skip all the array expressions because they could contain side-effects. On the other hand, limiting this to constants seems very narrow and not particularly useful outside of artificial examples.

There are ways to implement this properly, but since it was made clear to me that optimizations like this are not really desired in Haxe, I'll go ahead and close this issue.
