### ISSUE TITLE
[display] @type on enum constructor arguments

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5729]
```haxe
class Main {
	public static function main() {
		var c = Constructor(1);
		switch (c) {
			case Constructor(integer): trace("test");
		}
	}
}

enum TestEnum {
	Constructor(i:Int);
}
```

Hovering over `integer` highlights the entire `case` and returns `Void`:

![](http://i.imgur.com/woKHqBS.png)

**Comment by Simn** [comment]
This happens because we map our AST like this: `| ESwitch (e,cases,def) -> ESwitch (loop e, List.map (fun (el,eg,e,p) -> List.map loop el, opt loop eg, opt loop e, p) cases, opt (fun (eo,p) -> opt loop eo,p) def)`. Unfortunately, the order of evaluation for this is undefined in OCaml and the display pre-processor assumes that the first (that is, innermost, because it's a bottom-up mapping) sub-expression that contains the display position is the one we want.

Fixing this requires changing ast.ml `map_expr` to have a clearly defined evaluation order. For the ESwitch case, this would be:

```ocaml
	| ESwitch (e,cases,def) ->
		let e = loop e in
		let cases = List.map (fun (el,eg,e,p) ->
			let el = List.map loop el in
			let eg = opt loop eg in
			let e = opt loop e in
			el,eg,e,p
		) cases in
		let def = opt (fun (eo,p) -> opt loop eo,p) def in
		ESwitch (e, cases, def)
```

The good news is that ESwitch is by far the worst case, the bad news is that changing this for all other cases is still a bit of an intern job.
