### ISSUE TITLE
Allow overloading `=`

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#5738]
Since we can overload assignment operations already, I wonder what the rationale is behind not allowing it for `=`?

I mostly want this for tink_sql. It is already possible to write things like 

``` haxe
db.Character
  .where(function (c) return c.id == someId)
  .update(function (c) return [c.hitpoints += 50, c.mana -= 15])
```

but for assignments I have to resort to 

``` haxe
db.Character
  .where(function (c) return c.id == someId)
  .update(function (c) return [c.name.set(someName)])
```

That's rather awkward and unintuitive.

**Comment by back2dos** [comment]
So, any thoughts on this? Is it a minor change or should I make it a proposal?

**Comment by kevinresol** [comment]
I would like to hear some comments from the team too.

**Comment by RealyUniqueName** [comment]
Great +1 for this feature!
This could make a lot of things so much easier.

**Comment by RealyUniqueName** [comment]
@ncannasse  @Simn is there anything to discuss about this feature?

**Comment by ncannasse** [comment]
Don't have a strong opinion on this, I haven't read the reason why it was forbidden in the first place, would surely like to hear before deciding

**Comment by RealyUniqueName** [comment]
@Simn ?

**Comment by Ilir-Liburn** [comment]
@Simn, please use @:op(=B) instead of @:op(A=B) so that overloading function is not static

**Comment by nadako** [comment]
> @:op(=B)

that is not a valid expression syntax, so we can't easily do that :D

**Comment by Ilir-Liburn** [comment]
@:op(_=B)  :D

**Comment by RealyUniqueName** [comment]
Overloading function doesn't have to be static. E.g. these are equal:
```haxe
@:op(A + B) static function add(a:Abstr, b:MyType) ...

@:op(A + B) function add(b:MyType) ...
```

**Comment by Ilir-Liburn** [comment]
Well, at least we have a workaround, it is weird

```haxe
    @:op(A...B) public static inline function range<T>(lhs:Abstract, rhs:T) {
        lhs.value = rhs;
        lhs.type = Type.typeof(rhs);
    }

   var a = new Abstract();
   a ... 0;
```
because allows me to declare overloading function without returning an iterator. Everything is inline as I wanted, so it doesn't matter if function is static or not

**Comment by Ilir-Liburn** [comment]
Now things get complicated

```haxe
   var a1 = new Abstract();
   var a2 = new Abstract();
   a1 = a2;
```
Here compiler assumes I want to copy a value or reference of the underlying type, but that is not what I want. I want to copy a values of member variables of the underlying type. This somehow shows how urgent we need @;op(A = B), but it also shows why Simn is against it (assuming he still is): operator A = B is not a full copy unless we make it so, meaning A = B is not necessary A == B.
Furthermore, my workaround use A = B without return, while real implementation would probably return a value or reference and assign that to variable holding A. Again, what is returned is not necessary making A == B

**Comment by Ilir-Liburn** [comment]
I suggest to make unique operator, meaning something is transferred from B to A which not makes A == B

```haxe
// @:op(A := B) ?
// @:op(A =< B) ?
@:op(A <- B) public function copyLeft(final rhs:Dynamic) { // or @:const ?
    // something can be copied here, while rhs is read only
    this.value = rhs.value;
    this.type = rhs.type;
}
```

no return value.

Such operators doesn't exist, so Simn will probably not like it. Just want to continue discussion, everyone seems to be quiet now. Suggestions please.

**Comment by Ilir-Liburn** [comment]
I don't like it either, but I need it without using a1.assign(a2) or such. Code a1 = a2 will copy reference of the underlying object if a1 and a2 are of the same abstract type so that

```haxe
   var a1 = new Abstract();
   var a2 = new Abstract();
   a1 = a2;
   a2.value = 10;
   // a1.value will also become 10 because @:from or @:op(A = B) will never be called
   // @:from public static function clone(a:Abstract) return /* some cloning code here */;
```
while in case underlying type is just basic type or dynamic
```haxe
   var a1 = new Abstract();
   var a2 = new Abstract();
   a1 = a2;
   a2 = 20; // a1 will stay whatever it was 
```

If Simn ever implements @:op(A = B) it will be never called in place of variable initialization (@:from or new will be used) and never called when A and B are of the same abstract type. In between, @:op(A = B) could be called, but I don't know what kind of other problems could arise.

**Comment by Ilir-Liburn** [comment]
To conclude my opinion on this, @:op(A = B) should be only

```haxe
@:op(A = B) public static function copy(lhs:Abstract, rhs:Abstract):Abstract {
    lhs.value = rhs.value;
    lhs.type = lhs.type;
    return lhs;
}
```
or if underlying type is dynamic

```haxe
@:op(A = B) public static function copy(lhs:Abstract, rhs:Abstract):Abstract {
    if (/* rhs is object */) { 
       lhs.value = rhs.value;
       lhs.type = lhs.type;
       return lhs;
      }
      else return rhs;
}
```

overloading default A = B compiler behavior if types are of the same abstract type so that we can make a copy (or clone) if underlying type is an object instance (without @:op(A = B) defaults to compiler coping a value or reference). Otherwise, everything is about what comes first: @:from or @:op(A = B) or even new(chicken || egg)

**Comment by RealyUniqueName** [comment]
Let's try this for 4.1

**Comment by Simn** [comment]
I think this actually needs a haxe-evolution. I'm having trouble understanding the intended semantics under various circumstances. For example, what if we have an assignable abstract property which has a setter? Is that just a declaration error? Or what if we assign to a normal local variable, but our assignment overload doesn't actually assign to `this`? Should that be a requirement?

Frankly, I don't like messing with `=` in an arbitrary manner. It currently has well-defined semantics and comes with this implicit promise that there's mutability happening. If any `=` in syntax could in actuality be a no-op because the lhs happens to be an abstract overloading it, the cognitive load when reading Haxe code is increased because one has to keep that in mind.

Intuitively, I'd say that an overloaded assignment operator should be required to assign to `this`, and thus also be `inline`. That's why I think a haxe-evolution is in order so these things can be agreed upon.

**Comment by Simn** [comment]
Here's some code to demonstrate this:

```haxe
abstract Assigner(String) {
	public function new(value:String) {
		this = value;
	}

	@:op(a = b) function assign(rhs:Assigner) {
		return new Assigner('$this = $rhs');
	}
}

class Main {
	static public var varAss:Assigner;
	@:isVar static public var propertyAss(get, set):Assigner;

	static function get_propertyAss() {
		return propertyAss;
	}

	static function set_propertyAss(value:Assigner) {
		return propertyAss = value;
	}
}

@:analyzer(ignore)
function main() {
	var localAss:Assigner = null;
	localAss = new Assigner("assigner");
	trace(localAss); // null
	Main.varAss = new Assigner("assigner");
	trace(Main.varAss); // undefined
	Main.propertyAss = new Assigner("assigner");
	trace(Main.propertyAss); // undefined
}
```

Generated JS:

```haxe
var Assigner = {};
Assigner._new = function(value) {
	return value;
};
Assigner.assign = function(this1,rhs) {
	return Assigner._new("" + this1 + " = " + rhs);
};
var Main = function() { };
Main.get_propertyAss = function() {
	return Main.propertyAss;
};
Main.set_propertyAss = function(value) {
	return Assigner.assign(Main.propertyAss,value);
};
function Main_main() {
	var localAss = null;
	Assigner.assign(localAss,Assigner._new("assigner"));
	console.log("source/Main.hx:28:",localAss);
	Assigner.assign(Main.varAss,Assigner._new("assigner"));
	console.log("source/Main.hx:30:",Main.varAss);
	Main.set_propertyAss(Assigner._new("assigner"));
	console.log("source/Main.hx:32:",Main.get_propertyAss());
}
```

Looking at the `main` code without much context, these traces are not what I expect in a non-concurrent environment. Even the property version doesn't work because the setter itself calls the overload.

**Comment by RealyUniqueName** [comment]
It's already allowed to overload `+=`, `-=`, `--`, `++`
And they already work with setters somehow. I guess `=` should follow the same behavior.

**Comment by Simn** [comment]
I expected someone to bring up the `+=` argument, but in my opinion this is not the same thing. As soon as you have the `+`, you already have to be aware of whatever semantics your operands have. With `+` in particular it can be either a numeric type or `String` even before we consider operator overloads.

In contrast, `=` is much more generic. It carries no inherent meaning other than "something is assigned to", and that's what allowing arbitrary overloads for it would lose.

Either way, a change like that has to be sanctioned, so we will need a haxe-evolution. And if you want my vote on that (which you probably won't need), it will take some convincing arguments for why this makes the language any better. Until then, I'll close here.
