### ISSUE TITLE
Interp.clear not working

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5739]
Today I hit into the following problem.

One of my macro is calling Context.getType, which trigger some more modules to be loaded, some of them being modified from a previous compilation, which then triggers another macro which does the new  `Interp.clear`. Let's say that things does not go very well when returning from this macro...

I think it is necessary to restore the previous behavior and investigate what the original issue with it was eventually.

**Comment by Simn** [comment]
Are you implying that there were multiple interpreter contexts by design? And what exactly is the problem now? Maybe we're just clearing too much, i.e. the runtime/eval parts.

**Comment by ncannasse** [comment]
The initial problem was a DynArray.get with negative index, because we reset the registers stack in Interp.clear. However even without this we also need to keep our previous globals table because it is necessary for the macro to execute correctly.

So yes, given that macro context can be reset/clear during compilation while we are already executing a macro, it seems safe to assume that we can need to have several contexts. It was not by design but it happened to work pretty well before your change.

For instance, the context "before reset" might have a different global table than "after reset".

**Comment by Simn** [comment]
So what if we simply don't reset globals either?

I really think the current approach is better. We just have to save/restore the state properly when we have a macro-in-macro situation. Your globals should be an argument in that favor too because you could "lose" some global with the old implementation as well if it's completely reset:

1. Macro does something that causes a global value to be set (context 1)
2. A flush is necessary, so a new context is created (context 2).

At this point there's no way to win: If a callback or something uses context 1 it misses out on whatever caused the flush (modified/new type?), if it uses context 2 the global value is gone. The former is probably what I came across in #5676.

Really, I can't see how having multiple contexts of something that has mutable global information and is itself cached (`ctx.g.macros`) could work.

**Comment by ncannasse** [comment]
We need to reset the globals. Since we're creating a new neko context, we will create a new globals table so we cannot reuse the previous context ones ! Some classes have been changed, which means they might have different statics, so different globals, we simply cannot "share" the state between the contexts.

PS: this is not a macro-in-macro situation (which we use for a macro called while in macro mode)

Also, I don't understand your comment. In which case would a callback still use context 1 ? We just want the macro on the stack (running in context 1) to properly finish computing what it needs to and return, at which point the macro context will be GC'ed since it's no longer referenced by anything.

**Comment by ncannasse** [comment]
Let me be more clear : there should not be any reference to the macro context, everything should go through the typer which will use its "current" macro context.

ATM the clear is wrecking the macro interpreter and needs to be reverted. I don't see any theorical issue with having several macro contexts.

**Comment by Simn** [comment]
I've reverted it, can't be arsed to have lengthy discussions about it at the moment. Please deal with whatever I came across in #5676 then.
