### ISSUE TITLE
Macro statics initilization

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5746]
Following conversation in #5676

In macro context (with compilation server), static variables:
a) can be kept in the state they were in the previous compilation (reusing macro context)
b) can be reset the their default value during compilation (discarding + creating a new macro context)

Now in order to improve it, we could fix (a) by generating all statics initialization code in a separate function that would get called when reusing the macro context, so you would get a freshly initialized module. That should render useless the `onMacroContextReused`

For (b) the only solution would be to detect before reusing the macro context (so on the first called macro) if one of the modules of the macro context has been modified.

This would ensure the same statics behavior has you would get without macro context reuse, without the extra time required to initialize the context.

**Comment by ncannasse** [comment]
There's no much design decision here.
Here's a complete list of thing to do:

- [ ] have a way in Eval to reset static variables to their default value or expression, like if you would initialize the module again
- [ ] call this everytime we "reuse" the macro context (instead of onMacroContextReuse)
- [ ] add an api "haxe.macro.Storage" similar to browser localstorage, but only in-memory for compilation server. It persists across recompilation. We can have a "global" storage for all compilation contexts and a "local" storage for the current one (set of defines)
- [ ] deprecate previous "context reuse" etc. callbacks (they are no longer by the compiler called anyway)

@back2dos comments?

**Comment by Simn** [comment]
Adding haxe.macro.Storage sounds complicated. How about supporting `@:persistent static var x = 1;` instead? I could support this easily by simply filtering these statics out so they are not reinitialized on context reuse, which would give the previous behavior.

**Comment by ncannasse** [comment]
What would be complicated about haxe.macro.Storage ? It's just a Hashtbl
stored in memory.
The problem with statics is that you don't really control the
initialization order which is quite hard to deal with.

**Comment by Simn** [comment]
Why does the initialization order matter here?

I would prefer a per-static metadata to a dynamic string map.

**Comment by ncannasse** [comment]
I prefer an explicit API than a per-static medata but I guess we can have both. Moving to Release 4.0 as this is a breaking change.

**Comment by back2dos** [comment]
Hmm, I'm not sure what to make of this. If you run with the server, side effects are generally persisted.

For example in tink_macro, there's this thing called `BuildCache` for `@:genericBuild` which allows making sure that `MyGenericBuild<SomeType>` always returns the same result. In essence it takes a `Type->TypeDefinition` function that is only run if there's no entry for the particular type. In that case, it does `Context.defineType` with the result. Which is quite the side effect - and we're not rolling that back on the next build (luckily). So I wonder what the rationale is behind doing it for static vars. 

So I guess my question is: Why isn't the macro context reused all the time? In my experience the need to reset global state on recompilation is the exception and not the norm, because most global state changes reflect code that has been generated **and persisted**, so in the vast majority of cases you don't want to lose the global state corresponding to the code. Using `Context.onGenerate` to do house keeping is pretty comfortable (you can purge cache entries for types that are long gone and what not).

**Comment by Simn** [comment]
Still not sure how to proceed here.

**Comment by Simn** [comment]
I talked with @frabbit about this and we agreed on going forward with the reset while allowing to tag statics to be kept.
