### ISSUE TITLE
[cs] NativeArray + Null<T> fail

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5751]
``` haxe
class Main {
    static function main() {
        (new Array(new cs.NativeArray(10)) : Array<Null<Int>>);
    }
```

generates

``` cs
new global::Array<object>(((object[]) (new global::haxe.lang.Null<int>[10]) ));
```

ast:

```
[New:Array<Null<Int>>]
    Array<Null<Int>>
    [New:cs.NativeArray<Null<Int>>]
        cs.NativeArray<Null<Int>>
        [Const:Int] 10
```

this is blocking #5749

**Comment by waneck** [comment]
I cheated a little bit on this one. I've made a special case for NativeArray on the cast detection. We could potentially do this for every TNew expression, but the issue is that we currently don't propagate expression changes down on the cast detection. So for example:

```haxe
class Something<T> { function new(t:T) {} }

var x = (cast new Something<Null<Int>>(null) : Something<{}>);
```

We could theoretically detect this and make it `new Something<{}>(null)`, but we'd need to propagate the `Null<Int>->{}` change. And that's not easy.
