### ISSUE TITLE
[Flash] Regression: try..catch does not catch type coercion error on return.

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#5774]
Latest Haxe does not catch type coercion errors on returns:

``` haxe
class Test {
    static function main() {
        try {
            trace(test());
        } catch(e:Dynamic) {
            trace(e); //This traces is invoked, but it should not
        }
    }

    static function test():Array<String> {
        var value = "1,2,3,4,5,6";
        try {
          return cast value;
        } catch(e:Dynamic) { //because of this
          return value.split(","); 
        }
    }
}
```

3.2.0 traces `[1,2,3,4,5,6]` as expected: http://try.haxe.org/#4D0f1
3.3.0 (and latest git) traces error message: http://try-haxe.mrcdk.com/#1bbF7

**Comment by Simn** [comment]
Eh, I don't think that's defined behavior? If you want to catch stuff you'll have to use safe-casts, not unsafe ones.

**Comment by RealyUniqueName** [comment]
I expect `catch(e:Dynamic)` to catch all exceptions :)

**Comment by RealyUniqueName** [comment]
oh... It does not matter if it a return or anything else. It just does not catch: http://try-haxe.mrcdk.com/#7076C

**Comment by nadako** [comment]
what? O_O
```
static function test[Function:Void -> Array<String>] [Block:Dynamic] [Return:Dynamic] [Cast:Array<String>] [Const:String] "1,2,3,4,5,6"
```

**Comment by Simn** [comment]
Yes but technically this doesn't guarantee to throw a catchable exception in the first place. The analyzer considers the catch block to be unreachable because there's nothing that could throw (to its knowledge).

**Comment by nadako** [comment]
I think it's not safe to assume that `cast` won't throw.

**Comment by Simn** [comment]
Well, it's called unsafe for a reason.

**Comment by RealyUniqueName** [comment]
but `try...catch` _must_ catch _all_ errors, i guess )

**Comment by Simn** [comment]
I really don't think we should define this. You can trigger some native errors that aren't caught on several targets as far as I know.

If I have to assume that anything can throw I basically can't do analysis because I can't build a CFG that isn't insane.

**Comment by RealyUniqueName** [comment]
If this is some sort of tradeoff, i think that should be documented somewhere

**Comment by ncannasse** [comment]
If it's a regression it needs to be addressed.

**Comment by RealyUniqueName** [comment]
Sorry, closed accidently

**Comment by RealyUniqueName** [comment]
Can this be handled as a special case like "if `try..catch` contains `return Dynamic/unknown` then keep `try..catch`" ?

**Comment by ncannasse** [comment]
TCast(e,None) should be marked by the analyzer as being able to throw exception just like TCast(e,Some t), that's the case in most static targets

**Comment by Simn** [comment]
TCast None is inserted by the compiler _very_ liberally. Changing this to have an impact on the CFG edges could have quite a bit of an impact.

I don't understand why we suddenly start defining that unsafe casts raise catchable exceptions.

**Comment by RealyUniqueName** [comment]
For me it's not about "unsafe cast errors should be catchable", but "`try..catch(e:Dynamic)` should be able to catch any error"

**Comment by RealyUniqueName** [comment]
Also this as3 code works as expected (does not throw):
```haxe
static function test():Array {
   try {
     var result:* = true;
     return result;
   } catch(e:*) {
      return [];
   }
}
```
While equal haxe code compiled to swf does not work as expected (throws exception):
```haxe
static function test():Array<String> {
   try {
     var result:Dynamic = true;
     return result;
   } catch(e:Dynamic) {
      return [];
   }
}
```

**Comment by ncannasse** [comment]
> I don't understand why we suddenly start defining that unsafe casts raise catchable exceptions.

Given that ECast can throw exceptions, it seems very weird to be able to catch them at some upper level but not in same function because of the analyzer. It's normal to considered this a bug.

**Comment by Simn** [comment]
We optimize these casts away all the time. You originally considered them to not have a side-effect in [2012](https://github.com/HaxeFoundation/haxe/commit/dd0a7778b191d674168218a245241d410fbf0052) and now it's suddenly a bad thing to do that... I really don't know what to do with this.

**Comment by ncannasse** [comment]
The original `has_side_effect` detection was not meant to eliminate try/catch. Can you show some examples on how changing that would affect the output?

**Comment by ncannasse** [comment]
We could simply say that TCast have side effects only when inside a try/catch if that can help.

**Comment by back2dos** [comment]
The way I see it this has nothing to do with `ECast`, since `cast $e` is practically equivalent to `($e : Dynamic)`. So the questions seems to be how many guarantees we give about untyped code. 

If I understand @Simn correctly, the choice seems to be between 

1. defeating the analyzer
2. accepting that untyped code requires intimate knowledge about both Haxe and the target runtime anyway (notice how when compiling to a dynamic target none of the catch clauses are ever reached)

I have a strong preference here ;)

**Comment by ncannasse** [comment]
This have bitten me today again, I think that the correct solution is to keep TCast as-it (consider it doesn't have side effects), but only remove try/catch if the code is constant (no fields access, no cast, etc.)
@Simn would that work for you?

**Comment by Simn** [comment]
You guys are crazy.

**Comment by Simn** [comment]
```haxe
class Main {
	@:analyzer(full_debug)
	static public function main() {
		var i = try {
			var i1 = haxe.Int64.ofInt(1);
			var i2 = haxe.Int64.ofInt(1);
			var i3 = i1 + i2;
			i3 * i2;
		} catch(e:Dynamic) {
			trace("Caught!");
			null;
		}
		trace("" + i);
	}
}
```

![main main-cfg](https://cloud.githubusercontent.com/assets/634365/20562338/5151de66-b183-11e6-85a5-399d8475f960.png)

Total insanity, but at least your unspecified code now behaves as unspecified.

**Comment by back2dos** [comment]
I'm with Simn here. I always thought the word "unsafe" carries some meaning. 

The same cast will not raise an exception on dynamic platforms and lead to runtime errors far from the call site. It is indeed "crazy" to cause that kind of complexity *all over the place* only to allow writing totally unportable code for which there are far cleaner alternatives.

**Comment by ncannasse** [comment]
try/catch is specified as catching both haxe and native exceptions. It now behaves as specified.

**Comment by Simn** [comment]
I'm fine with that part of the specification. What I have problems with is defining what actually causes native exceptions. We optimize away so much, but now we suddenly have to keep something because it might throw a native exception.

If you go down that road, we cannot optimize `{ a + b; }` to `{ a; b; }` either because someone might rely on the fact that the binop throws if one of the operands is a null-value. We also couldn't optimize away some write-only variable because the assignment might cause some native cast error.

This also wrecks my purity checks because if virtually anything can throw, virtually nothing is technically pure. Is that really where you want to take Haxe?

**Comment by back2dos** [comment]
For starters, I request that for dynamic platforms unsafe casts be considered side effect free. The recent improvements in the haxe/js output are stunning and give it a clear edge over other compile-to-js solutions. I care about this personally and believe it makes for a great selling point.

> try/catch is specified as catching both haxe and native exceptions. It now behaves as specified.

Can you please point me to that specification? If it exists, it means we either badly need to change it or might as well get rid of the optimizer altogether.

```haxe
try {
  trace(Math.min(1, 2));
}
catch (e:Dynamic) {
  trace("unreachable");
}
```

That trace statement is unreachable, right? Well, it turns out that prefixing the code by `untyped window.Math = {};` will make `Math.min(1, 2)` raise a "native" exception.

**Comment by ncannasse** [comment]
I think you are confusing two things. Side effects are defined by some values being modified, leading the need to invalidate some optimization cache. For instance:

```
var x = this.a + this.b;
sideEffect();
var y = this.a + this.b
``` 

If there is no side effect, we have the guarantee that `x == y` and we can optimize out the second operation. In that sense, TCast, TField etc. does not have side effects and should not be specified has having one.

However they can throw native exceptions, which does not affect the values in place, but can be caught by a try/catch. So yes I don't think try/catch should be eliminated, expect from the obvious cases such as 
`try false catch(e : Dynamic)`. 

The `Math.min` example has a side effect (trace) so it not elligible to optimization. Without the trace, it depends if the compiler has a definition of "can throw exceptions" (in which case it could optimize it out) or if just cares about "side effect" (in which case we don't know if an exception will be throw or not so we can't optimize out)

**Comment by Simn** [comment]
That still doesn't change the fact that I can scrap my purity inference because I have to assume that everything potentially throws a native exception:

```haxe
class Main {
	static public function main() {
		pointlessAdd(1, 2);
	}

	static function pointlessAdd(i1:Int, i2:Int) {
		return i1 + i2;
	}
}
```

The call gets optimized away completely because pointlessAdd is considered to be pure. Following your logic would mean that we cannot do that, because the `+` operation could throw a native exception which in turn could be caught by the user.

If that's what we're going for I don't understand why I even worked on a static analyzer. We can barely optimize anything if we have to assume that native exceptions occur and are caught as part of the specification.

**Comment by RealyUniqueName** [comment]
If this case is affects analyzer so badly, can we just add more details to [`try..catch` doc](https://haxe.org/manual/expression-try-catch.html) instead of breaking optimisations?

**Comment by RealyUniqueName** [comment]
And describe caveats in [analyzer doc](https://haxe.org/manual/cr-static-analyzer.html)

**Comment by ncannasse** [comment]
I don't have much a problem with code that might throw exception but has not side effect being removed. I only care about try/catch being removed while it should catch native exceptions, which is th problem with this issue in the first place
