### ISSUE TITLE
Compiler hanging 

### ISSUE THREAD

**Issue by sledorze** [HaxeFoundation/haxe#5785]
Compiler version from nightlies: 
haxe_2016-11-01_development_d32dd16

This code hangs the compiler forever (Js target at least).

```haxe
typedef Observable<T> = {
	function flatten<U>():Stream<U>;
};
typedef Stream<T> = {
	>Observable<T>,
	function takeUntilBy<U>(otherObs:Observable<U>):Stream<U>;
	function bufferWhileBy():Stream<Array<T>>;
};

class Main {

  public static function main() {
    var mouseMoves : Stream<Int> = null;
    mouseMoves.takeUntilBy(mouseMoves);
  } 
}
```

What is happening:

Compiler hangs forever..

What should happen:

Compiler completes.

Note:

changing the code to this make the compiler not to block:

```haxe
typedef Observable<T> = {
	function flatten<U>():Stream<U>;
};
typedef Stream<T> = {
	>Observable<T>,
	function takeUntilBy<U>(otherObs:Stream<U>):Stream<U>;
	function bufferWhileBy():Stream<Array<T>>;
};

class Main {

  public static function main() {
    var mouseMoves : Stream<Int> = null;
    mouseMoves.takeUntilBy(mouseMoves);
  } 
}
```

**Comment by sledorze** [comment]
For information, switching from typedef to interfaces fixes the compiler hanging.

**Comment by Simn** [comment]
@ncannasse: This looks like your favorite battleground.

**Comment by ncannasse** [comment]
(;_;) I'm glad it's set to to "no Milestone"

**Comment by Simn** [comment]
Minimized:

```haxe
typedef Stream<T> = {
	function bufferWhileBy():Stream<Array<T>>;
};

class Main {
	public static function main() {
		var mouseMoves:Stream<Int> = null;
		var i:Stream<Dynamic> = mouseMoves;
	}
}
```

This travels endlessly between `unify_anons`, `unify_with_access` and `unify` with the return type of `bufferWhileBy` continuously expanding.

**Comment by ncannasse** [comment]
Typically this require to store a type pair in unify_stack and check for its presence before recursing, but I think the problem here is that the type parameters application creates new distinct types each time, negating the unify_stack check, can you confirm?

If that is the case, one possibility would be to have an apply_stack which would be similar to unify_stack but would store ((t * t list) *  t) pairs, storing that for a given type t and parameters t list we have generated another t, and reuse this one instead of creating another each time.

**Comment by Simn** [comment]
Yes that seems indeed to be the problem.

I like the `apply_stack` idea, but the question is how exactly we extract values from that. We can't use physical equality, and if we employ some type equality check we're back to where we started.

**Comment by ncannasse** [comment]
`We can't use physical equality` why ?

**Comment by Simn** [comment]
I'm probably misunderstanding what exactly you mean so maybe you should just implement it.

**Comment by ncannasse** [comment]
Note : this is still reproducible

**Comment by Simn** [comment]
I have to wonder if this is permissible at all in a non-lazy environment. Shouldn't we disallow recursive typedefs if they have type parameters?

I can't see how we would solve this with a stack check because the type parameters are different on every recursion: They go from `Array<Int>` to `Array<Array<Int>>` to `Array<Array<Array<Int>>>` and so on.

**Comment by ncannasse** [comment]
I'm not even sure what to disallow here exactly :)

**Comment by Simn** [comment]
I'm not sure either. We want to stop this self-inflation, but I think that could happen across various typedefs.

Still, this probably has to be caught at definition-level. I can't see how we would handle it during unification because it's not a recursion problem where we keep coming across the same types.

**Comment by ncannasse** [comment]
I'll remove from 4.0 because I don't think it occurs a lot, still something we might want to fix at some point but not a show stopper for 4.0 release

**Comment by nadako** [comment]
Was working on #6028 and #7655 and stumbled upon this again. It's the same issue, right?

```haxe
typedef Thenable<T> = {
	function then<TOut>():Thenable<TOut>;
}

class Main {
	static function main() {
		({then: () -> null} : Thenable<String>);
	}
}
```

```
Fatal error: exception Stack overflow
Raised by primitive operation at file "pMap.ml", line 132, characters 38-43
Called from file "_build/src/core/type.ml", line 2213, characters 2-1020
Called from file "_build/src/core/type.ml", line 1759, characters 11-17
Re-raised at file "_build/src/core/type.ml", line 1768, characters 4-11
Called from file "_build/src/core/type.ml", line 1759, characters 11-17
Re-raised at file "_build/src/core/type.ml", line 1768, characters 4-11
Called from file "_build/src/core/type.ml", line 2019, characters 10-21
Called from file "_build/src/core/type.ml", line 2223, characters 4-43
Called from file "pMap.ml", line 132, characters 38-43
Called from file "_build/src/core/type.ml", line 2213, characters 2-1020
Called from file "_build/src/core/type.ml", line 1759, characters 11-17
Re-raised at file "_build/src/core/type.ml", line 1768, characters 4-11
Called from file "_build/src/core/type.ml", line 1759, characters 11-17
Re-raised at file "_build/src/core/type.ml", line 1768, characters 4-11
Called from file "_build/src/core/type.ml", line 2019, characters 10-21
Called from file "_build/src/core/type.ml", line 2223, characters 4-43
Called from file "pMap.ml", line 132, characters 38-43

etc
```

**Comment by sledorze** [comment]
Thanks guys to take care of that long standing issue 👍
