### ISSUE TITLE
DCE Removing member variables from constructor function

### ISSUE THREAD

**Issue by rjewson** [HaxeFoundation/haxe#5798]
DCE removes class variable fields from the constructor function in the JS target if they are not explicitly referenced in the constructor.  They are later added when first referenced in a method on that class.

V8 and other JS VM's keep hidden classes, dynamically adding properties to an object cause the VM to re-compile causing a momentary performance issue (frame-rate drops, GC etc)

See [http://try.haxe.org/#C2F3d](http://try.haxe.org/#C2F3d)

**Comment by Simn** [comment]
I don't understand what you consider to be the issue here.

**Comment by rjewson** [comment]
The problem is sub-optimal JS output.  The object structure should be constant otherwise you incur additional processing overhead in the VM.  Including all the fields at startup will lead to the vm creating better hidden classes, faster = faster startup, less overhead later during program execution.

**Comment by nadako** [comment]
I think OP is talking about `b` not being initialized in the constructor, so it's not about DCE. I think this was discussed on the ML before, but I don't exactly remember what the conclusion was.

PS When I think about consistent default values and field intialization, I always want to either add initializations into constructor or in into generated class prototype. Not sure what's best for V8 hidden class optimization though.

**Comment by rjewson** [comment]
The field is there without dce.

Maybe this helps: [http://mrale.ph/blog/2014/07/30/constructor-vs-objectcreate.html](http://mrale.ph/blog/2014/07/30/constructor-vs-objectcreate.html)

**Comment by nadako** [comment]
Hmm, with DCE=no, genjs creates a null-initialized field in the prototype which is not the same as initializing it in constructor.

But I think that's still not because DCE removes the field, it's because it doesn't remove something from `Type` or `Reflect` that makes genjs generate reflection support code, and thus this prototype fields.

Anyway, thanks for the link, we should read about it.

**Comment by Simn** [comment]
I'm not sure we should do anything here unless someone shows some benchmarks that suggest a measurable difference.

**Comment by ncannasse** [comment]
This has nothing to do with DCE in the sense that Haxe will output the same code for your example with DCE disable. 

What you would like is to force all variables to be set to a default value in the constructor in order to teach V8 the "form" of the object. This would require for instance initializing all Int to 0 and all Float to NaN like Flash does, but this would also break backward compatibility and produce more code output. I think this should be an user choice to do such thing, and it can be automated with macros.

**Comment by ncannasse** [comment]
@nadako DCE -no defines the `b` variable inside the class `prototype` which is different from having it in each created object in terms of memory layout (I think)

**Comment by Simn** [comment]
I don't think this is an actionable issue so I'll go ahead and close this. If someone comes forward with a benchmark showing that a change would make a difference, we can look into this again.
