### ISSUE TITLE
[C#] Std.is(object, BytesData) always false even if 'object' is BytesData

### ISSUE THREAD

**Issue by Muxeu** [HaxeFoundation/haxe#5813]
```
class BytesTest {
    public function new() {
        var bytes:Bytes = Bytes.alloc(32);
        var data:BytesData = bytes.getData();

        if(Std.is(data, BytesData)) {
            trace("I am BytesData");
        } else {
            trace("I am not BytesData");
        }
    }
}
```

Generates wrong code for C#:
```
public class BytesTest {
		
		public BytesTest() {
			unchecked {
				if (( global::haxe.io.Bytes.alloc(32).b is object[] ))
				{
				    trace("I am BytesData");
				}
				else {
				    trace("I am not BytesData");
				}
				
			}
		}
		
		
	}
```

_global::haxe.io.Bytes.alloc(32).b is object[]_ always return false because b is _byte[]_

Haxe 3.3.0-rc.1

**Comment by nadako** [comment]
I'm afraid this is a general problem with the fact that Haxe type parameter erasure doesn't play well with type checks like this, e.g. this example can be reduced to:

```haxe
typedef IntArray = cs.NativeArray<Int>;

class Main {
	static function main() {
		var a = new IntArray(10);
		if (Std.is(a, IntArray)) {
			trace("YAY");
		} else {
			trace("NAY");
		}
	}
}
```

Since `Std.is` is a function that receives a class without type parameter information as its second argument, it can't generate anything sensible (like `int[]`) from it.

Here's the AST dump for the `Std.is` call (note the `TypeExpr`).
```
[Call:Bool]
	[Field:v : Dynamic -> t : Dynamic -> Bool]
		[TypeExpr Std:Class<Std>]
		[FStatic:v : Dynamic -> t : Dynamic -> Bool]
			Std
			is
	[Local a(2968):cs.NativeArray<Int>]
	[TypeExpr cs.NativeArray:Class<cs.NativeArray>]
```

---

@Simn @ncannasse I think it's pretty bad that this goes through the compilation and even SILENTLY compiles natively on some platforms and since we probably can't support this, we should forbid `Std.is` calls with non-`Dynamic` type parameters, just like `cast(a, B)` does. I know this is awkward since `Std.is` is just a function with `Dynamic` second argument instead of proper `is` expression (which I think it should be). Alternatively we could maybe emit an error if a class with non-Dynamic type parameters is used in `TypeExpr` through a `typedef` like this. This probably would be the least invasive change.

For now I'm reassigning this to you guys for discussion, this may or may not require some handling in C# generator, depending on what the consensus is.

**Comment by ncannasse** [comment]
Yes,  `MyClass<NotDynamicType>` is not a value, so should be forbidden in catch or TTypeExpr

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
