### ISSUE TITLE
Property in extern class implements interface want getter/setter

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#5839]
I think, this must not be a error:
```haxe
interface I {
	var p(get, set) : Bool;
}
extern class C implements I {
	public var p(get, set) : Bool;
}
```

Errors:
Field get_p needed by I is missing
Field set_p needed by I is missing

**Comment by kevinresol** [comment]
you probably need to define the extern getter/setter? lik:

```haxe
extern class C implements I {
	var p(get, set) : Bool;
	function get_p():Bool;
	function set_p(v:Bool):Bool;
}
```

**Comment by ibilon** [comment]
If a variable is defined as (get, set) then it has no physical presence, meaning it's never referenced by the haxe compiler, regardless of whether it exists or not in the native class.
So you must define them so that haxe can make code for the variable usage.

If you just want the var then don't specify (get, set) and the native accessors will be called by the compiler/interpreter of the target you compile to if they exist.

**Comment by Simn** [comment]
What he said.
