### ISSUE TITLE
3.4-rc.1 inline issue with cpp

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#5855]
I ran into some inline code causing the c++ gen to inserting variables incorrectly trying to reach them via the global scope operator.

Here is an isolated test, I'm not sure if pasting the error here is ideal given it being specific to the class but the full information is on the repo in the readme. I tried to narrow it down further but I wanted to test more of the new compiler version and have limited time.

haxe `3.4.0 (git build development @ 865aa86)`
hxcpp `329e23aef9715a93c491bf2800bbf602f229ccc9`

#### [minimal test case repo](https://github.com/underscorediscovery/haxe_3.4_inline_issue)

cc @hughsando

**Comment by underscorediscovery** [comment]
I should note this worked on haxe `3.2.1`.

**Comment by hughsando** [comment]
@Simn I think this is caused by the 'return' from an inlined constructor messing with the scope of the inlined variables.  Here is a simpler example:
```} //BalancedBST


#if !display @:generic #end
class BalancedBSTIterator<K,T> {

    var tree : BalancedBST<K,T>;
    var current : T;

    //:test: toggle the inline here or above 
    inline
    public function new(_tree:BalancedBST<K,T>) {

       // Removing this line causes a weird `current variable
       if (_tree==null) return;

       if (_tree!=null && _tree.root!=null)
       {
          tree = _tree;
          current = tree.root;
       }

    } //new

    public inline function hasNext():Bool {
        return true;
    } //hasNext

    public inline function next() {
        return current;
    }

} //BalancedBSTIterator



class Test {

    static function main() {

        var bst: BalancedBST<Null<Int>, String> = new BalancedBST();
        for(string in bst) {
            trace(string);
        }
    }
}

```
If I remove the 'return' I get a very odd unused variable called `current (note:leading back-tick) which messes with the hxcpp gen too.  (shows up on '-D dump' too).

**Comment by Simn** [comment]
```haxe
class C {
	public var field:String;
	public inline function new() {
		if (Math.random() > 0.5) {
			field = "foo";
		}
	}
}

class Main {
	@:analyzer(ignore)
	static function main() {
		var c = new C();
		trace(c.field);
	}
}
```

Generated JS:

```js
Main.main = function() {
	if(Math.random() > 0.5) {
		var c_field = "foo";
	}
	console.log(c_field);
};
```

We probably even test this on JavaScript, but didn't notice the problem due to var hoisting.

Ideally, these variables would be declared in the scope that dominates all scopes the variable appears in. Unfortunately, this is not very easy to determine on our texpr structure. In the long run, I'd like to implement this in the analyzer properly, which could also be used for the code motion implementation.

For 3.4 I'll have to come up with some temporary solution.

**Comment by hughsando** [comment]
You could probably just put it in the scope where the 'new' call is.

**Comment by Simn** [comment]
This is giving me a hard time, partially because our texpr structure makes it hard to detect scopes properly. For instance, the TIf-then expression in my example is """"optimized"""" to not hold a TBlock at all.

I don't want to just dump every var declaration at top scope because that makes code output downright worse. Will have to see how to deal with this...

**Comment by Simn** [comment]
This change is not exactly one of my greater accomplishments, but it does fix the issue. It also disconnects some variable declarations from their initial assignments, but that should be fine and we can optimize this later.
