### ISSUE TITLE
Problem with enum matching when capture variable name is the same as enum instance name in haxe 3.4

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#5877]
This code was working in some not latest 3.3 release, but after updating to 3.4 it's not compiling.
Not sure if this is a bug. But IMHO local to scope variable should always hide variables from outer scopes.
```haxe
package;

private enum Foo {
	error(object:Dynamic, error:String);
}

class Main {
	static function main() {
		switch(null:Foo) {
			case error(object, error): trace(error); // error: object : Dynamic -> error : String -> _Main.Foo should be String
			//case error(object, err): trace(err); // compiles 
		}
	}
}
```

**Comment by Simn** [comment]
This is working as designed. The problem is not the trace but trying to capture something as `error`, which resolves to an enum constructor. We obviously cannot change that as that would make it impossible to match against enum values. You can force the capturing by using `case error(object, var error):` instead.
