### ISSUE TITLE
do { ... } while (false) compiles to while (true) { ...; break; } 

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#5896]
try.haxe: http://try.haxe.org/#828Cf

Source:
```haxe
class Test {
    static function main() {
        do {
            trace("hi");
            if (Math.random() < 0.5) break;
            trace("by a chance");
        } while (false);
    }
}
```
JS:
```js
Test.main = function() {
	while(true) {
		console.log("hi");
		if(Math.random() < 0.5) {
			break;
		}
		console.log("by a chance");
		break;
	}
};
```
There is no apparent reason for doing this (does Haxe have any targets that don't have a do-while\do-until loop?), it only produces interwoven branching in output code.

The issue appears to be [semi-]recent - roughly half of year ago do-while loops would still compile to do-while loops as one could expect.

In a3af62f build the last `break;` is replaced by `if (!false) break;`, which suggests that the entire thing an optimization mishap.

**Comment by Simn** [comment]
The problem with Haxe-loops is that the conditions can be complicated and then cannot be placed inside the `while(here)` in the generated code. I opted to treat all loops as `while(true)` in order to be able to place the conditional code inside the loop body, which greatly simplified the internal handling.

At some point I tried to reconstruct do-loops at the end, but that lead to some problem which I cannot remember right now. I'm willing to look into this again though, also because there's still a problem with complex conditions + `continue` statements (I think we even discussed that before in some other issue).

**Comment by YellowAfterlife** [comment]
To add: highlighted [here](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#6-infinite-loops-with-deep-logic-exit-conditions-or-unclear-exit-conditions), `while (true)` \ `for(;;)` loops may cause entire function to not be optimized in V8, adding to reasons to keep generated code simple, where possible.

**Comment by Simn** [comment]
To illustrate the problem, consider code like this:

```haxe
class Main {
	static function main() {
		do {
			trace("hi");
			if (Math.random() < 0.5)
				break;
			trace("by a chance");
		} while ({
				var a = getValue();
				trace(a);
				a == 12;
			});
	}

	static function getValue() {
		return 12;
	}
}
```

The analyzer transformation moves the conditional block into the loop body, which is good for code generation in general:

```js
Main.main = function() {
	while(true) {
		console.log("source/Main.hx:4:","hi");
		if(Math.random() < 0.5) {
			break;
		}
		console.log("source/Main.hx:7:","by a chance");
		var a = Main.getValue();
		console.log("source/Main.hx:10:",a);
		if(!(a == 12)) {
			break;
		}
	}
};
```

However, we cannot simply take the exit condition and put it in a `} while(condition)` because then we run into scoping problems (not on JS, but on targets with sane scoping behavior).
