### ISSUE TITLE
Abstract cast for function without explicit return type

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5913]
Not a regression, same behaviour since 3.2

Abstract casts for a function require explicit return type to work.

```haxe
import haxe.ds.Option;

class Test {
  static function main() {
    var r:Recover<Bool> = function() return true; // fails: Bool should be haxe.ds.Option
    var r:Recover<Bool> = function():Bool return true; // works
  }
}

@:callable
abstract Recover<T>(Void->Option<T>) from Void->Option<T> {
  @:from public static function ofConst<T>(f:Void->T):Recover<T>
    return function () return Some(f());
}
```

**Comment by RealyUniqueName** [comment]
This seems like "by design".
Function signature is unified with `Recover<Bool>` first (which makes the monomorph of return type to be bound to `Option<T>`) and then function body is typed.

If I just change the order to type the function body before trying to unify the function with `Recover<Bool>` then everything explodes (e.g. can't even compile haxelib).
If I detect function return type is monomorph and after unifying the function with `Recover<Bool>` I type the function without using the unification result, and then try to unify the unification result with the return type deduced during function typing - everything explodes again.

@simn ?

**Comment by RealyUniqueName** [comment]
Simn confirmed my conclusion. So, this is by design.
