### ISSUE TITLE
FileSystem.exists() does not seem to be unicode-aware

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFoundation/haxe#5935]
Reproduction case:

1) Create this file on your hard drive (I'm using windows):
```C:\Денисカタカナ冰淇淋\api\test.txt```

2) From your code, using hxcpp target, call:
```FileSystem.exists("C:\Денисカタカナ冰淇淋\api\test.txt")```

**What should happen:**
The function should return true

**What happens instead:**
The function returns false

**Speculation:**
The error is in this call:
https://github.com/HaxeFoundation/haxe/blob/875ad19432abc2cec6b345cc49a880f5c7f3c98a/std/neko/_std/sys/FileSystem.hx#L34

To this function:
https://github.com/HaxeFoundation/haxe/blob/875ad19432abc2cec6b345cc49a880f5c7f3c98a/std/neko/_std/sys/FileSystem.hx#L103

And this function:
https://github.com/HaxeFoundation/haxe/blob/875ad19432abc2cec6b345cc49a880f5c7f3c98a/std/haxe/io/Path.hx#L262

They use standard string functions rather than UTF-aware functions.

Not sure what the proper solution is, but left as-is, using `FileSystem.exists()` naively on the computer of a random person in, say, Russia, China, Japan, etc. could very well return false on requests when opening files from .e.g. their documents directory, which likely includes their username.

**UPDATE**

If you skip the `FileSystem.exists()` check and just use `File.getContent()` directly within a try/catch block to handle the non-exist case, you get an exception:

```[file_contents,C:\Денисカタカナ冰淇淋\api\test.txt]```

So it seems there is a need for UTF-aware filepath handling functions. I understand it might be a burden to change the standard library, but perhaps some new functions could be added, or provided in a separate library?

**Comment by starry-abyss** [comment]
Happens for me too on both Haxe 3.2.1 and Haxe 3.4-rc2.
I didn't use you filename, since I already have some files with Russian and English names. Also I just used filenames at the root directory instead of long paths.
Also Haxe doesn't allow me to use single slashes like: D:\Безимени1.ods, had to use D:\\Безимени1.ods instead.

**Comment by ncannasse** [comment]
Can you try with HashLink? It's using UTF16 system functions

**Comment by larsiusprime** [comment]
Sure, what's the best way to compile a simple app with hashlink? I've never used it before.

**Comment by Justinfront** [comment]
larsiuprime

It's pretty similar to Neko.
If your on windows get the hl.exe 
[hl downloads](https://github.com/HaxeFoundation/hashlink/releases)
or on linux / mac you can make yourself, simpler if your just **make hl** than **make all** since for **all** you need sdl etc... stuff installed which with my attempt with macports did not work but probably simpler on linux. 
```
git clone https://github.com/HaxeFoundation/hashlink.git
cd hashlink
make hl
```
you may need to specify the ARCH=32 or similar, and for the clone can't remember if there are submodules ( --recursive ).
Once you have hl make sure it can be found on terminal or put it next to your code.
For your actual program, it's the same as running neko vm using an hxml file and nightly haxe.
```hxml
-hl output.hl 
-main Main
# mac probably...
-cmd ./hl output.hl
# windows probably...
-cmd hl.exe output.hl
```
Alternatively read http://hashlink.haxe.org/

Hope that helps, probably simpler than you thought unless your on a mac and want to do graphics with it!

**Comment by R32** [comment]
Actually, this problem has been present in the hxcpp.

```haxe
class Test {

	static function main() {
		var s = "./Денисカタカナ冰淇淋/api/test.txt";
		Sys.print("file: " + s);
		Sys.print(" == " + sys.FileSystem.exists(s) + "\n");

		for (f in sys.FileSystem.readDirectory("./")) {
			if (f.length > 8) {
				Sys.print("dir: " + f);
				Sys.print(" == " + sys.FileSystem.exists(f) + "\n");
			}
		}
	}
}
```
output:

![x](https://cloud.githubusercontent.com/assets/6825113/23610360/1f08ddc6-02ad-11e7-9d21-c0aff09abff9.png)

**Comment by jgranick** [comment]
Fixed in HXCPP:

https://github.com/HaxeFoundation/hxcpp/commit/795f952b52bed7b2a7b1fc17d608bdc543acfa3c
https://github.com/HaxeFoundation/hxcpp/commit/d48ac3e2a478df1e6b1451d4fc84dd6e23d97496

**Comment by cjmxp** [comment]
When can hashlink be included in the haxe？

**Comment by RealyUniqueName** [comment]
@Aurel300 is this covered by our new unicode sys tests?

**Comment by Aurel300** [comment]
@RealyUniqueName It is:

https://github.com/HaxeFoundation/haxe/blob/99eb84dee6fb7d25fa4f35f1943d058f0cf5665c/tests/sys/src/TestUnicode.hx#L161

But the test is disabled temporarily for C++ (#8400) and C# (#8247). The C++ issue in particular is probably a superset of this one, so perhaps close this issue?

**Comment by RealyUniqueName** [comment]
Yeah, thanks
