### ISSUE TITLE
problem with cache compiler server and macro rebuild with lib partials

### ISSUE THREAD

**Issue by francescoagati** [HaxeFoundation/haxe#5998]
hello i have a problem with lib partials haxe 3.4 and cache compilation server. the problem is that the lib partials use a static var map called partials for store the fields of classes mixin (see this line https://github.com/FuzzyWuzzie/haxe-partials/blob/master/partials/Partials.hx#L58). the problem is that on haxe 3.4 when i recompile for the second time the var partials is recreated. this happens in haxe 3.4 but in haxe 3.2 i haven't this problem. The AST of class Partials is reprocessed and reloaded also if the file isn't be touched

**Comment by francescoagati** [comment]
i have understand the problem. for some stranges motives is like if the vm is completely reload.
also the variables put in __dollar_loader are erased

**Comment by nadako** [comment]
I came to conclusion that using static vars to save state in macro context is totally unsafe and can lead to all kinds of issues.

@ncannasse could you maybe write a blog post explaining particularities about saving state in macros, when we can do what and how to solve common tasks of reusing data in macros without serializing and saving it to disk? :)

**Comment by francescoagati** [comment]
Yes but this is a problem of haxe 3.4. In haxe 3.2 work really good. What is change from 3.2 to 3.4?
I have try to hack also the objects __dollar_* of the neko  vm for try to save the state. But at some points all the variables of the neko vm are resetted. I think there is a bug in some parts of the completion server because this in have 3.2 don't happen

**Comment by francescoagati** [comment]
I think @back2sos use cachingin tink_macro

**Comment by francescoagati** [comment]
@back2dos

**Comment by nadako** [comment]
@francescoagati as I understood, it was never safe to rely that state is not reset. By the way, it's not a nekovm, macros are run by their own interpreter in the compiler. :)

**Comment by back2dos** [comment]
It is true that I try to use caching as much as possible in tink. Most of the time I have no idea what I'm doing though. It's all just trial and error and usually just randomly breaks with a Haxe update :D

**Comment by nadako** [comment]
> It is true that I try to use caching as much as possible in tink. Most of the time I have no idea what I'm doing though. It's all just trial and error and usually just randomly breaks with a Haxe update :D

My feelings precisely. :)

**Comment by francescoagati** [comment]
understood. yes sorry the interpreter. but what is the right mode for having caching data in compiler server?

**Comment by nadako** [comment]
> what is the right mode for having caching data in compiler server

that's what I'd like to know too hence I tried to summon @ncannasse as the main user of the comp.server :)

**Comment by ncannasse** [comment]
A short answer for now: the macro interpreter context is reused when possible, but depending on the macro call order and dependencies, this mean that the context might be trashed and a new one created during compilation. That was already the case in 3.2 and 3.3. 

It it then not good to rely on static variables when using macro because:
- they might not be reset between compilations
- they might be reset during compilations
(actually they are not really "reset", we are simply using a new fresh macro context)

It also not a good strategy because only a part of your classes might be recompiled when using the compiler cache, making it hard to correctly manage the static state since between compilations the order and amount of macro calls might vary.

You should consider storing per-type data into metadata instead of static var, this is considered the best way to deal with it.

**Comment by francescoagati** [comment]
thanks Nicolas.

**Comment by francescoagati** [comment]
thanks to all. resolved with serialization of fields ast in file system
