### ISSUE TITLE
[display] "Context has no field" errors in @diagnostics

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6000]
Originally reported here: https://github.com/vshaxe/vshaxe/issues/85

Even if the entire module is wrapped in `#if macro`, any usage of `haxe.macro.Context` fields seems to result in "has no field" errors:

![image](https://cloud.githubusercontent.com/assets/2620907/22609536/e0b55e7c-ea61-11e6-9b94-43f97483fd15.png)

Same with `Context.warning()`, `Context.error()` etc.

```haxe
#if macro
import haxe.macro.Expr;
import haxe.macro.Context;

class Macro {
	public static function build():Array<Field> {
		return Context.getBuildFields();
	}
}
#end
```

```
haxe --display Macro.hx@0@diagnostics
```

```
[{"file":"C:\\GitHub\\HaxeRepro\\source\\Macro.hx","diagnostics":[{"kind":2,"severity":1,"range":{"start":{"line":6,"character":9},"end":{"line":6,"cha
racter":31}},"args":"Class<haxe.macro.Context> has no field getBuildFields"}]}]
```

**Comment by FrancisBourre** [comment]
It's a very annoying one daily when you use macros a lot.

**Comment by waneck** [comment]
I'm having the same problem, and it's pretty annoying. @Simn if you're okay with a workaround, we could probably add the `Context`, `Tools`, etc API stubs to the other platforms. They still wouldn't work of course, but I think this provides a lot of advantages - for example, being able to have good completion when working on macros. If you're okay with that change, I can provide a PR

**Comment by Simn** [comment]
I don't have a solution for this. We should probably lose the `#if macro` hack in the parser, but that comes with its own set of problems.

**Comment by nadako** [comment]
I believe @waneck is talking about losing `#if (neko || eval)` guard from the body of `Context` class, so all methods are defined for all targets, which makes sense to me given that we still can't figure out whether current display module is supposed to be typed in macro context or not.

**Comment by waneck** [comment]
Yeah, that was what I was talking about. I kinda like this alternative, as I think it will not only solve the diagnostics issues, but it will also improve autocompletion when you are writing the macro code itself

**Comment by ncannasse** [comment]
I'm fine with it, but maybe we should have a way to make sure it throws
something when it's finished compiled instead of runtime (not sure when/how)

**Comment by nadako** [comment]
There's more guards to add: https://github.com/HaxeFoundation/haxe/commit/64b861845234bb089e1abe453da76c86791740fb#commitcomment-24437559

**Comment by Doppp** [comment]
I'm not sure if this is related but I'm getting this in HaxeDevelop too, albeit unrelated to macros. I created a new class called Helper in the same directory as another class called Model and used one of the methods in the Helper class in Model and get this error. I am new to Haxe so it might be that I'm doing something stupid but I'm struggling to rectify this issue.

![haxedevelop_2018-02-26_21-52-42](https://user-images.githubusercontent.com/627410/36674016-bbcf78d0-1b3f-11e8-9c79-51b30b140d68.png)

**Comment by RealyUniqueName** [comment]
Try asking for help at community.haxe.org

**Comment by neillrobson** [comment]
I seem to be running into this same issue (with `Context` in particular). I'm on Haxe 4.1.4. Just using `Context` in a raw Haxe project seems to work fine (no errors in VSCode, no diagnostic issues reported on command line, compiles and runs as expected). However, when trying to use `Context` in a Lime/OpenFL project, this exact issue arises:

![image](https://user-images.githubusercontent.com/6138168/103490626-2fd3e000-4deb-11eb-926b-688606f48794.png)
![image](https://user-images.githubusercontent.com/6138168/103490642-3f532900-4deb-11eb-9527-c4b86fed3138.png)

My intuition says that the tool delegating to Haxe diagnostics is simply not defining the `display` compiler flag somewhere along the line, but I am struggling to pinpoint that location. When I hover over the flag, I get a value of `"1"` rather than _not defined_ for the others:

![image](https://user-images.githubusercontent.com/6138168/103490707-aa9cfb00-4deb-11eb-8298-82348d61562a.png)

Furthermore, when I run diagnostics on the command line (on a copy of the file, outside of the Lime/OpenFL project), I get the same errors:

```
$ haxe --display AssetLoader.hx@0@diagnostics
[
    {
        "file": "C:\\Users\\Neill\\Downloads\\AssetLoader.hx",
        "diagnostics": [
            {
                "kind": 2,
                "severity": 1,
                "range": {
                    "start": {
                        "line": 13,
                        "character": 16
                    },
                    "end": {
                        "line": 13,
                        "character": 40
                    }
                },
                "args": "Class<haxe.macro.Context> has no field registerModuleDependency"
            },
            {
                "kind": 2,
                "severity": 1,
                "range": {
                    "start": {
                        "line": 17,
                        "character": 42
                    },
                    "end": {
                        "line": 17,
                        "character": 56
                    }
                },
                "args": "Class<haxe.macro.Context> has no field getBuildFields"
            },
            ...
        ]
    }
]
```

I can post a new issue on the Lime/OpenFL extension page, but since this GH issue seems to be the canonical location for discussing, I thought I'd post my experience here first.

**Comment by RealyUniqueName** [comment]
@neillrobson that may be an instance of #9977

**Comment by neillrobson** [comment]
@RealyUniqueName That report looks promising. I can certainly pull up my dummy/test project later today to see if the same issue arises.

However, I don't see any action steps to be taken on that thread. Other than trying for reproduction, is there any other action that would be helpful for me to take to assist in nailing this down?

**Comment by RealyUniqueName** [comment]
Yep. Post your dummy project there, please.
