### ISSUE TITLE
[js] `Browser.getLocalStorage()` check

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#6050]
If you are browsing private on iOS, localstorage is available but you cannot write in it. It'll throw "QUOTA_EXCEEDED_ERR: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota."

This can be solved in the detection of localstorage by trying to write something in storage:

Can the implementation of `Browser.getLocalStorage()` be changed to:
```haxe
  	/**
	 * Safely gets the browser's local storage, or returns null if localStorage is unsupported or
	 * disabled.
	 */
	public static function getLocalStorage() : Storage
	{
		try {
			var s = window.localStorage;
			s.getItem("");
			var key = "" + Math.random();
			s.setItem(key,key);
			s.removeItem(key);
			return s;
		} catch( e : Dynamic ) {
			return null;
		}
	}
```

**Comment by nadako** [comment]
But it's available at least for reading. I don't think we should add this kind of checking to the generic "get" function. Also we can't be sure that this "random" key won't clash with something existing one, effectively corrupting data in a mere "getLocalStorage" function... 

I'm leaning towards that this should be checked by the user.

**Comment by nadako** [comment]
BTW who makes decisions about JS stuff nowadays?

**Comment by markknol** [comment]
For me localstorage is "unsupported" when you can't read nor write, there is nothing to read when you can't write.

**Comment by fullofcaffeine** [comment]
> BTW who makes decisions about JS stuff nowadays?

+1 Who has the ownership of the JS target and the long-term vision for it? I remember it was @aduros, if I'm not mistaken, right?

Is the long term vision/goals being documented/discussed somewhere, besides evolution? 

It'd be nice to have this crystal clear, as the JS target is one of (if not the) most important target, alongisde `hxcpp`.

**Comment by dagnelies** [comment]
IMHO I'd rather throw a "LocalStorage unsupported" exception, it's more explicit. Or leave it like it is. Returning null would just result in a more difficult to debug code, especially if minified.

**Comment by fullofcaffeine** [comment]
> BTW who makes decisions about JS stuff nowadays?

So? Who has the ownership of the JS generator now?

**Comment by back2dos** [comment]
I don't really like the idea of having the same result if a feature is not supported vs. when it is disabled. Those things are *fundamentally* different. If local storage is not available, you can still try to fit the data into a cookie or what not. If local storage is explicitly *disabled*, e.g. because user is in private browsing, then you simply need to be aware of that.

**Comment by back2dos** [comment]
@nadako it's funny you should ask this:

> BTW who makes decisions about JS stuff nowadays?

Personally I've always assumed it was you ;)

**Comment by nadako** [comment]
Nah, I just commit random stuff mostly, but yeah, I guess i could maintain it.

**Comment by markknol** [comment]
The idea of this function is to get a usable localstorage if it is usable without runtime errors. If you want errors to be trown then you should just do window.localStorage yourself and catch the possible errors. 
For me "supported" should be "usable" for this convenience method. In private mode there is no need to know if its supported when its unusable. Then you have to try/catch again, which is silly in my opinion.
@nadako can I PR it? It's not a big dramatic change.

**Comment by back2dos** [comment]
@markknol I disagree, but whatever. You're right that I can just not use this method. The code you added should be guarded by `if (s.length == 0)` or something. Otherwise the check will return no storage if the storage is full - meaning that you have a storage stuffed with data but you just get `null` instead \o/

**Comment by dagnelies** [comment]
If it was me, I'd rather enhance the `Browser.getLocalStorage()` to:

1. make the additional write check like you said
2. more importantly, throw exceptions instead of returning null

Swallowing exceptions just makes code harder to debug since it hides the real cause (unsupported? disabled? security setting?) and lead to a null pointer exception somewhere else, which can be tough to debug on minified code. With exceptions, you can also act differently depending on the cause.

**Comment by markknol** [comment]
@back2dos thats a good point, so to confirm lets go for this?

```
try {
	var s = window.localStorage;
	s.getItem("");
	if (s.length==0) {
		var key = "" + Math.random();
		s.setItem(key,key);
		s.removeItem(key);
	}
	return s;
} catch( e : Dynamic ) {
	return null;
}
```

**Comment by back2dos** [comment]
@markknol Yeah, I think that could work.

@dagnelies you're making good points, but starting to throw exceptions is effectively an API change, so it will have to wait for Haxe 4. If we're going to break the API, I'd rather return an `enum { Available(s:Storage); Disabled; NotImplemented; }` because that's far more explicit. But right now all we get to decide is when to return `null` and when not to ;)

**Comment by mockey** [comment]
@markknol @back2dos 
`if (s.length==0) {`
I don't understand this. How does checking `localStorage.length == 0` guarantee that it's not full? It only means it is empty. There can be something stored already (which makes `length > 0`), can't it?
Maybe you didn't see that this `getLocalStorage` function is to return the `localStorage` object or `null` not any value...

Generally a check like this is not a good idea IMO, especially in the std-lib. In case of localStorage you have to handle reading and writing separately anyway. A full localStorage (or on iOS in private mode) is still fine for reading, just not for writing. Maybe even for replacing keys with the same sized value, not sure. You have to `try/catch` every write to make sure it really gets written.
