### ISSUE TITLE
DCE removes parent constructor invocation.

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6062]
```
class Test {
    static function main() {
        var child = Type.createInstance(Child, []);
      	child.childFn(); //this one works.
        child.parentFn();  //Error: parentFn is not a function
    }
}

class Parent {
    public var parentFn = function() {};
    function new() {}
}

class Child extends Parent {
    public var childFn = function() {};
}
```
http://try.haxe.org/#89Df4
Perhaps constructor should never be DCE'd if class is not DCE'd completely.

**Comment by SlavaRa** [comment]
This is the very biggest problem for our project :(

**Comment by nadako** [comment]
It's not about parent constructors, it's a about contructors in general and is kind of expected behaviour, since you don't use the ctor and don't mark your classes with `@:keep` either. For example, the following `trace` will be removed too:

```haxe
class Test {
    static function main() {
        var child = Type.createInstance(Parent, []);
        child.parentFn();        
    }
}

class Parent {
    public var parentFn = function() {};
    function new() {
        trace("hi");
    }
}
```

At later compilation stages it creates a new constructor so it can move member var initialization there, that's why `parenFn/childFn` are present. Arguably it should not generate those inits as well, since from the compiler's point of view, that class can never be constructed, but I think at that point it's not easy to determine if there was a constructor or not originally.

**Comment by RealyUniqueName** [comment]
So either Haxe should not generate those inits (and it looks like this is the correct behavior), or generate parent constructor invocation. Fix is required anyway )

**Comment by RealyUniqueName** [comment]
Is it possible to automatically add `@:keep` to classes passed to `Type.createInstanct()`?

**Comment by nadako** [comment]
> Is it possible to automatically add @:keep to classes passed to Type.createInstanct()?

Not sure that would add anything but confusion, since you don't normally use `Type.createInstance` passing the type to it directly (since you'd just do `new Cls` in that case).

**Comment by RealyUniqueName** [comment]
Agree

**Comment by Simn** [comment]
Maybe we should indeed keep the constructor as soon as we keep an instance field. The assumption that if we use an instance field, we have to construct an instance at some point (and hence use the constructor) seems quite sound.
