### ISSUE TITLE
[cpp] Regression of externs, caught in relation to casts of Array<Float> to Array<cpp.Float32>

### ISSUE THREAD

**Issue by dazKind** [HaxeFoundation/haxe#6080]
While porting my engine to 3.4 I noticed a strange issue concerning the generated code of an extern that involves casting Array\<Float\> to Array<cpp.Float32>. In the sample below are 2 cases. 

The first case doesnt cast correctly and thus reading the Pointer on the cpp-side will yield basically the double bytes. 

In the second case it's working correctly bc it generates a temp-var with the correct type thus the conversion will take place. Funny enough, this temp-var will only appear if you keep the `_value.length/16` parameter inside the extern-call. If you replace it with say `0` the result will be faulty omitting the temp-var as in the first case above.

Sample code:
```haxe 

/*
build.hxml:

-main Main.hx
-cpp cpp/
-debug
*/

import cpp.Float32;

extern class GL {
    inline static function uniform4fv(_value:Array<cpp.Float32>):Void
        untyped __cpp__("myUniform4fv((const float*)&({0}[0]))", _value);

    inline static function uniformMatrix4fv(_a:Int, _b:Bool, _value:Array<cpp.Float32>):Void
        untyped __cpp__("myUniformMatrix3fv({0}, {1}, {2}, (const float*)&({3}[0]))", _a, _value.length/16, _b, _value);
}

@:cppFileCode("
    #include <cstdio>

    void myUniform4fv(const float *_v) {
        printf(\"_v[3] = %f \\n\", _v[3]);
    }
    void myUniformMatrix3fv(int _a, int _b, bool _c, const float *_d) {
        printf(\"_d[3] = %f\", _d[3]);
    }
")
class Main {
    static function main() {
        var vec4:Array<Float> = [1.0, 2.0, 3.0, 4.0];
        var mat44:Array<Float> = [1.0, 2.0, 3.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];
        
        GL.uniform4fv(cast vec4);

        GL.uniformMatrix4fv(0, false, cast mat44);
    }
}

```

The output will read:
> _v[3] = 2.000000
> _d[3] = 4.000000

It should read:
> _v[3] = 4.000000
> _d[3] = 4.000000

Generated cpp:
```cpp
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_35_main)
HXLINE(  36)		::Array< Float > vec4 = ::Array_obj< Float >::fromData( _hx_array_data_332f6459_1,4);
HXLINE(  37)		::Array< Float > mat44 = ::Array_obj< Float >::fromData( _hx_array_data_332f6459_2,16);
HXLINE(  39)		myUniform4fv((const float*)&(vec4[0]));
HXLINE(  41)		{
HXLINE(  41)			::Array< float > _value = mat44;
HXDLIN(  41)			myUniformMatrix3fv((int)0, ((Float)_value->length / (Float)(int)16), false, (const float*)&(_value[0]));
            		}
            	}
```

*Edit*: Tested with 3.4rc2 & latest hxcpp

**Comment by Simn** [comment]
You shouldn't rely on the compiler creating temporary variables for you. I'm thinking that this worked in older Haxe versions only incidentally because the inliner created these temp vars in order to preserve side-effect order. That's probably also the reason why the `_value.length/16` makes a difference because it introduces something that might be influenced by another function argument.

This strikes me as a case of inaccurate externs and relying on unspecified semantics. However, I acknowledge that it is indeed perceived as a regression, so we have to find a solution. @hughsando, what's your take on this?

**Comment by ncannasse** [comment]
Does removing the GL "inline" work?

**Comment by dazKind** [comment]
@ncannasse Unfortunately not. Since it's an extern class it exist doesnt in the compiled code.

**Comment by hughsando** [comment]
I can't promise any consistency when "untyped `__cpp__`" is used, since anything might go in there.

The rule from now on is simple: Use accurately typed "@:native" functions.  Do not use untyped `__cpp__`.
If you follow this rule, I can guarantee compatibility for future versions. Note that this might require me to add some types if we come across stuff that can't be accurately described.
eg:
```haxe
import cpp.Float32;

extern class GL {
    @:native("myUniform4fv")
    static function uniform4fv(_value:Array<cpp.Float32>):Void;

    @:native("myUniformMatrix3fv")
    static function uniformMatrix4fv(_a:Int, c_:Bool, _value:Array<cpp.Float32>):Void;
}

@:cppFileCode("
    #include <cstdio>

    void myUniform4fv(Array<float> v) {
        float *_v = &v[0];
        printf(\"_v[3] = %f \\n\", _v[3]);
    }
    void myUniformMatrix3fv(int _a, bool _c, Array<float> v) {
        float *_d = &v[0];
        printf(\"_d[3] = %f\", _d[3]);
    }
")
class Main {
    static function main() {
        var vec4:Array<Float> = [1.0, 2.0, 3.0, 4.0];
        var mat44:Array<Float> = [1.0, 2.0, 3.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];
        
        GL.uniform4fv(cast vec4);

        GL.uniformMatrix4fv(0, false, cast mat44);
    }
}

```

Note that this code is actually nicer than the untyped code, apart from the hxcpp Array showing up in the interface functions.  In these cases, I suggest you make an (cpp) inline trampoline function to call an external API with types "float *" etc.  This is an equivalent about of messiness as in the `__cpp__` code.

**Comment by dazKind** [comment]
Wow thanks for the useful insights! I'll definitely keep them in mind for my future extern work. 

For the moment I think I'll stick to using an explicitly typed temp-var + untyped __cpp__ in the inlined function. At least for all my current opengl-externs. 

```haxe
extern class GL {

    inline static function uniform4fv(_value:Array<Float>):Void {
        var tmp:Array<cpp.Float32> = cast _value;
        untyped __cpp__("myUniform4fv((const float*)&({0}[0]))", tmp);
    }

    inline static function uniformMatrix4fv(_a:Int, _b:Bool, _value:Array<Float>):Void {
        var tmp:Array<cpp.Float32> = cast _value;
        untyped __cpp__("myUniformMatrix3fv({0}, {1}, {2}, (const float*)&({3}[0]))", _a, tmp.length/16, _b, tmp);
    }
}
```

```cpp
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_36_main)
HXLINE(  37)		::Array< Float > vec4 = ::Array_obj< Float >::fromData( _hx_array_data_332f6459_1,4);
HXLINE(  38)		::Array< Float > mat44 = ::Array_obj< Float >::fromData( _hx_array_data_332f6459_2,16);
HXLINE(  40)		{
HXLINE(  40)			::Array< float > tmp = vec4;
HXDLIN(  40)			myUniform4fv((const float*)&(tmp[0]));
            		}
HXLINE(  42)		{
HXLINE(  42)			::Array< float > tmp1 = mat44;
HXDLIN(  42)			myUniformMatrix3fv((int)0, ((Float)tmp1->length / (Float)(int)16), false, (const float*)&(tmp1[0]));
            		}
            	}
```

**Comment by Simn** [comment]
I guess we can close here.
