### ISSUE TITLE
[feature request of js] some like @:onlyforStaticExtension

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#6096]
I think this is useful for write some extern class for js

```js
using Main.ES6Array;

class Main {
	static function main() {
		var a = [];
		a.fill(0, 1, 2);
	}
}

extern class ES6Array {
	@:onlyforStaticExtension
	static function fill<T>(a: Array<T>, value:T, ?start: Int, ?end:Int): Array<T>;
}
```
current ouput:
```js
ES6Array.fill(a,0,1,2);
```
expected output:
```js
a.fill(0, 1, 2);
```

**Comment by Simn** [comment]
You can do this:

```haxe
extern class ES6Array {
	static inline function fill<T>(a: Array<T>, value:T, ?start: Int, ?end:Int): Array<T> {
		return untyped __js__("{0}.fill({1}, {2}, {3})", a, value, start, end);
	}
}
```

However, this is probably going to cause problems with missing optional arguments because `null` is inserted in that case. This has been a long-standing problem and I'm still not sure what a good solution is.

Still, any compiler-feature would have to solve  this problem as well. Maybe there's a case to be made in favor of something like `Js.nativeCall("{0}.fill", a)(value, start, end)` which deals with optional arguments appropriately.

**Comment by Simn** [comment]
Right, that's actually good enough. The optional argument situation is a separate issue and I'm not sure it's viable in the first place, so I'll go ahead and close here.
