### ISSUE TITLE
[lua] Enums and  @:expose

### ISSUE THREAD

**Issue by Drabuna** [HaxeFoundation/haxe#6099]
I use enums quite a lot and according to documentation I should use @:expose if I want to expose this enum to be accessible outside of the generated code scope:

`@:expose
enum Color{
    Red;
    Green;
    Blue;
    Yellow;
`

In generated code enum is not exposed. This is problematic, so I have to do workarounds and expose them using:

`
static function __init__(){
untyped __lua__('_hx_exports["enums"]["Color"] = enums.Color');
}
`

Should expose behave normally and just expose the enums?

**Comment by nadako** [comment]
Yeah, looks like it's only implemented for classes and static fields.

**Comment by jdonaldson** [comment]
I hadn't considered exposing enums to other lua code, if only because I couldn't think of use cases.  How were you planning to use this?

**Comment by Drabuna** [comment]
@jdonaldson Imagine you have a function in haxe that will return an enum as a result. In your lua code you want to run different logic based on which enum value was returned. It would be very nice if you can just reuse enums for comparison.

**Comment by jdonaldson** [comment]
Yeah, that seems like a good use case.   Here's my train of thought on supporting that:

You're talking about a function that returns an enum.  You should still be able to export that function, and get access to the enum, right?

It's worth mentioning that haxe enums are considerably more sophisticated than enums from other languages.  In fact, they're a form of a [GADT](https://en.wikipedia.org/wiki/Generalized_algebraic_data_type).  The runtime construct for them is actually a table, rather than a simple string value.  You'd be returning a table, which may not be ideal for other lua code to deal with.

That said, it's possible to get haxe to use simple value types (strings, ints, etc.) for enums. You'll need to use [abstract enum types](https://haxe.org/manual/types-abstract-enum.html).

Does this help at all?  I understand that there's some obstacles for getting haxe and lua to integrate well together.  Thanks for giving us feedback here, we'll try and streamline things better as we move forward.

**Comment by Drabuna** [comment]
Yeah, I've noticed that enum is actually a table where the first element is an int value and second one is a string name (or the other way around).
Will @:expose work for abstract enum types?

**Comment by jdonaldson** [comment]
@:expose should work on a method that returns the enum type... you don't need to expose the enum itself to lua, you can just use strings/numbers/etc. there

**Comment by jdonaldson** [comment]
I'm going to close this, I don't see anything actionable.
