### ISSUE TITLE
neko.dll missing from Haxe 3.4.2 binaries installaiton

### ISSUE THREAD

**Issue by ashes999** [HaxeFoundation/haxe#6130]
From haxe.org > Download > Windows Binaries, I get redirected to [this zip file](http://haxe.org/download/file/3.4.2/haxe-3.4.2-win.zip/). When I download it, it doesn't seem to include neko.

When I run `haxelib list`, I get an error that `This program can't start because neko.dll is missing from your computer. Try reinstalling the program to fix this problem.`

Is this by design? If so, is there any other way to just download the required DLLs to make `haxelib` run with the binaries distribution?

**Comment by andyli** [comment]
Haxe still depends on Neko, so you will have to install Neko first. The Windows installer installs Neko for you. If you use the zip archive, you may download and config Neko manually with the Neko zip archive available at http://nekovm.org/download.

**Comment by ashes999** [comment]
@andyli thanks, that link is exactly what I was looking for.

**Comment by Tetralux** [comment]
Came across this exact issue recently when trying out Haxe for the first time.
After spending a fairly long time trying to figure out how to use the CLI, this issue caused me to give up.

At no point is it made clear that you need anything more than the zip.

I suggest that this information should be made very obvious on the download page.

---

The message you get about the missing DLL, ideally would also prompt you to install it seperately, rather than the generic "reinstalling may fix this problem" text.

It's also worth noting that since I had no intention of using the Neko VM over the other options, it might be a handy if the loading of this DLL (and any others like it) was optional, and instead, its absence simply disables the appropriate functionality.
In this case, you would just be unable to use the Neko VM as a target.
