### ISSUE TITLE
[swf] Map.iterator.next() yields repetitive thing

### ISSUE THREAD

**Issue by buckle2000** [HaxeFoundation/haxe#6141]
See https://github.com/HaxeFlixel/flixel/issues/2048#issuecomment-289811168
[Current document](http://api.haxe.org/Iterator.html?#next) of `Iterator.next()` is untrue for flash:
> ... iterators should not require a call to hasNext() before the first call to next() if an element is available.

**Comment by Gama11** [comment]
Here's a more complete issue report, since I was already in the process of writing one:

_______

```haxe
class Main {
    public static function main() {
        var iterato = ["foo" => "bar", "bar" => "foo"].iterator();
        trace(iterato.next(), iterato.next());
    }
}
```

From my understanding, this should always print either `foo, bar` or `bar, foo` (as maps are unordered), since the docs of `next()` state:

>Returns the current item of the Iterator and **advances to the next one**.

(http://api.haxe.org/Iterator.html?#next)

On the `swf` target, this is not the case, it prints `bar, bar` there. JS, Python, CPP and Neko all behave as expected.

If this is working as intended, the docs should be made clearer.

**Comment by Gama11** [comment]
C# is producing some weird results here too:

```
trace(iterato.next(), iterato.next(), iterato.next());
```

>Main.hx:4: null,bar,foo

This definitely conflicts with the spec IMO:

>On the other hand, iterators should not require a call to hasNext() before the first call to next() if an element is available.

(http://api.haxe.org/Iterator.html?#next)

**Comment by buckle2000** [comment]
BTW, should iterating a dictionary outputs keys?
In as3, python, lua, C#, C++, we get keys (sometimes with values).

**Comment by back2dos** [comment]
The satus of the specification is unclear: https://github.com/HaxeFoundation/haxe/issues/4911#issuecomment-193996530

**Comment by buckle2000** [comment]
@back2dos I don't understand you. In any way, this Iterator is considered "broken".

**Comment by back2dos** [comment]
@buckle2000 you have quoted what the documentation specifies. I have pointed you to an issue where it seems like that specification may be removed in the foreseeable future. In that case, the iterator will not be considered broken anymore, but your code will still not work as it should. In short: don't rely on it, until a decision has been made.

**Comment by buckle2000** [comment]
Thank you. Anyway, I think `for (v in dict) ...` should yield keys, not values.

**Comment by back2dos** [comment]
> Anyway, I think for (v in dict) ... should yield keys, not values (present behavior).

1. I don't think it should. First of all Haxe's `for in` is equivalent to AS3's `for each in`. If you use `for each in` on a dictionary, it will give you the values, not the keys. Furthermore, if you loop over an array, you also expect to get the values, not the keys, no? Why should it be any different for maps then?
2. Whether or not you and I agree, it is unlikely to change just like that, because it will break a lot of code. If you can make a good case for it, [go ahead](https://github.com/HaxeFoundation/haxe-evolution) and then it may be taken into consideration for Haxe 4. AFAIK `for (key => val in dict) {}` is planned anyway, which I think makes the whole debate obsolete ;)

**Comment by buckle2000** [comment]
all right

**Comment by buckle2000** [comment]
so how do I enumerate keys?

**Comment by buckle2000** [comment]
so how do I enumerate keys now?

**Comment by back2dos** [comment]
> so how do I enumerate keys now?

Uhm, that's what `map.keys()` is for ;)
