### ISSUE TITLE
invalid enum matching

### ISSUE THREAD

**Issue by jozefchutka** [HaxeFoundation/haxe#6198]
Following code matches enum which is null to E.A case using latest compiler (3.4.2) on try.haxe.org. I would expect something else, maybe an exception...

```haxe
class Test {
    static function main() {
        var e:E = null;
        switch(e)
        {
            case E.A:
                trace("e = E.A");
        }
    }
}

enum E {
    A;
}
```

**Comment by Simn** [comment]
Just spent 30 minutes looking for the original issue: #2019

Back then we decided that it was fine to optimize this. The thing is that `switch(null)` without a `case null:` would not do what you want in the first place (I think it throws an exception on all targets?).

I'll stare at this for a bit though because this inconsistency bothers me somehow.

**Comment by jozefchutka** [comment]
having 2 or more entries in enum drives you to do this or that better both compile time and runtime. also makes the matching working
