### ISSUE TITLE
case <var> syntax change

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6207]
One thing I often have to explain about Haxe to new developers are the `case ident:` that is actually a default when the pattern `ident` is unmatched.

It currently gives a warning but that's not very straightforward to understand that it's a actually a catch-all case, and can often lead to code with wrong behavior.

I propose removing this, forcing "case" to always be a not-single-var pattern (at least when there's no guard), and instead allow  `default ident:` (ident being optional) which gives a better understanding that it's actually a catch-all case.

**Comment by ibilon** [comment]
If I remember correctly somebody mentioned the `case var ident:` syntax,
which I like better than `default indent:`.

**Comment by nadako** [comment]
yeah, `var` inside patterns already works. tho `case var ident:` doesn't parse, but `case (var ident):` does

**Comment by Simn** [comment]
Huh, that's a parser bug I think...

**Comment by nadako** [comment]
IIRC we discussed before that explicit var binding like that should be the preferred syntax.

**Comment by Simn** [comment]
Yes I like `case var ident`, but I'm not sure about outright breaking `case ident`. That would break a lot of code... A warning would be good here in my opinion.

**Comment by nadako** [comment]
sure, we can make it through the proper deprecation process with a warning for one major version lifespan

btw do we also prefer `case Some(var v)` instead of `case Some(v)`?

**Comment by ncannasse** [comment]
It would be interesting to conduct a poll with the community between `case var ident` and `default ident`, I think the later is more suitable as a "catch all" since that's what `default` already does.

**Comment by sledorze** [comment]
@nadako reveals here the consistency issue accros all patterns.
I really think introducing the 'var' keyword in all patterns just add more unnecessary boilerplate, and only for default cases, well, it looks singular and weird.. (even ugly).
So if it 'case ident' really hurt the newcomers, I would agree with @ncannasse , but non exclusively.

**Comment by ncannasse** [comment]
I agree that the `var` keyword should not be added. We don't want to make it mandatory for `Some(x)` for instance, that would break like all Haxe code. And I don't see the point of making it optional either.

**Comment by ibilon** [comment]
> I think the later is more suitable as a "catch all" since that's what default already does.

It's not necessarily a catch all https://try.haxe.org/#1A507

**Comment by ncannasse** [comment]
@ibilon that's why I said in my original post "at least when there's no guard"

**Comment by ibilon** [comment]
Should read better ;)

But since it's possible to have guards and a guarded default would look really weird I don't think we should change `case ident` to `default ident`.

**Comment by back2dos** [comment]
How about this: if `case indent` with no guard is followed by more branches, give a more descriptive warning, or even make that an error. Wouldn't that address the issue without any syntax changes?

**Comment by Simn** [comment]
Doesn't that already give a warning about unused cases?

**Comment by frabbit** [comment]
I really `case x` because it looks a lot nicer than `default x` because of the same length. I actually never use default anymore, I use `case _` instead. I would actually prefer getting rid of default.

**Comment by nadako** [comment]
> I really case x because it looks a lot nicer than default x because of the same length. I actually never use default anymore, I use case _ instead. I would actually prefer getting rid of default.

I second this. IMO `default` is really a redundant leftover from classic switch.

**Comment by Justinfront** [comment]
_ is sometimes a bit strange, find it not ideal to have default after lots of case I always end up checking manual, but to have both of these would be good.

case _
case default 

much nicer than

default

probably need to get better at complex switches to really comment on the main aspect of this thread.

**Comment by back2dos** [comment]
> Doesn't that already give a warning about unused cases?

A warning, yes, but it's not *that* informative if you're just getting started with Haxe after having used a language with C-style switch statements:

```haxe
var magicNumber = 7;
switch Std.random(10) {
  case magicNumber:
    trace('magic!');
  default: // <-- Warning: this case is unused
}
```

My suggestion is that while typing a `case ident` that is not the last case, you produce the warning there (or consider making it an error), make it more explicit and possibly give a link to the relevant entry in the manual.

The current syntax is just fine. It takes a couple of minutes to learn. It is consistent within itself and with other languages that support pattern matching. I don't think forcing people to put `var` on *every* variable binding is such a good idea (and it's not what is being suggested anyway) and I don't think creating one more special case to learn makes the language more newcomer friendly. Even then, the question would be: what error would `case ident` produce?

**Comment by frabbit** [comment]
@back2dos I agree that the focus should be on the error message to make it clear for everyone. I actually quite like how elm focuses on human readable error messages which also gives hints ;). http://elm-lang.org/blog/compiler-errors-for-humans

**Comment by ncannasse** [comment]
Those who claim about `case ident` completely misread my original issue. When you mispel ident, for instance if you try to match an invalid enum constructor, it will turn your specific case into a catch-all leading to code errors. Such mistake should be the one the compiler protects you against, ie an error.

**Comment by ncannasse** [comment]
Another suggestion would be to allow only `case (ident)` with or without guard, and still allow `case _` as a specific case since there's no mistake possible here.

**Comment by frabbit** [comment]
Ok I got it, sorry I really misread your proposal. How about a warning if you use case ident and you don't use the bound variable? Otherwise I could live with `case var x`.

**Comment by ncannasse** [comment]
@frabbit you might use the bound variable, it might even compile!

switch( myEnum ) {
case wrong: return wrong;
...
}

(think for instance if you had this code before and you remove the `wrong` constructor because of refactoring)

**Comment by back2dos** [comment]
@ncannasse I don't get your point What I have suggested is that this should compile:

```haxe
switch( myEnum ) {
  case wrong: return wrong;
}
```

This should not (or at least give a very clear warning):

```haxe
switch( myEnum ) {
  case wrong: return wrong; //Error: catch-all case must be at last position in switch statement. See http://haxe.org/rtfm
  case ...: 
}
```

We don't have to change syntax and we won't break any (meaningful) code.

**Comment by ibilon** [comment]
@back2dos that doesn't work if you typo the last case though

**Comment by kevinresol** [comment]
> @back2dos that doesn't work if you typo the last case though

Capture variables are restricted to start with lower case letter, so naming enum entries with capitalized first letter would mitigate that. And I believe that should be promoted as best practice, if not enforced by the compiler.

**Comment by ncannasse** [comment]
In our case we are using idents which are abstract(String) enums coming from castledb, so the naming could differ depending on the user.

**Comment by ousado** [comment]
I'm with @back2dos on this one. The compiler could do quite a bit more without breaking existing code.

In addition to enforcing a catch-all to be the last case, we could use the existing Levenshtein distance implementation to check if a typo is likely (e.g. a with distance of <= 2 characters to an existing constructor), and give a warning in that case. Along with good/improved errors and warnings, such errors won't go unnoticed and the compiler can provide useful guidance to newcomers.

Should the current catch-all var syntax be removed, however, the IMO next best option already exists, making use of the standard capture syntax: 
```haxe 
switch _ { 
  case ident=_:
}
```
Which is why I'd oppose the introduction of new, special syntax just for this case.

**Comment by Simn** [comment]
Nicolas and I agreed on `case var x`. I implemented it with the following properties:

* if an identifier is close to an expected value, you get a warning `Potential typo detected (expected similar values are downLeft). Consider using var downleft instead`
* for `case downleft` you always get a warning `case downleft has been deprecated, use case var downleft instead`

This should be a good solution because you can still use short capture identifiers in deep patterns, as long as they aren't similar to expected values (which they usually aren't).

**Comment by EricBishton** [comment]
I found your warnings cryptic because it's not immediately obvious what difference you are trying to convey.  Consider using quotes to set off the difference between the current and suggested usages. 

For example:
-  `Potential typo detected (expected similar value is 'downleft').  Consider using 'var downleft' instead.`
-  `Short capture syntax 'case downleft' has been deprecated; use 'case var downleft' instead.`

**Comment by Simn** [comment]
It actually has backticks there, but I didn't know how to escape them here... x)

**Comment by back2dos** [comment]
I don't know about you guys, but right now for me this is super annoying. I use stuff like this *a lot*:

```haxe
switch someComplexStringExpression {
  case null | '': someDefaultBehavior();
  case v: someSpecificBehavior(v);
}

switch Std.instance(someVar, ParticularClass) {
  case null: genericCase(someVar);
  case v: particularCase(v);
}
```

So when I try Haxe 4, I get warnings all over the place. It's not that I'd mind the making that `var v`, but in fact I have to make it `#if haxe_ver >= 4 var #end v` and that's not fun anymore. And ignoring tons of warnings is not an option either

Could we skip the warning when both of these conditions are met:

1. The `case` is the last one in the `switch` and there's no `default`, so no other branches are mistakenly intercepted. Otherwise the compiler should say something like: "catch-all case must be at last position in switch statement"
2. The `switch` target is neither an `enum` nor an `@:enum abstract` (bonus: with at least one lower case constructor), so it's safe to assume that the captured variable name is not a typo. Otherwise, the compiler should say something like the existing: "Potential typo detected (expected similar value is 'downLeft'). Consider using 'var downleft' instead."

Or whatever. Actually, anything will work for me, so long as I don't have to litter all my code with conditional compilation or all my output with warnings ;)

**Comment by nadako** [comment]
I feel very uneasy about this change, because it just seems to bring a lot of inconsistency, unless I mistunderstood the change...

 * We have to use `case var x` for capturing, but only for toplevel matches. Why is that? We could have a typo in a deeper match as well, e.g. `case Some(downLeft)`, which won't emit a warning and will be a "proper" catch-all. At the same time, if I'm understanding correctly, using `var` in deeper matches (`case Some(var downleft)` is discouraged as more verbose...
 * `case _` is a special case in the compiler now, so we don't have to write `case var _`, right? I mean, I get that it would be stupid having to write `case var _`, but now it's inconsistent with the rest of catch-call cases, making pattern-matching even more complex to understand, meh...
 * Now when we have `final`, I think most of the time we would want our capture vars to be `final`, but do we support `case final x`? Even if we do, that looks verbose as hell...

In the end, this sounds to me like a lot of complexity and design inconsistency added to fix one particular confusion. Wouldn't a typo-detection when matching on enum be enough?

**Comment by Simn** [comment]
> Wouldn't a typo-detection when matching on enum be enough?

That's what I added for deep matching. There's just this extra check for toplevel because Nicolas insisted on that. But looking at this a few days later, I also wonder if that's really necessary as long as typos are detected...

**Comment by Simn** [comment]
By the way, I thought that `case var x` was working in Haxe 3. I added support for it to the pattern matcher, but didn't realize that the parser doesn't like it: It enters var-parsing mode and thinks the `:` is the start of a type-hint. This makes me consider patching it for a 3.4.4 release in order to allow `case var x` on both Haxe 3 and 4.

**Comment by nadako** [comment]
Since `var x` was already working for deeper patterns in Haxe 3, I think supporting it top-level patterns is good.

But encouraging them and emitting a warning about it seems a bit too much. If we're talking about typos in enum ctor names, a typo detector should be enough: 99% of time you make a typo in enum ctor name and the correct fix is to fix the typo. If the catch-all var name was intentional, you just add `var` to it (although you should rethink your naming in this case).

So, I propose removing the warning, but still supporting optional `var` for top-level patterns.

PS Oh, and also support `final` for captures while we're at it.

**Comment by Simn** [comment]
I have disabled the toplevel warning for now because it really is too annoying to handle like this.

**Comment by jgranick** [comment]
I agree with Nicholas that `case ident:` is confusing. I did not realize that was valid syntax.

```haxe
var a = 1;
var v = 2;
switch (a) {
    case 0: trace ("a is 0");
    case v: trace ("a is 2"); // a is actually 1
    case 1: trace ("a is 1"); // this will never be hit
}
```

I think `default` is clearer that it will catch all cases

**Comment by kevinresol** [comment]
Actually it is ok for me, because the compiler gives warning already. To be more strict perhaps the compiler should error (instead of warning) with unused patterns.

**Comment by kevinresol** [comment]
Well, the confusion comes from the fact that in js switch/case can compare against variables. But in haxe it is always either constant or capture variable.

**Comment by back2dos** [comment]
@jgranick You have a catch-all clause that is not at the last position. I think *everyone* agrees that the compiler should give you a very explicit warning (if not error).

**Comment by jgranick** [comment]
@back2dos In most languages (and in Haxe, if `v` is inline) it is not a catch-all clause. Just sharing that I find this confusing :smile:

**Comment by ncannasse** [comment]
This is already a way-too-long thread, but here's my opinion:

I think there is a problem with `case ident` and that in the end we should not allow it as a catch-all. However since Haxe 3.4 does not allow `case var ident` it seems necessary to have some kind of transition going on without having all users to #if haxe4 everywhere.

**Comment by Simn** [comment]
Since #6589 makes it necessary to have a 3.4.4 release, I'll also fix the `case var` parsing for that. This allows using the syntax for both Haxe 3 and 4.

**Comment by back2dos** [comment]
As a library maintainer that still puts me in a place where I have 3 choices:

- live with the fact that everyone who wants to use the libs with Haxe 4 is flooded with errors
- stuff conditional compilation everywhere
- drop support for everything < 3.4.4

I don't like the prospect and I think there's better solutions still:

How about we disallow the variables of catch-all cases to shadow any identifier in scope. In other words if `ident` actually has a valid type, then `case ident` should yield a compiler warning or better yet an error. Together with catch-all clauses having to compile with the other two conditions I proposed above, I think most cases are covered.

Any warnings/errors that would come from that can be fixed by choosing a different name, after which it will be fine in Haxe 4 and continue to work with older versions.

**Comment by ncannasse** [comment]
Let's put it in 3.4.4 first and decide later how it goes.

@Juraj : your solution does not take possible typos into account, that
turns a wanted specific-catch into a catch-all with undesirable runtime
effects

**Comment by ousado** [comment]
> @Juraj : your solution does not take possible typos into account, that
turns a wanted specific-catch into a catch-all with undesirable runtime
effects
…

@ncannasse ( you mean @back2dos, I guess ) 
That's only true if it's the last case and the typo is so severe that no warning is generated, which seems unlikely to coincide. I'm still with @back2dos here.

**Comment by Simn** [comment]
I kinda agree with both sides here, which isn't very helpful. I really don't want to force `case var x` on everything, but at the same time I can see why someone would be confused about a `case v` not matching some variable/field, but being a capture variable instead. And the fact that adding `inline` changes the semantics simply isn't good design...

So I don't know.

**Comment by kevinresol** [comment]
I suggest removing the special `inline` semantic and force people to write `case x if(x == v):`

**Comment by ousado** [comment]
That `inline` preserves its own semantics in patterns is only consistent.

**Comment by back2dos** [comment]
@ncannasse would you care to construct a typo that elludes all three conditions?

**Comment by nadako** [comment]
I think it's good and consistent at it is in current dev: there are warnings about potential typos wrt enum constructors and unused cases and `case var` is supported everywhere to resolve rare cases of identifier clashes.

**Comment by Simn** [comment]
I don't really know what to do here. I'm inclined to just close this issue because we detect typos now, and I don't think we want to outright break `case x`.

**Comment by ncannasse** [comment]
I propose immediate action for 4.0:

- warning on `case ident` , to be replaced with `case var ident` 
- removal of `case ident` support in 4.1

**Comment by back2dos** [comment]
I propose not to do that. Feel free to reread the ample supply of arguments provided in this thread or to answer the questions that have been put to you.

**Comment by back2dos** [comment]
Also: if we really must break something here, then I would say we should disallow lowercase enum constructors.

**Comment by jcward** [comment]
I agree with @ncannasse, the typo struggle is REAL, and that's supposed to be a core strength of Haxe. A typo is way more common than a user actually intending to use a capture variable. Plus lower-case typos are [not caught](https://try.haxe.org/#99913) and will cause runtime errors.

I have some backwards compatible suggestions:

```
  case <ident>: <exprs>
```

1) Simply change the error message to "Enum value <ident> not found (did you mean ...), or capture variable must be lower-case."

But better still would be to determine if the user **_intended_** a capture variable:

2)  If exprs does not contain `CIdent(ident)`, then the compiler can assume it's not meant to be a capture variable, and can give a much better error message: "Unknown enum constructor <ident> (did you mean: ...)"

3) **Optional:** further building off 2), if exprs does not contain `CIdent(ident)`, it's probably a lower-case typo (which currently gets accepted :sob:) the error could be "Error: unused capture variable <ident>, use _ instead".

So the question is, @simn, how feasible is it to "detect `CIdent(ident)` in exprs" ?

**Comment by Simn** [comment]
Here's what I'm going to do: I'll close this issue as I consider the original problem to be addressed by the typo detection. It may only be reopened along with a code sample that demonstrates the problem and looks like it could have been written by a real-life human being.
