### ISSUE TITLE
Allow @:op(a in b)

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6224]
@nadako says it should be possible :smile:

**Comment by nadako** [comment]
It should be possible, but I guess it needs some design regarding how we handle `EIn` (static/non-static overloads, which one to choose both exprs are abstracts overloading `in`, etc). Though maybe we can re-use the usual operator overloading logic here.

**Comment by nadako** [comment]
And yeah, I think this can be useful for DSLs (e.g. SQL).

**Comment by ibilon** [comment]
How will that work if you do `for (a in theabstract)` with and without the `hasNext()` + `next()` function?
Or is it only for outside for loops?

**Comment by nadako** [comment]
for loops handle `EFor(EIn)` at syntax level, so it shouldn't be a problem.

**Comment by ibilon** [comment]
Ok good,
as long as the documentation is **very** clear about it, I can already see people complaining about how they overloaded the in operator but still can't loop over their abstract ;)

**Comment by nadako** [comment]
After briefly looking into this, I wonder why we have a separate AST node for `in` at all. Wouldn't it be more consistent if it were just a binop? Then it would automatically work for abstract `@:op` overloads as well. 

If we consider changing it to a binop, now would be the best time for this (because Haxe 4), otherwise, we'll have to add special `EIn` handling in the typer, along with `a_ins` list to the `tabstract` structure, similar to `a_ops` and `a_unops`.

Opinions? @Simn @ncannasse @waneck @hughsando
