### ISSUE TITLE
minor var fusion regression after the inline ctor rework

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6229]
The following used to fuse before #6178 merge (see below):

```haxe
class Vec2 {
    public var x:Float;
    public var y:Float;

    public inline function new(x) {
        this.x = x;
        this.y = x;
    }
}

class Main {
    static inline function mkVec(x)
        return new Vec2(x);

    static function f()
        return 1.0;

    inline function getVec() {
        return mkVec(f());
    }

    static var inst:Main;

    static function main() {
        var v = inst.getVec();
        trace(v.x + v.y);
    }
}
```

was 
```js
Main.main = function() {
	var x = Main.f();
	console.log(x + x);
};
```

now
```js
Main.main = function() {
	var v_y;
	var v_x;
	var x = Main.f();
	v_x = x;
	v_y = x;
	console.log(v_x + v_y);
};
```

note that if we remove the block from the `getVec` function (so it's body is just the return expression), it fuses again

cc @basro as he might have a quick idea what and how to fix that :)

**Comment by basro** [comment]
Oops.. It seems the old inline constructors had a flatten function which I had misunderstood to be simply unwraping a block. That function was actually merging all the superfluous blocks inside of it as well.

My reworked version was only unwrapping the outer block while leaving the contents intact, which causes this difference.

Luckily fixing it so that it behaves the same as old inline constructors is a two lines change, I'll make a PR with the fix soon.
