### ISSUE TITLE
Class creation via Context.onAfterTyping() fails in JavaScript target

### ISSUE THREAD

**Issue by hereticByte** [HaxeFoundation/haxe#6254]
# Class creation after typing only works on neko (not on JS)

Hello Community,

why does the class creation via _Context.onAfterTyping()_ does not work on _JavaScript_?

It works on neko. So I assume, the error is not on my side.

I have simplified the algorithm to analyse the process.

You can download it from github here:
_https://github.com/hereticByte/CreateNewClass_

## What the algorithm does

A class named _'NewClass'_ is given. It has a field that needs to be changed during compilation time after typing.

As the class itself can't be changed after typing, it is excluded within the callback _Context.onAfterTyping()_.

Within the same callback a surrogate class _'NewClassSurrogate'_ is created and the field _'x'_ is changed to _"Great!"_. As the surrogate class has to be called replacing the _'NewClass'_ the original _'NewClass'_ needs to be redirected to the surrogate via _@:native("package01.package02.NewClassSurrogate")_.

Thank you, Juraj, for this sophisticated approach. 

But as I said, it only works on neko. Not on JS.
Is it a bug?

haxelib version:
3.4.2 (just updated)

Kind regards

**Comment by hereticByte** [comment]
I have found a workaround.

**Comment by vladimirvelikov** [comment]
Could you please share the workaround?

**Comment by Gama11** [comment]
![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by RealyUniqueName** [comment]
I guess the workaround is to add `@:keep` meta to the generated class.

**Comment by vladimirvelikov** [comment]
I have the @:keep, I even disabled dce.

In my case if the @:native metadata is added in onAfterTyping, the class to be replaced is still referenced, albeit with dot notation (js-unflatten style) while everything else is flattened. 

If the @:native metadata is added directly in the haxe file of the class to be replaced, then the newly generated replacement class is being referenced correctly and things work as expected.

**Comment by hereticByte** [comment]
Hello Vladimir,

I am sorry, I can't reconstruct the scenario anymore. I have created this project seperate from the original project, the actual issue occured in. 
... only for the purpose to be able to communicate about it.

Regrettably I do not know anymore, how I solved it in the orignal project. And I also do not know the name of the original project anymore as well. So I can't look it up.

I would have documented it more consciously, if I knew that someday someone would stumbles across the same question.

Kind regards

**Comment by nadako** [comment]
I gotta say what you guys are doing is really nasty and there's probably a better way to deal with the original issue.

The issue here is that `Compiler.exclude()`, as stated in its documentation is actually making the type `extern` and `@:native` is handled differently for extern classes on JS target with regard to name flattening: there's no flattening of extern paths.

That means that you should actually add `@:native("package01_package02_NewClassSurrogate")` to the excluded class, because that's how `NewClassSurrogate` will be generated, unless you have `-D js-unflatten` defined. So you might also have to add some `Context.defined("js"/"js_unflatten")` checks.

**Comment by vladimirvelikov** [comment]
You have a point there regarding flattening of externs, but the problem is rather that even if both the replaced and replacing classes are not in a package, when addMetadata is called in onAfterTyping, in the generated code still the *replaced* class is being referenced, instead of the *replacing* class.

I already have a small repro-case that demonstrates it and will be sharing it tomorrow. Would be very thankful if you guys can take a look at it.

As for the original issue. I have a (varying) set of classes that all implement a certain interface, which I have an @:autoBuild macro run on. The macro collects some info about these classes. That info is then used to translate domain-specific language code into regular haxe code.  So the issue is that there is no guarantee that the interface's @:autoBuild macro will run first and gather the info about the implementing class, so that info can be used to translate the DSL code properly. Any ideas about how to approach this are greatly appreciated too. The more so if these don't involve reading a manually maintained list of classes from a file in an initialization macro.

**Comment by vladimirvelikov** [comment]
Here is a minimal repro case https://github.com/vladimirvelikov/native-in-onaftertyping

If line https://github.com/vladimirvelikov/native-in-onaftertyping/blob/76da0e7cb4e2795614e8340847344ffb60f831d2/src/ReplacedClass.hx#L4 is uncommented, things work fine.

Line https://github.com/vladimirvelikov/native-in-onaftertyping/blob/76da0e7cb4e2795614e8340847344ffb60f831d2/src/ReplaceMacro.hx#L47
doesn't have the same effect, though.
