### ISSUE TITLE
[neko] Float being handled as Int.

### ISSUE THREAD

**Issue by m22spencer** [HaxeFoundation/haxe#6256]
```haxe
class Main {
    static function main() {
        var a:Float = 1430000000;
        var b:Float = 1430000000.0;

        var aa:Float = a * a;
        var bb:Float = b * b;

        Sys.println('aa: $aa');               //aa: 892485632
        Sys.println('bb: $bb');               //bb: 2.0449e+18

        Sys.println('aa == bb: ${aa == bb}'); //aa == bb: false
    }
}
```
Run with:
```haxe -x Main```

The square of `a` seem to be done via 32 bit integer multiplication and is overflowing.

**Comment by ttencate** [comment]
Also ran into this. It broke arithmetic inside the Nape physics library due to this overflow. It seems the "int-ness" of these floats gets plumbed all the way through function calls and across to different classes:

```haxe
class Main {
    static function main() {
        var a:Float = 1430000000;
        var aa:Float = a * a;
        test(aa);                    // aa: 892485632
        Sys.println(Type.typeof(aa)) // TInt
    }

    static function test(aa: Float) {
        Sys.println('aa: $aa');
    }
}
```

This even happens if the callee is in a different file or even a different library.

Reproducible at least on Haxe 3.4.2 back through 3.2.1 (which is the oldest version I can easily install).

**Comment by Simn** [comment]
I think at this point it's safe to say that we aren't going to fix old neko bugs.
