### ISSUE TITLE
[python] null param in function returned from function

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6259]
This was isolated from dox -> hxtemplo -> [hxparse](https://github.com/Simn/hxparse). Looks like this effectively breaks hxparse on Lua.

```haxe
class Main {
	static function main() {
		function f(a) return a.b;
		f({b: (s) -> s.length})("");
	}
}
```

```
attempt to index local 's' (a nil value)
stack traceback:
        export/run.lua:102: in function <export/run.lua:101>
        export/run.lua:103: in function 'main'
        export/run.lua:300: in main chunk
        [C]: ?
```

```bash
> haxe -version
4.0.0 (git build HEAD @ fedbe2c)
```

Lua version doesn't seem to matter, happens with 5.1, 5.2 and LuaJIT. Other targets have no issues with this.

**Comment by nadako** [comment]
This seems to be related to the fact that functions within anon objects are generated with the `self` first argument, while they shouldn't (anon objects don't have methods and thus no notion of `this`).

**Comment by jdonaldson** [comment]
Yeah, this bug exposes a lot of issues.  Firstly, the anon functions _are_ generated with dummy "self" arguments.  This is so they can be exchanged more easily between anon objects and instances... even if used with Dynamic.  Of course, if you write a function that returns a field (instance/anon), and _then_ call it as a simple local function, the compiler loses track of the fact that it needs a self argument.

Secondly, lua doesn't like treating string instances as objects, so extracting/dealing with fields needs to be handled differently.

I handled some of the string/field issues in a separate commit.  The fix here is that every time you return an instance field in a function, the compiler will bind this method so that it can be executed as a plain local function.  Keep in mind that in this particular case, the function is modified _twice_: once to add a dummy self to the anon object field function, and once to bind the dummy self to a new closure when it is part of a function return.

This should work, but it's not a pattern that's going to produce optimal lua code.  I'll add another here for the lua FAQ.

**Comment by andyli** [comment]
Look like there is similar issue for the python target:
```
Test.hx:275: ABORTED : AttributeError("'str' object has no attribute 'length'",) in unit.issues.Issue6259.test
```

**Comment by jdonaldson** [comment]
I'll disable the test for python and check that in... just a sec.
