### ISSUE TITLE
[php7/cppia] lazily-initialized (get, null) property

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6281]
The following fails on PHP7:

```haxe
class Main {
	public static var syntaxes(get, null):String;

	static function get_syntaxes():String {
		if (syntaxes == null)
			syntaxes = "foo";
		return syntaxes;
	}

	public static function main() {
		trace(syntaxes);
	}
}
```

```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: Main::$syntaxes in php/lib/Main.php:19
Stack trace:
#0 php/lib/Main.php(33): Main::get_syntaxes()
#1 php/index.php(13): Main::main()
#2 {main}
  thrown in php/lib/Main.php on line 19
```

Isolated from the [markdown](https://github.com/dpeek/haxe-markdown) lib. Haxe version: acc026c645be8960e9cf9a0ee9467355c01a9195

**Comment by szczepanpp** [comment]
I wonder if it's a bug or not. I'm simply adding `@:isVar` on the property and always assumed it's a  target specific behaviour (e.g. it can work on JS without annotation because in JS you can use variables not declared explicitly).

Now, looking at Haxe documentation ([https://haxe.org/manual/class-field-property-rules.html](https://haxe.org/manual/class-field-property-rules.html#define:-physical-field)), it states that `a property with the read-access or write-access identifier being default or null` is considered physical, which in turn prevents Haxe compiler _only_ from throwing a _compilation error_. Documentation doesn't say how the field is defined in terms of using annotation or just working on a specific (dynamic) target.

**Comment by Gama11** [comment]
This works on C++, C#, Java, Neko, HL, JS, Lua, Python and the old PHP target. I'd say it's a bug. ;)

**Comment by Gama11** [comment]
Looks like this may need to be reopened, cppia is failing on the unit test:

>Issue6281.hx:11: foo should be 0
Test.hx:221: DONE [6890 tests]
Test.hx:222: SUCCESS: false
Command exited with 1 in 0s: /home/travis/build/HaxeFoundation/haxe/tests/unit/bin/cppia/Host-debug [bin/unit.cppia]
test cpp failed

@hughsando
