### ISSUE TITLE
unly $bind code in javascript

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#6297]
```js
class Main {
    static function main() {
        js.Browser.document.onclick = function(e: js.html.MouseEvent) {
            if (e.preventDefault != null)
                e.preventDefault();
        }
    }
}
```
generated code:

```js
window.document.onclick = function(e) {
    if($bind(e,e.preventDefault) != null) {
        e.preventDefault();
    }
};
```

**Comment by Simn** [comment]
This would require some analysis. We have to use $bind in case the function may be called at some point, so we would have to detect situations in which this can't happen.

**Comment by back2dos** [comment]
I think the use case of feature detection is particular enough to treat it in isolation, in which case you really just want to make sure that checks against null (and not null) avoid `$bind`. In any other scenario, checking whether the (non-dynamic) method of an object is null or not is pretty much non-sense anyway.

That said, polyfilling this one is pretty trivial, so that's what I would personally go for:

```haxe
if (!Event.prototype.preventDefault)
  Event.prototype.preventDefault = function () {
    this.returnValue = false;
    this.defaultPrevented = true;
  }
```

**Comment by Simn** [comment]
Closed by https://github.com/HaxeFoundation/haxe/commit/2b95c53be98670141a214b27cd5f54924f27942d

**Comment by nadako** [comment]
closed by 7440224a035438014acb9cb58c22ed26ab3fe500?

**Comment by Simn** [comment]
I thought that reopened it

**Comment by RealyUniqueName** [comment]
Yep, 7440224 closes it.

**Comment by Simn** [comment]
Ah sorry, I didn't notice that there were two commits.
