### ISSUE TITLE
Pattern matching failure

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6327]
```haxe
import haxe.macro.Type;

class Main {
    static function main() {
        var t:Type = null;
		switch (t) {
			case TType(_.get() => {name:'A'}, _) | Std.string(_) => 'A':
				trace('A');
			default:
				trace('default');
		}
    }
}
```

error: `haxe.macro.Type has no field get`

Removing the or-case `| Std.string(_) => 'A'` fixes it

**Comment by Simn** [comment]
That's a funny one, but actually not a real issue. What you have is a parsing problem due to precedence confusion between `=>` and `|`. With `=>` having lower priority, you end up with `stuff to the left => 'A'` instead of what you want. Looks silly in this situation, but I don't think there's anything we can do about it because we don't want to change `=>` precedence.

Solution: Use `,` instead of `|` or put parentheses around `Std.string(_) => 'A'`.
