### ISSUE TITLE
Extended class type recognition

### ISSUE THREAD

**Issue by 7h3w4rd0c70r** [HaxeFoundation/haxe#6332]
Hey, While working on a project I got an error recognising class type. This is the simplified example of a problem:
```haxe
class Test {    
    static var a: Class<A>;
    static var b: Class<B>;
    
    static function main() {
        a = B;
        b = B;
        a = b;
    }
}

class A { }

class B extends A { }
```
Variable a is of type Class\<A\> so you should be able to assign a class B to it (because B is extended class A) and it works - on line 6 (a = B). But on line 8 I got an error. b contains class B, so you should be also able to assign b to a. Instead of this, you get a type error "Class\<B\> should be Class\<A\>".
**Is this behaviour ok or is it a bug in the compiler?**

**Comment by jozefchutka** [comment]
I would also like to understand if this is a compiler bug and can be fixed anytime soon?

**Comment by Simn** [comment]
Not a bug because it violates variance.

Actually I think the `a = B` assignment shouldn't work either. It probably does due to top-down inference, but I'm not sure it makes a lot of sense from the run-time's point of view.

Any opinions @ncannasse?

**Comment by 7h3w4rd0c70r** [comment]
@Simn Sometimes it makes sense, when you have a large project with lots of extended classes, to be able type check class B by some other class A witch it extended from. It makes sense, because class B is actually class A, it has all its properties and methods, plus it has something more. May be this could be default behaviour, and if you would need a total exact match with exactly the one class, you could use some extra syntax to do that...

**Comment by jozefchutka** [comment]
What we are trying to achieve is to use [react externs](https://github.com/massiveinteractive/haxe-react) esp. createElement defined as
```haxe
public static function createElement(type:CreateElementType, ?attrs:Dynamic, children:haxe.extern.Rest<Dynamic>):ReactElement;
```

while first parameter to be EitherType
```haxe
typedef CreateElementType = haxe.extern.EitherType<haxe.extern.EitherType<String, haxe.Constraints.Function>, Class<ReactComponent>>;
```

then extend ReactComponent classes:
```haxe
class MyComponent extends ReactComponent {}
```

and be able to use it within createElement:
```haxe
React.createElement(MyComponent)
```

Right compiler throws errors just like in the simple case on the beginning of this thread, we would like to find a way forward, and wither we need to modify externs (any suggestions?) or wait for compiler fix

**Comment by Simn** [comment]
The problem I have is that static structure is not inherited, and `Class<T>` represents the static structure at run-time:

```
class Main {
	static function main() {
		getValue(A);
		getValue(B);
	}

	static function getValue(c:Class<A>) {
		trace(Reflect.field(c, "value"));
	}
}

class A {
	@:keep
	static public var value = 12;
}

class B extends A { }
```

I'm not sure if this is supposed to work or not.

**Comment by jozefchutka** [comment]
@Simn I think your code should get compiled but there might be runtime problem. Anyway that solves rather some other issue than originally reported, which is purely compile time related

**Comment by elsassph** [comment]
@jozefchutka as far as I can tell `react.React.createElement(Foo);` works - you must have a different situation.

**Comment by jozefchutka** [comment]
@elsassph you are right we managed to make createElement work, probably there was some other issue related. The only outstanding issue is the case on top of the thread

**Comment by 7h3w4rd0c70r** [comment]
@Simn Yes, You're probably right, a = B is antipattern. But then a = b is too and probably should invoke error by compiler

**Comment by back2dos** [comment]
@Simn I think examples constructed on reflection are a bit contrived. 

`Class<T>` mostly is there so that you know that `Type.createInstance` will give you a `T`.

A good question is whether `Std.instance(value, c)` should always return `value` if `value` is `T` and `c` is `Class<T>`. Currently, [it's not necessarily the case](https://try.haxe.org/#eb7d3):

```haxe
var c:Class<A> = B;
var a:A = new A();
trace(Std.instance(a, c));//null
```

The documentation for `Std.instance` does not contradict the behavior, neither does the documentation for `Class<T>`, which merely refers to `Type` . OTOH it does seem a little surprising.

It comes down to establishing what `Class<T>` actually means. There are two possibilities:

1. when constructed, returns a value that satisfies type `T`
2. a runtime type check against `Class<T>` must succeed for any value that satisfies type `T`

The first one should hold obviously. If the second one holds, then `a = B` should not compile, otherwise `a = b` should compile.

**Comment by jozefchutka** [comment]
who can help us find the answer? @ncannasse ?

**Comment by ncannasse** [comment]
As @simn noted, it seems top down type inference allows assigning B value to a `Class<A>`, which is fine because the only (mostly) typed thing you can with a Class is to create instances of it with `Type.createInstance/createEmptyInstance`, so Class is covariant.

However Haxe does not usually allows variance in typing, only for literals.
This can be also reproduced with an Array by doing:

```haxe
var a : Array<Float> = [123]; // ok
var a = [123];
var b : Array<Float> = b; // not allowed
```

So while we could make a special case for `Class` in the typing unification and make it covariant, I think the current behavior is good as well.

**Comment by Simn** [comment]
I agree it's not worth introducing a special case for.
