### ISSUE TITLE
types didn't unify in build macro

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#6402]
```haxe
import haxe.macro.Expr;
import haxe.macro.*;

class Base {}
class Extended extends Base {}

class Builder {
    #if macro
    static public function checkUnify():Void {
        var baseType = ComplexTypeTools.toType(macro:Base);
        var extendedType = ComplexTypeTools.toType(macro:Extended);
        var unify = Context.unify(extendedType, baseType);
        trace("Extended unifies Base? " + unify);
    }
    #end
    macro static public function build():Array<Field> {
        trace("in @:build");
        checkUnify();
        var fields = Context.getBuildFields();
        return fields;
    }
}

#if !macro
@:build(Builder.build())
#end
class Test {
    var extended:Extended;

    macro static function checkUnify() {
        trace("in macro function");
        Builder.checkUnify();
        return macro {};
    }

    static function main() {
        checkUnify();
    }
}
```

Using Haxe 3.4.2, result is expected
```
Test.hx:17: in @:build
Test.hx:13: Extended unifies Base? true
Test.hx:31: in macro function
Test.hx:13: Extended unifies Base? true
```

Using Haxe development (b5fca6d3a), the types didn't unify in build macro
```
Test.hx:17: in @:build
Test.hx:13: Extended unifies Base? false
Test.hx:31: in macro function
Test.hx:13: Extended unifies Base? true
```

This issue breaks ufront (=> haxelib website).

**Comment by Simn** [comment]
That's probably another consequence of Nicolas' change, see #6321.

**Comment by andyli** [comment]
Indeed, reverting 34f80449f27e332ddf070601913e26fd8430f0c7 fixed this.

**Comment by ncannasse** [comment]
The problem is the following : 

The compiler is working with several "passes". You are either at "class building pass" (PBuildClass) or "expression typing pass" (PTypeExpr). In this case you are trying to do some typing while still in PBuildClass, which is unsound from a pure typing point of view.  Let's say you are trying to check if a method is of a given type, this might require to type the method, which might require to type the class you are currently building, which you cannot because it's currently waiting for the result you need...

Before my patch, calling a Context.getType would start recursing, so it would go like this:

```
Building class A... (mode : PBuildClass)
     Calling getType... (mode : PTypeExpr)
         Flush pending unbuild classes
               Building class B...
```

So you would not get the class A built until all other classes are finished building, which creates a whole set of other isssues.

A proper way of dealing with it would be to make the whole class building lazy instead of pass-based by changing `TInst (t_class, type_params)` to  `TInst (bool -> t_class,type_params)` and we would either be able to get the class in a unbuilt state (false) or built state (true) depending on the compiler passes we are in. But that's a massive change in Haxe implementation.

**Comment by back2dos** [comment]
So you're saying that build macros cannot call `Context.getType` anymore?

**Comment by ncannasse** [comment]
This is more precise than that. Calling getType will work, and given that we force class building when doing cl.get() , classes fields will be populated (unless it's already on the build stack). 

Things are more complex when you try to do actual typing (Context.unify in above case), because you're doing typing while still in PBuildClass pass (which you usually shouldn't do) so depending if the classes have already been built or not you might get strange results.

Actually, we could do things better by doing the following:

- in typing_timer : force a flush when changing the pass, so we are sure that classes are correctly built before entering typing
- cast_or_unify doesn't use typing_timer true as it should

currently in japan so I don't have everything setup to try this, maybe @Simn can have a look

**Comment by Simn** [comment]
That won't quite work like that. Context.unify relies on the unification error being thrown in order to return `false`, but `typing_timer` catches any `Error` and turns it into a real compilation error.
