### ISSUE TITLE
JS variable shadowing 

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6409]
```haxe
package foo;

enum E {
    Flags( v : String );
}

class Main {
    static function main() {
        var foo_E = null;
        var f : foo.E = Flags(""); // runtime error 
        trace(f);
    }
}
```

The `foo_E` variable will shadow our foo.E enum, this error has been introduce by package flattening

**Comment by Simn** [comment]
This might be difficult to fix. It's easy in the specific case you reported because we can find the `E` type in the local module, but it might very well be defined in a completely different module. This would then require browsing all types to find potential conflicts.

I guess we can do that as a preparation step for `rename_local_vars`.
