### ISSUE TITLE
[display] range issues with metadata in macro reification

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6418]
```haxe
class Main {
	static function main() {}

	macro function foo(e:Expr) {
		macro @:pos(e.pos) $e;
	}
}
```

When hovering over any part of `macro @:pos(e.pos)`, the entire function's range is highlighted:

![](http://i.imgur.com/2hUrtbN.png)

```
> haxe --display Main.hx@89@type
<type p="..\main.hx:4: lines 4-6">
haxe.macro.Expr
</type>
```

**Comment by Simn** [comment]
The problem here is that `@:pos` itself is a metadata which disappears during reification. You are then left with just the annotated expression, and since that doesn't include the display position, you get the entire function.

The only way to fix this would be by including `@:pos` itself in the AST somehow. I don't think that's worth it.
