### ISSUE TITLE
[display] @type is not showing docs for properties with getters

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6422]
```haxe
class Main {
    static function main() {
        property;
    }

    /** docs **/
    static var property(get, set):Int;
    static function get_property() return 0;
    static function set_property(i) return 0;
}
```

The `@type` response to this is missing its docs attribute:

```
> haxe --display Main.hx@54@type
<type p="..\main.hx:3: characters 9-17">
Int
</type>
```

![](http://i.imgur.com/K8SshCt.png)

However, in the case of `(default, default)`, `(default, null)`, `(default, never)`, `(default, set)` and `(null, set)` it works fine:

```
> haxe --display Main.hx@54@type
<type p="..\main.hx:3: characters 9-17" d=" docs ">
Int
</type>
```

![](http://i.imgur.com/pQ0bcaK.png)

This suggests that having a getter is what breaks it.

**Comment by nadako** [comment]
The issue here is that at this position it's already transformed to a field call for which we don't provide any documentation source. We could handle `get_`/`set_` calls, but I wonder if we should match their name by the prefix or maybe there's some field meta that points to the original property field, from which we can retrieve the documentation without doing weird string operations?

**Comment by Simn** [comment]
We should be consistent here: If position-display goes to `get_property` then the docs should be those of `get_property`, too. The question is if position-display should go to `property` as well because that's what the user sees.

**Comment by Simn** [comment]
... and I think that's better because you can go to the accessor functions on the `get` and `set` anyway.

**Comment by Simn** [comment]
The test I added tests only the position because I didn't know how to escape the documentation in our documentation-based display tests.
