### ISSUE TITLE
Numeric types bug

### ISSUE THREAD

**Issue by gNikro** [HaxeFoundation/haxe#6463]
Target JS

```
var a:UInt = 2147483647;
var b1:Float = 2147651419;
var b:UInt = Std.int(b1);
		
trace(a, b); //2147483647, 2147651419
trace(Type.typeof(a), Type.typeof(b)); //TInt,TInt
trace(a - b); //4294799524
trace(2147651419, Type.typeof(2147651419)); //2147651419,TFloat
trace(2147483647, Type.typeof(2147483647)); //2147483647,TInt
```

second example

```
var uint32Arr:Uint32Array = new Uint32Array(data);
		
uint32Arr[0] = 2147483647;
uint32Arr[1] = Std.int(2147651419);
		
trace(uint32Arr[0], uint32Arr[1]); //2147483647,2147651419
trace(Type.typeof(uint32Arr[0]), Type.typeof(uint32Arr[1]));//TInt,TFloat
		
var a:UInt = uint32Arr[0];
var b:UInt = uint32Arr[1];
		
trace(a, b);//2147483647,2147651419
trace(a - b);//4294799524
```

So i can store value 2147651419 to uintArray even for haxe its not UInt, then i can also read that value as UInt but when i try to do something with value i will get overflow

Also why is 2147651419 is float while it should be UInt
BTW it still strange behavior because in some cases i see Type INT and its value is like UInt e.g 2147651419 apears as "Int 2147651419" but it actually not Int and not UInt its value actually casts to int and we get overflow

**Comment by Simn** [comment]
I'm having some trouble working out what you mean to report here. UInt when targeting JS is an abstract and thus a compile-time type. Haxe's reflection reports TFloat for anything outside the signed 32bit range because the run-time cannot distinguish unsigned and signed there (because there are no types).

In general, when the run-time only has "number" we have to make some sort of concession with regards to reflection. This is because we cannot tell where the value came from: It could have been a Float, an Int, an UInt, or perhaps something else.

I'll go ahead and close this as I cannot see anything wrong here. Feel free to reply with further details.
