### ISSUE TITLE
`Context.getType('.')` forces top-level completion instead of actual compilation.

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6499]
```haxe
//Main.hx
class Main {
	static function main() {
		Macro.test();
	}
}

//Macro.hx
class Macro {
	macro static public function test() {
		haxe.macro.Context.getType('any.string.which.ends.with.dot.');
		return macro {};
	}
}

//Shell
$ haxe -x Main
<il>
<i k="package">php</i>
<i k="package">sys</i>
<i k="package">haxe</i>
...
```
Instead of compiler error i get top-level completion.

**Comment by nadako** [comment]
I think this comes from here: https://github.com/HaxeFoundation/haxe/blob/development/src/typing/typeload.ml#L327

The `tname` is empty because it's the last part of dot-splitted type path, I guess. I think there's a check missing whether we're in display mode or not (it's a bit weird tho that type loading handles this, maybe it should be moved into the calling side).
