### ISSUE TITLE
Add ES6 class support

### ISSUE THREAD

**Issue by damoebius** [HaxeFoundation/haxe#6546]
Hi,
As mentioned in this thread https://github.com/HaxeFoundation/haxe/issues/4552#issuecomment-316024274 , it's important to have a way to use ES6 class instead of prototypes.
We could have either a compiler flag or a meta @:es6 on class definition.

**Comment by back2dos** [comment]
I find the option with metadata interesting, because one could just use [`--macro addGlobalMetadata("", "@:es6")`](http://api.haxe.org/haxe/macro/Compiler.html#addGlobalMetadata) to have it everywhere. OTOH I can't think of a use case of having mixed output. If ES6 is acceptable, you might as well use it for all classes and if it's not, then you cannot have it even for a single class.

**Comment by Simn** [comment]
We already have `-D js_es=5` so we should certainly use that.

**Comment by ncannasse** [comment]
Anyone willing to add support for -D js_es=6 classes ?

**Comment by fullofcaffeine** [comment]
@Nicolas this is relevant: https://github.com/kevinresol/hxgenjs/pull/4.
hxgenjs is serving as a playground for new gen js ideas / features. Perhaps
this could eventually be turned into an OCaml plugin or integrated into the
compiler.

**Comment by nadako** [comment]
I worked on this a bit and found one unfortunate behaviour of ES6 classes: in Haxe we currently can call `super` at any time inside the child constructor, but ES6 will complain if one tries to access `this` before calling `super`, e.g.:

```js
class A {
  constructor() {}
}

class B extends A {
  constructor() {
    this.v = 15; // ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
  }
}

new B();
```

The similar requirements are found in C#, but it's solved there by [using constructor overloading and moving actual constructor body into static functions](https://gist.github.com/nadako/94b5b67a1885a89f8f3eddf69f40a760). Obviously we can't do the same for JS because there's no constructor overloading.

Will have to think some more about how to implement this without much ugliness or run-time overhead. Advices welcome :-)

**Comment by nadako** [comment]
> Obviously we can't do the same for JS because there's no constructor overloading.

Well we kind of can, by having an `EMPTY` marker instance and adding `if (arguments.length === 1 && arguments[0] === EMPTY) return;` to emulate similar overloading:

```js
var EMPTY = {};

class A {
  constructor() {
    if (arguments.length === 1 && arguments[0] === EMPTY) return;
    A._hx_ctor_A();
  }

  static _hx_ctor_A() {
    console.log("base ctor");
  }
}

class B extends A {
  constructor() {
    super(EMPTY);
    if (arguments.length === 1 && arguments[0] === EMPTY) return;
    B._hx_ctor_B();
  }

  static _hx_ctor_B() {
    console.log("before super()");
    A._hx_ctor_A();
  }
}

new B();
```

Doesn't look cute though.

**Comment by nadako** [comment]
ping @kevinresol @back2dos as our js target power-users :)

**Comment by back2dos** [comment]
Yeah, I guess that's fine. I wonder if you could generate that code only when necessary and give a warning. But to be honest I don't use inheritance much, so I don't have a strong opinion here.

**Comment by kevinresol** [comment]
Sorry, but the fact is that I never explicitly touched ES6 at all. So I simply have no comments on this one.

**Comment by nanjizal** [comment]
Can it be implemented so the output is only complex when required or would that have side effects, I just thinking that the uglier the js looks the more objections there is against Haxe's use by mainstream.

**Comment by RealyUniqueName** [comment]
I think branching implementation is a bad idea in this case.
It will complicate code on the js generator side (more difficult to maintain, more error-prone) and it will complicate things for anyone who want to deal with the generated js.
Just an additional trouble for no real profit (correct me if i'm wrong).

**Comment by nanjizal** [comment]
Well that's a lot of boiler plate for code that will often not be needed, my understanding is in most case you don't need to run code before super - or is that always needed with Haxe inheritance in ES6 js?  

If you are trying to sell Haxe as a tech the first thing a javascript developer does is look at the generated code, I know because that is the first thing they do when you show them something cool created in Haxe when in a recent interview or at a js meetup.  

I often feel the '$', 'Hx', '_', '__', 'hx' etc...  prefaces can make Haxe generated javascript more daunting and will make it less appealing.  So quick experiment I just went through doing some search and replace on a reasonably sized experiment, often using 'x' instead of the other characters.  The code still seems to still work.  I guess '__stuff__' could be replaced with 'andStuff' or something to reduce the perl feeling.

https://gist.github.com/nanjizal/77f4b69115e0ad1d9df9bb308f25d517

Original demo here you can see the source feels less 'human' with $ and hx_ etc...
https://hxdaedalus.github.io/hxDaedalus-Kha-examples/build/basic/

For me the gist looks less scary, I know the current output is safe, but less people friendly.  Should I open up a suggestion in Evolution, I doubt if anyone will care because Haxe is all about good solutions which I understand and not really about impressions.  But anyway I hope illustrates atleast that complicating the js output can make haxe less inviting to people unfamiliar with the tech and may affect performance expectations ( ie js dev is going to feel it makes it slower even if it makes little real difference ).

Anyway won't further labour the point as I know that suggestions can add a lot of work and can increase stability risks, so I just bring it up, RealyUniqueName is probably correct.

**Comment by nanjizal** [comment]
it's stripped out some of the char, the 'stuff' part makes no sense, oh well.

**Comment by back2dos** [comment]
Well, I guess we need something like this anyway, because otherwise `Type.createEmptyInstance` is not going to work.

**Comment by ncannasse** [comment]
@nadako I don't have a better idea and yes as @back2dos said it's necessary anyway for `Type.createEmptyInstance`. You can maybe simply disable it in case the constructor (and the superclasses constructors) are pure, which should cover many cases already.

**Comment by nadako** [comment]
We use `Object.create(cl.prototype)` for `Type.createEmptyInstance` at the moment. Is that not compatible with ES6 classes?

Anyway, I'll look into extracting the empty-ctor filter from gencommon into something reusable for JS.

**Comment by back2dos** [comment]
Uhm, if that works., sure :)

IIRC the reason for ES6 classes was that something doesn't get set when you use prototypes instead of classes.

**Comment by nadako** [comment]
> IIRC the reason for ES6 classes was that something doesn't get set when you use prototypes instead of classes.

I'll have to research on that, maybe it's somehow related to classes implemented natively...

**Comment by nanjizal** [comment]
I hear of OpenFL having Typescript support but not looked into it, what is the official approach on Angular and Typescript. In my area React seems popular :( but talked to a dev in Oxford, a lot of the science parks are using Angular so it won't disappear.  

**Is ES6 important or just an easier fruit, I get the impression supporting ES5 is pretty much enough at moment?**  But neglecting TS is a decision that matter, which direction Haxe chooses is important and I am not convinced a strategy has been discussed, I am kind of worried about OpenFL offering Typescript has not been discussed. The worry is that  will all the toolkits end up getting rewritten in typescript, this could be a risk for Haxe's progress ? A plan in regard to Typescript should be made even if it's not public, but it should be about either to support or avoid it. 

Completely off topic but related to the toolkit risk is should haxe foundation fork Luxe, it has always seemed more robust than openfl and is simple and clean to use like heaps and does not need AIR so heaps in some respects is behind.  But I am not sure it can compete with the power of Kha, but we seem to have already lost a buildable Flambe ( can be built by haxe vetrans for html but not by new users, and for c++ I seemed a bit broken? ).

**Comment by ncannasse** [comment]
Regarding Typescript support, I've recently updated https://github.com/ncannasse/ts2hx to convert .d.ts to .hx

**Comment by jgranick** [comment]
Regarding TypeScript, generating `.d.ts` files to coincide with generated `.js` could be helpful, _especially_ if documentation is included as well. However, I'd be happy enough if we just get ES6 output, as that's basically what TypeScript is (with a different filename and optional annotations)

**Comment by Pign** [comment]
Hello,

I have troubles following the conversation… What is the current status of this request? Is it accepted? Is it awaiting a proposal for language design?

**Comment by fullofcaffeine** [comment]
I'd like to know as well, as this is relevant to a current codebase of mine. Any news here?

**Comment by back2dos** [comment]
I guess there are two issues:

1. dealing with the super constructor call having to be called before accessing anything else on `this`
2. supporting ES5 output as well, without creating too much of a mess.

**Comment by nadako** [comment]
I will implement the generation with super-call support as described before (have a wip branch already), but I think it'll release after 4.0 as this is quite a lot of changes and AFAIK we're in "soft-freeze" already.

**Comment by nadako** [comment]
implemented with `-D js-es=6` since 406d3fb2bfb4016b384082768182a3d470633ed8

**Comment by haxiomic** [comment]
Amazing stuff @nadako, thank you for working on this :)

**Comment by dionjwa** [comment]
Yeah I just noticed this, great stuff!

**Comment by sonygod** [comment]
how about add es6 decorator  support ? @nadako

**Comment by nadako** [comment]
Well AFAIK they are still draft proposal with experimental implementations. Also last time I checked they were just a syntax sugar for some function calls, which means they can be used with current haxe with a little bit more inconvenience that can be solved by macros :) I'd like to hear opinions on that from some more Haxe/JS users.
