### ISSUE TITLE
Dispatch.hx easier debug

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#6581]
Hi,
in haxe.web.Dispatch.hx runtimeDispatch function use a try catch that will make loose the debug stack trace when we have an issue in dispatchers code.

I think it would be great to keep the try catch only in release mode.

Thanks
Seb

**Comment by Simn** [comment]
Dispatch will be removed from the standard library for Haxe 4.

**Comment by sebpatu** [comment]
but its not removed yet.
i suppose that for backward compatibility, there will be a new haxelib containing the Dispatch code, where the request should be added.

**Comment by jonasmalacofilho** [comment]
@sebpatu its new home is [hx3compat](https://github.com/HaxeFoundation/hx3compat), but I'm not sure what the plans are for future work on those modules.

I actually use and maintain a [forked implementation](https://github.com/jonasmalacofilho/eweb.hx/blob/master/lib/eweb/Dispatch.hx) that takes into account the HTTP method during the dispatch (`doFoo()` vs. `getFoo()` vs. `postFoo()`).  If you think it's useful for your use case as well, you can post the issue there as well...

**Comment by jdonaldson** [comment]
I'm working on a replacement for Dispatch here: https://github.com/jdonaldson/golgi

It's macro based rather than reflection based, and already it's much faster.  However, it's still a work in progress.  Like Dispatch, it doesn't have features specific to http routing.

tink_web is also pretty similar, more focused on http routing, and much more mature : https://haxetink.github.io/tink_web/#/
