### ISSUE TITLE
remove @:font support?

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6624]
It's badly implemented and flash-only.

**Comment by nanjizal** [comment]
There is really no reason that the code can not be used on any platform ideally it could generate triangles for GPU graphics and for Canvas type platforms it could define an interface eg:
https://github.com/nanjizal/justTriangles/blob/master/justTriangles/IPathContext.hx
Currently many graphics toolkits implement fonts with images, there is a post by Hugh on NME 
http://gamehaxe.com/2011/03/28/nme-font-rendering/
and Kha uses Kravur eg: 
https://github.com/Kode/Kha/wiki/Kravur-(Adding-fonts)
But it's incredibly useful to have vector fonts, either as precalculated triangles using something like 
poly2trihx
or as canvas style draw commands, this allows you to either resample points equally for transformations like fisheye or just to get really clean fonts at any scale.  
Seems a shame to remove this would be nice to perhaps develop it for more general use.  Also for flash/openfl target it's very important, till you give up flash support totally I feel it's not appropriate to remove this anyway?
You can argue that this is beyond the scope of Haxe compiler but Haxe is used for practical pragmatic creation of games and applications so it can be very useful.  To do font fill of vector at runtime on GPU is not really very practical but to use precalculated triangles is efficient, so having Haxe complier help with this is worthwhile for anything related to advertising and games.
But agree it should not be just for Flash it would not be too hard to get it more useful for all languages, suggests move towards generic canvas and triangle support and retain current flash fonts.  Perhaps foundation members have some thought but from gaming perspective it could be useful.  I seem to remember creating some basic svg output support which considering I don't really do Ocaml code, it can't be too bad to work with, but long since probably lost code.

**Comment by nanjizal** [comment]
ousado interested in helping extend this to be generic useful.  Simn you talked about Ocaml external module support would this be a good project to test this with?

**Comment by nanjizal** [comment]
Ideally an option to provide triangles based on equal spaced points this would not be too heavy for ocaml but really heavy to do well in haxe at runtime, this would provide vector fonts that can be warped in anyway a user wants.

**Comment by fullofcaffeine** [comment]
Maybe this could be re-implemented as a macro and routed to an external
tool?

**Comment by nanjizal** [comment]
fullofcaffeine I am sorry but your suggestion is really stupid.

Ocaml is much faster, if it becomes a standalone Ocaml tool it would be lost? 

Essentially it was the hxswfml font part written in Ocaml, if it was ported to a macro it would be slower and unreliable as it would be tied to macro improvements. Making as a macro is really bad idea for this code as it would run much slower and add a mainentence debt for the Compiler team for a feature that is not currently used often.  At moment keeping it is not expensive.  If ported to a macro it would need to be kept up to date.

As far as I remember it works without any maintenence, when was the last time it needed changing?

 So while I understand it's use case is fairly minor, justification for removing it is also unjustified, if the only reason is to make compiler flags simpler it seems a bit of a shame. 

To get embedded font for flash target, it is surely simplest way, after all if you only want flash say for AIR you really don't want OpenFL or NME dependancy as they are not always sync'd with nightly Haxe.

I think it would be nice extended, but would understand if it was removed if flash target was removed.  Given AIR is still supported with no current end of life for AIR itself ( Yet ), swf's are not really going away that fast, looking at the Stage3D facebook group there are still many commited to AIR platform and flash support is still very useful for companies wanting soft transitions to Haxe, where they can rebulid part of their code base in parts gradually.

There are still thousands and thousands of AIR products perhaps millions on the itunes store written in AS3, for Haxe to reduce tools that help soften the transition with Haxe rather than go for mainstream non haxe solutions, and to require they need to use OpenFL does not seem ideal.  Prefer they move all the business logic over to Haxe and then consider all graphic engines in relation to c++/js in terms of their needs and timescales.

I understand factoring it into a standalone tool but after the work to get it into Ocaml really seems quite absurd to want it as a macro, macros don't solve everything!!

Perhaps as a standalone tool if that's feasible - I think it may have some hooks in other parts of the compiler that would make it hard to separate and would be an effort to separate and properly test no functionality was lost.  But it could be nice for Haxe developers wanting to get into Ocaml then perhaps it's less daunting than the main Compiler project as a place to contribute extend and explore?

**Comment by Simn** [comment]
> fullofcaffeine I am sorry but your suggestion is really stupid.

Can we not do that? Thank you.

Having this implementation is pointless. If anything, a native C implementation should be linked via OCaml CFFI and that can then be used. Still, I'd just keep https://github.com/HaxeFoundation/ocamllibs/tree/master/ttflib around in case somebody wants to do something with it for whatever reason.

**Comment by fullofcaffeine** [comment]
> fullofcaffeine I am sorry but your suggestion is really stupid.

Don't want to start a flame here, but it you might want to review your
netiquette manners. That was a really harsh way to answer an idea shootout.
I was just trying to help, as I don't think this should be a burden that
the core team should be maintaining as part of the compiler itself.

Anyway, I don't really use it and don't care about Flash (anymore), so I'm
indifferent about it.

**Comment by back2dos** [comment]
People. Saying that *an idea* (as opposed to a person) is really stupid is a perfectly valid response, because non-stupid ideas are the absolute exception (and anyone who thinks their ideas are an exception to the rule is in really big trouble). Everyone should be at liberty to suggest any idea, stupid or not, and in the former case everyone who can make a case *why* the idea is stupid should do that (and whether or not you agree with Justin, he made a genuine effort). It's for the benefit of everyone.

To suggest decisions out of indifference for the matter does not only slash your odds of not saying something stupid, it borders on disrespect. Entering a discussion not caring one bit about somebody else's use case does all but give you the high ground to police their choice of words. As a community, we have more to gain by caring about what people need than how they express themselves, so long as they don't resort to personal attacks.

We all care deeply about some aspects of Haxe, so let's please agree to focus on those and just try (I know it's hard) to sit out the rest. That's a great way to piss people off a lot less. While I don't care about the subject at hand, I can perfectly relate to how Justin reacted. Thank you for your consideration.

**Comment by Simn** [comment]
I'm not interested in any meta-discussions here. Just let it go, thank you.

**Comment by back2dos** [comment]
You brought it up. So, which one is it?

**Comment by ncannasse** [comment]
I don't see the value added of removing something that works, especially if there's no maintenance required for it. We could try to have it implemented in pure Haxe instead, but that would require extra work on the flash target and I don't think we want that either.

**Comment by Simn** [comment]
It doesn't really work though, see #4596 as an example.

**Comment by ncannasse** [comment]
It works in many cases, maybe some modern fonts are not supported in which case I'm ok if we simply redirect users to the code and ask them for a PR if they want to help with it.

**Comment by nanjizal** [comment]
The Ocaml is based on Jan's TTF parser used in hxswfml, this same engine in Haxe in an improved form is used by hundreds of thousands, perhaps millions of VideoScribe users, but I had to fix it for lots of TTF that users supplied many were pretty bad TTF, the production code works on apple, pc or mac TTF on apple, mac or pc using AIR.  So there is absolutely no reason it can not work it just needs lots of test cases and some effort, I did feedback many of my tweaks to Jan but some were ignored and I think a new version of Haxe came out that did switches on enums differently and he started to loose interest in Haxe, but the modified code was updated.

The main problems I seem to remember were that some fonts used apple font table information not well documented, incomplete font tables or just full of broken glyphs, because TTF is fairly complex some fonts creators just do the minimum and you have really rather bad fonts to deal with, they look good but are rather incomplete many times just limiting the length of the Glyph For loop allows bad fonts to be processed by ignoring the later Glyphs.

So the Ocaml tool just needs lots of test fonts ( apple and pc ) and to compile a terminal c tool to inspect visually the broken glyphs, normally you can just change the for loop length to run till the broken Glyph, then look at why it breaks and put in protection for really crap data or some logic to use the font tables differently.

Given lots of time, lots of fonts and some funding I could work on making it more reliable and with some specifications we could adapt it to be more useful on all Haxe platforms, without lots of users it's hard to get access to lots of bad TTF!  I guess the main practical problem is that unless you triangulate the data, draw commands are not much use to a GPU since fills are too slow, but should be fine for Canvas.

But it's not a fun job to work with Fonts and unless there was specific requirement I doubt anyone would want to put the effort into taking it further.  I would give it a go but since I am not working spending lot of time on this does not seem a good idea, I would be better learning PHP, Python, Angular4 etc... as I am sure you would appreciate.

So Nicolas assertion is correct it works just not on every font but that can be fixed and I don't feel the code is inherently bad, it just needs tweaking for real life fonts?

**Comment by nanjizal** [comment]
Most code that processes TTF is c because a font like Arial has tens of thousands of Glyphs and that can take a very long time to process into draw commands, so it's not too practical to use Haxe for this certainly not Haxe flash, Ocaml is better but some changes to the loop may well improve speeds greatly most font you only need a small part.

**Comment by fullofcaffeine** [comment]
Fair enough.

**Comment by Simn** [comment]
Fine, we'll keep it for now.
