### ISSUE TITLE
"Unbound variable, please report this"

### ISSUE THREAD

**Issue by FireSlash** [HaxeFoundation/haxe#6674]
Haxe Version: 4.0.0-preview2
Dependencies: pixijs 4.5.5 (I tried to build a repro case with haxe's built-in json loader but failed)

I stripped down this code as much as possible to repro, so the it doesn't technically work anymore, however the purpose is simply to illustrate the bug. I'm actually not sure the code ever could have worked in the first place, but the compiler output isn't desirable in either case.

code:
```
import pixi.loaders.Loader;

typedef SomeStruct = {
	foo : String
};

class Main
{
	private var someArray = new Array<SomeStruct>();

	public function new( )
	{
		var someLoader = new Loader();
		someLoader.load(function(response) {
			var foo = response.resources["assets/someFile.json"].data;
			
			someArray.push({
				'foo': foo.bar,
			});			
		});
	}

	static function main() 
	{
		new Main();
	}
}
```

Compiler output:

```
Unbound variable, please report this
{
        v_id = 2230;
        v_name = `this;
        v_type = Main;
        v_capture = false;
        v_extra = None;
        v_meta = [];
}
```

Compiler options:
```
-cp src
-lib pixijs
-main Main
-js dist/main.js
-D source-map-content
-debug
```
(Output is repeated a second time, but identical)

data in this context should be a Dynamic, though you may want to dig into pixi/loaders/Resource.hx for more information on the exact types being used

**Comment by Simn** [comment]
```
typedef ResourceLoader = {
	var resources:haxe.DynamicAccess<String>;
}

class Main {
	var someArray = [];

	public function new() {
		load(function(response) {
			response.resources["foo"];
			someArray.push(null);
		});
	}

	@:overload(function(cb:ResourceLoader -> Void):Void {})
	static public function load(cb:String) { }

	static function main() {
		new Main();
	}
}
```

Reminds me of https://haxe.org/blog/this-is-not-the-variable-you-are-looking-for/

This is a problem in general typing. It arrives like this at the analyzer:

```
While analyzing Main.new
<initial>
function() {
        Main.load(function(response<630>:ResourceLoader) {
                cast cast response<630>.resources["foo"];
                `this<635>.someArray.push(null);
        });
}
</initial>
```

My first guess is that `@:overload` and closure-this don't work well together. I'm not quite sure how the `DynamicAccess` is involved though.

On a related note, that pixijs load function looks wrong to me:

```haxe
	@:overload(function(?cb:ResourceLoader -> Dynamic -> Void):ResourceLoader {})
	@:overload(function(?cb:ResourceLoader -> Void):ResourceLoader {})
	@:overload(function(?cb:Void -> Void):ResourceLoader {})
	function load(?cb:Dynamic):ResourceLoader;
```

That would almost always take the `?cb:Dynamic` version because you can assign anything to it.

**Comment by Simn** [comment]
In fact, giving the `?cb:Dynamic` lower priority avoids the issue. But there's obviously still something wrong on our end.

**Comment by Simn** [comment]
What happened here was that our `type_function` was not exception-safe: If an error exception was raised while typing the function expression, the original state would not be restored. This means that the local function set the context to "local function", raised an exception, and the field function would then think it was also a "local function" and thus not generate a `this` variable.

This is usually not a big deal because if typing fails, it fails. However, with overloads involved, we want to "try again" with a clean state.

**Comment by nadako** [comment]
I wonder if it would be safer to rework these `save_something -> restore` functions so they take some function as argument and encapsulate saving/restoring completely, e.g.

```ocaml
let with_saved_function_state ctx f =
  let old_stuff = ctx.stuff in
  let restore = ctx.stuff <- old_stuff in
  Std.finally restore f ()

(* and then... *)
with_saved_function_state ctx (() -> 
  ctx.stuff <- blah blah;
  more_stuff ();
);
```
