### ISSUE TITLE
Context.getBuildFields() also getting non-class fields (local variable declarations) during type completion

### ISSUE THREAD

**Issue by Glidias** [HaxeFoundation/haxe#6695]
var fields = Context.getBuildFields();
	for (f in fields) {
		Context.warn(f.name, Context.currentPos());			
	}

A function within  class.

	function saveSomething():Void {
		// type the following line to trigger type completion...
		// this.

		var ab:String;
	
	}

Execute type-completion at a position before any local "var" declarations (not after), and Context.getBuildFIelds() also wrongly picks up the local var fields `ab` underneath! Why? For the field names  they result in: `["saveSomething", "ab"]`

During actual compile/build, it doesn't pick up the local `ab` field.

**Comment by Simn** [comment]
Yes that can happen due to how the parser resumes on an error. It's not really possible to tell if you're declaring a local variable or a variable field there.

The only heuristic would be indentation. But we currently completely discard whitespaces during lexing, so I don't think we could add this easily.

**Comment by Glidias** [comment]
What is Context.getBuildFields() actually, was under the impression that it should only return class fields. So, this is supposed to be expected behaivour? 

THat's not good, because my framework can wrongly pick up certain fields and "think" there's an error or something wrong with a certain convention of a class member field being declared.

**Comment by Simn** [comment]
Well, your framework arguably shouldn't perform such checks while in display mode anyway, so that's probably the way to go about addressing this. In general, you should be very shy with your macros in display mode because the compiler skips a lot of things and only types the minimal information required to provide display information.

It's common practice to have some `#if !display` in macro code, and to use `Context.defined("display")`.

**Comment by Glidias** [comment]
I see, okay, that was what i was looking for.
