### ISSUE TITLE
[cs] native compilation error with side-effect-free statement

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6784]
The following fails to compile to C#:

```haxe
class Main {
    public static function main() {
        cs.system.Console.BufferHeight;
    }
}
```

```
> haxe -main Main -cs cs
haxelib run hxcs hxcs_build.txt --haxe-version 4000 --feature-level 1
src\Main.cs(29,3): error CS0201: Nur assignment-, call-, increment-, decrement-, await- und 'new object'-Ausdrücke können als Anweisungsrc\Main.cs(29,3): error CS0201: Nur assignment-, call-, increment-, decrement-, await- und 'new object'-Asrc\Main.cs(29,3): error CS0201: Nur assignment-, call-, increment-, decrement-, await- und 'new object'-Ausdrücke können als Anweisung
        verwendet werden.
Compilation error
Native compilation failed
Error: Build failed
```

Of course, the example is a bit silly because it doesn't do anything, but it probably still shouldn't fail during native compilation like that since it's valid Haxe code?

Haxe version: 37f6b2a9b

**Comment by nadako** [comment]
Normally, C# generator creates a temp var for those cases, but here I think what happens is that from the Haxe standpoint it's a `get_BufferHeight()` call (which is then generated as `BufferHeight` property access), so it leaves it unchanged because function calls should be fine. So I guess the "temp var generator" filter should be a bit smarter and handle lone getter calls. Also maybe there's some purity info in the IL which we could reuse to make Haxe analyzer not generate these calls at all.

**Comment by waneck** [comment]
I ended up just detecting this when generating the actual C# code. That temp var generator seems to have been removed, as it's not needed anymore - something (I imagine the analyzer) already detects them before
