### ISSUE TITLE
bootstrap from source ?

### ISSUE THREAD

**Issue by rofl0r** [HaxeFoundation/haxe#6806]
hi, i want to provide haxe for my source-based distro [sabotage linux](https://github.com/sabotage-linux/sabotage), but i don't see any download suitable to bootstrap from source. since there's no existing haxe toolchain available, just fetching the source tarball from github is not sufficient (as haxe is written in haxe). we would need a source tarball containing the haxe source transpiled into C++.

**Comment by andyli** [comment]
Nah, haxe is written in ocaml, not haxe, so there is no need to bootstrap. BTW, haxe (haxelib, to be accurate) depends on neko, so you should look into packaging neko first.

You may find other distros' haxe/neko packages helpful since they contains all the details on how to build the things. e.g. Fedora's:
 * https://src.fedoraproject.org/rpms/haxe/blob/master/f/haxe.spec
 * https://src.fedoraproject.org/rpms/nekovm/blob/master/f/nekovm.spec

**Comment by rofl0r** [comment]
ocaml? are you kidding?
if not, that's a major downer... i don't have an ocaml toolchain, and i didn't intend to add one :/

**Comment by andyli** [comment]
Feel free to get in touch if you change your mind to package ocaml. There is nothing we can do until then.
