### ISSUE TITLE
[abstract] transitive cast through underlying type

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6814]
Extracted from gitter:

```haxe
class Test {
    static function main() {
        var to:ToString = cast 'to';
        test(to);
    }

    static function test(v:FromString)
        trace(v);
}

abstract FromString(String) from String {}
abstract ToString(String) to String {}
```

Currently fails with 

```
Test.hx:4: characters 13-15 : ToString should be FromString
Test.hx:4: characters 13-15 : For function argument 'v'
```

I think that the compiler should be able to figure out there are compatible `from/to` in the two types. However, considering all combinations of the convertible types on both sides could be expensive. So I propose the compiler should only consider the underlying type as the bridge. In other words, it should work if and only if:
1. the underlying type of the two abstracts are the same; AND
1. the transition can be done through the underlying type

**Comment by ncannasse** [comment]
That seems quite arbitrary to allow such cases of transitiveness and not the more general ones, but I understand why you would want to restrict to it. Keeping open for now

**Comment by Simn** [comment]
We should not allow this. It looks good in your example, but falls flat when you have something like https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/issues/Issue3360.hx. You do _not_ want to be able to assign `Vec3` to `Quat` there, despite both of them being defined over `Array<Float>` and implicitly casting to it.

Something like this would have to be dependent on some additional metadata or something. But I don't want to extend abstract casts in any way for the time being because it's already too much of a mess as it is.
