### ISSUE TITLE
Should implicit cast works on default parameter value?

### ISSUE THREAD

**Issue by romanmikhailov** [HaxeFoundation/haxe#6879]
I have a method with `haxe.Int64` parameter and I want to specify default value for this parameter.
I specify -1 as default value. But it causes compilation error:
```
Test.hx:9: characters 40-42 : Int should be haxe.Int64
```
Example:
```haxe
import haxe.Int64;

class Test {
    static function main() {
        fromLong(10000);
        fromLong();
    }

    static function fromLong(value:Int64 = -1) {
        trace(value);
    }
}
```
https://try.haxe.org/#28701

Why implicit cast doesn't work here?

**Comment by RealyUniqueName** [comment]
Maybe it should work indeed since default values are part of a function implementation in Haxe and not part of a function signature.

**Comment by nadako** [comment]
Seems like it should work.

**Comment by RealyUniqueName** [comment]
I don't think it's a bug.
Currently it follows the spec. Because provided example means this in fact:
```haxe
static function fromLong(value:Int64 = Int64.fromInt(-1)) {
    trace(value);
}
```
Which is obviously not allowed, because `Int64.fromInt(-1)` is not a constant value.

It _could_ work, because it could be implemented. 
But it _should not_ work right now according to current spec we have.

**Comment by Simn** [comment]
Casts shouldn't be allowed there.

This particular problem will be solved once we have Int64 literals. I think it would just work as-is then.
