### ISSUE TITLE
[eval] Performance issue of Array write access

### ISSUE THREAD

**Issue by daisuda** [HaxeFoundation/haxe#6904]
``` haxe
package;
#if !macro
class Main 
{
	static function main() 
	{
		MyMacro.bug();
	}
	
}
#end
class MyMacro {
	public static macro function bug(){
		var tt = new Array<Int>();
		trace("begin");
		for (i in 0...999999){
			tt[i] = 0;//VERY SLOW, wait a couple of minutes
			//tt.push(0);//ok
		}
		trace("end");	
		return macro trace("hi");
	}	
}
```

haxe version: nightly build and 4.0.0-preview.3

**Comment by back2dos** [comment]
Maybe writing out of bounds should generally be discouraged? Instead, we could inline `push` on platforms where `a[a.length-1] = x` is faster.

**Comment by nadako** [comment]
> Maybe writing out of bounds should generally be discouraged?

I agree, but I don't see this being changed anytime soon, but we could totally optimize the "writing to the last+1 index" to work as `push` (i assume it preallocates space, so it's faster next time?)

**Comment by Justinfront** [comment]
Last time I looked there was still an Array/Vector issue on Flash AIR with using push and unshift verses array access, this is because it takes an allocation that it does not release it straight away, I have a feeling there maybe something similar in js.
What happened with   arr.length = 0;   was that implemented in Haxe?

**Comment by RealyUniqueName** [comment]
> What happened with arr.length = 0; was that implemented in Haxe?

We will probably get `Array.resize(n)` https://github.com/HaxeFoundation/haxe/pull/6869

**Comment by Simn** [comment]
This is a bit of an anti-pattern for the eval array implementation. You can speed it up by pre-allocating the array size, i.e. having `tt[999999] = 0;` before the loop start. This could probably be detected with some analysis, but it would also probably miss more complex cases.

The root of the problem is that the internal `set` function pessimistically resizes the array to `elementOffset + 5`, whereas push, insert and unshift resize it to `currentLength * 2 + 5`. It feels wrong to double the length on a set though, so I'm not sure what the best approach is.

An option might be to keep track of how often an array has been resized, and if that number crosses a threshold, double the size on all future set operations. Of course, this would require additional bookkeeping, so it may or may not be worth it.

**Comment by ncannasse** [comment]
Could we have a summary of the targets that are impacted by this
performance issue apart Eval ?

**Comment by daisuda** [comment]
Thank you Simon and happy to see you again.
