### ISSUE TITLE
Very Strange bug in c++ (true == true => false)

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#6906]
The following zip file contains 3 files (somehow the package p1 seems to be important)

[bug_cpp.zip](https://github.com/HaxeFoundation/haxe/files/1811855/bug_cpp.zip)

Just run the code and you will see output like:
```
BoolTraits.hx:12: true,true,false,false
Main.hx:9: false
BoolTraits.hx:12: true,true,false,false
Main.hx:10: false
BoolTraits.hx:12: true,true,false,false
Main.hx:11: false
```

which is very strange because 
a => true, 
b => true, 
but a == b is false.

if you run the code multiple times, you can get different outputs like:
```
BoolTraits.hx:12: true,false,false,false
Main.hx:9: false
BoolTraits.hx:12: true,false,false,false
Main.hx:10: false
BoolTraits.hx:12: true,false,false,false
Main.hx:11: false
```
or
```
BoolTraits.hx:12: false,true,false,false
Main.hx:9: false
BoolTraits.hx:12: false,true,false,false
Main.hx:10: false
BoolTraits.hx:12: false,true,false,false
Main.hx:11: false
```

which is quite strange.

**Comment by hughsando** [comment]
The problem is that a templated interface (Eq, which must logically use Dynamic for template args) is used to call a non-templated function (BoolTraits.eq which has non-Dynamic args).  I need to insert a glue function to convert the args here.
When the arg types mismatch, you get crap on the stack which may or may not work, which explains the issue (and why I can't reproduce on windows)
You might also want to make this interfaces generic to avoid Dynamic - and work around this bug.

**Comment by hughsando** [comment]
Turns out I was creating the glue, but not using it.

**Comment by frabbit** [comment]
Thx, looks good, seems to work now ;). I have a lot of problems with generic in haxe (limitations mainly), so that's not an option atm, but that's a different topic ;)

**Comment by frabbit** [comment]
i will leave this open and add a unit test later.
