### ISSUE TITLE
[Static Extension] Cannot call static method - "Too many arguments" error

### ISSUE THREAD

**Issue by T1mL3arn** [HaxeFoundation/haxe#6936]
If `foo`'s arg is `Dynamic` then there will be error `Too many arguments`. If we change type to `Int` it does compile.
```haxe
using Test;
using Test;
class Test {
    static function main() {
        new Test();
    }
    
    public static inline function foo(arg:Dynamic)
    	trace(arg);
    
    public function new(){
        foo(123);
    }
}
```

Is this expected behavior with `Dynamic` type and Static Extension ?

Tested on 3.4.4 and 3.4.7. Online code sample https://try.haxe.org/#Cc8f1 .

**Comment by dpomier** [comment]
Yes it is :) 
Here the first argument of the `foo` call is the instance of your class `Test`

**Comment by bendmorris** [comment]
>If foo's arg is Dynamic then there will be error Too many arguments.

This happens because, with `using Test`, anything that unifies with the first arg's type `Dynamic` (so anything really, including `Test`) will enable `foo` as a static extension method. Static extension methods implicitly pass the instance as the first argument, so the int is an invalid second argument.

> If we change type to Int it does compile.

That's because `Test` *doesn't* unify with `Int`, so you're just calling a static function at that point, and passing in one argument.

**Comment by kevinresol** [comment]
`foo(123)` is essentially `this.foo(123)`, so static extension is applied on `this` which means essentially you are calling `foo(this, 123)`, thus the error.

**Comment by T1mL3arn** [comment]
So `foo(123)` becomes `Test.foo(123)` and it leads to the error because of static extension. Understood, thanks!
