### ISSUE TITLE
Leading optional arguments mess up inference.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#6937]
Here is an example (https://try.haxe.org/#c9e03):

```haxe
class Test {
  static function main() {
    var o = new Observable([123]);
    o.select(function (v) {
      $type(v);
      return true;
    });
  }
}

class Observable<T> {
  public function new(value:T) {}
  public function select(?options:{}, cb:T->Bool) {}
}
```

I get two warnings for the `$type`: first `Unknown<0>` and next comes the correct `Array<Int>`. I would speculate that it's because when the compiler realizes there's no way for an `EFunction` to unify with `TAnonymous`, it aborts top down inference and looks at the thing bottom up, then comes to the conclusion that `Unknown<0>->Void` still isn't `{}` and only then skips the `options` argument. And if there are errors from the bottom up inference (e.g. https://try.haxe.org/#Ac68d) that part is not even reached.

Would there be a way for the compiler to "remember" errors and warnings if the argument is optional and only display them if it can't find another solution?

**Comment by fondation451** [comment]
Hello, I am new in this project, and that would be my first issue in this project.

I had a look at the code, and I think the problem is that once a warning has been thrown to the server, it can not be removed easily in the typing process.

Here we have a first try of unification of type of the anonymous function with the first parameter (optional) options. Obviously it fails, and it carries on with the unification of type with the second parameter which is a function and succeed. It corresponds to this particular portion of code of the function `unify_call_args'` in the file calls.ml (line 172) :

```ocaml
	| e :: el,(name,opt,t) :: args ->
		begin try
			let e = type_against name t e in
			(e,opt) :: loop el args
		with
			WithTypeError (ul,p)->
				if opt then
					let e_def = skip name ul t p in
					(e_def,true) :: loop (e :: el) args
				else
					arg_error ul name false p
		end
```

The first time, it fails and it raises the exception `WithTypeError`. At this point, the body of the anonymous function has already been visited and the warning message has already been sent to the server. The second unification try succeed and throw another warning to the server.

We need to get rid of the first warning message when it fails. The problem is that we do not have the access to the context of the server during the typing process. The warnings are stored in this context.

So I have two questions.

- Is the context of the server really not accessible from the typing process ? It seems so, but I am not sure.
- One solution that I could propose is to modify the function message in `main.ml` which deals with the message (warnings) to the server. One possible solution would be to have only one warning for each position. If two warnings are on the exact same position, the oldest should be removed. Does it look like a fair solution ?

Nicolas

**Comment by Simn** [comment]
Unfortunately, the issue didn't specify the observed behavior. Running this on latest I also get these two warnings and the code compiles fine. The linked try.haxe is empty, so I'm not sure what the problematic case here actually is. I'll go ahead and assume that the issue has been resolved, otherwise feel free to reopen!

**Comment by Simn** [comment]
I just found #5522 which might be a good example of the problem.

**Comment by kLabz** [comment]
Not sure either what exactly this was about, but with dev I see two occurrences of `$type`: `Unknown<0>` and `Array<Int>`; while with #12945 I only get the correct `Array<Int>`.
