### ISSUE TITLE
[display] @position fails on function argument with `?`

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6943]
```haxe
class Main {
    public static function main() {}

    function foo(?test:Int) {}
}
```

A position request on `test` should return test itself again, but the result is empty:

```xml
>haxe --display Main.hx@68@position
<list>
</list>
```

If you remove the `?` from the parameter, it works as expected:

```xml
>haxe --display Main.hx@67@position
<list>
<pos>Main.hx:4: characters 15-19</pos>
</list>
```

This breaks vshaxe's rename, which makes use of `@position`, if invoked on the parameter itself (still works on usages of it).

**Comment by Simn** [comment]
This took me forever to find. The problem was that we generated the implicit `= null` default value with the position of the field, and then the expression display handler picked that up and though we were looking for the position of `null`.

I have fixed this by using `null_pos` for the generated expression, like we do for generated metadata.
