### ISSUE TITLE
[js] haxe.CallStack.lastException is potentially leaking

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6966]
We with @NenadBojkovski just discovered that storing last caught exception in `haxe.CallStack.lastException` is problematic, because it retains references to outer context and thus can cause memory leaks. Apparently, even if the exception is a simple string wrapped in the `HaxeError`, it'll retain the context due to stack information capture, so the objects on the stack won't be collected.

I wonder how realistic would be to teach the compiler to clear the `lastException` value in the end of the catch expression. This obviously must take control flow into consideration (e.g. early return/break).

**Comment by Simn** [comment]
The way exceptionStack() is documented it is supposed to retain that information, which means we couldn't clear it like you suggest.

**Comment by nadako** [comment]
Is it?

> stack elements between the place the last exception was thrown and the place it was caught

That can be interpreted differently I guess. To me it makes sense to only guarantee this information within a catch block. 

I guess we need @ncannasse to clarify this.

**Comment by R32** [comment]
Why doesn't remove it in release? Actually the callstack message has been confusing to me that i can‘t quickly find where the error occurred

**Comment by Simn** [comment]
We should look into this for Haxe 4 because it might be a "regression".

**Comment by Simn** [comment]
Does anyone feel responsible for this?

**Comment by nadako** [comment]
I kind of do, but it'll take quite some time before I can look into it and even more before I'll be able to figure it out :)

**Comment by RealyUniqueName** [comment]
I don't see the need to store the whole exception. The only thing, which should be stored, is the call stack. Which does not hold any references.

A better approach would be to change exceptions and `haxe.CallStack` completely. 
Haxe wraps exceptions into native target types anyway, so why doesn't it expose those native exceptions to the user code?
That will allow to access exception stack at any time even if some other exception was thrown inbetween. As the bonus, it will save some cpu and memory, because of no need to store and handle each exception for `haxe.CallStack.exceptionStack()`.
Something like this:
```haxe
try {
   throw "Terrible error";
} catch(first:Exception<String>) {
  trace(first.origin); //Terrible error
  try {
    throw "Another error";
  } catch(second:Exception<Dynamic>) {
     trace(second.origin);
     trace(second.stack);
     trace(first.stack); // the stack of the first exception is still available!
  }
}
```

**Comment by ncannasse** [comment]
Storing `.stack` value might be expensive in case we don't use it, because it's mostly likely something lazy that only gets built upon request.

That bring us to the proposal of having a proper Exception type: I'm not sure we can have this working for all platforms. For instance HL and Neko does maintain a single (per thread) exception stack, so it would require to copy it for every catch in order to get the require behavior. Nothing avoidable, but it adds to the cost of using exceptions. I'm not sure about other platforms.

**Comment by RealyUniqueName** [comment]
> Storing .stack value might be expensive

Targets I checked already provide that value with every exception. So we don't need to store it (`.stack` is just an example; could be a getter)
Didn't know about Neko and HL.  This requires a deep investigation and a detailed proposal.

**Comment by ncannasse** [comment]
Back to the original thread message: even if we did set lastExpression = null, that would still leak for uncaught exceptions. 

Otherwise, I'm fine restricting CallStack.exceptionStack usage to within-catch-block-only. That would allow something such as inlining an access to the local var "$e" that happens to be the exception caught in JS catch, removing the need for lastException entirely.

**Comment by nadako** [comment]
@RealyUniqueName IIRC the issue we had was exactly because of the stack information holding objects
@ncannasse uncaught exceptions won't leak because `lastException` is only set in `catch`.

**Comment by ncannasse** [comment]
@nadako can you take of this soon ? thanks :)

**Comment by nadako** [comment]
I was kind of hoping @Simn will look into this, because I think it should be handled by the analyzer somehow, because we need to consider control flow, maybe we could try doing this together at the HaxeUp session or something

**Comment by Simn** [comment]
This is somewhat tricky because you could have something like this:

```haxe
		var a = try {
			[];
		} catch(e:Dynamic) {
			CallStack.exceptionStack();
		}
		trace(a);
```

This necessitates having `{ var r = CallStack.exceptionStack(); CallStack.lastException = null; r; }`.

Is there really no better solution for all of this...?

**Comment by nadako** [comment]
> Is there really no better solution for all of this...?

It would be much easier if we specified `CallStack.exceptionStack` to be a magic function that only works when called directly within the catch block, as @ncannasse said we could the simply access the caught exception. But I'm not sure how breaking it is, because it would mean that e.g. the following won't be possible anymore:

```haxe
function reportBadThings() {
    trace("Bad things happened at " + CallStack.exceptionStack());
}

try {
   doBadThings();
} catch (e:Any) {
   reportBadThings();
}
```

**Comment by Simn** [comment]
Can we just store the `Array<StackItem>` instead of the js.Error? There's no way this could have any measurable impact on the JS engines, even if you use exceptions in performance-critical code for whatever reason.

**Comment by nadako** [comment]
Meh, I don't think we want to run this code even if we're not using the stack information:

https://github.com/HaxeFoundation/haxe/blob/cdc317b14223b4b25022f218362d3fc5301d5f0e/std/haxe/CallStack.hx#L44-L69

**Comment by nadako** [comment]
(that and then this: https://github.com/HaxeFoundation/haxe/blob/cdc317b14223b4b25022f218362d3fc5301d5f0e/std/haxe/CallStack.hx#L327-L349)

**Comment by Simn** [comment]
Would it be acceptable to 4.1 this? I can't think of a good solution here.

**Comment by ncannasse** [comment]
I think it is acceptable to change the specification of exceptionStack() and say it might not work outside of a catch context, plus set lastException=null at the end of a catch.

**Comment by Simn** [comment]
Yes but "at the end of a catch" isn't trivial in the general case...

**Comment by nadako** [comment]
Note that #9124 alone doesn't fix the issue because using `CallStack.exceptionStack()` will still store the stack in a static var. However if the code is changed to use `haxe.Exception` (and its `stack` property) instead - the problem will be avoided.
