### ISSUE TITLE
Eager type-hint loading on class fields can lead to long completion times

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7018]
In a situation like this:

```haxe
class Main {
	static var foo:Foo;
	static public function main() {
		"foo";
	}
}
```

When requesting e.g. hover display on the `"foo"`:

```
haxe -v --display Main.hx@72@type
```

The compiler is going to load the `Foo` type before typing the `main` expression. This can lead to a lot of unnecessary typing, for instance if `Foo` has a build macro which isn't cached by the compilation server:

```
Parsed Main.hx
Parsed Foo.hx
Parsed C:\GitHub\haxe\std/StdTypes.hx
... lots of parsing and typing
Calling macro Macro.build (Foo.hx:1)
Macro.hx:3: build
Exiting macro Macro.build
Parsed C:\GitHub\haxe\std/EnumValue.hx
Parsed C:\GitHub\haxe\std/Enum.hx
Typing Main.main
<type p="c:\github\haxerepro\source\main.hx:4: characters 3-8">
String
</type>
```

Do you think we could lazify the loading of `Foo` here? Its type shouldn't be required until we actually access the field, right?

**Comment by ncannasse** [comment]
That's quite tricky. First it will create an additional indirection for every type loaded (hidden behind a TLazy), if we do that for every type we load I'm not sure what is the additional memory/cpu it will take.

Then it might start typing before all modules have been correctly loaded. I'm quite sure this will create some issue with macros etc.

I would prefer another way to deal with this. For instance, we already do expression optimization to prevent typing a lot of things when getting completion for a given method. We could also look at which member variables are required for correctly typing the expression in order to reduce extra loading.

**Comment by Simn** [comment]
To clarify, I only want to do this for the current display file, so I don't think memory/cpu concerns are warranted here. However, macros probably are.

I'm not sure a syntax-based exploration would work well here. We don't have the luxury of locality like we do for the current optimization, so any class field could be referenced from anywhere else...

**Comment by Simn** [comment]
I've tried adding this and use it where we normally load the type on var fields:

```ocaml
let lazy_display_type ctx f p =
	if ctx.is_display_file then begin
		let r = exc_protect ctx (fun r ->
			let t = f () in
			r := lazy_processing (fun () -> t);
			t
		) "" in
		TLazy r
	end else
		f ()
```

Testing completion in @jeremyfa's project.

Before:

![code_2018-05-17_11-37-22](https://user-images.githubusercontent.com/634365/40169901-60ee0668-59c7-11e8-865c-921d11b4987f.png)

After:

![code_2018-05-17_11-38-57](https://user-images.githubusercontent.com/634365/40169909-66122278-59c7-11e8-8266-1b477193bccd.png)

**Comment by Simn** [comment]
The solution I tried didn't work, and I don't have another approach. Closing due to lack of ideas.
