### ISSUE TITLE
Inline XML

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7035]
Implement Inline XML syntax to allow DSLs (with reentrency).
See https://github.com/HaxeFoundation/haxe-evolution/pull/26 [updated]

**Comment by kevinresol** [comment]
Related: https://github.com/HaxeFoundation/haxe-evolution/pull/26

**Comment by Simn** [comment]
Since we only need this as a TODO-item, I'm locking conversation in favor of HaxeFoundation/haxe-evolution#26 to avoid fragmentation.

**Comment by ncannasse** [comment]
@Simn what decision do you need from me ?

As for the default fallback when the XML is not handled by a custom macro parser, we should fallback on smart string parsing, so the following works:

```haxe
var count = 33;
var str : haxe.XmlString = <xml>$count + $count = ${count*2}</xml>
trace(str.toString());
```

haxe.XmlString would just be an abstract over String with a toString() (and maybe a @:to String as well) for API design purpose. It would anyway compile to:

```haxe
var count = 33;
var str = "<xml>"+count +" + "+ count +" = " + (count*2)+"</xml>";
trace(str);
```

**Comment by Simn** [comment]
I still don't have any idea what to actually do here. Do we add a full XML parser to the compiler or what?

**Comment by ncannasse** [comment]
It's quite well described in juraj haxe evolution proposal. The only change that I wish to make is to have xml validation and smart string handling for markup constants tha reach the typer. But this can even be done in a second step.

**Comment by Simn** [comment]
I still find it unacceptable to have a parser that can't handle `<tag arg="</tag>"></tag>`.

**Comment by ncannasse** [comment]
I understand, but it's a trade-off, and btw this is not even valid XML.

**Comment by Simn** [comment]
What exactly are we trading here though? If we have to walk through the tokens anyway, we might as well parse XML properly, even if we just return a string from that operation. I'd rather invest some more time and do it right.

**Comment by ncannasse** [comment]
@Simn the trade off is the following: either we ensure XML but then a lot of XML dialects such as JSX or other formats that enrich XML syntax will not be valid, or we allow much more than only XML by detecting only opening/closing tags

**Comment by ncannasse** [comment]
So doing only the minimal number of syntax checks (balanced opening/closing
tags) allows us to maximize the expressiveness of what can be put between
these tags

**Comment by Simn** [comment]
I've made a first messy implementation here: https://github.com/Simn/haxe/commit/6413f1e8f2d447c3a759752600794f485d345150

It's not architecturally obvious to me how to approach this: We need the parser to trigger a new lexer mode, which means it needs the lexbuf. I had to add a `code_ref` because of that which feels really dirty.

We can't do this during pre-processing because we only want to have this type of lexing if we're expecting an expression. Otherwise we would break `a<b` parsing.

I'm also just kind of hoping that none of the `Stream.npeek` cause the tokens to be consumed in the wrong lexer mode.

A limitation is that we currently only support tags that parse according to the identifier rules. If we want to support that `foo.Bar_barf3-gnieh:blargh` thing from the evolution example we're gonna have to consume tokens in the parser that are acceptable as tag name. That also means we need a regex in the lexer to pick up the closing tags.

Lastly, I tested this with exactly one string so it probably won't work anyway.

**Comment by frabbit** [comment]
@simn just wondering does this allow `<foo>${x < 1 ? "a" : "b"}</foo>`?

**Comment by Simn** [comment]
I'm not sure what you're asking. It doesn't use the `${ }` syntax to escape back to Haxe code. I don't think that was the idea either.

It certainly parses that correctly though.

**Comment by frabbit** [comment]
I was wondering about the `<` inside of the `${}`, because it doesn't have a corresponding closing tag.

**Comment by Simn** [comment]
That's no problem. The lexer doesn't care about a single `<` at all. It matches these patterns:

```
| '<','/',ident,'>'
| '<',ident
```

So what it would pick up is `a<b ? "a" : "b"`. In that case it would check that `<a` was not our opening tag, add it to the buffer and keep going.

**Comment by frabbit** [comment]
hmm, but this could be a problem?

`<foo>${x <foo ? "a" : "b"}</foo>`

**Comment by Simn** [comment]
Yes that wouldn't work.

**Comment by markknol** [comment]
So `<div><div>Hope</div></div>` also isn't going to work?

**Comment by frabbit** [comment]
@markknol i guess that should work because it's counting opening and closing tags, right @Simn? As long as you have normal xml it's fine (although i think `<br />` won't work). But the content of interpolations like in my example can cause problems.  And what about string contents like in `<foo>${"<foo"}</foo>`?

**Comment by frabbit** [comment]
it's hard to make it flexible and bulletproof at the same time.

**Comment by Simn** [comment]
The proposal doesn't aim for bulletproof.

**Comment by ncannasse** [comment]
Oh maybe we want <div some="attributes"/> to work, since the idea is to
allow any well formed XML to pass, but I wonder how that would be possible.

**Comment by ncannasse** [comment]
I guess this requires to detect all  `<TAG` ,  `/>` and `</TAG>`

**Comment by Simn** [comment]
That may or may not work now.

I'll probably just merge this and see. It shouldn't get in the way of anything else.

**Comment by Simn** [comment]
What's the idea behind this `XmlString` abstract? I agree that we can parse these strings like format strings, but I'm not sure about introducing a new type here.

**Comment by ncannasse** [comment]
The idea was not to mix "normal strings" and <xml>string</xml> , by making
the other behind an abstract. Allows for API to require one type of String
and not the other, giving a tip to the user to what kind of thing is
expected, but I'm not sure if it's a good idea or not.
