### ISSUE TITLE
Clarification about `final` on fields

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#7039]
I've heard a number of times that `final` makes fields immutable. This is [not at all the case](http://try-haxe.mrcdk.com/#c6Bd9): 

```haxe
var o = { foo: 4 }
var o2:{ final foo:Int; } = o;
trace(o2.foo);//4
o.foo = 5;
trace(o2.foo);//5 - not very "final", is it?
```

Is this a type hole, or is it intentional?

**Comment by Simn** [comment]
We have always allowed assigning to `(default, never)` like this, and given that `final` is just a shortcut for that, it's only consistent.

Now, whether or not that's a good idea is another question.

**Comment by back2dos** [comment]
Well, if this is the final behavior (tadaaa), then I would point out that we still don't have a way to express immutable fields in Haxe. I'll spare you the usual rant ;)

**Comment by ncannasse** [comment]
I think things are quite clear here. You have an object of type { foo : Int } which is mutable. You can "const-ify" it by passing it to something restricting its mutation, but that does not change the fact that the original object can still be changed.

**Comment by Simn** [comment]
After talking with @back2dos again, I think this kind of "accessor variance" should not be allowed. A `final` field should really be final, which is also something an optimizer might use. IMO we should get this right for Haxe 4, and we can probably do so without touching the `(default, never)` semantics.

**Comment by ncannasse** [comment]
I'm not sure I understand the logic here. "final" is a constraint, and constraints in Haxe (public/private/type constraints/etc.) have variance. Why not letting variance on final as well?

**Comment by back2dos** [comment]
I think this is what `final` should mean:

```haxe
var o2:{ final foo:Int } = ANYTHING;
var foo = o2.foo;
Thread.create(function () {
  while (true) assert(foo == o.foo2);//this assertion ALWAYS holds
});
```

Or maybe final should not mean that, but then something else should exist in the language to express the fact that a field will NEVER change.

**Comment by Simn** [comment]
I don't think you can compare these other constraints to `final` because there is no way to violate them. There is no write-access if you will, whereas with `final` you can violate the constraint from the outside by writing to the non-final version of it. This means that we should have invariance here.

Semantically, if you see a `final` field, you expect it to retain the same value between two accesses. That is, `obj.finalField == obj.finalField` should always hold, no matter what's in between the two access operations.  While visibility and access modifiers only determine what _you_ can do with a field, `final` should be stronger and make the promise that _nobody_ can modify the field.
