### ISSUE TITLE
[display] improve workspace symbols performance

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7056]
One of the reasons why workspace symbols don't feel that responsive is probably the sheer amount of stuff it reports.. I don't think you really care about locals + function params at that level - it should be fine to only have them for document symbols. Especially if that means a performance boost.

I mean, seriously, "ignored" local vars too? :D

![](https://i.imgur.com/JqOE41H.png)

Another thing I've noticed in TypeScript's workspace symbols is that they only start returning results after you type at least a single character, while for Haxe is starts searching right away and usually hangs for a split-second because of that. That's probably something to implement on the vshaxe side though.

**Comment by kLabz** [comment]
> Another thing I've noticed in TypeScript's workspace symbols is that they only start returning results after you type at least a single character, while for Haxe is starts searching right away and usually hangs for a split-second because of that. That's probably something to implement on the vshaxe side though.

I'm not convinced by that part :thinking: 

I've disabled that behavior locally (removed https://github.com/HaxeFoundation/haxe/commit/ac2c5f009fec33339306f72cfbb73862ded099c3#diff-106d4296b9b6f4da4b6e1264b40faf39e98ce933e5512a6e4ec1d2467f36d229R620) to be able to do a filter-less `workspace/symbol` query on vim and throw the result at telescope to be able to fuzzy search on it, and it's pretty responsive:

![Recording 2023-01-05 at 11 22 12](https://user-images.githubusercontent.com/6101998/210757668-7f056ff9-49cc-4793-8b40-237d26f76659.gif)
_(request is sent when yellow cursor disappears, and total delay includes parsing the whole json)_

Edit:
Admittedly, vscode is slower but that's partly because it seems to be debouncing there:
![Recording 2023-01-05 at 11 29 57](https://user-images.githubusercontent.com/6101998/210759572-e4e7d312-8839-4ba8-a8cd-4c22c665bc5e.gif)

But yeah, for typescript it does nothing until at least one character is typed. Not sure it's a good reason for us to prevent other tools from working with worspace-wide symbols, though.
