### ISSUE TITLE
Conditional compilation issue

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#7108]
Have not been able to make a general and succint example out of this, but it was reproducing in my code base and this snippet (http://try-haxe.mrcdk.com/#e66Ed) seems to _somehow_ reproduce the issue (although not faithfully):

```haxe
class Test {
  static function main() {
    trace("Haxe is great!");
    #if js
      trace('x');
    #elif js
      trace('elif');
    #else
      trace('end');
    #end
  }
}
```

Maybe "elif" was allowed some time ago and has not been supported in latest versions?

**Comment by azrafe7** [comment]
haxe 4.0.0 preview

As always sorry if I'm misunderstanding something.

**Comment by azrafe7** [comment]
PS: from google searches it seems that #elif was never supported, but somehow gets through the parser anyhow.

**Comment by Simn** [comment]
It's a valid token as far as the lexer is concerned. All tokens are skipped in inactive branches, so this never comes up as a problem.

Maybe we should indeed error on invalid `#`-tokens in these cases.

**Comment by EricBishton** [comment]
You mean: "It's a valid token as any space-delimited set of characters is a [skipped] token in inactive compilation branches," right?  It would be nice if inactive CC branches did spit out syntax errors, but then you couldn't #if 0 ... { invalid, half written, code } #endif' any more just to get a test compile.  Well.. actually, you could detect '0' as a special circumstance...

@azrafe7 '#elseif'  is the token that denotes a second branch for conditional compilation.

@Simn - If you're going to think about creating an error when you see '#unrecognized' in a source file, 
 I'd love to see `#error "message"` be a recognized sequence so that you could do something like:
```haxe
hxcpp_debugger.hx

  #if !hxcpp
  #error "hxcpp debugging can only be used in C++ targets."
  #endif
```
And that would stop the compiler with an error message:
```
  hxcpp_debugger.hx: 2: lines 2-2: hxcpp debugging can only be used in C++ targets.
``` 
(or whatever the 4.0 error message format will be.)

**Comment by Simn** [comment]
> You mean: "It's a valid token as any space-delimited set of characters is a [skipped] token in inactive compilation branches," right?

That's not true, we still lex normally in inactive branches. The lexer dies on `#if false £ #end` or any other unrecognized character.

> I'd love to see #error "message" be a recognized sequence

`#error "message"` has been around for a long time.

**Comment by EricBishton** [comment]
> #error "message" has been around for a long time.
My bad.  Not sure why I thought it wasn't.

**Comment by Simn** [comment]
Probably because it's not properly documented.

**Comment by azrafe7** [comment]
Thanks @EricBishton (figure that out just after posting).

@Simn, yes, why not error out in this cases? (I see you only added the documentation label)
