### ISSUE TITLE
Generic types ignores operator overloading for Abstracts. 

### ISSUE THREAD

**Issue by dmitryhryppa** [HaxeFoundation/haxe#7124]
Hello!
Check this, please: 
https://try.haxe.org/#231E2

The question is why compiler ignoring operator overloading for MyInt in that case? 
By `@:generic` metadata we said to compiler to generate `testCompare` function directly for MyInt type, so... 
Is this a bug or this is by design?

Thanks ;)

**Comment by Simn** [comment]
`@:generic` never re-types, which means any operation that occurs during typing (macros, operator overloads etc.) are applied to the generic version, not the applied one.

However, your example wouldn't work anyway because `testCompare.T` is inferred to `MyInt`, and `b:Int` is then assigned to it through the `from Int`. That means the `a == b` would be `MyInt == MyInt` and no operator overloading would occur.

**Comment by dmitryhryppa** [comment]
Got it. Thank you.
