### ISSUE TITLE
[cpp] Interfaces passed to the function as Dynamic

### ISSUE THREAD

**Issue by dmitryhryppa** [HaxeFoundation/haxe#7128]
Hello,
I found that classes which was implemented by interfaces is passes to the functions as a Dynamic objects,
which do casting and which is two times slower then using of plain objects.

Here is code sample:
```
package;
import haxe.Timer;

interface IObject {
    public function test():Void;
}

class Object implements IObject {
    public function new() {

    }

    public function test():Void {
        
    }
}

class App {
    static var iterCount:Int = 99999999;
    public static function main():Void {
        Timer.measure(() -> testFunc1(new Object()));
        Timer.measure(() -> testFunc2(new Object()));
    }

    private static function testFunc1(obj:IObject):Void {
        for (i in 0...iterCount) {
            obj.test();
        }
    }

    private static function testFunc2(obj:Object):Void {
        for (i in 0...iterCount) {
            obj.test();
        }
    }
}
```

Here is screenshot:
![Image](https://i.imgur.com/hhkTzpz.png)

So, IObject is generated as:
```
class HXCPP_CLASS_ATTRIBUTES IObject_obj {
	public:
		typedef hx::Object super;
		HX_DO_INTERFACE_RTTI;

		void (hx::Object :: *_hx_test)(); 
		static inline void test( ::Dynamic _hx_) {
			(_hx_.mPtr->*( static_cast< ::IObject_obj *>(_hx_.mPtr->_hx_getInterface(0x2572cfe8)))->_hx_test)();
		}
};
```

But can we remove unnecessary casting by generating interfaces with something as below and pass them to the function as `IObject` and not as `Dynamic`?
```
class HXCPP_CLASS_ATTRIBUTES IObject_obj {
	public:
                ( .... )
                virtual void test() = 0;
};
```

That's a problem, becaus in general it provoke a lot of unnecessary casting in whole codebase.
Also current implementation can't be used directly in C++ as interface of external lib.

Thank you :)

**Comment by dmitryhryppa** [comment]
I've reversing the order of the tests as Hugh advised. 
And I still have 2 times difference:
```
App.hx:25: 0.151098904508816s
App.hx:26: 0.298462700424245s
```

MSVC 2017

**Comment by Simn** [comment]
I'm not sure how much we could gain here. Interfaces do require dynamic resolution to an extent because you can't know any field offsets. I'm not surprised to see a x2 difference anyway, but I've assigned Hugh to comment.

**Comment by hughsando** [comment]
2x difference is about what I would expect.
There is no actual "casting" going on here (static_cast is free), but there are 2 function calls - one to get the function pointer and then 1 to run it, rather than  just 1 to run it.
It might be possible to cache one of these calls if you were to make multiple interface calls, but that is not the case here.  JIT languages can do some interesting things here, but i am not clever enough for that.

From a low-level point of view, class access knows the exact byte-offsets for all the fields, but interface access does not, so it needs extra logic to get there.  Native c++ uses an extra jump table to do quite cheap jumps, but this requires pointers offsets, which messes with my GC implementation.  And haxe allows widening of parameter types which complicates things again.  In short, this is quite tricky and I would not want to change things without some implementation demo.

**Comment by ncannasse** [comment]
Works as intended.
Note: you can use @:generic to create type-specific version of the function optimized for a specific class instance.
