### ISSUE TITLE
[cache] GIT stack does not update cache

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7203]
Found when working on Northgard: I did a git stash on Heaps in order to tmp revert some changes. When switching back to VSCode I am getting compilation errors related to previous code.

File modified was  h3d.mat.MaterialSetup, project was successfully compiled before git stash, but the file referencing material setup was modified by hand.

**Comment by Gama11** [comment]
We turned off the changed module checks in order to avoid the crazy overhead that was causing for every single request (especially toplevel), but that means only files edited within VSCode will trigger invalidation, since we rely on file change events from the language server now.

With VSCode's file watcher API, it's probably possible to extend that to ".hx files located within the workspace that changed", rather than just "files edited in VSCode". However, not noticing changes to files outside of the workspace is probably going to remain a known limitation for a while, although we could have a setting to opt out of this and let Haxe do the (slow) checks again.

**Comment by Simn** [comment]
This is probably more of a vshaxe issue. Although I still wonder if we need an option to invalidate directories instead of files. Adding/deleting files has different semantics than modifying them.

**Comment by ncannasse** [comment]
Can't we enable it by default for compilation at least ?

**Comment by Gama11** [comment]
That might make sense, for compilation the overhead would be much less severe / noticable, relatively speaking. For display requests though, it's not acceptable to wait that long.

**Comment by ncannasse** [comment]
Looks good to me :) when is the next update ? :D

**Comment by Simn** [comment]
Good idea (I think). Try adding `&& ctx.com.display.dms_kind <> DMNone` to the guard in `has_policy` in server.ml.

**Comment by ncannasse** [comment]
Looks ok from what I tried, closing for now will reopen if necessary.
