### ISSUE TITLE
Inline produces monomorphs

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7206]
The following code:

```haxe

class Main {

	inline static function getIndex(i:Int) : Float {
		switch( i ) {
		case 0: return 1.23;
		case 5: return 2.45;
		default: return 0.;
		}
	}

    static function main() {
		var x = 0.;
		for( i in 0...10 )
			x += getIndex(i);
		trace(x);
	}
	
}
```

Produces the following AST:

```
[Var x1(8557):Unknown<2>]
[Switch:Void]
	[Parenthesis:Int] [Local i(3685):Int:Int]
	[Case:Unknown<2>]
		[Const:Int] 0
		[Binop:Unknown<2>]
			[Local x1(8557):Unknown<2>:Unknown<2>]
			=
			[Const:Float] 1.23
	[Case:Unknown<2>]
		[Const:Int] 5
		[Binop:Unknown<2>]
			[Local x1(8557):Unknown<2>:Unknown<2>]
			=
			[Const:Float] 2.45
	[Default:Unknown<2>]
		[Binop:Unknown<2>]
			[Local x1(8557):Unknown<2>:Unknown<2>]
			=
			[Const:Float] 0.
```

Leading to `x1` becoming Dynamic (instead of Float) on static targets runtime.
I think this might be a regression wrt recent inline changes.

**Comment by Simn** [comment]
Not a regression, but should still be fixed of course.

**Comment by Simn** [comment]
The core problem here is that switches in `NoValue` situations aren't typed as `Void` but as a monomorph. This has been the case since before I wrote the original pattern matcher.

Changing this unfortunately comes with some problems when inlining. In order to support `Context.getTypedExpr`, we're wrapping the `TSwitch` node in a `TMeta @:ast` node in order to preserve the original syntax. This is necessary because there's no syntactic equivalent of `TEnumParameter`. However, when the inliner rewrites the `TSwitch` type from `Void` to something else, the `TMeta` remains unaffected and ends up causing "Cannot use Void as value` errors.

I'll hack this for now in the inline algorithm, but in general I'd prefer if we could lose `Context.getTypedExpr` and its entourage.
