### ISSUE TITLE
Cannot modify the abstract value, store it into a local first(haxe 4 dev)

### ISSUE THREAD

**Issue by djaonourside** [HaxeFoundation/haxe#7286]
http://try-haxe.mrcdk.com/#03710
It compiles ok with haxe 3 and haxe 4 preview 1. After haxe 4 preview 4 I've got the error:
`Cannot modify the abstract value, store it into a local first`

**Comment by Simn** [comment]
This is pretty messy. I thought we typed this wrongly because `this` inside an abstract refers to the underlying type as opposed to the abstract itself. However, if we do that, we're losing information about type parameters when inlining.

The actual problem here is that we insert a `cast` to keep the typing right, and thus end up with `cast this = value`, which is rejected.

**Comment by Simn** [comment]
```haxe
class Main {
	static function main() { }
}

abstract TestMap(Dynamic) {
	public function new() {
		fromObj();
	}

	inline function fromObj() {
		this = { };
	}
}
```
