### ISSUE TITLE
Dates outside of int32 range

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#7303]
I'm guessing that it's a safe uint32
```
NekoVM 2.1.0 (c)2005-2016 Haxe Foundation
Haxe Compiler 4.0.0-preview.4+6fd053615 - (C)2005-2018 Haxe Foundation
```
```haxe
class Main {
	static function main() {
		var t = new Date(1970, 0, 1, 2, 0, 0);
		trace(t, t.getTime());
		t = new Date(1970, 0, 1, 1, 59, 59);
	}
}
```
```
src/Main.hx:4: 1970-01-01 02:00:00, 0
Called from ? line 1
Called from Main.hx line 5
Called from ...\haxe\std/neko/_std/Date.hx line 24
Called from ...\haxe\std/neko/_std/Date.hx line 30
Uncaught exception - std@date_set_hour
```
Edit: I suppose the timestamp is on GMT so the earliest safe-to-create time is noon rather than midnight like it commonly is.

**Comment by Simn** [comment]
I don't think we will look into this given that it's a neko-specific issue, but I'll let @ncannasse decide on that.

**Comment by R32** [comment]
same on hashlink, the date is limited to 1970~2038.

**Comment by ncannasse** [comment]
Yes, we use the standard C API for dates, which is bounded to these dates. HashLink, HxCPP (and Eval?) might also be affected.  I don't think we will fix it for neko, but we might look into supporting more wide Date ranges.

Looking at https://en.wikipedia.org/wiki/Year_2038_problem, it seems that we could use an int64 on 64 bit systems without much issue.

Also, we could allow < 0 times to support the 1902...1970 range on 32 bits systems as well (if possible).

Fun fact :  in JS you can't create a date between Year 0 and 99 AD  as `new Date(1940,0,1)` and `new Date(40,0,1)` returns the same value.

Anyway, we will need more unit tests for this.

**Comment by YellowAfterlife** [comment]
It's expected that the date starts at 1970 but it is not expected to get an exception on reportedly-minimum value because of timezones. Should at least mention this in the doc - if I was in GMT <= 0 timezone, I wouldn't even notice until users would start reporting errors.

**Comment by Simn** [comment]
I have to do something on eval here because it gives a `Unix_error` at the moment. What do we want to do with this?

**Comment by thomasjwebb** [comment]
In my experience (see the issue referenced above), hl says invalid date for dates before 1970, which I find odd because I think it's more common for time_t to be signed int, which would mean a range of 1902-2038. If it was unsigned, then it would make sense you couldn't go before 1970 but would also mean that you could go until 2106. The c standard doesn't define the underlying type but time_t should be 64-bit on 64-bit systems.

But the fact that it's not invalid, but simply miscalculated for dates prior to 1970 for the cpp target (also as you can see on the related issue above) makes me think that it's just doing the math wrong or something. Just glancing at Date.cpp, it looks like it's already using 64-bit.

**Comment by ncannasse** [comment]
I have slightly improved HL support to have the whole 32 bits support (1970-2106). However sending negative numbers ( before 1970 ) to `localtime` trigger an error, so even with 64 bits we wouldn't be able to easily support dates < 1970

**Comment by Simn** [comment]
This kills hxcpp too. Are we gonna specify that dates < 1970 might not work on some targets? I suppose we still want it to raise a proper exception in that case.

**Comment by ncannasse** [comment]
I think atm the best is to specify that only dates in the [1970,2106[ range might be supported by the platform. + we need to test for >2038 in order to ensure that we don't overflow the way it was on HL before my fix here https://github.com/HaxeFoundation/hashlink/commit/563ee0afd0f84835f9c3d3a6c2340aea4fc9d8cc

**Comment by ncannasse** [comment]
Not 4.0 priority

**Comment by Simn** [comment]
I want to at least fix the native OCaml exception.
