### ISSUE TITLE
Generic type parameter defaults

### ISSUE THREAD

**Issue by benmerckx** [HaxeFoundation/haxe#7304]
I actually think I saw this elsewhere before so it could a duplicate, but I can't find the issue (if there is one). The concept is simple - at least in syntax, probably not the implementation part :)

````haxe
class Test<T = {}> {
  public function new() {}
}
var a = new Test();
$type(a); // Test<{}>
````

There's similar syntax in [flow](https://flow.org/en/docs/types/generics/#toc-adding-defaults-to-parameterized-generics) and [typescript](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#generic-parameter-defaults).

Note: this is possible to emulate with `@:genericBuild` but those blow up if you them in macro context...

**Comment by Gama11** [comment]
@Simn once asked me to outline how this would look like, this was the result:

https://gist.github.com/Gama11/dd46e8d8d5430eec1817e7b3dbe87b36

>Note: this is possible to emulate with `@:genericBuild` but those blow up if you them in macro context

Sort of, but not really... The problem is that there's no way to make the type parameter optional in type hints with `@:genericBuild`, so you can't declare `var foo:SomeType;` as a member variable when `SomeType` has a type parameter. See also: https://github.com/HaxeFlixel/flixel/issues/1677#issuecomment-166310680

___

Either way, I guses this would most likely require a haxe-evolution proposal.

**Comment by benmerckx** [comment]
I didn't know it was possible to have the type inferred when constructing it directly. I was running into this with `class ... extends Test {}`. I looked up haxe react to see how it handled a similar situation, but it just shows how useful this could be: https://github.com/massiveinteractive/haxe-react/blob/19156680859ac0e27249762101cb8533b911a141/src/lib/react/ReactComponent.hx#L14
I'll try to put this into a proposal.

**Comment by Gama11** [comment]
>I didn't know it was possible to have the type inferred when constructing it directly.

Hm? Do you mean this line in the "current situation" section of the Gist?

```haxe
var foo = new Foo(); // works, T is inferred based on first usage
```

**Comment by benmerckx** [comment]
Exactly. Running into `missing type parameter` a few times my mind somehow concluded only Map and Array type parameters are inferred because of compiler magic. The remark wasn't that relevant to the proposal, just stating something new I (maybe re-)learned :)

**Comment by Simn** [comment]
This would have to go through https://github.com/HaxeFoundation/haxe-evolution
