### ISSUE TITLE
[display] pattern variable missing from completion with empty case

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7327]
This is an interesting one.. I first though it might be a regression from https://github.com/HaxeFoundation/haxe/commit/f41be5bd663fd0a4ba37fe71072cb0b473b55824, but it doesn't seem like a regression at all (even compared to 3.4.7) - `v` is simply missing from completion here:

![](https://i.imgur.com/zVRBQWc.png)

This is only an issue if the case body is empty, it works with a trace:

![](https://i.imgur.com/RbpHN1J.png)

---

```haxe
package cases;

class Issue7327 extends DisplayTestCase {
	/**
	import haxe.ds.Option;

	class Main {
	    public static function main() {
	        var o:Option<Int> = None;
	        switch (o) {
	            case Some(v): {-1-}
	            case None:
	        }
	    }
	}
	**/
	function test() {
		eq(true, hasToplevel(toplevel(pos(1)), "local", "v", "Int"));
	}
}
```

**Comment by Simn** [comment]
This one is pretty annoying because there's a big "hole" in the AST position-wise, which causes the display preprocessor to not figure out that the display position is within the `case`.

I think this also causes some weirdness with positions when debugging. There might even be an open issue about that.
