### ISSUE TITLE
Stored TypedExpr not replaced in cases

### ISSUE THREAD

**Issue by elnabo** [HaxeFoundation/haxe#7359]
If I build a switch using macro where the case expression comes from `Context.storeTypedExpr` the compilation will fail with `Unrecognized pattern: @:storedTypedExpr 1`. Doing the same with `Context.getTypedExpr` works as expected.

Happen in both 3.4.4 and latest build.

Minimal example :  http://try-haxe.mrcdk.com/#C49Ac
```haxe
import haxe.macro.Context;
import haxe.macro.Expr;

class Test {
  static function main() {
        m(11);
  }
  static macro function m(e) {
        var stored = haxe.macro.Context.storeTypedExpr(haxe.macro.Context.typeExpr(e));
    	var got = haxe.macro.Context.getTypedExpr(haxe.macro.Context.typeExpr(e));
    
    	// When using storedTypedExpr switch is invalid
    	var c = {expr:macro trace("yes"), guard:null, values:[stored]};
    	// When using getTypedExpr switch is valid
    	//var c = {expr:macro trace("yes"), guard:null, values:[got]};
    
    	var s = {expr:ESwitch(macro 1, [c], macro trace("no")), pos:Context.currentPos()};
    	//var s = macro trace($stored);
    	return s;
    }
}
```

**Comment by Simn** [comment]
Pattern matching and stored expressions don't mix well because patterns are entirely based on AST-level expressions. The best we can do here is to convert the typed expression to an untyped one, which basically turns `storeTypedExpr` into `getTypedExpr`.

In theory I could add a more restricted converter for this, but I doubt that would make any difference in practice.

**Comment by elnabo** [comment]
Thanks for the fast fix.

And yeah the type is not such an important information in this case.
