### ISSUE TITLE
New function type: invalid parsing of a function returning another function

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7373]
```haxe
class Test {
    static function main() {
      var fn:(i:Int)->(i1:Int, i2:Int)->Void = i -> { //Test.hx:3: characters 26-27 : Unexpected :
        trace(i);
        return (i1, i2) -> {
          trace(i1, i2);
        }
      }
      fn(1)(2, 3);
    }
}
```
Latest dev Haxe.
http://try-haxe.mrcdk.com/#b2151

**Comment by Simn** [comment]
@nadako: Was this one of the restrictions due to us still supporting the old syntax?

**Comment by nadako** [comment]
Probably, yeah.

Even if there was no restriction, it's a good idea to at least add parentheses in code like this.

**Comment by Simn** [comment]
Agreed, I don't think we can support this until we drop the old syntax.

**Comment by back2dos** [comment]
Yes parens would be great (I had to look at the value to decipher what is meant), but I don't get why this doesn't parse. Added the new function type syntax to hscript and it parses just fine: https://github.com/back2dos/hscript/commit/a423ca9e576119f33bfbcbb5d49aff77aa91a23d#diff-c8c04dd1a23f6387728711c5dce61f28R110

Perhaps there's something I'm not getting, but there shouldn't be an error at the position where it is now, because after the first `->` we know that next up is a ComplexType and that therefore a function (new style or old) must be allowed.

**Comment by Simn** [comment]
I think the problem is that it should still support `(i:Int) -> (i1:Int) -> Void`.

**Comment by back2dos** [comment]
Well, for starters `(i:Int) -> (i1:Int) -> Void` doesn't  currently parse, for the same reason that `(i:Int)->(i1:Int, i2:Int)->Void` won't: parser rejects the second `:` either way (I don't see why one would work and the other one wouldn't).

Something is definitely fish here. The [evolution proposal](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0003-new-function-type.md) says "If the desired behaviour is to have a functional return type, parenthesis should be used:". But I don't actually understand why that must be and even so why the parse error is the one we're getting.
