### ISSUE TITLE
final inference and operator overloading

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7394]
I thought the error on the comparison here was about implicit casts / the same as #7391, but this still errors:

```haxe
class Main {
	public static function main() {
		var b:Bar = {i: 0};
		trace(b > {i: 1});
	}
}

typedef Foo = {
	final i:Int;
}

@:forward abstract Bar(Foo) from Foo {
	@:op(A > B) function compare(other:Bar)
		return this.i > other.i;
}
```

```
source/Main.hx:4: characters 9-19 : Cannot compare Bar and { i : Int }
```

Works fine if `i` is a `var` instead of `final`.

**Comment by Simn** [comment]
I don't know if I can fix this. We don't usually apply top-down inference to the rhs in case of comparison operators...

**Comment by Simn** [comment]
Ok, let's think about this. We disallowed "final variance" which mean that we can no longer assign a final field to a non-final field or vice-versa. The situation we have here is a bit different because we do not have an actual assignment, but a comparison operator. While we still have to unify, there would be no harm in allowing final variance.

The problem is that we don't distinguish these cases internally: unification is unification. The other problem is that we do not use top-down inference. I wonder if we should top-down infer the rhs of comparison operators, either in general or for structures in particular.

@ncannasse: Any opinions on the matter?

**Comment by ncannasse** [comment]
The more I look at it the more I feel that final variance was a bad idea... It forces to split unify into two kind of unification : "value passing" unification, in which case if unified the target value might be modifiable (passing as argument, return value, assignment, etc.) --- which is what we want to forbid for final. VS "type checking" unification, in which we compare the type but the value will not "escape" (comparison, but not only ?)

**Comment by Simn** [comment]
Most of our unification occurs for real assignments. I can't even think of any other unification between two structure types that could trigger this. The case in this issue is very special: You have to use an abstract over a final structure in order to create a `>` unification.

Regardless, my question stands: Shouldn't we top-down infer for comparison operators? It seems wrong to do it for `==` and `!=` but not for `>` and friends. From a typing point of view this should be the same, right?

**Comment by ncannasse** [comment]
I agree we should unify our comparison operators typing.

**Comment by Simn** [comment]
Done! I would really like to keep this `final` behavior because I think it makes the language stronger. I know it's possible to construct cases where it's a bit annoying, but even then the worst case is probably that you have to add a `cast` somewhere. So unless we come across something unexpected, let's try to go with this for Haxe 4.
