### ISSUE TITLE
[cs] null value returned by generic function with return type Null<Int> is converted to 0

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#7428]
The following code prints/returns `null` for all platforms except C# where the `null` value is converted automatically into an Int `0`.

```haxe
class Test {

    public static function main() {
        trace(Std.string(getIntOrNull()));
    }

    public static function getIntOrNull():Null<Int> {
        return execute(function():Null<Int> {
            return null;
        });
    }

    public static function execute<T>(callback:Void->T):T {
        var result = callback();
        return result;
    }
}
```

I tested with Haxe 3.4 and Haxe 4 nightly.

**Comment by aartzrc** [comment]
I have a similar quirk when using a generic function, here is a sample:
```haxe
class MainIntNull  {
    static function main() {
        var intA:Array<Int> = [0,1,0,1,2];
        trace(unique(intA));
    }

    public static function unique<T>(a:Array<T>):Array<T> {
        var res:Array<T> = [];

        for(i in a)
            if(null != i && res.indexOf(i) == -1)
                res.push(i);

        return res;
    }
}
```
The idea is to return only unique and not-null values. It works in js and neko, but cs fails due to this comparison:
```cs
global::haxe.lang.Runtime.eq(default(T), i))
```
`default(T)` becomes zero, which causes the value of zero to be considered null.

For my case, if there was a way to detect not-nullable types on a static target I could remove the null check.

**Comment by RealyUniqueName** [comment]
This one is risky to change (just like anything else type related in gencs). I've made some progress, but it affects type casting which usually breaks some nasty edge cases in C# target.

**Comment by sebthom** [comment]
Still the case for Haxe 4.0.5 and 4.1.0-nightly.
