### ISSUE TITLE
cannot catch Context.typeof when typing a macro generated expression

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#7466]
The following code triggers a correct but not catchable error `String should be Int`:

See: https://tryhaxe.frabbit.de/#92Da8

Test.hx
```haxe
class Test {
  static function main() {
    trace(Macro.canType( Macro.getCheckType() ));
  }
}
```
Macro.hx
```haxe
import haxe.macro.Expr;
import haxe.macro.Context as C;

class Macro {
  macro public static function canType (e:Expr) {
    return try {
    	C.typeof(e);
    	macro true;
    } 
    catch (e:Dynamic) {
      trace("CATCHED:" + e);
      macro false;
    }
  }
  
  macro public static function getCheckType () {
    return macro ({ name : "foo" } : { var name : Int; });
  }
}
```

**Comment by Simn** [comment]
"CATCHED" :D

**Comment by Simn** [comment]
The problem occurs because we turn `Error` into `Fatal_error` here: 

https://github.com/HaxeFoundation/haxe/blob/f912a38afeffca0f2bc4f64e9c30178f8ad1555f/src/typing/calls.ml#L605-L608

I went on a blame-expedition to find the commit that added this:

https://github.com/HaxeFoundation/haxe/commit/8fbad3662d3664803dad34300d6df5cf98ae8264#diff-eb918bc546b40568ecadf7d9546c3119R2394

Linked issue: #953

I don't know why this would have to be turned into a fatal error, so I'm inclined to change that and see if anything breaks.

On a related note, the linked Haxe source misses non-`Error` exceptions and doesn't reset state properly.
