### ISSUE TITLE
Allow macros to be in .macro.hx module.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#7488]
To not further hijack #7453 I wanted to ask if we could allow macros implementations to be declared in `.macro.hx` modules. It works with `.eval.hx`, but that has it's own issues:

> the `.eval.hx` file is also used if your target platform is eval (for `--run`/`--interp`), which means the separation fails.

**Comment by Simn** [comment]
I'll take the opportunity to review all our usages of `platform_name` and use `macro` where sensible.

**Comment by Simn** [comment]
* codegen.ml: This is for where to create dump files. Might be useful to change.
* castDetect.ml: Uses the platform name to check some type paths like platform.Int64. Probably irrelevant, but should stay `eval` because that's where the standard library is.
* main.ml: `-cmd` adds the platform name as a `__platform__` env var. No idea, let's keep it I guess.
* server.ml: Sends the name to `find_directories` which filters directory names using it. Should stay `eval`.
* common.ml:
  * Adds platform name as a `-D`. Should stay `eval` because we define `macro` separately.
  * Deals with the platform name as part of the package rules. Should not change.
  * `find_file` uses the platform name to look up specialized platform files. This is what we want to change here.
* compilationServer.ml: Stores platform name for debugging. Irrelevant
* completionItem.ml: Outputs platform name as part of metadata help. Should not change.
* analyzer.ml: See codegen.ml
* macroContext.ml: Updates compiler defines by removing platform name from the list for the macro context.
* typeloadParse.ml: Uses the platform name for forbidden package errors. Already uses `macro` when in a macro.
