### ISSUE TITLE
return return return 

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#7490]
I noticed in all Haxe version you can do multiple `return` keywords:
```haxe
class Test {
  static function main() {
    return return return 1;
  }
}
```
http://try-haxe.mrcdk.com/#B0191

**Comment by Simn** [comment]
That's a consequence of "everything is an expression". We allow return as a value because you can do `var x = x == null ? "foo" : return` and similar things. It's cleaned up properly before generation, so there's no problem here.

**Comment by nadako** [comment]
I believe it was already discussed before and it's the consequence of "everything is an expression", because `return` is an expression with an unknown type, so you can things like do `var a = if (...) 1 else return;`.

While in a simple example like this it looks quite stupid, it's not really easy to enforce, because things like this can be coming from macros and not break any logic. Also you might want to do an early return from a block that is a value of another return or something, so let's leave it as is.

**Comment by markknol** [comment]
Thanks for explanation!
