### ISSUE TITLE
[eval] unused var in __init__ crashes --interp

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7499]
```haxe
class Main {
	static function __init__() {
		var s:String;
	}

	public static function main () {}
}
```
```
$ OCAMLRUNPARAM=b haxe -main Main --interp
Fatal error: exception File "_build/src/macro/eval/evalJitContext.ml", line 84, characters 9-15: Assertion failed
Raised at file "_build/src/macro/eval/evalJitContext.ml", line 84, characters 9-21
Called from file "_build/src/macro/eval/evalJitContext.ml", line 104, characters 12-31
Called from file "_build/src/macro/eval/evalJit.ml", line 182, characters 15-36
Called from file "_build/src/macro/eval/evalJit.ml", line 574, characters 9-15
Called from file "_build/src/macro/eval/evalJit.ml", line 574, characters 9-15
Called from file "_build/src/macro/eval/evalJit.ml", line 634, characters 9-40
Called from file "_build/src/macro/eval/evalPrototype.ml", line 34, characters 14-28
<...>
```
This is a recent regression. It didn't crash a few weeks ago.

**Comment by Simn** [comment]
I know why this happens, but I don't know why it would be a regression...

**Comment by RealyUniqueName** [comment]
Because it used to work without a crash )
I caught it here: 
https://github.com/RealyUniqueName/Safety/blob/fbf95a3d3de302cc01b817d483319e8f4e3cd790/test/cases/TestCompileTime.hx#L94-L97
`shouldFail(s.length)` is a macro which emits `s.length`

**Comment by Simn** [comment]
That's probably a different case.

But anyway, I'll fix them both.

**Comment by Simn** [comment]
I see now. I thought the problem was that the compiler emits the `__init__` function's expression without a TBlock, but it turns out that eval already adds one.

The actual problem was that I had a single-element-block "optimization" that wasn't pushing a variable scope, so the JIT context didn't know where to register the variable. I didn't catch that because it's very unusual to have a block whose only element is a variable declaration.

**Comment by Simn** [comment]
@hughsando: This kills cppia too. I have `#if`ed out the test for now.
