### ISSUE TITLE
[analyzer] unnecessary tmp vars generated for php

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7500]
```haxe
class Main {
	var field = 0;

	function test() field += 10;

	static function main() {}
}
```
```
$ haxe -main Main -php bin -D analyzer-optimize
```
```php
public function test () {
	$tmp = $this;
	$tmp->field = $tmp->field + 10;
}
```
This is the lates development.

**Comment by Simn** [comment]
That happens because of this:

https://github.com/HaxeFoundation/haxe/blob/4669a2754d6783827eaa79e7da7d21c3f18a9939/src/optimization/analyzerTexpr.ml#L108-L111

I suppose we have to make the check more elaborate and see if the rhs actually has a side-effect (or could be affected by one? Not sure...)
