### ISSUE TITLE
`String.iterator()` and `String.keyValueIterator()` 

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7502]
I'll start a PR for `String.iterator()` and `String.keyValueIterator()` in the nearest days.
So if anyone is already working on this task, let me know.

**Comment by fullofcaffeine** [comment]
Mind giving more context about this? Any examples of how it'd look like?

**Comment by Simn** [comment]
Take:

```haxe
for (charCode in string) {
    trace(charCode);
}
````

Turn into:

```haxe
var iterator = new haxe.iterators.StringIterator(string);
while (iterator.hasNext()) {
    var charCode = iterator.next();
    trace(charCode);
}
```

Inline to:

```haxe
var offset = 0;
while (offset < string.length) {
    var charCode = string.charCodeAt(offset++);
    trace(charCode);
}
```

And the same thing with `for (charOffset => charCode in string)`.

**Comment by RealyUniqueName** [comment]
Are you sure it should iterate over codes and not over chars?

**Comment by RealyUniqueName** [comment]
Or maybe extend String API with `.chars():CharIterator` in addition to `.iterator():CodeIterator`?

**Comment by Simn** [comment]
Frankly, I wouldn't be surprised if people _expect_ characters instead of codes here. However, I feel like we should be a bit arrogant here and say that codes are probably better for them. You can always `String.fromCharCode` if you want an actual character.

I don't mind having a StringCharacterIterator too, that's why we started the haxe.iterators package. But I don't think this has to be added to String itself. We can add convenience functions for all these iterators to StringTools instead.

**Comment by Simn** [comment]
Can we close this?
