### ISSUE TITLE
Compiler cache leads to `$hxEnums not defined`

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#7552]
Since upgrading to 4p5 I occasionally get the runtime error `$hxEnums not defined` because the generated JS indeed doesn't declare that variable after some incremental builds. Will try to make a reproducible example.

**Comment by haxiomic** [comment]
In 4p5 `hxEnums` is emitted if an enum type is used (`has_feature ctx "has_enum"`) or `Type.resolveEnum` is used. One of those flags must be getting incorrectly unset in incremental builds.

I'd guess it's likely that `has_enum` is being unset but if your code uses `Type.resolveEnum`, then try removing the `inline` and `untyped __define_feature__` from `Type.hx`. If that fixes it then it indicates something is going on with `__define_feature__` in incremental builds

I'm guessing `-dce no` prevents the issue?

**Comment by haxiomic** [comment]
I found an easy repro – it seems like the `has_feature` flags are lost on subsequent compiles because the compiler is skipping cached files and not getting any flags from them

There's a zip attached with detailed instructions but the gist is:
- Use an enum that's declared in its own file and compile: *first time, output is correct*
- Compile again after trivial change (but without changing enum): *output is missing `$hxEnums` declaration (i.e. `has_feature "has_enum"` is false)*
[dce-cache-bug.zip](https://github.com/HaxeFoundation/haxe/files/2479528/dce-cache-bug.zip)

This seems like a big issue because quite a lot of code depends on `has_feature` flags!

**Proposed fix**
- When caching a file, also store its associated `has_feature` flags
- When compiling, apply cached `has_feature` flags for all referenced files

**Comment by Simn** [comment]
We already store features in modules (`m_features`). Maybe the problem here is that it's not added to whatever `has_feature` checks exactly.

**Comment by haxiomic** [comment]
That's good to know! It seems to affect other flags too, in the example, on the second compile (without any changes at all), `js_Boot.__string_rec` is missing but used by `$estr`.

Same results on other targets (tested python)

**Comment by kevinresol** [comment]
Interestingly I am not using compilation server but still getting this:

https://travis-ci.org/haxetink/tink_stringly/jobs/441989041#L1815

`-dce no` does fix it.

**Comment by ncannasse** [comment]
Seems like a regression, because I remember it was supposed to work.

**Comment by Simn** [comment]
I have reverted the hxEnums change, will track the rest in #7581.
