### ISSUE TITLE
Trace not showing in "Load Json using Http" example with Java and Cpp targets

### ISSUE THREAD

**Issue by pcdv** [HaxeFoundation/haxe#7563]
Hello,

I'm new to Haxe and was testing a few examples from try.haxe.org on macOS.

I chose the **Load Json using Http** example and was able to make it work in nodejs. But if I choose the java or cpp target, the program does not display anything. 

I tried other examples **Hello world** or **Unit testing** and they worked ok.

I googled around and was not able to find a possible explanation. Sorry if I'm missing something obvious!

Thanks.

**Comment by haxiomic** [comment]
Hey @pcdv, thank you for reporting! The problem is actually down to a typo in the try.haxe.org example's URL and therefore `onData` not being called: add in the missing forward slash after org so it becomes: `https://api.ipify.org/?format=json`.

To catch the error you can add callbacks for `onStatus` and `onError`, 
```haxe
http.onError = function(error) {
    trace('Error: $error');
}
http.onStatus = function(status) {
    trace('Status: $status');
}
```

I'll look into fixing the example and close issue this when that's done :)

**Comment by haxiomic** [comment]
I think haxe should support the URL in the example, here's some discussion: https://stackoverflow.com/a/42193734 about why, so I've made PR #7564 to enable this

**Comment by pcdv** [comment]
Thanks, that was fast. And I confirm it works :)
