### ISSUE TITLE
$hxEnums is not defined

### ISSUE THREAD

**Issue by polygonal** [HaxeFoundation/haxe#7581]
Using Haxe Compiler 4.0.0-preview.5+7eb789f54

File Foo.hx:
```haxe
enum Foo {
	A;
	B;
	C;
}
```
File Main.hx:
```haxe
class Main {
	public static function main() {
		Foo.A;
	}
}
```
Usage:
```
haxe.exe -main Main -js main.js
```
Error:
```
var Foo = $hxEnums["Foo"] = { __ename__ : true, __constructs__ : ["A","B","C"]
ReferenceError: $hxEnums is not defined
```

Probably related to https://github.com/HaxeFoundation/haxe/issues/7552 (although no compilation server is used)

**Comment by polygonal** [comment]
forgot to mention: works when compiled with `-dce no`

**Comment by haxiomic** [comment]
Thanks for the minimal example @polygonal, this helps a lot!

I'm planning to take a look at this one early November

**Comment by romamik** [comment]
Just bumped into this. My minimal example is a little bit more minimal.
Compile with `-dce std` to get error, with `-dce no` or `-dce full` runs fine.
```haxe
package;

enum Foo {
  Bar;
  Baz;
}

class Test {
  public static function main() {
  }
}
```

**Comment by Simn** [comment]
@haxiomic Is it early November yet? :P

**Comment by haxiomic** [comment]
@Simn 
:P early November has been pushed back a bit this year (crunch time in the office at the moment)

I made a start and it seems like global DCE flags are lost by the end of `filters.ml:run`, but I haven't fully grokked the design of the DCE system yet to work out the right solution

**Comment by haxiomic** [comment]
@Simn because this is going to take a little while for me to get to, in the short term we could put `$hxEnums` back as always emitted independent of DCE flags

However I think we should keep this issue as a high priority because it will behind other DCE bugs

**Comment by nadako** [comment]
The problem here is that `Dce.check_and_add_feature` [uses `dce.curclass` module](https://github.com/HaxeFoundation/haxe/blob/1dcb2c550fd6c5037c803a0e692c2eace592b0d4/src/optimization/dce.ml#L119) to add `"has_enum"` feature to, while `dce.curclass` is often set to a `null_class`, especially when we're processing enums.

I [added](https://github.com/HaxeFoundation/haxe/blob/1dcb2c550fd6c5037c803a0e692c2eace592b0d4/src/optimization/dce.ml#L118) a commented-out assert there to catch all these cases and I think the more correct solution would be to also have the `dce.curmodule` that is properly set when processing other kinds of types (or alternatively just have a mutable `dce.add_feature` function pointer that encapsulates how/where the feature is added).

Having said that, I'm not very familiar with the dce code (well, and the compiler code in general) nowadays, so maybe there's a better solution. Summoning @Simn! \o/

**Comment by Simn** [comment]
We could add `curmodule`, or we assign `{null_class with cl_module = ... }` to `curclass` in case of enums.

**Comment by Aurel300** [comment]
Any progress? Temporary work-arounds?

**Comment by nadako** [comment]
In the latest git version, `$hxEnums` is never eliminated, which is a temporary workaround :)
