### ISSUE TITLE
`String.indexOf('')` and `String.lastIndexOf('')`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7609]
Specification added in 6a42fbb6648933b367a8d7809b1af6d11d52743b because of https://github.com/HaxeFoundation/haxe/pull/7608#issuecomment-437071377

Targets to fix:
- [x] neko
- [x] hashlink
- [x] python
- [x] lua
- [x] c#
- [x] java
- [x] cpp

**Comment by Simn** [comment]
Added cpp because that fails too.

**Comment by Simn** [comment]
Note that I moved this to 4.1 in #7402 because I find it too annoying to deal with at the moment. I vote for a revert of https://github.com/HaxeFoundation/haxe/commit/6a42fbb6648933b367a8d7809b1af6d11d52743b unless somebody wants to look into all these targets.

**Comment by Simn** [comment]
Though I'll say that this particular neko failure seems quite bad:

```
src/unitstd/String.unit.hx:81: 14 should be 15
src/unitstd/String.unit.hx:95: 14 should be 15
```

**Comment by Aurel300** [comment]
Found this again during #8117. The docs should specify what the intended behaviour of `s.indexOf("", index)` and `s.lastIndexOf("", index)` should be. Unfortunately making this consistent across targets might involve adding some checks to otherwise direct function mapping:

 - `neko`: `$sfind(str, x, "")` returns `x` but throws an error if `x < 0 || x >= str.length` (but this should be handled in the Stdlib wrapper now)
 - `js`: `str.indexOf("", x)` returns `clamp(x, 0, str.length)`
 - `java`: `str.indexOf("", x)` returns `clamp(x, 0, str.length)`
 - `python`: `str.find("", x)` returns `x < 0 ? max(0, str.length + x) : (x > str.length ? -1 : x)`
 - `php`: `strstr(str, "", x)` issues a warning (empty needle) and returns `false` (not found)
 - `cs`: `str.IndexOf("", x)` returns `x` but throws an error if `x < 0 || x > str.length`
 - `cpp`: `String::indexOf` returns `x > str.length ? -1 : x` (negative index is not handled, so it can trigger a segfault easily)

Some of the above is relevant for `indexOf` behaviour in general, especially when using wild `startIndex` values.

**Comment by RealyUniqueName** [comment]
Added fixes for initial unit tests for an empty search string.

Except lua:
https://github.com/HaxeFoundation/haxe/blob/ed2bc3d339bcefed3f2f95dfbe69aab535e678f9/std/lua/_std/String.hx#L70-L73
@jdonaldson  could you take a look at that please?

**Comment by jdonaldson** [comment]
Sure thing

**Comment by jdonaldson** [comment]
I put in another edge case check to make the lua platform consistent with the rest.  The relevant test has been re-enabled as well.

**Comment by jdonaldson** [comment]
Also, I went ahead and checked off lua from the checklist above, just since it's so satisfying.  😁
