### ISSUE TITLE
[compiler] Dedicated module to print errors

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7634]
From https://github.com/HaxeFoundation/haxe/issues/6860#issuecomment-368066586

Taking the elm compiler as a reference, if I understand correctly, compiler errors are represented as enums and handled by a dedicated module. So that error messages can be nicely/consistently printed, also we can add links to help people understand and fix their errors.

This would probably also help unit testing of the compiler, instead of checking the stderr output text, we can just check the properly typed enum.

Also, the well-formed error should also be exposed to macro, to improve error handling there.

**Comment by ncannasse** [comment]
Where's the PR ? :-D

**Comment by kevinresol** [comment]
I know this is huge because errors are raised from everywhere and there are unit tests based on error message output.

But once the foundation is laid, I think it would be much easier for people to contribute to the actual error messages, reference links, etc.

**Comment by Simn** [comment]
I already spent a lot of time restructuring the compiler sources to make this possible. It comes down to extending the `error_msg` ADT in `error.ml` and then replace all calls to `error` (which uses the `Custom` constructor) with `raise_error` (which would use structured errors).

The only real issue here is that this is the most boring task I can imagine.

**Comment by Simn** [comment]
I think there's nothing particularly actionable here, and Rudy's recent work on improved error messages has improved error reporting a lot already!
