### ISSUE TITLE
php7 Reflect.getProperty doesn't work

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#7671]
Hej,

I'm using haxe 4 preview 5 and target php7.
When calling Reflect.getProperty, it gives null and the getter is not called at all :

```haxe
class Obj {
	public var test	(get, null)	: String;
	function get_test(){
		trace( "getter call" );
		return "foo";
	}
	public function new(){}
}

class Main {
	static function main(){
		var o	= new Obj();
		trace( o.test);						// "foo" (and "getter call")
		trace( Reflect.getProperty( o, "test" ) );	// "null"
	}
}
```

**Comment by filt3rek** [comment]
Inspecting the output php files, I just saw that in Boot and I don't know if it's correct, it seems $called is always false ?

```haxe
static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;
```

**Comment by RealyUniqueName** [comment]
It's not always `false`. In PHP static local vars preserve their values between function calls.
I'll try to find some time to take a look at this issue today.

**Comment by filt3rek** [comment]
Ah ok, I don't know the PHP very deep, sorry.
About the getter, I've tried Haxe 3.4 also and it's the same, getter is never called. It's strange that noone noticed that yet. 
Thanks for your answer ! 😉

**Comment by RealyUniqueName** [comment]
I've fixed it for `-dce no` and `-dce std`.

@Simn, with `-dce full` there is no way for a generator to check if `get_test` is actually a getter or just a normal function, which just happens to have such a name. Because the corresponding property is already erased at the generation step. Could we extend a `MethodKind` enum or add a field like `field_purpose`  to `tclass_field` structure?

**Comment by ncannasse** [comment]
I think the correct fix would be to keep the property as long as the getter
or setter is kept.
