### ISSUE TITLE
switch "clears" type parameter

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#7672]
So this happened:

```haxe
enum EListingField<T:Obj> {
	ELCounter;
	ELID;
}

typedef TListingConf<T:Obj> = {
	fields:Array<EListingField<T>>
}

class Obj {
	public var id : Int;
}

class Main {

	static function main() {}
	 
	static function works<T:Obj>( conf : TListingConf<T>, iterable : Iterable<T> )
		for (o in iterable)
			for (field in conf.fields) 
				'<td>${o.id}</td>';

	static function doesnt<T:Obj>( conf : TListingConf<T>, iterable : Iterable<T> )
		for (o in iterable)
			for (field in conf.fields) {
				$type(o); // doesnt.T
				switch field {
					case ELCounter:
						'<td>&nbsp;</td>';
					case ELID:
						$type(o); // Unknown<0>
						'<td>${o.id}</td>';
				}
			}
}
```

Fails with:

```
src/Main.hx:30: characters 11-15 : Constraint check failure for EListingField.T
src/Main.hx:30: characters 11-15 : { id : String } should be Obj
```

FWIW the `$type` warnings are reported in order of occurrence. Problem exists on 3.4.7, 4p5 and current nightly.

**Comment by Simn** [comment]
This is another instance of GADT gone wrong. Related: #4578

**Comment by Simn** [comment]
The behavior is different when using `case EListingField.ELID:` which is very concerning. I think this must be some difference in general typing because the pattern matcher should treat these equally. My guess is that the qualified version doesn't apply the type parameters correctly, which happens to avoid the problem here by accident.
