### ISSUE TITLE
Xml parser false positive

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7689]
The following string passes the xml parser while it should not:
`haxe.xml.Parser.parse("<flow>x")`

**Comment by ncannasse** [comment]
The following example, instead of throwing an XmlParserException, will issue a Bad node type error:

```haxe
class Main {

	static function main() {
		var xml="<f><f/></f></f>";
		trace(haxe.xml.Parser.parse(xml));
	}
	
}
```

**Comment by Simn** [comment]
After the recursion in `CHILDS` state, the outer state becomes `BEGIN` and it falls through the switch due to eof. Then this happens:

```haxe
		if (state == S.BEGIN)
		{
			start = p;
			state = S.PCDATA;
		}

		if (state == S.PCDATA)
		{
			if (p != start || nsubs == 0) {
				buf.addSub(str, start, p-start);
				addChild(Xml.createPCData(buf.toString()));
			}
			return p;
		}
```

It switches states from `BEGIN` to `PCDATA` and then accepts the input.

I think going from `CHILDS` to `BEGIN` is not right. It loses the contextual information that we have an open tag.

**Comment by ncannasse** [comment]
The folllowing also successfully parses while it should not:
`<f><f></f>`

**Comment by Simn** [comment]
Yes that's the same problem. The parser logic basically does not check for closing tags at all.

**Comment by Simn** [comment]
Setting this to 4.0 because it's a bit embarrassing.

**Comment by Simn** [comment]
This took me longer than I care to admit because the parsing logic is a bit wonky. I think it has the correct checks in place now, but it's hard to be certain...
