### ISSUE TITLE
[nullsafety] false-positive error for field access

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7723]
```haxe
@:safety
class Main {
	static function main() {
		var s:{?f:Int} = {};

		if (s.f != null) {
			f(s.f); // error!
		}
	}

	static function f(v:Int) {}
}
```

This gives:
```
src/Main.hx:7: characters 6-9 : Safety: Cannot pass nullable value to not-nullable argument "v" of function "f".
```

It's currently a [known limitation](https://github.com/RealyUniqueName/Safety#limitations), but I think we can make it work for physical field access as long as there's no _impure_ operations between the null check and the access. Note that there can be a case when we read the field twice - first time right after null check, and the second one after some impure call - we should allow first and complain about the second one.

**Comment by nadako** [comment]
> as long as there's no impure operations between the null check and the access

FYI, TypeScript currently [doesn't care about this at all](https://www.typescriptlang.org/play/#src=var%20o%3A%20%7B%20f%3F%3A%20number%3B%20%7D%20%3D%20%7Bf%3A%2015%7D%3B%0D%0A%0D%0Aif%20(o.f%20!%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20mutate()%3B%0D%0A%20%20%20%20var%20n%3A%20number%20%3D%20o.f%3B%0D%0A%7D%0D%0A%20%0D%0Afunction%20mutate()%20%7B%0D%0A%20%20%20%20o.f%20%3D%20undefined%3B%0D%0A%7D%0D%0A).

**Comment by back2dos** [comment]
Hmm, the purity idea sounds fancy, but I doubt it'd be practical. As soon as you `trace(s.f)`, it's nullable again. And even then, this would only work in single threaded environments (and you'd have to also be very careful around coroutines and such). 

This is pretty much consistent with maps and what not. I think the best way to deal with it is like so:

```haxe
@:nullSafety
class Main {
	static function main() {
		var s:{ ?f:Int } = {};

		switch s.f {
			case null:
			case i: f(i);
		}
	}

	static function f(v:Int) {}
}
```

This completely sidesteps all problems that might spring from `s.f` being modified.

**Comment by ncannasse** [comment]
I find the TypeScript approach very pragmatic. It's quite bad from a theoretical point of view, but if the idea is to get rid of 98% of null accesses (VS 100%) it's good enough. 

Maybe it is the best trade-off between end-user annoyance and actual runtime safety.

**Comment by back2dos** [comment]
In light of the fact that the switch statement perfectly does the job, doing something that is plainly incorrect is many things, but not pragmatic.

**Comment by Gama11** [comment]
So you want people to replace all `if (some.field != null)` checks with switch statements? That seems quite unrealistic to me, the end result of that is probably just that they wouldn't bother to enable null safety at all (me included).

**Comment by Simn** [comment]
I'm lost, how does using a switch make any difference here?

**Comment by back2dos** [comment]
> So you want people to replace all `if (some.field != null)` checks with switch statements? 

If your expectation is that making code null safe will just be a matter of adding `@:nullSafety` globally, you're in for a surprise. For starters, all the fields that are indeed nullable will have to be declared as such and as a result a lot of code that accesses them without a null guard (because it "knows" that the field is initialized by the time it's accessed). Consider just this simple pattern:

```haxe
@:nullSafety
class Main {
	public var lazy(get, null):String;
	function get_lazy() {
		if (lazy != null) lazy = computeSuperExpensiveString();
		return lazy;
	}
	function new() {}
	static function main() {
	}
	static function computeSuperExpensiveString() {//TODO: optimize
		Sys.sleep(.5);
		return 'yo!';
        }
```

This will fail, because non-nullable fields have to be initialized at declaration or in the constructor (even adjusting a code base to that simple fact will take some amount of work). But since the field is to be initialized lazily, you have to either use `""` as a sentinel, or do something like this:

```haxe
	var _lazy:Null<String>;
	public var lazy(get, never):String;
	function get_lazy() 
		return switch _lazy {
			case null: _lazy = computeSuperExpensiveString();
			case v: v;
		}
```

And so on, an so forth ...

> That seems quite unrealistic to me, the end result of that is probably just that they wouldn't bother to enable null safety at all (me included).

If some people don't see the value of null safety, then they have to do exactly *nothing* to not opt in. 

Those who do will have to do quite a bit of work, the least of which will be to swap out `if` for `switch`. And it seems far more unrealistic anyone would go through all the trouble to get null safety only in the "pragmatic" cases.

**Comment by back2dos** [comment]
> I'm lost, how does using a switch make any difference here?

This works *already*, because the switch captures the value and therefore `i` is known to not be `null`, regardless of any changes to `s.f`. Is that what you're asking?

**Comment by RblSb** [comment]
> this would only work in single threaded environments (and you'd have to also be very careful around coroutines and such)

I think it's a pretty big layer of code. Things may not be asynchronous at all, so this strictness is unnecessary in many cases. It would be very nice if this particular filter were optional and included on demand for packages, just like `@:nullSafety` (because strict field access is important feature, but for another type of projects). Like `@:threadNullSafe` (or reverted `@:threadNullUnsafe`) for classes / fields. Switch / temp var is just look verbose.

**Comment by back2dos** [comment]
You're cherry picking. There's a whole array of ways that the field can get modified.

If you're concerned with terseness, that is a different matter. I would point out that the token count for the switch statement is exactly the same (17), but the example is contrived. Let's use slightly more realistic field names:

```haxe
@:safety
class Main {
  static function main() {
    var object:{?minWidth:Int} = {};

    if (object.minWidth != null) {
      f(object.minWidth);
    }
    //vs switch:
    switch object.minWidth {
      case null:
      case i: f(i);
    }
  }

  static function f(v:Int) {}
}
```

As you can see, there is less redundancy in the switch than the if. And the syntax is more stable. What if minWidth becomes a property? Will we still pretend it's nullability is invariant? Do you even want to be calling the getter twice? And how about if it becomes `function getMinWidth():Null<Int>` then?

```haxe
    switch object.getMinWidth() {
      case null:
      case i: f(i);
    }
    //is this really better?
    if (object.getMinWidth() != null) {
      f(object.getMinWidth());
    }
```

If you really want to code golf, then this is the winner btw:

```haxe
    //static extension `ifSet` on `Null<T>` (or we could actually add something like this to `Null<T>`):
    object.minWidth.ifSet(i -> f(i));//actually in this case you can just use `f` instead of `i -> f(i)`.
```

Also, half the time you'll actually want to treat the null case. So you want to be comparing:

```haxe
    if (object.minWidth != null) {
      f(object.minWidth);
    }
    else {
      f(determineDefault());
    }
    //vs switch:
    switch object.minWidth {
      case null: f(determineDefault());
      case i: f(i);
    }
```

And in fact in the special case where you want to just use a default value:

```haxe
    //vs again static extension:
    f(object.minWidth.or(determineDefault()));
    //vs defining an operator on `Null<T>` ... probably not gonna happen, but I'm just saying
    f(object.minWidth || determineDefault());

```

There's absolutely no point in clinging to this type hole inducing `if` pattern, because there are numerous alternatives that are more succinct **and** work for *arbitrary* nullable expressions **and** avoid computing the same thing twice.

**Comment by Gama11** [comment]
@back2dos Your replacements for _simple_ if-checks don't look terrible (though I still think it's highly unrealistic to expect that people will change their habits to that degree). However, for more complex ifs with multiple conditions it IMO looks much worse due to the increased indentation:

```haxe
if (client != null && client.outputChannel != null) {
	client.outputChannel.dispose();
}
`````

vs:

```haxe
if (client != null) {
	switch client.outputChannel {
		case null:
		case outputChannel: outputChannel.dispose();
	}
}
```

(I guess what I'd really want here is a C#-style `client?.outputChannel?.dispose();`)

**Comment by Simn** [comment]
Note that these switches are translated to `if` expressions too. The match + bind is not an atomic operation in multi-threaded environments.
