### ISSUE TITLE
Compilation fails when using the same name as an abstract field for captured variable

### ISSUE THREAD

**Issue by leonaci** [HaxeFoundation/haxe#7728]
Haxe 4.0.0-preview.5 on windows(64 bit) fails to compile the following code:
```hx
enum E {
	A(s:S);
}

abstract S(String) {
	public var value(get, never):String;
	function get_value():String return this;
}

class Test {
	static function f(e:E):Void {
		switch(e) {
			case A(value):
		}
	}
    
    static function main() {}
}
```

Error message:
`src/Test.hx:13: characters 11-16 : Cannot access non-static abstract field statically`

Same in preview.4.

Maybe it is related to the issue #5011, but not reproduced on 3.4.4 : [try.haxe.org/#1928b](https://try.haxe.org/#1928b)

**Comment by Simn** [comment]
I wonder if we should change the pattern matcher behavior to only look up enum (and enum abstract) constructors, instead of trying to just type the entire thing like we do now. That would also solve the problem where you add some inline field and suddenly your patterns resolve to it.

You could still match against inline fields but you would have to qualify them. It's a breaking change and I'm not entirely sure if it's a good idea, but I really don't like this attempted typing we do with identifiers right now.

**Comment by nadako** [comment]
> You could still match against inline fields but you would have to qualify them. 

What? We don't have to qualify inline fields? I was sure it's supposed to only work for enum ctors :)

**Comment by Simn** [comment]
I have to fix this for the RC somehow...

**Comment by Simn** [comment]
This isn't a good solution for various reasons, but I think it's fine for the RC.

I still want to try and only allow unqualified typing of enum (abstract) constructors. That should help cleaning up the matcher logic quite a bit.

**Comment by Simn** [comment]
One other thing we currently allow as plain idents in patterns is type expressions like `case String`. I hate this a bit but I guess it's too late to suggest removing it.

**Comment by Simn** [comment]
The other problem is that people probably burn my house down if we break this:

```haxe
class Main {
	static inline var key1 = 12;
	static inline var key2 = 13;

	static public function main() {
		switch (getKey()) {
			case key1:
			case key2:
		}
	}

	static function getKey() {
		return 13;
	}
}
```

Not sure what to do here

**Comment by Simn** [comment]
Not gonna change anything for 4.0 after all. Mostly because I'm not sure what to change.
