### ISSUE TITLE
[js] haxe.http.HttpJs Enable DELETE, PATCH, PUT

### ISSUE THREAD

**Issue by dmcblue** [HaxeFoundation/haxe#7762]
JavaScript is capable of DELETE, OPTIONS, PATCH, and PUT requests but the Haxe implementation ( [haxe.http.HttpJs](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/http/HttpJs.hx) ) does not allow this (at least as far as I can figure out).  Some thing like the attached code would allow other request types; its just a slight change of the existing code.

Of course, it'd probably be best to refactor all the Http classes to have a more straight-forward interface that works across all (or most) platform targets but this could be a quick fix.

[HttpJs.hx.txt](https://github.com/HaxeFoundation/haxe/files/2838033/HttpJs.hx.txt)

**Comment by Simn** [comment]
That seems like a fair idea, but it should use https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/http/HttpMethod.hx instead of a `String` argument. It also shouldn't still have the additional `post` argument because that's redundant.

Feel free to send a pull request so we can discuss this further.
