### ISSUE TITLE
[macro] typedef vs Context.typeExpr

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7763]
Sometimes you want to write a macro that receives a "type expression" and processes it somehow. A natural way is to do `Context.typeExpr` and match for `TTypeExpr(...)`, however there are two problems with passing `typedef`s like that:

```haxe
typedef A = {};
typedef B = Int;

class Main {
	static function main() {
		f(A);
		f(B);
	}

	static macro function f(t) {
		var td = switch haxe.macro.Context.typeExpr(t).expr {
			case TTypeExpr(TTypeDecl(td)): td;
			case other: throw "typedef expected, got " + other;
		}
		trace(td);
		return macro null;
	}
}
```

For `f(A)`, this code will fail with the error `A is not a value`, which is fair if we consider normal typing, but it would be good to delay this error to let macro process it in some way. Especially given that we have an API which is supposed to allow that (`case TTypeExpr(TTypeDecl(...))`).

For `f(B)` the macro seems to receive a followed type in `TTypeExpr`, which will result in a pattern matching failure and thus the error: `typedef expected, got TTypeExpr(TAbstract(Int))`

**Comment by Simn** [comment]
Well, that's how expression typing works and that's what `typeExpr` exposes. I don't think we should change the behavior here or make special cases for it.

**Comment by nadako** [comment]
That's debatable, because technically there's no reason to not **type** it as `TTypeExpr(TTypeDecl)`, like we do for other type expressions. And we already defer some checks for the later, like the var initialization or null for static platforms, how this particular "type is not a runtime value" check is different from those that it should be done eagerly in the typer?

What about the second thing? I don't understand how is that intended behaviour :)

**Comment by Simn** [comment]
I'm not sure what you mean. The typer has always followed typedefs to their actual types for type expressions. That's implemented directly in `type_module_type` and probably code from Haxe 0.1. If we changed that, we would have to review all occurrences of `TTypeExpr` and `type_module_type` to make sure it uses `resolve_typedef` where appropriate.

You'd have to find a really good reason for doing that to warrant the effort. And even then, it would be a breaking change for macros, and it would also break if you added `var A` in your example. Overall, using `getType` seems much more appropriate here.

**Comment by back2dos** [comment]
Using expressions to refer to types is pretty iffy and the [evolution proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/44) to improve it got rejected, so I guess you'll have to live with the fact that this is deemed an edge case. FWIW this will work quite fine for typedefs:

```haxe
function getPath(e:Expr)
  return switch e {
    case macro $i{name}: name;
    case macro $owner.$field: '${getPath(owner)}.$field';
    default: Context.error('dot path expected', e.pos);
  }
Context.getType(getPath(e));
```

**Comment by nadako** [comment]
> Overall, using `getType` seems much more appropriate here.

> FWIW this will work quite fine for typedefs

yeah that's basically what I generally use, but I always saw that as a workaround for the `TTypeExpr` situation. maybe i got it wrong, so oh well :)

**Comment by Simn** [comment]
Well, if we had https://github.com/HaxeFoundation/haxe-evolution/pull/44  it would require users of your macro to use `f(:A)`, which is arguably worse than `f(A)` with appropriate handling. So I'd argue that the `getPath` approach is actually superior for this case.

We could add `getPath` to ExprTools. We already have the reverse in MacroStringTools.toFieldExpr (sort of, it accepts `Array<String>` instead of the dot-path as an argument).

**Comment by back2dos** [comment]
> Well, if we had [HaxeFoundation/haxe-evolution#44](https://github.com/HaxeFoundation/haxe-evolution/pull/44) it would require users of your macro to use `f(:A)`, which is arguably worse than `f(A)` with appropriate handling. So I'd argue that the `getPath` approach is actually superior for this case.

That argument only works for the most trivial of cases: when the type is an unparametrized type path. It doesn't cover function types, anonymous types or parametrized types. Some of those cases can be worked around with via typedefs, but again not all:

```haxe
static function blargh<T>(value:T) {
  someMacro(:Array<T>);
}
```

There's no way to typedef to `Array<blargh.T>`, so you have to come up with even weirder workarounds like `someMacro((_:Array<T>))`. Or use strings like @frabbit showed in the Oct 2018 HaxeUp. Sure, it's all possible, but pretty awkward. So long as this is considered an edge case (I disagree with that assessment, but it's what it is), such awkwardness is what we have to live with. I think it's fair to then point out when this "edge case" comes up, so that the situation can be reassessed, if the "edge case" becomes the rule ;)

**Comment by nadako** [comment]
for the record, i also agree that a complex type expression would be useful in a world full of macros :) i mean we even have inline xmls that are required to be processed by macro...

**Comment by Simn** [comment]
See that's why we're so apprehensive to adding new syntax because as soon as you do, everyone goes "you added xyz so you might as well add abc".

**Comment by nadako** [comment]
(don't want to start a long argument here, but still) i think that's a natural reaction when a syntax with basically one justified use-case is added, when one with much more usages is deemed "not worth it". given that there are very much viable workarounds/alternatives for both of them

**Comment by Simn** [comment]
> with much more usages

Which are? The only thing this seems to do is allow you to write `:SomeType<X>` instead of `(_:SomeType<X>)`. Yes it looks nicer, but I'm not seeing more usages here.

Also, https://github.com/HaxeFoundation/haxe-evolution/pull/44 was never suggested in a macro-only context. In fact, most of the discussion revolved around run-time intricacies.

**Comment by nadako** [comment]
> The only thing this seems to do is allow you to write `:SomeType<X>` instead of `(_:SomeType<X>)`.

Exactly, `validate(value, :Type<X>)` looks much cleaner than `validate(value, (_:Type<X>))` or `validate(value, var _:Type<X>)` or `validate(value, "Type<X>")`, not only because of the token-count, but also because the syntax has clear meaning and purpose - to pass a type. It's just good for readability IMO. And I think given that there are more use-cases where you'd want to pass a complex-type, it's more important to have a clear syntax for that than to have an inline xml instead of an xml string.

And the discussion about run-time was mostly about the fact that the proposed run-time behaviour is not new for Haxe - we can typedef a type with diferent type parameters and use it as a type expression just like that. It's already a "hole" if you wish and the proposed feature didn't make it worse, IMO. That said, for me having it as a macro-only feature would be sufficient.

**Comment by back2dos** [comment]
> `validate(value, :Type<X>)` looks much cleaner than `validate(value, (_:Type<X>))` or `validate(value, var _:Type<X>)` or `validate(value, "Type<X>")`

Well, to be fair, what you probably want is `validate((value : Type<X>))`. If only we could get rid of that ternary operator, you could make it shorter still ...

> See that's why we're so apprehensive to adding new syntax because as soon as you do, everyone goes "you added xyz so you might as well add abc".

I've heard you say that a number of times and IIRC I already tried to clarify the issue, but at the risk of repeating myself I will do so again: you're misperceiving what has actually been said.

It's not exactly the exception that proposals get opposed on the grounds of some design maxim that Haxe supposedly follows. E.g.: "we can't add `...` as unary prefix op, because it has no default runtime semantics" or "we can't add `EComplexType`, because it has no runtime semantics". Well then, if there are counter examples (`in` outside `for` head, `=>` operator, xml literals, expression level runtime meta (without the colon)), you're sure to get them, because it's a correct rebuttal to an incorrect universal claim.

The argument made however is not "you added xyz so you might as well add abc". The argument is "I have a really good use case for abc that would make my life better". Of course almost everything is easier than judging the value of a use case. None the less, that is what we should be genuinely trying, because that's the ground on which truly pragmatic decisions are made. Which brings us to the crux of the matter:

>> with much more usages
>
> Which are? The only thing this seems to do is allow you to write `:SomeType<X>` instead of `(_:SomeType<X>)`. Yes it looks nicer, but I'm not seeing more usages here.

This is the equivalent of saying that `var` has only one use case: you can write `{ var x = someExpr; trace(x * 2); }` instead of `(function (x) trace(x * 2))(someExpr)` or `switch someExpr { case x: trace(x * 2); }`

Ok, yes, `var` has "one use case", but it happens to cover an immense problem domain. I concede that the "one use case" for `EComplexType` covers a significantly smaller domain, but I would argue from personal experience that it is still relevant: as I had mentioned in the original proposal, our code base at Docler has a few hundred occurrences of types being encoded as strings for the lack of a better alternative (although admittedly it's slowly decreasing as we're cutting down non-essential use of dependency injection). Dan seems to need this too, as does Heinz, as did the author of the evolution proposal. That may not be enough, ok, fine I guess. But if it'll keep coming up, then perhaps there's actually something to it ;)

**Comment by Simn** [comment]
You're always doing the same thing: Take something, abstract it to arbitrary levels and then derive something else from that. If you abstract enough, you can find a perceived precedent for anything and thus justify its validity. While this is a good approach in a court of law, I don't believe that it leads to good language design.

> "we can't add `...` as unary prefix op, because it has no default runtime semantics"

That's misconstrued and you know it. My concern in that discussion (#7234) was that we would create such a precedent, and you're proving time and time again that you're more than happy to use that to justify further additions.

> "we can't add `EComplexType`, because it has no runtime semantics"

That is also inaccurate. Nicolas didn't argue that we can't add it because it has no run-time semantics, he merely questioned the overall benefit (because there are no run-time semantics).

> Of course almost everything is easier than judging the value of a use case. None the less, that is what we should be genuinely trying, because that's the ground on which truly pragmatic decisions are made.

But that is exactly what you're _not_ doing.

> `var`

Case in point... more likening something to something else and deriving.

> as I had mentioned in the original proposal, our code base at Docler has a few hundred occurrences of types being encoded as strings for the lack of a better alternative

> Dan seems to need this too, as does Heinz, as did the author of the evolution proposal.

Yah that's a much more interesting approach. Unfortunately, there was no follow-up in the Haxe-evolution proposal and the original author ended up ragequitting Haxe. The thing wasn't even formally rejected in the end.

I'm trying to keep an open mind to these things and realize that sometimes I misjudge the costs and benefits of features. However, it's much easier to convince me with good usage examples than by telling me that you can use switch in place of var.

**Comment by ncannasse** [comment]
We already have th `_:` operator for that ;-)   `f(_:Array<Int>)` works really well.

**Comment by nadako** [comment]
> We already have th `_:` operator for that ;-) `f(_:Array<Int>)` works really well.

You meant `f((_:Array<Int>))` and I already mentioned it :)
