### ISSUE TITLE
[js] should HttpBase's setPostData() parameter accept more than just String?

### ISSUE THREAD

**Issue by rb1147x** [HaxeFoundation/haxe#7782]
I recently had an issue where I needed to implement a file upload feature on a website. I am doing this by creating a FormData object, appending the file, and sending it via xhr.

`setPostData` requires a String argument, but on MDN it looks like there should be more acceptable parameters for `xhr.send()`: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send#Parameters

Guessing, I had tried `setPostData(Std.string(form_data))` and various Content-Type headers (multipart/form-data, application/octet-stream, application/x-www-form-urlencoded), however, I'm not sure which, if any of those would be the correct ones. The JS output keeps the `Std.string(form_data)` conversion which may be why it wasn't working.

For now I just cast it with `setPostData(cast(form_data))`, but that just looks odd.

I'm using Haxe 4.0.0-rc.1.

Is this an issue someone has encountered before? Is this a type issue within the `HttpBase` class?

**Comment by haxiomic** [comment]
Thanks for the report @rb1147x 

Hmm, so HttpBase probably should allow non-strings for post data, but [currently the sys implementation assumes a string](https://github.com/HaxeFoundation/haxe/blob/945461390b774b761f57777365b1e0cbb3ac26be/std/sys/Http.hx#L215) so probably won't work correctly for sys targets but I think you're safe for js.

I had a quick look at [sys/Http.hx](https://github.com/HaxeFoundation/haxe/blob/945461390b774b761f57777365b1e0cbb3ac26be/std/sys/Http.hx#L215) I don't think it would be too hard to support binary data there (it's just appended to the message).

Feel free to make a PR to add support for binary postData in [sys/Http.hx](https://github.com/HaxeFoundation/haxe/blob/945461390b774b761f57777365b1e0cbb3ac26be/std/sys/Http.hx#L215) (it doesn't have to be perfect, we can reach an ideal solution after some back-and-forth). Otherwise I'll assign myself after a few days.

**Comment by rb1147x** [comment]
Ah, I'm probably not the most qualified to implement a fix for this in the sys/Http.hx class. I've only been working with the JS target.

And speaking of which, for JS, while a cast is working just fine, I'm assuming there's a better way to handle this?

**Comment by haxiomic** [comment]
If it's browser JS only, then I'd use `js.html.XMLHttpRequest` directly since then you know exactly what is going on (and that has the correct types)

**Comment by haxiomic** [comment]
Looks like #2586 is tracking a similar issue
