### ISSUE TITLE
Rare issue with compiler cache

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7793]
I don't have a reproducible example but I would like this one to be looked into.

In the past months, we had several errors with the following pattern:
- someone has some project open on VSCode, which successfully compiles
- confident enough, he commits+pushes the code 
- someone else updates, and get a parse error in some file (missing ; at eol etc.)
- the original committer can still compile, but when closing and restarting VSCode, he gets the error

The could be an issue with VSCode, expect that it had only occurs so far with parsing errors only - not the other kind of errors.

@Simn could you check if there is any chance that a parsed with error (and resumed?) file might gets into the cache ? (either parsing cache or even typed cache)

**Comment by ncannasse** [comment]
This is an important error, quite rare (4-5 occurrences in the past 2 months) but quite highly problematic. Let's do the checks and hopefully find some reason this might happen. If we can't find it, let's push it to 4.1

**Comment by ncannasse** [comment]
@trethaller can maybe give some additional info

**Comment by Gama11** [comment]
This reminded me of an issue I had written down, but not reported... I think there's a good chance it's related:

- have a `main` with `{}.foo();` and a trace after it
- try to compile it, it should fail with `Unexpected .`
- switch to another `.hx` file tab (to trigger diagnostics on it)
- compile again, now it succeeds, but `main` is empty in the compiled output (!)

Doesn't reproduce with diagnostics disabled, but 100% of the time otherwise.

![](https://i.imgur.com/QMdofQ9.gif)

**Comment by ncannasse** [comment]
Woohoo thanks @Gama11 that might be it indeed!

**Comment by djaonourside** [comment]
I can confirm that it happens with my project too.  Sometimes vscode and compilation server give no error while teamcity building with haxe cmd does it.

**Comment by Simn** [comment]
We cache stuff if

* `ctx.has_error = false` and
* `com.display.dms_full_typing = true`.

The problem with diagnostics is that it collects errors instead of emitting them, which means `ctx.on_error` is never set to `true`. It also qualifies as `dms_full_typing` because that's what we want to do for diagnostics.

We have to somehow communicate that we are in an erroneous state even in diagnostics mode. I'm not sure how to best do that right now because our architecture is pretty awkward in this regard.

**Comment by posxposy** [comment]
This reminds me of my old issue:
https://github.com/HaxeFoundation/haxe/issues/7195

Sometimes, but on a regular basis, I got problems with caching on the C++ target. 
Don't know how to reproduce it, because I do not do anything special. Just writing code as always. Just in some point, I realize that compiled application is using old codebase, or even won't compile at all with linking errors (and sometimes I finding generated classes which were removed from the project some time ago). Restarting VSCode always helps.

**Comment by ncannasse** [comment]
Some additional information : I could confirm that the developer that had the bug had `haxe.enableDiagnostics = false` in VSCode configuration. However I guess this can also be triggered by doing a hover or other diagnostic-on-demand call?

**Comment by trethaller** [comment]
I'm pretty confident (but not 100% sure) that in the few cases where I experienced this, the error was introduced by modifying source code outside of VSCode, most likely in a diff program before committing. The following builds (in VSCode) would then not report any error, and would not until the incorrect file is opened.

**Comment by Simn** [comment]
Vshaxe sets the compiler to a mode where it (the compiler) doesn't check file modification times, but instead relies on vshaxe to inform it about changed files. This gives a huge speedup for completion because we can avoid a lot of file system checks, especially on large codebases. However, it obviously causes problems if files are modified outside of vscode.

@Gama11: We might have to make that a setting which is off by default. That makes me a bit sad but I don't see what else we could do here. Even if we somehow listen to file changes within the open repositories, the problem could occur in files which are outside of that repository.

**Comment by Gama11** [comment]
Hm.. what if there was a mode where the compiler checks file modification times, but only on compilation requests?

In fact, doesn't it already do that since https://github.com/HaxeFoundation/haxe/issues/7203?

**Comment by Simn** [comment]
Right, that's likely again an issue with diagnostics...

There might also be problems with caching in macro context though. That should technically always be considered to be "compilation". Meh

**Comment by Gama11** [comment]
I thought there was no caching for diagnostics precisely because it led to isssues?

**Comment by Simn** [comment]
There is as explained in https://github.com/HaxeFoundation/haxe/issues/7793#issuecomment-463385599

**Comment by ncannasse** [comment]
Just want to emphasis that this is a must-fix for 4.0 final imho

**Comment by Simn** [comment]
Note: @Gama11's issue here is about a _parsing_ error. I completely ignored that fact and it likely is a different problem than other people have.

In principle it's similar: The parser is lenient in diagnostics mode and ignores errors, so the server thinks it's fine to cache the file. It's then picked up on the next compilation.

This probably means that I have to review the error handling in the entire parser again. What a time to be alive...

**Comment by ncannasse** [comment]
@Simn I confirm that our errors also are only about parsing, not typing.

**Comment by Simn** [comment]
This should be resolved. I probably won't know for sure until we make a release, but we're definitely on the right track here.
