### ISSUE TITLE
[eval] Expr presentation in eval-debugger

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7860]
Considering that the primary use case for eval-debugger is macro debugging, it would be nice if `ExprTools.toString()` could be used for the string representation of `Expr` objects. Something like this doesn't tell you a lot at a glance:

![](https://i.imgur.com/QZcRxkq.png)

If this instead showed you what the actual Haxe code the expressions represent looked like (while still allowing to expand and drill down into the underlying fields of course), it would be much more helpful.

**Comment by Simn** [comment]
Note that unlike for regexes, I didn't add this to the actual value printer because all these peasants that use trace-debugging wouldn't like that.

I'm also not going through haxe.macro.Printer but use your `Ast.s_expr` instead. That's because `haxe.macro.Printer` might not even be part of a compilation, and I don't think we want to start loading additional types when debugging.

**Comment by Gama11** [comment]
This is pretty awesome. :tada:

![](https://i.imgur.com/agWKgnh.png)

**Comment by Gama11** [comment]
Thanks to tooltips, it even works reasonably well for multi-line expressions:

![](https://i.imgur.com/qWpvqeU.png)

Now if only VSCode would allow us to syntax-highlight that. :)

**Comment by Simn** [comment]
That screenshot gives me a headache.
