### ISSUE TITLE
[eval] uninitialized var shown with value of loop counter

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7861]
This is an interesting one...

```haxe
#if !macro
@:build(Main.build())
#end
class Main {
	static function main() {}

	#if macro
	static function build() {
		for (_ in [1,2,3]) {}
		var foo;
		return null;
	}
	#end
}
```

![](https://i.imgur.com/yULM6dw.png)

Without the loop, the value is `null` as long as it's not been initialized as expected.

The dump is also interesting:

```haxe
static function build() {
	{
		{
			var _ = 1;
		};
		{
			var _ = 2;
		};
		{
			var _ = 3;
		};
	};
	var foo;
	return null;
}
```

It looks like `-D analyzer-optimize` fails to optimize that away.

**Comment by Simn** [comment]
The problem is that eval shares local slots to minimize memory usage. You can also reproduce the problem with this:

```haxe
class Main {
	static function main() {
		{
			var x = 1;
			trace("ok");
		}
		var foo;
	}
}
```

This will show `foo = 1` because `foo` and `x` share the same local slot.

This is going to require a different approach which actually considers the liveness of variables properly. At the very least we'll have to detect that the variable is defined after (or on) our current position. This would mean that when stopping on the `var foo`, you would _not_ see the `foo` variable, which I think is how other debuggers behave as well.

**Comment by Gama11** [comment]
>This would mean that when stopping on the `var foo`, you would _not_ see the `foo` variable, which I think is how other debuggers behave as well.

I think it depends, for both Node and Flash it seems to be `undefined`. But yeah, that seems perfectly fine. Seems to behave like that in HL too.

**Comment by Gama11** [comment]
While this is fixed for the variables view, hover and debug console are still broken:

![](https://i.imgur.com/SNNpDty.png)
