### ISSUE TITLE
[eval] no variables at "leaving-function" position

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7862]
Follow-up for #7767. The fake position on `}` doesn't show any of the variables in the current scope:

```haxe
class Main {
	static function main() {
		foo();
	}

	static function foo() {
		var value = 1;
		trace("bar");
	}
}
```

![](https://i.imgur.com/r89HanU.png)

![](https://i.imgur.com/ZNFJhIp.png)

This works fine in the HL, Flash and Node debuggers.

**Comment by Simn** [comment]
Meh, the scope is already closed at that point, so it's not exactly incorrect to say that there are no variables because there are no scopes. This would be quite confusing on `return` statements because your cursor would be at the end of the function, but the scope you see could be somewhere in the middle of it.

Or is it only supposed to halt at the `}` if control flow falls through?

**Comment by Gama11** [comment]
>Or is it only supposed to halt at the `}` if control flow falls through?

Yes.

**Comment by Simn** [comment]
I don't understand how this is useful or makes any sense from a run-time point of view, but if all other debuggers do it I guess I'll try to comply.
