### ISSUE TITLE
[nullsafety] false-positive in pattern matching

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7973]
```haxe
enum E {
  A(x:Null<Int>);
}

@:nullSafety
class Main {
  static var e:E = A(null);

  static function main() {
    switch e {
      case A(null):
      case A(v): (v : Int); // Null safety: Cannot cast nullable value to not nullable type.
    }
  }
}
```

**Comment by Simn** [comment]
Note that the pattern matcher translates this to an `if`. We should also check if this occurs if there are more than two cases.

My guess is that the null-checker doesn't deal with `TEnumParameter` correctly. This can basically be treated like a field access to a `final` field because enum values are immutable.

**Comment by CarlOlson** [comment]
I can't reproduce this behavior on RC3.

**Comment by RealyUniqueName** [comment]
It's not reproducible now, because it's was fixed along along with some other similar issue.
Here is what comes from pattern matcher:
```haxe
var tmp = Main.e;
{
	var x = tmp[0];
	if (x == null) {} else {
		var v = x;
		{
			i = v;
		};
	};
};
```
As you can see `v` is null-safe because it is assigned from `x` in a branch where `x` cannot be null. Thus no error emitted.
