### ISSUE TITLE
[bug] uppercase package name and lowercase packagename macro

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8019]
It just was a try and it works. I was confused that it works.
It shouldn't work.

Example: http://try-haxe.mrcdk.com/#98B02

```haxe
var c:haxe.macro.Expr.TypeDefinition = {
  pos: haxe.macro.Context.currentPos(),
  pack: ['Test'],
  name: 'test',
  kind: TDClass(),
  fields: [
    {
      access: [APublic],
      name: 'new',
      kind: FFun({
  			expr: macro {},
        ret: null,
        args: []
      }),
      pos: haxe.macro.Context.currentPos()
    }
  ]
};
haxe.macro.Context.defineModule('Test', [c]);
```

generates (is valid):

```js
var Test = function() { };
$hxClasses["Test"] = Test;
Test.__name__ = ["Test"];
Test.main = function() {
	haxe_Log.trace("Haxe is great!",{ fileName : "Test.hx", lineNumber : 3, className : "Test", methodName : "main"});
};
var test = function() {
};
$hxClasses["test"] = test;
test.__name__ = ["test"];
test.prototype = {
	__class__: test
};
```

**Comment by Gama11** [comment]
This seems similar to how macros don't check the names of identifiers as would be the case with normal Haxe syntax (#5002).

**Comment by Gama11** [comment]
`name: 'test'` no longer works due to #8708.

It looks like the `pack: ['Test']` example in particular isn't actually a bug, that gets interpreted as a module name:

https://github.com/HaxeFoundation/haxe/blob/329d29f4f97d1eaf8562680300847cacefcb4ed4/src/macro/macroApi.ml#L1478-L1482

But of course, there's still plenty of other ways to produce invalid packages:

```haxe
pack: ['']
pack: ['0']
pack: ['Foo', 'Bar']
pack: ['\n']
...
```

I think the compiler should error in those cases.
