### ISSUE TITLE
[lua] un-hardcode more initialization lua code

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8051]
See https://github.com/hxdefold/hxdefold/issues/13#issuecomment-476400759

**Comment by jdonaldson** [comment]
hey @nadako can you check out this branch and see if it works for you ? https://github.com/HaxeFoundation/haxe/tree/unhardcode_lua_init

**Comment by jdonaldson** [comment]
I checked in the relevant change here : https://github.com/HaxeFoundation/haxe/commit/561e73ed9bdfcd80c55e119058874717a848ff1d

The lua helper scripts are more stable now, and I don't need to tweak them along with the generator any more.  It makes sense to factor them out.  I believe this solves the issue here as well, so I'll close this.  Feel free to re-open if there's another detail to address.
