### ISSUE TITLE
Sys unicode unit tests

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8094]
I know it's late since we're already at RC2 but I'm a bit worried about our state of Sys support wrt unicode, as #8087 #8057 etc are showing.

I don't want to delay the 4.0 final release but I think it's better if we have a good picture of were we're at and if we can fix some of the most urgent issues before final release that would be great.

We need to test the following (with full unicode chars - including 😂):
- filesystem names (file/dirs) , cwd/setcwd
- filesystem I/O (read/write)
- Sys.args
- print
- stdin/stderr/stdout
- sys.io.Process args + i/o
- env variables get/put
- and basically most of Sys class API

The tricky part is that we cannot just check that `readDirectory(createDirectory("é")) == "é"` since we might create some weirdly name directory, then decode it wrongly, and consider that we pass the test.

So for instance we need to have first a validation of readDirectory (with an already GIT created dir+file) and then we can test createDirectory.

Same of env vars / Sys.args etc.

**Comment by Aurel300** [comment]
Concerning file and filesystem tests only, for the time being:

The approach of providing files and directories with various Unicode-heavy names directly in the Git repo should cover a lot of cases. Some things of note:

 - characters that are reserved on NTFS (Windows), but allowed on HFS+ (macOS) should not be part of the provided files
    - these should **eventually** be tested but I think for that we need to make sure the sys platform understands the *filesystem* it works on, rather than just the OS type
 - characters that have different NFC and NFD normalisation
   - in Haxe tests *either* representation should be accepted, since we don't have methods for Unicode normalisation (and maybe never will #7009 #6748 #3072 was opened five years ago!), so read the filenames, decode via `Utf8` into `Bytes`, accept any "correct" representation
   - `git` will accept these files, but macOS and Linux have different conventions on filename representation (NFD and NFC respectively) - I have yet to test if committing from one will somehow turn into the other on the other platform
