### ISSUE TITLE
@:nullSafety on an abstract level is ignored

### ISSUE THREAD

**Issue by AdrianV** [HaxeFoundation/haxe#8121]
this code compiles, but should error

```haxe
@:nullSafety
abstract Foo(Null<Int>) from Null<Int> to Null<Int> {
  // when I enable the next line it errors as expected
  // @:nullSafety	
  public function val(): Int return this;
  
}

@:nullSafety
class Test {
  
  static function main() {
    var x: Foo = null;
    trace(x.val());
  }
}
```

**Comment by CarlOlson** [comment]
@AdrianV I'm having trouble reproducing incorrect behavior. On HEAD and 4.0.0-rc.3 I get the following error:

```
Test.hx:5: characters 29-40 : Null safety: Cannot return nullable value of Null<Int> as Int
```

This makes sense to me. With null safety you cannot cast a `Null<Int>` to an `Int`. If you remove the explicit return type you get the following error:

```
Test.hx:12: characters 11-18 : Null safety: Cannot pass nullable value to not-nullable argument "v" of function "trace".
```

So it looks like since you wrote the code behavior has changed?

**Comment by AdrianV** [comment]
It looks like the issue is fixed. I will close the issue
