### ISSUE TITLE
haxe.io.Bytes does not support UTF-16 surrogate pairs

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#8198]
Using `Bytes.ofString` or `Bytes.toString` incorrectly handles UTF-16 surrogate pairs

(This article might be helpful https://thekevinscott.com/emojis-in-javascript/)

```
"I feel 😉"
Byte 0 is 0
Byte 1 is d
Byte 2 is 49
Byte 3 is 20
Byte 4 is 66
Byte 5 is 65
Byte 6 is 65
Byte 7 is 6c
Byte 8 is 20
Byte 9 is ed
Byte 10 is a0
Byte 11 is bd
Byte 12 is ed
Byte 13 is b8
Byte 14 is 89
```

```haxe
var array = [ 
	0x0,
	0xd,
	0x49,
	0x20,
	0x66,
	0x65,
	0x65,
	0x6c,
	0x20,
	0xed,
	0xa0,
	0xbd,
	0xed,
	0xb8,
	0x89
];

var bytes = Bytes.alloc(array.length);
for (i in 0...array.length) bytes.set(i, array[i]);

var string = bytes.toString();
var bytes2 = Bytes.ofString(string);

trace ("CORRECT BYTES:");
trace (array);

trace ("ACTUAL BYTES:");
for (i in 0...bytes2.length)
{
	trace (bytes2.get(i));
}
```

**Comment by Aurel300** [comment]
Which target? What is the actual output? AFAIK 4.0 is aiming for UCS-2 compatibility, not the full Unicode, i.e. there may be some issues with non-BMP characters (ones which need to be represented with surrogate pairs in UTF-16). This is because some of Haxe targets internally represents strings with UTF-16 and some don't.

**Comment by jgranick** [comment]
Here are some tests:

 1. HTML5 reports byte length of 0 (broken)
 2. Neko appears to work!
 3. HashLink breaks on the "I feel \uD83D\uDE09" string literal and on byte length 0
 4. C++ also appears to work :smile:
 5. Flash appears to _sort of_ work -- the bytes are converted but the values are incorrect

**Comment by ncannasse** [comment]
Bytes.ofString expect UTF8 content, and surrogate pairs are UTF-16, so doing Bytes.ofString on such bytes will not work. 

Where does these bytes come from in the first place ?
The correct UTF-8 bytes for "I feel 😉" are 0x49206665656c20f09f9889

**Comment by ncannasse** [comment]
PS: this has been elevated by Flowplay

**Comment by Aurel300** [comment]
The "correct bytes" in the OP appear to be what you would get if you encoded UTF-16 surrogates into UTF-8, without correctly interpreting the pair as a single codepoint. See e.g. https://stackoverflow.com/questions/51001150/what-are-surrogate-characters-in-utf-8

**Comment by RealyUniqueName** [comment]
`Bytes.ofString(s)` and `bytes.toString()` encodes/decodes to/from Utf8 on utf16 platforms, thus inconsistencies on malformed UTF8 bytes sequences because each platform deals with that in their own way.
Try `Bytes.ofString(s, RawNative)` and `bytes.getString(0, bytes.length, RawNative)` instead.

However, I think we should try and make `ofString(s, UTF8)/toString()` as consistent across targets as possible.

**Comment by jgranick** [comment]
The bytes I shared above come from this string in Java:

“I feel \uD83D\uDE09”

I am also told that this is the proper way for Java to handle it

**Comment by Simn** [comment]
The bytes in the OP are prefixed with the string length and encoding that to bytes makes no sense, no matter the encoding. The example should be changed to lose the 0x00 + 0x0D values because that only confuses the issue here.

**Comment by ncannasse** [comment]
```haxe

class Main {

    static function main() {
		var str = "I feel \uD83D\uDE09";
		var str2 = "I feel 😉";
		trace( str == str2 );
		trace( haxe.io.Bytes.ofString(str).toHex() );
		trace( haxe.io.Bytes.ofString(str2).toHex() );
    }
	
}
```

Here's the output in JS:

```
Main.hx:7: false
Main.hx:8: 49206665656c20efbfbdefbfbdefbfbdefbfbdefbfbdefbfbd
Main.hx:9: 49206665656c20f09f9889
```

So I'm still not sure how you're getting these Bytes, and you should never use directly UTF-16 surrogate pairs as \u as the Haxe compiler will instead insert two unicode chars.

**Comment by ncannasse** [comment]
Oh, I understand now that the 0x000D prefix is actually the string length.
So, the problem here is that you have the bytes 49206665656C20 - which is correct for `"I fell "` but then you have `EDA0BDEDB889` which are not correct utf8 bytes for representing `😉` (it should be F09F9889 as my previous JS example shows).

So my question is: where do these bytes comes from ?

**Comment by ncannasse** [comment]
Uhm, it seems indeed that both "I feel \uD83D\uDE09" and "I feel 😉" are generated the same in Java output, as `java.lang.String str = "I feel \ud83d\ude09";`

I've opened an issue related to that here:
https://github.com/HaxeFoundation/haxe/issues/8204

**Comment by ncannasse** [comment]
@jgranick were you able to solve the issue ? there are two problems on your side
- you need to skip the first two bytes which contains the string length
- the remaining bytes are not UTF8 compatible, you need to fix the sender into sending correct UTF8 data

**Comment by jgranick** [comment]
I'll take a look -- I did just discover this issue which sounds like this encoding difference:

https://stackoverflow.com/questions/8843742/is-ed-a0-80-ed-b0-80-a-valid-utf-8-byte-sequence

**Comment by ncannasse** [comment]
There's some writing about Java uses of "not really utf8" here:
https://en.m.wikipedia.org/wiki/UTF-8#CESU-8
Tell is if you find a reproducible Haxe/Java sample that does not output
valid utf8
