### ISSUE TITLE
[display] Completion within a structure

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8217]
```haxe
class Main {

	static function foo( cmd : String ) {
		switch( cmd ) {
		case "user/login":
			var o = {
				x : 55,
				str : "hello".
				z : 66,
			};
		}
	}

}
```

This fails with `No completion point was found`

**Comment by Gama11** [comment]
Hm...

![](https://i.imgur.com/hAf1zIu.png)

(at 032d95957)

**Comment by ncannasse** [comment]
Ah, this might be more context sensitive because I could reproduce with this `var o` in my class

**Comment by ncannasse** [comment]
I have updated my sample, it should reproduce now

**Comment by Simn** [comment]
This comes out of the parser as an empty block for some reason. Must be some resuming going wrong.

**Comment by Simn** [comment]
Note that this is a bit weird to parse because of the missing `,` after the `str` field. I opted to not auto-fill this one because I'm worried that could lead to wrong parsing in other cases. As a consequence, the subsequent `z` field is _not_ part of the parsed structure:

```
  67- 159 EBlock
  71- 159   ESwitch
  77-  84     EParenthesis
  79-  82       cmd
  94- 106       "user/login"
  89- 157         EBlock
 111- 157           EVars
 111- 157           o
 119- 157             EObjectDecl
 125- 126             x
 129- 131               55
 137- 140             str
 150- 151               EDisplay DKDot
 143- 150                 "hello"
 156- 157           z
```

What happens is that after detecting the completion position, the object declaration parsing figures that we're done with the object and auto-fills the `}` for the object. It then accepts the `z` as a normal identifier but doesn't know what to do with the `:`.

I think the worst case here is that we could get structure completion which includes the `z` field. But there's only so much parse-guessing we can do.
