### ISSUE TITLE
Context.toComplexType() returns extra pos, which cannot be converted by macro reification

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#8261]
```haxe
import haxe.macro.*;

class Test {
    macro static function getComplexType() {
        var ct = Context.toComplexType(Context.getType("Int"));

        trace(ct); //TPath({name: StdTypes, params: [], sub: Int, pos: #pos((unknown)), pack: []})
                   //                                             ^^^ `pos` is not in Haxe 3.4.7

        return macro $v{ct}; // Uncaught exception Cannot convert #pos((unknown)) to expr
    }
    static function main() {
        trace(getComplexType());
    }
}
```

**Comment by andyli** [comment]
9e365cedc6896eb0bd9083b701f8a54e22e7f1d0 is the first bad commit according to `git bisect`.

**Comment by Simn** [comment]
This is a bit of an issue. `TypePath` doesn't have a `pos` field so we cannot just add this when reifying. But we also cannot add it to `TypePath` without breaking lots of code.

I think this secretive position handling was a mistake. We should just have broken this properly once instead of trying to patch it behind the scenes. Not sure what to do about this now other than ignoring these position fields when reifying objects...

#7845 is related.
