### ISSUE TITLE
Lua compiler assumes that standard libraries are in the global table

### ISSUE THREAD

**Issue by EmptySetRBLX** [HaxeFoundation/haxe#8265]
Core functionality such as math, table, and require are all index as:

```
_G.math
_G.table
_G.require
```

In a lot of embedded Lua apps, these are treated as keywords instead of global table entries. 

While you can work around it by inserting these libraries into the global table/setting the global tables __index metamethod to search for the index in the global fenv() with some Lua attached to the top of each file at compile time, its rather hacky and adds an unnecessary layer of complexity to the generated code.

Therefore, there should be a compiler option to disable these global table look ups.

**Comment by nadako** [comment]
> there should be a compiler option to disable these global table look ups

Note: when/if we do that, don't forget about escaping haxe identifiers where needed.

**Comment by jdonaldson** [comment]
I think the best approach here would be to assign these standard library module instances back to the global table.  Otherwise, the wrong variable assignment could clobber the whole (e.g. `table`) module. 
 This should be done as part of an initialization step, probably the very first one.

I'm thinking maybe some sort of `-D` directive? e.g.:

```
-D alias_lua_global _G.math:math
-D alias_lua_global _G.table:table
...
```
I'd like to alias them all at once, but my guess is that different environments are going to proxy/alias different standard libraries.  So, let's start with one at a time.

I'm also wondering if this would ever make sense on other targets, and if we should follow some shared pattern.

**Comment by jdonaldson** [comment]
I actually think there's a good pattern that exists for this already, use Compiler.includeFile : https://api.haxe.org/haxe/macro/Compiler.html#includeFile

you can generate a simple patch script like so : 


```lua
-- fix_modules.lua
_G.math = math;
_G.require = require;
_G.table = table;
```

You can include this script via hxml:

```hxml
-main Main
-lua out.lua
-cmd lua out.lua
--macro haxe.macro.Compiler.includeFile("fix_modules.lua")
```
or via ``__init__``:
```haxe
class Main {
    public static function main() {
        trace("Hello World");
    }
    static function __init__(){
        haxe.macro.Compiler.includeFile("fix_modules.lua");
    }
}
```

This should insert the script near the top of the generated output, before the global namespace table is referenced anywhere.  It's a good place to configure ``_G`` so that the rest of the Haxe code can work consistently.

**Comment by jdonaldson** [comment]
I think this is the best way forward for now.  I'll close this out, but feel free to reopen if there's another detail to address.
