### ISSUE TITLE
Binary format for eval?

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#8275]
I wonder if it might be possible to serialize typed AST (and reload it via some API)? I'm mostly looking to avoid parsing/typing macros.

**Comment by ncannasse** [comment]
typed AST is full of objects references to other types within the compilation context, so as it it's very much monolitic and it's very hard to serialize a part of it (like a single class) and reload it later by making it point to correct current context types which might not even be loaded at this point.

I would qualify the request as very hard to achieve for a quite limited gain, and propose it to be closed.

**Comment by nadako** [comment]
@Simn was experimenting with this though, I'm curious about the conclusions were made

**Comment by back2dos** [comment]
> making it point to correct current context types which might not even be loaded at this point.

Couldn't that be solved via TLazy though?

**Comment by Simn** [comment]
Designing the loader for something like this requires some thought because ultimately we have to replicate the typing passes here, at least to some extent.

**Comment by Simn** [comment]
I've been dealing with memory-related problems the last couple days and have come to the conclusion that our typed AST is quite heavy memory-wise. It should be worthwhile to investigate a binary format which we could store instead.

For context (64-bit system):

> The simplest texpr (`break` and `continue`) take 40 bytes. Something like `null` is 120 bytes. `args[0]` is 360 bytes, which causes flash's Type.createInstance to hit almost 100kb.

There should be ways to serialize this very efficiently. The expression kind can be encoded as a single byte, and we can keep track of positions by using some delta-approach. We can also investigate some hash-consing techniques, given that the reading part is supposed to be the efficient one.

I'm posting this here because whatever format we come with for the compiler cache can also be used for eval. It should be possible to serialize all this to disk and then publish it as part of a haxelib.

**Comment by Gama11** [comment]
This sounds like something that could potentially be used for more or less instant language server startup in the future too, if the cache is dumped to and loaded from disk. :)

**Comment by back2dos** [comment]
Some design effort was made in https://github.com/Aurel300/hxb/blob/master/FORMAT.md

With that repo around, I suppose there's not much of a point of keeping this issue open.
