### ISSUE TITLE
[discussion] remove AS3 target

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8295]
I think we should remove the AS3 target:
- i would be surprised if it's used by anybody at all
- it confuses newcomers that think that as3 output behaves exactly the same as swf output (while in reality it's a different target with its own quirks)
- SWF target fully covers AVM/Flash platform and has more freedom for generating efficient code (e.g. native iterators), not to say bytecode compilation is much faster
- it hinders improvements of SWF target (which is still useful and used), because of shared `flash` define and `std` files, so all changes made for SWF have to be adapted for AS3
- nobody seems to care about its state at all, but I'm sure _some_ people will be happy if it's gone

**Comment by RealyUniqueName** [comment]
It's probably too late to remove it in 4.0. Let's deprecate it and remove in 4.1

**Comment by Gama11** [comment]
You could also make the opposite arguments that it's exactly the right time though, because it's a major version that can have breaking changes like this. :)

**Comment by RealyUniqueName** [comment]
It's already two RCs deep into 4.0 :)

**Comment by Simn** [comment]
But nobody uses it.

**Comment by RealyUniqueName** [comment]
I'm fine with removing it.
Just saying that it could be a more graceful process. I bet somebody out there actually uses it :)

**Comment by ncannasse** [comment]
Let's add a warning for possible deprecation and reference this issue in the text, We will see if we get some feedback after RC3. Will still be time for removal for 4.0 final or postpone for later.

**Comment by m0rkeulv** [comment]
If you are removing targets, please try to make it more convenient to switch between Haxe versions so that developers that use the deprecated target can easily switch back and forth between Haxe 3 and 4.

 I also think it is a bit late to do this change as Haxe 4 previews has been available since late 2017, and could have been adopted by developers who need the AS3 output.

As a side note, I have always considered the fact that Haxe could output source files in different languages one of its primary strengths.

**Comment by Gama11** [comment]
@m0rkeulv Do you have a use case for the AS3 target that's not covered by the Flash target?

**Comment by m0rkeulv** [comment]
Not that I can’t use SWC/SWF files for myself,  but it would be convenient for generating sources for cross-platform API so that  anyone who uses the generated API/AS3 source files can fix bugs and/or troubleshoot themselves. 

As far as I know Smartfox2X (smartfoxserver.com) uses Haxe to generate their SWC file for Flash/Air target (it contains the Std,Lib and Boot classes) and its annoying not to have access to source files when issues or bugs occurs. ( the SWCs cant be decompiled and recompiled either due to Haxe optimizations)

**Comment by ncannasse** [comment]
There are existing SWC/SWF decompilers for that job.

**Comment by m0rkeulv** [comment]
The only Decompiler that i know of that is still in development is JPEXS Free Flash deompiler and it does not handle Haxes way of doing loops (`§§hasnext` and `§§nextname`) and pushing and popping from the stack (§§push,  §§pop()) very well.  Depending on how things are exported you may end up with a file where all local variables are `_locXX`, while you can modify the SWC directly it’s just inconveniently.

This is a snippet  from a class in  SFS2x API SWC and its not very decompiler and developer friendly.
```as3
package de.polygonal.core.fmt {
   public class NumberFormat {    
      public static var _hexLUT:Array = ["0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F"];
	  
      public function NumberFormat(){}
      
	  public static function toBin(param1:int, param2:String = undefined, param3:Boolean = false) : String
      {
         var _loc5_:int = 0;
         var _loc6_:int = 0;
         var _loc8_:int = 0;
         if(param2 == null)
         {
            param2 = "";
         }
         _loc5_ = param1;
         §§push(32);
         if(_loc5_ < 0)
         {
            §§push(0);
         }
         else
         {
            _loc5_ = _loc5_ | _loc5_ >> 1;
            _loc5_ = _loc5_ | _loc5_ >> 2;
            _loc5_ = _loc5_ | _loc5_ >> 4;
            _loc5_ = _loc5_ | _loc5_ >> 8;
            _loc5_ = _loc5_ | _loc5_ >> 16;
            _loc6_ = _loc5_;
            _loc6_ = _loc6_ - (_loc6_ >> 1 & 1431655765);
            _loc6_ = (_loc6_ >> 2 & 858993459) + (_loc6_ & 858993459);
            _loc6_ = (_loc6_ >> 4) + _loc6_ & 252645135;
            _loc6_ = _loc6_ + (_loc6_ >> 8);
            _loc6_ = _loc6_ + (_loc6_ >> 16);
            §§push(32 - (_loc6_ & 63));
         }
         var _loc4_:int = §§pop() - §§pop();
         var _loc7_:String = (param1 & 1) > 0?"1":"0";
         param1 = param1 >> 1;
         _loc5_ = 1;
         while(_loc5_ < _loc4_)
         {
            _loc5_++;
            _loc6_ = _loc5_;
            _loc7_ = ((param1 & 1) > 0?"1":"0") + ((_loc6_ & 7) == 0?param2:"") + _loc7_;
            param1 = param1 >> 1;
         }
         if(param3)
         {
            _loc5_ = 0;
            _loc6_ = 32 - _loc4_;
            while(_loc5_ < _loc6_)
            {
               _loc5_++;
               _loc8_ = _loc5_;
               _loc7_ = "0" + _loc7_;
            }
         }
         return _loc7_;
      }
```

and this would be the original haxe code (might be a newer version of the code).
```haxe
class NumberFormat
{
	static var _hexLUT = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F"];
	
	/**
	 * Returns a string representation of the unsigned integer <code>x</code> in binary notation.
	 * @param byteDelimiter a character to insert between bytes. The default value is an empty string.
	 */
	public static function toBin(x:Int, byteDelimiter = "", leadingZeros = false):String
	{
		var n = Limits.INT_BITS - Bits.nlz(x);
		var s = ((x & 1) > 0) ? "1" : "0"; 
		x >>= 1;
		for (i in 1...n)
		{
			s = (((x & 1) > 0) ? "1" : "0") + ((i & 7 == 0) ? byteDelimiter : "") + s;
			x >>= 1;
		}
		
		if (leadingZeros)
			for (i in 0...Limits.INT_BITS - n)
				s = "0" + s;
		return s;
}
``` 
https://github.com/Glidias/HashDS/blob/master/hx/de/polygonal/core/fmt/NumberFormat.hx

approximation of how it would look as AS3 (while a bit messy its somewhat readable and can be modified):
```as3
package de.polygonal.core.fmt {
	public class NumberFormat {
		
		static protected var _hexLUT : Array;
		
		static static_init function init() : void{
			de.polygonal.core.fmt.NumberFormat._hexLUT = ["0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F"];
		}
		
		
		static public function toBin(x : int,byteDelimiter : String = "",leadingZeros : Boolean = false) : String {
			if(byteDelimiter==null) byteDelimiter="";
			var n : int = 32 - de.polygonal.ds.Bits.nlz(x);
			var s : String = (((x & 1) > 0)?"1":"0");
			x >>= 1;
			{
				var _g : int = 1;
				var _g1 : int = n;
				while(_g < _g1) {
					var i : int = _g++;
					s = ((((x & 1) > 0)?"1":"0")) + ((((i & 7) == 0)?byteDelimiter:"")) + s;
					x >>= 1;
				}
			};
			if(leadingZeros) {
				var _g2 : int = 0;
				var _g3 : int = 32 - n;
				while(_g2 < _g3) {
					var i1 : int = _g2++;
					s = "0" + s;
				}
			};
			return s;
		}
```

Now to be clear, this is not a real problem for me as i got a working Haxe port of the API (https://github.com/m0rkeulv/smartfox-haxe-client) but its just a theoretical case/Example.

**Comment by RealyUniqueName** [comment]
Added a deprecation warning

**Comment by RealyUniqueName** [comment]
Since a warning has been added maybe move this issue to 4.1 milestone?

**Comment by jcward** [comment]
Interesting. I'm just now upgrading to haxe 4.1.4, and we're running into this, `Error: : unknown option '-as3'.`

Backstory, we started using the as3 target because:

- Our "1.0" app was originally AS3 for web, iOS and Android
- We started investigating Haxe and HTML5 support at the same time, and started the "2.0" project in Haxe targeting javascript.
- But we decided that we'd cross-compile parts of our framework from Haxe back to AS3 for use in the "1.0" product (in hopes that we'd eventually migrate the whole thing to Haxe.)

By and by, "1.0" is still AS3 (partially generated from .hx) and we plan to continue to use AIR SDK to target iOS and Android (and Chromebook via Android app).

Anyway, I'll see about a couple paths forward, either:
- try to compile the Haxe parts to .swc and use it in the AIR build.
- or maybe, use haxe <4.1 for the AS3 generated classes, and haxe >4.1 for the JS parts of the build... maybe `#if haxe_xxx` if there are issues with that?

Just commenting, in case anyone else lands here. Cheers!
