### ISSUE TITLE
[cpp] Not possible to extend an extern class?

### ISSUE THREAD

**Issue by akbcode** [HaxeFoundation/haxe#8300]
Is it not possible to extend a native C++ class from Haxe? I tried it but in the generated code _obj is suffixed to the actual name of the extern class. It doesn't compile.

Would be nice if we could extend an extern class but at least cpp generator should show an error if not possible.

**Comment by RealyUniqueName** [comment]
@hughsando Do extern classes expected to be extendable by Haxe classes?

**Comment by hughsando** [comment]
It is not possible to extend an external class from haxe - mainly because of GC and object ownership issues.  If haxe were to allocate the new class, then things like the constructor and destructor would not be called.  If the external system were to allocate the class, then the object would not be part of the GC system.
Possibly best to have an external object "owning" a haxe implementation and delegating the work to the haxe object.
