### ISSUE TITLE
Test suite for new display protocol

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8355]

**Comment by Simn** [comment]
The `haxe.display` package should now have all the types we need for this. Adding these tests should for the most part be a matter of creating a version of https://github.com/HaxeFoundation/haxe/blob/development/tests/display/src/DisplayTestContext.hx which utilizes the new protocol. This is likely going to require further abstractions though because several tests check for the concrete data at the moment.

We need more interns... :(

**Comment by Simn** [comment]
We have display tests in https://github.com/HaxeFoundation/haxe/blob/development/tests/server/src/DisplayTests.hx now. It's not the most convenient thing in the world, but the framework is there.
