### ISSUE TITLE
Allow else-less if in array literals.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#8363]
Say we have this code:

```haxe
function makeSalad() {
  var ingredients = [];
  ingredients.push(someLettuce());
  if (likesTomatoes) ingredients.push(someTomatoes());
  ingredients.push(someSalt());
  if (likesOnions) ingredients.push(someOnions());
  ingredients.push(someOil());
  return new Salad(ingredients);
}
```

I would much prefer to write this:

```haxe
function makeSalad()
  return new Salad([
    someLettuce(),
    if (likesTomatoes) someTomatoes(),
    someSalt(),
    if (likesOnions) someOnions(),
    someOil(),
  ]);
```

It's not a biggie, but the second version does have a lot less noise, and this would be kinda aligned with how if statements without else work in array comprehensions.

**Comment by grepsuzette** [comment]
Since it seems like a new construct, I will jump on the occasion to say I would like it even more as a postfix ;)
```haxe
function makeSalad()
  return new Salad([
    someLettuce(),
    someTomatoes() if (likesTomatoes),
    someSalt(),
    someOnions() if (likesOnions),
    someOil(),
  ]);
```

**Comment by RealyUniqueName** [comment]
No Perl here, please :)

**Comment by grepsuzette** [comment]
```haxe
var n : Int = switch color {
  case Black: 40;
  case Blue if (condition): 44;
  case _: 49;
}
```
Why should the above be Haxey and not a `var a = [Black, Blue if (condition)];`?

**Comment by RblSb** [comment]
@emugel you don't return `Blue` because `if` condition here. Also Haxe already has`[for (i in 0...10) if (i < 5) i]`. Personally i'm not sure this is how Haxe expressions works and this probably should not be allowed (looks like ternary operator without second part, or `try` without `catch`). At the other side this is fine sugar, mostly interested if this can be done easily for any expression to return "nothing" inside array/map initialization context for consistency.

**Comment by farteryhr** [comment]
consider the general ending: `var a=[for(i in 0...10) i, for(i in 100...110) if (i&1) i, if(Std.random(2)) 1]` ?

**Comment by Simn** [comment]
This would have to go through haxe-evolution. I don't like it very much because the nature of the typed expression is influenced by one of its elements. I bothers me that you can have a clean `EArrayDecl` to `TArrayDecl` translation, and then by adding an `if` somewhere in the element list it turns the entire thing into some `TBlock` mess.

However, I acknowledge that this is a very compiler-centric view of things and maybe usability concerns are more important here.

**Comment by Aurel300** [comment]
@back2dos Any chance you could put this as a proposal so it is not buried in the issues here?
