### ISSUE TITLE
[cpp] Sys.setCwd, .deleteFile, .deleteDirectory, FileSystem.exists, .rename fail on Unicode path

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8400]
This is not Windows specific!

```haxe
class Main {
  public static function main():Void {
    trace(Sys.getCwd());
    Sys.setCwd("\u0080");
    trace(Sys.getCwd());
  }
}
```

```bash
$ mkdir `printf "\xC2\x80"`
$ haxe --main Main --cpp out.cpp
...
$ out.cpp/Main
Main.hx:3: /cppcwd/
Main.hx:5: /cppcwd/
```

(`xxd` confirms it is the same path.)

`Sys.deleteFile` and `Sys.deleteDirectory`, `FileSystem.rename`, `FileSystem.exists` seem similarly affected.

Once fixed:

 - [ ] re-enable test marked with this issue number in `tests/sys/src/TestUnicode.hx`

**Comment by andreasdr** [comment]
Ok. Any plans when this will be fixed?

**Comment by andreasdr** [comment]
Hi,

we the SoccerTutor(https://www.soccertutor.com) devs really rely on Umlauts working with MacOSX/Windows/Linux and later Tablet.

So we like to offer a bounty to get this fixed, not sure if this is the right place here, but Ill ask here for it:
- 400 EUR If this is fixed and we get at least some instructions to build our Haxe versions(not the newest currently) with this fix applied for MacOSX/Windows/Linux
- 150 EUR BONUS if fixed by Tue 8th FEB

I am looking forward to hearing from you. Feel free to contact us using this email: andreas@drewke.net

Many thanx and 

Best regards
Andreas
