### ISSUE TITLE
Date.set* methods

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8486]
I'm wondering if there's a reason why Haxe `Date` API does not provide mutating methods like `setYear`, `setMonth`, etc. I quickly checked that JS and Flash both provide these and on other targets we provide our own implementations, so it should be possible to implement in a clean way.

If there are no objections, I could work on this.

cc @ncannasse

**Comment by back2dos** [comment]
Hmm. Until recently, I've considered dates immutable and kinda liked it that way. That's not to say that I'm totally against, because I can always define an immutable date type. At the same time turning a core type into something mutable is nothing to be sneezed at, because all code written against the assumption that it's consuming/returning/exposing something immutable now has this assumption broken and I'd say that's kind of a big deal.

**Comment by Aurel300** [comment]
A mild compromise would be to have the `set*` methods return a new instance, wasteful as it is.

**Comment by nadako** [comment]
OK, let's not dive into this now. I kind of need this because of some AS3 code I'm converting to Haxe, but there are ways to work this around.

**Comment by fullofcaffeine** [comment]
@nadako Would you mind elaborating here on what the workarounds are? For future reference.

**Comment by nadako** [comment]
> @nadako Would you mind elaborating here on what the workarounds are? For future reference.

It's of course hacky, but I'm thinking about having a static extension that provides missing methods like this:

```haxe
public static function setMonth(date:Date, month:Int) {
  #if (js || flash)
  // these ones have native API
  (cast date).setMonth(month);
  #elseif cpp
  // Date is a wrapper class around `Float`, so we can modify the internals
  @:privateAccess date.mSeconds = ...; 
  #end
  // other targets are similar
}
```
