### ISSUE TITLE
[cs] broken exception handling when using callback

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/haxe#8519]
During benchmark testing with formatter I found out that C# has an issue with catching exceptions thrown by a callback. I reduced my code down to a basic example:
```haxe
class Main {
	static function main() {
		run(throwsException);
	}

	public static function run(cb:Void->Void) {
		try {
			cb();
		} catch (e:String) {
			trace("caught " + e);
		}
	}

	public static function throwsException() {
		throw "my exception";
	}
}

```
expected output: "my exception caught"
C# output: "unhandled exception" + stacktrace

broken for both Haxe 3 and 4

**Comment by nadako** [comment]
Not a generator issue for once, but something in the `Runtime.callMethod` implementation.

**Comment by nadako** [comment]
So, `MethodBase.Invoke` wraps thrown exception in a `TargetInvokationException`, so we should do `try method.Invoke(...) catch (e:TargetInvokationException) throw e.InnerException`.

The problem is how to preserve stack trace without horrible hacks. With .NET 4.5 we can do `ExceptionDispatchInfo.Capture(ex.InnerException).Throw()`, but before that....

**Comment by nadako** [comment]
In general we should rework how method closures are created in C#, these should not go through reflection. I had a branch with the rework a couple years ago but never got it to work 100% due to some problems with access control.

**Comment by nadako** [comment]
> branch with the rework

I think that was it https://github.com/nadako/haxe/tree/gencommon_faster_method_closures
