### ISSUE TITLE
migrate off camlp4

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#8547]
camlp4 is no longer well maintained and it's not compatible with OCaml 4.08 right now.

## Why it's important

Our Haxe packages will be removed from every repositories that update to OCaml 4.08. Debian has OCaml 4.08 in the NEW queue to experimental, and I suppose the transition to 4.08 will begin soon. Ubuntu, which is based on Debian, will have its LTS release in April 2020. 

## Possible solutions

 1. Use something else.

 2. Help fix camlp4's OCaml 4.08 compatibility and probably take over its maintainance.

**Comment by Aurel300** [comment]
(Some of what we discussed in Slack:)

[PPX](http://ocamllabs.io/doc/ppx.html):

> OCaml 4.02 and OCaml 4.03 introduce the PPX system to replace Camlp4.

However, it seems that since we use [stream expressions](https://ocaml.org/learn/tutorials/stream_expressions.html) in [`grammar.mly`](https://github.com/HaxeFoundation/haxe/blob/development/src/syntax/grammar.mly#L25), we cannot switch _directly_ to PPX:

> NOTE: the stream expressions are based on camlp4, whose usage is discouraged in modern OCaml as it's incompatible with ppx (syntactic preprocessors).

(If we moved away from stream expressions, we could probably use an [automated converter](https://github.com/janestreet/camlp4-to-ppx).)

**Comment by nadako** [comment]
For the short term I would look for some alternative for port our RD-parser without changing everything.

**Comment by nadako** [comment]
> For the short term I would look for some alternative for port our RD-parser without changing everything.

Looks like [camlp5](https://github.com/camlp5/camlp5) might be an option. It's maintained, supports 4.08.1 and have similar [stream parsers](https://camlp5.github.io/doc/html/parsers.html) feature.

**Comment by nadako** [comment]
Uhm, looks like just replacing camlp4 with camlp5 already works? O_o I'll prepare a PR to check if I'm not crazy.

**Comment by nadako** [comment]
So we use camlp5 now :)

**Comment by andyli** [comment]
That took much shorter time to resolve than I thought. Thanks :D
