### ISSUE TITLE
[java] deprecated warning

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8557]
On latest dev build (camlp5)

```haxe
C:\HaxeToolkit\haxe\std/java/_std/sys/net/Socket.hx:43: characters 15-36 : Warning : Usage of this field is deprecated
```

**Comment by Aurel300** [comment]
What Java version are you running?

**Comment by Ilir-Liburn** [comment]
1.8.0_144

I got this warning by mistake, typing something what caused VS Code to import some module which I removed afterwards, I don't remember which module that was.

**Comment by Gama11** [comment]
I doubt the Java version is relevant? Perhaps the hxjava version, since that's where the .jar for the Java std lib lives.

**Comment by Ilir-Liburn** [comment]
hxjava is 3.2.0

**Comment by Simn** [comment]
It complains about `new java.net.Socket()`, but I don't understand what's deprecated there. [The API](https://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#Socket--) doesn't mention any deprecation for the empty constructor...

**Comment by RealyUniqueName** [comment]
Maybe meta from different overloaded fields is mixed somehow?

**Comment by Simn** [comment]
Ah good point, that must be it.

**Comment by Simn** [comment]
I can't find the issue, but the problem is simply that we don't represent constructor overloads in our AST. The compiler simply takes the first overload it finds and if that happens to have a deprecation attribute, we get a warning.

I'll probably gracefully fix this by not warning about deprecated constructors if they have overloads.
