### ISSUE TITLE
If block without else followed by inline markup

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#8565]
This breaks with `Invalid character 0x20` (long before getting to `Markup literals must be processed by a macro`):

```haxe
    var markup = {
      var foo = "foo";
      if (foo == "bar") {
        trace('.');
      }
    	<someMarkup />;
    };
```
(http://try-haxe.mrcdk.com/#0B3Fd)

I know inline markup is being reworked but this will probably still apply.

**Comment by Aurel300** [comment]
Slightly more minimal:

```haxe
if (true) {}
<someMarkup />;
```

**Comment by RealyUniqueName** [comment]
We need to decide on the final design for markup literals first.

**Comment by Simn** [comment]
I don't think this is related to the concrete syntax. Something goes wrong here due to the semicolon-else lookup, which is going to be an issue no matter which syntax we pick.

**Comment by Simn** [comment]
Right, due to the lookahead we lex both the `<` and the `someMarkup`. They are not removed from the stream, but are also no longer visible to the lexer. When the parser then comes across the `<` and wants to start lexing not-xml, the lexer no longer sees the `someMarkup` but the space after it and chokes.

I think we can soft-fix this by not using `npeek 2` directly, but checking for the `;` first and the `else` after. This way the lexer isn't gonna miss the identifier. Technically, we would have to re-insert the tokens into the lexer somehow, but that is probably very complicated and I don't think it's actually necessary.
