### ISSUE TITLE
Null access in haxe.crypto.Base64 static field init

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8583]
Since https://github.com/HaxeFoundation/haxe/pull/8571, the following happens when trying to compile [Flixel's unit tests](https://github.com/HaxeFlixel/flixel/tree/dev/tests/unit) through the compilation server:

![](https://i.imgur.com/lWBKsSs.png)

**Comment by JustinRyanH** [comment]
I've come across this while trying to run heaps with 4.0.0-rc3 on Ubuntu.

**Comment by Gama11** [comment]
Are you sure you're using rc.3 and not a more recent nightly build? The change that caused this is not in rc.3.

**Comment by Simn** [comment]
The problem is that in evalJit.ml we capture the prototype and it is then not initialized properly. This is not compatible with the lazy approach taken in #8571.

Conceptually, we want to make sure things are initialized when we first execute something. I think this would come down to dealing with it at the places we have `EKEntrypoint`.
