### ISSUE TITLE
[java] text corruption in Shift-JIS environment

### ISSUE THREAD

**Issue by malony0** [HaxeFoundation/haxe#8586]
```haxe
class Main
{
	public static function main():Void
	{
		//あ
		trace("\u3042");
	}
}
```
```
$ haxe --main Main --java bin
$ java -jar bin/Main.jar
```
in ver 4.0.0-rc3, this outputs the following in Shift-JIS environment.
(tested on Windows command prompt, code page:932)
```
Main.hx:7: 縺
```
Expected output is:
```
Main.hx:7: あ
```
compiled and tested with the same setting, but in ver 3.4.7.
​
I also tested with c# and python, but they worked fine.

**Comment by terurou** [comment]
This code works fine in Haxe 4.0.0-rc.2.

**Comment by Aurel300** [comment]
I am pretty sure this comes from setting stdout and stderr to UTF-8:

https://github.com/HaxeFoundation/haxe/blob/f244bb85b6fc71353634e3ff8fbb80d24478c4e2/std/java/Init.hx#L27-L28

This makes it more likely Unicode output will work (even when the Windows console or pipe is not in the correct codepage). Unfortunately it also ignores the codepage if it was actually set correctly to something incompatible with Unicode.

I don't know how to fix this properly because Unicode et al. are a mess on Windows IMHO. What you can do is:

 - use a Unicode environment in the console (= Unicode-compatible fonts, code page 65001)
 - replicate the two lines linked above at the start of your program, but replace `"utf-8"` with `"ms932"`, or perhaps `"shift-jis"` - see also https://stackoverflow.com/questions/37155417/string-encoding-conversion-utf-8-to-shift-jis

**Comment by terurou** [comment]
This issue is VERY BAD in Windows/Japanese environment. 
Please make encoding setting opt-out. (eg. `-D java_encoding_auto` )

**Comment by Simn** [comment]
This seems a bit tricky because either way we end up with something that doesn't work by default. I'm not sure if the setting to utf-8 should be opt-out or opt-in. Technically, you can already opt-out anyway by manually resetting the encoding at the start of the program, as @Aurel300 mentions.

**Comment by Simn** [comment]
I forgot about this one. I think we have to do something for 4.0 here or at the very least document a workaround.

**Comment by RealyUniqueName** [comment]
I'm not very familiar with java, but do we really need to explicitly set utf8? Afaik we don't do it for other targets. It's up to user to setup an environment where a program runs or up to a developer of each specific app to detect an environment.

**Comment by Aurel300** [comment]
@RealyUniqueName I made changes to other targets that are similar, i.e. setting the output stream mode to UTF-8. Maybe it's not the prettiest, but Windows environments seem to be years behind in terms of proper Unicode support, so just telling users to "setup an environment" is not good imho.

I agree we can have a `-D disable-auto-utf8-stream` (suggestions for a better name welcome) and simply wrap the stream settings in `#if !disable_auto_utf8_stream`.

**Comment by Simn** [comment]
I'm a bit worried that having such a setting by default is really bad practice. Maybe we should ask some real Java devs what they think about this.

**Comment by RealyUniqueName** [comment]
Forced encoding also causes https://github.com/HaxeFoundation/haxe/issues/8772
