### ISSUE TITLE
How can I upgrade the opam haxe pin?

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#8603]
So I followed BUILDING.md to configure my build environment with the pinned haxe package. Installing works fine. But how can I upgrade this pinned package?
`opam upgrade haxe --deps-only` doesn't work
`opam upgrade haxe` tries to upgrade the whole package (not just the deps)
`opam upgrade` upgrades everything to the newest version (incl. an incompatible `sedlex`)
Right now I do `opam upgrade` followed by `opam install haxe --deps-only`, which sets sedlex back to the needed version. Is there a better way? I haven't found anything in the opam docs...

**Comment by andyli** [comment]
I think a `opam update` (not to be mistaken with `upgrade`) will sync the pin as well as prompt you to upgrade/rebuild the deps.

**Comment by mockey** [comment]
`opam update`syncs the pin, but does not upgrade anything. It says: `Now run opam upgrade to apply any package updates`...
It seems that there is no `--deps-only` option for `opam upgrade`.
With `opam upgrade haxe` I get: `haxe is not installed. Install it?`. I guess the install entry from the opam file would be run then (`make install`).

**Comment by andyli** [comment]
Ah, now I understand the problem. I guess what we're doing here is not a major use case in opam.
People usually actually install the pinned package instead of just `--deps-only`. So maybe if you're not hacking around the haxe source code, it may make more sense to `opam install haxe`, which will add haxe to PATH when `eval $(opam env)`, which can be added to your .bashrc if you want. In that case, `opam update/upgrade` will respect the haxe opam file because you actually installed it.

**Comment by mockey** [comment]
So `opam upgrade` would build haxe then in the `~/.opam` directory?
I don't know, I think I'd prefer to have haxe in my own PATH separate from opam, maybe I'll try `opam install haxe --fake`...

**Comment by RealyUniqueName** [comment]
Doesn't look like we need to do something here. Feel free to reopen if I'm wrong.
