### ISSUE TITLE
Switch to another parser instead of Camlp5

### ISSUE THREAD

**Issue by XVilka** [HaxeFoundation/haxe#8615]
See these discussions:
- https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985
- https://discuss.ocaml.org/t/the-end-of-camlp4/4216/2

For example Menhir, Sedlex, Angstrom, or others.

**Comment by Simn** [comment]
We have no plans to move the parser to another implementation during Haxe's OCaml lifetime. I don't think there's even a need to discuss this at the moment. There was a previous attempt to move to a menhir implementation, but that turned out to be infeasible for various reasons.

_If_ someone actually wants to work on an alternative implementation, I'd be happy to help. However, in my experience nobody has the necessary amount of time and skill to actually come through with that.
