### ISSUE TITLE
[display] too much stuff

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8639]
Toplevel completion currently sends insane amounts of data if there are some native libraries involved. While the compiler can handle that fine, consumers of the output may struggle quite a bit.

We have to look into filtering the results if the amount of display items exceeds X (configurable). The IDE can then re-request upon input change, and the compiler just has to re-filter.

The filtering itself requires some thought too. 

This kinda blocks #8638.

**Comment by EricBishton** [comment]
I'm going to throw a straw-man idea out here...

What if the filtering were user-defined?  Meaning, of course, tool-defined?  The filter could be passed in as Haxe code that can be eval-ed during display requests.

Advantages:
 - Always what the tool requires - no need to guess at the filtering strategy.
 - Reduce bandwidth (which we get with any reduction strategy).
 - Filters can be arbitrarily complex.
 - Perhaps the type of data and format (e.g. compressed-not-JSON) can be determined by the filter and/or requesting tool.

Some issues with this:
 - Authors of filters will eventually want to keep context.  (e.g. `numberPassed < 1000`, or `if (requestedPage *pageSize > rowId && (requestedPage) +1 * pageSize < rowId) includeInfo(); else...`)
 - Potentially, lots of code paths to test and support.  (Of course, eval will be better debugged!)
 - Potentially opens compiler-specific information to the tool builder.
 - Badly written filters will run slower than broadcasting all of the data.
 - Eval performance becomes more critical.
 - Eventually, authors will want filters run at "search" time, rather than just "format results" time, to speed up or (terminate early) display response.  (Design, in theory, but don't implement at first.)  This is more interesting in terms of specific searches that currently have to wade through mountains of data to get a small answer.

To implement:
 - Add an argument to the compiler only useful during display access.  Could point to a file??
 - Initially, runs only at "format results" time.

So, I am less interested in hashing out this with comments to this issue than I am with seeding your brains with an idea.  (I don't think this feature should require a haxe-evolution PR to get off the ground.)

**Comment by Gama11** [comment]
That sounds incredibly over-engineered...

**Comment by EricBishton** [comment]
Well, it's the (or one) natural evolution of the thought: this could be solved with a callback, but how do we get one into the compiler?

Like I said, I'm just trying to help think of solutions.  Be they bad, too complex, or whatever.  They should be rejected if better (or simpler) solutions present themselves.
