### ISSUE TITLE
Array.each

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8678]
Now that `map` cannot be used with a `Void`-returning function, let's have a `each` (or `forEach`).

```haxe
public inline function each(f:T->Void):Void {
  for (el in this)
    f(el);
}
```

**Comment by Gama11** [comment]
Considering we've been waiting on `Array.contains()` since at least 2014 (https://github.com/HaxeFoundation/haxe/issues/3323) because of reflection / `Dynamic`, this doesn't seem like something that can be added as an inline method just like that.

Also, some would say this encourages bad style, a famous blog post on the topic:
https://blogs.msdn.microsoft.com/ericlippert/2009/05/18/foreach-vs-foreach/

**Comment by Simn** [comment]
We are unlikely to extend the Array API anytime soon for various reasons. If you prefer this style, you can always use it via a static extension.
