### ISSUE TITLE
Hl performance issues

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8699]
just compare this code run in Neko and HashLink 

Neko target only cost <1% CPU

![image](https://user-images.githubusercontent.com/748320/63694342-ccc25880-c848-11e9-9d1b-57e0961f0a35.png)

but HashLink cost more than 99% cpu.

![image](https://user-images.githubusercontent.com/748320/63694264-9dabe700-c848-11e9-9edc-1cc481243c1b.png)

	
       package;
	import haxe.MainLoop;

	using Lambda;

	class Main {
		static function main() {
			trace("Hello, world!");

			MainLoop.addThread(function() {
				while (true) {
					Sys.sleep(10);
					trace(" hi");
				}
			
				
			});
		
		}
	}

**Comment by sonygod** [comment]
Linux Ubuntu  18.04

![image](https://user-images.githubusercontent.com/748320/63694408-fa0f0680-c848-11e9-8f94-8c4f3bb3434c.png)

**Comment by Aurel300** [comment]
It looks like HL is busy-waiting there. Will be fixed with new threads in 4.1.

**Comment by sonygod** [comment]
@Aurel300  will you fix as soon as possible? because current our game server uses hl as the Main target.

**Comment by Aurel300** [comment]
I can't see what the bug really is. The `sys_sleep` implementation in HashLink seems fine, not busy-waiting. Could be related to `MainLoop` @ncannasse

**Comment by jonasmalacofilho** [comment]
The issue seems to be on the main thread.

No idea what goes on there, but taking a quick look I see that `MainLoop` (or more specifically `EntryPoint`) calls `Lock.wait` and busy waits there.

```haxe
	public function wait(?timeout:Float):Bool {
		if (timeout == null) {
			deque.pop(true);
			return true;
		}
		var targetTime = haxe.Timer.stamp() + timeout;
		do {
			if (deque.pop(false) != null) {
				return true;
			}
		} while (haxe.Timer.stamp() < targetTime);
		return false;
	}
```
—[`/std/hl/_std/sys/thread/Lock.hx#L33`](https://github.com/HaxeFoundation/haxe/blob/2398ac5c57194ab9477ca0109cb85a7c39a485f0/std/hl/_std/sys/thread/Lock.hx#L33)

Another thing I noticed is that `MainLoop.tick` will return 1e9 "ticks" if there are no events left, and that value ends up being used as the timeout for `Lock.wait` in this example.  But I don't know if/how this matters.

**Comment by ncannasse** [comment]
Yes I confirm the issue comes from invalid sys.thread.Lock implementation in HL.
Fixing it would requiring porting the lock_* primitives from neko here (https://github.com/HaxeFoundation/neko/blob/master/libs/std/thread.c#L336) to HL sources here (https://github.com/HaxeFoundation/hashlink/blob/master/src/std/thread.c)

**Comment by sonygod** [comment]
@ConstNW  will you have a look this issue?

**Comment by sonygod** [comment]
@Aurel300 @ncannasse  why put this issue to 4.1?  why not be fixed as soon as possible?

**Comment by sonygod** [comment]
current I return to use Nekovm as my game server instead of HashLink. it's low performance and hight 

cpu cost !

**Comment by sonygod** [comment]
thank you so much, it's fixed . and I need more tests and confirm to close.
![image](https://user-images.githubusercontent.com/748320/64190544-370e7500-cea9-11e9-8b72-a8fdb1f63c45.png)

**Comment by sonygod** [comment]
@ConstNW it seems only improve  on  Linux  performance, but Windows still cost lot's CPU 

and *.hl build from Windows then run in Linux still cost CPU like before?

**Comment by ConstNW** [comment]
@sonygod, no. on windows problem also fixed. try to compile with flag `-D hl-ver=1.11`

**Comment by sonygod** [comment]
but current Hashlink version is 1.10  only.
C:\HaxeToolkit\haxe\std/hl/_std/String.hx:211: characters 8-14 : Invalid version string "1.11". Should follow SemVer.

**Comment by Aurel300** [comment]
I think you might have to specify `-D hl-ver=1.11.0` ?

**Comment by sonygod** [comment]
@Aurel300 yes, it's ok
