### ISSUE TITLE
[macro] haxe.macro.Context.getExpectedType()

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#8745]
Hej,
I'm sorry I don't know if it's a bug, I've made many tests to understand how does it work macro with type inference and I can't understand if it's a normal behaviour or a bug. And I would ask if it would be possible to get the real expected type on the left side.

```haxe
class Tools {
  macro public static function get(e){
    trace( haxe.macro.Context.getExpectedType() );
    return e;
  }
  
  public static function foo<T>(e:T):T{
    return e;
  }
}
```

```haxe
using Tools;

class Test {
  static function main() {
    var n : Int = 5.get();			// TAbstract(Int,[])
    var n2 : Int = 5.get().foo();		// null
    var n22 : Int = (5.get():Int).foo();	// TAbstract(Int,[])
    var n3 : Int = Tools.get( 5 ).foo();	// null
    var n4 : Int = Tools.foo( 5.get() );	// TMono()
    var n5 : Int = Tools.foo( Tools.get( 5 ) );	// Tmono()
  }
}
```
We can test it here : http://try-haxe.mrcdk.com/#aD52d

**Comment by Simn** [comment]
This is working as intended. For instance, the expected type of `5.get().foo()` as a whole is `Int`, but there is no expected type for the sub-expression `5.get()`, which is the macro call. Expected types are not promoted to sub-expressions in most cases because they don't apply to them. We don't expect the `5.get()` to be an `Int`.

**Comment by filt3rek** [comment]
Thx @Simn for your answer.
There isn't any way to get what I want please ?
