### ISSUE TITLE
Strict null safety mode for single-threaded code

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8895]
`Strict` mode assumes (class?) variables can be changed by other threads. It would be nice to have a strict mode that is strict, but assumes a single-threaded application.

**Comment by back2dos** [comment]
AFAIK there are rather serious plans to add coroutines or the like in the foreseeable future, which means anything can be concurrent. Perhaps this can be fully handled by making sure null safety runs after the suspension related transformation, but it seems like the first step in digging a deep hole.

**Comment by Aurel300** [comment]
@back2dos Coroutines are not automatically multi-threaded though.

**Comment by back2dos** [comment]
They don't need to be multi-threaded to be concurrent. What matters is that execution may be suspended between the null check and the 2nd access, and any other coroutine (quite possibly running on the same thread) could potentially do any amount of things to said field. I don't know how much implicitness regarding suspension we're going for in the end, but from what I remember it was quite a bit, so it's something to be aware of.

Personally I think we should promote `switch` as the idiomatic way of dealing with strict null safety, because it solves a whole range of other problems too.

**Comment by Aurel300** [comment]
Ah, I see what you mean. But still, a coroutine suspension does not happen randomly, it happens at a function call. Does null-safety currently assume any function call havocs fields?

**Comment by Simn** [comment]
Coroutines should not be a special case if null-safety runs after it.

**Comment by ncannasse** [comment]
Yes, null safety operates once the code is transformed into final Ast, so
they will be automatically taken into account. OTOH this might require some
extra work because we have no way to ensure that some cases in the switch
will get executed before others and thus that some variables will get
initialized before access.

**Comment by RealyUniqueName** [comment]
Now I think null safety should be executed before coroutines.
Because here it's clear which vars are local and when they get initialized (pseudocode)
```haxe
function suspendable() {
  var a;
  suspend();
  a = 'hello';
  suspend();
  trace(a.length);
}
```
but here it's not obvious for null checker anymore:
```haxe
function suspendable() {
  switch(state) {
    case 0:
      suspend();
    case 1:
      loclals.a = 'hello'; 
      suspend();
    case 2:
      trace(locals.a.length);
  }
}
```
Depending on coroutines implementation locals can be captured into a coroutine body closure or stored as fields of some object.
In both cases they can't be considered safe after a check against null in strict mode.
