### ISSUE TITLE
@:pure functions and memoization if reusal in descendant scope?

### ISSUE THREAD

**Issue by grepsuzette** [HaxeFoundation/haxe#8931]
I haven't been able to find a lot of documentation about `@:pure`, only what `haxe --help-metas` says about it.

Therefore I don't know if it's simply an annotation and nothing else, or what exactly are the plans for it; but I would like to ask if it could do memoization later:

_Exampli gratia_:
```haxe
class T {
    public static function main() {
        trace(costly_operation(4));
// following result could/Should be reused by compiler
// because @:pure + same inputs => same output
        trace(costly_operation(4)); 
                                            
        trace(costly_operation(3));
    }

    @:pure public static function costly_operation(n:Int) : Int {
        return n + 1;
    }
}
```
The main reason is practical. 90% of cases it would save you the trouble of declaring a `var myVar = costly_operation(4);`, which is always a pity when you do a lot of one line functions and that you have to add `{` and `}` because the function now takes two line...

It would be neat if the compiler could memoize those (i.e. if a pure function is used more than once in a given scope with the same exact parameters (therein probably lies the difficulty and it would require to really think about what makes a variable immutable)).

For very expensive calls we can already use caching, lazy systems and so on, but the memoization would be very transparent to us and would encourage using more pure functions.

**Comment by Simn** [comment]
Something like this is way more involved and would have to go through haxe-evolution. I don't have high hopes for it though because the concept is fairly high-level and thus difficult to analyze.

**Comment by Aurel300** [comment]
I think locally this would not be extremely difficult, if considering immutable types – keep a table of calls to pure functions when compiling/analysing a function, indexed by the function + its arguments. When you find a call that is already in the table, memoise.

For mutable values it might be a bit different though. E.g. `Bytes.ofString` is declared `@:pure`. I assume this means it does not modify the argument or the state of the program at all, besides allocating a new `Bytes` instance. But of course, if you memoised and reused the same `Bytes` instance from two different calls, you would have a bad time, since modifications to one would result in modifications to the other.

https://github.com/HaxeFoundation/haxe/blob/91dc4be111f3e521e2c5219b76d328a779f30ac9/std/haxe/io/Bytes.hx#L579-L582

**Comment by grepsuzette** [comment]
That `@:pure` in `haxe.io.Bytes` was added by @Simn in  503ac64ce40c50664dd31a89de603753de46c5fe with one change in `analyzer.ml` in 2016. I really don't understand what it does. You probably found one really interesting example here.

Before I or someone else make a proposal, would it be possible to clarify what is the purpose and behaviour of @:pure right now? If we close the issue now it is not ideal to gather some more thought or information.
