### ISSUE TITLE
Provide Haxe Linux builds via Snapcraft

### ISSUE THREAD

**Issue by TheHippo** [HaxeFoundation/haxe#8936]
After reading @andyli [explaining on Twitter](https://twitter.com/andy_li/status/1191947169688887298) why the newest Haxe build for Linux take that long I remembered `snap`. [Snapcraft](https://snapcraft.io/) is package management system that works on the most common Linux distributions and would provide an easier way to get Haxe to all the Linux users.

**Comment by andyli** [comment]
I have looked at snap multiple times, but it isn't the magical solution for us at the moment.

Snap isn't universally useable. For instance, it can't be used in containers or WSL 1.

If there is no Haxe package in a repo, that will prevents any Haxe-built software getting into the repo, because packages can only depends on packages in the same repo.

I can additionally create a Haxe snap, but that will just be another thing for me to maintain. But if you or anyone want to step up to create and maintain such (official) Haxe snap, I can offer help.
