### ISSUE TITLE
[tre] tre vs compiler cache vs overrides

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8953]
Base.hx
```haxe
class Base {
	function f() {
		f();
	}
}
```

compile using compiler cache, the tail recursion will be optimized. then if we add a subclass in another module without touching `Base` module:

Child.hx
```haxe
class Child extends Base {
	override function f() {}
}
```
...and compile again, the TRE won't be cancelled.

this is because `Tre` filter is run before state save, so I guess it should be run after :-P

PS maybe it even makes sense to run it post-DCE so we can enable TRE if we *had* an override, but it was removed by DCE

**Comment by RealyUniqueName** [comment]
State save is executed after the analyzer. That means if tre is moved after state save, it couldn't benefit from various cleanups for #8952, #8950 and #8954 
@Simn is it ok to run the analyzer again for tre-affected methods after `save_class_state`?

**Comment by RealyUniqueName** [comment]
Changed TRE to not apply to non-final instance methods for now.
However, local named functions get TRE'd even inside of non-final instance methods.

**Comment by RealyUniqueName** [comment]
Closing this because I don't think we will lift those restrictions in a foreseeable future. 

Currently TRE is applied to:
* `final` methods
* `static` methods without `dynamic` access modifiers
* `inline` methods (however, inlining mostly happens _before_ tre is applied)
* local named functions
* `final fieldName = function() { /*...*/; fieldName(); }`
