### ISSUE TITLE
StringTools.endsWith unicode issue on haxe 4 cpp target

### ISSUE THREAD

**Issue by codeservice** [HaxeFoundation/haxe#8980]
On haxe release 4.0.2 windows 64 bit environment, included code compiled  for cpp target:

```haxe
trace(StringTools.endsWith("123\n","\n"));
trace(StringTools.endsWith("μου\n","\n")); //issue
trace("μου\n".charCodeAt(3));
```

produced result: true, **false**, 10

**Comment by Simn** [comment]
@hughsando This reproduces for me, could you check it?

**Comment by Shallowmallow** [comment]
Seems to be stil the case 4.0.5

On C  targets  (linux , android)


if you do

```haxe
trace(StringTools.endsWith("région_cercle", cercle));
```

it says false. On html5 it works.

**Comment by jeremyfa** [comment]
Reproducing the issue as well on cpp with haxe 4.

**Comment by Simn** [comment]
I just checked again and it still reproduces with latest Haxe and hxcpp.

@hughsando Anything we can do here?

**Comment by dmitryhryppa** [comment]
Looks like there is a typo in `StringTools`.  Probably this part: https://github.com/HaxeFoundation/haxe/blob/development/std/StringTools.hx#L258-L265

should be: 
```haxe
		if (s.length < end.length)
			return false;
		var from = s.length - end.length;
		var p0 = s.c_str();
		var p1 = end.c_str();
		for (i in from...end.length)
			if (p0.at(i) != p1.at(i))
				return false;
		return true;
```

**Comment by Aurel300** [comment]
@dmitryhryppa No, that would be wrong. You'd be indexing `p1` (the `end` string) using indices that might only be valid in `p0` (the `s` string). The original `var p0 = s.c_str().add(s.length - end.length);` offsets the C string pointer by `s.length - end.length` bytes, so in the loop `p0.at(i)` is the same as `s.c_str().at(s.length - end.length + i)`.

However, there *might* be a problem there. `add` offsets by bytes. But on the Haxe side, `s.length - end.length` is probably calculated in characters rather than bytes. It should be something like `var p0 = s.c_str().add(s.byteLength - end.byteLength)`, where `byteLength` would refer to the actual `hxString` `length` member. Is that right @hughsando ?

**Comment by posxposy** [comment]
@Aurel300 Yep, true. I deleted my suggestion but looks like you managed to see it :D
Here is a bit dirty option:
```haxe
		if (s.length < end.length)
			return false;

		var p0 = s.c_str();
		var p1 = end.c_str();

		var sLength = untyped __cpp__("strlen({0})", p0);
		var endLength = untyped __cpp__("strlen({0})", p1);

		p0 = p0.add(sLength - endLength);
		for (i in 0...endLength)
			if (p0.at(i) != p1.at(i))
				return false;
		return true;
```

**Comment by Aurel300** [comment]
The cpp side already knows the byte length of the string, so `strlen` is unnecessary (and potentially slow).

**Comment by posxposy** [comment]
@Aurel300
> The cpp side already knows the byte length of the string, so `strlen` is unnecessary (and potentially slow).

Ah, good to know.
I've just meant, that counting bytes length looks like a working solution.
