### ISSUE TITLE
[display] diagnostics break hover (or something)

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8991]
Finally was able to find time to prepare a proper test case for a thing that was annoying me a lot past couple weeks:

```haxe
	function test() {
		var mainHx = 'class Main {
	static function main() {
		C.inst{-1-}ance;
	}
}';
		var cHx = 'class C {
	public static var instance:Int;
}';
		var mainHx = Marker.extractMarkers(mainHx);
		vfs.putContent("Main.hx", mainHx.source);
		vfs.putContent("C.hx", cHx);

		runHaxe(["--no-output", "-main", "Main"]);
		runHaxeJson([], DisplayMethods.GotoDefinition, {file: new FsPath("Main.hx"), offset: mainHx.markers[1]});
		runHaxe(["--display", new FsPath("C.hx") + "@0@diagnostics"]);
		runHaxeJson([], DisplayMethods.Hover, {file: new FsPath("Main.hx"), offset: mainHx.markers[1]});

		var result = parseHover().result;
		trace(result);
		Assert.equals(DisplayItemKind.ClassField, result.item.kind);
	}
```

commenting `runHaxe(["--display", new FsPath("C.hx") + "@0@diagnostics"]);` will make it pass.

regression since haxe 4.0 release :-P

**Comment by Simn** [comment]
Some more details because this is slightly tricky: The texpr-display mode just used `find_module` and didn't account for the possibility of a module's dependency being invalidated, which is something we usually resolve on-lookup instead of on-invalidation. By going through `type_module_hook` we end up in server.ml `type_module`, which does the usual dependency invalidation checks.
