### ISSUE TITLE
[eval] debugger doesn't respect custom toString()

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9036]
```haxe
class Main {
	static function main() {
		var p = new Point(0, 0);
		trace(p);
	}
}

class Point {
	public final x:Int;
	public final y:Int;

	public function new(x, y) {
		this.x = x;
		this.y = y;
	}

	function toString() {
		return '($x, $y)';
	}
}
```

In the debugger, it just shows the class name rather than the custom `toString` representation - I'm fairly sure this used to work at some point? Maybe this is a special case for some reason though.

![](https://i.imgur.com/SoIXuwl.png)

The trace outputs `(0, 0)` as expected, so it can't be DCE. Doesn't seem like it could be something on the VSCode end either, as the `Point` class name has to come from the eval debugger.

**Comment by nanjizal** [comment]
This has been changed for a long time I think, I certainly gave up on relying on my own toString methods to be called.

I am not sure if it was discontinued due to a possible overhead of calling Haxe toString, but there is an easy work round.
``` haxe
trace( Std.string( p ) );
```
For js target you can toggle behaviour by just overriding trace.
``` haxe
import js.Browser;
class Main {
	static function main() {
                haxe.Log.trace = function( v : Dynamic, ?inf : haxe.PosInfos ) 
                           Browser.console.log( Std.string( v ) );
		var p = new Point(0, 0);
		trace( p );
	}
}
class Point {
	public final x:Int;
	public final y:Int;

	public function new(x, y) {
		this.x = x;
		this.y = y;
	}
    public
	function toString() {
		return '($x, $y)';
	}
}
```
It's likely quite similar for all targets. If there is an overhead, or serious problem with modifying existing trace then the alternative would be to update the documents with work round example or provide a compiler flag.

**Comment by Gama11** [comment]
@nanjizal This issue is not about traces. The problem you describe is just Haxe's trace implementation being DCE'd ("hello world optimization"), I think.

**Comment by Simn** [comment]
The problem here was that the `toString` call was attempted in the debugger thread, which isn't set up to execute any code (no call stack etc.). I've changed it so the code is executed in a temporary thread, which is also what we do for some other debugger operations that run code.

We still have no debugger tests for this so it might break again... feel free to look into that next time you're bored.
