### ISSUE TITLE
Using Reflect.getProperty() different for functions between targets

### ISSUE THREAD

**Issue by AustinEast** [HaxeFoundation/haxe#9068]
The hashlink target seems to use Reflect.getProperty()  on functions differently than other targets.

I boiled it down to this test case:
```haxe
class Test {
    static function main() {
        var f = (i) -> {
            1++;
        };
        
        trace(Reflect.getProperty(f, "length"));
    }
}
```
When I test on hashlink, reflecting the length of the function returns `null`, but on all other tested targets it returns `1`.

**Comment by Gama11** [comment]
I'm not sure why you expect this to work, Haxe has no concept of a "function length". You're relying on unspecified target-specific behavior here, 

Also, it seems to fail on more targets than not, the only ones where it seems to work are JS and Flash. Besides HashLink, it does **not** work on Cpp, Cppia, Neko, Python, Java, JVM, C#, PHP and Eval either.

**Comment by nanjizal** [comment]
Javascript has long allowed properties and functions to be attached to functions and Flash you can do anything using some carefully placed brackets with a string within, and it has prototype origins. This is a feature found in some dynamic untyped/partially typed languages, it is not something that I would expect supported by Haxe as it's dynamic behaviour and inconsistant with Haxe's more rigorous typed approach.  Potentially you maybe able to implement in Neko ( I really have no idea ) as Neko internally is more dynamic than HashLink, but certainly not suited to highly typed HashLink.

It could be argued that the behaviour should be disabled for Flash/JS targets but likely it's not worth the effort and hard to enforce, but certainly one that is at odds with Haxe approaches and one you should try to avoid on the basis it goes against the spirit of Haxe.

If you favour this type of behaviour then I would suggest you look at moving to language like Ruby for backend and revert to working with JS directly.  The behaviour is fun but totally at odds with Haxe philosophy, it's a language choice - clear typed languages or prototype/dynamic with duck typing.  Totally agree with Gama11 closing issue, your asking for a feature that is at the other end of the programming language spectrum and not appropriate.

AustinEast if you have not explored the differences, I strongly suggest you read 
http://ruby-doc.com/docs/ProgrammingRuby/
and perhaps a book like
https://www.amazon.co.uk/Real-World-Functional-Programming-Tomas-Petricek/dp/1933988924
as they should help clarify the very different perspectives of programming.

There are probably more recent books but certainly Haxe is a functional leaning language with OOP and some pragmatic aspects rather than pure object/prototype language like JS or Ruby. Just felt it was important to clarify why I don't think your request is even suitable for Haxe to entertain.

**Comment by AustinEast** [comment]
@Gama11 I’m not the one who’s doing it this way haha - I originally ran into the issue from using the signals lib (problem code here: https://github.com/peteshand/signals/blob/master/src/signals/Signal.hx#L196). I suppose I’ll open an issue over there instead.
