### ISSUE TITLE
[Feature Request][Breaking Change] haxe.http.Http request() should not be defined as POST or GET only

### ISSUE THREAD

**Issue by Jarrio** [HaxeFoundation/haxe#9072]
This should be an abstract enum with a default property at best, the current implementation only allows users to `POST` or `GET` and because this isn't a sys target `customRequest` isn't actually available but that shouldn't really influence the difference.

```
GET
POST
PUT
HEAD
DELETE
PATCH
OPTIONS
```
and the usage should ideally be:

```haxe
var http = new haxe.Http('api_url');
http.request(DELETE);
```
The current implementation forces users to use other libraries when it's really not required and the proposed changed would be a more complete experience in general

**Comment by Simn** [comment]
We aren't gonna break the Http class like this. If you would like to develop a modernized API, I recommend doing it as a haxelib.

**Comment by Jarrio** [comment]
Can we compromise and expose a universal `customRequest` method for the http side of things? The functionality shouldn't be completely hidden away at the minimum

**Comment by nanjizal** [comment]
@Jarrio maybe this is relevant:
https://github.com/nanjizal/hxTShopify/blob/master/src/hxTShopify/connection/Https.hx#L95
https://2.python-requests.org/en/master/
Also check Tink solutions.

**Comment by Jarrio** [comment]
@nanjizal Yeah, for this particular usecase I'm defaulting to the hsnodejs implementation and i'm actually already using tink and want to remove it because it adds 15,000+ lines of code to my output which I *really* do not need.

Fair enough adjusting the default API for something as big as `haxe.Http` is a no go but i'm not sure why only the sys target has implemented the ability for `Http` to gain access to a `customRequest` it seems like the API is incomplete without it for all the major targets.

**Comment by nanjizal** [comment]
@Jarrio I don't know I think they are working on nodejs sys and async stuff at the moment.
Meanwhile perhaps this is useful if your working with nodejs.
https://github.com/nanjizal/folderNode/

**Comment by back2dos** [comment]
> already using tink and want to remove it because it adds 15,000+ lines of code to my output which I really do not need.

Whoops. If this is so, it has me rather alarmed. I get quite different numbers:

```haxe
#if !std
using tink.io.Source;
import tink.http.Request;
#end
class Main {
  static function main() {
    #if std
    var http = new haxe.Http('http://example.com/');
    http.onBytes = function (s) trace(s);
    http.onError = function (s) trace(s);
    http.request();
    #else
    var client = new tink.http.clients.NodeClient();
    client.request(new OutgoingRequest(new OutgoingRequestHeader(GET, 'http://example.com/', '', []), ''))
      .next(res -> res.body.all())
      .handle(o -> trace(switch o {
        case Failure(e): e.message;
        case Success(c): c.toString();
      }));
    #end
  }
}
```

With haxe 4.0.5 I get the following `haxe -main Main -lib hxnodejs -lib tink_http -js out.js -dce full`:

- 399 lines with `-D std`
- 2048 lines for tink

So what I observe is closer to stdlib than to the 15K you're getting. Any hints on how to get it to generate as much code as you have?

**Comment by Jarrio** [comment]
@back2dos This is also on haxe 4.0.5
```haxe
import tink.http.Client;

class Main {
	static function main() {
		Client.fetch('http://google.com').all().handle((status) -> {
			switch (status) {
				case Success(data): trace("success");
				case Failure(data): trace("fail");
			}
		});
	}
}
```
outputs 8200 lines of code alone, I'm presently not using DCE as i'm just running server tests at the moment so i'm not using release.hxml. Switching DCE on gets this down to 2500 LOC but a 75% increase is still unnecessary I don't need anything else tink has to offer in this project and the functionality is baked into the standard lib just not allowed to be used for some reason?

**Comment by Gama11** [comment]
Hm, it may be possible to do this without breaking the API once / if there's overload support.

**Comment by Jarrio** [comment]
It is possible with at least the std `HttpNodeJs.hx` implementation. I haven't actually read through the code but my current work around I manually changed the file and changed the definition of `request` to:

```haxe
public override function request(?post:Bool) {
	this.customRequest((post) ? Post : Get);
}

public function customRequest(method:HttpMethod) {}
```
This works for me and i've tested with GET/POST/DELETE so far but the change was minimal and I took no time to read what I was changing when I did it. But I just removed the condition forced in the `request` method, IIRC this is exactly how `sys.Http` does it but for some reason it's not present on the js side of things so I figured there must have been a reason for that?

**Comment by back2dos** [comment]
@Jarrio the choice is yours of course. Personally, I was worried about the numbers you gave, which even without DCE (which is an irrelevant metric in my book) are off by a factor. In the future, it might be nicer if you tried a bit harder not to post wrong data.

> the functionality is baked into the standard lib just not allowed to be used for some reason

The standard library aims for portability, sometimes at the expense of features. The main reason for not supporting other methods is historical. FlashPlayer doesn't support them, and neither does ActiveX. For better or worse, we still have a flash backend and [still support ActiveX](https://github.com/HaxeFoundation/haxe/blob/8616359ff7f1916e5275cf9d620e79837bc66025/std/js/Browser.hx#L116).

There are various ways to not make this a breaking change. Using `customRequest` is not one of them, because on most sys platforms it's already defined with a different signature. What's required is a non-breaking API extension, that will have to be implemented on all platforms that can support it (and ideally do something meaningful on platforms that don't) and also properly covered with tests. It's all possible and if you're still convinced it's a minimal effort, then perhaps instead of arguing you'll have better luck with a pull request ;)

**Comment by Jarrio** [comment]
> it might be nicer if you tried a bit harder not to post wrong data.

Apologies, I took the number from my github tracking after removing tink, but it does increase code size unnecessarily if all you want is to be able to define a standard http method.

> Flashplayer doesn't support them

In the standard library, flash doesn't even have a unique definition. At least in here it doesn't:  <https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Http.hx>

> Using customRequest is not one of them, because on most sys platforms it's already defined with a different signature.

I guess this is a fair reason, but the definition of `customRequest` isn't part of `HttpBase` so a different signature wouldn't cause friction *for the most part* but I can understand the point of view that if you want to "unify" the API's it should be uniform across all platforms - Which is exactly my point, sys should not be the only platform to implement this feature. 

> It's all possible and if you're still convinced it's a minimal effort, then perhaps instead of arguing

This is exactly what i'm trying to figure out, it evidently *seems* minimal effort and I would like to submit a PR but i'm assuming i'm wrong here and missing something. If it's as easy as just moving the conditional to `request` and adding `customRequest` then that wont take long at all. 

HttpMethod is already in the standard lib:
<https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/http/HttpMethod.hx> <https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/http/HttpNodeJs.hx#L83>
<https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/http/HttpJs.hx#L113:L120>
and moving these conditions wont take any longer than a few minutes but you mention that adding `customRequest` is not the way to go about this which is exactly what I was going to do. So if you could maybe elaborate on a better alternative I will happily go that route.

**Comment by back2dos** [comment]
> Which is exactly my point, sys should not be the only platform to implement this feature.

But `sys` doesn't implement this feature. On `sys` the `customRequest` actually there to allow streaming the message onto a `haxe.io.Output` - it solves an entirely different problem.

> So if you could maybe elaborate on a better alternative I will happily go that route.

You can:

1. pick an entirely new name, e.g. `requestWithMethod`
2. make an abstract that unifies with `Bool` and `HttpMethod`:
   
   ```haxe
   abstract HttpMethodOrBool(HttpMethod) from HttpMethod to HttpMethod {
     @:from static function ofBool(b:Bool):HttpMethodOrBool
       return if (p) Post else Get;
   }
   ```

   And then you go `function request(?method:HttpMethodOrBool):Void`. Technically, this is a breaking change, because the method will no longer unify with `?Bool->Void` but I wonder if anybody uses it that way.

3. Declare a method for every HTTP verb (`get`, `delete`, ... ). This is perhaps a bit awkward though.

**Comment by Jarrio** [comment]
I'm a fan of the abstract route, it seems to be the "neatest" option - but it will require changing the type from `HttpBase`. I'll experiment with this when I get a bit because this will also force the sys target api to change and I wasn't aware of the alternative functions `customRequest` had.

3 is definitely out 😂 and 1 is the "least damaging" but might not be the best approach

**Comment by nanjizal** [comment]
@Jarrio I am failing to see the point. Did you look at folderNode.communication.Https
You just need to adapt these two methods to your exact requirements.
``` haxe
    public function put( url: String, payload: Dynamic, pass: String ){
        var http = new XMLHttpRequest();
        http.onreadystatechange = function(){
            if( http.readyState == 4 ){
                if( http.status == 200 ){
                    var holder: THolder = haxe.Json.parse( http.responseText );
                    onLoad( holder );
                } else {
                    onError( Std.string( http.status ) );
                }
            }
        }
        http.open( "PUT", url, true );
        http.withCredentials = true;
        http.setRequestHeader( "Content-type", "application/json" );
        http.setRequestHeader( 'Authorization', 'Basic $pass' );
        http.send( Json.stringify( payload ) );
    }
    public function delete( url: String, id: String, pass: String ){
        var http = new XMLHttpRequest();
        http.onreadystatechange = function(){
            if( http.readyState == 4 ){
                if( http.status == 200 ){
                    onDelete( id );
                } else {                    
                    onError( Std.string( http.status ) );
                }
            }
        }
        http.open( "DELETE", url, true );
        http.withCredentials = true;
        http.setRequestHeader( "Content-type", "application/json" );
        http.setRequestHeader( 'Authorization', 'Basic $pass' );
        http.send();
    }
```
This is not just theoretical it has been tested in real use case from an electron application and should work for any similar common JSON api requiring PUT and DELETE. Further I setup Kha within the Electron application so it would be feasible to create nice graphic WebGL front end within Electron without having to use horrible html mark up, and css :), I expect full on armory3d should be feasible, could probably dig out some code.  But Electron is huge, I think if your worried about application size then avoid nodejs/electron totally!

[detail of shop to shop product transfer and manipulation](https://github.com/nanjizal/hxTShopify#details-of-shoppy-test)

You might be best off looking more closely at why your Tink approach is too bloated because tink is probably more suited for complex use cases, and likely possible to pair down if your willing to look inside.
