### ISSUE TITLE
[display] Find References is slow

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9095]
(just so we have a proper issue) after a210a2365d7dd71053c2c335d30530eaef4cd8dc, find references has become very slow (from 9 to 29 seconds on the first run and from 0.2 to 22 seconds on the second, when finding a commonly-used interface in our codebase)

**Comment by nadako** [comment]
as mentioned on Slack, it is much faster. still a little bit slower than before, especially for the second search (it was like 0.2s and now it's 1.3), but it's usable again \o/

**Comment by Simn** [comment]
Ideally, we would group all class fields so that whenever a member of the group is referenced, the reference is extended to all other members of the group too. However, this requires associating additional information with class fields, for which we don't have a straightforward solution at the moment.

**Comment by Simn** [comment]
See if that helped

**Comment by nadako** [comment]
It did! :)

**Comment by Simn** [comment]
I guess we can close this?
