### ISSUE TITLE
Is it possible to use third party java lib(s) in haxe src?

### ISSUE THREAD

**Issue by mrtinkz** [HaxeFoundation/haxe#9106]
Is it possible to use third party java lib(s) in haxe src?

1. I am planning to implement a common library in haxe and distribute in multiple targets (java, python, c#) but I would have to use a 3rd party java library not one but multiple.
2. Not sure if haxe supports interoperability or pretty much everything need to be written from scratch.
3. Can I convert the 3rd party libs from java to haxe?
4. What's the best way to proceed?

**Comment by Aurel300** [comment]
Are you asking if you can use Java libraries and compile them into Python and C#? No, you cannot. Haxe allows you to compile **Haxe code** to Java, Python, C#, etc. If you happen to be compiling to Java, then you can use 3rd party Java libraries, otherwise it doesn't make much sense – why would Python know how to use Java libraries?

And, as far as I know, there is no automated Java to Haxe converter. [java2haxe](https://github.com/Danielku15/java2haxe) seems to have been what you are looking for, but it is now severely out-dated and not maintained.

So either you write all the functions you need in Haxe yourself (i.e. port the Java libraries), or you find pure-Haxe libraries that do it, or you find a similar set of libraries for C# and for Python and use them as a back-end for an API that dispatches calls to them depending on the current compilation target.

**Comment by mrtinkz** [comment]
So you are saying that if the 3rd party libraries are available in (java, C# and python - all three of them) I should be able to point them individually in haxe and use those to build the src in haxe and compile them back.

The 3rd party libraries I am going to use are already available in (java, python & c#) so I am guessing I should be able to use them directly or you suggest to make api calls (which might not be an intended solution but I can think about it)

**Comment by mrtinkz** [comment]
Apologies if my questions are naive. Haxe is new for me.

**Comment by back2dos** [comment]
It all depends on the target:

- For java use `--java-lib path/to/the.jar` to add a jar file. Haxe compiler extracts signatures from this and should also provide autocompletion
- For cs use `--net-lib path/to/the.dll`, which works very similarly to jar support.
- For python you need to write externs with `@:pythonImport`. You can check out [examples from the std lib](https://github.com/HaxeFoundation/haxe/search?p=5&q=pythonImport&unscoped_q=pythonImport)

**Comment by RealyUniqueName** [comment]
I'm closing this as there seems to be no issue with the compiler.
Feel free to reopen if I'm wrong.
