### ISSUE TITLE
[std] haxe.macro.Context.getModule() throws exception instead of returning null

### ISSUE THREAD

**Issue by fal-works** [HaxeFoundation/haxe#9223]
Everyone else might know, but still.

### Ver

Haxe 4.0.5

### Current description

> Resolves a module identified by `name` and returns an `Array` of all
> its contained types.
> 
> The resolution follows the usual class path rules where the last
> declared class path has priority.
> 
> If no module can be found, `null` is returned.

### Repro

```haxe
class Main {
	static function getModuleTest() {
		final moduleName = "ModuleNameThatDoesNotExist";
		trace('Try to get module: ${moduleName}');
		try {
			final types = haxe.macro.Context.getModule(moduleName);
			if (types == null) trace("Returned null.");
		} catch (e:Dynamic) {
			trace("Exception caught.");
			throw e;
		}
	}
}
// cmd: haxe --macro 'Main.getModuleTest()'
```

```
Main.hx:4: Try to get module: ModuleNameThatDoesNotExist
Main.hx:9: Exception caught.
(unknown) : Type not found : ModuleNameThatDoesNotExist
```

### Should

Either
- Return null as stated, or
- Fix the doc (and maybe the exception should say "Module not found"??)

**Comment by Simn** [comment]
The documentation should be fixed here because `getModule` should behave like `getType`, which is documented to throw an exception.

**Comment by RealyUniqueName** [comment]
Changed the doc.

Internal exception raised is `Module_not_found`, but it's specifically set to be described as "Type not found":
https://github.com/HaxeFoundation/haxe/blob/fe5c3d17968f0428d5461194acc985aa8284bb8f/src/core/error.ml#L266
@Simn do we want to change that?

**Comment by Simn** [comment]
Probably not, but @nadako is the expert for this.

**Comment by nadako** [comment]
Well... I can only assume this is because originally this error was only(?) raised from _type_ loading procedures, and "we" wanted simplier error messages, so we get a simple "Type not found" message when trying to resolve "pack.InexistantType" instead of talking about modules (also because "normally" you have modules with main types). On the other hand, _inside_ the compiler we want an exception that tells us what exactly went wrong, thus `Module_not_found`. :)

**Comment by Simn** [comment]
Let's not change anything else here.
