### ISSUE TITLE
weird tempvaring

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9305]
> (extracted from #9296)

```haxe
class Main {
	static function main() {
		var a = 1;
		var b = () -> 1;
		function c() {
			f(a, b());
		}
	}

	static function f(arg1:Int, arg2:Int) {}
}
```

generated js:

```js
var a = 1;
var b = function() {
	return 1;
};
var c = function() {
	var c = b();
	Main.f(a,c);
};
```

There are two issues with this:

 * The `b()` call is stored in a temp var for no apparent reason.
 * Even if the temp var is needed, its name (`c`) is confusing. I would expect it to be named after an argument (`arg2`).

This is important in the context of #9035

**Comment by RealyUniqueName** [comment]
According to the code of analyzer that happens because `a` is a captured variable:
https://github.com/HaxeFoundation/haxe/blob/f9a7e541fdc8451d3ff20f5175f364c667dd21db/src/optimization/analyzerTexpr.ml#L863-L864
I checked and this condition is evaluated to `true` because `a` has `v_capture = true`.

And it's actually a bug.
Consider this sample:
```haxe
class Main {
    static function main() {
        var a = 999;
        var b = function() {
            a = 123;
            return a;
        }
        f(a, b());
    }

    static function f(arg1:Int, arg2:Int) {
        trace(arg1, arg2);
    }
}
```
this is expected to print `999, 123`, but it prints `123, 123`, because analyzer changes the order of the access to `a` and the call to `b`.
And it happens even without `-D analyzer-optimize`.

**Comment by Simn** [comment]
This is a problem with the initial transformation of the call. The second argument is moved out as a temp var, but the first one remains even though it can be affected.

This is probably a more general problem with the affection checker. With any luck it's just a missing `v_capture` check there that then also fixes some as of yet undiscovered inlining issues (and makes Nicolas complain about temp vars).

**Comment by Simn** [comment]
I don't really understand why, but a unit.js diff suggests that there are actually _less_ variables now.

**Comment by nadako** [comment]
Indeed, the original example now generates:
```js
var c = function() {
	Main.f(a,b());
};
```
even without `-D analyzer-optimize`

**Comment by Simn** [comment]
I double-checked this again with `@:analyzer(full_debug)` to make sure I'm not crazy, but it looks exactly how we want it to.

Initial:

```haxe
function() {
        var a<6187> = 1;
        var b<6188> = function() {
                return 1;
        };
        var c<6189> = function() {
                Main.f(a<6187>, b<6188>());
        };
}
```

After transformation:
```haxe
function() {
        var a<6187> = 1;
        var b<6188> = function() {
                return 1;
        };
        var c<6189> = function() {
                var a<6637> = a<6187>;
                var c<6638> = b<6188>();
                Main.f(a<6637>, c<6638>);
        };
}
```

Note how both arguments are temp-varred out, which is what we want at this stage. The only weird part is that the variable for `b` is named `c`...

After fusion:

```haxe
function() {
        var a<6187> = 1;
        var b<6188> = function() {
                return 1;
        };
        var c<6189> = function() {
                Main.f(a<6187>, b<6188>());
        };
}
```

Fusion is also correct:

1. `var a<6637> = a` is rejected because the `b()` call is in the way.
2. `var c<6638> = b()` is accepted. Only `a<6637>` is in the way and that's a normal variable which cannot be affected by the `b()` call.
3. `var a<6637> = a` is accepted now because the `b()` call has moved past the appearance of the `a` argument.

I also checked the C++ output where the evaluation order of call arguments is undefined. Step 3 is rejected there for that reason, so the output becomes:

```haxe
		var c = function() {
			var a1 = a;
			Main.f(a1, b());
		};
```
