### ISSUE TITLE
[ide] Addressing the multiple errors problem

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#9317]
There a few things that keeps annoying me regarding IDE integration.
Sadly, for some of them there's nothing we can do expect wait for VSCode to give us enough control over the Problems.

One however we can do since we control the compiler is the following:

This kind of error:
![image](https://user-images.githubusercontent.com/1022912/79424592-aceec900-7fc0-11ea-8258-a1c29562d49f.png)

Will turn into this single problem:

![image](https://user-images.githubusercontent.com/1022912/79424658-c6901080-7fc0-11ea-8382-4c99a6368752.png)

That's very annoying since you have to go back to the terminal view in order to get information about the actual type that was required or even actual error.

I suggest we deal with it by passing some env var to the compiler when run from VSHaxe, so it changes its output by grouping same-position error messages into a single message.

**Comment by ncannasse** [comment]
Putting that for 4.1 so it can be discussed quickly, it's not a big fix once we agree on the way to handle it.
CC @Gama11

**Comment by Gama11** [comment]
Actually, VSCode's custom task execution API has been finalized for a bit now, which means we could experiment with parsing Haxe error messages ourselves instead of relying on regex problem matchers. We would then have to report them as diagnostics and manage that diagnostics collection ourselves.

Unfortunately, even in that case the compiler currently doesn't output enough information to tell which line is an actual error message and which ones are merely "related information" for another one. The only way I see to do that right now would be to hardcode certain prefixes, such as `error.startsWith("For function argument")`. Any ideas how to improve this - something a parser could detect reliably? Maybe related error starting with `- `  or similar?

Alternatively we could look into adding a `compile` method to the JSON-RPC API, and Haxe would then return errors to the IDE in a structured way. This would likely require a fairly big refactor in how Haxe deals with error messages though, apart from having to design the JSON-RPC method, since I don't think Haxe actually knows what error messages are related to each other internally either. This approach would probably be the most work but also the least flexible, since it only works if we can call Haxe directly (a lot of frameworks like Lime do it indirectly).

**Comment by RealyUniqueName** [comment]
Note that we have error messages, which span across multiple positions:
```
Child.hx:12: Field foo has different @:native value than in superclass
Parent.hx:34: Base field is defined here
```
I think the right way is to group messages on the compiler side. Otherwise IDEs may need an update every time a new error kind is introduced in the compiler.

**Comment by Gama11** [comment]
@RealyUniqueName I know, but IDEs would be able to parse it if it looked like this:

```
Child.hx:12: Field foo has different @:native value than in superclass
Parent.hx:34: - Base field is defined here
```

VSCode's "related diagnostic information" does support additional positions.

**Comment by Gama11** [comment]
The more I think about it, the more I'm convinced that a compiler API is not going to work - most of the time, tasks don't call Haxe directly, but through Lime, Kha, NME, vshaxe-build... Even a `haxe --run` script that calls `haxe` via `Sys.command()` or similar would break it. I think we need to parse the error messages from stdout / stderr.

**Comment by ncannasse** [comment]
> Actually, VSCode's custom task execution API has been finalized for a bit now, which means we could experiment with parsing Haxe error messages ourselves instead of relying on regex problem matchers. We would then have to report them as diagnostics and manage that diagnostics collection ourselves.

Oh please yes :D That would also solve the out-of-order messages (messages that gets sorted by line number instead of as reported by the compiler)

**Comment by ncannasse** [comment]
> Note that we have error messages, which span across multiple positions:

Yes I agree, this is another annoying thing, since vscode currently group _and sort_ by file/line without caring at all about the compiler order.

**Comment by Gama11** [comment]
>That would also solve the out-of-order messages

Not sure it would, it's still the same problems UI even if you're using the diagnostics API.

**Comment by ncannasse** [comment]
So. What's the actual plan for it ? Compiler support ? IDE Support ? Both ? ;)

**Comment by Gama11** [comment]
- The env var to merge messages as you suggested might be a quick and easy short term solution for at least part of the problem.
- Eventually I want to look into the new API as mentioned, but not sure when I'll get to that / how much work that's going to be.
    - This approach requires the compiler to change how it outputs error messages that are just additional information for others, like an additional position. Maybe simply prefixing those messages with a `-`? That could make it easier to "parse" for humans too.

**Comment by RealyUniqueName** [comment]
I like the idea of prefixing sequential messages. But maybe with something like `+`, `&` or `>` to hint the relation "syntactically".
```
Main.hx:12: Something is wrong
Another.hx:34: + Additional info here.
```
or
```
Main.hx:12: Something is wrong
Another.hx:34: > Additional info here.
```

**Comment by Simn** [comment]
I'm removing the 4.1 label because I can't see us dealing with this quickly in any way.

**Comment by ncannasse** [comment]
I think we should be able to come up with a solution that works and is quite easy to implement, maybe this could be discussed on #ide ?
