### ISSUE TITLE
[eval] Invalid_argument("String.sub / Bytes.sub")

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#9333]
When targeting eval (--interp -D eval-stack) the following fails:
```haxe
class Test {
   public static function main() {
       new EReg("b", "").matchSub("aba", 0, -1);
   }
}
```

```
Invalid_argument("String.sub / Bytes.sub")
```

I tried haxe 4.0.5 and nightly build.
All other targets work.

**Comment by Simn** [comment]
The documentation says:

> This function expects pos and len to describe a valid substring of s, or else the result is unspecified. To get more robust behavior, this.match(s.substr(pos,len)) can be used instead.

My understanding of that was that a length of -1 is not a valid substring.

However, if this works on all other targets then I'll comply in eval as well.

**Comment by sebthom** [comment]
Thanks for changing it.

What confused me regarding the docu is that the method signature is defined as:
```haxe
matchSub(s:String, pos:Int, len:Int = -1):Bool
```
Where the default value of `len` is `-1` - which kind of implies that providing -1 must also be a valid value.

**Comment by Simn** [comment]
Well, now I'm confused too. The Java implementation does this: `len < 0 ? s : s.substr(0, pos + len)`. So for any negative `len` it would take the entire string, otherwise a substring.

Now I'm not sure what the specification is in the first place and how it relates to `substr`. I also thought that a negative length on that one had defined semantics, but according to the documentation that's unspecified as well.
