### ISSUE TITLE
Regression: enough inlining thwarts ECheckType

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9355]
Consider the following marvel:

```haxe
class Main {
  static inline function output(s:String)
    trace(s);

  static inline function writeFloat(f:Float)
    output(Std.string((f:Float)));

  static inline function writeFloatDirectly(f:Float)
    trace(Std.string((f:Float)));

  static function main() {
    var o:Opacity = .5;
    writeFloat(o);
    writeFloatDirectly(o);
    output(Std.string((o:Float)));
  }
}

abstract Opacity(Float) from Float to Float {
  @:to public function toString():String
    return 'huh?';
}
```

In 4.0.5 this outputs:

```
Main.hx:3: 0.5
Main.hx:9: 0.5
Main.hx:3: 0.5
```

In 031345d (latest available nightly at the time of writing this):

```
Main.hx:3: huh?
Main.hx:9: 0.5
Main.hx:3: 0.5
```

**Comment by RealyUniqueName** [comment]
This turned out to be quite involved.
The real issue is not a check-type being removed (`(valueOfFloat:Float)` should be safe to eliminate), but a filter,which inserts abstract casts.
Reduced:
```haxe
class Main {
  static inline function writeFloat(f:Float)
    trace(Std.string(f)); 

  static function main() {
    var o:Opacity = .5;
    writeFloat(o);
  }
}

abstract Opacity(Float) from Float to Float {
  @:to public function toString():String
    return 'huh?';
}
```
The `writeFloat(o)` call gets inlined as `var f:Float = o; trace(Std.string(f));` and reduced to `trace(Std.string(o))`, which is correct.
But then [AbstractCasts.handle_abstract_casts](https://github.com/HaxeFoundation/haxe/blob/86c5241/src/context/abstractCast.ml#L239) filter kicks in and changes it to `trace(Opacity.toString(o))`

Making inliner to not substitute `f` with `o` (if their types don't match) breaks quite a few tests.
Making inliner to substitute `f` with `cast o` is wrong, because it results in expressions like `f += value` being generated as `cast o += value`.

I think inliner does its job correctly. The wrong part is the `handle_abstract_casts` inserting additional casts after typing process is finished.
Any ideas?

**Comment by RealyUniqueName** [comment]
I failed to find a good solution.
But since it affects only `Std.string` calls (see #2401 and [related commit](https://github.com/HaxeFoundation/haxe/commit/27e464a2e1e76b9dda0d9997ecc0f59d43ace9c9)) I'll make a PR with a small hack.
