### ISSUE TITLE
Constraint check error position is not accurate

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9393]
In the example above, the "constraint check failure" error will be reported at the position of `f` (not even the call). I think I understand why that's happening (it's checking the field itself, not really a call argument, right?), but maybe it is possible to store a position of a thing that made T an actual type (`1` in this example).

```haxe
class Main {
	static function f<T:String>(v:T) {}
	static function main() {
		f(1);
	}
}
```

**Comment by Simn** [comment]
IMO this is not worth fixing. Addressing this in the general case (where there's no 1:1 mapping between argument and type parameter) would require quite a bit of effort which I don't think is justified.

It can probably be changed to give the error of the call as a whole instead of the field, but trying to map this to individual arguments seems pretty crazy.

**Comment by nadako** [comment]
Is this `test-needed` or it's covered by position changes in existing tests?

**Comment by Simn** [comment]
I figured that this was covered by the other tests where the position became more narrow.
