### ISSUE TITLE
[cpp] Regex inconsistent behaviour

### ISSUE THREAD

**Issue by jskuse** [HaxeFoundation/haxe#9500]
Recently upgraded a project to Haxe & HXCPP 4.1.1 and have found an issue with a previously fine regex not matching correctly, I've checked this against other targets and it seems to behave how I would expect:

```haxe
// broken
trace(~/[A-Za-zÀ-ÖØ-öø-ÿ0-9]+/.match("a")); //cpp false, js true, hl true
// u flag was previously required on cpp for unicode, but doesn't seem to make any difference 
trace(~/[A-Za-zÀ-ÖØ-öø-ÿ0-9]+/u.match("a")); //cpp false, js true, hl true

// fine
trace(~/[A-Za-z]+/.match("a")); // cpp true, js true, hl true
trace(~/[A-Za-zÀ-ÖØ-öø-ÿ0-9]+/.match("ö")); // cpp true, js true, hl true
```

**Comment by tobil4sk** [comment]
This issue was related to hxcpp's smart string functionality. This has been fixed in https://github.com/HaxeFoundation/hxcpp/pull/1037, and there is a now a test for this bug [in the hxcpp repo](https://github.com/HaxeFoundation/hxcpp/blob/96f5f9a69744e5fd07717e5af9d5b45bd3a8890a/test/std/Test.hx#L242-L254).

**Comment by Simn** [comment]
I'll assume that this can be resolved by updating hxcpp even on older Haxe version.
