### ISSUE TITLE
[PHP] Dynamic manipulation

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#9524]
Hej !

I get a headache today with that : 
```haxe
var o : { v : Dynamic } = { v : false };
var o2 : { v : Dynamic } = { v : true };
var v	= o.v;
var v2	= o2.v;
throw o.v + ":" + v + "#" + o2.v + ":" + v2; // false:#true:1
```
Why it shows true and 1 for the same value and why for false there is an empty string please ?

**Comment by RealyUniqueName** [comment]
If you check the generated code you'll see:
```php
$o_v = false;
$o2_v = true;
$v = $o_v;
$v2 = $o2_v;
throw HaxeException::thrown(\Std::string($o_v) . ":" . ($v??'null') . "#" . \Std::string($o2_v) . ":" . ($v2??'null'));
```
`o.v` and `o2.v` go through `Std.string`, because they are typed as `Dynamic`. And `Std.string` follows Haxe semantics (which is `"false"` for `false` and `"true"` for `true`).
But `v` and `v2` don't infer `Dynamic` (that's the rule in Haxe: `Dynamic` is never infered), instead their types become [monomorphs](https://haxe.org/manual/types-monomorph.html). And later upon string concatenation their types morph into `String`. That's why compiler doesn't  generate `Std.string` for them. That triggers native PHP stringification semantics at runtime, which is an empty string for `false` and `"1"` for `true`.

**Comment by RealyUniqueName** [comment]
General advice: 
Avoid `Dynamic` or at least try to type-hint it as soon as possible.

**Comment by filt3rek** [comment]
Thanks Aleksandr for the explanation.
I know I avoid most time Dynamic but here I can't it's a tools class and I deal with dynamic values.
I've compared the same thing in JS and I get `false:false#true:true` so I thought it should be the same thing.
At the end I don't know, will it be let like that or should it give also `false:false#true:true` in PHP target ?

**Comment by RealyUniqueName** [comment]
Current behavior is correct.
You can workaround that by adding type hints to `var v` and `var v2`:
```haxe
var v:Dynamic	= o.v;
var v2:Dynamic = o2.v;
```

**Comment by filt3rek** [comment]
Yes that's what I've done.
But it's strange to have differences between targets...

**Comment by RealyUniqueName** [comment]
Nothing to do here.
