### ISSUE TITLE
unify_min vs constructor references

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9579]
It would be neat if the following works:

```haxe
class Main {
	static function main() {
		final makeThing = if (Math.random() > 0.5) A.new else B.new;
	}
}

class Base {
	public function new(i:Int, f:Float, s:String, b:Bool) {}
}

class A extends Base {}
class B extends Base {}
```

![image](https://user-images.githubusercontent.com/2620907/84590844-304e5e80-ae3a-11ea-9fbd-4508b09e794d.png)

Note that this already works when calling the respective constructors in the branches.

**Comment by Simn** [comment]
This requires a special case for `TFun`, similar to what's already done for `TAnon`. We have to be careful with unification here because function arguments are contravariant, which means we don't want the most generic type, but the most specific one.

The algorithm would roughly be:

1. If the first type isn't `TFun`, fail.
2. Otherwise, create an array of its argument types.
3. Also create a list of its return type.
4. For each subsequent type:
    1. If it's not `TFun` or if the arity doesn't match, fail.
    2. Otherwise, for each argument type:
        1. If the new type is assignable to the old one, replace it because it is more specific.
        2. Otherwise, if the old type is assignable to the new one, keep it.
        3. Otherwise, fail.
    3. Append the return type to the list.
5. Unify-min the list of return types.
6. Return the function type consisting of types in the argument array and the result of the return type unify-min.

Sounds like fun!
