### ISSUE TITLE
[PHP] Reflect.fields() inverse order

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#9667]
Hej !

I don't know if it's an error or if it depends just of the target and it's not the same order and it's like that but doing `Reflect.fields` evaluates inverse order in PHP than in JS.

**Comment by nanjizal** [comment]
### order is not specified.

But you could manually adjust it for PHP or Javascript, as they not defined in Ocaml they are all in the **std** code and there seems many entry points eg:
https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/haxe/ds/ObjectMap.hx#L83

With a search and replace within of **std.js._std** try changing **push** for **unshift** ?

I expect since order is probably not specified in Javascript ( and it may differ in different implementations rhino etc..) and since Haxe has # code for es6 which may or may not have the same order. 

Also potentially changing something as simple as **push** for **unshift** may have performance consequences, and if they were negative then I doubt that would be acceptable.

An **unshift** _switch-a-roo_ would need extensive testing and likely would still not guarentee consistant ordering, I think likely low priority but it is something I did ask about on discord with little interest, but I would be curious if you do some testing.

For a specific use case such as fast simple decoding between JS and PHP, or code generation it maybe better to implement your own Abstract around a class with an alternate implementations?

**Comment by RealyUniqueName** [comment]
I don't think order is specified in `Reflect.fields`.
However there was an issue of invalid order of evaluation for fields init expressions in object declarations.
