### ISSUE TITLE
Transititve casts for interfaces

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#9752]
The following worked in 4.1.2, but not anymore in 4581cae:

```haxe
class Main {
	static function main() {
		var buffer:Future<AssertionBuffer> = null;
		var assertions:Assertions = buffer;
	}
}

interface IFuture<T> {}

abstract Future<T>(IFuture<T>) from IFuture<T> to IFuture<T> {}

@:transitive
abstract Assertions(Stream<Assertion>) from Stream<Assertion> to Stream<Assertion> {
	@:from
	public static function ofFutureAssertions(p:Future<Assertions>):Assertions return null;
}

interface IStream<T> {}

abstract Stream<T>(IStream<T>) from IStream<T> to IStream<T> {}

class Assertion {}
class SignalStream<T> implements IStream<T> {}


abstract AssertionBuffer(SignalStream<Assertion>) from SignalStream<Assertion> to Assertions {}
```

Apparently `AssertionBuffer(SignalStream<Assertion>)` is the key, changing the underlying type to `Stream<Assertion>` or `IStream<Assertion>` would make it work.

**Comment by vonagam** [comment]
This is not a transitivity issue, but a variance issue. 

Let's look at what unification path here is expected:
```
Future<AssertionBuffer> -> Future<Assertions> -> Assertions
```
First arrow is variance (only type parameters have changed), second is an implicit field abstract cast. Since there is only one abstract cast in the chain it can work without `@:transitive` meta. 

What's the problem then? Let's look on first arrow in terms on underlying types:
```
Future<AssertionBuffer> -> Future<Assertions>
=
IFuture<SignalStream<Assertion>> -> IFuture<IStream<Assertion>>
```
As underlying types are not equal for this to work `IFuture` has to support covariance (class `SignalStream` to an interface `IStream`, from more specific to less) on first type parameter. Which it does not. 

What happens if we, as mentioned, replace underlying type of `AssertionBuffer` from `SignalStream<Assertion>` to `Stream<Assertion>` (or `IStream<Assertion>` as it is what streams underlying value is)?
```
Future<AssertionBuffer> -> Future<Assertions>
=
IFuture<IStream<Assertion>> -> IFuture<IStream<Assertion>>
```
They become equal and everything works. So before (in 4.1.2 for example) when underlying types were used directly an expected error was present, but when both sides were wrapped in abstracts some checks were skipped and one could get (unknowingly) covariance to work (as in this example).

Now underlying equality checks are always made and those uncontrolled covariance licenses are rewoked.

**Comment by kevinresol** [comment]
Thanks for the detailed explanation!  That's really helpful. Now i wonder what is the syntax to allow covariance on the type parameter of IFuture?

**Comment by vonagam** [comment]
There is none... Covariance/contravariance is supported only for structures for now. 
Here is relevant issue to subscribe - #9611.
