### ISSUE TITLE
[Lua] -D lua_vanilla still generates extern lib requiements

### ISSUE THREAD

**Issue by kevansevans** [HaxeFoundation/haxe#9798]
I'm currently experimenting with a project utilizing the lovr engine. The page for getting started with Lua explains that this is fine as using ``-D lua_vanilla`` in my compile should exclude generating required libs. However with this code I have here:

```import hxdoom.Engine;
   import lovr.Lovr;

   class Main 
   {
	public static var hxdoom:Engine;
	static function main() {
		Lovr.load = function(args) {
			hxdoom = new Engine();
		}
	}
   }
```
```
-cp src
-D lua_vanilla
--library lovr
--library hxdoom
-main Main
-dce full
-lua bin/lua/Main.lua
```
Generates this line in the Main.lua ``__lua_lib_luv_Misc = _G.require("luv")`` [Main.lua (lines 244 and 801)](https://github.com/HaxeFoundation/haxe/files/5023869/Main.txt)

"luv" appears to be an external lib https://github.com/luvit/luv

I'm using the externs generated by this haxe project: https://github.com/excessive/lovr-haxe-wrappergen and setting them to a dev haxelib, and the git version of hxdoom as a dev library https://github.com/kevansevans/HxDoom/tree/master/library

Included source and .hxml file [lua_example.zip download](https://github.com/HaxeFoundation/haxe/files/5023861/lua_example.zip)

**Comment by jdonaldson** [comment]
The `lua_vanilla` avoids imports for low level types (mainly bit and utf8 libraries).  If you include other haxe standard libraries, you can still wind up with imports.

My guess is that Lovr/hxdoom is using some sys (file system/os) functionality, and it's causing the import of luv (which I use for most sys functionality, since Lua does not provide this by default).

The way to work around this is by finding which libraries form luv are getting imported and used (and why).  My guess is that there's some helper libraries available through lovr, and these can be used instead.  My process there would be to write a full extern for lovr, and then use the extern to implement the relevant base Haxe std lib classes (e.g. FileSystem, Sys, etc).  

I realize this is not necessarily easy for a beginner to do, but it's not terribly difficult with a little experience, and you can look at other relevant Haxe/lua libraries to see how it's done.  

Also, FWIW, the `lua_vanilla` keyword will be deprecated soon, but the functionality will be available through other keywords that selectively disable certain third party library functionality (in favor of pure lua implementations).

**Comment by jdonaldson** [comment]
I'm closing this for now, but I'm happy to continue chatting about this, I've done a number of things to support Lua development, but there's a lot of various libraries out there with very opinionated implementations.  It's tough to strike a balance with "default" behavior in some cases.

**Comment by kevansevans** [comment]
Thank you, I appreciate the response. I'll give a poke through my libraries and what gets generated for lovr and get the fixes to the right people, and get back to this when I find something.

I do think it's a bit misleading, though, that if these flags are expected to turn off all dependency generation, that it still ends up making dependency code. I think a great addition to help devs avoid this hiccup is if the compiler were to throw errors whenever the dev uses a package that absolutely can't be used without a lua dependency if it's been flagged to not generate.

**Comment by kevansevans** [comment]
Got some time to poke around, and my library had an unused Haxe.timer in one of it's classes. Thank you for the help!

**Comment by jdonaldson** [comment]
That's great news, glad there's a workaround!

I agree that it's misleading.  Lua is such a limited language that even primitive Haxe types (strings, mainly) require special externed libraries to work properly.  A simple "hello world" app in Haxe can import many such libraries in Lua.  The Lua vanilla mode is designed to not require additional libraries unless they are specifically requested (via an import, etc).  This still can lead to some confusion, so I'll try a more fine-grained approach towards supporting the necessary behavior.
