### ISSUE TITLE
StoreTypedExpr of @:native enum entry

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#9812]
Follow up #9806

```haxe
// Main.hx
class Main {
	static function main() {
		trace(Foo.Baz); // Good: Generates `Foo.BAR`
		trace(Macro.store(Foo.Baz)); // Bad: Generates `Foo.Baz`
	}
}

extern enum Foo {
	@:native('BAR') Baz;
}

// Macro.hx
import haxe.macro.Context;

class Macro {
	public static macro function store(e) {
		return Context.storeTypedExpr(Context.typeExpr(e));
	}
}
```

**Comment by RealyUniqueName** [comment]
The issue is enum fields are not passed to macros by reference unlike fields of other types.
So, upon decoding an enum field back from macros into compiler a new `tenum_field` instance is created instead of fetching existing field from `tenum`. And then upon applying `@:native` names to types and fields such macro-decoded enum fields are missed.
I replaced decoding with fetching the field by name from the enum.
One downside of this approach is that if a macro changes enum field name then `store_typed_expr` would fail. But other than that `haxe.macro.EnumField` behavior is more consistent with `haxe.macro.ClassField` now (in a sense that any changes to `ClassField` in a macro are not reflected in generated code).
