### ISSUE TITLE
Option to use static extension with implicit casts

### ISSUE THREAD

**Issue by xm75** [HaxeFoundation/haxe#9847]
Adding something like @:using could fix the current incompatibility between the static extensions and implicit casts.

This is related to: https://github.com/HaxeFoundation/haxe/issues/5924

**Comment by RealyUniqueName** [comment]
Please elaborate. Preferably with code samples.

**Comment by xm75** [comment]
When used, this option would make the static extension and implicit casts work the same way as before #5924.

Something like this:

```
@:forward
abstract X(MyType) {

    @:from
    @:using
    static public function fromA(a:A) {
        return cast a;
    }
  
    @:to
    @:using
    public function toA():A {
      return cast this;
    }
}
```

Maybe there are better solutions, but it's pretty inconsistent that now this things can't be compatible.

**Comment by Simn** [comment]
That would be pretty awkward to implement because we usually distinguish expression-based unification from typed-based unification purely by context. With something like this we would have to try the expression-based approach and if we come across a casting field that isn't marked with `@:using` we would have to fall back. And that also raises more questions, like should the fallback attempt to find _other_ casting fields which might have a `@:using` or should it go straight to type-based unification?

I wonder if we should instead simply always use expression-based unification for anything that is brought into context via `@:using`. But somebody has to think that through as well.

**Comment by Simn** [comment]
This would have to go through haxe-evolution.
