### ISSUE TITLE
Array<Int64> contains() 

### ISSUE THREAD

**Issue by davzrm** [HaxeFoundation/haxe#9888]
Hello, 

Was running some tests until I ran into a problem. 
```
import haxe.Int64; 

var tempArray : Array<Int64> = [ 1 ];
trace(tempArray.contains(1));   // returns false
trace(tempArray.indexOf(1)); // returns -1
```
The trace returns false. 

Just wanted to ask if this was intended. 
I'm not sure if this is the right place to post this though, sorry.

**Comment by RealyUniqueName** [comment]
On some targets `haxe.Int64` is implemented on top of an object with two fields: higher order bits and lower order bits. So, when you define two `haxe.Int64` values like `var a:Int64 = 1; var b:Int64 = 1;` these are physically different objects at runtime. A comparison `a == b` holds because the compiler knows both `a` and `b` are `haxe.Int64` and it substitutes the comparison with an operator overloading method call.

But `Array.indexOf` and `Array.contains` are generic functions which are not aware of `haxe.Int64` semantics because the compiler does not know what would be the types of arguments at runtime when compiling the inner code for `indexOf` and `contains`. And expression `[a].contains(b)` yields `false` because `a` and `b` are different objects and they are compared by reference inside of `Array.contains`.

I doubt we can change that for methods of `Array`. But you can have a class with `Int64`-related tools.
For example:
```haxe
class Int64Tools {
  static public function containsInt64(a:Array<Int64>, value:Int64):Bool{
    for(v in a) if(v == value) return true;
    return false;
  }
}
```
```haxe
using Int64Tools;

class Main {
  static function main() {
    var arr:Array<haxe.Int64> = [ 1 ];
    trace(arr.containsInt64(1)); // true    
  }
}
```

**Comment by davzrm** [comment]
I see. 

Alright, I guess I'll go with the extension then. 

Thanks!
