### ISSUE TITLE
[ide] no documentation for @:structInit fields

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9956]
```haxe
@:structInit class C {
	/** hello **/
	var x:Int;
}

function main() {
	var c:C = {};
}
```

![image](https://user-images.githubusercontent.com/49749/99060458-5a01e200-25a0-11eb-8ae5-d4da7ea07236.png)
![image](https://user-images.githubusercontent.com/49749/99060479-625a1d00-25a0-11eb-9433-7b4fbbdb6294.png)

This is a tricky one. I think it's because the completion here is actually for the (generated) constructor arguments, and arguments cannot currently have their own documentation.

I guess one solution would be to introduce "argument documentation" internally and set it from field documentation for the generated arguments, but I'm not sure how big would be the impact of this, also performance/memory wise. If we do that though, then in future we could also extract argument documentation from `@param` tags to provide some nice hover hints for arguments. :)

**Comment by Simn** [comment]
In the bigger picture it seems really silly that we generate a constructor from the class fields only to then extract the fields from the constructor arguments...

**Comment by Simn** [comment]
I'm thinking that instead of creating fake class fields in `get_struct_init_anon_fields`, we can simply iterate the constructor argument names and look up the real fields on the class + its parent classes.

**Comment by nadako** [comment]
> In the bigger picture it seems really silly that we generate a constructor from the class fields only to then extract the fields from the constructor arguments...

I don't think it's silly, because it's actually a feature: if you have a hand-written constructor - its arguments will also be used for `@:structInit` instead of fields, allowing for more control and things like initializing only specific fields. It's kinda like named arguments :)

**Comment by Simn** [comment]
There are two levels here:

1. A fix specific to auto-generated `@:structInit` could simply extract the actual class fields from the class (and potential parent classes) and use these for displaying. This would retain all the information present on the class fields, and is quite easy to implement.

2. A more general solution is `@param` handling, in which case auto-generated `@:structInit` constructors would get documentation from which argument-specific information can be extracted. This would solve the issue here as a subset, but is much more difficult to implement:

* We need a javadoc parser.
* We have to figure out where and when to extract and (possibly) store the argument-specific information.
* We have to find a way to actually get this information in the right place, which is going to affect `unify_field_call` in some way. The problem here is that call argument handling is type-based, so all we really have is the `(n,o,t)` tuple. This could be extended, but I'm reluctant to make such changes to such a central function. An alternative might be to let `unify_call_args` do its thing and then get `unify_field_call` to augment the display information.

**Comment by Simn** [comment]
Note to self: This might also be related to signature display, where we also have to deal with specific arguments in the context of their call. Maybe this is a huge cleanup opportunity because the signature handling code really sucks things that I shouldn't mention on GitHub.

**Comment by Simn** [comment]
Some notes from my stream today:

* I have to learn how to use the new `cf_doc`.
* `get_struct_init_anon_fields` somehow enters the wrong branch where `cf_expr = None`. Probably some typing order issue.
* We need a javadoc parser.
* The hover case is related to #7802.

**Comment by Simn** [comment]
@RealyUniqueName Could you check how to get generated `@:structInit` constructors to inherit the documentation of super constructors? I'm testing with this:

```haxe
@:structInit
class Parent {
	/**
		This is y
	**/
	var y:String;
}

@:structInit
class Child extends Parent {
	/**
		This is x
	**/
	var x:Int;
}

function main() {
	var c:Child = {};
}
```

When requesting completion inside that `{}` we get documentation for `x`, but not for `y`. I tried calling `build_class_field_doc` on the generated constructor, but that didn't have any effect. Not sure if this is some typing pass problem or if I'm just not using this `@:inheritDoc` mechanism correctly.
